### ISSUE TITLE
配色方案

### ISSUE THREAD

**Issue by zaqzrh** [osfans/trime#10]
鍵盤：
# 鍵盤背景顏色、鍵盤背景圖片
# 鍵位背景顏色(字符鍵和功能鍵)
# 前景字符顏色
# 鍵位按下的顏色

；
狀態欄(輸入候選欄)參照小狼毫weasel.yaml：
# 輸入碼大小和顏色
# 第一候選的顏色和背景色
# 非第一候選的顏色和背景色
# 反查碼顏色

；
舊事重提，給個題目，有沒有答案不緊要。

**Comment by osfans** [comment]
好啊，你幫忙設計啊

**Comment by zaqzrh** [comment]
等我會設計，可能太陽已落山，放出了，等有緣人吧。

**Comment by osfans** [comment]
你參考weasel.yaml設計語法啊，我管實現。

**Comment by zaqzrh** [comment]
自定義配色方案，由開發者osfans開發完成！
