### ISSUE TITLE
bilibili發彈幕時，候選條爲空

### ISSUE THREAD

**Issue by osfans** [osfans/trime#100]

**Comment by mrhso** [comment]
不過我一切正常，得證實一下。

**Comment by xiaoqun2016** [comment]
安卓4.4未见此问题。

**Comment by iaoiezaon** [comment]
不僅bilibili，很多視頻類軟件發彈幕時都有這個問題。

**Comment by osfans** [comment]
感覺是這個錯誤：

E TextureVideoView: run into mSurfaceTexture == savedSurfaceTexture, should create new TextureView for new TextureMediaPlayer?

**Comment by YazidLee** [comment]
是的，所有全屏发送弹幕的软件都会出现这个问题，如bilibili，斗鱼，熊猫TV等

**Comment by Bambooin** [comment]
#317

**Comment by Bambooin** [comment]
Fix in #462
Daily build can be found for test and verify
https://github.com/osfans/trime/actions
