### ISSUE TITLE
实体键盘无法呼出输入法

### ISSUE THREAD

**Issue by ThreeIce** [osfans/trime#1001]
**Describe the bug**
如题，使用版本3.2.11，使用效果如同没有安装输入法
3.1.3正常
3.2.10可以输入中文，但也无法呼出输入法面板
使用设备为Matepad Paper，系统为鸿蒙2.0
**To Reproduce**
Steps to reproduce the bug:
4. See bug

**Expected behavior**

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi Mix 4]
 - OS: [e.g. Android 11]
 - Theme: [e.g. Tongwenfeng]
 - Version: [e.g. 3.2.1]
 - Build info: 
   ```
   You could find build info in About Activity and click it to copy.
   e.g. 
   Build: Commit CI
   Date: 2022-06-12 10:09 UTC
   Commit: v3.2.6-58-gd9b4c1f, 2022-06-12 17:58:14 +0800
   Branch: develop
   Repository: https://github.com/osfans/trime
   ```
**Additional context**

**Comment by deorth-kku** [comment]
我有一样的问题。
>使用版本3.2.11，使用效果如同没有安装输入法  

3.2.11并不是如同没有安装输入法，而是按键映射错乱，a-z直接上屏输入字母，而数字1-6被映射成了输入码xyzuvw，空格是输入码d
>3.2.10可以输入中文，但也无法呼出输入法面板  

确实如此，但我可以在系统层面开启“连接实体键盘时显示屏幕键盘”，这样起码能看到候选条。

**Comment by wblzz** [comment]
我的设备是华为matepad pro，系统是鸿蒙3.0，3.2.12也是遇到同样的问题。
3.1.3安装后部署一直无响应，还以为也不能用呢，部署好了以后正常使用。

**Comment by WhiredPlanck** [comment]
请看新版本有无此问题。每夜版：https://github.com/osfans/trime/releases/tag/nightly

**Comment by FEI352** [comment]
> 请看新版本有无此问题。每夜版：https://github.com/osfans/trime/releases/tag/nightly

小米平板5 Pro 5G，安卓13 MIUI Pad 14 V14.0.23.7.31.DEV，下载安装今天的每夜版，依旧需要开启“键盘、鼠标和触控板”-“使用屏幕键盘”才能在物理（实体）键盘上使用同文。输出。

**Comment by RavenNil** [comment]
Huawei Matepad pro 12.6
型号：WGR-W19 4.2.0.210
HarmonyOS版本：4.2.0
Trime版本：v3.2.18-0-gc10e2e84-release 从Fdroid安装

同样的也许要打开虚拟屏幕键盘，才能正常显示候选词并且输出

**Comment by stevesun1986** [comment]
> Huawei Matepad pro 12.6 型号：WGR-W19 4.2.0.210 HarmonyOS版本：4.2.0 Trime版本：v3.2.18-0-gc10e2e84-release 从Fdroid安装
> 
> 同样的也许要打开虚拟屏幕键盘，才能正常显示候选词并且输出

我也是
