### ISSUE TITLE
请教同文输入法配置的问题

### ISSUE THREAD

**Issue by zhl111** [osfans/trime#1004]
我的三星安卓手机，安装完同文APP，找不到、sdcard/rime的文件夹啊？哪里都找不到

**Comment by Bambooin** [comment]
Please check: https://github.com/Bambooin/rimerc

**Comment by zhl111** [comment]
这个我更看不懂了，看来只能放弃在手机上使用了，我只会复制拷贝这么简单的操作，却找不到这个路径
![image](https://user-images.githubusercontent.com/29135984/235177974-0c94b850-2713-4cd5-9abd-e7b1728c67bf.png)

**Comment by wxyzh** [comment]
就是内部存储的根目录下，和download，DCIM 平级

**Comment by zhl111** [comment]
感谢，我搞定了。另外想问一下，这同文键盘的功能和布局是什么文件控制的？我用的是双拼

我下载安装了最新版[trime-3.2.11-arm64-v8a-debug.apk](https://github.com/osfans/trime/releases/download/v3.2.11/trime-3.2.11-arm64-v8a-debug.apk)，我把雾凇拼音拷到手机里。结果提示错误：
w/rime.trime(5718):nonexistent config file ',/intallation.yamal'.
E/rime.trime(5718):failed to save config tostream.
w/rime.trime(5718):nonexistent config file '/,/build/default.yaml'.
w/rime.trime(5718):nonexistent config file '/,/user.yaml'.

**Comment by wxyzh** [comment]
https://github.com/osfans/trime/issues/998 
这里去找缺失的文件。
rime-ice的字典比较大，建议你下载fdroid的版本去部署字典

**Comment by l0o0** [comment]
> w/rime.trime(5718):nonexistent config file ',/intallation.yamal'.
E/rime.trime(5718):failed to save config tostream.
w/rime.trime(5718):nonexistent config file '/,/build/default.yaml'.
w/rime.trime(5718):nonexistent config file '/,/user.yaml'.

@wxyzh 你好，我也出现类似的问题。请问这个文件在 #998 issue的哪一个回复里

**Comment by zhl111** [comment]
重置可以自动生成，但是我原来的文件存在也不认，什么原因就不懂了
