### ISSUE TITLE
请问各位大佬rime编译不通过是怎么回事？

### ISSUE THREAD

**Issue by Mr-Li-jc** [osfans/trime#1010]
![image](https://github.com/osfans/trime/assets/22043213/8cca6a96-ae08-4752-adb4-705027c2e702)

**Comment by Wenti-D** [comment]
好像这玩意在 Windows 系统上无法编译，在 Linux 下才可以（WSL 也行）。

**Comment by goofyz** [comment]
如果不想自行編譯 rime 的話，可以一載最新的 apk 檔，將裏面的 `lib\*`  放到 `StudioProjects\trime\app\prebuilt` 入面即可略過

**Comment by 793383996** [comment]
RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly before end of the underlying stream
windows下载失败，上面说不能编译，那这个是不是白下了。。。
