### ISSUE TITLE
3.2.11 部署卡死 方案https://github.com/iDvel/rime-ice

### ISSUE THREAD

**Issue by lililiwuming** [osfans/trime#1011]
**Describe the bug**
App Package Name: com.osfans.trime
App Version Name: 3.2.11
App Version Code: 20230301
OS Name: HMA-AL00 10.1.0.163(C00E160R1P8)
OS Version: 4.14.116 (10.1.0.163C00)
OS API Level: 29
Device: HWHMA
Model (product): HMA-AL00 (HMA-AL00)
Manufacturer: HUAWEI
Tags: release-keys
Screen Size: 1080 x 2244
Screen Density: 3.0
Screen orientation: Portrait
--------- beginning of main
E/om.osfans.trim(12828): LoadAppImageStartupCache enabled : 1
E/om.osfans.trim(12828): Not starting debugger since process cannot load the jdwp agent.
E/AwareLog(12828): AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@fe549ec
E/HwViewGroupImpl(12828): parse speed value length error
E/HiView.HiEvent(12828): length is 0 or exceed MAX: 1024
E/HiView.HiEvent(12828): length is 0 or exceed MAX: 1024
E/rime.trime(12828): Encode failure: '黃瑾瑜'.

**Comment by wxyzh** [comment]
https://github.com/osfans/trime/issues/997#issuecomment-1512423902
#997

**Comment by WhiredPlanck** [comment]
请看新版本有无此问题。每夜版：https://github.com/osfans/trime/releases/tag/nightly
