### ISSUE TITLE
打多个拼音 多次选择候选词的时候未及时更新候选词

### ISSUE THREAD

**Issue by Aiden2014** [osfans/trime#1012]
**Describe the bug**
打多个拼音 多次选择候选词的时候未及时更新候选词

**To Reproduce**
1. 输入多个字的拼音
2. 选择 “候选” 这一栏，点击想要选择的字或者词，选好后在当前界面并没有及时更新下一个拼音的候选词，直到切换别的界面或者下滑上滑该 “候选” 界面才能刷新到下个拼音的候选词

**Expected behavior**
当步骤2点击完候选字或者词后，应该及时更新当前界面的下一个拼音的候选词

**Screenshots**
我通过录屏来演示，下面是视频的链接
https://1drv.ms/v/s!AuBp9-TDYqfJgTmLTCyvp5FwV8MJ?e=upZe1P

**Smartphone (please complete the following information):**
 - Device: [Redmi 8A]
 - OS: [Android 10   MIUI 12.5.3]
 - Theme: [trime]
 - Version: [v3.2.11-0-g46f3862c-release]
 - Build info: 
   ```
   Build: mull
   Date: 2022-06-12 10:09 UTC
   Commit: v3.2.11-0-g46f3862c, 2023-05-22 21:19:20 +0800
   Branch: null
   Repository: https://github.com/osfans/trime
   ```

**Comment by Aiden2014** [comment]
经测试 使用tongwenfeng主题时也会出现这种情况

**Comment by Wenti-D** [comment]
据开发者说这是「积重难返」的问题 ~，然后咕了~

**Comment by controlledentropy** [comment]
> 使用tongwenfeng主题时也会出现这种情况

那这表示接下来是要继续革命，还是继往开来XD，看来我还是蹲在.9老版本比较好

**Comment by controlledentropy** [comment]
> 据开发者说这是「积重难返」的问题 ~，然后咕了~

那这表示接下来是要继续革命，还是继往开来XD，看来我还是蹲在.9老版本比较好

**Comment by WhiredPlanck** [comment]
请看新版本有无此问题。每夜版：https://github.com/osfans/trime/releases/tag/nightly

**Comment by Aiden2014** [comment]
现在是解决了，但是在 更多 的 候选 一栏里面不能显示所有候选词，只能显示菜单里面设置的候选词数量![Screenshot_2024-01-26-23-15-50-548_net.gsantner.markor-edit.jpg](https://github.com/osfans/trime/assets/54656326/cb3b60bc-ccac-4dc9-9553-07b95edec4bf)
