### ISSUE TITLE
3.2.12状态栏不显示

### ISSUE THREAD

**Issue by Sunpulseqd** [osfans/trime#1013]
安卓10
之前用3.0.9正常 升级3.2.12之后 不管是trim 还是tongwenfeng主题 状态栏都不显示 同一个主题 拼音正常
![Collage_20230527_113533](https://github.com/osfans/trime/assets/77373494/43ae96ac-da5f-4c43-bddd-3298c7ef8b46)

**Comment by 3xpert** [comment]
我的也是，今天升级android到13，结果如下图（play上的版本），安装3.2.12，结果键盘呼不出来
![image](https://github.com/osfans/trime/assets/8335065/60597736-b791-4367-ae00-29432e685ced)

**Comment by sharp-tasting** [comment]
> 我的也是，今天升级android到13，结果如下图（play上的版本），安装3.2.12，结果键盘呼不出来
> ![image](https://github.com/osfans/trime/assets/8335065/60597736-b791-4367-ae00-29432e685ced)
> 

play 版太老了，安装 3.2.12 之前最好删了原来的用户目录 rime 中的 build 文件夹，然后部署新的。

另外个人感觉 3.2.10 更稳定，11版闪退，12版又实在太卡了

**Comment by 3xpert** [comment]
谢谢！
3.2.12可以了，3.2.10安装后没法启动
> 删了原来的用户目录 rime 中的 build 文件夹

**Comment by atlanticfirst** [comment]
3.2.13也遇到了同样的问题

**Comment by sharp-tasting** [comment]
> 3.2.13也遇到了同样的问题

同样遇到。
暂时解决方法：强杀trime的后台，再开trime，主题设置就不为空，可以切换了。

**Comment by atlanticfirst** [comment]
> 

我看得到主题，也能切换，但就是状态栏是空的，其他打字什么的都很正常.......

**Comment by sharp-tasting** [comment]
> > 
> 
> 我看得到主题，也能切换，但就是状态栏是空的，其他打字什么的都很正常.......

不好意思啊，我回错了。。。
我全新安装13版，解决掉切主题的bug之后，实测两个主题状态栏都是OK的

**Comment by atlanticfirst** [comment]
找到问题了，我方案里加入的拼音备注功能多了一行代码.........把代码删掉就好了。作者如果可以的话能不能把日志做简单点，方便我这种小白。出错时告诉我哪个文件哪一行有问题就行，现在的日志看得我一头雾水，出了错看日志看半天也不知道是哪个功能哪个文件的问题，只能摸黑一点一点的删来测试

**Comment by sharp-tasting** [comment]
> 找到问题了，我方案里加入的拼音备注功能多了一行代码.........把代码删掉就好了。作者如果可以的话能不能把日志做简单点，方便我这种小白。出错时告诉我哪个文件哪一行有问题就行，现在的日志看得我一头雾水，出了错看日志看半天也不知道是哪个功能哪个文件的问题，只能摸黑一点一点的删来测试

强烈同意，那个日志真的槽点太多。。。几万行的垃圾info信息反复循环（比如 #999 里面贴的那种日志），导出的时候不能只导出warning和error，还得放电脑上vscode批量删除info。。。

**Comment by WhiredPlanck** [comment]
请看新版本有无此问题。每夜版：https://github.com/osfans/trime/releases/tag/nightly
