### ISSUE TITLE
用3.2.2版本，输入时卡顿。有没有办法解决

### ISSUE THREAD

**Issue by guoyan1983** [osfans/trime#1023]
oppo手机，android13。安装3.2.2。用了雾凇拼音词库。这两天使用时，输入会卡顿。是因为什么缘故呢，能不能解决呢。谢谢

**Comment by MokOopsing** [comment]
版本号有没有搞错，这么老吗？
另外雾凇确实有点占内存，词库太大了

**Comment by guoyan1983** [comment]
> 版本号有没有搞错，这么老吗？ 另外雾凇确实有点占内存，
没有搞错。后面的几个版本，加了雾凇的词库。无法部署。。。。

**Comment by wxyzh** [comment]
可以尝试使用这个版本 https://github.com/osfans/trime/issues/997#issuecomment-1512423902
#997

**Comment by guoyan1983** [comment]
> 可以尝试使用这个版本 [#997 (comment)](https://github.com/osfans/trime/issues/997#issuecomment-1512423902) #997

感谢。解决了问题。！！！！！谢谢了！！！！

**Comment by WhiredPlanck** [comment]
请看新版本有无此问题。每夜版：https://github.com/osfans/trime/releases/tag/nightly
