### ISSUE TITLE
v3.2.12 键盘呼不出来 The keyboard list cannot be summoned

### ISSUE THREAD

**Issue by Helenaria** [osfans/trime#1029]
**Describe the bug**

3.2.12版本的trime键盘，常按空格呼不出来别的键盘
In version 3.2.12, the list of keyboards cannot be summoned from long pressing the spacebar.

**To Reproduce**
Steps to reproduce the bug:
1. 呼出trime键盘 Summon the trime keyboard
2. 常按空格（朙月拼音 - 简化字）Long press the spacebar（朙月拼音 - 简化字）

**Expected behavior**
能常按空格呼出别的键盘 To be able to summon the list of keyboards from long pressing the spacebar.

**Log**
没有崩溃 No crash

**Screenshots**
![keyboard problem](https://github.com/osfans/trime/assets/80150720/e1e9cbc1-073e-45bd-b53f-cbb0c603a655)

**Smartphone (please complete the following information):**
 - Device: Vivo V25
 - OS: Android 12
 - Theme: 孤寺 Lost Temple
 - Version: 3.2.12
 - Build info: 
Builder: Release CI
Build Time: 2023-05-01 12:12:10 UTC
Build Version Name: v3.2.12-0-g31fa50fd
Git Hash: 31fa50fd
Git Branch: v3.2.12
Git Repo: https://github.com/osfans/trime

**Additional context**

**Comment by WhiredPlanck** [comment]
请看新版本有无此问题。每夜版：https://github.com/osfans/trime/releases/tag/nightly
