### ISSUE TITLE
旋轉屏幕後，鍵盤高度與寬度保持不變。

### ISSUE THREAD

**Issue by DaengGWokFook** [osfans/trime#103]
![screenshot_2016-08-22-15-55-07](https://cloud.githubusercontent.com/assets/18633778/17878455/ce3bcb30-68b8-11e6-93ba-592a0371ae0c.png)

**Comment by DaengGWokFook** [comment]
20160708版本，目前只能通過旋轉屏幕或切換方案解決。

**Comment by osfans** [comment]
看來寬度有問題了。

**Comment by osfans** [comment]
有發現重現的方法嗎？我好像以前遇到過一次

**Comment by DaengGWokFook** [comment]
瀏覽器用一會，點地址準備輸入時，發現字體變大了，鍵盤右邊一半沒了。

**Comment by X1aomu** [comment]
我也遇过两次，但还没发现规律，切换了一下输入法就又正常了，不过有一点，异常时的键盘与手机为横屏时的键盘比例是一样的

**Comment by osfans** [comment]
所以不知什么情况下当成横排了

**Comment by DaengGWokFook** [comment]
終於找到規律了。
豎屏時在(google chrome)瀏覽器地址欄輸入，接著隱藏鍵盤，然後轉屏再輸入地址，此時鍵盤依然保持豎屏時的鍵盤。

**Comment by DaengGWokFook** [comment]
橫屏轉豎屏也會保留橫屏鍵盤狀態

**Comment by DaengGWokFook** [comment]
![screenshot_2016-08-28-15-33-57](https://cloud.githubusercontent.com/assets/18633778/18036312/f630ae00-6d34-11e6-90ac-1a33793b2d4d.png)
橫屏出現豎屏鍵盤

**Comment by osfans** [comment]
在我這正常 奇怪

**Comment by DaengGWokFook** [comment]
20170104版本好像沒出現此問題

**Comment by osfans** [comment]
這個好像是很偶發的問題。我也遇到過了。
