### ISSUE TITLE
自動匹配佈局好像有問題

### ISSUE THREAD

**Issue by JeffChien** [osfans/trime#1031]
**Describe the bug**
用 trime.custom.yaml 來修改鍵盤佈局

雙拼鍵盤只能用自動匹配的 26 鍵版本，用 `preset_keyboards/XXXXXX/import_preset` 或者定義一個完整的鍵盤也不行。
我有另一個 bopomo_tw 的也是類似的情況，自動匹配到 time.yaml 的 bopomo 鍵盤，我無法用 `preset_keyboards/bopomofo_tw` 來
覆蓋新設定

**To Reproduce**
1. 定義 preset_keyboards/{sheme_id}/import_preset: qwerty0
   或是複製一份為 preset_keyboards/{sheme_id} 且改掉 name.
2. copy trime.custom.yaml to /sdcard/rime
3. hit deploy
4. switch between 2 themes to activate new layout.

**Expected behavior**
`.default` 應該要匹配到 {schema_id} 的鍵盤佈局.

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 12
 - Theme: trime
 - Version: 3.2.13
 - Build info: 
   ```
   You could find build info in About Activity and click it to copy.
   e.g. 
   Build: Commit CI
   Date: 2023-07-01 02:55:43 UTC
   Build Version Name: v3.2.13-0-gc1cf0a73
   Git Hash: c1cf0a73
   Git Branch: v3.2.13
   Git Repo: https://github.com/osfans/trime
   ```
**Additional context**

**Comment by controlledentropy** [comment]
有沒有嘗試過回退到以前的版本？老版本也有同樣的問題嗎？

**Comment by JeffChien** [comment]
F-Droid 上最舊的 3.2.9 正常

**Comment by Wenti-D** [comment]
目前匹配好像确实是有问题，只会匹配第一个下划线前的字串，例如我打微软双拼，键盘 ID 是 `double_pinyin_mspy` 识别不了，改成 `double` 就能识别。

**Comment by JeffChien** [comment]
好吧，那我就繼續用 3.2.9

**Comment by goofyz** [comment]
refs #907 
應該已 fix, 有需要的在下一版本試下吧

**Comment by Wenti-D** [comment]
> refs #907 應該已 fix, 有需要的在下一版本試下吧

的确修复了，谢谢。
