### ISSUE TITLE
3.2.8 部署后键盘布局不会刷新，需要再进一次主题

### ISSUE THREAD

**Issue by isPoto** [osfans/trime#1032]
我在用 3.2.8，我发现部署后键盘布局不会刷新，需要再进一次主题 OK 才刷新。
预期效果是部署后即刷新键盘

**Comment by controlledentropy** [comment]
开发者在很早前的issue里就确认这个问题了，说是忘记加入.custom.yaml的变更检测了

然而几天前刚刚发布的3.2.13，确认这个问题依然存在（躺.....

**Comment by Bambooin** [comment]
Close with #1060
