### ISSUE TITLE
中英键盘硬切，从其他主题换回会变成「中文键盘打英文」

### ISSUE THREAD

**Issue by isPoto** [osfans/trime#1035]
**Describe the bug**
因为中英键盘我分别设置不同的标点符号，而 mode switch 并不能切换中英文布局；
所以中英文键盘没有用 mode switch，而是 preset key 直接换键盘布局。

但是中英文键盘硬切，会导致从其他键盘换回来时，会变成「中文键盘打英文」。
预期结果是「从其他键盘换回来时，是中文键盘打中文」。

**To Reproduce**
Steps to reproduce the bug:
1. preset key 分别设置指向 default 和 letter 的 键
2. default 和 letter 键盘布局中应用这两键
3. 换成其他主题
4. 再从其他主题换回本主题；
5. 弹出的键盘是中文键盘布局，英文打字状态

**Expected behavior**
「从其他键盘换回来时，是中文键盘布局打中文」

**Smartphone (please complete the following information):**
 - Device: Oneplus 3
 - OS: Android 9
 - Theme: Singbit by Poto
 - Version: 3.2.8

**Additional context**
希望 mode switch 能切换 default 和 letter 键盘布局

**Screenshot**
中文键盘，M 键有米符
![Screenshot_20230709-150053](https://github.com/osfans/trime/assets/59009389/bbb4bc34-99b6-4784-b971-1152b0e2efcc)

英文键盘，M 键没有米符
![Screenshot_20230709-150058](https://github.com/osfans/trime/assets/59009389/03bec877-8d30-4645-bc2f-7f16429afb78)

从其他主题切换回来后，变成中文键盘打英文
![Screenshot_20230709-150035](https://github.com/osfans/trime/assets/59009389/3c262fdf-e844-40b0-8924-ea98f505ed5f)

**Comment by isPoto** [comment]
中英文键盘都开 lock 和 reset ascii mode，英文键盘下切换其他应用，和 Deploy 后，这两种情况弹出的键盘肯定会出现以上情况。

但中文键盘不开 reset ascii mode, 能解决「切换应用后弹出的键盘是『中文键盘打英文』」问题，但「从其他主题切换回来后弹出的键盘是『中文键盘打英文』」依旧存在。

**Comment by shitlime** [comment]
参考 [这个笔记](https://shitlime.gitbook.io/trime-problems-note/yuan-ma-yue-du-bi-ji-pei-zhi) 或许有所帮助

**Comment by goofyz** [comment]
我始終不能重現此問題，能否上載相關主題檔案讓我試試？

**Comment by isPoto** [comment]
> 我始終不能重現此問題，能否上載相關主題檔案讓我試試？

你 TG 几多？可以粤语沟通

我让你嘅 TG 唔再单机

**Comment by goofyz** [comment]
> > 我始終不能重現此問題，能否上載相關主題檔案讓我試試？
> 
> 你 TG 几多？可以粤语沟通
> 
> 我让你嘅 TG 唔再单机

gzlwc

**Comment by WhiredPlanck** [comment]
请看新版本有无此问题。每夜版：https://github.com/osfans/trime/releases/tag/nightly
