### ISSUE TITLE
Trime中为什么没有`共享文件夹`？

### ISSUE THREAD

**Issue by ipcjs** [osfans/trime#104]
Rime下打path貌似就是将两个文件合并成一个文件：`custom.yaml`+`base.yaml`=>`result.yaml`
我测试了下Prime和Trime在给方案打patch时，各文件的位置：
- Trime：`[用户文件夹]/[方案].custom.yaml`+`[用户文件夹]/[方案].schema.yaml`=>`[用户文件夹]/[方案].schema.yaml`
- Prime：`[用户文件夹]/[方案].custom.yaml`+`[共享文件夹]/[方案].schema.yaml`=>`[用户文件夹]/[方案].schema.yaml`
  - （注：若`共享文件夹`中没有`[方案].schema.yaml`则使用`用户文件夹`中的`[方案].schema.yaml`文件）

Trime中没有`共享文件夹`，`base.yaml`和`result.yaml`是同一个文件，导致不能像Prime一样，通过清空`custom.yaml`来还原方案的默认配置。
为什么Trime中不设置`共享文件夹`呢？

**Comment by osfans** [comment]
可以通過回廠還原base，刪除custom，部署。

共享的放在data下？幾十兆，有些佔空間。

**Comment by xiaoqun2016** [comment]
说说我所观察到的。  
众所周知，同步功能会将schema.yaml和custom.yaml备份到同步文件夹中。但这里面有个有趣的现象：凡是带有`customization`  这一句的schema，都不会被备份。而这个`customization`只存在于打过补丁的schema中，也就是说，同步功能只接收**原始的schema**和**后续给它打的补丁**，这就是合并前的状态呀！你只要在最开始打补丁前同步一次，以后任你怎么折腾，都可以从同步文件夹中提取之前的原始方案文件。  
这样还不够吗？ 手机空间宝贵，有没有必要把同一套schema放在三个位置（同步、共享、用户）？而且 多一个共享文件夹只会变得更混乱，很多人修改配置文件都改到共享文件夹中去了。 
个人观点

**Comment by osfans** [comment]
共享文件夾放到/data/下面，一般人沒有權限去改，跟linux一樣，是只讀的。

**Comment by osfans** [comment]
所以倒是不會搞混，但是用戶想要改essay.txt這些就要麻煩點，需要root。一般只能通過custom打補丁的方式改方案，這個可能是公子推薦的做法。

**Comment by xiaoqun2016** [comment]
也好，用户如果把schema改坏了会自动从共享文件夹中提取正确的来覆盖。  
如果是补丁不对，就不会合并。 改错了顶多不生效。 

虽然，我个人觉得被补丁合并过的schema很乱，连注释都没了，不大喜欢这样，所以都是直接在自己的schema中修改的。 但是对外交流时都是尽量用打补丁的方法，这是官方推荐的。  不过做emoji滤镜时没法做出通用的补丁，所以视频中就没用补丁了。

essay.txt可以做成dict.yaml的格式，直接在需要的方案中import_tables，效果一样的。

**Comment by ipcjs** [comment]
看[佛振的说明](https://github.com/rime/home/wiki/CustomizationGuide#%E5%AE%9A%E8%A3%BD%E6%8C%87%E5%8D%97)，设置`共享文件夹`的目的应该是为了：在升级软件时，同时升级`预设方案和配置`，而不影响用户配置。
所以如果Trime以后要添加`预设方案和配置`的话，还是设个`共享文件夹`好。
`共享文件夹`可以放在`/sdcard/Android/data/[package_name]/`下面，位置比较隐蔽，不需要root权限就可以编辑。

**Comment by osfans** [comment]
我覺得還是按照安卓的規矩，放到/data/data下面比較好。到時升級，直接覆蓋這個目錄就好。

一般用戶可以不管這個文件夾；高級用戶的話，可以自己root修改。跟linux一樣，自己sudo去修改/usr目錄。

**Comment by osfans** [comment]
不然都在/sdcard下面，會搞混的。
`/sdcard/Android/data/[package_name]/` 這個也是安卓標準的嗎？我去查查

**Comment by ipcjs** [comment]
@osfans 是Android标准，用这个方法获取目录：[Context.getExternalFilesDir()](https://developer.android.com/reference/android/content/Context.html#getExternalFilesDir%28java.lang.String%29)

**Comment by xiaoqun2016** [comment]
如果以后要「消减预设方案，强调用户个性设置」，那么共享文件夹就应该逐渐退出历史的舞台了，我是这么理解的。 也许可以直接问问佛振本人？

**Comment by ipcjs** [comment]
@xiaoqun2016 为什么要”消减预设方案“=.=!。「预设方案」是用来方便用户快速上手的，和「用户个性化设置」又不冲突。要个性化设置直接打patch就行了

**Comment by xiaoqun2016** [comment]
@ipcjs 是看到佛振这么说的  https://github.com/rime/brise/pull/112#issuecomment-229854113  

> 今後的輸入法升級的趨勢是消減預設的輸入方案，強調用戶個性設置，librime 的主要改進方向是讓用戶定製更靈活方便。brise 則要拆分爲衆多獨立的代碼庫，「東風破」也就不再成爲一個「官方」的方案集了。

共享文件夹更像是一个存在本地的东风破方案集。拆分东风破或许是为了做成便于在线下载的形式？到时候共享文件夹会变成一个云端的资源库？   瞎猜的

**Comment by ipcjs** [comment]
@xiaoqun2016 佛振也还只是提个概念而已，具体怎么做也没说。目前所有的桌面版Rime都是有`共享文件夹`的，而Trime没有`共享文件夹`。导致把桌面版的方案文件直接copy到Trime中的话，实际上合并的行为和桌面版是不一样的。

**Comment by xiaoqun2016** [comment]
@ipcjs 你可以再观察一下PC端的合并行为。  
再确认一下是不是这样的：  
PC端只在以下情况会用到共享文件夹里的schema：  
  - ➀用户文件夹中的schema损坏或缺失  
  - ➁共享文件夹中的同名schema版本号高于用户文件夹中的  

---

共享文件夹有优点也有缺点，做与不做都有道理吧。  

可能是用久了吧，我已经习惯了目前的Trime，刚开始总在挑毛病，现在总在发掘优点。哈哈！

**Comment by ipcjs** [comment]
@xiaoqun2016 

> 不管是➀还是➁，对于老老实实打补丁的人来说，有没有共享文件夹其实没有任何区别。因为他的个性配置都在补丁里，不受影响。

源码里面是这样写的？我实测修改patch文件后，重新部署，若共享目录里存在同名方案，则是和共享目录里的文件合并；否则，和用户目录里的文件合并。合并的文件都不一样，怎么会没有区别呢？

**Comment by xiaoqun2016** [comment]
简单验证一下，在用户文件夹的schema中修改一处设置，只要不与补丁冲突，部署后仍然存在。这说明了什么？

**Comment by ipcjs** [comment]
@xiaoqun2016 你同时再在patch文件末尾加个回车试下？我也不知道什么原理，只有修改了patch文件，重新部署时，才会重新合并。

**Comment by xiaoqun2016** [comment]
看来我错了。 抱歉。确实是不一样。

**Comment by ipcjs** [comment]
@xiaoqun2016 看了下源码（C++没学过，看的很头疼=.=!）：
[这一行](https://github.com/rime/librime/blob/a067237fec822ad462fa040b9eacd4251cc0df4d/src/lever/deployment_tasks.cc#L154)应该是获取schema路径的代码，调用了[string WorkspaceUpdate::GetSchemaPath(Deployer\* deployer, const string& schema_id, bool prefer_shared_copy)](https://github.com/rime/librime/blob/a067237fec822ad462fa040b9eacd4251cc0df4d/src/lever/deployment_tasks.cc#L208)来获取路径。第三个参数`prefer_shared_copy`传的是`true`，优先使用`shared_data_path`。
跟我的实测结果是相符的。

**Comment by xiaoqun2016** [comment]
突然觉得 要把这个输入法用熟 需要付出的代价太大了

**Comment by ipcjs** [comment]
@xiaoqun2016 只是用的话不会特别麻烦吧=.=!
要开发的话，应该蛮复杂的，librime从11年就开始开发了。。

**Comment by ipcjs** [comment]
@xiaoqun2016 找到判断patch文件是否改变的地方了：
合并生成的文件中会保存一个`customization`，`customization`是根据patch文件的内容通过计算生成的，相当于一个特征值，下次合并时，会比较patch文件的特征值和目标文件中的`customization`是否相等，只有不相等才会合并。

相关代码：
https://github.com/rime/librime/blob/a067237fec822ad462fa040b9eacd4251cc0df4d/src/lever/customizer.cc#L79
https://github.com/rime/librime/blob/a067237fec822ad462fa040b9eacd4251cc0df4d/src/algo/utilities.cc#L37

**Comment by ipcjs** [comment]
@osfans 我看了下[源码](https://github.com/osfans/trime/blob/develop/jni/librime_jni/rime.h#L13)，发现Trime是设置了共享目录的，只不过是放在`/data/data/com.osfans.trime/rime`下面，没root权限编辑不了。要么下个版本换成`/sdcard/Android/data/com.osfans.trime/rime`？方便编辑

**Comment by osfans** [comment]
@ipcjs 同意換到/sdcard下面。所以trime並不是用戶文件夾和共享文件夾在一起，也不是沒有共享文件夾，而是共享文件夾裏沒有東西，都忘了自己當時是怎麼寫的了。

**Comment by osfans** [comment]
樓主的捐贈收到了，感謝！是不能留言？那我應該重新生成一個二維碼？

**Comment by ipcjs** [comment]
@osfans 可能是第一次扫的时候看错了吧=.=!，之后就没问题了。

**Comment by osfans** [comment]
今天我改過了，換成加好友的界面了，應該可以留言了。

**Comment by osfans** [comment]
18bac624883c8624d3adc01135844995f78b58b8 解決

**Comment by Freed-Wu** [comment]
现在共享文件夹是 `/sdcard/rime-data` 吗？没有看到相关文档 :cry:
