### ISSUE TITLE
请问trime支持自定义按键布局吗

### ISSUE THREAD

**Issue by diggerdu** [osfans/trime#1046]
感谢开发者开源了如此优秀的输入工具
有个问题想请教一下：trime 有办法支持自定义软键盘的按键布局吗，例如添加；’ ~ <ESC> 等按键

**Comment by MokOopsing** [comment]
https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3

拜托你先看看wili

**Comment by diggerdu** [comment]
> [osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3](https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3)
> 
> 拜托你先看看wili

好的 谢谢，刚才只读了Readme 没注意到有一个wiki
