### ISSUE TITLE
点击验证码输入框，就崩溃退出

### ISSUE THREAD

**Issue by superLei** [osfans/trime#1047]
**Describe the bug**
点击手机验证码输入框，就崩溃。

**To Reproduce**
Steps to reproduce the bug:
发现只要是app登录界面有要输入手机验证码地方，一点击验证码组件就会触发崩溃。

**Screenshots**
![image](https://github.com/osfans/trime/assets/17941039/9230a2cd-aa68-42e5-bbe9-69417774f04e)

**Smartphone (please complete the following information):**
 - Device: moto x30
 - OS: [Android 13]
 - Theme: [trime]
 - Version: [3.2.13]

**Additional context**
没有程序崩溃的日志，程序好像也没有打印出来。

**Comment by wxyzh** [comment]
可能是因为没有缺少数字键盘

**Comment by superLei** [comment]
> 

输入手机号的时候，可以自动调出数字键盘。输入验证码，就会崩溃

**Comment by shitlime** [comment]
在百度网盘中并没有这个问题，可能是系统太新

OS: HarmonyOS 3.0.0.165 相当于 Android10

Trime: 3.2.14

**Comment by superLei** [comment]
> 

android13的数字键盘调用是不是有改变，trime中有新的数字键盘支持吗？

**Comment by shitlime** [comment]
> 
Google官方的文档中并没有提及关于数字键盘的改变，且有人测试Android12中同文在百度云盘的验证码输入框可正常输入

Android13变更： https://developer.android.google.cn/about/versions/13/summary?hl=zh-cn

或许你可以再次检查你的数字键盘相关配置

**Comment by superLei** [comment]
这是我的配置: 
  keyboards: [.default, default, pinyin_simp, wubi86_number, symbols_4row] #键盘配置
 
解决: 
1. 把数字键盘命名由`wubi86_number`修改成`number`。
2. 并同步修改了keyboards中的键盘配置好了。

总结：
的确是数字键盘相关配置有问题，应该是程序中只认数字键盘为'number'这个字段名称。但是当数字键盘名称为'wubi86_number'的时候，大部分场景下还是可以调出数字键盘，只是部分场景会触发应用崩溃。

**Comment by WhiredPlanck** [comment]
请看新版本有无此问题。每夜版：https://github.com/osfans/trime/releases/tag/nightly
