### ISSUE TITLE
termux、ConnectBot等命令行中 `Enter` 会发送两次

### ISSUE THREAD

**Issue by shitlime** [osfans/trime#1053]
在使用termux、ConnectBot等命令行中 `Enter` 键会发送两次，视频演示：

https://github.com/osfans/trime/assets/31384673/f55e9d96-a639-4064-a710-4ef8786a18eb

+ 视频中使用的是ConnectBot
+ 同文的版本是 CI https://github.com/shitlime/trime/actions/runs/5700346932

参考 https://github.com/osfans/trime/issues/957 之后尝试使用了ConnectBot的特殊键，
发现ConnectBot的 `Esc` 键按下后再按同文的 `Enter` 表现为只有一个 `Enter`

https://github.com/osfans/trime/assets/31384673/88415145-f203-4380-a091-24047a8a7889

----
*有空打算翻源码找找问题*

**Comment by shitlime** [comment]
问题跟踪
----
两次回车的来源是：
https://github.com/osfans/trime/blob/e2f9ec1b8aafc33e34a960cf4d35a1555aafc872/app/src/main/java/com/osfans/trime/ime/core/Trime.java#L608-L615


在使用ConnectBot时发现 `editorInfo.inputType` 的值为 `524432` 这个值在Android的InputType [文档](https://developer.android.com/reference/android/text/InputType) 中没有任何记录
![图片](https://github.com/osfans/trime/assets/31384673/93d447b7-e6a2-4f25-85a2-c2413610615f)

**Comment by shitlime** [comment]
问题跟踪
----
根据一位热心群友提供的使用termux时的log（片段）：

```
D/[main] KeyboardView(23668): KeyboardView.java:950] onBufferDraw() keyBackground==null, key=/
I/[main] Trime(23668): Trime.java:610] >>>>>handleReturnKey: editorInfo.inputType=0
D/[main] Trime(23668): Trime.java:1071] 	<TrimeInput>	handleKey()	EnterOrHide, keycode=66
D/[main] KeyboardView(23668): KeyboardView.java:1103] 	<TrimeInput>	releaseKey() key=66, mComboCount=0, mComboMode=false
D/[main] Event(23668): Event.java:279] <Event> getRimeEvent()	code=66, mask=1073741824, name=Return	output key=65293, meta=1073741824
D/[main] TextInputManager(23668): TextInputManager.kt:298] 	<TrimeInput>	onRelease() needSendUpRimeKey=false, keyEventcode=66, Event.getRimeEvent=[I@8dd669d
D/[main] TextInputManager(23668): TextInputManager.kt:313] 	<TrimeInput>	onRelease() finish
```

可以发现 `termux` 的 `inputType` = `0` 

 `InputType.TYPE_NULL` 的值是 `0` ; `InputType.TYPE_MASK_CLASS` 的值为 `15`

按位与之后，无论是ConnectBot（ `524432` ）还是termux（ `0` ）都为 `0` 条件都成立，此时发送了一次 `Enter`

在下一个 `if` 导致发送了两次 `Enter`

**Comment by shitlime** [comment]
已修复
----
修复后的CI： https://github.com/shitlime/trime/actions/runs/5706354737

测试几天无问题后发pr合入主线，届时关闭此issue

**Comment by controlledentropy** [comment]
大佬留笔！我还以为是CrdOS的体制问题，也遇到了这个问题但没留意，通常用英文输入也就蒙混过去了XD

另外，快把热心群号亮出来吧，这里和小绿书一样冷清诶。。。

ps：头像真可爱啊，也是萝莉控么 XDrz

**Comment by shitlime** [comment]
> 大佬留笔！我还以为是CrdOS的体制问题，也遇到了这个问题但没留意，通常用英文输入也就蒙混过去了XD
> 
> 另外，快把热心群号亮出来吧，这里和小绿书一样冷清诶。。。
> 
> ps：头像真可爱啊，也是萝莉控么 XDrz

群是同文 关于 里面的群2

**Comment by controlledentropy** [comment]
> > 大佬留笔！我还以为是CrdOS的体制问题，也遇到了这个问题但没留意，通常用英文输入也就蒙混过去了XD
> > 另外，快把热心群号亮出来吧，这里和小绿书一样冷清诶。。。
> > ps：头像真可爱啊，也是萝莉控么 XDrz
> 
> 群是同文 关于 里面的群2

好的萝莉控

**Comment by shitlime** [comment]
已交PR
