### ISSUE TITLE
外接蓝牙键盘后，无法显示候选框

### ISSUE THREAD

**Issue by yanhuacuo** [osfans/trime#1058]
第一，『显示在应用程序上层』的权限列表中，找不到同文输入法了。
第二，外接键盘使用时，候选框无法显示了。

**Comment by FEI352** [comment]
我也遇到了和你同样的问题，
1. 外界键盘使用的时候，没有像gboard一样的输入法候选框。
2. 而且要先使用过触控键盘的输入法，才能显示物理键盘的输入法。希望能改进。
设备是小米平板5 pro 5G，最后一个开发板。安卓13。

**Comment by yanhuacuo** [comment]
> 我也遇到了和你同样的问题，
> 
> 1. 外界键盘使用的时候，没有像gboard一样的输入法候选框。
> 2. 而且要先使用过触控键盘的输入法，才能显示物理键盘的输入法。希望能改进。
>    设备是小米平板5 pro 5G，最后一个开发板。安卓13。

两三年前，印象中还是能用的。

**Comment by yanhuacuo** [comment]
感觉是『显示在应用程序上层』没有表达的结果。

**Comment by yanhuacuo** [comment]
参考：

https://developer.android.google.cn/guide/topics/ui/bubbles?hl=zh-cn

https://developer.android.google.cn/guide/topics/ui/picture-in-picture?hl=zh-cn

**Comment by shitlime** [comment]
1. 新版的同文不需要这个权限
2. 请问是否需要使用特定的输入方案进行测试，因为我在使用实体键盘测试时，没有复现

**Comment by controlledentropy** [comment]
我目前是通过scrcpy投屏使用，也是会遇到这样的问题。不唤起屏幕键盘，就无法弹出候选框（甚至时间久了习得了某种新意义上的“盲打”）。

对了，我配置的是悬浮窗竖排。

**Comment by yanhuacuo** [comment]
> 1. 新版的同文不需要这个权限
> 2. 请问是否需要使用特定的输入方案进行测试，因为我在使用实体键盘测试时，没有复现

您说的「没有复现」，是指：**在实体 Android 设备上，连接蓝牙键盘时，虚拟键盘自动隐藏，同时输入法候选框的悬浮条正常显示吗？**

如这种： https://www.bilibili.com/video/BV1f4411N77s/?spm_id_from=333.999.0.0&vd_source=0d05a37563bb1109bc73f16a8004a282

我在小米平板5pro 上测试时，发现：候选框无法正常显示，只能盲打。

**Comment by yanhuacuo** [comment]
> 我目前是通过scrcpy投屏使用，也是会遇到这样的问题。不唤起屏幕键盘，就无法弹出候选框（甚至时间久了习得了某种新意义上的“盲打”）。
> 
> 对了，我配置的是悬浮窗竖排。

我也是，以前是可以用的： https://www.bilibili.com/video/BV1f4411N77s/?spm_id_from=333.999.0.0&vd_source=0d05a37563bb1109bc73f16a8004a282

**Comment by yanhuacuo** [comment]
98五笔方案：https://gitee.com/wubi98/trime-98wubi

这份配置文件，默认的 trime 主题做了「竖排悬浮」：https://gitee.com/wubi98/trime-98wubi/blob/master/trime.yaml#L56

**Comment by yanhuacuo** [comment]
又在手机上测了一下，仅当开启【使用屏幕键盘】时，即【虚拟键盘不隐藏】时，配置好的「悬浮候选框」才能显示。
一旦令「虚拟键盘隐藏」，「悬浮候选框」一并消失不见，只能盲打。

**Comment by shitlime** [comment]
+ 没有复现指手机上使用实体键盘，并不会自动隐藏软键盘
+ 请问使用的是什么版本，因为有大佬用 scrcpy ，并且疑似有个修复的commit

**Comment by yanhuacuo** [comment]
> * 没有复现指手机上使用实体键盘，并不会自动隐藏软键盘
> * 请问使用的是什么版本，因为有大佬用 scrcpy ，并且疑似有个修复的commit

最新 CI，我这边最大的问题是：光标处，无法正常显示「候选框」。

- ![pic](https://raw.githubusercontent.com/yanhuacuo/trime-98wubi/main/2023-08-09_075713.png)

**Comment by yanhuacuo** [comment]
> * 没有复现指手机上使用实体键盘，并不会自动隐藏软键盘
> * 请问使用的是什么版本，因为有大佬用 scrcpy ，并且疑似有个修复的commit

使用这份主题：https://gitee.com/wubi98/trime-98wubi/blob/master/trime.yaml#L56

它该如楼上所示那样，光标处，有一个浮动候选框。

**在手机或平板上，不连「蓝牙键盘」时，浮动候选框表现正常。**

**当连上「蓝牙键盘」后，浮动候选框消失。**

**Comment by 1284685832** [comment]
这边也有相同的问题，使用的是最新的稳定版。

![e9fe9a573145f2eae19dc5ba19f29a11](https://github.com/osfans/trime/assets/21006190/43ca202f-849f-4642-a965-dfde61ecce30)

如上图所示，没有候选框，和盲打差不多了。

**Comment by yanhuacuo** [comment]
> 这边也有相同的问题，使用的是最新的稳定版。
> 
> ![e9fe9a573145f2eae19dc5ba19f29a11](https://user-images.githubusercontent.com/21006190/259353104-43ca202f-849f-4642-a965-dfde61ecce30.jpg)
> 
> 如上图所示，没有候选框，和盲打差不多了。

是的，你是什么设备？

**Comment by 1284685832** [comment]
> > 这边也有相同的问题，使用的是最新的稳定版。
> > ![e9fe9a573145f2eae19dc5ba19f29a11](https://user-images.githubusercontent.com/21006190/259353104-43ca202f-849f-4642-a965-dfde61ecce30.jpg)
> > 如上图所示，没有候选框，和盲打差不多了。
> 
> 是的，你是什么设备？

华为matepad11

**Comment by yanhuacuo** [comment]
> > > 这边也有相同的问题，使用的是最新的稳定版。
> > > ![e9fe9a573145f2eae19dc5ba19f29a11](https://user-images.githubusercontent.com/21006190/259353104-43ca202f-849f-4642-a965-dfde61ecce30.jpg)
> > > 如上图所示，没有候选框，和盲打差不多了。
> > 
> > 
> > 是的，你是什么设备？
> 
> 华为matepad11

我在小米平板5pro 上也是一样，感觉就是相同的 API 出了问题。

**Comment by FEI352** [comment]
想到了一个并不完美的解决办法，"使用屏幕键盘-开启后，连接到实体键盘时，它会一直显示在屏幕上"，开启这个选项之后，触控键盘就会一直显示在屏幕上上，这样中间就会有候选了。如果能有什么皮肤把触控键盘所有按键去掉。只留切换皮肤，输入法方案，以及候选框，就可以实现底部出现候选框。

**Comment by 1284685832** [comment]
> 想到了一个并不完美的解决办法，"使用屏幕键盘-开启后，连接到实体键盘时，它会一直显示在屏幕上"，开启这个选项之后，触控键盘就会一直显示在屏幕上上，这样中间就会有候选了。如果能有什么皮肤把触控键盘所有按键去掉。只留切换皮肤，输入法方案，以及候选框，就可以实现底部出现候选框。
![2d3e7a7e462e31278b5760f32c57c2ec](https://github.com/osfans/trime/assets/21006190/a8179bfa-33a0-4255-9d1b-c29cdbad5745)

确实可以这样做。

**Comment by FEI352** [comment]
> > 想到了一个并不完美的解决办法，"使用屏幕键盘-开启后，连接到实体键盘时，它会一直显示在屏幕上"，开启这个选项之后，触控键盘就会一直显示在屏幕上上，这样中间就会有候选了。如果能有什么皮肤把触控键盘所有按键去掉。只留切换皮肤，输入法方案，以及候选框，就可以实现底部出现候选框。
> > ![2d3e7a7e462e31278b5760f32c57c2ec](https://user-images.githubusercontent.com/21006190/259646588-a8179bfa-33a0-4255-9d1b-c29cdbad5745.jpg)
> 
> 确实可以这样做。

你能够给我一份配置文件吗？默认的主题实现不了这样的效果，我也想要我的同文变成你这样。

**Comment by MokOopsing** [comment]
同文有个设置 接实体键盘时使用迷你键盘 自己找找

**Comment by yanhuacuo** [comment]
虽然同文已经内置了「迷你」的布局，但是这个「迷你」主题在「安卓平板横向使用」时，还是过于高大了。

在【小米平板5pro】上：

【设置】→【更多设置】→【语言与输入法】→【键盘、鼠标和触控板】→【使用屏幕键盘】（勾中）

在【同文输入法设置】的【主题】中，选中【pc】，即可实现类 pc 那**悬浮候选框跟随光标**了。

基于默认主题，修改的，这两份都需要：

https://gitee.com/wubi98/trime-98wubi/blob/master/pc.trime.yaml
https://gitee.com/wubi98/trime-98wubi/blob/master/pc.trime.custom.yaml

- ![打字时](https://raw.githubusercontent.com/yanhuacuo/trime-98wubi/main/1.jpg)

- ![状态栏](https://raw.githubusercontent.com/yanhuacuo/trime-98wubi/main/2.jpg)


## 期待改进

如果  keys 下一个键位也没有设置，就会报「空指针」错误，希望可以改进一下，允许「没有键位的虚拟键盘存在」。
目前就是把涉及到的值设为 0 ，让它的影响尽可能地小。

当然「状态栏」（提示中、英、简、繁、显、隐）的这一栏可以长驻，「状态栏」挺重要。

```
  "preset_keyboards/qwerty":
    name: 全功能布局
    author: "osfans <waxaca@163.com>"
    ascii_mode: 0
    columns: 10 #鍵盤列數，超過則自動換行，默認30列
    width: 10
    height: 0
    lock: true
    horizontal_gap: 0
    vertical_gap: 0
    key_symbol_offset_x: 0
    key_symbol_offset_y: 0
    key_text_offset_x: 0
    key_text_offset_y: 0
    key_hint_offset_x: 0
    key_hint_offset_y: 0
    key_press_offset_x: 0
    key_press_offset_y: 0
    keys:
      - {click: '1',swipe_left: 'Hide', swipe_right: 'Hide', swipe_up: 'Hide', swipe_down: 'Hide'}
```

**Comment by FEI352** [comment]
> 虽然同文已经内置了「迷你」的布局，但是这个「迷你」主题在「安卓平板横向使用」时，还是过于高大了。
> 
> 在【小米平板5pro】上：
> 
> 【设置】→【更多设置】→【语言与输入法】→【键盘、鼠标和触控板】→【使用屏幕键盘】（勾中）
> 
> 在【同文输入法设置】的【主题】中，选中【pc】，即可实现类 pc 那**悬浮候选框跟随光标**了。
> 
> 基于默认主题，修改的，这两份都需要：
> 
> https://gitee.com/wubi98/trime-98wubi/blob/master/pc.trime.yaml https://gitee.com/wubi98/trime-98wubi/blob/master/pc.trime.custom.yaml
> 
> * ![打字时](https://raw.githubusercontent.com/yanhuacuo/trime-98wubi/main/1.jpg)
> * ![状态栏](https://raw.githubusercontent.com/yanhuacuo/trime-98wubi/main/2.jpg)
> 
> ## 期待改进
> 如果 keys 下一个键位也没有设置，就会报「空指针」错误，希望可以改进一下，允许「没有键位的虚拟键盘存在」。 目前就是把涉及到的值设为 0 ，让它的影响尽可能地小。
> 
> 当然「状态栏」（提示中、英、简、繁、显、隐）的这一栏可以长驻，「状态栏」挺重要。
> 
> ```
>   "preset_keyboards/qwerty":
>     name: 全功能布局
>     author: "osfans <waxaca@163.com>"
>     ascii_mode: 0
>     columns: 10 #鍵盤列數，超過則自動換行，默認30列
>     width: 10
>     height: 0
>     lock: true
>     horizontal_gap: 0
>     vertical_gap: 0
>     key_symbol_offset_x: 0
>     key_symbol_offset_y: 0
>     key_text_offset_x: 0
>     key_text_offset_y: 0
>     key_hint_offset_x: 0
>     key_hint_offset_y: 0
>     key_press_offset_x: 0
>     key_press_offset_y: 0
>     keys:
>       - {click: '1',swipe_left: 'Hide', swipe_right: 'Hide', swipe_up: 'Hide', swipe_down: 'Hide'}
> ```

你好，本人小白，对于rime的理解仅限于抄作业，所以用了你的皮肤，如果我想调整PC皮肤的字体，应该修改那几个文件的那些代码呢？
![Screenshot_2023-08-11-00-54-01-889_com kiwibrowser browser-edit](https://github.com/osfans/trime/assets/104716040/5575c804-a276-4c3c-9d84-583fe8e88606)

**Comment by yanhuacuo** [comment]
> > 虽然同文已经内置了「迷你」的布局，但是这个「迷你」主题在「安卓平板横向使用」时，还是过于高大了。
> > 在【小米平板5pro】上：
> > 【设置】→【更多设置】→【语言与输入法】→【键盘、鼠标和触控板】→【使用屏幕键盘】（勾中）
> > 在【同文输入法设置】的【主题】中，选中【pc】，即可实现类 pc 那**悬浮候选框跟随光标**了。
> > 基于默认主题，修改的，这两份都需要：
> > https://gitee.com/wubi98/trime-98wubi/blob/master/pc.trime.yaml https://gitee.com/wubi98/trime-98wubi/blob/master/pc.trime.custom.yaml
> > 
> > * ![打字时](https://raw.githubusercontent.com/yanhuacuo/trime-98wubi/main/1.jpg)
> > * ![状态栏](https://raw.githubusercontent.com/yanhuacuo/trime-98wubi/main/2.jpg)
> > 
> > ## 期待改进
> > 如果 keys 下一个键位也没有设置，就会报「空指针」错误，希望可以改进一下，允许「没有键位的虚拟键盘存在」。 目前就是把涉及到的值设为 0 ，让它的影响尽可能地小。
> > 当然「状态栏」（提示中、英、简、繁、显、隐）的这一栏可以长驻，「状态栏」挺重要。
> > ```
> >   "preset_keyboards/qwerty":
> >     name: 全功能布局
> >     author: "osfans <waxaca@163.com>"
> >     ascii_mode: 0
> >     columns: 10 #鍵盤列數，超過則自動換行，默認30列
> >     width: 10
> >     height: 0
> >     lock: true
> >     horizontal_gap: 0
> >     vertical_gap: 0
> >     key_symbol_offset_x: 0
> >     key_symbol_offset_y: 0
> >     key_text_offset_x: 0
> >     key_text_offset_y: 0
> >     key_hint_offset_x: 0
> >     key_hint_offset_y: 0
> >     key_press_offset_x: 0
> >     key_press_offset_y: 0
> >     keys:
> >       - {click: '1',swipe_left: 'Hide', swipe_right: 'Hide', swipe_up: 'Hide', swipe_down: 'Hide'}
> > ```
> 
> 你好，本人小白，对于rime的理解仅限于抄作业，所以用了你的皮肤，如果我想调整PC皮肤的字体，应该修改那几个文件的那些代码呢？ ![Screenshot_2023-08-11-00-54-01-889_com kiwibrowser browser-edit](https://user-images.githubusercontent.com/104716040/259818469-5575c804-a276-4c3c-9d84-583fe8e88606.jpg)

这个↓，有注释。
https://gitee.com/wubi98/trime-98wubi/blob/master/pc.trime.custom.yaml

**Comment by wxyzh** [comment]
在候选栏加个开关
  - options: [_keyboard_.default, _keyboard_mini]
    states: [ "⌨️", mini]

**Comment by yanhuacuo** [comment]
> 在候选栏加个开关
> 
> * options: [_keyboard_.default, _keyboard_mini]
>   states: [ "⌨️", mini]

只是 MIIN 还不够 MINI

**Comment by wxyzh** [comment]
> > 在候选栏加个开关
> > 
> > * options: [_keyboard_.default, _keyboard_mini]
> >   states: [ "⌨️", mini]
> 
> 只是 MIIN 还不够 MINI
在另外写一个呗

**Comment by MokOopsing** [comment]
在自己用的主题里面加上一个mini键盘，然后按照以下示例进行配置

![image](https://github.com/osfans/trime/assets/39441028/8f0d1f9e-1524-4200-a27d-464dbe636229)

https://github.com/osfans/trime/pull/765

![image](https://github.com/osfans/trime/assets/39441028/0bc56ecb-f9db-4841-bfb7-30ec65f60e11)


https://github.com/osfans/trime/pull/765/files#diff-576044bfa960f926b690c474d29070c88459d69ad837f073d8249bb35a27c572R1009
![image](https://github.com/osfans/trime/assets/39441028/3256e183-636b-4d2b-93a1-a6d9c0cb58a5)

**Comment by controlledentropy** [comment]
> 在自己用的主题里面加上一个mini键盘，然后按照以下示例进行配置
> 
> ![image](https://user-images.githubusercontent.com/39441028/263211748-8f0d1f9e-1524-4200-a27d-464dbe636229.png)
> 
> #765
> 
> ![image](https://user-images.githubusercontent.com/39441028/263211403-0bc56ecb-f9db-4841-bfb7-30ec65f60e11.png)
> 
> https://github.com/osfans/trime/pull/765/files#diff-576044bfa960f926b690c474d29070c88459d69ad837f073d8249bb35a27c572R1009 ![image](https://user-images.githubusercontent.com/39441028/263211616-3256e183-636b-4d2b-93a1-a6d9c0cb58a5.png)

尝试了一下，按键区最多只能压缩到高度10-15左右，再压缩就只缩短键高但空白部分依然能出发按键，加上菜单栏基本能压缩到2行半的高度。只能说也能用了。

大佬能不能把几个月前说好的自动应用主题的鸽子放了啊，到现在最新的ci依然在修改.custom并重新部署后不会自动应用变更。。。。

**Comment by controlledentropy** [comment]
对了，添加mini切换开关之后，切小键盘没问题，且回全键盘就会崩溃，然后重启到全键盘。。。。

```switches/@next2:
    options: [_keyboard_default, _keyboard_mini]
    states: [ "⌨️", mini]

**Comment by wxyzh** [comment]
> 对了，添加mini切换开关之后，切小键盘没问题，且回全键盘就会崩溃，然后重启到全键盘。。。。
> 
> ```switches/@next2:
>     options: [_keyboard_default, _keyboard_mini]
>     states: [ "⌨️", mini]

你的主键盘是default吗？改成你的主键盘名称试试呢

**Comment by controlledentropy** [comment]
> > 对了，添加mini切换开关之后，切小键盘没问题，且回全键盘就会崩溃，然后重启到全键盘。。。。
> > ```
> >     options: [_keyboard_default, _keyboard_mini]
> >     states: [ "⌨️", mini]
> > ```
> 
> 你的主键盘是default吗？改成你的主键盘名称试试呢

哈哈哈感谢大佬，确实是键盘名称问题。我还以为default自动指向方案里配置的qwerty呢，现在搞定了。
不过这个键盘的写法之前没见到，yaml配置指南里也没讲下划线的用法。还好上面老哥的例子里mini键盘的写法是正确的

**Comment by MokOopsing** [comment]
> > 在自己用的主题里面加上一个mini键盘，然后按照以下示例进行配置
> > ![image](https://user-images.githubusercontent.com/39441028/263211748-8f0d1f9e-1524-4200-a27d-464dbe636229.png)
> > #765
> > ![image](https://user-images.githubusercontent.com/39441028/263211403-0bc56ecb-f9db-4841-bfb7-30ec65f60e11.png)
> > https://github.com/osfans/trime/pull/765/files#diff-576044bfa960f926b690c474d29070c88459d69ad837f073d8249bb35a27c572R1009 ![image](https://user-images.githubusercontent.com/39441028/263211616-3256e183-636b-4d2b-93a1-a6d9c0cb58a5.png)
> 
> 尝试了一下，按键区最多只能压缩到高度10-15左右，再压缩就只缩短键高但空白部分依然能出发按键，加上菜单栏基本能压缩到2行半的高度。只能说也能用了。
> 
> 大佬能不能把几个月前说好的自动应用主题的鸽子放了啊，到现在最新的ci依然在修改.custom并重新部署后不会自动应用变更。。。。

肯定不是我说的，我只是个稍稍熟悉的使用者

**Comment by MokOopsing** [comment]
https://github.com/mokapsing/trime/releases

我没有能力修bug，只能回退同文代码到之前的版本，在这个基础上更新librime及lua到最新，这个版本支持自动切换到mini键盘布局 @yanhuacuo @controlledentropy

**Comment by yanhuacuo** [comment]
> https://github.com/mokapsing/trime/releases
> 
> 我没有能力修bug，只能回退同文代码到之前的版本，在这个基础上更新librime及lua到最新，这个版本支持自动切换到mini键盘布局 @yanhuacuo @controlledentropy

这里楼里是目前最贴近【PC】键盘的：https://github.com/osfans/trime/issues/1058#issuecomment-1674126836

mini键盘，根本不mini，不如全部隐掉。

**Comment by MokOopsing** [comment]
> > https://github.com/mokapsing/trime/releases
> > 我没有能力修bug，只能回退同文代码到之前的版本，在这个基础上更新librime及lua到最新，这个版本支持自动切换到mini键盘布局 @yanhuacuo @controlledentropy
> 
> 这里楼里是目前最贴近【PC】键盘的：[#1058 (comment)](https://github.com/osfans/trime/issues/1058#issuecomment-1674126836)
> 
> mini键盘，根本不mini，不如全部隐掉。

自带的mini好不好用没关系，有自动切换的能力比较好，因为不用动切，你自定的主题中的mini适合自己就好了，默认的mini只是给你一个参考

**Comment by cabins** [comment]
设置里面打开那个〔连接实体键盘时，打开mini键盘〕的开关生效么？从代码上看，这里肯定是有bug的啊。代码里面连android:key都写错了的。

**Comment by qchenac** [comment]
> > > 对了，添加mini切换开关之后，切小键盘没问题，且回全键盘就会崩溃，然后重启到全键盘。。。。
> > > ```
> > >     options: [_keyboard_default, _keyboard_mini]
> > >     states: [ "⌨️", mini]
> > > ```
> > 
> > 
> > 你的主键盘是default吗？改成你的主键盘名称试试呢
> 
> 哈哈哈感谢大佬，确实是键盘名称问题。我还以为default自动指向方案里配置的qwerty呢，现在搞定了。 不过这个键盘的写法之前没见到，yaml配置指南里也没讲下划线的用法。还好上面老哥的例子里mini键盘的写法是正确的

我也想问下划线的用法，文档里没看到

**Comment by cabins** [comment]
> > > > 对了，添加mini切换开关之后，切小键盘没问题，且回全键盘就会崩溃，然后重启到全键盘。。。。
> > > > ```
> > > >     options: [_keyboard_default, _keyboard_mini]
> > > >     states: [ "⌨️", mini]
> > > > ```
> > > 
> > > 
> > > 你的主键盘是default吗？改成你的主键盘名称试试呢
> > 
> > 
> > 哈哈哈感谢大佬，确实是键盘名称问题。我还以为default自动指向方案里配置的qwerty呢，现在搞定了。 不过这个键盘的写法之前没见到，yaml配置指南里也没讲下划线的用法。还好上面老哥的例子里mini键盘的写法是正确的
> 
> 我也想问下划线的用法，文档里没看到

wiki中有这样的解释：
![image](https://github.com/osfans/trime/assets/2500123/73fbdb31-f975-4cce-8f92-d0097f15cdb1)


源码中也有这样的逻辑：
![image](https://github.com/osfans/trime/assets/2500123/7be3b622-d993-48ec-b85e-916c42b49233)

**Comment by qchenac** [comment]
> > > > > 对了，添加mini切换开关之后，切小键盘没问题，且回全键盘就会崩溃，然后重启到全键盘。。。。
> > > > > ```
> > > > >     options: [_keyboard_default, _keyboard_mini]
> > > > >     states: [ "⌨️", mini]
> > > > > ```
> > > > 
> > > > 
> > > > 你的主键盘是default吗？改成你的主键盘名称试试呢
> > > 
> > > 
> > > 哈哈哈感谢大佬，确实是键盘名称问题。我还以为default自动指向方案里配置的qwerty呢，现在搞定了。 不过这个键盘的写法之前没见到，yaml配置指南里也没讲下划线的用法。还好上面老哥的例子里mini键盘的写法是正确的
> > 
> > 
> > 我也想问下划线的用法，文档里没看到
> 
> wiki中有这样的解释： ![image](https://private-user-images.githubusercontent.com/2500123/297557103-73fbdb31-f975-4cce-8f92-d0097f15cdb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTg5ODcsIm5iZiI6MTcwNTU1ODY4NywicGF0aCI6Ii8yNTAwMTIzLzI5NzU1NzEwMy03M2ZiZGIzMS1mOTc1LTRjY2UtOGY5Mi1kMDA5N2YxNWNkYjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMDYxODA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGM1OGI2OTk0NDEyMjUxY2Q4ZWM4YTFkMWUxZGJiMGJiYjQ1Mzg2MWRhYTlmYzZlYjQ0NmRiZWY2NTE1MjIyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nLk98HMyf1Kox8f1RRj2UJQgAyVq7eCfWrWtJP6OmrE)
> 
> 源码中也有这样的逻辑： ![image](https://private-user-images.githubusercontent.com/2500123/297557098-7be3b622-d993-48ec-b85e-916c42b49233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTg5ODcsIm5iZiI6MTcwNTU1ODY4NywicGF0aCI6Ii8yNTAwMTIzLzI5NzU1NzA5OC03YmUzYjYyMi1kOTkzLTQ4ZWMtYjg1ZS05MTZjNDJiNDkyMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMDYxODA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTVhMDc4NDNkMTNmODAwYjgwNTkxM2FlODZkYWQyMTQxZDllODMzNTIyOWU2Y2YxNjFiYTg5MDYzOGQ4OWI2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xggX7tJn4Yzq1jT-li0DU68PmUaixKDTe3ZOncOBrTI)

多谢指教，我再去好好翻翻

**Comment by WhiredPlanck** [comment]
@yanhuacuo 请看新版本有无此问题。每夜版：https://github.com/osfans/trime/releases/tag/nightly
