### ISSUE TITLE
.9.png 背景图片不生效

### ISSUE THREAD

**Issue by nopdan** [osfans/trime#1061]
还是按照普通图片进行解析的

首次支持：https://github.com/osfans/trime/pull/462/files#diff-49eda8a1fb1f48c823d06bc9face01e6082e3e76fb638d8639d559ba9bc60ffcR684

重构：https://github.com/osfans/trime/commit/678eb8f71fcca679842935b79489fd98d224d525#diff-84bef8431fee961d3dfb1573407408b09d7b37d64f317a601ede96cd34d2d182R64

版本用的最新ci版。图片做的肯定没错，用ps，as还有网页工具做的均不生效。
主题配置也没问题，复制trime.yaml，只修改了其中的 key_back_color。

**Comment by shitlime** [comment]
昨天调试过程中，发现key_back_color参数解析有问题，

可能的影响：
1. 使用图片当按键背景（ `key_back_color` ）时，可能失效
2. 特别是在默认键盘（假设为a键盘）中不使用图片，在另一个键盘中使用图片（假设为b键盘），从a切换到b时，b读取不到 `key_back_color` 的实际值，读取到 `-1` （ 猜测： `-1` -> `0xFFFFFF` -> `白色` ），实际显示为纯白色……

很棘手，我也可能没时间修复了……
