### ISSUE TITLE
编码提示显示在右边时，无编码提示的候选下沉

### ISSUE THREAD

**Issue by nopdan** [osfans/trime#1062]
编码提示显示在上面是正常的
![image](https://github.com/osfans/trime/assets/47845580/a516285c-e0e4-4f36-af84-aa0c3bb07ee0)
![image](https://github.com/osfans/trime/assets/47845580/d07315d0-6e9e-47cc-875c-53ede3025bfb)

编码提示显示在右边
![image](https://github.com/osfans/trime/assets/47845580/89a1a412-f48e-4fec-a64f-5123df500235)
![image](https://github.com/osfans/trime/assets/47845580/87b4d7b9-1920-4f5e-80c2-05e33d082d03)
![image](https://github.com/osfans/trime/assets/47845580/160ee307-3790-4feb-a8a4-2abef3629a96)

## 同文版本
最新 ci 版

## 复现条件
编码提示设置为显示在右边，首选有编码提示（我是使用lua添加的提示）

则除了首选外的候选项，有提示的正常，无提示的下沉。

**Comment by WhiredPlanck** [comment]
@nopdan 请看新版本有无此问题。每夜版：https://github.com/osfans/trime/releases/tag/nightly
