### ISSUE TITLE
能不能做成IOS下仓输入法的功能？

### ISSUE THREAD

**Issue by tarkky** [osfans/trime#1063]
上下滑动按键实现不同的符号输入。
另外，候选字页面别用滚动条了，可以选择全键盘页面的候选字选择？
另附仓输入法的链接：https://github.com/imfuxiao/Hamster
谢谢作者。

**Comment by MokOopsing** [comment]
（难道读了比尔·盖茨的自传就可以成为比尔·盖茨？）

说实话，开源输入法（特别是同文）缺的不是提要求的人，需是缺开发者

https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3#%E5%9B%9Bandroid_keys

swipe_left: 左滑
swipe_right: 右滑
swipe_up: 上滑
swipe_down: 下滑

至于全键盘页面的候选字选择，也是可以的，可以配置同文液体键盘来实现。

![image](https://github.com/osfans/trime/assets/39441028/83b9e182-43ca-4867-bb56-77463bde7ea0)


有问题 应该先问有没有 再问能不能做

**Comment by tarkky** [comment]
> （难道读了比尔·盖茨的自传就可以成为比尔·盖茨？）
> 
> 说实话，开源输入法（特别是同文）缺的不是提要求的人，需是缺开发者
> 
> https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3#%E5%9B%9Bandroid_keys
> 
> swipe_left: 左滑 swipe_right: 右滑 swipe_up: 上滑 swipe_down: 下滑
> 
> 至于全键盘页面的候选字选择，也是可以的，可以配置同文液体键盘来实现。
> 
> ![image](https://user-images.githubusercontent.com/39441028/259012063-83b9e182-43ca-4867-bb56-77463bde7ea0.png)
> 
> 有问题 应该先问有没有 再问能不能做

非常感谢回复。
嗯，确实不能做伸手党。不过由于不是开发人员，没办法贡献编程力量，如果有捐赠链接的话麻烦贴出来，想略表心意。不过我确实搜索了一下，可能是关键字不准确没有结果，就没有再尝试搜素了。再次感谢

**Comment by MokOopsing** [comment]
我的意思是，开发者通过一个同类的软件的功能效果进行复刻不太容易，更何况不是一个平台的东西，另一个是同文的现状，已经没有什么活跃的开发者了，建议进同文群了解讨论一些功能的使用

**Comment by tarkky** [comment]
> 我的意思是，开发者通过一个同类的软件的功能效果进行复刻不太容易，更何况不是一个平台的东西，另一个是同文的现状，已经没有什么活跃的开发者了，建议进同文群了解讨论一些功能的使用

了解了。谢谢。我看群都是qq群，我虽然有qq，但是不怎么用的？有没有电报群？

**Comment by tarkky** [comment]
另外，请教一下，如何配置同文液体键盘？没搜到，不好意思。

**Comment by MokOopsing** [comment]
建议到同文qq群问问，我个人是不用液体键盘的，另外应该没有专门的同文tg群，或者我不知道

**Comment by shitlime** [comment]
> 另外，请教一下，如何配置同文液体键盘？没搜到，不好意思。

液体键盘教程：

https://github.com/tumuyan/trime-without-CMake/wiki/%E9%94%AE%E7%9B%98%E5%B8%83%E5%B1%80#%E6%B6%B2%E6%80%81%E9%94%AE%E7%9B%98

这是另一位开发者，也是液体键盘功能设计者亲手写的教程，很遗憾，在主线中并没有这个wiki。

仅供参考，因为液体键盘经历过重构，有一些细节可能有所变化，但是按这个教程入门没什么问题。

**Comment by controlledentropy** [comment]
> （难道读了比尔·盖茨的自传就可以成为比尔·盖茨？）
> 
> 说实话，开源输入法（特别是同文）缺的不是提要求的人，需是缺开发者
> 
> https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3#%E5%9B%9Bandroid_keys
> 
> swipe_left: 左滑 swipe_right: 右滑 swipe_up: 上滑 swipe_down: 下滑
> 
> 至于全键盘页面的候选字选择，也是可以的，可以配置同文液体键盘来实现。
> 
> ![image](https://user-images.githubusercontent.com/39441028/259012063-83b9e182-43ca-4867-bb56-77463bde7ea0.png)
> 
> 有问题 应该先问有没有 再问能不能做

哎，起始楼主这也反应出同文社群现在的活跃程度真的大不如前了。应当是所有纯配置文件的解决方案都难以被当下的大众接受，毕竟现在市场上的同类商业产品都具备优秀交互逻辑和丰富的配置接口，配置方法直观且符合直觉。

 我也算是同文老用户了，因隐私需求跳过来的。后来转入小鹤双拼增加了一些粘度，直到一个月前才花力气用一周时间详细学习和打造了自己的滑动输入方案。回头看看想想，这种学习梯度，对于我这个计算机专业的尚且感觉不好应付，对于普通用户，想开箱即用都做不到。如果稍微有一点定制需求，基本都劝退了（资料松散分布稀疏，配置参数多格式严，资料也远跟不上开发进度，调试实际效果也需要大量时间）
 
 论体验，可能同文到手用甚至远远不如停更好多年的谷歌拼音。之前见到很多小白来文文档里都有的问题，我也会觉得烦。后来想想，好像是太阳底下无新事。改变还是需要发生在同文社群这边，或者被历史慢慢落下。

**Comment by spew8712** [comment]
> 建议到同文qq群问问，我个人是不用液体键盘的，另外应该没有专门的同文tg群，或者我不知道

可以進RIME群：https://t.me/loverime，裡面也有同文用戶。

**Comment by spew8712** [comment]
> > 我的意思是，开发者通过一个同类的软件的功能效果进行复刻不太容易，更何况不是一个平台的东西，另一个是同文的现状，已经没有什么活跃的开发者了，建议进同文群了解讨论一些功能的使用
> 
> 了解了。谢谢。我看群都是qq群，我虽然有qq，但是不怎么用的？有没有电报群？

可以進RIME群：[https://t.me/loverime](https://t.me/loverime)，裡面也有同文用戶。
