### ISSUE TITLE
开启自动切换时，暗黑模式在白天重启后不会换回明亮模式

### ISSUE THREAD

**Issue by ddarfantasy** [osfans/trime#1071]
**Describe the bug**
开启自动切换时，暗黑模式在白天重启后不会换回明亮模式。

**To Reproduce**
Steps to reproduce the bug:
1. Android 系统设置自动开启深色模式
2. Trime 中设置自动切换配色方案
3. 在 Android 系统深色模式时关机
4. 在 Android 系统应该切换回明亮模式时开机

**Expected behavior**
Trime 自动切换为明亮配色

**Log**
N/A

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Independent
 - OS: Independent
 - Theme: Tongwenfeng
 - Version: 3.2.13
 - Build info: 
   ```
   Builder: F-Droid
   Build Time: 2023-07-03 04:07:35 UTC
   Build Version Name: v3.2.13-0-gc1cf0a73
   Git Hash: c1cf0a73
   Git Branch:
   Git Repo: https://github.com/osfans/trime
   ```
**Additional context**
N/A

**Comment by superLei** [comment]
+1

**Comment by goofyz** [comment]
現在若剛剛設定配色，然後手動切換系統的白天/夜晚模式的話，同文會正確切換配色。
可是若放置一段時間後，同文不會切換回白天模式。

Steps:
1. 「配色」選一包含明亮/暗黑的配色 (假設為 my_theme_day)
2. 開啟同文的「自動切換」
3. 手機設定夜晚開啟手機的夜晚模式
4. 到夜晚時，可以確認同文轉換為暗黑配色
5. 待到明早時，手機已經轉為白天模式，但同文仍然為暗黑配色
6. 同啟同文「配色」查看，會發現配色設定為 "my_theme_night"，而非一開始的 "my_theme_day"
