### ISSUE TITLE
华为P30，安装部署报错

### ISSUE THREAD

**Issue by cj000918** [osfans/trime#1076]
点击部署的时候
报下面的错

手机是鸿蒙系统

E/rime.trime(24916) error creating user data dir.
E/rime.trime(24916) failed to save config to stream.

**Comment by MokOopsing** [comment]
没有写入权限？

**Comment by gitbruc** [comment]
华为用啥输入法都行啊，没有隐私的

**Comment by WhiredPlanck** [comment]
请看新版本有无此问题。每夜版：https://github.com/osfans/trime/releases/tag/nightly
