### ISSUE TITLE
支持release打包

### ISSUE THREAD

**Issue by usc** [osfans/trime#1078]
尝试支持release打包，大佬帮忙看看是否可行？谢谢

1、添加release.keystore（.gitignore需要去掉）并且修改app/build.gradle.kts中的storeFile
```
 storeFile = rootProject.file("release.keystore")
```
2、workflows中release-ci.yml Setup keystore步骤大致如下，使用github action secrets存储密钥
```
      - name: Setup keystore
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        run: |
          touch keystore.properties
          echo storePassword="$SIGNING_STORE_PASSWORD" > keystore.properties
          echo keyPassword="$SIGNING_KEY_PASSWORD" >> keystore.properties
          echo keyAlias="$SIGNING_KEY_ALIAS" >> keystore.properties
```
3、release-ci.yml Build Trime 步骤修改为`make release`
4、release-ci.yml Add JNI cache 步骤`debug`修改为`release`

**Comment by wxyzh** [comment]
- name: Decode keystore 
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'keystore/test.jks'
          fileDir: '/home/runner/work/_temp/'
          encodedString: ${{ secrets.KEYSTORE }}
          
      - name: create keystore and properties file for signing the app   
        run: |
          echo "storeFile=/home/runner/work/_temp/keystore/test.jks" >> /home/runner/work/trime/trime/keystore.properties
          echo "keyAlias=$SIGNING_KEY_ALIAS" >> /home/runner/work/trime/trime/keystore.properties
          echo "storePassword=$SIGNING_STORE_PASSWORD" >> /home/runner/work/trime/trime/keystore.properties
          echo "keyPassword=$SIGNING_KEY_PASSWORD" >> /home/runner/work/trime/trime/keystore.properties

**Comment by Bambooin** [comment]
Actually we blocked by permission to set GitHub Action secret, we had key and password.

**Comment by wxyzh** [comment]
It's really heartbreaking

**Comment by Bambooin** [comment]
We can move Trime to rime project and setting the secret see #576.

**Comment by osfans** [comment]
@Bambooin ，参考这里设了四个secrets，看看够不够用。
https://github.com/marketplace/actions/sign-android-release#single-apk
```yaml
      signingKeyBase64: ${{ secrets.SIGNING_KEY }}
      alias: ${{ secrets.ALIAS }}
      keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
      keyPassword: ${{ secrets.KEY_PASSWORD }}
````

**Comment by WhiredPlanck** [comment]
> @Bambooin ，参考这里设了四个secrets，看看够不够用。 https://github.com/marketplace/actions/sign-android-release#single-apk
> 
> ```yaml
>       signingKeyBase64: ${{ secrets.SIGNING_KEY }}
>       alias: ${{ secrets.ALIAS }}
>       keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
>       keyPassword: ${{ secrets.KEY_PASSWORD }}
> ```

wow

**Comment by Bambooin** [comment]
应该够了，现在就可以把 GitHub 里面的 secret 导出 keystore.properties

```
      - name: Setup keystore
        run: |
          echo "set up keystore for release"
          echo "need help!!"
```

这样不会影响现有的 release-ci.yml

@usc 已经写了部分逻辑，还剩把 base64 转换成 key 文件

**Comment by WhiredPlanck** [comment]
@Bambooin base64 转文件可以通过
```sh
echo ${{ secrets.SIGNING_KEY }} | base64 --decode | cat >> signingkey.jks
```
实现。我在写了。
