### ISSUE TITLE
v3.2.4及之后版本使用四叶草九宫格方案输入卡死

### ISSUE THREAD

**Issue by gurecn** [osfans/trime#1085]
**Describe the bug**
使用3.2.14版本，配合四叶草九宫格输入方案时发现，发现卡顿。往后回滚版本，发现这个问题从3.2.4版本就开始存在了。而3.2.3版本正常。请分析该问题，谢谢

**To Reproduce**
1. 安装3.2.3版本，连续输入按键：64426（ninhao、你好），重复十次仍无明显卡顿。
2. 安装3.2.4或更新版本，重复以上动作，连续输入按键：64426（ninhao、你好），重复两次就开始卡顿。

**Expected behavior**

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**
输入显示参考云盘文件内截图。

**Smartphone (please complete the following information):**
 - Device: HUawei Mate 20
 - OS: HarmonyOS 3
 - Theme: 同文风增强版（九宫格模式）
 - Version:3.2.3正常、3.2.4及更高版本异常

**Additional context**
使用的四叶草方案和词库文件网盘下载：https://pan.quark.cn/s/b51f30082007

**Comment by gurecn** [comment]
好像破案了，猜测是编译版本的问题。debug版本时会卡顿，release版本就好很多。

**Comment by controlledentropy** [comment]
> 好像破案了，猜测是编译版本的问题。debug版本时会卡顿，release版本就好很多。

我这里是全键盘小鹤方案，不论用什么主题皮肤透明度还是默认也不论挂不挂字典，从3.2.10起，按键跟手程度大减，并且候选字出现的延迟非常大，当拼码堆起来之后（大概七字以后）就异常卡顿，输入和反馈之间的延迟甚至超过500ms
然而退回3.2.3经典版本重复相同输入，基本还是秒出。

**Comment by ldsj007** [comment]
请问release版本在哪下载，我找不到呢！

**Comment by controlledentropy** [comment]
> 请问release版本在哪下载，我找不到呢！

仓库页面右侧啊？都来gayhub了还在问白毒可以回答的问题。全局搜索以下release字段，浏览器也能给你指出来啊

**Comment by ldsj007** [comment]
![image](https://github.com/osfans/trime/assets/26075483/2cc6d5ba-2b8e-42bc-afa3-4fef173a78d6)
你指的是这里吗？这里我是知道的，但在这里面只有debug版啊！
![image](https://github.com/osfans/trime/assets/26075483/d7b3c5b8-e47a-45fa-9a7a-51be61d2da9f)

**Comment by controlledentropy** [comment]
> !你指的是这里吗？这里我是知道的，但在这里面只有debug版啊！ !

事实上trime很长一段时期都没有release版本了，将来相当一段事件也不会有。自从开发者计划开始部分重构摊子，只能说真 release遥遥无期

这个release的debug相比每天的ci，就算作是release了XD

**Comment by ldsj007** [comment]
> > ！你指的是这里吗？这里我是知道的，但这里只有调试版本啊！
> 
> 事实上trime很长一段时间都没有发布版本，未来相当一段时间也不会有。既然开发者计划开始部分重建摊子，只能说真正发布遥遥无期
> 
> 这个release的debug相比每天的ci，就算是release了XD

收到，明白了。

**Comment by su226** [comment]
> ![image](https://user-images.githubusercontent.com/26075483/272110571-2cc6d5ba-2b8e-42bc-afa3-4fef173a78d6.png) 你指的是这里吗？这里我是知道的，但在这里面只有debug版啊！ ![image](https://user-images.githubusercontent.com/26075483/272110687-d7b3c5b8-e47a-45fa-9a7a-51be61d2da9f.png)

[F-Droid](https://f-droid.org/packages/com.osfans.trime/)上的是Release版

**Comment by ldsj007** [comment]
> > ![图像](https://user-images.githubusercontent.com/26075483/272110571-2cc6d5ba-2b8e-42bc-afa3-4fef173a78d6.png)你指的是这里吗？这里我是知道的，但这里只有调试版啊！![图像](https://user-images.githubusercontent.com/26075483/272110687-d7b3c5b8-e47a-45fa-9a7a-51be61d2da9f.png)
> 
> [F-Droid](https://f-droid.org/packages/com.osfans.trime/)上是发布版


谢谢啦

**Comment by gurecn** [comment]
> 请问release版本在哪下载，我找不到呢！

我自己编了（哭笑）

**Comment by ldsj007** [comment]
> > ![图像](https://user-images.githubusercontent.com/26075483/272110571-2cc6d5ba-2b8e-42bc-afa3-4fef173a78d6.png)你指的是这里吗？这里我是知道的，但这里只有调试版啊！![图像](https://user-images.githubusercontent.com/26075483/272110687-d7b3c5b8-e47a-45fa-9a7a-51be61d2da9f.png)
> 
> [F-Droid](https://f-droid.org/packages/com.osfans.trime/)上是发布版

F-Droid版本部署会报错。但是正常使用。

**Comment by WhiredPlanck** [comment]
@gurecn 現在推出[每夜版](https://github.com/osfans/trime/releases/tag/nightly)了，試用一下還有問題嗎？

**Comment by Stephenzero** [comment]
> **Describe the bug** 使用3.2.14版本，配合四叶草九宫格输入方案时发现，发现卡顿。往后回滚版本，发现这个问题从3.2.4版本就开始存在了。而3.2.3版本正常。请分析该问题，谢谢
> 
> **To Reproduce**
> 
> 1. 安装3.2.3版本，连续输入按键：64426（ninhao、你好），重复十次仍无明显卡顿。
> 2. 安装3.2.4或更新版本，重复以上动作，连续输入按键：64426（ninhao、你好），重复两次就开始卡顿。
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Log** If applicable, add crash log to quick focus your problem.
> 
> **Screenshots** 输入显示参考云盘文件内截图。
> 
> **Smartphone (please complete the following information):**
> 
> * Device: HUawei Mate 20
> * OS: HarmonyOS 3
> * Theme: 同文风增强版（九宫格模式）
> * Version:3.2.3正常、3.2.4及更高版本异常
> 
> **Additional context** 使用的四叶草方案和词库文件网盘下载：https://pan.quark.cn/s/b51f30082007

四叶草方案在哪里下载？？？
