### ISSUE TITLE
请问可否添加候选字宽度修改功能

### ISSUE THREAD

**Issue by Nobody-Lee** [osfans/trime#1086]
您好，我在使用trime的时候，因为候选字间距过小很容易造成误触，可否适当调整一下候选字的间距，谢谢
候选字
![Screenshot_2023-09-29-11-53-37-774_mark via](https://github.com/osfans/trime/assets/84911629/644ce4c7-2b78-4de9-b039-b9826fe0ee3f)

**Comment by MokOopsing** [comment]
先问有没有，再问能不能加
https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3
![Screenshot_2023-09-30-12-53-14-928_com microsoft emmx](https://github.com/osfans/trime/assets/39441028/0f1c8105-9778-4eb1-9751-0665a9adf935)

**Comment by controlledentropy** [comment]
> 您好，我在使用trime的时候，因为候选字间距过小很容易造成误触，可否适当调整一下候选字的间距，谢谢 候选字 !

这个issue还不关闭？
