### ISSUE TITLE
键盘高度patch了，重新部署之后trime.yaml里面也同步了，可是无效

### ISSUE THREAD

**Issue by RyanLeeee** [osfans/trime#109]
如题，怎么上传图片，我截图了

**Comment by RyanLeeee** [comment]
customization:
  distribution_code_name: ""
  distribution_version: ""
  generator: "Rime-JNI"
  modified_time: "Wed Sep 14 09:26:41 2016"
  rime_version: 1.2.9
patch:
  "style/color_scheme": default
  "style/comment_height": 16
  "style/comment_text_size": 13
  "style/key_height": 80
  "style/key_text_size": 24
  "style/round_corner": 0.0
  "style/symbol_text_size": 9
  "style/text_height": 24
  "style/text_size": 18
这是我patch里面全部信息

**Comment by osfans** [comment]
看下最終的trime.yaml。

還有schema.yaml裏面可能也有key_height，會優先生效。

**Comment by RyanLeeee** [comment]
最终的trime.yaml里面也显示key_heigt： 80

**Comment by RyanLeeee** [comment]
schema.yaml里面没有关于key_heigt的项目
 # Rime schema

# encoding: utf-8

schema:
  schema_id: pinyin_simp
  name: 袖珍简化字拼音
  version: "0.8"
  author:
    - 佚名
  description: |
    源自 Android 拼音
  dependencies:
    - stroke

switches:
- name: ascii_mode
  reset: 0
  states: [ 中文, 西文 ]
- name: full_shape
  states: [ 半角, 全角 ]
- name: ascii_punct
  states: [ 。，, ．， ]

engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - script_translator
    - reverse_lookup_translator

speller:
  alphabet: zyxwvutsrqponmlkjihgfedcba
  delimiter: " '"
  algebra:
    - abbrev/^([a-z]).+$/$1/
    - abbrev/^([zcs]h).+$/$1/
    - derive/^([nl])ue$/$1ve/
    - derive/^([jqxy])u/$1v/
    - derive/un$/uen/
    - derive/ui$/uei/
    - derive/iu$/iou/
    - derive/([aeiou])ng$/$1gn/
    - derive/([dtngkhrzcs])o(u|ng)$/$1o/
    - derive/ong$/on/
    - derive/ao$/oa/
    - derive/([iu])a(o|ng?)$/a$1$2/

translator:
  dictionary: pinyin_simp
  preedit_format:
    - xform/([nl])v/$1ü/
    - xform/([nl])ue/$1üe/
    - xform/([jqxy])v/$1u/

reverse_lookup:
  dictionary: stroke
  enable_completion: true
  prefix: "`"
  suffix: "'"
  tips: 〔笔画〕
  preedit_format:
    - xlit/hspnz/一丨丿丶乙/

punctuator:
  import_preset: default

key_binder:
  import_preset: default

recognizer:
  import_preset: default
  patterns:
    reverse_lookup: "`[a-z]*'?$"

**Comment by osfans** [comment]
奇怪啊，要重新部署。想不到其他的可能了。

**Comment by RyanLeeee** [comment]
在设置里部署n遍无效....我是s7edge,6.0.1的系统。我试试重装输入法

**Comment by RyanLeeee** [comment]
我重新安装了输入法，并用同样的trime custom文件部署，第一次部署闪退，第二次部署成功，然后打字的时候无法弹出。显示 同文输入法已停止。。。

**Comment by ipcjs** [comment]
你给了trime文件存取权限没有？我刚装的时候就因为没权限导致一打开就无响应

**Comment by osfans** [comment]
開存儲權限了吧？可以把rime文件夹改名看看。有工具抓系统日志吗？抓到的话 可以找trime rime和native的相关日志

**Comment by RyanLeeee** [comment]
权限给了，原来是因为没有选配色，我选了个default就好了，但是最初的问题仍然没有解决，那就是patch已经同步到trime.yaml文件里面但是无效

**Comment by RyanLeeee** [comment]
改名 ？任意名字？抓日志我找找软件

**Comment by osfans** [comment]
哦 配色有问题啊 那手动改高度也没用吗

**Comment by xiaoqun2016** [comment]
`style`里面的`key_height`是全局**备用**参数。实际生效的高度是`preset_keyboards`里面每个键盘布局所设定的`height`。  （除非键盘布局中的`height`缺失，`key_height`才会生效）
这个在「trime .yaml详解」里面有提及。

**Comment by RyanLeeee** [comment]
谢谢!!

**Comment by RyanLeeee** [comment]
当初因为手头有点事情没折腾了，现在换成了ios。应用商店那个irime好像是盗版??

**Comment by osfans** [comment]
不是盜版，是另一個人開發的。

**Comment by RyanLeeee** [comment]
哦哦 谢谢 那个人好像违反了规定啥的，我不用

**Comment by osfans** [comment]
現在lib開源了，不過irime主程序還沒開源，聽說元旦時開源。

**Comment by RyanLeeee** [comment]
嗯嗯 您的团队有没有开发ios的意向👏

**Comment by osfans** [comment]
等別人開源了，可以一起合作的。

**Comment by RyanLeeee** [comment]
嗯嗯 👍👍👍
