### ISSUE TITLE
feature request: 支持密码管理器输入法内嵌填充

### ISSUE THREAD

**Issue by skymkmk** [osfans/trime#1090]
**Describe the solution you'd like**

诸如 BitWarden、KeePassDX 之类的密码管理器可以和支持密码内联的输入法（如 Gboard）进行联动，快捷输入密码，如下图所示

![Screenshot_2023-10-18-21-56-09-901_org mozilla firefox](https://github.com/osfans/trime/assets/62805286/d8b1c7a2-0532-4419-96ae-061829f032ad)

由于 Android 系统的碎片性，如果不使用输入法内联方案的话，密码管理器的磁帖不一定能百分百调起，所以希望可以支持输入法密码内嵌填充

**Additional context**

参考 Gboard

**Comment by ShellWen** [comment]
我看看我能不能做，我研究一下

**Comment by ShellWen** [comment]
参考：

https://developer.android.com/guide/topics/text/ime-autofill?hl=zh-cn

**Comment by ShellWen** [comment]
相关的 API 官方几乎没给什么说明，我正在试图逆向 GBoard 找到他们的实现，可能需要花点时间

**Comment by Eventide** [comment]
> 相关的 API 官方几乎没给什么说明，我正在试图逆向 GBoard 找到他们的实现，可能需要花点时间

fcitx5-android看起来也已经实现了。

**Comment by WhiredPlanck** [comment]
与 #1021 重复
