### ISSUE TITLE
按键冲突问题

### ISSUE THREAD

**Issue by skymkmk** [osfans/trime#1091]
**Describe the bug**
当 trime 作为默认输入法被激活时，tachiyomi 的音量键翻页功能无法正常使用。切换默认输入法后，该功能立刻恢复正常。由于我不使用其他类似功能的软件，所以这里特定写为 tachiyomi，其他类似监听有监听音量键功能软件是否正常不得而知。

**To Reproduce**
Steps to reproduce the bug:
1. 使用 Tachiyomi 并打开音量键翻页功能
2. 查看任意漫画
3. 复现

**Expected behavior**
按键事件可以正常传递

**Log**
无，但我自行编译并查看 onKeyDown 方法在 tachiyomi 中按下返回的值，发现是正常返回 false。由于我不了解 Android 开发以及不了解本项目架构，无法提供更多信息。

**Screenshots**
无

**Smartphone (please complete the following information):**
 - Device: Xiaomi 12S Pro
 - OS: Android 13
 - Theme: Not relevant but danjing on GitHub
 - Version: 3.2.14
 - Build info: 
   ```
   Builder: F-Droid
   Build Time: 2023-09-10 02:27:40 UTC
   Build Version Name: v3.2.14-0-ge6ed8804
   Git Hash: e6ed8804
   Git Branch: 
   Git Repo: https://github.com/osfans/trime
   ```

**Additional context**
软件完全退出，仅启动前台（软件前端）时，该功能仍正常，但键盘调起一次之后就立刻失效。
我曾经考虑是否是主题问题，于是我删除了主题中有关的功能配置，但仍无效。Trime 配置高度自由，如果是我的配置问题的话也烦请指教，谢谢大家！

**Comment by controlledentropy** [comment]
其他版本也有相同的问题么？试试3.1.3什么的，看看是遗留问题还是代码开始重构时引入的新问题。要不检查一下方案文件和布局配置中与音量按键相关的快捷组合和映射？

**Comment by skymkmk** [comment]
> 其他版本也有相同的问题么？试试3.1.3什么的，看看是遗留问题还是代码开始重构时引入的新问题。要不检查一下方案文件和布局配置中与音量按键相关的快捷组合和映射？

经测试，3.1.3 无法很好的读取我当前的配置文件，但使用默认配置 (似乎这个版本会自动生成皓月拼音的配置文件)可以正常翻页；3.2.14 删除所有的 **方案配置** （不是主题配置）之后也可正常翻页，但只要启用任一方案配置的话就无法翻页。我尝试搜寻有关音量配置项但未果，似乎音量键的监听只存在主题配置中，也有可能是我眼拙未发现。

我稍后上传配置文件，供大家参阅。

**Comment by skymkmk** [comment]
删除了用户偏好和编译结果，同时主题相关的音量配置仍保留。

[rime.tar.gz](https://github.com/osfans/trime/files/13063035/rime.tar.gz)

**Comment by goofyz** [comment]
Related #803

**Comment by shitlime** [comment]
目前使用同文和tachiyomi音量键翻页正常，版本信息：

```
建構者：shitlime
Git 倉庫：https://github.com/shitlime/trime.git
建構 Git 雜湊值：eb4999beaa5a021555c00f5d17f12555e375226e
建構時間：2024年1月16日 14:51:14
```
