### ISSUE TITLE
更改字号后，候选栏出现条线样

### ISSUE THREAD

**Issue by zaqzrh** [osfans/trime#11]
当调整系统“候选字号”和“键盘字号”后，输入板的候选栏出现一条线，一秒后消失。新旧版都有。
贴吧图：http://tieba.baidu.com/p/3793431224?pn=2

**Comment by osfans** [comment]
有更新了，再試試。不過，還沒能在yaml中自定義。

**Comment by zaqzrh** [comment]
贴吧#63的这现象trime-20150713.apk还存在！

**Comment by zaqzrh** [comment]
如果该线是滚动条，只用示意作用，线条太粗碍眼了，虽然短时，也会阻挡候选字，建议把它取消了，因为候选栏是可以左右滑动，或用▶、◀来翻页的。

**Comment by osfans** [comment]
滑動時應該會顯示滾動條。

**Comment by osfans** [comment]
確認是滾動條了？那就是谷歌默認的動畫。

**Comment by zaqzrh** [comment]
不是你改好了嗎？trime-20150729好像沒有提示線條了。
左右滑動的時候有線條樣。

**Comment by osfans** [comment]
我可沒改，哈哈

**Comment by zaqzrh** [comment]
@osfans
版本：trime-20160517.apk
问题：加设字符集后，输入板的候选栏再次出现一条线(滚动条)，一秒后消失。
成因：加“自定義字符集[gb2312,utf8]”后，显示超出状态栏屏幕范围。
建议：状态栏的问题能解决要解决。

**Comment by osfans** [comment]
那個正常，超過會出現滾動條，告訴你可以滾動。你可以把gb2312改成“常用”，讓它變短點。
