### ISSUE TITLE
候选词数量能自适应吗?

### ISSUE THREAD

**Issue by RyanLeeee** [osfans/trime#110]
候选词数量如何更改成自适应，或者变得多一些

**Comment by osfans** [comment]
可以變多，menu/page_size，但是目前還不能自適應。

**Comment by RyanLeeee** [comment]
好的 谢谢

**Comment by xlucn** [comment]
可以重开吗，我觉得这是一个合理的功能请求。固定数量的候选词在桌面系统上是合适的，但是在手机上自动分行会更好些。
尤其是不开悬浮窗的情况下，自动分行会更自然。

在屏幕宽度足够的情况下，可以依然遵循`page_size`等选项，与既有选项不冲突。

Edit：即候选词短时，行为是一致；但若候选词长了，便动态减少每行的数量
