### ISSUE TITLE
候选出字很生硬没有百度 搜狗 rime那种丝滑流畅的感觉怎么

### ISSUE THREAD

**Issue by Gowa2017** [osfans/trime#1105]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by oniondelta** [comment]
### 關注使用 trime 開發到現在，先對開發人員說聲辛苦了！

早期 trime 版本，用同個方案，相對後來版本輸入時絲滑許多！
部屬方案也快非常多(時間比除以 2 還更短)！
後來版本確實沒有 Google 輸入法等一眾手機輸入法絲滑！輸入時頓挫感明顯！
但後來版本確實修正一些 bug 並增加很多很不錯的功能👍🏻！

如今功能架構，已夠多且很夠用！
但人多嘴多，總有人提出增加某某新功能！
### 對 trime 再增新設定和功能覺得都可先不必！
### 期望未來 trime 開發方向往絲滑順暢方面進展！
### 再次感謝開發人員的付出😀

**Comment by Gowa2017** [comment]
有没有办法做一个测量看看是哪个环节慢了

**Comment by oniondelta** [comment]
確實可各環節測試巡檢一下，
哪邊可修改，使其更絲滑！
再強調誠心的建議：
可先暫緩增加任何新功能，建議以改善絲滑程度為優先！

經驗心得：
這邊兩隻手機，一隻很老舊，主要用來聽歌等雜活，裝的是 trime 3.2.1 版，
再新的版本安裝後無法使用，摸了許久，推測應該是 opencc 32位元和64位元因素，
較新的手機一路更新到現在 trime 3.2.14 版。
兩者皆用相同 rime 設定檔！trime 鍵盤檔雖不相同，但差不多，新版 trime 鍵盤檔多設剪貼板。
因此可比較新舊版。

1. 於 trime 3.2.8 版左右版本，trime 選單中改變候選詞數量，如非 rime 檔案中的設定，譬如候選詞數量依寬度等，就會卡到極度緩慢，到了 trime 3.2.14 版已改善很多！👍🏻但感覺還可以再優化？！
2. 新版部屬比舊版慢非常非常多！
3. 部屬完，第一次鍵盤跑出來的時間，新版慢舊版非常多！
4. 新版剪貼板如回刪、return 等功能設置，這邊會發生問題，設置按了後，有崩潰情形發生。

**Comment by controlledentropy** [comment]
其实目前trime的现状，还是有大把工作需要在重构和基本功能上，视觉效果反而是其次。毕竟作为生产力工具，trime首先要保证输入效率。不过现在项目的现状，大伙是知道的，只能说大家有能力的一砖一瓦慢慢来吧。

至于性能来说，当初3.2.11刚放出的时候是真的卡顿，后续滑动输入触发机制改进，可以正常使用了，现在对trime作为主力输入法还是很满意的。而且release版本确实比这里的ci要流畅很多。

**Comment by gshang2017** [comment]
v3.2.9版本编译的librime关闭了日志输出，option(ENABLE_LOGGING "" OFF) ，以后编译的版本默认是打开的。老设备如果觉得布署和出字有所卡顿可以测试下，这是自用的。
https://github.com/gshang2017/trime

**Comment by oniondelta** [comment]
### 感謝各位大大的付出！👍🏻
### 3.3.1版比起3.2.14 之前的幾版，變順暢非常的多！感恩感謝！
