### ISSUE TITLE
键盘太大了 占了手机屏的一半还多 能解释下面的代码吗？

### ISSUE THREAD

**Issue by zcjxjw** [osfans/trime#111]
style:  background_dim_amount: 0.5  border_width: 3  candidate_font: han.ttf  candidate_spacing: 5  candidate_text_size: 22  candidate_view_height: 28  color_scheme: default  comment_font: latin.ttf  comment_height: 12  comment_on_top: true  comment_text_size: 12  destroy_on_quit: false  display_tray_icon: false  hanb_font: hanb.ttf  hilite_padding: 2  hilite_spacing: 4  horizontal: true  horizontal_gap: 1  inline_code: true  inline_preedit: true  key_font: symbol.ttf  key_height: 44  key_sound: false  key_sound_volume: "-1"  key_text_size: 26  key_vibrate: false  key_vibrate_duration: 30  key_width: 10.0  keyboards:

**Comment by zcjxjw** [comment]
改了键盘高度值 改不小     声音改为true 音量改为50也没一点声音

**Comment by zcjxjw** [comment]
我把手机的字体调为特大 显示模式大 这样同文两笔的键盘就特大 超过屏的一半了
key_height: 44 改为30 无效
key_sound: false    改为true
key_sound_volume: "-1"  -1改为50
也没音效

**Comment by zcjxjw** [comment]
建议直接在设置里加些设置选项 不用太专业  我们是用输入法 不想成为专家

**Comment by xiaoqun2016** [comment]
放心吧，学会这个基础配置，距离成为专家还很远。  
 https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3  
键盘高度是在每个键盘布局中的`height`里设定。  
声音为`true`就够了，音量是通过手机系统控制的。
