### ISSUE TITLE
平板上，横屏使用分离键盘布局，而竖屏的时候，仍然时候普通的键盘布局

### ISSUE THREAD

**Issue by cabins** [osfans/trime#1111]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
希望能够针对平板（或者所有的设备）的横屏进行单独的键盘布局设置，例如横屏的时候使用分离式键盘(例如下图是Gboard的分离键盘，这个布局现在其实可以自己编写yaml实现)，而竖屏的时候仍然时候普通的键盘。

![图片](https://github.com/osfans/trime/assets/2500123/fc84e01b-fd38-480e-b459-42561ee20ab6)

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by FEI352** [comment]
mark
