### ISSUE TITLE
能不能增加候选区域

### ISSUE THREAD

**Issue by chwt163** [osfans/trime#1117]
现在的候选方式只有一行几个字，同音字太多的话，选字效率比较低。
如果能像fcitx那样做成下拉按钮，会快捷很多。

![QQ图片20231125164707](https://github.com/osfans/trime/assets/70951194/44ba55cc-7cf7-4aa8-9b13-db77112085c6)

![QQ图片20231125165124](https://github.com/osfans/trime/assets/70951194/0ec5bfb7-f22c-417f-b189-fe4f16ec37e2)

**Comment by chwt163** [comment]
可以在 lssues 这里分享主题吗？
这个是我自己更改的同文风主题，深色比较护眼：
[my.trime.yaml.zip](https://github.com/osfans/trime/files/13463431/my.trime.yaml.zip)


![Screenshot_20231125_163409_com example android no](https://github.com/osfans/trime/assets/70951194/b8592794-f7bb-4b0a-b6bf-03f4be37f392)

![Screenshot_20231125_163417_com example android no](https://github.com/osfans/trime/assets/70951194/7a1f43e0-e627-483d-920f-adc3f9803fd9)

**Comment by Sunpulseqd** [comment]
目前只支持单行候选  如果嫌候选区域太小  可以试试启用悬浮框 
![1201700989935_ pic](https://github.com/osfans/trime/assets/77373494/23c00612-cc31-4fab-9b55-9559b8da7d8b)

**Comment by MokOopsing** [comment]
支持液体键盘候选

**Comment by chwt163** [comment]
还是下拉覆盖式的候选窗比较好用，这也是我目前最期待 trime 能够实现的功能。

**Comment by chwt163** [comment]
> 支持液体键盘候选

液体键盘是什么功能？trime 主题里面的liquid_keyboard_window？

**Comment by controlledentropy** [comment]
这个功能，同文无障碍修改版（Arime）实现了，但目前版本停留在3.1.3好像，用起来其实挺轻快的，但无法跟进当前trime的新功能和优化。不过说实在的，arime的下拉选字，只能翻页不能滑动，体验不是很好，而且怎么调整布局都还是很辣眼睛。

目前使用悬浮窗，选字全靠手动优化排序了。。。

**Comment by goofyz** [comment]
> > 支持液体键盘候选
> 
> 液体键盘是什么功能？trime 主题里面的liquid_keyboard_window？

Liquid Keyboard 有「候選」
https://github.com/osfans/trime/blob/7e9b4ef65df41c74ff965b0c9b3d6d98aa0f2692/app/src/main/assets/rime/trime.yaml#L712-L714

新增一個 prest key，再加進你的 keyboard 中便可以了：
`"preset_keys/liquid_keyboard_candidate": { label: 候選字, send: function, command: liquid_keyboard, option: "候选" }`

不過此功能只能顯示當頁的候選字詞，建議在 `default.custom.yaml` 中將 `menu/page_size` 加至 30 (好像是最大值)。

當然，我同意下拉按鈕更直觀和方便。

**Comment by chwt163** [comment]
> > > 支持液体键盘候选
> > 
> > 
> > 液体键盘是什么功能？trime 主题里面的liquid_keyboard_window？
> 
> Liquid Keyboard 有「候選」
> 
> https://github.com/osfans/trime/blob/7e9b4ef65df41c74ff965b0c9b3d6d98aa0f2692/app/src/main/assets/rime/trime.yaml#L712-L714
> 
> 新增一個 prest key，再加進你的 keyboard 中便可以了： `"preset_keys/liquid_keyboard_candidate": { label: 候選字, send: function, command: liquid_keyboard, option: "候选" }`
> 
> 不過此功能只能顯示當頁的候選字詞，建議在 `default.custom.yaml` 中將 `menu/page_size` 加至 30 (好像是最大值)。
> 
> 當然，我同意下拉按鈕更直觀和方便。

谢谢！效果也不错。
