### ISSUE TITLE
输入方案的切换菜单，能不能增加切换到其它输入法的选项？

### ISSUE THREAD

**Issue by chwt163** [osfans/trime#1118]
比如谷歌 gboard 和 fcitx， 是可以互相切换的。

**Comment by Sunpulseqd** [comment]
IME_switch: {label: 🌐, send: LANGUAGE_SWITCH} #彈出對話框選擇輸入法

**Comment by chwt163** [comment]
> IME_switch: {label: 🌐, send: LANGUAGE_SWITCH} #彈出對話框選擇輸入法

这要单独占用一个键位，要是能合并到 Menu 里面就好了。
