### ISSUE TITLE
分享一个深色主题以及一个疑问，怎么偏移字符的显示位置？

### ISSUE THREAD

**Issue by chwt163** [osfans/trime#1120]
想让 key_symbol 符号显示在键位右上角，那样看起来显得不那么密集，稍微清爽一点。
- {click: q, long_click: '1', label: '空格空格空格1', key_back_color: bh1, key_text_color: th1}
这样直接添加 label 不行，q键被显示成了1，难道要每个符号都定义一个别名？
想要这种效果：
![285575728-44ba55cc-7cf7-4aa8-9b13-db77112085c6](https://github.com/osfans/trime/assets/70951194/d97c07f4-b2c7-4851-8e96-b38bf0a9cad8)

**Comment by chwt163** [comment]
这个是我自己更改的同文风主题，深色比较护眼，增加了中英切换和隐藏键盘的按钮，个人觉得这两个功能是比较常用的。
另外原版同文风主题的中文符号，缺失了分号和单引号的右侧，我这个补全了。
[my.trime.yaml.zip](https://github.com/osfans/trime/files/13465727/my.trime.yaml.zip)

![QQ图片20231126094724](https://github.com/osfans/trime/assets/70951194/1de83dbd-8c11-43b2-a059-137a9122c509)
![QQ图片20231126094729](https://github.com/osfans/trime/assets/70951194/df284df7-5335-4def-a0fd-08432db8c6fe)

**Comment by Sunpulseqd** [comment]
是的 要想覆盖默认title 需要另外定义一个

**Comment by csjtl** [comment]
key_symbol_offset_x: 15
https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3#%E9%94%AE%E7%9B%98%E5%B8%83%E5%B1%80
![Screenshot_20231126-204629_NMM~2](https://github.com/osfans/trime/assets/55336802/ed61971e-60e3-409c-a7df-4b62cc8a3521)

**Comment by chwt163** [comment]
> key_symbol_offset_x: 15 https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3#%E9%94%AE%E7%9B%98%E5%B8%83%E5%B1%80 

谢谢！

**Comment by controlledentropy** [comment]
好问题啊，感谢提问和解答，我也有空优化一下我的方案。同深色主题，护眼其次，省电第一（全局amoled黑 XD）
