### ISSUE TITLE
candidate_font 效果类似备用字体 / hanb_font 没有效果

### ISSUE THREAD

**Issue by csjtl** [osfans/trime#1121]
**Describe the bug**

**To Reproduce**
Steps to reproduce the bug:
1. 更换 candidate_font 文件后, 效果只有方框字被更换. 常用字没有更换, 类似备用字体. 同时更换 hanb_font 没有任何作用.
2. 字体文件使用 https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project 其它字体也试了.

全新开始这样配置:
  candidate_font: PlangothicP1-Regular.allideo.ttf
  hanb_font: PlangothicP2-Regular.ttf
只有P1用来替换原字体没有的方块，p2不起作用。
用一会p1替换的字又成方块，p2的字体替换p2区的方块。
这时更改 candidate_font 和 hanb_font 的参数，字体不会有变化。

https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3#%E9%99%84%E5%BD%95-schemayaml%E4%B8%AD%E7%9A%84trime
schema.yaml中的style 字体也不管用

**Log**
导出信息: [com.osfans.trime.debug-2023-11-26T06_46_42Z.txt](https://github.com/osfans/trime/files/13466241/com.osfans.trime.debug-2023-11-26T06_46_42Z.txt)

**Screenshots**

**Smartphone (please complete the following information):**
--------- Device Info
OS Name: lineage_xz2c-userdebug 13 TQ2A.230505.002 f84359c6d0
OS Version: 4.9.227-perf+ (f84359c6d0)
OS API Level: 33
Device: xz2c
Model (product): Xperia XZ2 Compact (lineage_xz2c)
Manufacturer: Sony
Tags: release-keys
Screen Size: 1080 x 2059
Screen Density: 2.1000001
Screen orientation: Portrait

   ```
   You could find build info in About Activity and click it to copy.
   e.g. 
--------- Build Info
Builder: Release CI
Build Time: 2023-11-01 11:08:28 UTC
Build Version Name: v3.2.15-0-g31894f63
Git Hash: 31894f63
Git Branch: v3.2.15
Git Repo: https://github.com/osfans/trime
   ```
**Additional context**

**Comment by yanhuacuo** [comment]
hanb_font  确认失效。

candidate_font 表现正常。

用的是最新 CI 自动编译的版本。
