### ISSUE TITLE
输入中文时，按符号可以直接上屏，为什么句号却是候选翻页而不是上屏？

### ISSUE THREAD

**Issue by chwt163** [osfans/trime#1123]
这是 bug 还是可以设置的功能？

**Comment by MokOopsing** [comment]
当然是可配置的，由你使用的主题文件决定的，文件名应为xxx.trime.yaml，找到对应按键的代码实现， 应该是composing这个地方，意为输入时，提供别的功能

**Comment by chwt163** [comment]
> 当然是可配置的，由你使用的主题文件决定的，文件名应为xxx.trime.yaml，找到对应按键的代码实现， 应该是composing这个地方，意为输入时，提供别的功能

但我确认我的句号键是没有 composing 的。

**Comment by goofyz** [comment]
看看 `key_bindings.yaml` 吧

**Comment by chwt163** [comment]
> 看看 `key_bindings.yaml` 吧

没有这个文件，查了其它 yaml 的 key_bindings 段落，也没有 composing

**Comment by goofyz** [comment]
你的 `xxx.shcema.yaml` 裏有沒有這段？
```
key_binder:
  import_preset: default
```
我理解為，有這段的話，會自動匯入 [key_bindings.yaml](https://github.com/rime/rime-prelude/blob/master/key_bindings.yaml) 的設定。

將其改為 
```
key_binder:
```
即可取消所有特別 binding.

**Comment by chwt163** [comment]
> 你的 `xxx.shcema.yaml` 裏有沒有這段？
> 
> ```
> key_binder:
>   import_preset: default
> ```
> 
> 我理解為，有這段的話，會自動匯入 [key_bindings.yaml](https://github.com/rime/rime-prelude/blob/master/key_bindings.yaml) 的設定。
> 
> 將其改為
> 
> ```
> key_binder:
> ```
> 
> 即可取消所有特別 binding.

谢谢！这个可行。
