### ISSUE TITLE
大家觉得 trime 的滑动输入，好用吗？

### ISSUE THREAD

**Issue by chwt163** [osfans/trime#1131]
trime 3.2.15

搜了一些帖子，试着改一些设置，还是一言难尽~
有人觉得好用吗？是使用默认配置，还是自定义了哪些地方，能不能分享一下？

**Comment by Wenti-D** [comment]
我打双拼，用的自己主题，把「触发按键滑动手势的速度」和「……距离」调成了 40 和 800，感觉还行。

**Comment by chwt163** [comment]
> 我打双拼，用的自己主题，把「触发按键滑动手势的速度」和「……距离」调成了 40 和 800，感觉还行。

谢谢！

**Comment by chwt163** [comment]
我发现trime跟fcitx的不同点，fcitx滑动之后，即使停住不动，然后再松手，滑动仍然是有效的，而trime就不行，一旦停下来，滑动就失效了，变成停止位置的那个按键了。
我觉得，忽略滑动的停止事件，比较好。打个比方，trime的滑动，似乎要像写毛笔字的撇和奈，最后收尾的笔锋要干脆漂亮，如果直接停下来，然后直接抬笔离纸，滑动就不成功了。
