### ISSUE TITLE
形碼造詞快捷鍵

### ISSUE THREAD

**Issue by zcjxjw** [osfans/trime#114]
希望同文超强两笔增加一个用户可增加词组的快捷键 这样方便随时随地增加用户词组 

总之希望很多win下的功能都能在手机版上实现
而不用太专业 只要快捷

**Comment by Prcuvu** [comment]
造词是自动的。Windows端也没有手动造词的功能啊？

**Comment by osfans** [comment]
@Prcuvu 那語句流中可以嗎？

**Comment by xiaoqun2016** [comment]
![1233](https://cloud.githubusercontent.com/assets/16501929/18630344/8e46b05c-7e9e-11e6-962f-c8fa0349977e.png)

原帖 http://tieba.baidu.com/p/3519094305?pid=62866975063&cid=#62866975063

**Comment by osfans** [comment]
所以 结论就是自动造词 不需要快捷键了？

**Comment by xiaoqun2016** [comment]
如果很多人都有这个需求，可以考虑。只怕是楼主不知道怎么自动造词，以为rime没有造词的功能，才提的这个issue。  
我是觉得自动造词已经很不错了。

**Comment by zcjxjw** [comment]
比如说极点二笔在你用快捷键Ctrl+“+”键时就会提示你加词组 再按Ctrl+“方向键”可保存3 4字的词组

还有万能键 就是这一笔你不知道怎么写 你可用?代替

你最好自己装一个极点二笔试用一下 就知道它一多好用
  ----- Original Message -----

**Comment by zcjxjw** [comment]
你是自动的 没有快捷键 我打了很多汽车上面的词组也没见他自动造词 所以说应该加一个快捷键
  ----- Original Message -----

**Comment by osfans** [comment]
快捷鍵：建議使用自動造詞。具體怎麼用，要學習下rime。
萬能鍵：建議使用反查輸入，比如臨時使用拼音輸入，它會提示完整的二筆編碼。
