### ISSUE TITLE
Unable to install on Play Store

### ISSUE THREAD

**Issue by ehyoitsdavid** [osfans/trime#1141]
**Describe the bug**

If you go to the direct link for the app to Play store it shows as follows on Android 14.
"This app is made for an older version of Android"

**To Reproduce**
Steps to reproduce the bug:
1. Go to play store link in readme
2. Observed the error

**Expected behavior**

**Log**
If applicable, add crash log to quick focus your problem.
N/A
**Screenshots**
![Screenshot_20231209_134433_Google Play Store.jpg](https://github.com/osfans/trime/assets/106898439/77e19145-9835-4327-851b-db279021226c)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S23
 - OS: Android 14 (U)
 - Theme: N/A
 - Version: v3.2.15
 - Build info: 
   ```
   You could find build info in About Activity and click it to copy.
   e.g. 
   Build: Commit CI
   Date: 2022-06-12 10:09 UTC
   Commit: v3.2.6-58-gd9b4c1f, 2022-06-12 17:58:14 +0800
   Branch: develop
   Repository: https://github.com/osfans/trime
   ```
**Additional context**

This is because of the Google mandatory minimum API on Play Store

**Comment by Bambooin** [comment]
See #997
