### ISSUE TITLE
请问这个液体候选键盘里的按键高度，是在哪里定义的？

### ISSUE THREAD

**Issue by chwt163** [osfans/trime#1142]
找了半天没找到。
![Screenshot_20231210_091007_com example android notepad](https://github.com/osfans/trime/assets/70951194/423070dc-175e-4ef5-897e-186f4f286961)

**Comment by goofyz** [comment]
可以看看 https://github.com/tumuyan/trime-without-CMake/wiki/%E9%94%AE%E7%9B%98%E5%B8%83%E5%B1%80#%E6%B6%B2%E6%80%81%E9%94%AE%E7%9B%98

**Comment by chwt163** [comment]
liquid_keyboard:
  key_height: 40      #按键高度
有这个，但是更改数值没有效果。
并且，liquid_keyboard 里其它的符号键高都一样，唯独候选字的键高是不一样的。

**Comment by goofyz** [comment]
又看了一下代碼，它似乎只以 `label_text_size` 來決定大小，其他什麼的沒有讀進去。

在 2023年12月15日週五 22:15，chwt ***@***.***> 寫道：

**Comment by chwt163** [comment]
> 又看了一下代碼，它似乎只以 `label_text_size` 來決定大小，其他什麼的沒有讀進去。

是的，liquid_keyboard 里，唯独候选字不受label_text_size 的设定，其它都可以。
