### ISSUE TITLE
横屏竖屏时使用不同的键盘高度

### ISSUE THREAD

**Issue by wei-zeng** [osfans/trime#115]
横屏时如果使用与竖屏时相同的键高，会占用很大一部分屏幕，希望能独立设置两种屏幕方向的键高。

**Comment by cmddot** [comment]
这个可以考虑一下的了。开发可以自动切换不同颜色配置的功能（高度在颜色配置中调节），是不是开发叫而言会简单一点？？

**Comment by Bambooin** [comment]
过时的 issue
