### ISSUE TITLE
增減方案時報錯，trime.yaml被復原

### ISSUE THREAD

**Issue by archerindigo** [osfans/trime#1150]
最近換了Google Pixel 8 Pro，安裝了同文v3.2.15，將[這個自訂的配置檔 trime_config.zip](https://github.com/osfans/trime/files/13680683/trime_config.zip)放進rime文件夾，設定好usr和share文件路徑後部署行列30，算是可以使用。不過trime.yaml內的自訂部份沒有生效，打開檔案發現被還原到內置的版本。

而且每當我更改啟用的方案時都會報錯，然後trime.yaml被還原到原來的版本。只有我在報錯後重新覆寫trime.yaml，再進同文設定介面內重選一次主題，不再部署，新的trime.yaml才會成功生效。

報錯後的日誌：[com.osfans.trime-2023-12-15T03_38_34Z.txt](https://github.com/osfans/trime/files/13680781/com.osfans.trime-2023-12-15T03_38_34Z.txt)

報錯後的rime文件夾狀態：[rime_crashed.zip](https://github.com/osfans/trime/files/13680801/rime_crashed.zip)

現在可以打字就算，無力深究問題根源。以上資源及檔案給各位開發者參考一下。

**Comment by csjtl** [comment]
更改trime.yaml部署会复原, 要改trime.custom.yaml文件
或者把trime.yaml改个名字xxxx.trime.yaml

**Comment by archerindigo** [comment]
謝謝，用patch的確有效

最後想問emoji_suggestion的功能在新版是否失效？
