### ISSUE TITLE
意见与Bug

### ISSUE THREAD

**Issue by PILIHU2022** [osfans/trime#1151]
当我在使用蓝牙或有线键盘输入时，会弹出窗口，如下图
![Image_1702722916030](https://github.com/osfans/trime/assets/100511118/e8ed916f-80b4-4acb-af7d-c2b8deb74426)
而并不像搜狗输入法，如下图
![Image_1702723126309](https://github.com/osfans/trime/assets/100511118/2d870105-29ad-4416-83aa-5e0a6973fa5d)
且候选栏中的字显示不完整，见下图
![Image_1702723241851](https://github.com/osfans/trime/assets/100511118/9b2a9471-d271-464d-8ae2-b9a3a3e6fbdf)
望能在下一个吧版本中解决该问题和改进，感谢伟大的开源项目开发者

**Comment by cabins** [comment]
可以看下CI的版本，这个问题应该已经解决了。
