### ISSUE TITLE
Lose input focus on unlocking screen 

### ISSUE THREAD

**Issue by Bambooin** [osfans/trime#1156]
**Describe the bug**
Lose input focus on unlocking screen.

**To Reproduce**
Steps to reproduce the bug:
1. Lock the screen.
2. Double click to wake up
3. See bug

**Expected behavior**
The input focus is on, and can input the password.

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**
![issue](https://github.com/osfans/trime/assets/7157227/69891566-f6b4-4501-910a-392227e98dd7)

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi]
 - OS: [e.g. Android 13 Lineage OS 20]
 - Theme: [e.g. Tongwenfeng]
 - Version: [#1152]
 - Build info: 
   ```
   You could find build info in About Activity and click it to copy.
   e.g. 
   Build: Commit CI
   Date: 2022-06-12 10:09 UTC
   Commit: v3.2.6-58-gd9b4c1f, 2022-06-12 17:58:14 +0800
   Branch: develop
   Repository: https://github.com/osfans/trime
   ```
**Additional context**

**Comment by goofyz** [comment]
I tried Pixel , Sony & Samsung. No problem found.
is the keyboard already ready (not display a "deploying" screen first before showing the actually keyboard) when in the lock screen？

**Comment by Bambooin** [comment]
This is random bug in my phone, but seems gone with latest commit in #1152
