### ISSUE TITLE
對輸入法指定鍵盤布局後崩潰

### ISSUE THREAD

**Issue by a0193143** [osfans/trime#1164]
**Describe the bug**
在`trime.custom.yaml`中對輸入法指定鍵盤布局後崩潰

**To Reproduce**
照著詳解對我的輸入法指定鍵盤布局，刪掉build下的`trime.yaml`後重新選擇trime主題
```yaml
patch:
  "preset_keyboards/hanlo/import_preset": qwerty0
```
**Expected behavior**
套用所選的布局

**Log**
[com.osfans.trime-2023-12-29T21_04_39Z.txt](https://github.com/osfans/trime/files/13796019/com.osfans.trime-2023-12-29T21_04_39Z.txt)

**Smartphone (please complete the following information):**
 - Device: Poco X3 Pro
 - OS: crDroid 9.11 (Android 13)
 - Theme: trime
 - Version: 3.2.15
 - Build info: 
```
Builder: F-Droid
Build Time: 2023-11-04 11:59:15 UTC
Build Version Name: v3.2.15-0-g31894f63
Git Hash: 31894f63
Git Branch: 
Git Repo: https://github.com/osfans/trime
```

**Comment by goofyz** [comment]
我之前也遇到此問題。看了代碼，似乎是 `import_preset` 不會正常運作。
暫時建議不要用 `import_preset`，將鍵盤布局複製一套過去吧。
