### ISSUE TITLE
扩充字体（hanb_font）与 unicode第二平面

### ISSUE THREAD

**Issue by yanhuacuo** [osfans/trime#1165]
在同文里，扩充字体似乎是【HAN_B_FONT】，但是没有找到定义它的点位信息。

第二平面，即表意文字补充平面（Supplementary Ideographic Plane），范围为：0x20000-0x2FFFF，目前计有六万多汉字。

如果 hanb_font 可以指定到这个平面上，则配合另一个候选字体，理论上可以在输入法内显示 12 万字。

但是当前的版本，hanb_font 是失效的，定义了它，也不能在输入法内显示 0x2A6D7 ~ 0x2A6DF 等点位。

**Comment by yanhuacuo** [comment]
hanb_font 如果能覆盖第二平面，扩B，扩C，扩D，扩E，扩F，扩I，康熙部首就都可以显示了

https://gitee.com/wubi98/wubi98-unicode/blob/master/python-Unicode/point.py#L40

```
cjk_B_42711_B = 0x20000
cjk_B_42711_E = 0x2a6d6

cjk_B_ext_9_B = 0x2a6d7
cjk_B_ext_9_E = 0x2a6df

cjk_C_4149_B = 0x2a700
cjk_C_4149_E = 0x2b734

cjk_C_ext_5_B = 0x2b735
cjk_C_ext_5_E = 0x2b739

cjk_D_222_B = 0x2b740
cjk_D_222_E = 0x2b81d

cjk_E_5762_B = 0x2b820
cjk_E_5762_E = 0x2cea1

cjk_F_7473_B = 0x2ceb0
cjk_F_7473_E = 0x2ebe0

cjk_I_622_B = 0x2ebf0
cjk_I_622_E = 0x2ee5d
 
cjk_JianRong_ext_542_B = 0x2f800
cjk_JianRong_ext_542_E = 0x2fa1d

```

**Comment by nopdan** [comment]
同文的补充代码点 U+10000 ~ U+10FFFF
https://www.unicode.org/glossary/#supplementary_code_point
