### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by yanhuacuo** [osfans/trime#1168]
刚发的这个
![Screenshot_2024-01-02-01-31-29-121_com osfans trime debug](https://github.com/osfans/trime/assets/3107994/a0ba16ff-cacb-4eee-8ef0-649cf97b0d65)
![Screenshot_2024-01-02-01-30-29-850_com miui thirdappassistant](https://github.com/osfans/trime/assets/3107994/12fb33b2-f547-4be4-a28d-e7b8c0b00a46)
![Screenshot_2024-01-02-01-30-40-753_com miui thirdappassistant](https://github.com/osfans/trime/assets/3107994/6035ae8c-637d-4987-ac0c-7b3ea86f3a67)
![Screenshot_2024-01-02-01-30-44-627_com miui thirdappassistant](https://github.com/osfans/trime/assets/3107994/8df2fa7d-865b-424d-826f-b60a6557708c)

**Comment by goofyz** [comment]
似乎是在揀選主題時出現閃退？
是否每次都必會出現 ?
有沒有詳細的重現步驟?

**Comment by yanhuacuo** [comment]
> 似乎是在揀選主題時出現閃退？ 是否每次都必會出現 ? 有沒有詳細的重現步驟?
安卓14，选择主题必崩，复现100%

**Comment by yanhuacuo** [comment]
> 似乎是在揀選主題時出現閃退？ 是否每次都必會出現 ? 有沒有詳細的重現步驟?

配置没有问题

**Comment by goofyz** [comment]
鍵盤可以正常使用？
若鍵盤彈出後，再入主題畫面，會否再閃退？

**Comment by yanhuacuo** [comment]
> 鍵盤可以正常使用？ 若鍵盤彈出後，再入主題畫面，會否再閃退？
一切正常时，选择主题，不会闪退，若「重新部署」过一次后，点选主题，必崩。

**Comment by goofyz** [comment]
我這邊幾部 android 14 也不能重現。看 code 理論上不會出現此問題，但就是出現了，找不到原因。 但要 fix 應該也容易。
