### ISSUE TITLE
請不要在從其他鍵盤切換到 Trime 時重新佈署 (deploy)！

### ISSUE THREAD

**Issue by random-integer** [osfans/trime#1169]
平常我在手機上打字，打中文就用 Trime，打英文則會切到我另外習慣的英文鍵盤，按安卓提供的切換鍵盤鍵（在我的 Samsung 手機上是左下的鍵盤圖示）來切換。以往這麼做的效果很好，只要點兩下就可以來回切換。

但自從 Trime 前幾天更新到 3.26.16 版後，我發現每次換到 Trime 都會強制重新佈署！每次佈署就要花3秒左右，對於時常切換鍵盤的我，是極大的不便！

望開發者們可以把這個行為恢復到以前那樣，不要在切換鍵盤時佈署。如果每次這樣佈署是另外有什麼考量的話，那請問可不可以在設定加個選項說不要在切鍵盤時佈署嗎？謝謝！

**Comment by goofyz** [comment]
在之前的版本，切換輸入法時，有沒有要等 2- 3 秒後才出現 keyboard 的情況？

**Comment by random-integer** [comment]
> 在之前的版本，切換輸入法時，有沒有要等 2- 3 秒後才出現 keyboard 的情況？

有欸！難道那就是 Trime 在部署？更新只是顯示正在部署而已？

**Comment by goofyz** [comment]
沒錯。現在只是多顯示一個 UI 而已。
（嚴格來說它不是在部署，只是在重構 keyboard 這 object，我看看能否在下一版本前，改善這部份的效能）

**Comment by random-integer** [comment]
> 沒錯。現在只是多顯示一個 UI 而已。 （嚴格來說它不是在部署，只是在重構 keyboard 這 object，我看看能否在下一版本前，改善這部份的效能）

原來，了解！謝謝你們這麼用心維護 Trime！
