### ISSUE TITLE
使用ESC键以后要按两次键盘才能重新开始输入的问题

### ISSUE THREAD

**Issue by CAPKLU** [osfans/trime#117]
我自定义的退格键布局：{click : BackSpace , swipe_left : Escape}，作用是快速清空候选区，和电脑键盘上的ESC键作用一样。
使用ESC键后第一次点击没有反应，要再点一次任意键才能重新开始输入。
版本平台:v3.0-beta2-58-g5b7db5d-20160708

**Comment by xiaoqun2016** [comment]
直接按手机的返回键，可以清空候选。  
`repeatable: true`的按键 使用swipe功能时确实会有你说的问题。

**Comment by osfans** [comment]
看来repeatable的问题多多 不过我好像修复了一部分 应该不会失效了 但多输入一个空格的问题仍有。

**Comment by xiaoqun2016** [comment]
不加`swipe`功能，也会有类似问题。  
重现条件：  
  - 默认的trime.yaml（`{click: BackSpace, width: 15}`）  
  - 在退格键上快速滑动  

现象：  
  - 退格键会一下删除两个字符（触发了两次退格键）  
  - 随后按任意键都会失效（额外触发的那个退格键没有释放？）  


---


这个问题也有好的方面：  
具有`repeatable: true`的按键，在滑动路径上不会触发沿途的按键。  

这对改善滑动效果应该有帮助

**Comment by osfans** [comment]
f538b637453aa87f80ca5e33d05d6a2238de38cf 解決
