### ISSUE TITLE
切换键盘时ascii_mode无效

### ISSUE THREAD

**Issue by somebody66** [osfans/trime#1170]
各个键盘都设置了ascii_mode，但切换键盘时并未生效。
比如：主键盘设有"ascii_mode: 0"，数字键盘设有"ascii_mode: 1"，在两键盘间切换时，键盘状态一直保持不变，只能手动切换

**Comment by shitlime** [comment]
尝试添加下面的配置到 `ascii_mode` 项的同级：
```
reset_ascii_mode: true
```

**Comment by somebody66** [comment]
成功了！多谢多谢！
还以为是无解bug😂
