### ISSUE TITLE
液体键盘BUG

### ISSUE THREAD

**Issue by MokOopsing** [osfans/trime#1177]
**Describe the bug**

**To Reproduce**
Steps to reproduce the bug:
4. See bug

**Expected behavior**

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**
1.悬浮按钮出现时机不正确
![image](https://github.com/osfans/trime/assets/39441028/128dab52-383c-4283-a1ed-28122e651a83)
![image](https://github.com/osfans/trime/assets/39441028/5c004d64-5ea9-4630-a137-56427b062fcc)

2."更多"tab页中，点击emoji，数字，英文会直接上屏字符串
![image](https://github.com/osfans/trime/assets/39441028/cf9b612c-1ff1-46ba-bfb6-67b6dfc16374)

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi Mix 4]
 - OS: [e.g. Android 11]
 - Theme: [e.g. Tongwenfeng]
 - Version: [e.g. 3.2.1]
 - Build info: 
   ```
   You could find build info in About Activity and click it to copy.
   e.g. 
   Build: self build
   Commit:  30f7513dad64c0a70dc37b21b31db961d93a8ae9
   Branch: develop
   Repository: https://github.com/osfans/trime
   ```
**Additional context**

**Comment by goofyz** [comment]
問題 2 是上次 commit 30f7513dad64c0a70dc37b21b31db961d93a8ae9 引起的問題。會儘快修正。

至於問題 1 應該跟它不相關。你是如何遇到的？候選欄位是隱藏的嗎？

**Comment by MokOopsing** [comment]
> 問題 2 是上次 commit [30f7513](https://github.com/osfans/trime/commit/30f7513dad64c0a70dc37b21b31db961d93a8ae9) 引起的問題。會儘快修正。
> 
> 至於問題 1 應該跟它不相關。你是如何遇到的？候選欄位是隱藏的嗎？

候选栏是隐藏的，就进入液体键盘不显示，出来到主键盘就显示出来了

**Comment by goofyz** [comment]
. 1.悬浮按钮出现时机不正确 ![image](https://private-user-images.githubusercontent.com/39441028/296934319-128dab52-383c-4283-a1ed-28122e651a83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTI0MTYsIm5iZiI6MTcwNTQ1MjExNiwicGF0aCI6Ii8zOTQ0MTAyOC8yOTY5MzQzMTktMTI4ZGFiNTItMzgzYy00MjgzLWExZWQtMjgxMjJlNjUxYTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAwNDE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYTU2NTcwN2JkMTJhYzg3ZDY5ZjRlNGNjNjFmZThiOGNmMDM1YTVhYjc4YzY3MTQ0N2ZlNjc5OWE5NmRkMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1DAvLq2v-rcAY71LLKbBgDOxQ0y5FDb9tjmT0QGM6W8)

可是這圖有主鍵盤但沒有候選欄，是你的個人設定，還是 bug?

**Comment by shitlime** [comment]
问题2已在 #1178 修复

问题1表现为液体键盘悬浮窗异常，有时能正确出现，有时在主键盘出现，有时完全消失……

**Comment by MokOopsing** [comment]
> . 1.悬浮按钮出现时机不正确 ![image](https://private-user-images.githubusercontent.com/39441028/296934319-128dab52-383c-4283-a1ed-28122e651a83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTI0MTYsIm5iZiI6MTcwNTQ1MjExNiwicGF0aCI6Ii8zOTQ0MTAyOC8yOTY5MzQzMTktMTI4ZGFiNTItMzgzYy00MjgzLWExZWQtMjgxMjJlNjUxYTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAwNDE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYTU2NTcwN2JkMTJhYzg3ZDY5ZjRlNGNjNjFmZThiOGNmMDM1YTVhYjc4YzY3MTQ0N2ZlNjc5OWE5NmRkMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1DAvLq2v-rcAY71LLKbBgDOxQ0y5FDb9tjmT0QGM6W8)
> 
> 可是這圖有主鍵盤但沒有候選欄，是你的個人設定，還是 bug?

隐藏候选栏是因为我的个人配置，请忽略
