### ISSUE TITLE
[BUG]同文输入法与索尼自带相机app冲突

### ISSUE THREAD

**Issue by CAPKLU** [osfans/trime#119]
Sony的xperia系列有实体快门键，使用同文输入法后快门键无法正常工作。症状是只能启动自带相机应用，对焦功能不正常，反复对焦，按下后不能拍照。
停用同文输入法后恢复正常，启用后问题重现。现在测试受影响的机型至少有：z3国行，z3 dual，z3 compact港版，z5 compact港版。系统从5.0到6.0都有，都是官方固件，没有root。

第三方相机应用大部分都受影响。除了open camera，在设置中选择使用camera2 API后快门键能正常使用。

版本平台:v3.0-beta2-58-g5b7db5d-20160708

**Comment by CAPKLU** [comment]
这个问题有点诡异，因为我是在系统刚升级到5.0的时候开始使用同文输入法的，所以一直以为是系统bug。
我猜测可能是打开相机app后键盘在取景区后面弹出了，按下对焦后键盘反复隐藏弹出，所以才会反复对焦，而快门键是两段式的，对焦不正常快门就不会有反应。
这里还有补充一点，就是在锁屏界面按下快门的快速启动并拍照功能是正常的，大概是在这个过程里直接跳过了按下对焦的过程。
如果真是这样的话这个问题在其他app里应该也有，感觉是有风险的。不仅拖慢系统，耗电量也会增加。

**Comment by xiaoqun2016** [comment]
要不要关掉嵌入模式试试？

**Comment by CAPKLU** [comment]
@xiaoqun2016 
试着设置
"style/inline_preedit": none
没有变化，问题依旧。

**Comment by osfans** [comment]
@CAPKLU  有修復，要不要幫忙測試下？

**Comment by CAPKLU** [comment]
@osfans 我对 android 开发不了解且始终没有成功 clone 这个仓库，请把需要测试的 APK 包发送给我。我现在手上有 Z3C 和 Z5C 两部。

**Comment by osfans** [comment]
谷歌市場有放了一個測試版，但是不知怎麼找到它安裝它。
因爲上了谷歌市場，所以簽名換了，要刪掉以前的APK再安裝新的。

github上我傳了一個：https://github.com/osfans/trime/releases/download/v3.0/trime-20170119.apk

**Comment by CAPKLU** [comment]
@osfans 20170119 问题依旧，没有变化。

**Comment by osfans** [comment]
有沒有相機的APK？我安裝下試試。

**Comment by CAPKLU** [comment]
@osfans 并没有相机的 APK，因为是自带的相机 APP。

**Comment by osfans** [comment]
我說的就是SONY自帶的APP，因爲我們自帶的沒有問題，沒辦法測試。我上網找找。

**Comment by xiaoqun2016** [comment]
>第三方相机应用大部分都受影响

不像是某个相机app的问题。是不是实体快门键被识别成物理键盘了？

结合issue #101 来看，会不会是同一个问题？ 同文在没有激活文本框时，就已经开始工作了？

**Comment by osfans** [comment]
跟之前計算器的問題也蠻相似的。但是我這裏沒辦法測試。

**Comment by xiaoqun2016** [comment]
没有相机键，我也没办法测试。   
如果先解决掉101，那119这个问题估计也会消失。  （瞎猜）  
同文太勤快了，得限制它的工作区间……

**Comment by osfans** [comment]
@CAPKLU 還有個Focus鍵，又改了一版，請幫忙測試，感謝！
https://github.com/osfans/trime/releases/download/v3.0/trime-20170122.apk

**Comment by osfans** [comment]
確實要限制下，要不設個不啓用輸入法的程序列表。還有不處理的按鍵列表。

**Comment by CAPKLU** [comment]
@osfans 20170122 在 Z3C 和 Z5C 上测试成功，能够正常对焦和拍照。请问你是怎样做到的，非常好奇。 ：）
系统都是 6.0.1。

**Comment by xiaoqun2016** [comment]
相机、计算器怎么会调用输入法呢？有点纳闷……
没激活文本框时，不能禁用输入法吗，不太懂，只是觉得有点奇怪

**Comment by osfans** [comment]
不太懂，爲什麼有些系統裏面會調輸入法，因爲有文本框？
感謝！那我先上提交。
