### ISSUE TITLE
雙擊shift大寫鎖定

### ISSUE THREAD

**Issue by jkwchk** [osfans/trime#12]
希望加入雙擊shift大寫鎖定功能

**Comment by zaqzrh** [comment]
长按或向上滑可以锁定shift大写(变色)

**Comment by jkwchk** [comment]
其他輸入法一般double click就可以鎖定，所以希望加上這個
2015/07/22 23:47 "zaqzrh" notifications@github.com:

**Comment by osfans** [comment]
我試試

**Comment by Bambooin** [comment]
@jkwchk 最新版，同文风主题，中文状态下，点击 Shift 会切换 成 分词 按键，可以一直输入 大写
