### ISSUE TITLE
`preset_keys` 中自定义按键的 `text` 标签失效

### ISSUE THREAD

**Issue by Wenti-D** [osfans/trime#1208]
**Describe the bug**
按下 Return 键，输入码出现「Return」，而不是发送回车。

**To Reproduce**
Steps to reproduce the bug:
- 把一个键设定为`{click: Return}`；
- 按一下它。

**Expected behavior**
应当发送回车。

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**
![image](https://github.com/osfans/trime/assets/73067578/5bfc04e4-a06e-40d5-b485-d4290e11dc06)

**Smartphone (please complete the following information):**
 - Device: HUAWEI P40 Pro
 - OS: Harmony OS 4（Android 12 兼容）
 - Theme: [星天](https://github.com/Wenti-D/Astralwelkin)
 - Version: 3.2.17
 - Build info: 
   ```
   构建者：Windy Deng
   Git 仓库： https://github.com/osfans/trime.git
   构建 Git 哈希：f566a1a546c833b75cded228a45af0cc3a9f35bb
   构建时间：2024 年 1 月 25 日 22:43:03
   ```
**Additional context**
默认主题的 Enter 键是正常的。

**Comment by goofyz** [comment]
你檢查一下主題的 `android_preset_keys` 有沒有 `Return`

**Comment by Wenti-D** [comment]
发现问题可能出在处理组合键的逻辑中，仓库 Wiki 里《trime.yaml 详解》第五节 `preset_keys` 中有：

> 例 5: 自定义组合键
> 
> 使用text可以实现一些比较复杂的操作
> 比如：
> `overwrite: { text: "{Control+a}{Control+v}", label: 覆盖 }`

我的 Return 按键采用了这样的操作：

    Return: {label: '↵', repeatable: true, text: "{Return}{Eisu_toggle}"}

但是似乎失效了？

**Comment by nopdan** [comment]
可能是 #1202 引入的 bug，我会查看

**Comment by Wenti-D** [comment]
测试了一下，在 `preset_keys` 中写下：

    Return: {label: '↵', send: Return}
    Return1: {label: '↵', repeatable: true, send: Return}
    Return2: {label: '↵', repeatable: true, text: "{Return1}{Eisu_toggle}"}

结果
- 令回车为 `Return` 正常；
- 令回车为 `Return1` 正常；
- 令回车为 `Return2` 无效；

所以应该是组合键失效了。

**Comment by goofyz** [comment]
你試試轉回預設的 `trime` 主題看看是否正常

**Comment by Wenti-D** [comment]
> 你試試轉回預設的 `trime` 主題看看是否正常

是这样的，预设主题的回车键就如我上述所写的 `Return` 一样，它是正常的，但只要换成内含 `text` 用于执行组合键操作的标签时就出问题了。

这样看来议题标题得改（

**Comment by Wenti-D** [comment]
新现象，我自定义的键 `Transform: {text: "_", label: '゛゜ぁ'}` 会把「Transform」送到输入码，改成 `Transform: {send: "_", label: '゛゜ぁ'}` 则不会，但下划线送了两次。

**Comment by goofyz** [comment]
我的鍵 `has_menu: "{Return1}5"` 也會 crash，排查了一會，是在 has_menu: "{Return1}5" a650fcb80627539c8074bc6304994869387df36e 後才出現。
將 `Event.kt`  變回 `Event.java` 就沒事兒了。未找到確切原因。
