### ISSUE TITLE
flyme 安装无法正常使用

### ISSUE THREAD

**Issue by gege01** [osfans/trime#121]
安装同文输入法之后在rime文件夹中添加essay.txt;
default.yaml;symbols.yaml;所有在pc小狼豪用户文件夹中的以pinyin开头文件。并回厂，部署。依旧无法正常使用。
机型:魅蓝u10，系统:flyme5.2.3.1y。

**Comment by osfans** [comment]
可能是rime文件夹不对 里面有trime.yaml文件吗

**Comment by gege01** [comment]
我又回来确定了一下，trime.是有的

**Comment by osfans** [comment]
權限也開了？把bin文件刪掉，看看能不能成功。

**Comment by gege01** [comment]
基本上权限是没问题的，必须权限不全的话可能连安装都成问题。而且一些文件夹确实是软件自己创建的。

而bin文件。。我在手机上的rime文件夹并没有找到以bin为结尾的文件。

另外我写简体中文您看起来不吃力吧。

**Comment by osfans** [comment]
不吃力，簡繁都用的。沒有bin的話，就是部署沒成功，你點方案，然後選擇方案看看，有沒有bin生成。

**Comment by gege01** [comment]
选择方案我试过， 但是实际上现在就这样， 我再试试。

不过不知道您是否做过此软件在flyme平台上的适配呢？ 而且目前好像没有用于调试flyme系统下软件的pc软件。您如果需要我这个设备可以供您远程调试。当然需要我先部署一些东西，pc和手机都是我最近才到手的，而且pc是古老的win7。同时还要保证网络畅通和您有时间。另外我不是要求您帮我调试，只是您有意向的话我可以提供设备的远程。

**Comment by gege01** [comment]
再次确认 在方案中勾选好之后也无法正常使用。

**Comment by osfans** [comment]
沒有測試過flyme，要不你加QQ羣討論吧，523571568，我傳個打包的版本。

**Comment by gege01** [comment]
我也不确定是不是我步骤那里做错了。因为flyme我也是刚刚才开始用。老手机已经几乎不能用了。。我在别的机器上试试。

**Comment by gege01** [comment]
我找到问题了 是词库没拽进去。。。。重新安装 ，词库拽进去就好了。
