### ISSUE TITLE
支持自定义底部导航栏颜色

### ISSUE THREAD

**Issue by nopdan** [osfans/trime#1212]
在配色中添加 nav_bar_color，切换配色后自动刷新

**Comment by nopdan** [comment]
btw: @goofyz @Bambooin 两位不是大陆人士吗，我觉得几位开发者应该组建一个即时通讯群组，提升一下交流效率。。qq 不方便的话 tg, discord, matrix…… 随便哪个都可以

**Comment by goofyz** [comment]
我只有 tg
