### ISSUE TITLE
pre 3.2.17 跟隨系統自動切換主題顏色異常

### ISSUE THREAD

**Issue by developor** [osfans/trime#1215]
正常顯示應該是這樣
![Screenshot_2024-01-29-11-52-26-467_com android chrome-edit](https://github.com/osfans/trime/assets/67617330/3662bfac-2613-4a3a-b999-0220fd992a3b)
![Screenshot_2024-01-29-11-52-40-164_com android chrome-edit](https://github.com/osfans/trime/assets/67617330/e9f0c567-318d-424b-94da-34f7c4104c79)
pre 3.2.17 版本卻顯示這樣
![Screenshot_2024-01-29-11-53-48-842_com google android googlequicksearchbox-edit](https://github.com/osfans/trime/assets/67617330/7a40bf4e-c1fc-4646-891d-bd6410f09354)
![Screenshot_2024-01-29-11-54-01-332_com google android googlequicksearchbox-edit](https://github.com/osfans/trime/assets/67617330/89594d5c-4a39-4b77-a9d9-21e03f9f2942)
即使手動切換，某些按鈕的主題色也不見了
![Screenshot_2024-01-29-11-54-15-613_com google android googlequicksearchbox-edit](https://github.com/osfans/trime/assets/67617330/db57dbfa-9d28-49a1-9218-e647a3710f07)

**Comment by nopdan** [comment]
此问题我已经排查清楚了

**Comment by developor** [comment]
> 此问题我已经排查清楚了

bug 還在喔
![Screenshot_2024-01-30-01-36-16-497_com android chrome-edit](https://github.com/osfans/trime/assets/67617330/a834fe6d-a681-480f-bd74-501c10f09994)
![Screenshot_2024-01-30-01-35-52-903_com google android googlequicksearchbox-edit](https://github.com/osfans/trime/assets/67617330/dcd1989a-aae9-491a-85cb-ef3782c533f0)
![Screenshot_2024-01-30-01-35-39-185_com google android googlequicksearchbox-edit](https://github.com/osfans/trime/assets/67617330/73ead30f-5a98-445d-977e-8c026860fd57)

**Comment by developor** [comment]
> 此问题我已经排查清楚了

大佬有空可幫忙排查一下 ？
[xiaohe.zip](https://github.com/osfans/trime/files/14087757/xiaohe.zip)
