### ISSUE TITLE
_hide_candidate选项失效（1月31日，夜版）

### ISSUE THREAD

**Issue by cabins** [osfans/trime#1217]
**Describe the bug**
_hide_candidate选项失效，候选栏始终显示

使用的是1月31日的夜版。

**Comment by WhiredPlanck** [comment]
@cabins 今天凌晨的每夜版应该已经修复了此问题

**Comment by cabins** [comment]
> @cabins 今天凌晨的每夜版应该已经修复了此问题

Emm...不确定我的测试结果是否可靠，我这里……还是不生效。之前的时候能够将整个候选栏隐藏了，但现在还是隐藏不了。

**Comment by WhiredPlanck** [comment]
> > @cabins 今天凌晨的每夜版应该已经修复了此问题
> 
> Emm...不确定我的测试结果是否可靠，我这里……还是不生效。之前的时候能够将整个候选栏隐藏了，但现在还是隐藏不了。

我无法复现，我这里是正常的

**UPDATE:** 换主题会重新出现，失去了原有的记忆性，稍晚时候修复

**Comment by cabins** [comment]
我对比了release的3.2.16，（在平板上同时安装了夜版和3.2.16，使用相同的一套配置），发现3.2.16就是正常的可以隐藏的；但nightly的无法隐藏掉候选栏。

**Comment by cabins** [comment]
基本是生效了的。但是有一个问题：每次光标聚焦到输入框的时候，会弹出来一个空白的条。切换一下输入方案，就消失了（或者按一下ESC就消失了）。但再次聚焦到输入框的时候，还是会弹出来一个空白的条在屏幕的底部。
