### ISSUE TITLE
App crashes when I click theme and color

### ISSUE THREAD

**Issue by chenhuicui** [osfans/trime#1218]
**Describe the bug**
App crashes when I click theme and color
**To Reproduce**
Steps to reproduce the bug:
Do not perform any pre-operation, enter settings, click on theme and color matching, and after color matching, the app crashes and reports IException.

**Expected behavior**

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: huawei nova 5 pro
 - OS: android 10
-  version: 3.2.14]
 - Build info: 
   ```
   You could find build info in About Activity and click it to copy.
   e.g. 
   Build: Commit CI
   Date: 2022-06-12 10:09 UTC
   Commit: v3.2.6-58-gd9b4c1f, 2022-06-12 17:58:14 +0800
   Branch: develop
   Repository: https://github.com/osfans/trime
   ```
**Additional context**

**Comment by nopdan** [comment]
请使用 [nightly](https://github.com/osfans/trime/releases/tag/nightly) 版本
