### ISSUE TITLE
主题的 `keyboard_padding` 选项会切割键盘而不是压缩键盘。

### ISSUE THREAD

**Issue by Wenti-D** [osfans/trime#1226]
**Describe the bug**
设定键盘左右边距会切掉边上的键

**To Reproduce**
1. 在主题中将 `keyboard_padding` 或 `keyboard_padding_land` 设定为大于 0 的值；
2. 应用主题，可见键盘边缘被切掉了一部分。

**Expected behavior**
键盘整体宽度应压缩来适应此值。

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**
（竖屏 5，横屏 50 的效果）
![vert](https://github.com/osfans/trime/assets/73067578/1daf5c6a-981d-4ed1-89ed-15c54a79b42b)
![horiz](https://github.com/osfans/trime/assets/73067578/dc6b131e-cd3b-42f5-8106-02959c26287c)

**Smartphone (please complete the following information):**
 - Device: HUAWEI P40 Pro
 - OS: Harmony OS 4（Android 12 兼容）
 - Theme: [星天](https://github.com/Wenti-D/Astralwelkin)
 - Version: 3.2.17 nightly 29
 - Build info: 
   ```
   构建者：Windy Deng
   Git 仓库： https://github.com/osfans/trime.git
   构建 Git 哈希：d814b1836ea22486837e1a32025e3445064333b3
   构建时间：2024 年 2 月 4 日 17:45:28
   ```
**Additional context**
可在默认主题复现。
![trime](https://github.com/osfans/trime/assets/73067578/3bd21668-4ecc-4652-95a4-541501d6ae7e)

**Comment by nopdan** [comment]
#1223 已经修了
