### ISSUE TITLE
带调双拼在trime中卡顿问题

### ISSUE THREAD

**Issue by hetefei** [osfans/trime#123]
卡顿问题已解决，把拷过来的"terra_pinyin.userdb"、"terra_pinyin.userdb.old"删了就好了。【】内内容请忽略。

【我所用的带调双拼方案（zaqzrh分享的带调小鹤双拼） [https://github.com/zaqzrh/Tone-double_pinyin] 中的td_pinyin_flypy.schema.yaml，在鼠须管和小狼毫中都正常使用，但在trime打到5、6个字以后，就会出现卡顿（触屏和蓝牙键盘都是）（老版和161223最新版都是）。测试时其他输入方案均无卡顿，真是着急啊，不知是什么原因？
原分享者使用说明贴请见：http://tieba.baidu.com/p/3554938607
我的机器是小米平板2】

排查到现在，卡顿原因找到了，我把"terra_pinyin.userdb"、"terra_pinyin.userdb.old"拷贝过来了，删了就好了。

但另一个问题更让人头疼：

我将12345声调分别设置为aeo;,四个键，加上双拼，就是三键出一字。用带调双拼是为了快速写初稿，因此第一遍都不选字，直接空格上屏。

例如输入"不敢面对"，小鹤双拼加调对应的按键是"bu; gjo mm; dv;"（其中;o;;是声调，为便于阅读请忽略空格），鼠须管和小狼毫首选直接识别出来了。但同文识别的首选是"不敢呣呣对"。又如，要输"阳光是如此美好"，编码是"yhe gla ui; rue cio mwo hco"，同文的结果是“杨嗯啦事儿设此每好”。以上二例mac和win的rime都是正确识别的。

后者错误的原因，我估计同文将字母优先识别为拼音的声母或韵母。但前者那个"不敢呣呣对"的错误，我想不通原因了。

能否麻烦修复下这个bug？

**Comment by zaqzrh** [comment]
@osfans 这个应不是bug吧？@hetefei你看看.dict.yaml词典里有没有呣m2、m4音，干掉它或改为mu2、mu4（新的brise已改）

**Comment by osfans** [comment]
好的，那先關掉了。
