### ISSUE TITLE
增加 telegram 群组

### ISSUE THREAD

**Issue by nopdan** [osfans/trime#1230]
#346 

https://t.me/trime_dev

集成 Github Notification 还需要几位仓库合作者的权限

@Bambooin @WhiredPlanck @goofyz

**Comment by Bambooin** [comment]
Seems collaborators don't have permission to do it.

**Comment by nopdan** [comment]
> Seems collaborators don't have permission to do it.

有的，我试过了

**Comment by Bambooin** [comment]
Please give the guide,so we can try to do it.

**Comment by nopdan** [comment]
> Please give the guide,so we can try to do it.

我已经将 @GithubBot 添加进了群组，只需要私聊 bot，进行身份认证，然后绑定项目

**Comment by Bambooin** [comment]
We lack of maintainer in Telegram, it's nice for you helping to maintain it.

**Comment by nopdan** [comment]
新建了一个房间 matrix https://matrix.to/#/#trime:matrix.org 和 telegram 互通消息
@goofyz 加一下 tg 呗
