### ISSUE TITLE
候选垂直居中问题

### ISSUE THREAD

**Issue by nopdan** [osfans/trime#1239]
![Screenshot_2024-02-09-22-12-42-207_mark via-edit](https://github.com/osfans/trime/assets/47845580/ca02513d-3d7e-4e1b-b972-fe25dcce86a3)
![Screenshot_2024-02-09-22-13-24-583_mark via-edit](https://github.com/osfans/trime/assets/47845580/e9cc6a38-63c3-4182-a55c-e5359bc2df1a)

建议只在所有候选都没有编码提示的时候才居中
相关 #1062

**Comment by WhiredPlanck** [comment]
我记得我好早之前修了，怎么又出来了 ......

**Comment by yanhuacuo** [comment]
这种错位，不知与这个有没有关联性：

https://github.com/osfans/trime/issues/1241
