### ISSUE TITLE
预置基础配置事宜 / Ship app with essential config files

### ISSUE THREAD

**Issue by WhiredPlanck** [osfans/trime#1240]
众所周知，Rime 的日常使用基本离不开官方提供的 [prelude](https://github.com/rime/rime-prelude) 和 [essay](https://github.com/rime/rime-essay) 或类似格式的配置。我打算将它们预置到 app 中，方便大家放完方案就能部署，加强开箱即用体验。

实际来说，有两种想法：

1. 真正地 prelude 和 essay 下载下来，放入项目的 `app/src/main/assets/rime` 中（加入为 git 子模块然后软链接进去更合适？）。
2. 并不真正放入文件，而是在现有提示对话框中加入下载链接，引导用户下载。

欢迎其他意见和建议。

---

As we all known, the daily use of Rime relies on [prelude](https://github.com/rime/rime-prelude) and [essay](https://github.com/rime/rime-essay) provided by official or any other configs in a similar format. So I plan to ship them with the app to make it easy for users to "put down and deploy", enhancing out-of-box experience.

Actually, I have two ideas:

1.  Download prelude and essay indeed, and put them into `app/src/main/assets/rime` (Is it more appropriate to add as git submodules and symlink to there?)
2. Just add download link to existing tip dialog to guide users.

Any other suggestion is welcome.

@Bambooin @goofyz

**Comment by nopdan** [comment]
内置一个能够打字的最小环境就行，essay.txt 不是必要的

**Comment by yanhuacuo** [comment]
配置交流一直存在的客观困难是：字体定义权，尽属【主题】及【主题补丁】所有。
如果它能像 weasel 那样，优选接受【方案补丁】的定义，这样可能会好很多。
形码注解、超大字集，目前都需要配套的【主题】。
供参考。

**Comment by WhiredPlanck** [comment]
> 配置交流一直存在的客观困难是：字体定义权，尽属【主题】及【主题补丁】所有。 如果它能像 weasel 那样，优选接受【方案补丁】的定义，这样可能会好很多。 形码注解、超大字集，目前都需要配套的【主题】。 供参考。

我不是很明白，愿闻其详

**Comment by yanhuacuo** [comment]
> > 配置交流一直存在的客观困难是：字体定义权，尽属【主题】及【主题补丁】所有。 如果它能像 weasel 那样，优选接受【方案补丁】的定义，这样可能会好很多。 形码注解、超大字集，目前都需要配套的【主题】。 供参考。
> 
> 我不是很明白，愿闻其详


现在 weasel 支持优先从「**方案补丁**」（比如：wubi98_ci.custom.yaml）中**读取字体定义**，然后才是前端文件（即 weasel.custom.yaml）

这样做的好处，是**可以让「用户方案」更自主地控制自己的前端显示**。不同的方案，它的用户字集、所需要的字体，可能都大不相同。而这些字体，可能是主题文件，前端文件（trime.yaml，tongwenfeng.trime.yaml)无法支持的。

比如，这份是现在适配最新同文重构版的98五笔配置文件：https://github.com/yanhuacuo/98wubi_for_trime

对于普通的国标GB字集，98五笔方案必须对「同文风」这款主题打一这样个补丁：

https://github.com/yanhuacuo/98wubi_for_trime/blob/main/rime/tongwenfeng.trime.custom.yaml

```
patch:
  "style/candidate_font": 98WB-2.otf #候選字型
  "style/hanb_font": 98WB-2.otf #擴充字型
  "style/comment_font": 98WB-2.otf #opencc注释字型
```

因为98五笔的配置，添加了拆分注解，要保障这样的功能正确表达，上述【主题补丁】就不可或缺：

![303896919-bcbcc3ab-3d91-4178-ba72-b0de1b3d221b](https://github.com/osfans/trime/assets/3107994/77592909-6284-4ed6-84a0-376ab0811f88)

事实上：你可能无法预测用户还有什么样的主题，更难以让缺乏动手能力的用户在手机上打开 yaml 文件，为主题添加【98WB-2.otf】这样高度定制化的字体。

但是，如果 trime 接受从【方案补丁】（wubi98_ci.custom.yaml）中接受字体定义，那就没有这层问题需要考虑了。

现在，[98五笔的 weasel 配置](https://github.com/yanhuacuo/weasel-data) 中，即是这样定义的：https://github.com/yanhuacuo/weasel-data/blob/main/Rime/wubi98_ci.custom.yaml

**Comment by nopdan** [comment]
这不是有吗，https://github.com/osfans/trime/wiki/trime.yaml-詳解#1style

**Comment by yanhuacuo** [comment]
> 这不是有吗，[https://github.com/osfans/trime/wiki/trime.yaml-詳解#1style](https://github.com/osfans/trime/wiki/trime.yaml-%E8%A9%B3%E8%A7%A3#1style)

感谢，这可太棒了

**Comment by wxyzh** [comment]
iOS 的[仓](https://github.com/imfuxiao/Hamster/blob/main/InputSchemaBuild.sh)内置了 [prelude](https://github.com/rime/rime-prelude) 和 [essay](https://github.com/rime/rime-essay) 以及 [雾凇拼音](https://github.com/iDvel/rime-ice)

**Comment by goofyz** [comment]
最基本的放 prelude 就夠，直接放進 `assets` 中，在第一次安裝後複製到 `/rime` 吧。
至於放不放 essay 就取決於會不會放輸入法。我記得以前看過一些討論，說 trime 不想內置輸入法的，不知有否記錯。

**Comment by WhiredPlanck** [comment]
> 最基本的放 prelude 就夠，直接放進 `assets` 中，在第一次安裝後複製到 `/rime` 吧。 至於放不放 essay 就取決於會不會放輸入法。我記得以前看過一些討論，說 trime 不想內置輸入法的，不知有否記錯。

你没记错。我们确实可以不钦定内置任何方案，但是我觉得放点必需文件还是可以的。
