### ISSUE TITLE
【顽疾】opencc注解内容出现了不正确的折行

### ISSUE THREAD

**Issue by yanhuacuo** [osfans/trime#1241]
最新同文重构版，一直有这个问题：

另外，不是所有手机都会发生，即使是同一份配置。
不清楚复现条件，大佬们参议一下吧。
应该与字体无关，在同文的衍生版【中文输入法】上，从来没有这种问题。

![1](https://github.com/osfans/trime/assets/3107994/a653ac10-9e37-4e12-85a5-898a4e384394)
![Screenshot_2024-02-11-11-27-02-942_com miui notes](https://github.com/osfans/trime/assets/3107994/ee80ae37-0b4d-4042-b179-1d1299ee2740)
![Screenshot_2024-02-11-11-27-12-996_com miui notes](https://github.com/osfans/trime/assets/3107994/bcbcc3ab-3d91-4178-ba72-b0de1b3d221b)
![Screenshot_2024-02-11-11-29-05-176_com miui notes](https://github.com/osfans/trime/assets/3107994/531165ae-59df-41d0-9f97-9030a63bf8ea)

**Comment by goofyz** [comment]
從上面的圖看，是否輸入 `ww` 和 `qaj` 一定會出現問題？

我覺得是 window 闊度的問題。試試調整一下闊度或 margin_x 看看。

**Comment by yanhuacuo** [comment]
> 從上面的圖看，是否輸入 `ww` 和 `qaj` 一定會出現問題？
> 
> 我覺得是 window 闊度的問題。試試調整一下闊度或 margin_x 看看。

应该不是，配置如下：

https://github.com/yanhuacuo/98wubi_for_trime/blob/main/rime/pc.trime.yaml

**Comment by goofyz** [comment]
應該還是 window 大小的問題，但與主題設定無關。

正常情況下，`CompositionPopupWindow` 會根據內容，使用自身的 `updateCompositionView()` 來自動調整大小。
我試過推遲 `updateCompositionView()`，在大小還未調整前，能重現你的情況。
我認為你遇到的問題，有機會是，

1. `updateCompositionView()` 比顯示選詞的內容更新執行，結果令大小錯誤
2. 計算大小的函數本身有錯誤，某些情況會計算錯誤

如果只是偶然出現此折行情況，而非等定輸入必定出現，我認為是問題1的機會較大。

**Comment by yanhuacuo** [comment]
> 應該還是 window 大小的問題，但與主題設定無關。
> 
> 正常情況下，`CompositionPopupWindow` 會根據內容，使用自身的 `updateCompositionView()` 來自動調整大小。 我試過推遲 `updateCompositionView()`，在大小還未調整前，能重現你的情況。 我認為你遇到的問題，有機會是，
> 
>     1. `updateCompositionView()` 比顯示選詞的內容更新執行，結果令大小錯誤
> 
>     2. 計算大小的函數本身有錯誤，某些情況會計算錯誤
> 
> 
> 如果只是偶然出現此折行情況，而非等定輸入必定出現，我認為是問題1的機會較大。

是每次必然不正确折行，即使该行其实并非很宽，因为有些特别宽的行，反而显示是正常的。

**Comment by yanhuacuo** [comment]
问题解除了，感谢 @WhiredPlanck 

https://github.com/yanhuacuo/98wubi_for_trime/blob/main/rime/trime.custom.yaml#L41

![2024-05-08_140013](https://github.com/osfans/trime/assets/3107994/bebb8882-651f-40c3-b46a-ede94a67c17d)
