### ISSUE TITLE
每页显示候选词 选项 异常，之前没问题

### ISSUE THREAD

**Issue by tao659** [osfans/trime#1247]
默认状态下 每页显示候选词数量为 3倍候选栏宽度
可以正常显示候选词
切换每页候选词数量 为 不超过候选栏
无法正常显示候选栏

最新的develop 版本 构建信息如下

构建者：Commit CI
Git 仓库：https://github.com/osfans/trime
构建 Git 哈希：fa9e8c531e2ca5aa3e51be37420fd1d71212ff81
构建时间：2024年2月13日 14:13:39

![IMG_20240213_163357](https://github.com/osfans/trime/assets/16471291/9b4df0e4-f08e-4cad-a23c-485e2cec5641)

**To Reproduce**
Steps to reproduce the bug:
4. See bug

**Expected behavior**

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi Mix 4]
 - OS: [e.g. Android 11]
 - Theme: [e.g. Tongwenfeng]
 - Version: [e.g. 3.2.1]
 - Build info: 
   ```
   You could find build info in About Activity and click it to copy.
   e.g. 
   Build: Commit CI
   Date: 2022-06-12 10:09 UTC
   Commit: v3.2.6-58-gd9b4c1f, 2022-06-12 17:58:14 +0800
   Branch: develop
   Repository: https://github.com/osfans/trime
   ```
**Additional context**

**Comment by tao659** [comment]
默认状态
![IMG_20240216_132620](https://github.com/osfans/trime/assets/16471291/6630cac2-1451-4cfe-9331-328f769a277c)
可以显示候选词

![IMG_20240216_132650](https://github.com/osfans/trime/assets/16471291/47b5cb9c-06e6-4d11-9a9f-dff866f4f1b8)


修改不超过

![Screenshot_2024-02-16-13-27-42-772_com osfans trime debug-edit](https://github.com/osfans/trime/assets/16471291/b2bdfc30-5205-4f3b-866f-e3eccf20186f)


不能显示了
![IMG_20240216_132716](https://github.com/osfans/trime/assets/16471291/ae72f563-b1cb-4eb9-bdac-433338d12543)


不知道从哪个版本开始出现的
一直就存在了 

2.11前的版本应该还没有问题

**Comment by Wenti-D** [comment]
这个问题应该是在之前的 3.2.17 nightly 29 到 3.2.17 beta-1 16 之间出现的
