### ISSUE TITLE
调高剪贴板历史记录上限

### ISSUE THREAD

**Issue by Sourage** [osfans/trime#1249]

**Comment by WhiredPlanck** [comment]
剪贴板是同步系统剪贴板，只能有一个

**Comment by Sourage** [comment]
> 剪贴板是同步系统剪贴板，只能有一个

不是，我的意思是增加剪贴板词条数量上限，现在最多只有100，我记得旧版还挺多的，怎么新版反而更少了

**Comment by WhiredPlanck** [comment]
> > 剪贴板是同步系统剪贴板，只能有一个
> 
> 不是，我的意思是增加剪贴板词条数量上限，现在最多只有100，我记得旧版还挺多的，怎么新版反而更少了

首先为了确保你没误解，我先解释一下这个上限。N 条上限（在咱这个讨论里，N == 100）是指当新增的记录为第 N + 1 条时，第 1 条记录就会被挤出去，也就是说整个剪贴板是个先进先出的队列。

其次是，如果你确实有那么多记录想要留存，你可以：
1. 将某条记录置顶
2. 将其加入收藏，收藏夹是无限条数的

以上操作在长按剪贴板记录时都能看到。

最后，如果你依旧还是想增加剪贴板数量上限，那可以纳入日后计划。

**Comment by Sourage** [comment]
> > > 剪贴板是同步系统剪贴板，只能有一个
> > 
> > 不是，我的意思是增加剪贴板词条数量上限，现在最多只有100，我记得旧版还挺多的，怎么新版反而更少了
> 
> 首先为了确保你没误解，我先解释一下这个上限。N 条上限（在咱这个讨论里，N == 100）是指当新增的记录为第 N + 1 条时，第 1 条记录就会被挤出去，也就是说整个剪贴板是个先进先出的队列。
> 
> 其次是，如果你确实有那么多记录想要留存，你可以：
> 1. 将某条记录置顶
> 2. 将其加入收藏，收藏夹是无限条数的
> 
> 以上操作在长按剪贴板记录时都能看到。
> 
> 最后，如果你依旧还是想增加剪贴板数量上限，那可以纳入日后计划。

感谢讲解。主要是因为我保留了之前大厂输入法的使用习惯，当然也可能是我自己有这个习惯，那个剪贴板没有置顶更没有收藏的功能，一些常用的都保存在剪贴板里，复制了没用的就顺手删掉，所以剪贴板在我这里更类似“收藏夹”的功能，而你的讲解好像更当作是一种“草稿箱”的功能。

不过既然有收藏夹，剪贴板数量上限也就无所谓了，如果能多点选择当然是更好的，麻烦的话就没有必要了。抱歉浪费你时间了。
