### ISSUE TITLE
键盘高度无法锁定，无法自适应

### ISSUE THREAD

**Issue by nopdan** [osfans/trime#1250]
### 问题
[3.2.6]keyboard_height: 键盘锁定的高度。当每行按键高度、行之间间距之和与此参数存在差异时，键盘自动缩放为锁定的高度。使用此参数可以快速调整键盘高度而无需复杂。当缺少此参数时，键盘高度不做缩放计算。
[3.2.6]keyboard_height_land: 横屏下键盘锁定的高度，同上

自动适应键盘高度失效，锁定高度失效。可能与 #1191 有关

### 复现

使用同文风主题，由默认键盘切换到符号键盘。

### 预期

建议自适应逻辑：
1. 读取键盘配置，计算键盘总高度、宽度。
2. 计算每个按键尺寸百分比。
3. 绘制时，计算键盘画布大小（上下左右padding，重新启用废弃的左右手布局）。在 style 中指定则直接采用，没有指定则设定一个阈值，若上一个键盘的高度和当前键盘高度相差 < 10%，则采用上一个键盘的高度。画布大小乘以百分比后舍去小数部分为实际的按键尺寸。

可能需要调整的：按键触摸事件

**Comment by goofyz** [comment]
你是指 `keyboard_height` 沒有生效？我試了 `develop` 的沒有問題。
不過用 `themePicker` 似乎不能 refresh keyboard，需要回「主題」裏刷新一次。

**Comment by nopdan** [comment]
> 你是指 `keyboard_height` 沒有生效？我試了 `develop` 的沒有問題。 不過用 `themePicker` 似乎不能 refresh keyboard，需要回「主題」裏刷新一次。

1. `keyboard_height` 可以调整高度，但是不能保证键盘高度一致。
比如同文风键盘，从主键盘切换到 `123` 没问题，但是切换到符号键盘就会导致高度不一致，怀疑是对`垂直间距`的处理不当。

2. `themePicker` 没有问题

**Comment by chwt163** [comment]
我这里也是，主键盘、符号键盘、颜文字键盘，以及最新的 Nightly 的液体键盘，高度都不一致。
