### ISSUE TITLE
候选字号异常

### ISSUE THREAD

**Issue by tao659** [osfans/trime#1252]
配置 没有变过 安装 最新的develop版本
候选字号出现异常
如下图

![Screenshot_2024-02-16-09-05-55-564_io github forkmaintainers iceraven-edit](https://github.com/osfans/trime/assets/16471291/a088b4bf-0320-40e1-9c05-3321756e2fd9)

构建信息如下
构建者：Commit CI
Git 仓库：https://github.com/osfans/trime
构建 Git 哈希：2ba8da39062cd4875c14071305a751682e38bb2c
构建时间：2024年2月16日 02:43:03

**escribe the bug**

**To Reproduce**
Steps to reproduce the bug:
4. See bug

**Expected behavior**

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi Mix 4]
 - OS: [e.g. Android 11]
 - Theme: [e.g. Tongwenfeng]
 - Version: [e.g. 3.2.1]
 - Build info: 
   ```
   You could find build info in About Activity and click it to copy.
   e.g. 
   Build: Commit CI
   Date: 2022-06-12 10:09 UTC
   Commit: v3.2.6-58-gd9b4c1f, 2022-06-12 17:58:14 +0800
   Branch: develop
   Repository: https://github.com/osfans/trime
   ```
**Additional context**

**Comment by WhiredPlanck** [comment]
@tao659 ~~最新的版本可能需要调整一下配置，字号的单位发生了变化（原有的单位由于历史原因设置得不太科学），但理论上视觉体验应该没有明显变化。如果你觉得字体偏小，请将字号调大一点，在原有基础上加 2 ～ 4 应该比较合理。另外同文自带的配置中没有观察到明显异常，你也可以参考其中的字号设置。~~

**UPDATE:** 可能真的有问题，请稍候。

**Comment by tao659** [comment]
#1253 版本 字号正常了
但是候选栏 定位另外一个问题#1247  不知道是什么时候产生的
