### ISSUE TITLE
bundle a rime-data

### ISSUE THREAD

**Issue by Freed-Wu** [osfans/trime#1262]
How about bundle some rime im scheme in this App to increase user experience?
In some Linux distribution, they bundle some rime im schemes to a package named rime-data: 

https://search.nixos.org/packages?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=rime-data

The code to download rime-data is [here](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/data/misc/rime-data/generateFetchSchema.sh#L4-L26)

**Describe the solution you'd like**
Every time deploy user can use builtin rime im schemes. without add it by themselves.

**Describe alternatives you've considered**
Let user download rime-data and copy it to `/sdcard/rime` by themselves.

**Additional context**

**Comment by WhiredPlanck** [comment]
Duplicated with #1240
