### ISSUE TITLE
剪贴板记录不能删除

### ISSUE THREAD

**Issue by XYgnnJ** [osfans/trime#1264]
长按记录
点击全部删除没有确定或取消的选项

**Comment by XYgnnJ** [comment]
![S40222-14442211.jpg](https://github.com/osfans/trime/assets/78903862/75c7430b-c8de-44cb-a713-12f0a36c65bd)

选项应该就在那条白线，不过被遮挡了

**Comment by WhiredPlanck** [comment]
你的 Android 版本是 9 吗？请到 Releases 下载 3.2.17-beta1 或者体验我们的 nightly 每夜版
