### ISSUE TITLE
建議安裝包自帶方案

### ISSUE THREAD

**Issue by DaengGWokFook** [osfans/trime#127]
有好多人放棄同文是因爲同文要將電腦方案複製到手機才可用。

**Comment by osfans** [comment]
正式版会带的。

**Comment by DaengGWokFook** [comment]
何時出正式版?會在google商店嗎?

**Comment by osfans** [comment]
google商店比較麻煩，暫時沒有帳號。

**Comment by osfans** [comment]
https://play.google.com/store/apps/details?id=com.osfans.trime

已上架，已內置brise所有方案，感謝滿滿。
