### ISSUE TITLE
[question] default value of shared directory

### ISSUE THREAD

**Issue by Freed-Wu** [osfans/trime#1270]
I cannot found any document about shared/user directory. It looks like default value of user directory is `/sdcard/rime`. What is the default value of shared directory? Can it use `/sdcard/rime-data` as default value? Can the defaul value be displayed in `profile -> storage -> shared/ user directory`?

**Comment by WhiredPlanck** [comment]
> I cannot found any document about shared/user directory. It looks like default value of user directory is `/sdcard/rime`. What is the default value of shared directory? Can it use `/sdcard/rime-data` as default value? Can the defaul value be displayed in `profile -> storage -> shared/ user directory`?

You are right. The default value of shared/user directory is `/sdcard/rime`. You could custom them in the `Profile` page. For some reasons (I think it may be a bug), the default value doesn't display at first. Once you custom it as a preferred value, it will show in the preference item.

**Comment by WhiredPlanck** [comment]
Fixed by #1359 , close.
