### ISSUE TITLE
LiquidKeyboard 崩溃问题等

### ISSUE THREAD

**Issue by ghbasic** [osfans/trime#1273]
1 键盘设置中每页显示候选词数量项中上方选项无法选中
2 主题中调用 liquid_keyboard出错，或第一次出错，第二次可以进入

**Comment by ghbasic** [comment]
用原装的trime.yaml,第一次一定崩溃，以后偶然正常
[com.osfans.trime-2024-03-03T03_44_58Z[1].txt](https://github.com/osfans/trime/files/14471681/com.osfans.trime-2024-03-03T03_44_58Z.1.txt)

**Comment by ghbasic** [comment]
![Uploading Screenshot_20240301_225601_com.osfans.trime[1].jpg…]()

**Comment by WhiredPlanck** [comment]
> 1 键盘设置中每页显示候选词数量项中上方选项无法选中

此选项已被暂时停用。

> 2 主题中调用 liquid_keyboard出错，或第一次出错，第二次可以进入

已知缺陷，将很快修复。
