### ISSUE TITLE
将剪贴板内容也加进rime文件夹内

### ISSUE THREAD

**Issue by Sourage** [osfans/trime#1274]
希望可以在rime文件夹内加入一个专门储存剪贴板、收藏夹和草稿箱内容的文件夹，这样剪贴板等的内容可以直接在文件里修改，不会因卸载软件而使内容丢失。
亦或像候选词数量一样，剪贴板，收藏夹和草稿箱的历史记录上限也可以在文件里进行修改

**Comment by WhiredPlanck** [comment]
@Sourage 这个需求在我看来有点奇怪，因为目前我们提供了长按菜单可编辑条目的功能。流行的实现里剪贴板等内容都是存入数据库的，增删查改也有 Android 官方库的良好支持和增强。

**Comment by Sourage** [comment]
> @Sourage 这个需求在我看来有点奇怪，因为目前我们提供了长按菜单可编辑条目的功能。流行的实现里剪贴板等内容都是存入数据库的，增删查改也有 Android 官方库的良好支持和增强。

但是删除软件之后记录就不存在了，如果存放在文件夹内就可以保存了吧?

**Comment by shitlime** [comment]
其实是可以手动备份同文App 的 data，但似乎比较麻烦。

感觉同文是应该出一个备份/恢复应用数据的功能 *（应用数据不包括方案，仅包括同文自身的应用设置、剪切板）* 。

**Comment by WhiredPlanck** [comment]
> > @Sourage 这个需求在我看来有点奇怪，因为目前我们提供了长按菜单可编辑条目的功能。流行的实现里剪贴板等内容都是存入数据库的，增删查改也有 Android 官方库的良好支持和增强。
> 
> 但是删除软件之后记录就不存在了，如果存放在文件夹内就可以保存了吧?

可以考虑增加导出按钮，但我不太接受写入到外置文件的方案。

**Comment by amalgame21** [comment]
seems it can initiate some kind of security risk, unless you have a toggle for this feature, and default should be off.
