### ISSUE TITLE
liquid keyboard bug

### ISSUE THREAD

**Issue by ghbasic** [osfans/trime#1280]
1. liquid keyboard使用图片背景时, 显示悬浮窗必崩溃
2. liquid keyboard使用多个返回时,标签排列混乱不能显示更多返回标签
建议:
1.liquid keyboard 固定返回标签在行首
2.设置标准键盘统一keyboard和liquid keyboard
3.键盘候选区候选词数量采用自适应, 于候选栏尾设置显示全部候选按键,免去翻页痛苦

**Comment by chwt163** [comment]
第二点我这里没有问题，多个返回和更多标签可以同时存在并正常使用。

**Comment by goofyz** [comment]
1. 因為懸浮窗會使用 `key_back_color` 做背景色，但沒有處理 `key_back_color` 是圖片時的情況，所以會崩。遲點修正。
2. 我試過也沒問題。你的配置是怎樣的？

**Comment by nopdan** [comment]
新版已不再使用悬浮窗按键
