### ISSUE TITLE
20240306 Nightly版打字崩溃

### ISSUE THREAD

**Issue by cabins** [osfans/trime#1281]
**Describe the bug**
20240306 Nightly版打字崩溃，只要打字就崩溃，什么字也打不了
[com.osfans.trime-2024-03-06T06_17_55Z.txt](https://github.com/osfans/trime/files/14505480/com.osfans.trime-2024-03-06T06_17_55Z.txt)

异常日志见附件。

**Comment by shitlime** [comment]
实测并不会崩溃，请提供更多详细信息，例如方案、键盘布局等配置信息。

**Comment by cabins** [comment]
![Screenshot_20240307_090359](https://github.com/osfans/trime/assets/2500123/9251f15d-eb83-4027-a24d-9b85cb0524c5)
与方案没有关系，看日志，应该是计算悬浮候选窗口的x轴那里出了问题。在之前的版本上，这个悬浮窗口的位置虽然不对，但至少不崩溃。

从最近不到一周的nightly开始崩溃。

我的设备信息：
平板，实体键盘，横屏，Android 14。（其实在Android 13上我就发现这个x轴位置非必现的不对了）

不过也没有更多的人反馈，还是等等看看吧。我先退回到3.2.16去（3.2.17的状态栏隐藏不掉）。

**Comment by WhiredPlanck** [comment]
@cabins Fixed by https://github.com/osfans/trime/commit/83a6fe8dcf0f84c748e404dda26e2a56334b42bc , closing this issue.
