### ISSUE TITLE
部署 OpenCC 词典出错导致应用崩溃

### ISSUE THREAD

**Issue by mrdobejelly** [osfans/trime#1286]
部署的时候出现的崩溃日志

**Comment by mrdobejelly** [comment]
[com.osfans.trime-2024-03-10T18_26_06Z.txt](https://github.com/osfans/trime/files/14551377/com.osfans.trime-2024-03-10T18_26_06Z.txt)

**Comment by WhiredPlanck** [comment]
@mrdobejelly 请检查你的 OpenCC txt 格式的词典里有没有含有两个以上“污染”的。

**Comment by mrdobejelly** [comment]
> @mrdobejelly 请检查你的 OpenCC txt 格式的词典里有没有含有两个以上“污染”的。

解决了，感谢
