### ISSUE TITLE
Wrong tag name in release artifactory

### ISSUE THREAD

**Issue by Bambooin** [osfans/trime#1289]
Wrong tag name in release artifactory, it's should be `v3.2.17` instead of `nightly`.

https://github.com/osfans/trime/releases/tag/v3.2.17
>  com.osfans.trime-nightly-0-g98e201b9-arm64-v8a-release.apk

**Comment by WhiredPlanck** [comment]
> Wrong tag name in release artifactory, it's should be `v3.2.17` instead of `nightly`.
> 
> https://github.com/osfans/trime/releases/tag/v3.2.17
> 
> > com.osfans.trime-nightly-0-g98e201b9-arm64-v8a-release.apk

Needs to filter tags that don't start with `v`.
