### ISSUE TITLE
3.2.16版本引入无法切换为简体的问题

### ISSUE THREAD

**Issue by YuruiHong** [osfans/trime#1295]
**Describe the bug**
此现象在 #954 中已经描述过，具体为简繁切换按钮无法真正切换为简体，输出始终在繁体模式下。我经过回退历史版本发现，此问题出现在3.2.16及之后，3.2.15是最后一个无此问题的版本。同样的配置文件在最新`ibus_rime`下未出现类似问题。

**To Reproduce**
Steps to reproduce the bug:
1. 安装3.2.16及之后的trime，配置并部署
2. 点击简繁切换按钮
3. 按钮的显示状况改变，但输出的字词始终为繁体

**Expected behavior**
按钮能真正进行简繁切换。

**Smartphone (please complete the following information):**
 - Device: Redmi K30i 5G
 - OS: Lineage OS 20 (Android 13)
 - Theme: All
 - Version: 3.2.16 and above

**Additional context**

我的配置：

[20240317.zip](https://github.com/osfans/trime/files/14625277/20240317.zip)

**Comment by WhiredPlanck** [comment]
@YuruiHong 你的配置文件挺多 …… 你主用哪个方案？是哪个方案出问题了？

**Comment by YuruiHong** [comment]
> @YuruiHong 你的配置文件挺多 …… 你主用哪个方案？是哪个方案出问题了？

事实上只有三个独立的方案，`double_pinyin_plus`底层依赖明月拼音和`zrm2000`，挂载了`english``stroke`等。其实`double_pinyin_plus`是唯一中文方案。如果需要最小的复现，可以考虑直接使用明月拼音，如对我的方案在`default.custom.yaml`中添加一行

```yml
patch:
  schema_list:
    ...
    - {schema: luna_pinyin}
```

**Comment by WhiredPlanck** [comment]
@YuruiHong 经试验无法重现。请检查 opencc 文件夹内的配置是否齐全，建议备份好现有配置后通过应用内的“配置管理”——“恢复默认设置”——勾选“opencc”，然后点击“确定”恢复出厂 opencc 设置后再试一试。

[Screen_recording_20240317_141646.webm](https://github.com/osfans/trime/assets/47623588/4ba318f8-e74f-4391-b68e-961c94a8b097)

**Comment by WhiredPlanck** [comment]
@YuruiHong 可否提供一下 build 目录下的方案文件呢？

**Comment by YuruiHong** [comment]
我现在在最新的nightly版本中也无法复现这个问题了。😂

**Comment by YuruiHong** [comment]
我没有尝试过手动修改opencc相关的配置，只是在重装安卓系统的第一天配置trime时遇到此问题，后面采取相同的配置莫名就好了，或许可以考虑下和时间/重启相关的原因？
