### ISSUE TITLE
3.2.8 正常运行的皮肤无法在 3.2.16+ 上使用

### ISSUE THREAD

**Issue by isPoto** [osfans/trime#1298]
我皮肤在 3.2.8 中正常使用，然而在 3.2.17 中完全无法使用，任意按键直接崩溃

在 3.2.16 中可以打字但无法正常切换英文键盘

附件为皮肤在 3.2.17 崩溃报告
[com.osfans.trime-2024-03-17T17_56_57Z.txt](https://github.com/osfans/trime/files/14628357/com.osfans.trime-2024-03-17T17_56_57Z.txt)

**Comment by WhiredPlanck** [comment]
@isPoto 你的版本跨度太大，同文的皮肤规范在期间已发生多次有破坏性的调整。还烦请根据 Wiki 或向社区咨询自行调整。

**Comment by isPoto** [comment]
我将重新基于 3.2.17 初始皮肤重新开发

不必保持向下兼容性，以免历史包袱积重难返

**Comment by WhiredPlanck** [comment]
> 我将重新基于 3.2.17 初始皮肤重新开发
> 
> 不必保持向下兼容性，以免历史包袱积重难返

根据你提供的日志，问题应该也不是很大：你现用的主题配置里，`style/horizontal` 参数应该是一个布尔值（即应该是 `true` 或者 `false`），但现在是个整数值 0，所以解析异常了。

**Comment by isPoto** [comment]
> > 我将重新基于 3.2.17 初始皮肤重新开发
> > 不必保持向下兼容性，以免历史包袱积重难返
> 
> 根据你提供的日志，问题应该也不是很大：你现用的主题配置里，`style/horizontal` 参数应该是一个布尔值（即应该是 `true` 或者 `false`），但现在是个整数值 0，所以解析异常了。

感谢，现在解决崩溃问题。

还有最后一点。无法正常切换英文键盘

由于同文 mode switch 后不会刷新键盘，而我需要中英键盘部分键位独立功能
在 3.2.8，我用了两套独立键盘硬引用，即切换键盘。英文键盘 __include 自中文键盘并 __patch 更改

现在在 3.2.17，切换至英文键盘后，输出却依然是中文，键帽显示没变化（设计是「中文键盘下同一按键是笔画，英文键盘变成字母」，现在英文键盘下按键依然是笔画）。但颜色和符号提示正常变成英文键盘的布局（中英键盘是两套色彩，按键也有所变化）。我核对过，preset key 语法 3.2.8 和 3.2.17 一致，但其他细节不确定
