### ISSUE TITLE
3.2.17 无法硬切中英键盘

### ISSUE THREAD

**Issue by isPoto** [osfans/trime#1302]
我想要的效果：中英键盘独立的键帽显示和功能键。
但是同文 mode switch 切换中英不会刷新键盘，这意味着只是单纯地输出中英，键盘布局不变

我在 3.2.8 的做法是将中英键盘硬切，即切换键盘来实现中英独立键盘

现在 3.2.17 这种做法失效了，英文键盘无法正常打英文，切换至英文键盘打的是依旧是中文；字母键帽无法正常切换，只有符号提示和功能键正常切换

请问如果想在 3.2.17 上实现中英键盘两套布局，该如何实现？

**Comment by nopdan** [comment]
中文键盘设置指定英文键盘 `ascii_keyboard: ...`
