### ISSUE TITLE
Nightly 版本无法切换繁简了

### ISSUE THREAD

**Issue by gsysbrj** [osfans/trime#1305]
Nightly 版本无法切换繁简了

**Comment by WhiredPlanck** [comment]
@gsysbrj 最近好多人报这个问题。但是我重现不出来，有试过应用内重置 opencc 的配置文件吗？

**Comment by gsysbrj** [comment]
使用的是rime-rc這個項目的trime配置文件的最新版本，0.16.0
你試試使用這個配置文件能不能重現。
而且，我已經刪除nightly版本，重新安裝27版本，清除了數據緩存。但是問題依舊。
因此，我懷疑是配置文件觸發了這個bug，或者是某種情況下纔會觸發的與配置文件有關的bug。
目前僅能提供這些信息。

**Comment by gsysbrj** [comment]
> @gsysbrj 最近好多人报这个问题。但是我重现不出来，有试过应用内重置 opencc 的配置文件吗？

在應用內沒有找到重置opencc的操作按鈕。
您是指刪掉opencc目錄，再搞一份新的嗎？

**Comment by WhiredPlanck** [comment]
> > @gsysbrj 最近好多人报这个问题。但是我重现不出来，有试过应用内重置 opencc 的配置文件吗？
> 
> 在應用內沒有找到重置opencc的操作按鈕。 您是指刪掉opencc目錄，再搞一份新的嗎？

重置为默认配置方法：应用内的“配置管理”——“恢复默认设置”，在弹出的对话框里勾选“opencc”，然后确定
