### ISSUE TITLE
默认开启「点击候选词」

### ISSUE THREAD

**Issue by isPoto** [osfans/trime#1308]
点击候选词值得默认开启，因为它与常规操作不冲突，且能带来用户初次接触直觉上的便利

**Comment by goofyz** [comment]
我不明白，這個....是如何使用的？

**Comment by isPoto** [comment]
> 我不明白，這個....是如何使用的？

开启后，点击候选栏的字就能直接上屏

keyboard settings - click candidate(commit directly)

**Comment by kevinfis** [comment]
這個好用,
建議預設開啟+1, 也建議同時把候選欄預設外框加大一些, 更好點選.

補充說明, 這個開關位在"同文輸入app"中的選項 keyboard settings,
不存在於設定檔trime.yaml內.

附註:
如果要修改這個選項, 此處同時再加個建議,
在 'deploy 部署' 按鈕附近能不能增加個文字測試輸入區?
deploy按下去後有個地方測試輸入法,就不用切換到其他app進行輸入測試了.
