### ISSUE TITLE
在trime.custom.yaml中修改keys数量导致的输入法崩溃问题

### ISSUE THREAD

**Issue by eric1ee** [osfans/trime#1309]
版本：3.2.17以后都有这个问题（我用的3.2.13没问题，直接升级到3.2.18出现了这个问题）
具体描述：由于本人习惯问题，需要将第30、35键屏蔽，将31键宽度调整为15，32键调整为13，33键调整为40，34键调整为17，36键调整为15，调整后最下面一排键总宽度正是100。看图
![PixPin_2024-03-26_16-40-49](https://github.com/osfans/trime/assets/23067121/3a1f7166-ca02-46d6-bff7-b88e870ec261)
但是在调整过程中发现，写到如下代码时 
 "preset_keyboards/qwerty/keys/@30": {}
  "preset_keyboards/qwerty/keys/@31": {click: Keyboard_number,long_click: Keyboard_symbols,width:15}  # 默认数字键 
  "preset_keyboards/qwerty/keys/@32": {label: ' ，', click: ',', width: 13}
  "preset_keyboards/qwerty/keys/@33": {click: space, long_click: IME_switch, width: 40, ascii: spacex}  # 更改空格键宽度
  "preset_keyboards/qwerty/keys/@34": {label: ' 。', click: '.', has_menu: secondary, width: 17}
  #"preset_keyboards/qwerty/keys/@35": {} 
  #"preset_keyboards/qwerty/keys/@36": {click: Return, composing: Return1, width: 15}
此时部署键盘显示这样
![2](https://github.com/osfans/trime/assets/23067121/bb68c89a-d98d-4ec6-9726-d9563978d6d5)
可以发现被屏蔽的30号键仍然占据位置，后面的键位没有向左自动填充。
而继续将 # "preset_keyboards/qwerty/keys/@35": {} 这段代码释放（前面的注释去掉）之后，输入法崩溃，显示这样
![3](https://github.com/osfans/trime/assets/23067121/7cd5c66b-c4cb-4c80-8a60-71d976b8befc)
这些代码是我从3.2.13版本照搬过来的，那个版本用的没有问题

**Comment by goofyz** [comment]
應該是我之前加橫向鍵盤時造成的 bug 。找到問題所在。

這樣應該是你想要的效果？
![image](https://github.com/osfans/trime/assets/2428334/8c11fd9d-54f2-414d-b7ad-5e37d61eb148)

**Comment by eric1ee** [comment]
是的，目前我用的3.2.16也是正常的![PixPin_2024-03-27_11-21-45](https://github.com/osfans/trime/assets/23067121/db020f0f-9398-40e2-a57e-9e7f25aa1caf)
应该确定就是3.2.17之后出现的
