### ISSUE TITLE
用户词库 XXXX_user.dict.yaml 的词不能合并到相应方案中

### ISSUE THREAD

**Issue by SkatingCN** [osfans/trime#1315]
把方案用户词库 XXXX_user.dict.yaml 文件复制到用户文件夹（/storage/emulated/0/rime）中，点设置界面的“部署”。随后打开同文输入法，发现用户词库的词并没有合并到相应方案中。
经检查，该用户词库在Windows平台的小狼毫中部署后，用户词库的词是可以合并到相应方案中的。

**Comment by WhiredPlanck** [comment]
@SkatingCN 带不带 `_user` 对于 rime 来说没有区别，都是普通的词典。你小狼毫和同文的设置肯定不一样。
