### ISSUE TITLE
候选区的翻页键对调位置

### ISSUE THREAD

**Issue by docCesar** [osfans/trime#1318]
目前在用安卓上的trime， 候选区向下翻页的按钮默认在最右，左手输入时手指行程太长了而且很容易误触。 下翻的频率比上翻的高得多，能不能把翻页键的位置对调一下，把下翻键放到主手端？

**Comment by WhiredPlanck** [comment]
未来会将候选栏重构为像搜狗、百度等商业输入法的样式，敬请期待

**Comment by tsaiajie** [comment]
> 未来会将候选栏重构为像搜狗、百度等商业输入法的样式，敬请期待

期待中，这时候的话那个九宫格也可以使用了吧？能问下预计什么时候开始做吗？

**Comment by linzianabc** [comment]
> > 未来会将候选栏重构为像搜狗、百度等商业输入法的样式，敬请期待
> 
> 期待中，这时候的话那个九宫格也可以使用了吧？能问下预计什么时候开始做吗？

九宫格一直可以的。
