### ISSUE TITLE
切换输入方案时键盘不显示

### ISSUE THREAD

**Issue by Wenti-D** [osfans/trime#1319]
**Describe the bug**
当切换输入方案时键盘消失（似乎也像高度为 0）

**To Reproduce**
随便切换一下输入方案即可。

**Expected behavior**
应当能够显示对应方案的键盘。

**Log**
[com.osfans.trime.debug-2024-03-30T06_36_21Z.txt](https://github.com/osfans/trime/files/14810897/com.osfans.trime.debug-2024-03-30T06_36_21Z.txt)

**Screenshots**
症状如同 #1316，但不止是液态键盘，什么键盘都不显示。

**Smartphone (please complete the following information):**
 - Device: HUAWEI P40 Pro
 - OS: Harmony OS 4（Android 12 兼容）
 - Theme: （不重要，哪个都一样）
 - Version: 3.2.18 nightly-5 debug
 - Build info: 
   ```
   构建者：Commit CI
   Git 仓库： https://github.com/osfans/trime
   构建 Git 哈希：e254bd30b3d6073ff2c33a8edeaceeb561156647
   构建时间：2024 年 3 月 28 日 14:02:42
   ```
**Additional context**
无。

**Comment by WhiredPlanck** [comment]
已知问题。还在排查中。

**Comment by Chengxcy** [comment]
看描述应该是这个问题吧
版本：nightly-0-g5dc3eb8e-release
貌似最近发布的3.2.18也是这样
每次切换方案时，键盘消失了，只显示状态栏
![](https://picture-for-typora-1307694447.cos.ap-nanjing.myqcloud.com/img_for_typora/Screenshot_20240505_014052.jpg)
