### ISSUE TITLE
Lockscreen password is stored in `draft` in `液态键盘` and it can even be used in the lockscreen to unlock the phone

### ISSUE THREAD

**Issue by amalgame21** [osfans/trime#1322]
**Describe the bug**

`draft` in `液态键盘` stores the history of inputs, including lockscreen password.

1. If you use `password` as your lockscreen method and use `trime` to unlock your phone, it stores your password in `draft` in `液态键盘`.
I think it is a security risk, password should never be recorded as input history in lockscreen.

2. After your phone is locked, random people who have physical access to your phone can just find your previously input password from `draft` in `液态键盘`, click on it, and hit enter, and now our private data in your phone can be accessed by a random person.

3. Apart from `draft` in `液态键盘`, data in `collection` and `clipboard` can also be called in the lockscreen. 

location of the code about `draft`, `clipboard` and `collection`:
https://github.com/osfans/trime/blob/3dd930c0cb481a8ce292b7599a4ca831368a91e4/app/src/main/assets/rime/trime.yaml#L699

I tried to mitigate the issue with deleting `draft`, `clipboard` and  `collection` in the `keyboards` in `液态键盘` and deploy, just like what I proposed in the [previously rejected PR](https://github.com/osfans/trime/pull/976). However it didn't stop the actual code from working in the background.
After I put `draft`, `clipboard` and `collection` back in the config and deploy, ALL the information e.g. the clipboard and typing history while those keyboard was disabled, shown up again. That means Trime ALWAYS records your inputs history and clipboard and there is no way to disable it.

**To Reproduce**
Steps to reproduce the bug:
1. Unlock phone password with with trime input.
2. Password is stored in `draft` in `液态键盘`
3. Random people can call your previously input password in `draft` in `液态键盘` to unlock the phone
4. He can also see the data in `clipboard` and `collection` in `液态键盘`

**Expected behavior**
1. Password input in lockscreen should never be stored in `draft` in `液态键盘` or even in any form of record.
2. data in `clipboard`, `draft` and `collection` in `液态键盘` should never be revealed in lockscreen for security reason.
3. Allow user to disable  the clipboard and history recording completely in Trime.

Trime Version: 3.2.16

**Comment by amalgame21** [comment]
I tried to mitigate the issue with deleting `draft`, `clipboard` and  `collection` in the `keyboards` in `液态键盘` and deploy.
However it didn't stop the actual code from working in the background.
After I put `draft`, `clipboard` and `collection` back in the config and deploy, ALL the information e.g. the clipboard and typing history while those keyboard was disabled, shown up again. That means Trime ALWAYS records your inputs history and clipboard and there is no way to disable it.

**Comment by shitlime** [comment]
1. Deleting `tab` does not stop background recording. You need to disable it in the settings.

2. The password entered in the lock screen will not be recorded in `draft` unless the password input box you are using does not conform to the Android design specification. This is not a Trime issue.

**Comment by amalgame21** [comment]
Thanks for pointing out that it can be disabled in settings!
