### ISSUE TITLE
小米手機不顯示可選字列表，只出現一常用字

### ISSUE THREAD

**Issue by uliloewi** [osfans/trime#1324]
![8b992440-fe40-4b89-bdaa-52cc0e4ce73c](https://github.com/osfans/trime/assets/29732913/43581385-8dfd-44f8-a2a4-f4ecdc1fca86)
按下d，只顯示“的”

我的手機型號是：
![33b0e950-03d1-481a-bc96-671361a0dc76](https://github.com/osfans/trime/assets/29732913/9d650b53-af65-4324-bfab-babda236e979)

**Comment by WhiredPlanck** [comment]
@uliloewi 你的同文的版本是？

**Comment by uliloewi** [comment]
> @uliloewi 你的同文的版本是？

3.1.3

**Comment by WhiredPlanck** [comment]
> > @uliloewi 你的同文的版本是？
> 
> 3.1.3

请升级，此版本不适应 Android 11 及以上版本
