### ISSUE TITLE
v3.2.17后，键盘底部切换/隐藏输入法区域会与键盘重叠

### ISSUE THREAD

**Issue by jim-kirisame** [osfans/trime#1332]
- 版本：v3.2.17, 9096817 均重现
- 版本：v3.2.16 未重现
- 安卓版本：14

老版本：
![老版本](https://github.com/osfans/trime/assets/6049028/2b4a2a65-eb1d-48c9-bdb6-3dbc96f5687d)

新版本：
![新版本](https://github.com/osfans/trime/assets/6049028/7d4c6759-796c-4218-abd4-14efa1ccdc09)

**Comment by WhiredPlanck** [comment]
麻烦说下 Android 版本和手机型号，我这里没这个问题。

**Comment by jim-kirisame** [comment]
系统：LineageOS 21 (Android 14) 20240215，手机：Redmi K40S

**Comment by goofyz** [comment]
這個不是系統的設定嗎？
你使用其他輸入法的話，下方的區域會出現嗎？

**Comment by jim-kirisame** [comment]
> 這個不是系統的設定嗎？ 你使用其他輸入法的話，下方的區域會出現嗎？

是的，会出现。而且上一个版本也会出现，所以猜想是trime相关的问题。

**Comment by Norcean** [comment]
同样是Lineageos 21，在安装3.2.17后存在相同的问题。使用Gboard时是正常的。
trime:
![Screenshot_20240417-182709_Via](https://github.com/osfans/trime/assets/69784550/27c5bb41-0ad3-4f1a-b8a5-749ee3ffa8f9)
Gboard:
![Screenshot_20240417-182720_Via](https://github.com/osfans/trime/assets/69784550/5d9a9fce-eb85-4cb6-98d6-98dad622bb87)
日志：
[com.osfans.trime-2024-04-17T10_21_33Z.txt](https://github.com/osfans/trime/files/15009536/com.osfans.trime-2024-04-17T10_21_33Z.txt)

**Comment by goofyz** [comment]
是不是 lineageOS 才有的問題？

**Comment by Norcean** [comment]
> 是不是 lineageOS 才有的問題？

应该是的，只有lineage才有这样的“选择输入法栏”，使用iconify隐藏后能看起来正常的显示。
没有“选择输入法栏”的澎湃 os是正常的。

**Comment by Bambooin** [comment]
Linesage OS 20 is fine.

**Comment by WhiredPlanck** [comment]
部分 ROM 会使得输入法获取到的底部导航栏区域的高度为 0，导致键盘最终绘制在了其后方。

**Comment by ctaoist** [comment]
> > 是不是 lineageOS 才有的問題？
> 
> 应该是的，只有lineage才有这样的“选择输入法栏”，使用iconify隐藏后能看起来正常的显示。 没有“选择输入法栏”的澎湃 os是正常的。

我的小米pad7 pro怎么样也有这个问题，怎么修复啊

**Comment by starlifezzz** [comment]
lineageos22.1，手机型号mix2s,同样问题，会重叠，真的很无奈
