### ISSUE TITLE
请问 Nightly 的液体键盘，右侧固定的那几个文字可以自定义吗？我想用符号代替

### ISSUE THREAD

**Issue by chwt163** [osfans/trime#1333]
像这样：
![Screenshot_20240417_083009_net slions fulguris full fdroid_edit_803342001613347](https://github.com/osfans/trime/assets/70951194/a48c6d46-09d5-4c38-99d6-43da5edfba23)

**Comment by goofyz** [comment]
它是定義在 code 裏 (https://github.com/osfans/trime/blob/b51b48ade37ce67bfecf1440ffe2cc315a32a431/app/src/main/java/com/osfans/trime/ime/symbol/SimpleKeyDao.kt#L24-L29)
暫時不可自定呢

**Comment by chwt163** [comment]
好的，希望以后能实现自定义
