### ISSUE TITLE
Wiki-简易索引中指向的“trime详解” URL 有误

### ISSUE THREAD

**Issue by wordpure** [osfans/trime#1334]
[trime详解](https://github.com/osfans/trime/wiki/trime.yaml-%E8%A9%B3%E8%A7%A3) 对应的 URL 为 `https://github.com/osfans/trime/wiki/trime.yaml-%E8%A9%B3%E8%A7%A3`，但 [简易索引](https://github.com/osfans/trime/wiki/UserGuide) 里引用的 `trime详解`，对应的链接都是 `https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3`，`trime.yaml` 后面少了个 `-`。

![image](https://github.com/osfans/trime/assets/68013962/066b63d9-1b01-449c-a68c-a5e62e83b0ae)

**Comment by goofyz** [comment]
謝告之，已修正。

**Comment by wordpure** [comment]
好像漏了一个😂

![图片](https://github.com/osfans/trime/assets/68013962/3aa4cf88-f623-43c7-9a2f-613fc8fb026c)

**Comment by goofyz** [comment]
已修正 👍
