### ISSUE TITLE
最新夜版的 keyboard_padding_bottom 不生效

### ISSUE THREAD

**Issue by chwt163** [osfans/trime#1336]
keyboard_padding_bottom: 竖屏模式下，屏幕下边缘与键盘的距离（避免误触发全面屏）

com.osfans.trime-nightly-1-gdf6d73e0-arm64-v8a-release.apk

**Comment by goofyz** [comment]
我的有正常起作用，你試試大一點的數值看看。

e.g. `keyboard_padding_bottom: 20`

**Comment by chwt163** [comment]
刚试了下，正数有效，负数无效，以前负数是有效的，我需要的也是负数。

**Comment by chwt163** [comment]
> 我的有正常起作用，你試試大一點的數值看看。
> 
> e.g. `keyboard_padding_bottom: 20`

刚试了下，正数有效，负数无效，以前负数是有效的，我需要的也是负数。

**Comment by WhiredPlanck** [comment]
> > 我的有正常起作用，你試試大一點的數值看看。
> > e.g. `keyboard_padding_bottom: 20`
> 
> 刚试了下，正数有效，负数无效，以前负数是有效的，我需要的也是负数。

为啥需要负数？不设的时候是键盘被垫高了吗？

**Comment by chwt163** [comment]
> > > 我的有正常起作用，你試試大一點的數值看看。
> > > e.g. `keyboard_padding_bottom: 20`
> > 
> > 
> > 刚试了下，正数有效，负数无效，以前负数是有效的，我需要的也是负数。
> 
> 为啥需要负数？不设的时候是键盘被垫高了吗？

倒是没有垫高，但我的平板和备用机荣耀V10，不是全面屏，有实体键，不需要加大底部空间来避免误触，减小缝隙反而显得更为紧凑。

**Comment by WhiredPlanck** [comment]
> > > > 我的有正常起作用，你試試大一點的數值看看。
> > > > e.g. `keyboard_padding_bottom: 20`
> > > 
> > > 
> > > 刚试了下，正数有效，负数无效，以前负数是有效的，我需要的也是负数。
> > 
> > 
> > 为啥需要负数？不设的时候是键盘被垫高了吗？
> 
> 倒是没有垫高，但我的平板和备用机荣耀V10，不是全面屏，有实体键，不需要加大底部空间来避免误触，减小缝隙反而显得更为紧凑。

可否截图，默认应该是没有这个缝隙的 ……

**Comment by chwt163** [comment]
![Screenshot_20240425_085421_info plateaukao einkbro](https://github.com/osfans/trime/assets/70951194/5f027bc9-d122-4bc3-bb65-998f7123cfc7)

**Comment by WhiredPlanck** [comment]
@chwt163 个人感觉这个间距很正常啊，你还要往下吗 …… 新版的 keyboard_padding_bottom，是通过在键盘视图下面垫了一个空白视图，高度为 0 时不显现，为正数时就会把键盘垫高了。我想或许你可以考虑调整键盘的设置让它把按键往下画一点。

**Comment by chwt163** [comment]
> @chwt163 个人感觉这个间距很正常啊，你还要往下吗 …… 新版的 keyboard_padding_bottom，是通过在键盘视图下面垫了一个空白视图，高度为 0 时不显现，为正数时就会把键盘垫高了。我想或许你可以考虑调整键盘的设置让它把按键往下画一点。

请问哪个参数可以调整键盘位置？

**Comment by chwt163** [comment]
现在的底部缝隙，其实应该是有被垫高了的。
中间的那几条缝隙，是上下两排按键的缝隙相连，而底部只有一排按键，所以底部缝隙应该是中间缝隙的一半高度才对。
但从截图来看，中间和底部的缝隙，却是一样的高度，这应该就是底部被垫高了。

**Comment by RFDAJE** [comment]
这个问题貌似没有修复仍然存在 https://github.com/osfans/trime/discussions/1855
