### ISSUE TITLE
夜版液体键盘的 tabs 列表错位

### ISSUE THREAD

**Issue by chwt163** [osfans/trime#1337]
因为不喜欢横向滚动，所以我是把 tabs 放在液体键盘列表里的，这种方式更直观快速。
但列表里如果有 tabs ，从 tabs 里点击其他列表，就会出现对不上的错位情况。

如图，我把tabs命名“更多”，从这里点击“数学”，打开的却是“西符”

![Screenshot_20240420_113550_net slions fulguris full fdroid_edit_936238370088380](https://github.com/osfans/trime/assets/70951194/95e2e49d-1a25-400b-9269-600e2cc1c4be)

**Comment by chwt163** [comment]
建议把 tabs 也固定置于现在夜版的返回键上面，多放几个功能，右侧那几个按键字体也可以小一点，看起来不那么违和。

**Comment by WhiredPlanck** [comment]
这个错位挺迷的，似乎和主题有一定关系。待调查。
