### ISSUE TITLE
减少部署频率？

### ISSUE THREAD

**Issue by fishBone000** [osfans/trime#1338]
经常要打字的时候，点击输入框，同文弹出来，就开始部署了……虽然就花几秒（我这边是6秒左右），但还是有点麻烦。  
我在Linux上也用Rime。基本上登录的时候部署一下就可以了，后面都无需部署，直接开始打字。

或许和安卓限制进程后台运行有关？可以Workaround吗？

**Comment by WhiredPlanck** [comment]
@fishBone000 目前正在努力改善，敬请留意最近的每夜版。

**Comment by WhiredPlanck** [comment]
@fishBone000 请试试最近的每夜版，看看还会出现频繁部署的情况吗？

**Comment by fishBone000** [comment]
安装了五月一日发布的release，看起来不会频繁部署了。再多试几天，如果还是有问题再reopen。

**Comment by fishBone000** [comment]
Very nice，爽多了
