### ISSUE TITLE
夜版有时会出现点击完输入区之后失去焦点的情况

### ISSUE THREAD

**Issue by chwt163** [osfans/trime#1341]
程序刚启动完毕的时候，立刻激活输入法，复现的几率比较大。

**Comment by WhiredPlanck** [comment]
@chwt163 未能复现 ……

**Comment by goofyz** [comment]
我也經常遇到。
若冷啟動時更常現。

**Comment by WhiredPlanck** [comment]
@chwt163 @goofyz 模拟器内未能复现。请问两位的设备型号、Android/HarmonyOS 版本和测试的应用各是？

**Comment by chwt163** [comment]
https://github.com/osfans/trime/issues/1338
猜测可能跟这个有关联，因为有的时候会有“正在部署”的字样一闪而过，有的时候快到看不清字样，而有的时候，看起来是正常激活了输入法，输入文字回车之后才发现输入框没有光标。

荣耀V10
HarmonyOS：3.0.0
有几个应用出现过，包括系统设置的搜索框

**Comment by WhiredPlanck** [comment]
@chwt163 4 月 25 日的夜版也会吗？

**Comment by WhiredPlanck** [comment]
> #1338 猜测可能跟这个有关联，因为有的时候会有“正在部署”的字样一闪而过，有的时候快到看不清字样，而有的时候，看起来是正常激活了输入法，输入文字回车之后才发现输入框没有光标。
> 
> 荣耀V10 HarmonyOS：3.0.0 有几个应用出现过，包括系统设置的搜索框

我手头有荣耀 V20 实机，也是 HarmonyOS 3.0，未能复现。已经后台卡片里划掉然后重新点击搜索框调起键盘，过程中没有失焦的情况 ……

**Comment by chwt163** [comment]
> @chwt163 4 月 25 日的夜版也会吗？

25号的正在部署似乎比较频繁，并且会导致卡顿，因此我退回24号了，25号的使用时间很短。
24号和26号的，都有丢失焦点的情况。
你试试先锁屏一段时间，然后打开程序立刻激活trime，看能不能复现，似乎由于trime常驻后台不稳定导致？

**Comment by WhiredPlanck** [comment]
> > @chwt163 4 月 25 日的夜版也会吗？
> 
> 25号的正在部署似乎比较频繁，并且会导致卡顿，因此我退回24号了，25号的使用时间很短。 24号和26号的，都有丢失焦点的情况。 你试试先锁屏一段时间，然后打开程序立刻激活trime，看能不能复现，似乎由于trime常驻后台不稳定导致？

锁屏一段时间再启动确实会短暂出现“正在部署”等情况，这是受系统输入法服务生命周期所影响的。但是我也没有经历过失焦的情况，确实很迷。

**Comment by chwt163** [comment]
> > > @chwt163 4 月 25 日的夜版也会吗？
> > 
> > 
> > 25号的正在部署似乎比较频繁，并且会导致卡顿，因此我退回24号了，25号的使用时间很短。 24号和26号的，都有丢失焦点的情况。 你试试先锁屏一段时间，然后打开程序立刻激活trime，看能不能复现，似乎由于trime常驻后台不稳定导致？
> 
> 锁屏一段时间再启动确实会短暂出现“正在部署”等情况，这是受系统输入法服务生命周期所影响的。但是我也没有经历过失焦的情况，确实很迷。

确实是概率事件，难以找出必定复现的时机。
我现在用的是26号版，刚才就出现了一次，系统设置的搜索框，点击激活了，显示正在部署，大概一两秒部署完毕，这个时候我确认搜索框是没有光标的，但诡异的是搜索框可以输入文字，但是不能用trime的退格键来删除。。。

就刚才，我编辑这个帖子的时候又出现了，正在部署，然后失去焦点没有光标。。。

所以我猜测跟这个是有关联的：https://github.com/osfans/trime/issues/1338
之前的正式版是没有这个问题的。

**Comment by Bambooin** [comment]
Seems I saw this issue with #1156 when unlock the phone due to #1152.

**Comment by chwt163** [comment]
8月25号的 nightly，使用两天，没有出现过失去焦点了，之前的多个版本，都是每天都能复现的。
