### ISSUE TITLE
液体键盘处于 clipboard、collection 或 draft 标签页时，无法点击 tabs 标签

### ISSUE THREAD

**Issue by chwt163** [osfans/trime#1349]
28号夜版。
https://github.com/osfans/trime/issues/1337 已解决，但有一个小问题，如图：
如果当前位置，是位于“更多”左侧的标签，比如“收藏”，这个时候点击“更多”，没有反应。
左一和左二的“中符”“西符”是正常的，从左三开始，就点击不了。
![private-user-images_githubusercontent_com_2024-04-28_09-04-30](https://github.com/osfans/trime/assets/70951194/87507625-7ace-425a-aa81-0923793f4ba5)

**Comment by WhiredPlanck** [comment]
@chwt163 已复现，具体而言，其实是当前处于“剪贴”、“收藏”或”草稿“标签页时，无法切换至”更多“。
