### ISSUE TITLE
使用姿势不对引发的小小问题

### ISSUE THREAD

**Issue by xiaoqun2016** [osfans/trime#135]
在做一个特殊方案时，遇到了几个问题。详见录屏文件：  https://pan.baidu.com/s/1jIAzjhW

**Comment by ipcjs** [comment]
用的哪个录屏软件？感觉录屏效果不错呀😉（关注错了重点

**Comment by xiaoqun2016** [comment]
方案太奇葩，没人会这么折腾，前面两个问题可以忽略。  

嵌入模式问题多，觉得有必要抓一下。  
后来发现只有`preview`有问题，`composition`和`input`都没问题。不知道这个线索有没有用？

**Comment by osfans** [comment]
沒有問題了？還是不容易遇到了？

**Comment by xiaoqun2016** [comment]
很生僻的小问题，可解可不解。以后遇到再说吧
