### ISSUE TITLE
include could not find requested file:BoostRoot

### ISSUE THREAD

**Issue by 625341062** [osfans/trime#1351]
Mac Android Studio run 报错：
CMake Error at boost/CMakeLists.txt:20 (include):
  include could not find requested file:

    BoostRoot

**Comment by WhiredPlanck** [comment]
boost 源码包没有下载好。请检查 `app` 目录下是否存在 `boost-1.84.0.tar.xz` 文件，验证其 SHA256 校验值为 `2e64e5d79a738d0fa6fb546c6e5c2bd28f88d268a2a080546f74e5ff98f29d0e`（如果对不上可点击 https://github.com/boostorg/boost/releases/download/boost-1.84.0/boost-1.84.0.tar.xz 手动重新下载），然后可手动解压至 `app/src/main/jni` 目录中，重命名为 boost（如已存在可覆盖或者删除后再解压）。

**Comment by WhiredPlanck** [comment]
@625341062 请问问题解决了吗？
