### ISSUE TITLE
Trime经常在点击输入框后迟迟无法弹出

### ISSUE THREAD

**Issue by Matthew-Harris-36** [osfans/trime#1354]
同文输入法3.2.18（20240501）版本在真我Neo3 安卓13上经常遇到点击输入框，输入法迟迟无法弹出的情况。已经有不少人遇到这问题了，请求大佬修复下。在各个APP上都会出现这问题，而且最近的几个版本都有这问题。另外，Trime在弹出的瞬间，经常会有正在部署的提示，希望能给去掉，输入法还是瞬间加载出来好些。
![image](https://github.com/osfans/trime/assets/62049321/3b517bfc-a471-4e0c-8dd7-389190cace7e)
演示视频：https://www.bilibili.com/video/BV1nr421u72S
[com.osfans.trime-2024-04-30T06_18_20Z.txt](https://github.com/osfans/trime/files/15159741/com.osfans.trime-2024-04-30T06_18_20Z.txt)
[Trime配置_240430.zip](https://github.com/osfans/trime/files/15159742/Trime._240430.zip)

**Comment by WhiredPlanck** [comment]
@BlueDolphin9527 你这是 4 月 20 日凌晨构建的每夜版 …… 我在群里不是让你更新到最新的每夜版试试看吗 ……，下载链接在这儿：https://github.com/osfans/trime/releases/download/nightly/com.osfans.trime-nightly-4-g3c852a8b-arm64-v8a-release.apk

**Comment by Matthew-Harris-36** [comment]
> @BlueDolphin9527 你这是 4 月 20 日凌晨构建的每夜版 …… 我在群里不是让你更新到最新的每夜版试试看吗 ……，下载链接在这儿：https://github.com/osfans/trime/releases/download/nightly/com.osfans.trime-nightly-4-g3c852a8b-arm64-v8a-release.apk

好的，我试下

**Comment by Matthew-Harris-36** [comment]
> @BlueDolphin9527 你这是 4 月 20 日凌晨构建的每夜版 …… 我在群里不是让你更新到最新的每夜版试试看吗 ……，下载链接在这儿：https://github.com/osfans/trime/releases/download/nightly/com.osfans.trime-nightly-4-g3c852a8b-arm64-v8a-release.apk

试了最新版，刚安装上就遇到无法弹出的问题。我看都没人提相关的issues，开发者大大又怎么会去修复呢？

**Comment by WhiredPlanck** [comment]
> > @BlueDolphin9527 你这是 4 月 20 日凌晨构建的每夜版 …… 我在群里不是让你更新到最新的每夜版试试看吗 ……，下载链接在这儿：https://github.com/osfans/trime/releases/download/nightly/com.osfans.trime-nightly-4-g3c852a8b-arm64-v8a-release.apk
> 
> 试了最新版，刚安装上就遇到无法弹出的问题。我看都没人提相关的issues，开发者大大又怎么会去修复呢？

有人提。要拿最新版试，不然出错的原因可能不一样，上一个出错的地方可能已经修好了

**Comment by Matthew-Harris-36** [comment]
> > > @BlueDolphin9527 你这是 4 月 20 日凌晨构建的每夜版 …… 我在群里不是让你更新到最新的每夜版试试看吗 ……，下载链接在这儿：https://github.com/osfans/trime/releases/download/nightly/com.osfans.trime-nightly-4-g3c852a8b-arm64-v8a-release.apk
> > 
> > 
> > 试了最新版，刚安装上就遇到无法弹出的问题。我看都没人提相关的issues，开发者大大又怎么会去修复呢？
> 
> 有人提。要拿最新版试，不然出错的原因可能不一样，上一个出错的地方可能已经修好了

现在换了最新版这个问题出现得更加频繁了，已经严重影响到日常生活了。

**Comment by WhiredPlanck** [comment]
> 现在换了最新版这个问题出现得更加频繁了，已经严重影响到日常生活了。

日常生活还是要多备用一个输入法，我自己也是。

**Comment by WhiredPlanck** [comment]
@BlueDolphin9527 能麻烦再提供一下安上最新版后的日志吗？还有告知一下你出问题时用的主题和方案

**Comment by Matthew-Harris-36** [comment]
@WhiredPlanck 我的最新版里有三个主题，tongwenfeng/trime/trime。我默认使用的是第二个，看到你回答后，我试了下其它两个，问题还是没有解决。需要说明的是最新版问题不一样了，是输入法不会自动隐退。用的方案是86五笔1
[com.osfans.trime.debug-2024-05-02T02_43_07Z.txt](https://github.com/osfans/trime/files/15183248/com.osfans.trime.debug-2024-05-02T02_43_07Z.txt)
演示视频：https://www.bilibili.com/video/BV1yf421S76d/
