### ISSUE TITLE
在输入状态下切换应用崩溃

### ISSUE THREAD

**Issue by nopdan** [osfans/trime#1356]
[com.osfans.trime-2024-04-30T17_03_46Z.txt](https://github.com/osfans/trime/files/15168376/com.osfans.trime-2024-04-30T17_03_46Z.txt)

https://github.com/osfans/trime/assets/47845580/8dae7a8c-e720-4e6f-9040-9b0f4bc2fa33

**Comment by WhiredPlanck** [comment]
还是悬浮窗的问题 ……
