### ISSUE TITLE
崩溃日志, 修改了default.yaml的page_size并重新部署就会崩溃一次,之后正常

### ISSUE THREAD

**Issue by jcleng** [osfans/trime#1365]
[com.osfans.trime-2024-05-09T01_24_43Z.txt](https://github.com/osfans/trime/files/15256449/com.osfans.trime-2024-05-09T01_24_43Z.txt)

使用的是配置是 [rime-ice](https://github.com/iDvel/rime-ice)

**Comment by WhiredPlanck** [comment]
此问题已修复，请用最新每夜版。

**Comment by jcleng** [comment]
每夜版按键输入就会崩溃 一直崩溃
[com.osfans.trime-2024-05-09T02_27_36Z.txt](https://github.com/osfans/trime/files/15256830/com.osfans.trime-2024-05-09T02_27_36Z.txt)

**Comment by WhiredPlanck** [comment]
> 每夜版按键输入就会崩溃 一直崩溃 [com.osfans.trime-2024-05-09T02_27_36Z.txt](https://github.com/osfans/trime/files/15256830/com.osfans.trime-2024-05-09T02_27_36Z.txt)

已经修复，请等待明天凌晨的每夜版

**Comment by WhiredPlanck** [comment]
> 每夜版按键输入就会崩溃 一直崩溃 [com.osfans.trime-2024-05-09T02_27_36Z.txt](https://github.com/osfans/trime/files/15256830/com.osfans.trime-2024-05-09T02_27_36Z.txt)

临时解决方案，给主题的 style/layout 下加一行名为 min_check 的参数，要大于 0

**Comment by jcleng** [comment]
> > 每夜版按键输入就会崩溃 一直崩溃 [com.osfans.trime-2024-05-09T02_27_36Z.txt](https://github.com/osfans/trime/files/15256830/com.osfans.trime-2024-05-09T02_27_36Z.txt)
> 
> 临时解决方案，给主题的 style/layout 下加一行名为 min_check 的参数，要大于 0

对的,加了min_check就ok了; 或者使用默认主题trime就不会崩溃

**Comment by jcleng** [comment]
部署的时候提示`replacing previously registered component: charset_filter`或者`couldn't list directory './': filesystem error: in directory_iterator::directory_iterator(...): Permission denied [./]`
[com.osfans.trime-2024-05-11T03_50_15Z.txt](https://github.com/osfans/trime/files/15281541/com.osfans.trime-2024-05-11T03_50_15Z.txt)

**Comment by WhiredPlanck** [comment]
> 部署的时候提示`replacing previously registered component: charset_filter`或者`couldn't list directory './': filesystem error: in directory_iterator::directory_iterator(...): Permission denied [./]` [com.osfans.trime-2024-05-11T03_50_15Z.txt](https://github.com/osfans/trime/files/15281541/com.osfans.trime-2024-05-11T03_50_15Z.txt)

可以无视
