### ISSUE TITLE
返回默认键盘时，会变成西文

### ISSUE THREAD

**Issue by rijejt523** [osfans/trime#137]
从26键键盘进入数字键盘后，中文会变成西文，再返回默认键盘，还是西文。返回键使用的是click: Keyboard_default。
请教一下如何返回的默认键盘时，可以变成原状态，就是西文进数字键盘，返回还是西文，中文进数字键盘返回还是中文。

**Comment by rijejt523** [comment]
暂时通过修改26键键盘的ascii_mode: 0达到返回时一直是中文状态，可不可以返回成原状态？

**Comment by xiaoqun2016** [comment]
这个问题很久以前就解决了，除非你用的是很旧的版本。  
见 #32   和 https://github.com/osfans/trime/commit/339b8e12cd32d90fc01484da660b7da2c6e4732b

**Comment by rijejt523** [comment]
我不是程序员，没有看懂第二个链接什么意思，第一个链接虽然能看懂，但又没看到解决办法，我使用的是google play上的最新版，更新日期是1月4号。我的手机是google pixel xl。到底修改哪里可以解决，希望能明确说明，谢谢。

**Comment by xiaoqun2016** [comment]
不需要修改啊，默认就是你要的效果。除非你自己更改了主题参数。可以回厂trime.yaml，用默认主题测试看。  

影响键盘中英切换的参数大致有两个：  
① 主键盘的`ascii_mode` (不能为1)  
② `style`里面的`reset_ascii_mode` (false)    
如果这些地方都检查过了仍然有问题，那有可能是新bug。

**Comment by rijejt523** [comment]
返回原厂的trime.yaml确实没有这个问题了，我使用的是原厂带的sougou.trime,yaml这个主题，自己又修改了一些颜色和参数，目前还在修改中，希望能做出Google 拼音样式的键盘，挂的是wubi86的码表，我看了一下sougou.trime.yaml，里面的reset_ascii_mode是false，主键盘的ascii_mode原来是1，我现在改成0，还是没能达到西文进数字键盘，返回还是西文，中文进数字键盘返回还是中文这个目标。
数字或符号键盘的ascii_mode也不能为1么？如果是这样，emoji可能无法正确输入啊？

**Comment by xiaoqun2016** [comment]
如果默认的`trime.yaml` 主题没问题，就照那样改。
