### ISSUE TITLE
新版同文（3.2.10之后）兼容性问题

### ISSUE THREAD

**Issue by yzswt** [osfans/trime#1375]
此版本之后，九宫格用不了，程序直接崩溃，还有很多其他问题，请适配。感谢

**Comment by nopdan** [comment]
你要搞清楚谁适配谁

**Comment by WhiredPlanck** [comment]
新版本的同文为了提升体验不得不做出一些破坏性的更新，请联系你喜欢的九宫格方案的作者对新版同文做出适配。

**Comment by WhiredPlanck** [comment]
新版本的同文为了提升体验不得不做出一些破坏性的更新，请联系你喜欢的九宫格方案的作者对新版同文做出适配。
