### ISSUE TITLE
输入到一半直接切应用，再点键盘会造成崩溃

### ISSUE THREAD

**Issue by Ennuyeux233** [osfans/trime#1376]
![Screenshot_2024-05-16-08-49-34-157_com.osfans.trime.jpg](https://github.com/osfans/trime/assets/82691837/21949717-aeb8-42e5-8bde-fcfc05038b0e)

![com.osfans.trime-2024-05-16T00_41_47Z.txt](https://github.com/osfans/trime/files/15328196/com.osfans.trime-2024-05-16T00_41_47Z.txt)

https://github.com/osfans/trime/assets/82691837/fa2925ff-0dd8-4cec-a477-d888c86ccde0

**Comment by pqmu1808** [comment]
输入部分编码而不提交，直接隐藏键盘。然后再打开键盘，悬浮窗上显示前次已输入的编码，接着点击字母键出现应用程序崩溃。
关闭悬浮窗后则不会出现此问题。
trime版本 v3.2.18-0-gc10e2e84-release
验证机型:
小米10S (Xiaomi HyperOS 1.0.30 / Android 13)
华为Pura 70 Pro+ (HarmonyOS 4.2.0)

**Comment by nopdan** [comment]
用 nightly 版本

**Comment by Ennuyeux233** [comment]
用nightly版本正常了，谢谢
