### ISSUE TITLE
关于最新每夜版语音输入可使用性的问题。

### ISSUE THREAD

**Issue by bandengzex** [osfans/trime#1377]
根据wiki知道语音调用是VOICE_ASSIST命令，但是我设置后发现无法启动语音引擎
![image](https://github.com/osfans/trime/assets/103732230/f82c5eae-53a6-4564-91e1-f4415373f9cc)
搜索之前的议题发现老版本出发语音后键盘是会缩回去的，但是现在并没有生效
我查看了hyperos的语音引擎是空的，但是如【阅读】软件是可以正常调用的小爱的tts的。（这里表达错了，把语音转文字和文字转语音弄混淆了。trime的语音输入应该依赖的是语音转文字吧）
想问一下现在最新版的trime是已经取消了语音输入么。

**Comment by nopdan** [comment]
语言输入和 tts 完全是两个东西。你可以安装讯飞语记再试试。

**Comment by bandengzex** [comment]
> 语言输入和 tts 完全是两个东西。你可以安装讯飞语记再试试。

我也尝试安装了讯飞语记，在系统的语音输入里面有这个选项也勾选了 ，但是按键后依然无效

**Comment by goofyz** [comment]
你要自己手動開啟「麥克風」權限，才能啟動 speech2text。不過我印象中是沒有相關 UI 的。

**Comment by bandengzex** [comment]
> 你要自己手動開啟「麥克風」權限，才能啟動 speech2text。不過我印象中是沒有相關 UI 的。

这个我常试过了，依然无法启动。
经群里老哥解释，目前知道高版本Android因为要求应用有联网权限才能获取语音识别的api，所以同文在高版本Android且是最新版app上目前似乎无法实现

**Comment by goofyz** [comment]
我自己用的版本是轉換到語音輸入法去的，但前提是你要先安裝其他的語音輸入法。
