### ISSUE TITLE
能否添加其他语言输入法？诸如韩语 日语 法语等？

### ISSUE THREAD

**Issue by ly2101** [osfans/trime#138]
使用这个输入法以后就不想再用别的了，但是又需要输入其他语言如韩语 日语 或者法语等 来回在不同的输入法之间切换太麻烦 而且安装多了还占用资源。有没有办法可以支持三种以上的语言输入？

**Comment by ly2101** [comment]
或者哪位指点一下如何 自行加入或者打补丁？

**Comment by osfans** [comment]
日韩有人做方案的 估计不太好用 法语不清楚了

**Comment by osfans** [comment]
可以去群里问问 这里先关闭了

**Comment by osfans** [comment]
韓語的方案比如這裏：
https://github.com/rime-aca/schemata/tree/master/hangyl

**Comment by MartinHu92** [comment]
> 或者哪位指点一下如何 自行加入或者打补丁？

最后有添加好韩语、日语、法语吗，求指教
