### ISSUE TITLE
[BUG] 首次安装TRIME输入法，没有rime文件夹导致无限崩溃

### ISSUE THREAD

**Issue by shitlime** [osfans/trime#1391]
触发BUG关键：
+ 手机存储根目录没有 `rime` 文件夹存在 （新用户首次安装）

复现步骤：
1. 安装TRIME
2. 点击图标打开
3. 崩溃
4. 2，3循环

**Comment by goofyz** [comment]
你的 trime 是否跟我一樣，是在 windows 上自行構建的？

**Comment by shitlime** [comment]
> 你的 trime 是否跟我一樣，是在 windows 上自行構建的？

是的。跟这个有关系？

**Comment by goofyz** [comment]
正常情況下，trime 會將 `trime.yaml`, `opencc` 等檔案覆製到 `rime` 資料夾，若這些檔案存在便不會崩潰。

Trime 現在會使用 [DataChecksumsPlugin](https://github.com/osfans/trime/blob/develop/build-logic/convention/src/main/kotlin/DataChecksumsPlugin.kt) 去產生 `checksums.json`，再用它對比是否需要進行覆製。你可查看一下， window 底下的 `checksums.json` 中的檔案路徑會用 window 的路行符號 `\`，而不是 linux/android 上的 `/`，所以檔案對比和覆製都會失敗。

解決方法是將 DataChecksumsPlugin 中用到 `File.path` 改為 `File.invariantSeparatorsPath`，`checksums.json` 的路徑就用回 `/` 了。
我有空再 PR 吧 (或者交給你了 😄  )

**Comment by shitlime** [comment]
我手动创建 rime 目录能用，所以不急着修复
