### ISSUE TITLE
打字点键盘的一瞬间收起键盘，会导致崩溃

### ISSUE THREAD

**Issue by Sourage** [osfans/trime#1396]
![Screenshot_2024-06-07-13-26-08-151_com.github.android.jpg](https://github.com/osfans/trime/assets/159985235/6c0a5d89-f590-4e15-bc55-2e9178fc52af)

触发后是这样的，退格无法删去卡在上面的拼音，此时再打字必定崩溃
打字过程中切换软件，或打游戏时被某些场景打断就很容易触发，然后部署浪费时间
(不怎么会组织语言，希望大佬们能看懂并修复，谢谢)

**Comment by WhiredPlanck** [comment]
烦请报告您所使用的版本，方便的话请附上日志。

**Comment by Sourage** [comment]
> 烦请报告您所使用的版本，方便的话请附上日志。

版本为3.2.18最新发行版
v3.2.18-0-gc10e2e84-release
构建者：Release CI
Git 仓库：https://github.com/osfans/trime
构建 Git 哈希：c10e2e84110e50cfc5f6c17443f5703bf35e3349
构建时间：2024年5月1日 20:08:02

日志文件
![com.osfans.trime-2024-06-14T05_55_32Z.txt](https://github.com/user-attachments/files/15832335/com.osfans.trime-2024-06-14T05_55_32Z.txt)

**Comment by WhiredPlanck** [comment]
请尽量使用最新每夜版或关闭悬浮窗功能。
