### ISSUE TITLE
可以推荐一个yaml编辑器么?

### ISSUE THREAD

**Issue by lihuichang** [osfans/trime#1397]
我想自己做个主题,弄了几天了,一直各种报错.
现在是用vscode手動编辑的,导入手机频繁报错,还找不到具体错在哪一行,😫
像是:span_exclusive cannot have a zero lenght
还有不能被0除之类的,直接崩溃,我基本每行都检查了,找不到目标在哪,很受打击啊.😑
大佬能不能让log输出具体哪个位置啊,现在有一部分会显示出错行号.
求推荐一个方便编辑yaml文件的编辑器,拜谢○|￣|_

**Comment by shitlime** [comment]
vscode 挺好的，你需要安装一下有LSP功能的插件，进一步对`trime.yaml`检查错误

**Comment by lihuichang** [comment]
> vscode 挺好的，你需要安装一下有LSP功能的插件，进一步对`trime.yaml`检查错误

找到问题了,键盘布局里不能加"auto_height_index"这个设置,不然程序崩溃.
