### ISSUE TITLE
为什么我的trime总是崩溃啊,没有稳定版吗

### ISSUE THREAD

**Issue by cnzxb** [osfans/trime#1398]
是我打开的方式不对吗,使用环境小米安卓12,挂vpn

**Comment by WhiredPlanck** [comment]
烦请报告一下您所使用的版本？（可以在 app 右上角菜单的关于中找到构建信息，长按复制后粘贴到这里）

**Comment by cnzxb** [comment]
3.2.18![Screenshot_2024-06-14-14-50-12-529_com.miui.securitycenter.jpg](https://github.com/osfans/trime/assets/15361723/68f0a265-3d5f-415b-82e7-2b88d74bac87)

**Comment by cnzxb** [comment]
![Screenshot_2024-05-29-17-16-34-327_com.android.settings.jpg](https://github.com/osfans/trime/assets/15361723/a39ec26d-7b79-4b31-a64d-6c5e287079e5)

![Screenshot_2024-02-02-12-38-51-552_flar2.devcheck.jpg](https://github.com/osfans/trime/assets/15361723/59f0cd13-d5c0-4ab7-a6c2-9d378464a61c)

**Comment by cnzxb** [comment]
![Screenshot_2024-02-02-12-38-42-763_flar2.devcheck.jpg](https://github.com/osfans/trime/assets/15361723/732eb2c3-e5b2-4bef-9089-b6ca9eb72be5)

**Comment by cnzxb** [comment]
![Screenshot_2024-06-14-14-57-23-553_flar2.devcheck.jpg](https://github.com/osfans/trime/assets/15361723/a2ebb363-1c5d-4543-bf4f-5309d204732b)

**Comment by cnzxb** [comment]
![Screenshot_2024-06-14-15-05-13-941_com.osfans.trime.jpg](https://github.com/osfans/trime/assets/15361723/da842a34-4ecb-48f8-9cdc-bb43e5218dcc)

**Comment by WhiredPlanck** [comment]
这是 5 月 1 日发布的正式版本，发布时还有个 bug 没有来得及修复，现在已经修好了。请尽量使用最新每夜版，或关闭悬浮窗功能。
