### ISSUE TITLE
語音輸入不工作？

### ISSUE THREAD

**Issue by mrpurplecloud** [osfans/trime#140]
請問voice_assit這個命令是否已經可用呢？配置了以後沒有什麼效果，按鍵後連錯誤提示都沒有。Android 7.0，安裝的是最新版本的訊飛語記

**Comment by osfans** [comment]
要開語音權限吧？

**Comment by mrpurplecloud** [comment]
同文輸入法要的所有權限都已經給了，華爲P9,EMUI 5.0

**Comment by osfans** [comment]
那語音看看？說不定就成功了？

**Comment by mrpurplecloud** [comment]
反覆實驗,發現在只有在訊飛語記也在運行狀態下的時候能輸入。能不能在按下語音鍵的時候自動激活訊飛呢?另外, 沒有提示還是很不方便，萬一沒按好也不知道，可能說半天都沒用。有沒有辦法增加一個狀態提示呢？用聲音也行。要是這兩個問題解決了我就可以把搜狗給卸了。感恩做出這麼酷的輸入法！！

**Comment by osfans** [comment]
確實有這個問題。
要運行語記才行，不知是不是系統有限制。用安卓自帶的語音就沒有問題。
