### ISSUE TITLE
似乎ascii_keyboard tag不工作

### ISSUE THREAD

**Issue by FlyingpigNZ** [osfans/trime#1407]
最近在研究怎么做一个小鹤双拼的14键布局。
基本上布局已经可以工作了。
因为是非标准键盘，所以想通过ascii_keyboard: english来切换到标准的英文键盘。
从原理上来说应该是在切换的时候激活26键的标准英文键盘。
但是发现
    name: "小鹤双拼双键"
    width: 20
    height: 35
    ascii_mode: 0
    **ascii_keyboard: english**
    lock: true
    keys:
不工作。
跟了一下代码，发现以下可能有问题。
/app/src/main/java/com/osfans/trime/ime/keyboard/Keyboard.kt第167行
 -        if (asciiMode) asciiKeyboard = obtainString(keyboardConfig, "ascii_keyboard", "")
+        if (!asciiMode) asciiKeyboard = obtainString(keyboardConfig, "ascii_keyboard", "")
我的理解是应该是非ascii键盘（ascii_mode:0）的布局才需要ascii_keyboard。现在的逻辑似乎刚好反了。修改之后本地build的正常工作了。

另外，逻辑上说，如果指定了ascii_keyboard: english这个属性。在模式切换（change ascii_mode）的时候应该优先使用这个键盘吧。现在似乎取的是default id的键盘。具体我还没有跟。

因为修改挺简单。先把发现的东西放这里。维护者可以直接确认逻辑是否正确。
等回头能找到空闲时间，我再去拉个fork。

**Comment by WhiredPlanck** [comment]
@FlyingpigNZ 你的分析是正确的，查看最原始时期的代码，可以看到：

https://github.com/osfans/trime/blob/1e5daf1b08690422190a8b21de18506ad9d72305/app/src/main/java/com/osfans/trime/Keyboard.java#L162-L163

`mAsciiMode`（`asciiMode`）原先是 Int 类型，当其为 0 时（即现在的 `asciiMode` 为 `false` 时）才为 `asciiKeyboard` 赋值。确实是搞反了，这是代码重构造成的失误。感谢反馈。


> 等回头能找到空闲时间，我再去拉个fork。

如果你时间不足，我可以在提交中标注协作者，这样你的头像也会出现在 GitHub 的提交里了，不知是否可以？我也可以等你的 PR～

**Comment by jinmaonz** [comment]
> @FlyingpigNZ 你的分析是正确的，查看最原始时期的代码，可以看到：
> 
> https://github.com/osfans/trime/blob/1e5daf1b08690422190a8b21de18506ad9d72305/app/src/main/java/com/osfans/trime/Keyboard.java#L162-L163
> 
> `mAsciiMode`（`asciiMode`）原先是 Int 类型，当其为 0 时（即现在的 `asciiMode` 为 `false` 时）才为 `asciiKeyboard` 赋值。确实是搞反了，这是代码重构造成的失误。感谢反馈。
> 
> 
> > 等回头能找到空闲时间，我再去拉个fork。
> 
> 如果你时间不足，我可以在提交中标注协作者，这样你的头像也会出现在 GitHub 的提交里了，不知是否可以？我也可以等你的 PR～

您可以直接在您那边的分支直接修改了然后提交。
我说fork的意思是看看能不能为这个项目尽一点微薄之力。等我回头fork了再参与进来。

**Comment by FlyingpigNZ** [comment]
> @FlyingpigNZ 你的分析是正确的，查看最原始时期的代码，可以看到：
> 
> https://github.com/osfans/trime/blob/1e5daf1b08690422190a8b21de18506ad9d72305/app/src/main/java/com/osfans/trime/Keyboard.java#L162-L163
> 
> `mAsciiMode`（`asciiMode`）原先是 Int 类型，当其为 0 时（即现在的 `asciiMode` 为 `false` 时）才为 `asciiKeyboard` 赋值。确实是搞反了，这是代码重构造成的失误。感谢反馈。
> 
> 
> > 等回头能找到空闲时间，我再去拉个fork。
> 
> 如果你时间不足，我可以在提交中标注协作者，这样你的头像也会出现在 GitHub 的提交里了，不知是否可以？我也可以等你的 PR～

我的意思是您可以合并到您的PR里，标注协作现在不重要，我fork的意思是想找点时间看看能不能为这个项目尽一点微薄之力。
输入法实在是一个大家都绕不开的东西。

**Comment by WhiredPlanck** [comment]
@FlyingpigNZ 感谢你的支持

**Comment by Lucas-Wye** [comment]
> 最近在研究怎么做一个小鹤双拼的14键布局。 基本上布局已经可以工作了。 因为是非标准键盘，所以想通过ascii_keyboard: english来切换到标准的英文键盘。 从原理上来说应该是在切换的时候激活26键的标准英文键盘。 但是发现 name: "小鹤双拼双键" width: 20 height: 35 ascii_mode: 0 **ascii_keyboard: english** lock: true keys: 不工作。 跟了一下代码，发现以下可能有问题。 /app/src/main/java/com/osfans/trime/ime/keyboard/Keyboard.kt第167行
> 
>     * ```
>          if (asciiMode) asciiKeyboard = obtainString(keyboardConfig, "ascii_keyboard", "")
>       ```
> 
> 
>     * ```
>          if (!asciiMode) asciiKeyboard = obtainString(keyboardConfig, "ascii_keyboard", "")
>       ```
> 
> 
> 我的理解是应该是非ascii键盘（ascii_mode:0）的布局才需要ascii_keyboard。现在的逻辑似乎刚好反了。修改之后本地build的正常工作了。
> 
> 另外，逻辑上说，如果指定了ascii_keyboard: english这个属性。在模式切换（change ascii_mode）的时候应该优先使用这个键盘吧。现在似乎取的是default id的键盘。具体我还没有跟。
> 
> 因为修改挺简单。先把发现的东西放这里。维护者可以直接确认逻辑是否正确。 等回头能找到空闲时间，我再去拉个fork。

可以分享一下双键双拼的配置文件吗@FlyingpigNZ

**Comment by FlyingpigNZ** [comment]
> > 最近在研究怎么做一个小鹤双拼的14键布局。 基本上布局已经可以工作了。 因为是非标准键盘，所以想通过ascii_keyboard: english来切换到标准的英文键盘。 从原理上来说应该是在切换的时候激活26键的标准英文键盘。 但是发现 name: "小鹤双拼双键" width: 20 height: 35 ascii_mode: 0 **ascii_keyboard: english** lock: true keys: 不工作。 跟了一下代码，发现以下可能有问题。 /app/src/main/java/com/osfans/trime/ime/keyboard/Keyboard.kt第167行
> > ```
> > * ```
> >      if (asciiMode) asciiKeyboard = obtainString(keyboardConfig, "ascii_keyboard", "")
> >   ```
> > 
> > 
> > * ```
> >      if (!asciiMode) asciiKeyboard = obtainString(keyboardConfig, "ascii_keyboard", "")
> >   ```
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我的理解是应该是非ascii键盘（ascii_mode:0）的布局才需要ascii_keyboard。现在的逻辑似乎刚好反了。修改之后本地build的正常工作了。
> > 另外，逻辑上说，如果指定了ascii_keyboard: english这个属性。在模式切换（change ascii_mode）的时候应该优先使用这个键盘吧。现在似乎取的是default id的键盘。具体我还没有跟。
> > 因为修改挺简单。先把发现的东西放这里。维护者可以直接确认逻辑是否正确。 等回头能找到空闲时间，我再去拉个fork。
> 
> 可以分享一下双键双拼的配置文件吗[@FlyingpigNZ](https://github.com/FlyingpigNZ)

@Lucas-Wye 
https://github.com/FlyingpigNZ/trime/tree/develop-enhancement/schemas_and_themes
我放到这里了。

**Comment by Lucas-Wye** [comment]
> > > 最近在研究怎么做一个小鹤双拼的14键布局。 基本上布局已经可以工作了。 因为是非标准键盘，所以想通过ascii_keyboard: english来切换到标准的英文键盘。 从原理上来说应该是在切换的时候激活26键的标准英文键盘。 但是发现 name: "小鹤双拼双键" width: 20 height: 35 ascii_mode: 0 **ascii_keyboard: english** lock: true keys: 不工作。 跟了一下代码，发现以下可能有问题。 /app/src/main/java/com/osfans/trime/ime/keyboard/Keyboard.kt第167行
> > > ```
> > > * ```
> > >      if (asciiMode) asciiKeyboard = obtainString(keyboardConfig, "ascii_keyboard", "")
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > * ```
> > >      if (!asciiMode) asciiKeyboard = obtainString(keyboardConfig, "ascii_keyboard", "")
> > >   ```
> > > 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我的理解是应该是非ascii键盘（ascii_mode:0）的布局才需要ascii_keyboard。现在的逻辑似乎刚好反了。修改之后本地build的正常工作了。
> > > 另外，逻辑上说，如果指定了ascii_keyboard: english这个属性。在模式切换（change ascii_mode）的时候应该优先使用这个键盘吧。现在似乎取的是default id的键盘。具体我还没有跟。
> > > 因为修改挺简单。先把发现的东西放这里。维护者可以直接确认逻辑是否正确。 等回头能找到空闲时间，我再去拉个fork。
> > > ```
> > 
> > 
> > 可以分享一下双键双拼的配置文件吗[@FlyingpigNZ](https://github.com/FlyingpigNZ)
> 
> [@Lucas-Wye](https://github.com/Lucas-Wye) https://github.com/FlyingpigNZ/trime/tree/develop-enhancement/schemas_and_themes 我放到这里了。

谢谢，但是现在有些字似乎打不出来了，比如说 xue，需要按zx键和t键，但是按zx键的时候不会筛选出x，这要怎么解决啊[@FlyingpigNZ](https://github.com/FlyingpigNZ)

**Comment by FlyingpigNZ** [comment]
> zx

这个是小鹤双拼的编码，xue应该是zx加上ty两个键哈，也就是xt。倒是发现仍字敲er加gh出不来，但是仍然两个一起打就可以。
这个我都是声母韵母全打完再选择的，不单独选声韵母。

**Comment by Lucas-Wye** [comment]
> > zx
> 
> 这个是小鹤双拼的编码，xue应该是zx加上ty两个键哈，也就是xt。倒是发现仍字敲er加gh出不来，但是仍然两个一起打就可以。 这个我都是声母韵母全打完再选择的，不单独选声韵母。

谢谢，还有一个问题是每次打开双键双拼之后开始按键都没有候选词，这个情况应该怎么处理？

**Comment by FlyingpigNZ** [comment]
> > > zx
> > 
> > 
> > 这个是小鹤双拼的编码，xue应该是zx加上ty两个键哈，也就是xt。倒是发现仍字敲er加gh出不来，但是仍然两个一起打就可以。 这个我都是声母韵母全打完再选择的，不单独选声韵母。
> 
> 谢谢，还有一个问题是每次打开双键双拼之后开始按键都没有候选词，这个情况应该怎么处理？

不是很明白这个问题。
比如说我打“好”这个字。

![Image](https://github.com/user-attachments/assets/60302adf-3704-46f1-b039-70bdb8f4a381)
![Image](https://github.com/user-attachments/assets/bc017403-599a-4805-b823-08875aa39739)
声母h，由于h和g在一起，所以编码会提示g，但是会把g和h为声母的字都列出来。
韵母ao，也就是c。打了c之后，编码变成gao，但是候选单里列出的是gh，cv的所有组合，也就是gao, hao, gui, hui这些都会填入到候选列表里。如果你继续声母韵母打下去组成词句的话，长的常用词就会到前面。单字往后了。
另外，可能和你用的词库也有关系。
我现在用的词库是:
https://github.com/iDvel/rime-ice
这里的。

**Comment by Lucas-Wye** [comment]
> > > > zx
> > > 
> > > 
> > > 这个是小鹤双拼的编码，xue应该是zx加上ty两个键哈，也就是xt。倒是发现仍字敲er加gh出不来，但是仍然两个一起打就可以。 这个我都是声母韵母全打完再选择的，不单独选声韵母。
> > 
> > 
> > 谢谢，还有一个问题是每次打开双键双拼之后开始按键都没有候选词，这个情况应该怎么处理？
> 
> 不是很明白这个问题。 比如说我打“好”这个字。
> 
> ![Image](https://github.com/user-attachments/assets/60302adf-3704-46f1-b039-70bdb8f4a381) ![Image](https://github.com/user-attachments/assets/bc017403-599a-4805-b823-08875aa39739) 声母h，由于h和g在一起，所以编码会提示g，但是会把g和h为声母的字都列出来。 韵母ao，也就是c。打了c之后，编码变成gao，但是候选单里列出的是gh，cv的所有组合，也就是gao, hao, gui, hui这些都会填入到候选列表里。如果你继续声母韵母打下去组成词句的话，长的常用词就会到前面。单字往后了。 另外，可能和你用的词库也有关系。 我现在用的词库是: https://github.com/iDvel/rime-ice 这里的。

![Image](https://github.com/user-attachments/assets/b002df0e-095f-4389-89c4-58dfff1f6449)

我现在是不管按任何键都没有候选词，我把你分享的yaml跟rime-ice的放到一起然后重新部署了，这是软件的原因吗，我现在用的是最新release的那一版本，v3.3.2

**Comment by FlyingpigNZ** [comment]
> > > > > zx
> > > > 
> > > > 
> > > > 这个是小鹤双拼的编码，xue应该是zx加上ty两个键哈，也就是xt。倒是发现仍字敲er加gh出不来，但是仍然两个一起打就可以。 这个我都是声母韵母全打完再选择的，不单独选声韵母。
> > > 
> > > 
> > > 谢谢，还有一个问题是每次打开双键双拼之后开始按键都没有候选词，这个情况应该怎么处理？
> > 
> > 
> > 不是很明白这个问题。 比如说我打“好”这个字。
> > ![Image](https://github.com/user-attachments/assets/60302adf-3704-46f1-b039-70bdb8f4a381) ![Image](https://private-user-images.githubusercontent.com/93568111/410372920-bc017403-599a-4805-b823-08875aa39739.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg4MzcyNzksIm5iZiI6MTczODgzNjk3OSwicGF0aCI6Ii85MzU2ODExMS80MTAzNzI5MjAtYmMwMTc0MDMtNTk5YS00ODA1LWI4MjMtMDg4NzVhYTM5NzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjA2VDEwMTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MTQ5YjdkZWFhZGM3MjdkODMyMzY0NDRkNGI0MzUzMjlhZGYzNjhmOGJiYzY1OTg5MmYzMDBkNTU0MmM1MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fckkg0w0QVPR8Som8alKvf_-EXKxWPsYCJEYh_GGW9Q) 声母h，由于h和g在一起，所以编码会提示g，但是会把g和h为声母的字都列出来。 韵母ao，也就是c。打了c之后，编码变成gao，但是候选单里列出的是gh，cv的所有组合，也就是gao, hao, gui, hui这些都会填入到候选列表里。如果你继续声母韵母打下去组成词句的话，长的常用词就会到前面。单字往后了。 另外，可能和你用的词库也有关系。 我现在用的词库是: https://github.com/iDvel/rime-ice 这里的。
> 
> ![Image](https://github.com/user-attachments/assets/b002df0e-095f-4389-89c4-58dfff1f6449)
> 
> 我现在是不管按任何键都没有候选词，我把你分享的yaml跟rime-ice的放到一起然后重新部署了，这是软件的原因吗，我现在用的是最新release的那一版本，v3.3.2

我不记得主题是否也有影响，我把我现在手机上用的主题和码表一起放上来了你切换到包里的主题再试试。另外我用的是源码自行编译的，因为我有些个人需求，做了点小改动。但是这个应该没有影响。
从你的截图来看，感觉你现在还是ascii布局，所以可能是输出的英文，而不是中文，这个可能和主题里输入法切换的设置有关了，你试试我贴上来的主题吧。

[yamls.tar.gz](https://github.com/user-attachments/files/18688257/yamls.tar.gz)

**Comment by Lucas-Wye** [comment]
> 我不记得主题是否也有影响，我把我现在手机上用的主题和码表一起放上来了你切换到包里的主题再试试。另外我用的是源码自行编译的，因为我有些个人需求，做了点小改动。但是这个应该没有影响。 从你的截图来看，感觉你现在还是ascii布局，所以可能是输出的英文，而不是中文，这个可能和主题里输入法切换的设置有关了，你试试我贴上来的主题吧。
> 
> [yamls.tar.gz](https://github.com/user-attachments/files/18688257/yamls.tar.gz)

![Image](https://github.com/user-attachments/assets/724a8193-886e-43da-8c0c-332209d6c468)

![Image](https://github.com/user-attachments/assets/62fbe6a4-c55c-4ad5-a2af-93cb42a7a3cc)


感觉还是有问题，我这里只显示gao相关的词，没有hao的。h似乎不起作用？

**Comment by WhiredPlanck** [comment]
@Lucas-Wye @FlyingpigNZ 感谢两位对同文的支持。本 Issue 已经关闭，原则上不进行“挖楼”，如果需要更深入的普遍交流讨论，可以右转至本项目的 Discussion 区，那里更适合交流和分享心得。也可以加入我们的社群：

TRIME 同文输入法平台（QQ 群）：224230445
Rime 薈萃（QQ 群）：241934418
trime-dev（Telegram）：https://t.me/trime_dev
RIME（Telegram）：https://t.me/iloverime
