### ISSUE TITLE
liquid keyboard候选框导致crash

### ISSUE THREAD

**Issue by FlyingpigNZ** [osfans/trime#1409]
[com.osfans.trime-2024-06-22T09_55_46Z.txt](https://github.com/user-attachments/files/15936099/com.osfans.trime-2024-06-22T09_55_46Z.txt)
报告在这里，应该是
```
    @SuppressLint("NotifyDataSetChanged")
    fun updateCandidates(candidates: List<CandidateListItem>) {
        mCandidates.clear()
        mCandidates.addAll(candidates)
        notifyDataSetChanged()
    }
```
这里导致的，重现方式：
1. 打开输入法：
输入一些字符，打开liquid keyboard
往下拖动一点，比如说一行。
选中第二行的字符。
如图：
![select_first](https://github.com/osfans/trime/assets/93568111/abc1d872-01c9-456b-94d2-af86a534bfe0)
然后就crash了：
![crashed](https://github.com/osfans/trime/assets/93568111/2d354028-775d-40f2-b0c7-f557cd9e985f)

**Comment by WhiredPlanck** [comment]
@FlyingpigNZ 正如你在 PR 里所说，`notifyDataSetChanged` 这个函数是有 bug 的，在其他 adapter 里我改了，只有 `CandidateAdapter` 我没改，因为我想之后大改版就先没管 ……
