### ISSUE TITLE
長度單位

### ISSUE THREAD

**Issue by DaengGWokFook** [osfans/trime#141]
1. apk安裝包裏的鍵盤是一個鍵一行，但部署後變成所有鍵位在同一行。
個人認爲以上兩者都不方便查找鍵位，建議一行碼對應一行鍵位。
2. 默認鍵盤高度與寬度都是數字，很難理解其涵義。建議增加單位，例如：cm、mm、%等。
個人認爲%最好，因爲每個電子產品的屏幕大小不一，但比例幾乎一樣。

**Comment by osfans** [comment]
第一個沒有辦法，yaml重新部署就這樣了。
第二個不錯，之前也想過要這樣改。

**Comment by Bambooin** [comment]
过时的 issue
