### ISSUE TITLE
小白求问：无法修改3.2.18的tongwenfeng.trime.yaml，一部署就恢复原样，这是设定好的吗

### ISSUE THREAD

**Issue by BlueShipper** [osfans/trime#1418]
RT custom.yaml能工作，因为不懂怎么所有方案都优先用自定义键盘布局，于是偷懒把tongwenfeng.trime.yaml预设键盘修改成自定义，但是无论如何，一重新部署就恢复原状。哪怕只是全文件只改键盘高度，该文件也会恢复原样。这时现在版本都设定好的吗？还是我配置出错。

前情↓
本小白一直在用的都是google play 的古早版本。配置几乎平移小狼毫的用户文件夹，无更新意愿，直接在tongwenfeng.trime.yaml上修改。直到前天终于发现同文输入法从Google play 消失了？？才想还是更新一下吧。
接着f-droid至更新3.2.18。版本大跃迁，不熟悉搞不来。各种崩溃，又看不懂日志。无奈下载了还是很古早的3.2.3版本，看描述觉得够用就行。这回，在tongwenfeng.trime.yaml只修改了预设键盘布局，其余需求patch，成功了没有遇上问题，于是又动了更新至最新版的心思。折腾一番后遇上了如题所述。现在又退回3.2.3。

**具体疑问↓↓**
①3.2.3到3.2.18，共享/用户文件夹都是/sdcard/rime （查了很久真的不懂共享配哪，好像不配照常用），custom.yaml——配色方案，min_length，悬浮窗图标。然后故伎重施，在tongwenfeng.trime.yaml修改键盘布局。然后……发现无法修改。无论是外面改了再替换，还是同一文件修改保存，在部署之后，它都会恢复原样。鉴于我顺利使用的版本都太古早，所以想问问**是不是版本迭新后的设定**。
②还有一个需求是修改键盘高度，3.2.18键盘太高了，没找到教程案例，试了试"style/layout/" or "style/"都没改掉。

**Comment by linzianxyz** [comment]
试试，新建tonewenfeng.cuatom，在这里修改。
[tongwenfeng.trime.custom.zip](https://github.com/user-attachments/files/16066021/tongwenfeng.trime.custom.zip)

**Comment by BlueShipper** [comment]
> 试试，新建tonewenfeng.cuatom，在这里修改。 [tongwenfeng.trime.custom.zip](https://github.com/user-attachments/files/16066021/tongwenfeng.trime.custom.zip)

有用这个，但是不知道怎么通过这个自定义键盘布并替代预设的，所以才改tongwenfeng.trime.yaml的

**Comment by BlueShipper** [comment]
还有一个不影响使用的问题，是除了谷歌商店的版本，在别的版本上我都无法选择方案，新下的无法选中，旧的无法取消。而刚刚重下雾凇方案，把lua也更新后，这个问题就消失了。
我不懂这是个什么东西，但rt的问题是不是也和这个有关？

**Comment by WhiredPlanck** [comment]
@DHONEST  `trime.yaml` 和 `tongwenfeng.trime.yaml` 是同文内置/自带的配置文件，原则上确实是不可直接修改（即有可能会随应用更新而更新）。如果你确需在原有基础上添加自己的修改，请使用 .custom.yaml 后缀文件来“打补丁”，比如要对 `tongwenfeng.trime.yaml` 进行修改，你需要在用户文件夹新建 `tongwenfeng.custom.yaml` 文件，内容格式请参见 [Rime 定制指南](https://github.com/rime/home/wiki/CustomizationGuide)。

**Comment by sdlkfjkasdjfkl** [comment]
@WhiredPlanck  同问，尝试过版本 3.2.18 和 3.2.19, 在trime.custom.yaml 文件 修改 "style/layout/" or "style/"都没改掉。在3.30 preset_keys 不行了。谢谢您
