### ISSUE TITLE
五笔86“斗”打不出

### ISSUE THREAD

**Issue by laoxipi** [osfans/trime#142]
五笔86“斗”打不出，斗争可以，有斗的词貌似都能打出，“ufk码”没“斗”字

**Comment by Prcuvu** [comment]
五笔86词库的ufk编码有“斗”字。建议上传输入ufk没有出现“斗”字的截图。

**Comment by laoxipi** [comment]
截图在这里 [截图](https://cloud.githubusercontent.com/assets/26075091/24938725/81a8c574-1f6b-11e7-8bc7-83c38939d549.png)

**Comment by osfans** [comment]
懷疑是用了電腦上的bin。目前只有yaml通用，bin並不通用。

**Comment by laoxipi** [comment]
@osfans 大概你说的对了，图省事用了酷字评论区某位的配置，刚才重新用自己电脑上的配置了一下就好了，谢谢各位。
