### ISSUE TITLE
打开设置悬浮窗，输入文字闪退

### ISSUE THREAD

**Issue by bauw2008** [osfans/trime#1429]
### 摘要 / Summary

使用的是五笔词库，当输入超过4码会造成闪退，然后恢复。取消设置悬浮窗选项，问题消失。

### 重现步骤 / Steps to Reproduce

任意输入框、文本、浏览器等位置。

### 预期行为 / Expected Behavior

。。

### 日志 / Log

[com.osfans.trime-2024-07-15T10﹕36﹕12Z.txt](https://github.com/user-attachments/files/16233743/com.osfans.trime-2024-07-15T10.36.12Z.txt)

### 截图 / Screenshot

https://github.com/user-attachments/assets/00bcc3d4-5b45-4357-a549-c6f16b78a436

### 附加信息 / Additional Context

同文主题

### 系统版本 / OS Version

安卓10

### 应用版本 / App Version

nightly-0-g1cc9edde-arm64-v8a-release

### 构建信息 / Build Information

构建者：Nightly CI
Git 仓库：https://github.com/osfans/trime
构建 Git 哈希：9a5d2962a10dfd77d347ba55508180ee49402e5a
构建时间：2024年7月12日 00:05:49

**Comment by WhiredPlanck** [comment]
Fixed by #1430,  close.
