### ISSUE TITLE
如何添加一个“部署”的键

### ISSUE THREAD

**Issue by huangyg11** [osfans/trime#143]
想要在键盘上添加一个“部署”的按键。添加了如下配置

    "preset_keys/Deploy":
      command: run
      label: 部署
      option: "com.osfans.trime.deploy"
      send: function

但是点击之后，总是停止运行。请问该如何添加呢？

**Comment by osfans** [comment]
沒試過，我試試

**Comment by osfans** [comment]
06beb12afe8a9b5f07a3f62d5844e238161cccc7 添加。
