### ISSUE TITLE
候選字位置不能統一

### ISSUE THREAD

**Issue by linzianxyz** [osfans/trime#1431]
### 摘要 / Summary

用的最新每夜版，安卓12，和手機無關。
正常輸入編碼時候選字高度與帶有備註的候選字高度不一致。如下圖：
![IMG_20240718_131001](https://github.com/user-attachments/assets/4b498711-be8f-4bf4-9286-faf377256802)

### 重现步骤 / Steps to Reproduce

1.正常輸入候選，如二
2.反查，如朙月拼音，設置筆畫反查，反查按下`，輸入hh。即能看出1和2候選字的高度不同。
另外這個問題也同時存在於emoji、簡繁轉換提示等。

### 预期行为 / Expected Behavior

高度一致，改善用家體驗。

### 截图 / Screenshot

![IMG_20240718_131001](https://github.com/user-attachments/assets/30e61137-ed02-48fe-8426-d10021d3c019)

### 系统版本 / OS Version

安卓12

### 应用版本 / App Version

nightly-1-gd4a581d4-release

### 构建信息 / Build Information

构建者：Nightly CI
Git 仓库：https://github.com/osfans/trime
构建 Git 哈希：d4a581d4999c4f2264b59806df09631dc02ffa38

**Comment by WhiredPlanck** [comment]
本来就是“不一样的”。没有编码时，候选字会居中，有编码则稍靠下。

**Comment by linzianxyz** [comment]
> 本来就是“不一样的”。没有编码时，候选字会居中，有编码则稍靠下。

但是爲什麼要不一樣呢？如果有編碼的話，不需要候選字“下沉”呀？這樣的話，會有一種割裂感。再說，無論是小狼毫還是其他平臺，都沒有。最後，如果是因爲加在上面，將字“壓沉”，那麼同文有沒有提供將編碼放在候選字的右邊呢？

**Comment by MISTER-CHAN** [comment]
> > 本来就是“不一样的”。没有编码时，候选字会居中，有编码则稍靠下。
> 
> 但是爲什麼要不一樣呢？如果有編碼的話，不需要候選字“下沉”呀？這樣的話，會有一種割裂感。再說，無論是小狼毫還是其他平臺，都沒有。最後，如果是因爲加在上面，將字“壓沉”，那麼同文有沒有提供將編碼放在候選字的右邊呢？

可以在鍵盤主題裡將編碼設定在候選字右邊。不過我贊成提供一項設定將候選字改回同一高度。
