### ISSUE TITLE
切换方案后键盘消失

### ISSUE THREAD

**Issue by MISTER-CHAN** [osfans/trime#1447]
### 摘要 / Summary

切换方案后键盘消失，只剩下候选栏，如影片所示。

### 重现步骤 / Steps to Reproduce

https://github.com/user-attachments/assets/dc1cc347-edcd-4aa9-bf2f-5c89be25757c

### 预期行为 / Expected Behavior

键盘不应消失。

### 附加信息 / Additional Context

问题自夜版 7月 24日至今一直存在。

### 系统版本 / OS Version

Android 14

### 应用版本 / App Version

nightly-0-gdb08b6db-release

### 构建信息 / Build Information

建構者：Nightly CI
Git 倉庫：https://github.com/osfans/trime
建構 Git 雜湊值：db08b6db8aa62723643162037a2e34497f502be3
建構時間：2024年8月21日 00:05:48

**Comment by linzianabc** [comment]
我用的是19号的每夜版。没有出现你说的情况,切换方案不会重启。

**Comment by WhiredPlanck** [comment]
已知顽疾。和主题设置有一定关系。临时解决方案是暂时换成其他主题。

**Comment by MISTER-CHAN** [comment]
> 已知顽疾。和主题设置有一定关系。临时解决方案是暂时换成其他主题。

经实验，目前发现引起问题的缘故为切换方案时切换至以下键盘之一：
- 该键盘 ID 为 `qwerty`、`qwerty0` 或 `qwerty_`
- 该键盘 ID 为方案 ID

**Comment by WhiredPlanck** [comment]
> > 已知顽疾。和主题设置有一定关系。临时解决方案是暂时换成其他主题。
> 
> 经实验，目前发现引起问题的缘故为切换方案时切换至以下键盘之一：
> 
> * 该键盘 ID 为 `qwerty`、`qwerty0` 或 `qwerty_`
> * 该键盘 ID 为方案 ID

感谢提供信息，之后会进一步调查。

**Comment by stfy11** [comment]
切換方案和更換配色都會出現此問題

**Comment by Yh793** [comment]
> > > 已知顽疾。和主题设置有一定关系。临时解决方案是暂时换成其他主题。
> > 
> > 
> > 经实验，目前发现引起问题的缘故为切换方案时切换至以下键盘之一：
> > 
> > * 该键盘 ID 为 `qwerty`、`qwerty0` 或 `qwerty_`
> > * 该键盘 ID 为方案 ID
> 
> 感谢提供信息，之后会进一步调查。

```
切换方案已知的问题
默认主题内置多个键盘布局会出现切换方案出现这个问题。3.2.19
同文风只有一个内置布局就没有这个问题。
测试只保留默认主题的默认键盘切方案可以保持键盘。
```
切换主题还是会复现。

编辑：
[切换方案的问题由这个Pr引入](https://github.com/osfans/trime/pull/1432)
[主题问题由此PR引入](https://github.com/osfans/trime/pull/1460)b7eee6f62d36ba5a6eaa57fa44990553129b8e79
@WhiredPlanck
