### ISSUE TITLE
如何高效调试

### ISSUE THREAD

**Issue by huangyg11** [osfans/trime#145]
现在是用 AS 搭建了环境。用 make apk 编译，再安装到手机上。这在开发中有几个问题：

1) 每次都要重新启用，选择输入法，重新部署配置。
2) 没法利用AS来调试。

想问一下，是否有更高效的方法。谢谢！

**Comment by osfans** [comment]
目前沒有直接調試的方法，你熟悉的話幫忙加下。

我這裏覆蓋安裝的話，不需要每次都重新啓用，選擇。

**Comment by osfans** [comment]
另外sdk26已經放棄ant了，我也準備轉到gradle了。

**Comment by hhbluestar** [comment]
微信朋友圈评论不能输入任何字符。
