### ISSUE TITLE
呼出键盘程序直接崩溃

### ISSUE THREAD

**Issue by monodyjun** [osfans/trime#1450]
### 摘要 / Summary

之前用的好好的，突然在任意一界面呼出键盘程序直接崩溃。

### 重现步骤 / Steps to Reproduce

呼出键盘

### 预期行为 / Expected Behavior

程序崩溃

### 日志 / Log

[com.osfans.trime-2024-08-28T06_46_22Z.txt](https://github.com/user-attachments/files/16777598/com.osfans.trime-2024-08-28T06_46_22Z.txt)

### 截图 / Screenshot

![Screenshot_20240828_145349](https://github.com/user-attachments/assets/fee33223-bdb7-4e10-94f0-262e3c548701)

### 系统版本 / OS Version

Android 14

### 应用版本 / App Version

v3.2.19-0-ge46046ab-release

### 构建信息 / Build Information

构建者：Release CI
Git 仓库：https://github.com/osfans/trime
构建 Git 哈希：e46046abfb030a2687033f74ad00d1b2693af433
构建时间：2024年7月1日 18:27:14

**Comment by WhiredPlanck** [comment]
请先尝试最新每夜版。
