### ISSUE TITLE
疑问求解：如何实现“光标右移一词”效果？

### ISSUE THREAD

**Issue by ghost** [osfans/trime#147]
我在定制过程中想要实现“光标右移一词”按键，想到大多数操作系统下都可以通过发送 `Ctrl+Right` 来达成这一效果，于是在 trime.custom.yaml 的 patch 中加了这么一行：

``"preset_keys/next_word": {label: '↣', functional: false, send: Control+Right} ``

（完全仿照 `select_all: {label: 全选, functional: false, send: Control+a}`）

并且在键盘适当的位置调用了 `next_word`，然而结果仍然是普通的右移一个字符，和单独按 `Right` 一样。

问题究竟出在哪里呢？如何才能实现想要的效果？

**Comment by ghost** [comment]
有理由相信安卓是支持 `Control+Right` 右移一个单词的，在 [Hacker's Keyboard](https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard) 这款键盘下键入 `Control+Right` （可能要横屏方可显示包括 Ctrl 在内的全部按键）可以达到我想要的结果。

**Comment by osfans** [comment]
可能要找下代碼，看看他們是怎麼實現的。

**Comment by Jim-Young** [comment]
支持这个功能。 谢谢 osfans

**Comment by osfans** [comment]
db51335135a817c9f348e79a7e98b593f9a82e3b 解決了這個問題
