### ISSUE TITLE
Regression: 同文风主题下，按下 ⌘ 后，中文状态中若干标点无法正常输入

### ISSUE THREAD

**Issue by Iey4iej3** [osfans/trime#1470]
### 摘要 / Summary

这是 regression。在同文风主题下，按下 ⌘ 后，中文状态中若干标点（例如句号、问号、感叹号、书名号、顿号等等）无法正常输入。

### 重现步骤 / Steps to Reproduce

1. 切换至同文风主题，朙月拼音输入法；
2. 按下 ⌘；
3. （中文输入的情况下）点击第一行 `，。？！：、……；` 的任意一个标点符号，或者第三行的 `“” ‘’ （）` 等等标点符号组合；

### 预期行为 / Expected Behavior

输入被点击的标点符号

### 附加信息 / Additional Context

这是 regression：在 3.2.19 中不存在这个问题。

临时解决方案：在按下 ⌘ 后，切换至英文：此时能正常输入上述标点符号（并且是中文的全角样式）。

### 系统版本 / OS Version

Android 14

### 应用版本 / App Version

v3.3.0-0-g436c8fc4-release

### 构建信息 / Build Information

构建者：F-Droid
Git 仓库：https://github.com/osfans/trime
构建 Git 哈希：436c8fc42af638fdd8744533beec03567ec03c6c
构建时间：2024年9月8日 12:18:51

**Comment by linzianabc** [comment]
我这里是可以的，没有问题。不过，同文风有几个符号不能输入，需要自己设置下。

**Comment by Iey4iej3** [comment]
不清楚是否和配置有关。我是用 https://github.com/Bambooin/rimerc 刚才测试仅用此配置，仍然有这个问题。另外澄清：问题中我说的“中文状态”是指 `ascii_mode` 的值。

**Comment by Wenti-D** [comment]
看看是不是和 #1454 问题一样？

**Comment by Iey4iej3** [comment]
似乎是的，先关闭该 issue。
