### ISSUE TITLE
外接键盘时自动切换主题

### ISSUE THREAD

**Issue by UlyssesZh** [osfans/trime#1473]
### 摘要 / Summary

#1058 描述的 bug 现在仍然存在: 在不显示软键盘时, 悬浮窗是不会显示的. 目前的解决方案如 #1255 所讨论的, 需要创建一个专门给外接键盘使用的主题. 如果切换主题可以在插拔键盘时自动完成, 这将非常方便, 而且完全解决这个问题.

### 附加信息 / Additional Context

因为现在已经有了在有外接键盘时自动切换为迷你键盘的功能, 说明技术上根据外接键盘切换主题的功能应该也是可行的.

### 系统版本 / OS Version

Android 11

### 应用版本 / App Version

3.3.0

### 构建信息 / Build Information

Builder: F-Droid
Git Repo: https://github.com/osfans/trime
Build Git Hash: 436c8fc42af638fdd8744533beec03567ec03c6c
Build Time: Sep 8, 2024 03:18:51

**Comment by hankoi07** [comment]
你的手机可能设置（com.android.settings）选项被阉割过  
需要找到实体键盘设置（Settings$PhysicalKeyboard）并启用「使用屏幕键盘」
<details><summary>显示图片</summary>
<img width=35% src="https://github.com/user-attachments/assets/5dff9d74-c859-4b2d-9e0b-b841328f6e8d" />
</details> 

这个入口位于 `com.android.settings/.Settings$PhysicalKeyboardActivity`  
我试图使用 `adb am start 'com.android.settings/.Settings$PhysicalKeyboardActivity'` 启动它时得到的是手机厂商魔改过的设置界面  
最终通过 [Activity Launcher](https://f-droid.org/packages/de.szalkowski.activitylauncher/) 成功打开了实体键盘设置界面，就是上面那图。  

安装了Gboard的话有更用户友好的操作方法  
1. 先连上实体键盘
2. Gboard设置会出现实体键盘选项  
  <details><summary>显示图片</summary>
  <img width=35% src="https://github.com/user-attachments/assets/9ef7b6c1-7237-4f3a-9bab-15b33ab91f70" />
  </details> 
3. 点击  
  <details><summary>显示图片</summary>
  <img width=35% src="https://github.com/user-attachments/assets/c692b9be-cc17-4814-bfb9-a2c6dda06b8b" />
  </details> 

Also see: https://github.com/osfans/trime/issues/1058#issuecomment-1673459064

**Comment by UlyssesZh** [comment]
@NWater23 你对我的需求有误解. 现在的问题就是, 预期行为是在关闭 "使用屏幕键盘" 的情况下也能有悬浮窗, 但实际行为是我必须要打开 "使用屏幕键盘" 才行.

另外, 这则 issue 是关于自动切换主题的需求的, 跟悬浮窗是否显示的问题没有关系. 请不要偏题.

**Comment by WhiredPlanck** [comment]
这是一个技术特性，我们当前绘制键盘和悬浮窗的视图，会在“使用屏幕键盘”关闭时被隐藏。实际技术上的解决办法是改变悬浮窗视图的绘制方式，让它不要画在被隐藏的视图上，我本地已经在实验了，但有一些难点还没有解决，估计需要的时间比较长。

插入键盘时切换主题也许也是个不错的解决方法，不过这个也有一些难点，考虑到同文凌乱的主题系统设计，这可能会给日后开发维护带来一些挑战。

**Comment by WhiredPlanck** [comment]
@UlyssesZh 另外 app 中“主题与配色”中有“连接实体键盘时，使用迷你键盘”的选项，不知你是否打开，可以试一试起不起作用

**Comment by UlyssesZh** [comment]
连接键盘时自动使用迷你键盘是可以用的, 但是我还是希望能切换主题.
