### ISSUE TITLE
默认主题在简体环境下， 菜单，主题，剪切这些字都是繁体

### ISSUE THREAD

**Issue by bdfish** [osfans/trime#148]
1-换主题需要20秒，不知道我是不是特例
2-可否提供暗色主题，目前只有默认主题的配色可以选择暗色
3-默认主题在简体环境下，  菜单，主题，剪切这些字都是繁体

其实都是小问题，但是如果能够完善一下就更好了

系统是lineageos 7.1.2

**Comment by xiaoqun2016** [comment]
1，20秒有点不正常，可以适当精简主题。  
2，把暗色的color schemes复制到你需要的主题中。  
3，需要修改键盘标签。

**Comment by bdfish** [comment]
对于问题1--我没表达清楚,准确说应该是在默认主题之间切换需要20秒,我没有对配置文件做任何修改。

**Comment by iuen** [comment]
trime.yaml詳解里的第一个主题，能不能放出配置文件

**Comment by Bambooin** [comment]
1: 切换主题也就 2s左右
2: 暗色配色，我用的是 孤寺 配色
3: 最新版的同文风主题，已经是简体
