### ISSUE TITLE
连接实体键盘时，所有的功能键失效（夜版，内附定位commit号）

### ISSUE THREAD

**Issue by cabins** [osfans/trime#1485]
### 摘要 / Summary

当连接实体键盘的时候，所有的功能键均失效，是所有的。例如：
- Ctrl-A不能全选
- 空格键不能键入空格
- backspace键不能删除
- 方向键不能移动光标
- ……

看了下commit过程，找了两个commit对比测试了一下发现：
![image](https://github.com/user-attachments/assets/831af40e-e466-447e-a3b4-c582e01d7ef9)

能够肯定的是0f63fde这个commit的功能还是正常的；而b7eee6f这个commit打出来的包已经不正常了。

![image](https://github.com/user-attachments/assets/9bfb9152-987e-4265-a47d-e891669673ea)

麻烦大佬们排查一下。 @WhiredPlanck 

### 重现步骤 / Steps to Reproduce

使用同样的配置文件，不同的打包apk来测试。

### 预期行为 / Expected Behavior

功能键应该生效，现在空格，方向键，删除键都不能使用了。

### 系统版本 / OS Version

14

### 应用版本 / App Version

夜版

### 构建信息 / Build Information

-

**Comment by WhiredPlanck** [comment]
我已经发现了，正在修。

很快我要出差，这个修复可能要 11 月才能出来。
