### ISSUE TITLE
英文预测和中文手写.

### ISSUE THREAD

**Issue by raymondbackup** [osfans/trime#149]
请问要如何才有英文预测(English Prediction) 和中文手写了?

**Comment by osfans** [comment]
這個暫時沒有。手寫應該要第三方的lib。

**Comment by JackChen007** [comment]
也没有英文预测吗？

**Comment by Bambooin** [comment]
手写可以参考 #495 

英文预测 https://github.com/Bambooin/rimerc 里面的  easy_en
