### ISSUE TITLE
选择忘记自造词只会删除第一个自造词

### ISSUE THREAD

**Issue by Ennuyeux233** [osfans/trime#1491]
### 摘要 / Summary

选择忘记自造词只会删除第一个自造词

### 重现步骤 / Steps to Reproduce

首先学习一系列自造词，然后删除不在第一个的自造词

https://github.com/user-attachments/assets/ab40cdcd-353e-4420-92d3-fff1edf18022

### 预期行为 / Expected Behavior

删除的自造词应该是我们选择的自造词

### 系统版本 / OS Version

MIUI14

### 应用版本 / App Version

nightly-0-gefe0d773-release

### 构建信息 / Build Information

构建者：Nightly CI
Git 仓库：https://github.com/osfans/trime
构建 Git 哈希：efe0d7730c9d352a5f593f8abe55c9e71d8a538c
构建时间：2024年10月14日 00:06:13

**Comment by WhiredPlanck** [comment]
已确认为 librime 上游 API 故障，[修复](https://github.com/rime/librime/pull/945)已经合并，请等待同文更新。
