### ISSUE TITLE
剪贴板一段时间不用再打开就会崩溃

### ISSUE THREAD

**Issue by Ennuyeux233** [osfans/trime#1496]
### 摘要 / Summary

剪贴板有一段时间不是用再打开就会导致程序崩溃

https://github.com/user-attachments/assets/ce0bcaf9-9b51-435f-a41d-e5c067c24ff1

[com.osfans.trime-2024-10-19T03_31_15Z.txt](https://github.com/user-attachments/files/17442538/com.osfans.trime-2024-10-19T03_31_15Z.txt)

### 重现步骤 / Steps to Reproduce

一段时间不是用剪贴板，可能两个小时起步，然后再打开剪贴板

### 预期行为 / Expected Behavior

程序不会崩溃，可以正常打开剪贴板

### 日志 / Log

[com.osfans.trime-2024-10-19T03_31_15Z.txt](https://github.com/user-attachments/files/17442542/com.osfans.trime-2024-10-19T03_31_15Z.txt)

### 系统版本 / OS Version

MIUI14

### 应用版本 / App Version

nightly-1-g8440b0b3-release

### 构建信息 / Build Information

构建者：Nightly CI
Git 仓库：https://github.com/osfans/trime
构建 Git 哈希：8440b0b34a3b60739f54b2d3ee2f4edb81f24502
构建时间：2024年10月19日 00:06:36

**Comment by WhiredPlanck** [comment]
@Ennuyeux233 这是液态键盘的一个小 bug，修复已经合并（#1495） ，请等待今天 24 点过后的每夜版。
