### ISSUE TITLE
輸入提示配置沒有生效

### ISSUE THREAD

**Issue by bennyyip** [osfans/trime#150]
我使用https://github.com/rime/rime-jyutping/blob/master/jyutping.schema.yaml 作爲我的粵拼方案。該配置提供了輸入提示，但是在手機上沒有生效。  
具體見下面兩張圖，第一張是fcitx-rime裏的效果，第一張為trime。兩者都是使用同樣的配置。
![image](https://cloud.githubusercontent.com/assets/7467687/26814689/0e7e144e-4aba-11e7-9dac-b49116ff7c97.png)
![image](https://cloud.githubusercontent.com/assets/7467687/26814707/29aa2208-4aba-11e7-91a4-90993c4f2e7d.png)

**Comment by xiaoqun2016** [comment]
```yaml
show_comment: true  #显示提示区
```
