### ISSUE TITLE
希望能够支持外部键盘

### ISSUE THREAD

**Issue by Airthink** [osfans/trime#1501]
### 摘要 / Summary

平板上很多输入法都支持平板上的外部设备，但很多都做得不够好，例如很多候选栏都不跟随光标，我这边使用Gboard也有点时间了，希望trime也能有相应功能吧

### 系统版本 / OS Version

小米澎湃

### 应用版本 / App Version

V3.3.1

### 构建信息 / Build Information

没，我卸载了

**Comment by cabins** [comment]
Trime是支持的。不过我的平板上有一点点小BUG而已。但整体其实不影响使用。

**Comment by cabins** [comment]
![Screenshot_20241106_114429](https://github.com/user-attachments/assets/b88a666f-873c-40ca-83c3-380166d1a945)

补：在我这里是这样的

**Comment by atmouse-** [comment]
我还在用3.2.16版本，这个版本在物理键盘使用上也有点问题。

android系统第一次启动的时候，点到任何输入框开始输入的时候，第一次上屏一定会出现英文跟中文同时上屏的情况，只有当再次点击一次输入框，才不会出现同时上屏的问题，而且之后的任何输入框都不会出现该问题。

**Comment by cabins** [comment]
> 我还在用3.2.16版本，这个版本在物理键盘使用上也有点问题。
> 
> android系统第一次启动的时候，点到任何输入框开始输入的时候，第一次上屏一定会出现英文跟中文同时上屏的情况，只有当再次点击一次输入框，才不会出现同时上屏的问题，而且之后的任何输入框都不会出现该问题。

我这里也有你说的这个问题。但还好，不是非常影响我使用。

① 我这里还有另外一个问题，就是，默认的代码里面是无法正常的获取悬浮窗位置的（获取到的我的平板上x的值一直是负值，所以导致悬浮窗口一直在屏幕外面）。

我自己修改了代码来适配我的平板。但好像我修改的代码无法适配其他的平板，而且其他人好像也没有报出来类似的问题，所以也不是非常敢提issue和代码。

② 还有一个问题是，我这里只要光标聚焦在编辑框内，就会在底部弹出来候选栏，哪怕我配置里已经关掉了。切换一下方案就没有了。这个我也自己在代码里修复了。这个估计应该没有适配问题，回头有人报的话我再提交代码。

**Comment by FEI352** [comment]
> ![Screenshot_20241106_114429](https://private-user-images.githubusercontent.com/2500123/383887002-b88a666f-873c-40ca-83c3-380166d1a945.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3MTEwMjcsIm5iZiI6MTczNTcxMDcyNywicGF0aCI6Ii8yNTAwMTIzLzM4Mzg4NzAwMi1iODhhNjY2Zi04NzNjLTQwY2EtODNjMy0zODAxNjZkMWE5NDUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDFUMDU1MjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2JmZjJlOGU5OTc5MmIzMzlmYjQ1NWI1NmU5YzAwY2IyZmM1MTE2MzUwN2ViYzlmYmVkMGIzNzMxYWE0MzQzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5yhc3Svx3Bdm3B594bZcgqZtuxemb6Fo6m87E2SXJlk)
> 
> 补：在我这里是这样的

好看，怎么做到的，求大佬给一份配置文件
