### ISSUE TITLE
数字键盘、英文键盘、空格输出错乱

### ISSUE THREAD

**Issue by Ennuyeux233** [osfans/trime#1510]
### 摘要 / Summary

使用英文键盘和数字键盘与设定的输出结果不一致

https://github.com/user-attachments/assets/75cd72f8-a812-4fdd-a30e-058ef32fe090

### 重现步骤 / Steps to Reproduce

使用最新的同文输入法使用数字键盘和英文键盘

### 预期行为 / Expected Behavior

与设定的输出结果相符

### 系统版本 / OS Version

MIUI14

### 应用版本 / App Version

nightly-1-ga940ff34-release

### 构建信息 / Build Information

构建者：Nightly CI
Git 仓库：https://github.com/osfans/trime
构建 Git 哈希：a940ff3408aee6e483b2201dfd75c35a8cf7c911
构建时间：2024年11月12日 04:11:10

**Comment by WhiredPlanck** [comment]
这两天在摸索怎么搞清楚按键事件处理，先回退版本吧
