### ISSUE TITLE
Cannot type `{`, `}`, `(`, `)` in nightly

### ISSUE THREAD

**Issue by amalgame21** [osfans/trime#1516]
### 摘要 / Summary

Cannot type `{`, `}`, `(`, `)` in nightly

### 重现步骤 / Steps to Reproduce

1. Type `{`, `}`, `(`, `)`
2. Nothing happened

### 预期行为 / Expected Behavior

Type `{`, `}`, `(`, `)` successfully

### 系统版本 / OS Version

15

### 应用版本 / App Version

Nightly

### 构建信息 / Build Information

Builder: Nightly CI
Build Time: Nov 26, 2024 00:24:03

**Comment by WhiredPlanck** [comment]
You may need to change you key definition, the `text` filed may be `{}{Left}`，and you need to change them to `{{}}{Left}`.
