### ISSUE TITLE
Nightly版本使用实体键盘的时候，Enter键会输入一个空格或TAB之类的空白符，而不是回车

### ISSUE THREAD

**Issue by cabins** [osfans/trime#1518]
### 摘要 / Summary

① 这个现象在很多的程序里面都能复现，比如浏览器的地址栏，或者平板系统里面的一些搜索栏，甚至笔记软件
② 为了排除方案配置的影响，我测试的时候使用了空白的方案，即没有任何配置，也能复现这个问题
③ 我测试了Nightly，3.3.1，3.3.0这三个版本发现，3.3.0是正常的，从3.3.1开始就已经不正常了，具体的Commit未知

### 重现步骤 / Steps to Reproduce

如上面描述

### 预期行为 / Expected Behavior

预期是输入回车的表现，实际输入的是一个空格或者TAB之类的空白符号

### 系统版本 / OS Version

14

### 应用版本 / App Version

nightly-0-g9e1969b2-release

### 构建信息 / Build Information

构建者：Nightly CI
Git 仓库：https://github.com/osfans/trime
构建 Git 哈希：9e1969b2b67f4d05696b14a08728c7654b9aab80
构建时间：2024年11月28日 00:23:45

**Comment by cabins** [comment]
另外，我发现在实体键盘上主键盘区域上面的那一行数字键，如果按住Shift再去按数字键，输出的符号几乎都不对，只有@和*是对的，其他的都不行。

**Comment by cabins** [comment]
测试了其他的一些字符键，按住Shift的时候，输出也都不对（如[]:",./）等。这个好奇怪……

**Comment by cabins** [comment]
@WhiredPlanck 我测试了一下，的确能回车了。但是会敲〔一次〕回车，而输入〔两个〕换行。

**Comment by WhiredPlanck** [comment]
> @WhiredPlanck 我测试了一下，的确能回车了。但是会敲〔一次〕回车，而输入〔两个〕换行。

太怪了，我自己测的时候不会有两个换行呀
