### ISSUE TITLE
android trime用户词库的导入导出

### ISSUE THREAD

**Issue by llpub** [osfans/trime#152]
在linux下rime导入导出用户积累的词库有rime_dict_manager, 在android 的trime在下没找到, 请问如何实现这个功能?
Ps. 这里说的不是导入其它输入法的词库(那个用*.extended.dict.yaml已解决).
谢谢

**Comment by osfans** [comment]
目前有一個同步的功能。

**Comment by llpub** [comment]
打算把rime文件夹复制到电脑上, 用电脑的rime_dict_manager试试.

**Comment by osfans** [comment]
32位的嗎？可以給你編一個。

**Comment by osfans** [comment]
@llpub 32位的嗎？可以給你編一個。

**Comment by llpub** [comment]
arm64, 不过先不用了,这个优先级好像没那么高. 还是先解决重要的,如:'候选词数量能自适应吗' https://github.com/osfans/trime/issues/110 这类.
多谢
