### ISSUE TITLE
最近的nightly會變成只有最上一列的選項，沒有鍵盤

### ISSUE THREAD

**Issue by nijawang** [osfans/trime#1526]
### 摘要 / Summary

最近更新底下的幾個nightly更新後，輸入法都變成只剩下最上一列選項，沒有鍵盤。
![2024-12-07_10-48-52](https://github.com/user-attachments/assets/ce83ba6c-7e4b-46d8-9b1d-da15449da30d)

com.osfans.trime-nightly-0-gb35d43a4-arm64-v8a-release
com.osfans.trime-nightly-3-g9d05290e-arm64-v8a-release
com.osfans.trime-nightly-3-g41623f5d-arm64-v8a-release
com.osfans.trime-nightly-0-g41623f5d-arm64-v8a-release

### 重现步骤 / Steps to Reproduce

安裝完最近的nightly更新後，輸入法變成沒有鍵盤。

### 预期行为 / Expected Behavior

輸入法變成沒有鍵盤

### 系统版本 / OS Version

Android 9

### 应用版本 / App Version

nightly-3-g9d05290e-arm64-v8a-release

### 构建信息 / Build Information

nightly-3-g9d05290e-arm64-v8a-release

**Comment by WhiredPlanck** [comment]
请在你的主题里加入 `style/keyboard_height` 参数
