### ISSUE TITLE
Upgrade libiconv dependency

### ISSUE THREAD

**Issue by Bambooin** [osfans/trime#1532]
Build failed when I upgrade build tool due to obsolete libiconv code.
- cmake 3.31.1
- ndk 27.2.12479018

Proposal
- Remove libiconv module if we don't need it anymore
- Or repalce with https://git.savannah.gnu.org/git/libiconv.git

Usage of iconv: `grep -rl "iconv(" .`

I lack the knowledge to do this task, someone can help to do it.

The obsolete code is 7 seven years old and lack of maintenance.

https://github.com/osfans/libiconv-gnu.git

**Comment by WhiredPlanck** [comment]
libiconv is a backend of boost::locale, which is required by librime-charcode. It seems that  librime-charcode has been deprecated, maybe we can remove it too. Or our friend project fcitx5-android vendors a newer mirror: https://github.com/fcitx5-android/libiconv.
