### ISSUE TITLE
数字输入界面输入重复问题

### ISSUE THREAD

**Issue by yifan237** [osfans/trime#1541]
### 摘要 / Summary

在纯数字界面输入数字，按一次会重复出现两个相同数字，特别在输密码或验证码的时候，会直接导致输入错误，造成使用困扰，，已多次卸载并重新安装最新每夜版，并在不同机型上测试，均存在此问题，还望尽快修复，谢谢

### 重现步骤 / Steps to Reproduce

在纯数字界面输入数字，按一次会重复出现两个相同数字字符，特别在输密码或验证码的时候，会直接导致输入错误，造成使用困扰

### 预期行为 / Expected Behavior

恢复按一次数字显示一个字符

### 日志 / Log

[com.osfans.trime-2024-12-27T02_24_43Z.txt](https://github.com/user-attachments/files/18256745/com.osfans.trime-2024-12-27T02_24_43Z.txt)

### 截图 / Screenshot

![Screenshot_2024-12-27-10-25-49-27_3082c486780c76143534ea5d330090a3](https://github.com/user-attachments/assets/9bd03da8-6c9c-4ab6-a5ad-5bcfce295d3d)

### 系统版本 / OS Version

color os 15/magic os 9

### 应用版本 / App Version

nightly-0-g9807916a-release

### 构建信息 / Build Information

构建者：Nightly CI
Git 仓库：https://github.com/osfans/trime
构建 Git 哈希：9807916a521b00130f9495c122dfe453301f5213
构建时间：2024年12月27日 00:06:22__

**Comment by WhiredPlanck** [comment]
临时解决方法：把所有含 KP_1 等的键盘按键定义换成普通的 1

**Comment by yifan237** [comment]
> 临时解决方法：把所有含 KP_1 等的键盘按键定义换成普通的 1

请问要在哪里改?

**Comment by WhiredPlanck** [comment]
> > 临时解决方法：把所有含 KP_1 等的键盘按键定义换成普通的 1
> 
> 请问要在哪里改?

键盘定义在主题中

**Comment by WhiredPlanck** [comment]
与 #1524 重复，将关闭本 issue。
