### ISSUE TITLE
編譯環境

### ISSUE THREAD

**Issue by a5corpii** [osfans/trime#16]
README 裏面能不能列出編譯的環境，我也想加入。

**Comment by osfans** [comment]
我現在是用的archlinux和ant編譯的。估計像android studio之類的也行吧。
回頭我整理下。

**Comment by osfans** [comment]
安裝android sdk、android ndk、ant，然後`ant release`就好。
archlinux下的安裝編譯過程爲：

```
yaourt -S android-ndk android-sdk android-sdk-build-tools android-sdk-platform-tools android-platform apache-ant
ant release
```

**Comment by osfans** [comment]
試驗了下gradle也能用，`gradle release`也可以編譯。我自動編譯就用的gradle。
所以eclipse和android-studio應該都可以。
