### ISSUE TITLE
less、greater这些键要不要加到android_keys/name里面？

### ISSUE THREAD

**Issue by xiaoqun2016** [osfans/trime#163]
要配合Release+xxx，键盘中就必须使用英文键名。但目前`{click: less}`不会输出`<`，还有这些键：  
```
exclam	!
quotedbl	"
dollar	$
percent	%
ampersand	&
colon	:
greater	>
question	?
asciicircum	^
underscore	_
braceleft	[
bar	|
braceright	]
asciitilde	~
```

另外要不要把这些键的label默认设为对应的符号？

**Comment by osfans** [comment]
Android目前好像是通過Shift+下檔實現的，所以沒有鍵名。可能要搞個android_shift_keys或者rime_keys進行對應。

**Comment by xiaoqun2016** [comment]
试着直接把less添加到android_keys后面就能输出<，其它符号也行。我这样做是不是不够规范

**Comment by osfans** [comment]
加在大寫後面？那Release能用嗎？

**Comment by xiaoqun2016** [comment]
是的，加在最后面，Release能用。（如果加在中间，所有按键会错乱。）
