### ISSUE TITLE
关于添加较完善大词库和配置的提议

### ISSUE THREAD

**Issue by Bambooin** [osfans/trime#166]
词库问题一直是普通用户使用Rime系的痛点，可能很多小白用户会因此放弃。
所以我想在Trime里面添加很受欢迎的大词库。此词库来自贴吧的Rime的使用者。
链接为: http://tieba.baidu.com/p/4125987751?pn=3

但是有几点问题需要解决：

1. 词库较大，最大和基础的sgmain.dict有12MB，部署后大概有50MB的table.bin数据。
2. 有些用户的硬件不是很好的，初次部署可能要等大约5分钟，甚至导致应用崩溃。
3. 如果包含sgmain.dict的话，会导致apk文件大小骤增，不知是否可接受。
4. 可能需要贴吧作者的同意，来解决词库版权问题。

带来的好处：

- 小白用户可以直接安装部署，方便省事。
- 对于有些了解Rime的人可以自己灵活添加词库。
- 用户的体验会大大增加，输入更自然。
- 多平台体验统一。

自己的配置和体验：
本人Windows和Mac很早就使用此词库，一周前实在受不了Trime输入慢的问题了，
常用语要分几次一个一个的输入，而且有时还不准确。就想这是否可以把那个词库
也放在Android中，使用后发现输入变得很自然流畅了。于是萌生此想法。

下面为词库的列表以词库大小排序，自己使用的词库已标记，编译后大概64MB。

- [x] luna_pinyin.sgmain.dict.yaml 12M
- [x] luna_pinyin.sgplus2.dict.yaml 2.0M
- [ ] luna_pinyin.hanyu.dict.yaml 1.7M
- [ ] luna_pinyin.history.dict.yaml 1.1M
- [ ] luna_pinyin.shopping.dict.yaml 740K
- [ ] luna_pinyin.net.dict.yaml 728K
- [x] luna_pinyin.sgplus.dict.yaml 708K
- [ ] luna_pinyin.anime.dict.yaml 468K
- [x] luna_pinyin.poetry.dict.yaml 436K
- [ ] luna_pinyin.music.dict.yaml 272K
- [ ] luna_pinyin.movie.dict.yaml 200K
- [ ] luna_pinyin.user.dict.yaml 148K
- [x] luna_pinyin.computer.dict.yaml 144K
- [ ] luna_pinyin.game.dict.yaml 116K
- [x] luna_pinyin.chat.dict.yaml 104K
- [ ] luna_pinyin.english.dict.yaml 100K
- [ ] luna_pinyin.website.dict.yaml 88K
- [ ] luna_pinyin.emoji.dict.yaml 80K
- [ ] luna_pinyin.moba.dict.yaml 72K
- [ ] luna_pinyin.place.dict.yaml 40K
- [ ] luna_pinyin.cn_en.dict.yaml 32K
- [ ] luna_pinyin.kaomoji.dict.yaml 12K
- [ ] luna_pinyin.biaoqing.dict.yaml 8.0K
- [ ] luna_pinyin.extended.dict.yaml 4.0K
- [ ] luna_pinyin.extra_hanzi.dict.yaml 4.0K

**Comment by osfans** [comment]
通過在線下載的方式解決這個問題？

https://github.com/osfans/rime-tool
之前蒐集開源方案也是想做在線下載的。

**Comment by Bambooin** [comment]
是词库的问题，不是输入方案，主要对小白用户，Trime自带的词库输入很不方便。
各种输入方案，感兴趣的可能是对懂得Rime的人的特殊需求，一般用户仅仅会使用拼音输入方案。
有时输入两三个字的常用词条，可能要一个一个的输。如随便举例，（词库）可能要
分别输（词）候选项很多，要翻很多页，（库）还可以。本来只要输入（ck）两个
可能要用户点击5-6次，更不用说长一点的（我要吃饭了）。归根结底还是Trime自带词条数太少了。

**Comment by Bambooin** [comment]
我想给小白用户一个开箱即用的拼音输入方案的输入法，只要安装部署就能很自然的使用。

但是还是要看看大家的意见。

**Comment by osfans** [comment]
體積的話還好，主要還是版權問題。
平時我發的測試版，都是不帶方案的。

**Comment by xiaoqun2016** [comment]
打不出“词库”  “我要吃饭了”，那肯定是缺了八股文(essay.txt)。八股文是明月、地球、注音……这些方案的必备文件。请先体验完整版的输入方案，再决定要不要加入扩展词库。

**Comment by osfans** [comment]
所以我們可以完善下essay詞庫？

**Comment by xiaoqun2016** [comment]
我的意思是：明月、地球 这些方案原本就能打出“词库” “我要吃饭了” 这些常用词句

**Comment by xiaoqun2016** [comment]
如果因为误解而盲目扩展词库，这样不太好。  
而如果用了八股文，仍然觉得输入体验很糟糕，那可以考虑扩展词库

**Comment by Bambooin** [comment]
我肯定是添加了八股文(essay.txt)，不是说打不出来，而是需要用户输入很多，本来移动手机的屏幕就小，
输入长句要按很多很多按键。

还一个我只是随意举例的，“词库” 确实有，**但是可能要输入(ciku),而不是(ck)**，减少50%按键。
“我要吃饭了” 好像没有，用户要拆成“我-要-吃饭-了”四个部分。输入量肯定比(wycfl)多得多。

**Comment by Bambooin** [comment]
对于小白日常输入和使用，现在的词库可能还是匮乏些，而且大部分用户可能经常输入一些聊天类的东西。
luna_pinyin.chat.dict.yaml 104K，词库可能就满足了。

如果用户是程序员之类的，luna_pinyin.computer.dict.yaml 144K这个就不错。

用户的选择余地很多，高级用户还可以添加自己需要的词库，普通用户 luna_pinyin.sgmain.dict.yaml 12M
luna_pinyin.sgplus2.dict.yaml 2.0M 这两个就非常合适。

**Comment by JackChen007** [comment]
有几万的基本词库就够了。RIME会自己调节频率，如果是自己的高频词，下次第一个出现的就是，词库多了反而慢。

**Comment by Bambooin** [comment]
添加词库和配置文件参考，用户可以自行选择添加与否。 参考 #312
