### ISSUE TITLE
代码规范的工具格式化提议

### ISSUE THREAD

**Issue by Bambooin** [osfans/trime#168]
是否可以使用Android Studio工具，重新格式化所有的代码，以便更合理规范和易于阅读。

规范的代码缩进和操作符两边的空格等等，会使代码容易维护和开发。

由于改动较大，虽然仅仅是格式方面的，不知你的建议如何，还是保持现在的格式更好。

**Comment by osfans** [comment]
支持規範化，還有加註釋。
