### ISSUE TITLE
希望能加个“最小化按钮”

### ISSUE THREAD

**Issue by zaqzrh** [osfans/trime#17]
Trime的键盘是否有点“霸道”，阻挡了一半的手机屏幕。
希望能在状态栏加个“最小化的按钮”，打完字，不用时缩小键盘。
重复提案，贴吧79楼问题 http://tieba.baidu.com/p/3793431224?pn=3

**Comment by osfans** [comment]
這個跟自定義狀態欄一起做。
 其實現在可以放在鍵上實現的，代碼爲Prior。比如修改右上角的鍵：
`- {symbol: ')', code: 'Prior', label: '隱藏'}`

**Comment by osfans** [comment]
現在應該`- { click: 'Hide'}`就好。
不過還沒能放到狀態欄，需要解決 #26
