### ISSUE TITLE
地球拼音输出拼音

### ISSUE THREAD

**Issue by JackChen007** [osfans/trime#172]
灾书写的时候，地球拼音能否将拼音直接输出出来，不打汉字，只有拼音。

电脑上的地球拼音可以打出来。

**Comment by osfans** [comment]
默認是長按Enter，也就是Control+Enter。

**Comment by JackChen007** [comment]
可以了，谢谢。但是，后选项只有一个匹配的时候，无法输出拼音。
比如，把“汉语”两字的拼音 “hàn yǔ”用全拼完全打出来时，可以到键盘上方，但是，长按Enter无效。

**Comment by osfans** [comment]
這不知是不是rime的bug。

**Comment by JackChen007** [comment]
感觉是，实现的功能和Win7上的小狼毫不同。小狼毫是：打的哪个码，出来哪个码。Trime是 输出第一个候选词的码。

**Comment by osfans** [comment]
那直接Enter就可以出碼了吧？

**Comment by JackChen007** [comment]
可以出来，就是和小狼毫的功能不同。如果是单纯想输入拼音的码的话，还是小狼毫方便些。

**Comment by osfans** [comment]
應該要一樣的。小狼毫不是Enter和Control+Enter兩種嗎？

**Comment by osfans** [comment]
原來默認的是：
  CommitComment: {label: 編碼, send: Control+Shift+Return}
可以改成這種：
  CommitRawInput: {label: 編碼, send: Control+Return}

**Comment by osfans** [comment]
rime快捷鍵問題，關閉。
