### ISSUE TITLE
AS打开项目, 一直停留在building symbols, 等待很久之后导致AS卡死

### ISSUE THREAD

**Issue by minwei0829** [osfans/trime#173]
在网上搜了一堆内容, 都解决不了. 不知道大家有没有遇到我这个问题, 还请大家帮帮忙.

**Comment by osfans** [comment]
是比較慢，ndk的問題吧。

**Comment by minwei0829** [comment]
@osfans 目前是下载的最新的NDK, 很奇怪, 有什么好的解决办法吗

**Comment by minwei0829** [comment]
@osfans 是不是building symbols时需要下载一些资源, 而内地网络需要翻墙才能下载到

**Comment by osfans** [comment]
我是用命令行的，沒有遇到這種問題。@Bambooin 有遇到，不知有沒有解決。

**Comment by minwei0829** [comment]
@osfans 用命令行可以编译, 但是不引入AS, 开发起来很困难

**Comment by Bambooin** [comment]
@osfans 确实遇到过，问题的根结是JNI文件夹里面的文件太多太大，尤其boost
所以AS需要对这些文件索引，但是由于太大，最后只有卡死或崩溃。

解决办法：
首先使用在.gitignore里面添加app/src/main/jni/以忽略下面的文件，在解决问题后在删除该行。
AS->File->Invalidate Cache Restart,清除缓存。、
注意再次打开AS，在AS->把文件视图切换成Project Files，并把jni文件夹Exclude掉。

注意这个步骤一定要及时，有时还会失败。需要多试几次。

**Comment by Bambooin** [comment]
@osfans 是否可以把jni文件夹里面的东西去掉，尤其是boost。
只要使用软件包安装了boost，是否还必须使用boost？

其实java文件就那几个，索引基本半分钟就解决了，但是jni下面索引不了。

**Comment by osfans** [comment]
可以單獨裝Boost嗎？

**Comment by Bambooin** [comment]
使用了各个平台的软件包安装boost，我想应该可以去掉boost。

**Comment by osfans** [comment]
那還用以前的方法，用系統的boost頭文件？

**Comment by Bambooin** [comment]
去掉boost可能破坏兼容性，C++的东西不是很熟悉，如果兼容性可以的话，还是可以考虑去掉。

 @osfans  还有一个办法， 以前的jni是在主目录下的，不是放在app/src/main目录下面的。
那时候AS好像不会索引jni下面的文件（那时AS没有出现该问题），是否把jni目录
放在一个合理的目录，不要放在app/src/main，比如放在lib目录里面什么的。

**Comment by minwei0829** [comment]
@Bambooin 我试试看

**Comment by Bambooin** [comment]
主要是清除cache， 并把jni目录去掉AS索引的范围。可能要多试几次。

**Comment by minwei0829** [comment]
@Bambooin 试过好多次, 没成功, 有其他办法吗

**Comment by minwei0829** [comment]
@osfans 你好, 请问有没有编辑好的.so静态库文件, 可以直接引用并用于开发的

**Comment by osfans** [comment]
@minwei0829 有的，apk解壓就好。

**Comment by Bambooin** [comment]
@minwei0829 好像没别的办法了。

主要在gitignore 添加app/src/main/jni/
在清除缓存后再次打开项目后，**迅速**得把app/src/main/jni/文件夹设置为Excluded
可参考https://stackoverflow.com/a/6535511
或搜索intellij exclude folder from indexing

**Comment by minwei0829** [comment]
@Bambooin 好, 我再试试, 想请教一下, develop分支和master分支 有什么区别

**Comment by osfans** [comment]
我是想發佈之後就合併到master分支。所以develop是開發版，master是穩定版。

**Comment by lenchan139** [comment]
試了用command compile結果有下面的error，是我裝少了什麼嗎？

`  /Users/len/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/cstdio:137:9: error: no member named 'fgetpos' in the global namespace
  using ::fgetpos;
        ~~^
  /Users/len/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/cstdio:139:9: error: no member named 'fsetpos' in the global namespace
  using ::fsetpos;
        ~~^
  2 errors generated.
  ninja: build stopped: subcommand failed.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 22s
14 actionable tasks: 14 executed
Lens-MBP:trime len$ ./gradlew debug
`

**Comment by osfans** [comment]
@lenchan139 
最新的ndk不能用了，被拋棄了，目前只能用ndk14。

**Comment by osfans** [comment]
@minwei0829 @Bambooin   我只留了用的幾個boost libs，building symbols就很快了。
當然這樣include會不全，所以要先生成include文件夾。

```
 8a0ab2fdd96955edba592bab9c676266cbc856c4 libs/filesystem (filesystem-2014-07-23-224-g8a0ab2f)
 1f07ffa1521284c823cb60e37514f410adfa48eb libs/locale (boost-1.65.0)
 8191d582667c417334d65853e851be4ea3f8014f libs/regex (boost-1.64.0)
 613b2a55b602501bf6dfe3da8fb2218e1ffc2862 libs/signals (boost-1.63.0)
 3eb4d1eaf821d457e9019ca8f82eb181baf83797 libs/signals2 (boost-1.65.0)
 b97772973b8e46c0899092de1c1afac2feb56501 libs/system (system-2014-07-17-63-gb977729)
```

**Comment by osfans** [comment]
把.idea、app/app.iml等刪掉，升級到AS3.0，
[修改VM參數後](https://stackoverflow.com/questions/39640433/android-studio-2-x-building-symbols-forever)，終於可以很快的updating symbols了。不需要再刪除boost libs了。
