### ISSUE TITLE
卸载重装报错, /sdcard/rime/trime.yaml无法解析

### ISSUE THREAD

**Issue by minwei0829** [osfans/trime#175]
I/native: I/config.cc:692 loading config file '/sdcard/rime/trime.yaml'.
E/native: E/config.cc:698 Error parsing YAML: bad file

**Comment by osfans** [comment]
自己編譯成功了？
那可能有問題。jni那邊寫死的。跟java那邊動態獲取的路徑不同了。

**Comment by osfans** [comment]
應該已經解決
