### ISSUE TITLE
新clone下来的develop分支, 编译打包成功之后无法输入中文.

### ISSUE THREAD

**Issue by minwei0829** [osfans/trime#177]
提示: sdcard/rime 目录中没有essay.txt, default.yaml, symbols.yaml这三个文件

**Comment by minwei0829** [comment]
@osfans @boboIqiqi 之前还是可以用的, 请问我这个是什么原因

**Comment by osfans** [comment]
是放在了/sdcard/rime目錄。adb shell進去看看。
可以自己進設置-輸入中設定用戶文件夾。

**Comment by minwei0829** [comment]
设置中的目录就是/sdcard/rime. 这三个文件是不是打包进了.so静态库文件, 初始化的时候再取出来? 

**Comment by osfans** [comment]
不是，是在assets/rime裏面。直接解壓的。
