### ISSUE TITLE
设置中的showswitch选项无法设置，候选栏没有切换按钮

### ISSUE THREAD

**Issue by Bambooin** [osfans/trime#178]
看了最近似乎没有修改相关的代码，很有可能自己升级librime到最新版导致的。
不知道是不是这个原因。不管设置中是否开启都显示不了切换中英文的按钮。

librime最近似乎改了config的东西。

**Comment by osfans** [comment]
是的，我有提bug。
https://github.com/rime/librime/issues/140

**Comment by osfans** [comment]
更新了librime，可以了。
