### ISSUE TITLE
没有删除“用户词”的功能

### ISSUE THREAD

**Issue by zaqzrh** [osfans/trime#18]
例如：小狼毫默认编码编辑组合键(拼音)：Shift或Ctrl+BackSpace,回退一个音节，Shift+Delete删除用户词，Shift+←光标左移一个音节，Shift+→光标右移一个音节，Shift+↑上一个候选词，Shift+↓下一个候选词，Shift+Home光标第一个编码，Shift+Eng光标右移一个编码等等。

**Comment by osfans** [comment]
已完成
