### ISSUE TITLE
繁簡切換與拼音容錯

### ISSUE THREAD

**Issue by delphinuz** [osfans/trime#180]
版本  v3.0.1-195-g869cd81-20170908

因爲谷歌拼音與注音繁簡都無法線上切換，而一直在找可直接切換的輸入法。

trime在鍵盤上狀態的可顯示繁簡切換，但限制於文字輸入前。常常打完字，發現對方是要用簡體，無法直接切換成簡體(這點谷歌注音可以)，需要先刪除所有的輸入，切換，再重新輸入。如果有一鍵可以隨時切換是最方便的。

另外全拼打字的容錯不太好，谷歌這部分做的還不錯，可參考。

**Comment by osfans** [comment]
繁簡可以直接切換的，需要仿照這個自己加按鍵：
https://github.com/osfans/trime/blob/develop/app/src/main/assets/rime/trime.yaml#L791
```yaml
 Mode_switch: {toggle: ascii_mode, send: Mode_switch, states: [ 中文, 西文 ]}
```

**Comment by delphinuz** [comment]
繁簡可以直接切換的本來就有，但一進入輸入模式，狀態列上的繁簡切換就沒了。
希望是在按鍵上，或是固定在狀態列上不會被隱藏，可隨時按一下直接轉換狀態列上的候選字。
![3](https://user-images.githubusercontent.com/615043/30467925-97830dc6-9a1a-11e7-9abe-aeda2ee32839.jpg)

**Comment by delphinuz** [comment]
好了。原本"中"對應到space_R2，所以按了沒反應。改為 Henkan 即可繁簡切換。

另外有個怪問題，每次候選字都有個 "a" 不知怎麼解決。

![5](https://user-images.githubusercontent.com/615043/30473044-72d2437c-9a31-11e7-9815-74a459c9349c.jpg)

**Comment by osfans** [comment]
原来我加了Henkan啊。
那个要删除bin 再重新部署。

**Comment by delphinuz** [comment]
>那个要删除bin 再重新部署。
是指 a 嗎？刪除.bin後就沒了。

這圖是我目前比較想要的結果，已輸入的候選字可以直接繁簡轉換，而不用在轉換後重新輸入一次。

![43434](https://user-images.githubusercontent.com/615043/30487572-6516cf0c-9a66-11e7-815d-8fd3306e886c.jpg)

最後一行鍵盤相關的碼：

  - {click: Keyboard_number, long_click: Keyboard_bqrw, width: 12.5, key_back_color: bgn, key_text_color: tgn}
      - {click: Henkan, long_click: Keyboard_kao, key_text_size: "18", key_back_color: benter, key_text_color: tenter}
      - {click: '.', label: '。', long_click: '<>{Left}', key_back_color: bh4, key_text_color: th4}
      - {click: space, long_click: Mode_switch, swipe_left: "Left", swipe_right: "Right", width: 42.5, key_back_color: bkg, key_text_color: tkg}
      - {click: ',', label: '，', long_click: '/', key_back_color: bh4, key_text_color: th4}
      - {click: Return, long_click: Menu, swipe_up: Escape, width: 15, key_back_color: benter, key_text_color: tenter}
