### ISSUE TITLE
BlackBerry 物理键盘中文状态alt   shift键锁定行为不正确

### ISSUE THREAD

**Issue by yueduz** [osfans/trime#183]
英文状态下表现的行为是正确的

**Comment by osfans** [comment]
確實，聽說文本框的光標有三種狀態。

**Comment by yueduz** [comment]
@osfans 同文英文模式下在正常的，中文就不正常。同文的英文状态能单手操作

**Comment by osfans** [comment]
嗯，英文是完全交給系統處理的。

**Comment by yueduz** [comment]
中文状态按一次alt再输入一个符号后alt任然是锁定状态，不能自动解锁。虽然是锁定状态，但是却不能输入符号，但是能一个backspace就删除一段话。

osfans <notifications@github.com> 于 2017年11月28日周二 11:45写道：

**Comment by yueduz** [comment]
@osfans 能不是把这个功能先取消了，之前不能锁定还好用些，现在锁定不正常更麻烦，好不容易打了一段话，一个backspace就删完了。

**Comment by Bambooin** [comment]
黑莓实体键盘已经过时
