### ISSUE TITLE
默認注音佈局西文輸入狀態下無大寫字母選項

### ISSUE THREAD

**Issue by nusushika** [osfans/trime#184]
![screenshot_20171002-220133](https://user-images.githubusercontent.com/10937027/31177614-2755ee2c-a949-11e7-8064-bd3f54953126.png)
如題。我想要在鍵盤中添加一個 shift 按鈕，不知從何入手。
我放了一個大寫小寫的按鈕在上方也沒用。Shift 也只能作為中英文的切換鍵。

**Comment by DaengGWokFook** [comment]
我的右起註音鍵盤，shift鍵在左下角。
![screenshot_20171004-152740](https://user-images.githubusercontent.com/18633778/31195685-139594ee-a919-11e7-848d-9b8664465316.png)

**Comment by nusushika** [comment]
@DaengGWokFook 好的。我試著把這一個 Hide 改成了 Shift_L 就可以用大寫字母了，謝謝。不過真的好尷尬啊。

一開始我是用字母 a 的 swipe_down 來定義 Shift_L，結果卻變成切換中英文的功能。

不過現在解決了，心裡也蠻開心的。
![screenshot_20171005-112954](https://user-images.githubusercontent.com/10937027/31209977-4bdec0de-a9c1-11e7-9ae5-467664fa4a43.png)
