### ISSUE TITLE
黑莓keyone无法识别sym键

### ISSUE THREAD

**Issue by jqm800** [osfans/trime#185]
目前sym键作废，很不方便，可否解决下？谢谢！

**Comment by yueduz** [comment]
sym键应该在按下弹起后才打开符号例表,而不是按下就打开


![screenshot_20171028-133000](https://user-images.githubusercontent.com/1448159/32131614-3df34d0a-bb78-11e7-97d9-f96a07612c1e.png)

**Comment by jqm800** [comment]
这个符号列表没什么用，我想说的是在输入法中设置sym键的功能，但是试了各种sym键可能的名称，输入法始终没法识别按下这个键的动作。

**Comment by xpmarksman** [comment]
现阶段用讯飞内测版就好

**Comment by jqm800** [comment]
讯飞内测版不能使用选择复制粘贴这些快捷键，感觉没法发挥全键盘的优势

**Comment by osfans** [comment]
需要映射一下，暫時沒有實現。

**Comment by yueduz** [comment]
@jqm800 可以同时按下sym和字母输入其他符号。

**Comment by yueduz** [comment]
能把其中一个shift键映射到ctrl，把sym映射到tab键是极好的

**Comment by jqm800** [comment]
如何设置同时按下sym键和字母输入其它符号？

**Comment by yueduz** [comment]
@jqm800 不用设置。默认是什么符号就是什么，改不了。

**Comment by jqm800** [comment]
我的目标是按下sym键，选择第四个候选字，完全无法实现，所以我怀疑同文输入法无法识别按下sym键这个动作。

**Comment by Bambooin** [comment]
黑莓键盘已经过时
