### ISSUE TITLE
借宝地用下：我找的输入法代码遇到has stopped问题，问下怎么解决？

### ISSUE THREAD

**Issue by ryysoft** [osfans/trime#186]
贵方的apk能提供个下载链接吗？我用AS编译很难，很费时间，不想花太多时间，只是想对has stopped问题，进行对比下，看贵方的APK安装后，输入视图和界面能出来不？
初学输入法开发，请多指教。

**Comment by ryysoft** [comment]
我QQ396806883

**Comment by osfans** [comment]
命令行編譯比較快，或者參考 #173 。
有問題也可以去同文堂QQ羣討論。
