### ISSUE TITLE
请求如 windows 那样 ， 有 【五笔・拼音】方案

### ISSUE THREAD

**Issue by smith09** [osfans/trime#187]
#这个方案很方便，尤其在不需要开电脑，手机otg线连键盘，打字又快又方便。

**Comment by osfans** [comment]
可以有，但是目前需要自己放進去，https://github.com/rime/rime-wubi

**Comment by GoGoogle** [comment]
> 可以有，但是目前需要自己放進去，https://github.com/rime/rime-wubi

我放了，但测试发现没有拼音，只有五笔，并不是五笔拼音，怎么处理？

![Screenshot_20210321-144938_Chrome_1nopy](https://user-images.githubusercontent.com/9440508/111897474-08d89200-8a5b-11eb-873b-8d91cfd57b56.png)
