### ISSUE TITLE
trime似乎对vivo的支持不够好啊？

### ISSUE THREAD

**Issue by benojan** [osfans/trime#192]
我买了两次vivo，打开trime，点部署都是死程序

**Comment by xiaoqun2016** [comment]
- 看看权限里面，有没有允许同文读写手机存储卡？  
  - 方案有多大？会不会太复杂了超出手机能部署的极限了？

---

相关问题 https://github.com/osfans/trime/issues/136

**Comment by RightFS** [comment]
vivo似乎对trime支持不够好啊

**Comment by Bambooin** [comment]
试试最新的 apk https://github.com/osfans/trime/tree/gh-pages

另外配置文件可以参考 https://github.com/Bambooin/rimerc
