### ISSUE TITLE
无法在juicessh，connectbot之类的应用里用实体键盘里输入中文

### ISSUE THREAD

**Issue by aweall** [osfans/trime#194]
无法在juicessh，connectbot之类的应用里用实体键盘里输入中文，
底部没有出现输入栏，但可以正常输入英文。

虚拟键盘能够正常输入中英文。

尝试了下其他输入法，也有存在一样问题的如bing输入法。
但也有能正常输入的，如触宝输入法，讯飞输入法。

**Comment by qchenac** [comment]
搜狗也可以，我是在termux下用，貌似cli类的app中都有这个问题，但是原因不明。

**Comment by luhux** [comment]
单字输入(输入密码时用的状态) 
单词输入(平时输入用的状态)

trime 在外接物理键盘的情况下在终端使用单字输入，而且只能是西文输入

**Comment by qchenac** [comment]
原来如此，感谢解答了。但是为什么有些输入法却可以呢？（gboard,搜狗）还有小米的手机是可以在cli类软件中使用外接键盘用trime正常打中文的，就很奇怪
