### ISSUE TITLE
五笔单字 个别字乱码

### ISSUE THREAD

**Issue by LuzMasonj** [osfans/trime#195]
![screenshot_2017-11-15-08-57-02](https://user-images.githubusercontent.com/27768847/32813177-ce098dcc-c9e3-11e7-89ae-4cef516a8a53.png)
系统默认字体

**Comment by osfans** [comment]
這個是字體不全，而不是亂碼。

可以給系統安裝ext-b的字體，或者在trime.yaml中指定hanb_font
https://github.com/osfans/trime/blob/ec8689d65ead5932ca188af6e1c432b953368564/app/src/main/assets/rime/trime.yaml#L22

**Comment by jccode** [comment]
@osfans 能具体说下这个怎么安装吗？ 
字体下载链接有吗？搜了好久没搜到。然后怎么安装？用的是小米8，没有root。能给个相关的链接吗？ 非常感谢! 好多字打不出来，有豆腐块，好难受。

**Comment by osfans** [comment]
沒有root的話，可能無法解決系統字體無法顯示的問題。

同文無法顯示的話，可以在這裏下載擴展字體：http://fonts.jp/hanazono/
把其中的HanaMinB.ttf放到/sdcard/rime/fonts/hanb.ttf，然後重新部署就好了。
