### ISSUE TITLE
按键时弹出显示字符第二行显示不全

### ISSUE THREAD

**Issue by LuzMasonj** [osfans/trime#196]
按键时弹出显示字符第二行显示不全
如图 
![screenshot_20171115-215543](https://user-images.githubusercontent.com/27768847/32840146-c3c42cfa-ca51-11e7-8df7-c85f2ffb3ebb.png)
第一行直接不显示 第三行正常

**Comment by xiaoqun2016** [comment]
（安卓7.0 MIUI9 ）也有此问题

**Comment by LuzMasonj** [comment]
@xiaoqun2016 我是EMUI5.0

**Comment by LuzMasonj** [comment]
@osfans

**Comment by Bambooin** [comment]
过时的 issue
