### ISSUE TITLE
横屏模式下自动全屏

### ISSUE THREAD

**Issue by LuzMasonj** [osfans/trime#197]
横屏模式下自动全屏 占了整个屏幕 影响游戏 聊天
![screenshot_20171115-183744](https://user-images.githubusercontent.com/27768847/32840264-1cc2f624-ca52-11e7-91e7-09615ce23baa.png)
如图 百度输入法有开关
![screenshot_20171115-214156](https://user-images.githubusercontent.com/27768847/32840309-3cb43736-ca52-11e7-994e-01f90569608b.png)
不知道同文的要怎么弄

**Comment by LuzMasonj** [comment]
@osfans

**Comment by Bambooin** [comment]
最新版试试

**Comment by leehaoxindehao** [comment]
哪位大佬知道这个问题如何解决了吗？

**Comment by cabins** [comment]
这个问题在3.2.15还是存在。即便开关关掉，也还是会自动进入到全屏。
