### ISSUE TITLE
不能输入Shift+回车

### ISSUE THREAD

**Issue by yueduz** [osfans/trime#200]
我在键绑定中设置了Shift+回车上屏编码,但是无法上屏,他只发送回车.

**Comment by xiaoqun2016** [comment]
试了下Shift+回车，在keybinder里设置：  
```yaml
  - {accept: Shift+Return, send: Control+Shift+Return, when: always}
```
可以上屏comment。在软键盘，平板的外接键盘上都没问题。  
其它的CommitRawInput或者CommitScriptText，原理也是一样的。  

（若问题仍然存在，请提供详细信息以便分析）

**Comment by yueduz** [comment]
你是否回车就是上屏编码,你回车和Shift+回车是否效果一样

**Comment by xiaoqun2016** [comment]
回车是上屏首选还是编码，要看你是否使用了语句流。  
Shift+回车默认是上屏ScriptText，若你的方案没写preedit_format，也没有用语句流，那就跟直接回车没什么区别了。
