### ISSUE TITLE
7.1.2无法安装群里最新版本trime

### ISSUE THREAD

**Issue by yueduz** [osfans/trime#201]
但是我在travis中编译出的debug版本能安装.安装时提示解析包错误.

**Comment by xiaoqun2016** [comment]
解析软件包时出现问题，常见原因之一是你下载的apk损坏了（这个在群里已经发现多次）。请重新下载，或者先校验文件哈希值，确认无误再安装。  
File: trime-20171025-test.apk
MD5: 0c:9e:20:1d:83:1c:90:83:8b:8f:39:89:f1:11:21:fd
SHA1: ee:85:b3:26:e3:b7:90:b0:6f:4a:12:c2:e6:fc:b0:2a:06:80:39:c7

（若问题仍然存在，请提供详细信息以便分析）

**Comment by yueduz** [comment]
![2017-12-06 12-37-00](https://user-images.githubusercontent.com/1448159/33644826-40d223f6-da82-11e7-8389-f8616ce249b6.png)


![screenshot_20171206-123751](https://user-images.githubusercontent.com/1448159/33644890-c680bbca-da82-11e7-8fc3-4c945f6d4def.png)

没有更多提示,我找到一篇文章,是否和这有关系.http://blog.csdn.net/y505772146/article/details/55255344
