### ISSUE TITLE
按键音时有时无

### ISSUE THREAD

**Issue by xiaoqun2016** [osfans/trime#202]
按键音断断续续，时有时无。  
已打开同文按键音和系统铃声音量（搜狗与谷歌声音正常，应该没有在梦游😜）。  

在MIUI系统和ZUK手机上都能复现。已有多位用户反馈此问题。

**Comment by lflys** [comment]
我之前也遇到了这个问题，我的手机是vivo。
今天更新到最新版还是有这个问题，但是把之前的100%的按键音量调为99%就解决了。不知道是什么原因，估计是和系统自身的按键声冲突了吧。

**Comment by osfans** [comment]
100%就有問題？

**Comment by lflys** [comment]
对，我不知道为什么。我的手机是vivo x9plus。
刚刚又试了下，将按键音量调到100%就时断时续的，只要不是100%就没有问题。
和输入法是否设为按键震动无关。
而且，如果是在字母、回删和空格这三种键交替着按的话就总是会有声音。但只要是在其中一种键上按上两次及以上的次数就没声了。

**Comment by xiaoqun2016** [comment]
装20181219版发现已经修好了。感谢🙏

**Comment by osfans** [comment]
9fe97e6cb132a12b840ac69c26f43d8d8580a256 解決
