### ISSUE TITLE
undo/redo在QuickEdit里无效

### ISSUE THREAD

**Issue by xiaoqun2016** [osfans/trime#203]
`undo`/`redo`在其它文本框中都正常，唯独在QuickEdit中无效。  

试过Hacker's Keyboard的`Ctrl+z`和`Ctrl+y`，在QuickEdit里面有效。  
为什么同样是Ctrl+z/y，却有如此差别？  

在MIUI9 安卓7.0，魔趣 安卓6.0中都能复现。

**Comment by Bambooin** [comment]
过时的 issue
