### ISSUE TITLE
position设为left或right时，悬浮窗消失不见

### ISSUE THREAD

**Issue by xiaoqun2016** [osfans/trime#204]
设为`left`或`right`时，在QQ、微信、浏览器等文本框中输入时，都看不到悬浮窗。
（只遇到一个例外：QuickEdit把`left`和`right`都视为`fixed`，所以能显示，但悬浮窗都是固定在左下角，这也不是`left`或`right`该有的样子）

在MIUI与ZUK手机上能复现。已有多位用户反馈此问题。

**Comment by Bambooin** [comment]
过时的 issue
