### ISSUE TITLE
同步文件夹设到外卡无效

### ISSUE THREAD

**Issue by xiaoqun2016** [osfans/trime#205]
用的是MIUI9。  
其它APP在需要写入外卡时会提示用户授权，用户按提示操作过后即可正常写入。比如QuickEdit：  

![如图](https://user-images.githubusercontent.com/16501929/33644321-a2adc0d6-da09-11e7-9257-0bc7cfe45349.jpg)   

**同文没有申请这个授权，写入失败也没有提示**

**Comment by Bambooin** [comment]
可以试试最新的 apk。
