### ISSUE TITLE
Force Close on Deploy

### ISSUE THREAD

**Issue by juanchaopan** [osfans/trime#207]
有时,点击Deploy会秒退,没有找到规律,不知道是为什么
Nexus 5(emulator) API 22 x86_64 (修改过abiFilters)

停是停在这个地方:
app\src\main\jni\librime\src\rime\deployer.cc
void Deployer::JoinWorkThread() {
  if (work_.valid())
    work_.get(); //here, work_ is NULL
}

**Comment by juanchaopan** [comment]
作者有在x86或者x86_64 emulator上遇到过吗?

**Comment by osfans** [comment]
沒試過，有空試試。你有x86的機器？

**Comment by juanchaopan** [comment]
哈哈虚拟机

**Comment by Bambooin** [comment]
可以试试最新的 apk
