### ISSUE TITLE
想把默认键盘的Z行向左移半格

### ISSUE THREAD

**Issue by robinbz** [osfans/trime#212]
想把默认键盘的Z行向左移半格（参考百度手机输入法的1080P超级布局、ICS经典布局），求操作方法，或者以后能出个图形界面来改，谢谢大佬。如果是简单修改配置文件的话我还是可以，涉及修改APK包就有点牵强。

**Comment by robinbz** [comment]
对了，我用的是五笔，所以只有用导入方案。

**Comment by yueduz** [comment]
改主题就可以

**Comment by yueduz** [comment]
用不着改apk，

**Comment by zmx0142857** [comment]
打开配置文件 `/sdcard/rime/trime.custom.yaml` （没有则新建一个），输入：
```
# trime.custom.yaml
patch:
  preset_keyboards/qwerty/keys/@21/width: 10
  preset_keyboards/qwerty/keys/@29/width: 20
```
这样就把 `shift` 的宽度改成 10, `backspace` 的宽度改成 20 了。只是不对称的样子其实挺丑的...
