### ISSUE TITLE
Is it possible to use boost binaries instead of source code?

### ISSUE THREAD

**Issue by nlpguyz** [osfans/trime#214]
A developer complains: 第一次构建时候会占用android studio 大量虚拟机内存（studio64.option需要调大内存大小）不然会卡在build symbol这一步

**Comment by osfans** [comment]
我這邊更新到Android Studio 3.0之後好像好點了。
只是java開發的話，應該可以直接使用librime.so

**Comment by Bambooin** [comment]
AS 可以设置排除 boost 进行 build symbol，以前我是这么处理的
