### ISSUE TITLE
工程安装在手机上没有自带schemas方案，我如何自己导入方案？

### ISSUE THREAD

**Issue by summerzh** [osfans/trime#216]
该工程在as中编译安装在手机上后，没有自带的方案。我从rime中下载了几个方案放在手机外置的rime文件夹后，输入法查找不到。是我的操作方法有问题吗？
我把输入方案（比如我导入cangjie5.schema.yaml和cangjie5.dict.yaml）放在工程下的assets/rime中安装到手机后，输入法同样查找不到方案，请问，我该如何导入方案？万分感谢。

**Comment by osfans** [comment]
可以放到assets/rime下的，不過要在同文設置中回廠。

**Comment by summerzh** [comment]
谢谢你的回复。方案我已经搞明白了。不过我在使用Rime的jni时遇到了问题，我把rime打成so库，我再使用该so库时，调用Rime的jni方法都得不到结果，比如Rime.get_available_schema_list()返回为空。我还不清楚Rime类在使用之前要初始化什么？我已经调用了Rime.get();方法，请问我还需要做写什么操作吗？
