### ISSUE TITLE
無法輸入簡體，且切換繁簡也無效

### ISSUE THREAD

**Issue by Bambooin** [osfans/trime#217]
根據最新的git 33fdcd0編譯的，無法輸入簡體，不知是不是自己的配置有問題。

**Comment by sith-on-mars** [comment]
我也我也有這個問題

**Comment by Bambooin** [comment]
@stevenfang1997 
这个问题是我配置有误导致的，已经处理好了。

可以尝试以下方法，注意提前备份自己的设置。
1. 可能是opencc 的问题，需要输入->重置->勾选三个选项->部署
2. 可以使用整理好的小白配置 如：https://github.com/Bambooin/rimerc

**Comment by sith-on-mars** [comment]
从重置后部署就没问题了 谢谢
