### ISSUE TITLE
有道词典查词界面不能录入

### ISSUE THREAD

**Issue by maxwa** [osfans/trime#218]
有道词典（版本v7.6.x）在查词界面录入文字时，不能正确focus到录入框，按下键位后就失去焦点。

小鹤音形版本信息：
更新日志 v3. 0, 1-229-920f581 7-201 71 21 8 
RIME版本 rime-1. 2. 9-265-997cd661-arm64-v8a 
Opencc版本 ver. 1. 0. 5-47-933d57bd
小鹤音形 flypy. com v8. 3. 18. 0118

手机信息：
OS: Android
Ver: 5.1.1
Type: SM801

**Comment by Bambooin** [comment]
Daily build can be found for test and verify
https://github.com/osfans/trime/actions
