### ISSUE TITLE
可否提供一个“隐藏应用图标”的选项

### ISSUE THREAD

**Issue by itzXian** [osfans/trime#219]
放上隔壁 Google拼音输入法 的实例。
![Google拼音输入法截图](https://t1.picb.cc/uploads/2018/04/18/2rizdM.png "Google拼音输入法截图" )

**Comment by osfans** [comment]
之前也有試過，沒有成功。不知有沒有代碼示例。

**Comment by lilydjwg** [comment]
[XuiMod](https://github.com/zst123/XuiMod/blob/3c794ac576835ec53a9d365fcb5892c7677b22f9/src/com/zst/xposed/xuimod/SettingActivity.java#L188) 可以隐藏，不过它是 Xposed 模块，不知道可否参考。

**Comment by WhiredPlanck** [comment]
这个功能已在 #438 中添加了。尽请期待～
