### ISSUE TITLE
是否支持在键盘上滑动移动光标

### ISSUE THREAD

**Issue by synhi** [osfans/trime#220]
部分输入法支持在空格键上左右滑动控制光标在文中左右移动定位，十分方便，同文输入法有类似的功能么

**Comment by hrbwaxdoll** [comment]
這個需求很強烈，求支持

**Comment by itzXian** [comment]
支持,自己定制主题可以达到这个功能

#custom.trime.yaml
preset_keyboards:
      - {click: space, swipe_left: Left, swipe_right: Right}

关于更多定制操作可以查看trime预设主题(路径 /sdcard/rime/trime.yaml)

或者点击这里查看 [trime.yaml詳解](https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3)

**Comment by hrbwaxdoll** [comment]
谢谢！

**Comment by Xadoy** [comment]
swipe在我手机上的误操作率好高，基本上都会识别成click 或者long click，我觉得这算是bug了吧？还是只有我的手机这样？

**Comment by Xadoy** [comment]
oh, 我发现是搜狗的longpress_timeout或者multitap_interval设的太短了，所以滑动的触发有问题

**Comment by osfans** [comment]
嗯，那個主題的時間間隔比較短。
