### ISSUE TITLE
Upload stable builds from QQ Group everytime when it's confirmed as stable

### ISSUE THREAD

**Issue by ghost** [osfans/trime#221]
I know for stability, people should use old stable `3.0.1` release mainly because it's stable. But I see stable releases from trime QQ group are quite stable to use, so I open the issue to benefit github users. In the past, I used QQ wine application from deepin, all good. Now I am aware that I should abandon all the non-free softwares(not firmware) for all the devices, especially products from Tencent, one of the biggest EVIL CORPs in China. Please take it into consideration and be a user with FOSS. :-)

**Comment by Artoria2e5** [comment]
Are those QQ group builds based on source code available on GitHub (like a nightly build)? If that's the case, perhaps osfans can set up some sort of CI that builds an apk and puts it on bintray.

**Comment by ghost** [comment]
Yes, those builds are built from github and use newer library like boost. Setting up CI to upload apk here is an awesome idea, +1 for it.

**Comment by ghost** [comment]
I'd dare to ping @osfans

**Comment by Bambooin** [comment]
CI build is available on F-Droid and Github release, please refer the README.

@Artoria2e5  This is a ci  test build.    https://github.com/osfans/trime/tree/gh-pages
