### ISSUE TITLE
请教：带“- {”行的patch语句的写法

### ISSUE THREAD

**Issue by netzrh** [osfans/trime#223]
![default](https://user-images.githubusercontent.com/39295518/40298997-69e72c8a-5cd4-11e8-96ca-7762b3bb21f9.png)

**Comment by osfans** [comment]
這個應該可以刪除列表吧。
yaml通用的問題，可以去 [rime/home](https://github.com/rime/home) 問問，那邊人多。

**Comment by netzrh** [comment]
进qq群，看教程和Wiki，得到一些帮助
谢谢，关了！
