### ISSUE TITLE
OPPO r11 plus 使用经常崩溃

### ISSUE THREAD

**Issue by ghost** [osfans/trime#224]
OPPO R11 plus使用经常崩溃，崩溃之后就打不开了，只能卸载重新安装。

**Comment by osfans** [comment]
這個要看日誌了。

**Comment by Bambooin** [comment]
@ghost
很多国产 ROM 会严重杀应用，是不是考虑把 Trime 加在常驻内存白名单

目前使用 LineageOS 没有遇到这个问题，从用户反馈来说 OPPO 和Vivo 平台
似乎经常遇到 Trime 崩溃或无法使用问题，怀疑他们把 Trime 应用进程杀死了。
