### ISSUE TITLE
如何設定在ASCII模式下使用不同的hint、longclick等等？

### ISSUE THREAD

**Issue by danny0838** [osfans/trime#225]
試做了一個倉頡鍵盤如下：

    keys:
      - {label: 手, hint: q, click: q, long_click: 1, swipe_down: "!", key_back_color: bh1, key_text_color: th1}

以上設定在中文模式下顯示「手」及hint=q，在ASCII模式下「手」會變成「q」但hint的q不會消失。請問要如何設定才能讓它消失呢？

同理，如果希望中文模式時和西文模式的longclick提示不同，該怎麼做呢？

**Comment by Bambooin** [comment]
过时的 issue
