### ISSUE TITLE
如何為trime以外的主題打補靪？

### ISSUE THREAD

**Issue by danny0838** [osfans/trime#226]
如題，新增 `trime.custom.yaml` 可以為 `trime.yaml` 打補靪；若是要為 `tongwenfeng.trime.yaml` 打補靪該怎麼做呢？試過用`tongwenfeng.custom.trime.yaml` 和 `tongwenfeng.custom.yaml` 似乎都不行……。

**Comment by xiaoqun2016** [comment]
xxx.trime.custom.yaml

**Comment by danny0838** [comment]
原來如此，改用 `tongwenfeng.trime.custom.yaml` 就可以了。

[教學文件](https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3)似乎沒提到這部分，也許可以擴充一下？

**Comment by xiaoqun2016** [comment]
wiki就是由大家一起维护的，你也可以来写的。

**Comment by danny0838** [comment]
請問目前 wiki 是否有簡繁用字的約定？我習慣使用繁體中文，但文檔是簡中，我改了可能會造成繁簡不統一。

**Comment by xiaoqun2016** [comment]
单个页面内部还是统一比较好。要是你扩充的内容能够形成一个小课题，那可以新建一个页面，用你习惯的方式来写。写简写繁大家基本都看得懂。

**Comment by danny0838** [comment]
瞭解，感謝。
