### ISSUE TITLE
修改 *.trime.custom.yaml 後重新部署不會更新

### ISSUE THREAD

**Issue by danny0838** [osfans/trime#227]
如題，修改 `*.trime.custom.yaml` 檔案並按下重新部署，`*` 主題的設定值沒有改變。

此時如果修改 `*.trime.yaml` 檔案的最後修改時間（隨便做個修改存檔，還原該修改再存檔；或 `touch *.trime.yaml`）再按下重新部署，之前對 `*.trime.custom.yaml` 檔案的修改就會反映到 `*` 主題。

我推測程式在重新部署時會檢查 `*.trime.yaml` 的最後修改時間是否晚於上次部署的時間來決定是否更新 `*` 主題，但沒有檢查 `*.trime.custom.yaml` 檔案，以致於更新 `*.trime.custom.yaml` 檔案時，如果 `*.trime.yaml` 的最後修改時間沒有變化，就不會更新 `*` 主題。

同文輸入法版本： v3.0.1-20170210

**Comment by xiaoqun2016** [comment]
文件名若无误，那就重点检查下补丁有没有语法错误。 一般都是这两个原因了。   
你可以把不能更新的补丁贴上来，看能不能找到问题。

**Comment by danny0838** [comment]
抱歉之前的描述不夠清楚，我的意思是：修改 `*.trime.custom.yaml` 檔案並按下重新部署，`*` 主題的設定值沒有改變；但接著修改 `*.trime.yaml` 檔案的**最後修改時間**後再重新部署，`*`  主題的設定值就改變了。因此，可能是程式沒有檢查到 `*.trime.custom.yaml` 檔案更新而 `*.trime.yaml` 檔案未更新的情況。

已修改一樓的文字，煩請再確認。

**Comment by xiaoqun2016** [comment]
确认过，我这儿无法复现你说的问题。

**Comment by danny0838** [comment]
最近測試又沒這個問題了，看來之前的推測有誤。暫且先關閉議題，之後發現類似問題再提出。抱歉打擾，感謝。
