### ISSUE TITLE
切換中英文會導致sougou主題介面異常

### ISSUE THREAD

**Issue by danny0838** [osfans/trime#228]
如題，內建sougou主題的符號表右上角的按鈕在輸入模式為西文時會變成奇怪的東西。見圖：

![screenshot_20180626-021042](https://user-images.githubusercontent.com/531417/41867916-0761e364-78e7-11e8-9d52-6484a4c2c801.png)
![screenshot_20180626-021045](https://user-images.githubusercontent.com/531417/41867917-09c320e6-78e7-11e8-97a2-7b2615c8ba2f.png)

同文輸入法版本： v3.0.1-20170210

**Comment by xiaoqun2016** [comment]
键盘布局中的label只会在中文模式生效，这是正常现象。  此处显示的“下”就是在键盘布局中添加的`label: '下'`。  
这是主题写法的问题。  

不过新版同文已经不再内置这个主题了，有些问题可能需要你在使用过程中自行修正了。

**Comment by danny0838** [comment]
如果 `label` 只會在中文模式生效，請問要怎麼讓按鈕在英數模式下顯示不同於 `click` 的標示文字？

**Comment by xiaoqun2016** [comment]
只在中文模式生效的是preset_keyboards里面的label。 在preset_keys里面写的label是中英模式都生效的（前提是要去掉preset_keyboards里面的label）。  

---

>請問要怎麼讓按鈕在英數模式下顯示不同於 click 的標示文字？

英文模式下的标签取决于click的内容，除非你设置了`ascii: xxx`，但这样子会同时改变英文模式下click的功能。

**Comment by danny0838** [comment]
也就是說 `ascii` 的作用是在英數模式下覆寫 `click` 嗎？

有個提議，如 #225 提到的問題，目前 `hint`、`longclick` 等功能似乎無法在英數模式下與中文模式下有不同的行為。能否把 `ascii` 改為 `ascii_click`（原 `ascii` 保留作別名以向下相容），並提供 `ascii_hint`、`ascii_longclick`、`ascii_swipe_*` 等屬性？這樣語義更清楚，也讓 `hint`、`longclick` 等功能可以在英數模式與中文模式下有不同的行為。

**Comment by Bambooin** [comment]
sougou 主題 已经删除，可以使用 同文风 主题
