### ISSUE TITLE
下载android版本源码为什么跑不起来

### ISSUE THREAD

**Issue by zyz002** [osfans/trime#230]
Build command failed.

Error while executing process F:\android\SDK\cmake\3.6.4111459\bin\cmake.exe with arguments {-HG:\trime-develop\trime-develop\app\src\main\jni -BG:\trime-develop\trime-develop\app\.externalNativeBuild\cmake\release\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-21 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=G:\trime-develop\trime-develop\app\build\intermediates\cmake\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=F:\android\SDK\ndk-bundle -DCMAKE_TOOLCHAIN_FILE=F:\android\SDK\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=F:\android\SDK\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static -DANDROID_STL_FORCE_FEATURES=ON}

 (project) 

-- Check for working C compiler: F:/android/SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe

-- Check for working C compiler: F:/android/SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Check for working CXX compiler: F:/android/SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe

-- Check for working CXX compiler: F:/android/SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

Configuring snappy ...

-- Looking for byteswap.h

-- Looking for byteswap.h - found

-- Looking for stddef.h

-- Looking for stddef.h - found

-- Looking for stdint.h

-- Looking for stdint.h - found

-- Looking for sys/endian.h

-- Looking for sys/endian.h - found

-- Looking for sys/mman.h

-- Looking for sys/mman.h - found

-- Looking for sys/resource.h

-- Looking for sys/resource.h - found

-- Looking for sys/time.h

-- Looking for sys/time.h - found

-- Looking for sys/uio.h

-- Looking for sys/uio.h - found

-- Looking for unistd.h

-- Looking for unistd.h - found

-- Looking for windows.h

-- Looking for windows.h - not found

-- Looking for zlibVersion in z

-- Looking for zlibVersion in z - found

-- Looking for lzo1x_1_15_compress in lzo2

-- Looking for lzo1x_1_15_compress in lzo2 - not found

-- Performing Test HAVE_BUILTIN_EXPECT

-- Performing Test HAVE_BUILTIN_EXPECT - Success

-- Performing Test HAVE_BUILTIN_CTZ

-- Performing Test HAVE_BUILTIN_CTZ - Success

-- Looking for mmap

-- Looking for mmap - found

-- Looking for sysconf

-- Looking for sysconf - found

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/snappy/cmake/config.h.in does not exist.

CMake Error at CMakeLists.txt:75 (configure_file):

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/snappy/snappy-stubs-public.h.in does not exist.

CMake Error at CMakeLists.txt:96 (configure_file):

You have called ADD_LIBRARY for library marisa-static without any source files. This typically indicates a problem with your CMakeLists.txt file

You have called ADD_LIBRARY for library boost-static without any source files. This typically indicates a problem with your CMakeLists.txt file

You have called ADD_LIBRARY for library yaml-cpp-static without any source files. This typically indicates a problem with your CMakeLists.txt file

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/miniglog/miniglog/logging.h does not exist.

CMake Error at CMakeLists.txt:230 (configure_file):

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/BinaryDict.hpp does not exist.

CMake Error at CMakeLists.txt:303 (configure_file):

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Common.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Config.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Conversion.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/ConversionChain.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Converter.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/DartsDict.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Dict.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/DictConverter.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/DictEntry.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/DictGroup.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Exception.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Export.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Lexicon.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/MaxMatchSegmentation.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Optional.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/PhraseExtract.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Segmentation.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Segments.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/SerializableDict.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/SimpleConverter.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/TextDict.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/UTF8StringSlice.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/UTF8Util.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/opencc.h does not exist.

-- Looking for pthread.h

-- Looking for pthread.h - found

-- Looking for pthread_create

-- Looking for pthread_create - found

-- Found Threads: TRUE  

You have called ADD_LIBRARY for library rime without any source files. This typically indicates a problem with your CMakeLists.txt file

fatal: not a git repository: 'G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/.git'

CMake Error at CMakeLists.txt:373 (string):

fatal: not a git repository: 'G:/trime-develop/trime-develop/app/src/main/jni/librime/.git'

CMake Error at CMakeLists.txt:378 (string):

-armeabi-v7a

-- Configuring incomplete, errors occurred!

See also "G:/trime-develop/trime-develop/app/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeOutput.log".

See also "G:/trime-develop/trime-develop/app/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeError.log".

Build command failed.

Error while executing process F:\android\SDK\cmake\3.6.4111459\bin\cmake.exe with arguments {-HG:\trime-develop\trime-develop\app\src\main\jni -BG:\trime-develop\trime-develop\app\.externalNativeBuild\cmake\debug\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-21 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=G:\trime-develop\trime-develop\app\build\intermediates\cmake\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=F:\android\SDK\ndk-bundle -DCMAKE_TOOLCHAIN_FILE=F:\android\SDK\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=F:\android\SDK\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static -DANDROID_STL_FORCE_FEATURES=ON}

 (project) 

-- Check for working C compiler: F:/android/SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe

-- Check for working C compiler: F:/android/SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Check for working CXX compiler: F:/android/SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe

-- Check for working CXX compiler: F:/android/SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

Configuring snappy ...

-- Looking for byteswap.h

-- Looking for byteswap.h - found

-- Looking for stddef.h

-- Looking for stddef.h - found

-- Looking for stdint.h

-- Looking for stdint.h - found

-- Looking for sys/endian.h

-- Looking for sys/endian.h - found

-- Looking for sys/mman.h

-- Looking for sys/mman.h - found

-- Looking for sys/resource.h

-- Looking for sys/resource.h - found

-- Looking for sys/time.h

-- Looking for sys/time.h - found

-- Looking for sys/uio.h

-- Looking for sys/uio.h - found

-- Looking for unistd.h

-- Looking for unistd.h - found

-- Looking for windows.h

-- Looking for windows.h - not found

-- Looking for zlibVersion in z

-- Looking for zlibVersion in z - found

-- Looking for lzo1x_1_15_compress in lzo2

-- Looking for lzo1x_1_15_compress in lzo2 - not found

-- Performing Test HAVE_BUILTIN_EXPECT

-- Performing Test HAVE_BUILTIN_EXPECT - Success

-- Performing Test HAVE_BUILTIN_CTZ

-- Performing Test HAVE_BUILTIN_CTZ - Success

-- Looking for mmap

-- Looking for mmap - found

-- Looking for sysconf

-- Looking for sysconf - found

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/snappy/cmake/config.h.in does not exist.

CMake Error at CMakeLists.txt:75 (configure_file):

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/snappy/snappy-stubs-public.h.in does not exist.

CMake Error at CMakeLists.txt:96 (configure_file):

You have called ADD_LIBRARY for library marisa-static without any source files. This typically indicates a problem with your CMakeLists.txt file

You have called ADD_LIBRARY for library boost-static without any source files. This typically indicates a problem with your CMakeLists.txt file

You have called ADD_LIBRARY for library yaml-cpp-static without any source files. This typically indicates a problem with your CMakeLists.txt file

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/miniglog/miniglog/logging.h does not exist.

CMake Error at CMakeLists.txt:230 (configure_file):

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/BinaryDict.hpp does not exist.

CMake Error at CMakeLists.txt:303 (configure_file):

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Common.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Config.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Conversion.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/ConversionChain.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Converter.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/DartsDict.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Dict.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/DictConverter.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/DictEntry.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/DictGroup.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Exception.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Export.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Lexicon.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/MaxMatchSegmentation.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Optional.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/PhraseExtract.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Segmentation.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/Segments.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/SerializableDict.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/SimpleConverter.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/TextDict.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/UTF8StringSlice.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/UTF8Util.hpp does not exist.

CMake Error: File G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/src/opencc.h does not exist.

-- Looking for pthread.h

-- Looking for pthread.h - found

-- Looking for pthread_create

-- Looking for pthread_create - found

-- Found Threads: TRUE  

You have called ADD_LIBRARY for library rime without any source files. This typically indicates a problem with your CMakeLists.txt file

fatal: not a git repository: 'G:/trime-develop/trime-develop/app/src/main/jni/OpenCC/.git'

CMake Error at CMakeLists.txt:373 (string):

fatal: not a git repository: 'G:/trime-develop/trime-develop/app/src/main/jni/librime/.git'

CMake Error at CMakeLists.txt:378 (string):

-armeabi-v7a

-- Configuring incomplete, errors occurred!

See also "G:/trime-develop/trime-develop/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeOutput.log".

See also "G:/trime-develop/trime-develop/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeError.log".

**Comment by yueduz** [comment]
这个好像没人在windows下跑过，我都是在linux下。

**Comment by osfans** [comment]
應該是沒有下載子模塊

**Comment by osfans** [comment]
有問題再請更新。暫時關閉。
