### ISSUE TITLE
Android 9.0 输入框消失

### ISSUE THREAD

**Issue by monologconnor** [osfans/trime#231]
升级完安卓9.0后发现原本的编码区域不见了(阴影效果还在) 看不出自己已经输入了什么
![screenshot_20180811-140359](https://user-images.githubusercontent.com/38450642/43988022-9cc998e6-9d6f-11e8-8574-685478fe5e7a.png)

**Comment by dejavuwl** [comment]
我也遇到这个问题，并且选单也无法显示 到最上层，只有位于键盘下方的部分能显示出来
![image](https://user-images.githubusercontent.com/19871560/46566294-5aa20600-c94e-11e8-9d1b-aeefd9280a9a.png)

**Comment by jack-dracula** [comment]
和上面问题一样，拼音的显示框消失了

**Comment by osfans** [comment]
感謝回報。我再測試看看。

**Comment by osfans** [comment]
看來9.0上都有這個問題，暫時還沒有解法。

https://stackoverflow.com/questions/51906586/display-dialog-from-input-method-service-in-android-9-android-pie

**Comment by huyz-git** [comment]
![screenshot_2018-10-31-13-13-51-857_pl solidexplorer2](https://user-images.githubusercontent.com/22879638/47767549-174d7400-dd0f-11e8-8ee7-8daea0b66d76.png)
![screenshot_2018-10-31-13-13-34-042_com rhmsoft edit](https://user-images.githubusercontent.com/22879638/47767555-22080900-dd0f-11e8-9a39-8d116e70406e.png)
目前看来，在安卓9.0上，在填充的输入框状态下是可以正常显示编码的，非填充状态下则不行。

**Comment by huyz-git** [comment]
另外，我搜到了另外一个曾经遇到过相同问题的软件，但这个软件似乎已经解决了这个问题，可供参考：
https://github.com/PhilippC/keepass2android/issues/492
https://github.com/PhilippC/keepass2android/issues/377

**Comment by osfans** [comment]
@huyizheng 確實一樣，不過這個改動好像比較大，還沒看懂。

**Comment by wzyboy** [comment]
> 目前看来，在安卓9.0上，在填充的输入框状态下是可以正常显示编码的，非填充状态下则不行。

「填充」是在说「横屏」吗？我第一次使用 Trime 就是在 Android 9.0 上，总感觉怪怪的，后来终于发现原来是因为看不到已经输入的内容（仔细看可以看到小小的下边界阴影）。

我试了下横屏，终于能看到输入的东西了，但是候选框整条变黑了，选不了词了 :-)

**Comment by coci713** [comment]
好像群里面的最新的黑客键盘解决了这个问题，允许显示在其它应用上层

**Comment by huyz-git** [comment]
> 好像群里面的最新的黑客键盘解决了这个问题，允许显示在其它应用上层

好像是的，但是目前同文输入法并没有请求“显示在其它应用上层”这一权限。

**Comment by huyz-git** [comment]
更新：
最新版在请求了“显示在其他应用上层”权限之后：
方案菜单可以正常显示了：
![qq 20181217132229](https://user-images.githubusercontent.com/22879638/50068192-ae0ebb00-01ff-11e9-9d4b-bcf940abbeaa.png)
主题菜单还是不能显示：
![qq 20181217132253](https://user-images.githubusercontent.com/22879638/50068210-bcf56d80-01ff-11e9-801f-fa7cff50a934.png)
编码悬浮窗也还是不能显示：
![qq 20181217132243](https://user-images.githubusercontent.com/22879638/50068220-caaaf300-01ff-11e9-8d6c-fe40b092b0ff.png)

**Comment by osfans** [comment]
d8e9da2dfe2653c94cd4aecba00728b7a910cbb8 f98701c395896430dadb88abfff38ec299d254e3 e0c79f44cb40923ed3b574e5e69bb7785a7a5c87  修正了此問題。
https://github.com/osfans/trime/releases/download/v3.1/trime-20181217-release.apk 可顯示懸浮窗和對話框。

**Comment by wzyboy** [comment]
感谢修复！请问 `trime-20181217-release.apk` 相比 Play Store 上的 `trime-20170803-release.apk` ，是 cherry-pick 了这三个修复 commits，还是包含了从 2017-08 至 2018-12 这 14 个月的所有 commits 呢？

-----

安装试了下，自问自答：是 HEAD 版本的。不知可否提供一下 cherry-pick 版本的呢？我倒是可以自己编译，但是 debug key 和 release key 不能互相覆盖 :joy: 

-----

看错了。Play Store 上是 3.0.1 (2017-02-10) 版本。

**Comment by lilydjwg** [comment]
我也遇到了这个问题。Play 商店的版本是否可以更新一下呢？
