### ISSUE TITLE
能否做一个仓颉的双鍵

### ISSUE THREAD

**Issue by chernglee** [osfans/trime#232]
很喜欢触宝的14鍵方案，请问在rime 下能否做个仓颉的双鍵方案？

THX

**Comment by MISTER-CHAN** [comment]
五笔的官方双键敎程，可参考原理做仓颉的双键。

**Comment by MISTER-CHAN** [comment]
五笔的官方双键敎程，可参考原理做仓颉的双键。
https://github.com/osfans/trime/wiki/%E4%BA%94%E7%AC%94%E5%8F%8C%E9%94%AE%E9%85%8D%E7%BD%AE%E6%A1%88%E4%BE%8B%E8%AF%A6%E8%A7%A3(%E5%9B%9B)-%E5%AE%9E%E7%8E%B0%E6%89%8B%E6%9C%BA%E4%B8%8A%E7%9A%84%E5%8F%8C%E9%94%AE%E9%94%AE%E7%9B%98

**Comment by MISTER-CHAN** [comment]
官方的五笔双键敎程，可参考做仓颉的双键。
https://github.com/osfans/trime/wiki/%E4%BA%94%E7%AC%94%E5%8F%8C%E9%94%AE%E9%85%8D%E7%BD%AE%E6%A1%88%E4%BE%8B%E8%AF%A6%E8%A7%A3(%E4%B8%80)-%E5%87%86%E5%A4%87%E7%AF%87
