### ISSUE TITLE
外接蓝牙键盘在termux中无法调用同文输入法

### ISSUE THREAD

**Issue by qchenac** [osfans/trime#235]
以下均是在外接蓝牙键盘的条件下的测试结果，除了termux之外的普通app下均可正常使用同文输入中文（只在底部显示一条buffer，软键盘自然就消失了），且如果换成swiftkey，触宝，gboard均可以在termux中正常使用自带的中文输入法，而同文则只能输入英文，在设置中实体键盘选项里勾选了显示软键盘也没有作用。怀疑是不是termux这类CLI的软件把同文识别成只有中文输入法，所以就强制使用英文输入了。另外如果不用蓝牙外接键盘的话，在termux里是可以正常使用同文输入的，好像是废话（～
关于同文的版本，群里最新的测试版和个人定制输入法文件夹中那个com.osfans.trime.apk还有google play的版本全都试过了，各种方案也都翻来覆去的部署过，结果都是一样。

**Comment by qchenac** [comment]
据群友测试，在小米手机上可以调用，华为则不行。我的设备是三星tab s3，还有一个nexus 6p也试了，都不可以在termux中调用同文

**Comment by fz68** [comment]
也有这个问题，候选栏可以用设置显示，但是仍然无法输入中文： https://github.com/ThomasHawaiiKing/my-Rime

**Comment by qchenac** [comment]
> 也有这个问题，候选栏可以用设置显示，但是仍然无法输入中文： https://github.com/ThomasHawaiiKing/my-Rime

是的，我也很早就看到过那个链接了。。。作者在群里说这个暂时没办法，但是也没说是什么原因，很苦恼

**Comment by hughfenghen** [comment]
> 按 音量键加＋ Q 打开快捷栏，然后向右划快捷栏打开输入框，输入中文
不够便捷，但好歹能输入。。。

**Comment by muyinliu** [comment]
SwiftKey 可能是唯一一个能在 Termux 下输入中文的输入法，但 SwiftKey 的词库非常的差而且不支持导入词库，即使多次选词也不一定能添加到词库里面，只能耐心点...

**Comment by aliyoge** [comment]
> SwiftKey 可能是唯一一个能在 Termux 下输入中文的输入法，但 SwiftKey 的词库非常的差而且不支持导入词库，即使多次选词也不一定能添加到词库里面，只能耐心点...

空格键还不能确认

**Comment by muyinliu** [comment]
> > SwiftKey 可能是唯一一个能在 Termux 下输入中文的输入法，但 SwiftKey 的词库非常的差而且不支持导入词库，即使多次选词也不一定能添加到词库里面，只能耐心点...
> 
> 空格键还不能确认

是的😂，而且更新了 N 个版本，这些 bug 就是不修正，可能这就是大公司的产品吧……脸皮都不是一般的厚

**Comment by muyinliu** [comment]
最近更新到 Microsoft SwiftKey Beta v9.10.20.21 发现有键盘悬浮功能可用，但还有 bug，接入蓝牙键盘不能完美地使用

**Comment by muyinliu** [comment]
很高兴告诉大家：「手心输入法」支持 Termux 下输入中文，而且支持蓝牙键盘空格键候选字上屏以及数字选择候选字，词库也比 Microsoft SwiftKey Beta 好用很多，Microsoft SwiftKey 可以考虑卸载了～
