### ISSUE TITLE
請問使用黑莓keytwo,要怎麼開啟emoji

### ISSUE THREAD

**Issue by kirk0523** [osfans/trime#236]
請問使用黑莓keytwo,要怎麼開啟emoji
還是emoji功能是給全觸控螢幕的人的設計?

**Comment by Bambooin** [comment]
同文风主题，可以输入 emoji，但是要在软键盘点击一些按钮

**Comment by kirk0523** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} 但是黑莓是實體鍵盤手機，不會顯示觸控鍵盤請問可以新增一個emoji的選項嗎？如附圖。                                                                                                                                             從我的 BlackBerry 傳送 - 安全智能手機                                                                                                                                                                           寄件者： ***@***.***已傳送： 2021年8月31日 20:27收件者： ***@***.***回覆： ***@***.***副本： ***@***.***; ***@***.***主旨： Re: [osfans/trime] 請問使用黑莓keytwo,要怎麼開啟emoji (#236)  

同文风主题，可以输入 emoji，但是要在软键盘点击一些按钮
