### ISSUE TITLE
关于横屏状态下布局定义的建议

### ISSUE THREAD

**Issue by CyLoiMe** [osfans/trime#238]
建议增加一种可选的键盘布局设置：横屏布局。
目前在竖屏状态下按键高度调得稍高的话，切换到横屏时键盘会占屏过多导致遮挡输入光标。
假如可自定义横屏布局的话，既可以设置至合适的高度，又可以设计一种新的布局（横屏时键盘变长，把字母放两边可能会更舒适），更加完美。
不然增加些设置横屏状态下的按键尺寸的参数也行  _(:3 」∠)_

**Comment by cmddot** [comment]
老早就有人提了啊。我刚接触这个输入法也发现这个问题了。目前这样，横屏下基本无法使用的
