### ISSUE TITLE
Trime和Android下最新的Firefox62不相容

### ISSUE THREAD

**Issue by iosonoungatto** [osfans/trime#239]
在首次进入网页的文本框或者离开后再次进入文本框的时候，输入第二个字母后，输入第一个字母时的第一个候选字会自动被输进文本框，同时第一个字母依然存在在输入法的输入框中。
Firefox升级前并没有此错误。
![screenshot_20181005-231152](https://user-images.githubusercontent.com/18104931/46566868-6d98e400-c916-11e8-94fa-a53bf036ecd9.png)
上图是输入两个d后的情景。输入第一个d时候选字排在第一位的是「的」。第二个d被输入后，「的」字出现在文本框，同时输入法的输入框中有dd，候选框中显示的是dd对应的词。

**Comment by leapfly** [comment]
我用同文遇到类似的问题，比如输入一个「O」，有时候会出来两个字，等效于输入了「O+空格+O」。
我的手机版本是ANDROID 8.1 ，使用的浏览器是Firefox 63.02，输入法是 同文输入法。

**Comment by Bambooin** [comment]
请使用Trime和Firefox最新版重试，未重现。

在README下载部分选择相应的下载方式，最好选择F-Droid。

https://f-droid.org/packages/com.osfans.trime

**Comment by iosonoungatto** [comment]
谢谢楼上建议。我前几天升级了FF，如楼上所说暂时没有发现问题。
