### ISSUE TITLE
希望增加一键语言切换

### ISSUE THREAD

**Issue by hans-johnson** [osfans/trime#24]
如 Google 输入法以及 iOS 自带一样，希望可以把地球图标做成一键切换下一个其他输入平台，长按弹出输入平台列表。同时，地球左侧「…」也希望可以做成一键直接切换输入平台内下一输入方案，长按弹出平台内输入方案列表供选择。谢谢。

**Comment by osfans** [comment]
把code設成“Control+Shift+1”，應該可以一鍵切方案。rime默認的快捷鍵。
一鍵切平臺，要研究一下google的做法。

**Comment by osfans** [comment]
現在要切換的有很多，一共六個，幫忙想想怎麼設計比較好：
內部切換中英文、大小寫、方案、下一方案
內部切換鍵盤
外部切換平臺、下一平臺

**Comment by osfans** [comment]
切到下一平臺也有了，暫時關閉。
https://github.com/osfans/trime/blob/develop/app/src/main/assets/rime/trime.yaml#L803

**Comment by syu-id** [comment]
请问一键切换平台功能具体怎样使用？
