### ISSUE TITLE
上滑和下滑输入符号容易误触

### ISSUE THREAD

**Issue by Oyami-Srk** [osfans/trime#243]
习惯Google输入法那种下滑输入符号，但是发现Trime不论是上滑还是下滑总是需要特别刁钻的手法。
按住一个按键向下滑这种一般逻辑是行不通的，而是需要在按键那块很小的地方上划动
十分难受……
总是容易误触

**Comment by delphinuz** [comment]
試一下滑動，無論上下、左右，都有點太敏銳不好操作。

Oyami-Srk的建議不錯，按著後再上下左右，是比較常用的方式。看有無機會改為：
1 立即放開
2 按著一定時間 (Hold)，此時間使用著可以自行設定。
3 在立即放開與Hold之間，加上有方向著為滑動。

**Comment by startstarz** [comment]
+1 同求
另外，建议可在一个选项：不区分左右滑动，只辨别上或下的滑动，这样可以进一步降低误触。
即类似google/搜狗输入法那样

**Comment by Bambooin** [comment]
#281
