### ISSUE TITLE
win下无法编译

### ISSUE THREAD

**Issue by chenzhen1994** [osfans/trime#244]

**Comment by osfans** [comment]
错误是什么？
已知问题是：Android Studio编译so时会卡住。

**Comment by chenzhen1994** [comment]
报错某个文件夹缺少.git文件夹，其实是有这个文件夹的，就是android studio识别不出来，应该是win环境的问题

**Comment by osfans** [comment]
那應該是子模塊沒有下全。

```git clone --recursive https://github.com/osfans/trime.git trime```

**Comment by osfans** [comment]
如有問題再打開。
