### ISSUE TITLE
会出现输入较快的时候卡住，或者反映很慢吗，如何优化呢

### ISSUE THREAD

**Issue by devWanweitong** [osfans/trime#245]

**Comment by osfans** [comment]
是有这个问题，要优化的话，可以考虑批量发送按键事件，目前是每个按键单独发送的。

**Comment by devWanweitong** [comment]
非常感谢

**Comment by Bambooin** [comment]
最新的测试版，无法复现
Daily build can be found for test and verify
https://github.com/osfans/trime/actions
