### ISSUE TITLE
Wordpress 11.2 无法输入内容

### ISSUE THREAD

**Issue by jetashi** [osfans/trime#246]
小鹤安卓版8.9
Wordpress11.2
多部安卓设备出现类似的问题
发布文章可以输入标题
但是文章内容无法输入，按键无反应
从其他地方粘贴任意文本后
又可以正常输入
不知道是小鹤的问题，还是Wordprese的问题

**Comment by Bambooin** [comment]
请使用最新版Trime测试是否重现。

在README下载部分选择相应的下载方式，最好选择F-Droid。

https://f-droid.org/packages/com.osfans.trime

或者到小鹤官网 https://www.flypy.com 论坛提问题。

**Comment by jetashi** [comment]
最新版同文测试，问题仍然重现，所以才在上游反馈问题

**Comment by jetashi** [comment]
Wordpress升级到最新11.4，小鹤和trime最新版本，问题仍然重现

**Comment by Bambooin** [comment]
再试试最新版能复现吗
Daily build can be found for test and verify
https://github.com/osfans/trime/actions
