### ISSUE TITLE
关于新版本（trime-20181217-release.apk）的几个问题

### ISSUE THREAD

**Issue by lilydjwg** [osfans/trime#259]
之前一直使用 Google Play 中的 v3.0.1-20170210 版本，后来系统升级，为解决 #231 而安装了 GitHub releases 里的新版，遇到了一些问题：

* 我使用的 sougou 皮肤中的部分符号无法使用（键盘上看不到、也打不出来），比如：`~"?!:^%$`。这是何故？
* 长按时间变长了，导致更多的输入停顿。如何设置为旧行为？

另外，自定义主题时，在中文模式下，英文符号上屏前会被转换成中文符号。我能不能在配置按键时指定不要这个行为？

**Comment by xiaoqun2016** [comment]
①新版的`android_keys`有变化，可以把新trime.yaml里的`android_keys`抄到旧主题里（大概有七八十行）。

②长按时间现在是在设置页面调整，主题里的参数废弃了  

③直接上屏英文字符可以用`commit`，trime.yaml里有示例（要更新到最新的测试版，20181217版没有这个功能）

**Comment by lilydjwg** [comment]
问题已经解决，谢谢解答～
