### ISSUE TITLE
同文一直存在的一个小问题，附重现方法

### ISSUE THREAD

**Issue by MokOopsing** [osfans/trime#261]
如题，同文似乎一直有个不影响使用的问题，它偶尔会莫名奇妙使当前屏幕上的某个app的图标加上一个方框，十分诡异，虽然没什么影响，但是强迫症有点受不了
ps：现已知道如何复现

**Comment by MokOopsing** [comment]
复现：桌面上滑/下滑，进入桌面搜索，英文模式下，点击2下或以上任意字母按键（如aa），再点击一下home键回到桌面，桌面上app图标会多一个方形边框，点击桌面任意处消失，若此时点击多任务键，多任务界面里app视窗微缩图也会多一个方框。

**Comment by xiaoqun2016** [comment]
以前用三星手机的时候遇到过同样的问题，打完字回到桌面发现第一个图标被选中了。用小小输入法也会这样，跟作者反馈过但他们都不能复现。  

你试试关掉嵌入式编辑模式，也许就好了

**Comment by MokOopsing** [comment]
> 以前用三星手机的时候遇到过同样的问题，打完字回到桌面发现第一个图标被选中了。用小小输入法也会这样，跟作者反馈过但他们都不能复现。
> 
> 你试试关掉嵌入式编辑模式，也许就好了

确实是三星手机，关掉嵌入式编辑模式还是一样的:'( 所以应该是三星固件通病了，作者应该不会（没办法）解决这个问题了

**Comment by nicewise** [comment]
同有這個問題。關掉嵌入式編輯模式，重新部署之後消失。

**Comment by MokOopsing** [comment]
> 同有這個問題。關掉嵌入式編輯模式，重新部署之後消失。

请问你的是否也是三星机型呢？我关掉嵌入式，重新部署还是没有变化

**Comment by PoseidonWake** [comment]
这个加方框很像是发送了TAP键的效果，我一加也有这个问题，切换到英文后，在chrome地址栏百分之百会出现。

**Comment by MokOopsing** [comment]
已经不用三星，换了个机子没这个问题了，还有另一个崩溃的的问题#268也没了，所以。。。emm三星辣鸡

**Comment by Bambooin** [comment]
@mokapsing 这个问题可以在 #277 跟踪，里面提供信息更详细
