### ISSUE TITLE
3.1.2版本默认安装后，没有中文输入。

### ISSUE THREAD

**Issue by ghost** [osfans/trime#267]
我知道要修改default.yaml等文件，但是我用pc上的那堆yaml文件上传到手机的rime文件夹后，无法完成部署，一直在转圈。想要从头开始创建这些文件，又不知去哪儿找模板，能给个教程吗？

**Comment by ghost** [comment]
![1281869629](https://user-images.githubusercontent.com/591922/52098269-4a065180-2609-11e9-856c-5b5eee30920b.jpg)
![2021501175](https://user-images.githubusercontent.com/591922/52098270-4a065180-2609-11e9-83fc-f282dacb5dd6.jpg)
我再把这个安装过程盘一下，小米5s用户，miui9 8.2.1 开发版，从 github 下载 trime-20181217-release.apk，在安装前卸载原有版本，删除 /sdcard/rime 文件夹，确保干净的安装。安装后，只能输入英文。于是把 pc 上的小狼毫配置文件上传。
[rime.zip](https://github.com/osfans/trime/files/2819785/rime.zip)
有几个字典文件太大，我就不上传了，反正如图所示，选择了我要的方案后，部署的圆圈只画了1/4个不到，就闪退出界面，然后输入汉字，可以看到选择框空白，没有显示中文，也不能上屏中文。

**Comment by ghost** [comment]
目前转到谷歌拼音，反正打死不用国内的云输入法。

**Comment by ghost** [comment]
再从头安装一遍，这次学乖了，直接从https://github.com/rime/rime-luna-pinyin下载明月拼音的配置，放到rime目录，但是，找不到方案，只好自己写个 luna_pinyin.custom.yaml，很简单，只求出中文
`# luna_pinyin.custom.yaml`
`patch:`
`  "translator/dictionary": luna_pinyin`
结果，还是没有出现中文的候选字。也没有中文输入，我把明朝花园的字体下载，改名为han.ttf ，放到 rime/fonts 目录中，以求和 trime.yaml 等默认配置中的字体配合，还是没用，说明不是字体的问题。

**Comment by jiru** [comment]
@hjonline I had the same problem: no Chinese input after a installing `trime-20181217-release.apk`. I solved the problem by installing `trime-20170210.apk`, then upgrading to `trime-20170803-release.apk`, then upgrading to `trime-20181217-release.apk`.

**Comment by bj1949007** [comment]
同文新版更新了librime，语法要求比以前严格，建议先找个能用的方案，再将原有的配置一点点往上加

**Comment by 20140103** [comment]
怎么输入中文呢？

**Comment by Bambooin** [comment]
可以参考这个配置文件和步骤，希望有帮助

https://github.com/Bambooin/rimerc
