### ISSUE TITLE
如何製做apk？

### ISSUE THREAD

**Issue by uliloewi** [osfans/trime#269]
我自己製做了南京話拼音輸入法 https://github.com/uliloewi/lang2jin1 。schema.yaml和dict.yaml都有。怎麼做apk以便裝到安卓手機上？

**Comment by GJRobert** [comment]
南京話拼音，太潮了，兄弟，我佩服您

**Comment by uliloewi** [comment]
> 南京話拼音，太潮了，兄弟，我佩服您

閣下是南京人？apk還沒做成，但已經可以安裝了。參 https://uliloewi.github.io/LangJinPinIn/angzhuangfa

**Comment by GJRobert** [comment]
在下台灣人，不是您同鄉，不過非常支持各地語言的發展。您的南京話拼音、教程，還有另一個您參考的潮汕語專案，還有您們所做的 RIME 方案，對我都是很好的啟發及學習的對象。（因為我最近才開始接觸 RIME，所以看到除了吳語、粵語、閩南語之外還有其他語言也開始來利用 RIME，實在是挺驚艷的）

謝謝！祝您的 apk 問題順利找到答案！南京話輸入法我是會下載來觀摩學習的。

**Comment by Bambooin** [comment]
最新的APK，可以从下面地址获取，你的方案只需放入/sdcard/rime，并选取需要的方案，部署即可。

https://github.com/osfans/trime/tree/gh-pages

**Comment by GJRobert** [comment]
ulilowei 原本似乎是想問，個別的輸入方案，能否做成個別安裝的 APK，甚至個別發布到 Play Store 上，然後一鍵安裝，減少手動放入方案文件的步驟。
