### ISSUE TITLE
扩展字符集在哪获得?怎么添加？

### ISSUE THREAD

**Issue by Comaxim** [osfans/trime#27]
希望能详细说说

**Comment by osfans** [comment]
什麼意思？字體顯示嗎？字體目前是設定hanb字體，就能顯示了。
碼表的話，就是要自己添加了。

**Comment by Comaxim** [comment]
我向你說一下我的情況：只有“全拼”，“明月拼音*簡化字”在打字時有字出來，別的都打不出來，請問是碼表的問題嗎？還有默認情況下是hanb字體嗎？

**Comment by osfans** [comment]
是啊，那就是碼表不全。需要人維護的。

**Comment by Comaxim** [comment]
哦，謝謝了。
