### ISSUE TITLE
如何配置为默认英文输入？

### ISSUE THREAD

**Issue by skygate2012** [osfans/trime#271]
在schema.yaml修改`reset: 1`后没有作用，默认还是中文输入。

**Comment by metroroland** [comment]
你意思是未組成字詞時先在文字框顯示英文？等組好才中文上屏？

**Comment by skygate2012** [comment]
> 
> 
> 你意思是未組成字詞時先在文字框顯示英文？等組好才中文上屏？

不是，就是切换到输入法的时候默认是英文；按<kbd>Shift</kbd>切换到中文
不过现在问题已经解决（重装恢复默认配置再修改），谢谢关注

**Comment by QiangF** [comment]
我也想第一次在某个app里使用默认英文模式，就是输入全是英文不显示候选菜单，假设这个app是开机后第一次打开。

怎么我在 .schema.yaml 这么设都不行？

    switches:
    - name: ascii_mode
        reset: 1
        states: [ 中文, 西文 ]

    switches:
    - name: ascii_mode
        reset: 0
        states: [ 中文, 西文 ]

@skygate2012 能分享一下你的设置吗

**Comment by QiangF** [comment]
@metroroland 感觉应该和电脑上的一致，电脑上开机打开输入法后，默认输入就是英文/西文状态，就是不会显示候选词的状态，就是敲一个字母就上屏一个字母的状态

**Comment by lib314a** [comment]
键盘的默认输入模式会受到reset_ascii_mode 这个选项的干扰。

See #555.
