### ISSUE TITLE
Android Q 鍵盤終止運作

### ISSUE THREAD

**Issue by chivincent** [osfans/trime#274]
於 Android Q Beta 1 時，鍵盤會直接終止運作

**Comment by osfans** [comment]
這麼快就用上了？好像SDK還沒有出來。

**Comment by chivincent** [comment]
剛好昨天看到 Android Beta 的計畫就順手升了

然後 Android Q 目前有 Preview 的 SDK

![Screenshot_20190315_130442](https://user-images.githubusercontent.com/7449005/54409664-f8320a80-4722-11e9-8bc8-8fab3de1190c.png)

**Comment by stjnu** [comment]
android q beta4 无限闪退

**Comment by tangweijr** [comment]
同样的问题，小米手机，android q闪退

**Comment by Bambooin** [comment]
https://github.com/osfans/trime/blob/gh-pages/release/app-release.apk

请试试最新的版本。
