### ISSUE TITLE
在英文状态下输入似乎会自动发送Tap键

### ISSUE THREAD

**Issue by PoseidonWake** [osfans/trime#277]
与 #261 类似，在英文状态下返回桌面，会有一个方框选中左上角的图标

![Screenshot_20190326-205855.jpg](https://i.loli.net/2019/03/26/5c9a22436f449.jpg)

但不止出现在桌面，其他很多App里也有这个问题，都很像是按了一个Tap键的效果。
比如英文状态下在 Chrome 中输入自动选中第一个候选；使用其他工具搜索自动选中左上第一个按钮。

![Screenshot_20190326-104710.jpg](https://i.loli.net/2019/03/26/5c9a22f383e2c.jpg)![Screenshot_20190326-110519.jpg](https://i.loli.net/2019/03/26/5c9a22f522d5a.jpg)

和其他人交流后发现不止我一个人出现这个问题，下面这图是酷安评论区的，在知乎里出现，也是英文状态下打了几个字后，好像按了Tap键一样，输入框被选中，失去焦点，后面的输入直接无效了。

![cd20049241643a938b9d25c549e0b6e6.gif](https://i.loli.net/2019/03/26/5c9a25715a9ea.gif)

我试过换方案、换主题或者像 #261 里说的关闭嵌入模式，都不能消除这个问题。

**Comment by Bambooin** [comment]
困扰好久，根据 @KhaosChow 描述找到复现步骤

在按下 Home 键时，如果此时的 APP 使用了 Trime 并且是**英文模式**，
桌面就有一个 APP 图标被选中，按下桌面其他地方消失，如果是中文模式就没有这个现象。

使用了很多手机 Trime 都有这个现象，系统是 LineageOS

**Comment by Bambooin** [comment]
在补充一下复现必要条件，100% 复现

- Trime  处于英文模式
- 切换到桌面前，输入框一定要有字符

复现应用
- 微信
- Firefox
- 短信
- 联系人
- 设置
- 其他应用

@osfans 有空闲时间可以 debug 一下

**Comment by Bambooin** [comment]
最新版无法复现了

Daily build can be found for test and verify
https://github.com/osfans/trime/actions

**Comment by 1pcr3ss** [comment]
LineageOS official 17.1，3.2.2还是存在这个问题。中文、英文状态无差，只需要在输入框内使用Home或者End，无需字符，上划回桌面就会有图标被选到的现象。

**Comment by Bambooin** [comment]
LineageOS unofficial 18.1 无法复现

**Comment by 1pcr3ss** [comment]
> LineageOS unofficial 18.1 无法复现

备机的18.1official也有，但发现可能和系统无关。nova launcher才有，trebuchet不会。

**Comment by Bambooin** [comment]
Trebuchet 不会复现，其他的没有试过
