### ISSUE TITLE
升級核心算法庫 librime 1.4.0

### ISSUE THREAD

**Issue by delphinuz** [osfans/trime#279]
新增 拼寫糾錯 選項。

但下載新版的trime, 使用時並沒有這功能。

**Comment by osfans** [comment]
有的，需要在script translator中打開：
`translator/enable_correction: true`

用自動編譯的最新版看看： http://osfans.github.io/trime/

**Comment by delphinuz** [comment]
試了一下，是有的。不過應還有一些進步的空間。
