### ISSUE TITLE
中文模式下按_會輸出--

### ISSUE THREAD

**Issue by delphinuz** [osfans/trime#280]
使用luna拼音，原本以為是有特定的轉換鍵，但看一下luna_pinyin.schema裡是沒這樣的設定。

![ezgif-3-e7dae4afbb9c](https://user-images.githubusercontent.com/615043/55269933-d2386880-52d3-11e9-8723-1eb8d8a6556e.gif)

**Comment by Bambooin** [comment]
是不是 librime 里面的设定，我 Windows 里面也是这个效果。
