### ISSUE TITLE
滑動輸入建議

### ISSUE THREAD

**Issue by delphinuz** [osfans/trime#281]
用同一個gif來表示

https://user-images.githubusercontent.com/615043/55269933-d2386880-52d3-11e9-8723-1eb8d8a6556e.gif

當按下k下滑時也會觸發到m。若能增加個判斷，原按鍵未放手之前，之後的按鍵m不被觸發，這樣按下k再怎麼划動還是以k為主，這樣滑動應該會精確一些。

另外也建議可加個長滑動，這樣功能可設定多些。

**Comment by qidizi** [comment]
赞成，效利上来说上滑比长按更加省时快捷。
长按跟repeat又是冲突的。
所有滑动都应该不放前锁定起始键。而不是像当前处理，导致释放要非常小心。

另外所有的滑动都应该可以设定label

**Comment by AllenKOO** [comment]
强烈同意，现在确实不好用，我全部换成long_click了

**Comment by xlucn** [comment]
希望能参考gboard（中文输入）的行为，至少我个人觉得是很符合直觉的。

**Comment by aaron2wh** [comment]
你們是如何滑動輸入的啊？我好像不行啊，需要在哪裏開啓嗎？

**Comment by xlucn** [comment]
和输入方案有关，要有支持滑动输入的方案。多数在相应按键下部有标记，而不是上方。当然也不一定总是

比如我尝试过的 https://github.com/cxcn/danjing 甚至设置了四个方向的滑动，难用得很。。。
