### ISSUE TITLE
不同輸入法與鍵盤配置

### ISSUE THREAD

**Issue by delphinuz** [osfans/trime#282]
不同輸入法像是拼音與注音的鍵盤是不同的，是否在切換輸入法時，也能同時變更鍵盤配置呢？

**Comment by kltk** [comment]
同文输入法现在的自动匹配机制就是这样的 [trime.yaml详解](https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3)（见布局调用）

没有切换应该是没有对应输入法的布局
