### ISSUE TITLE
Feature request 9键拼音的支持

### ISSUE THREAD

**Issue by ted423** [osfans/trime#283]
主要是个人习惯，会比较习惯9键

**Comment by MISTER-CHAN** [comment]
对于九键、十四键等，官方早有敎程，原理相同：https://github.com/osfans/trime/wiki/%E4%BA%94%E7%AC%94%E5%8F%8C%E9%94%AE%E9%85%8D%E7%BD%AE%E6%A1%88%E4%BE%8B%E8%AF%A6%E8%A7%A3(%E4%B8%80)-%E5%87%86%E5%A4%87%E7%AF%87

**Comment by ted423** [comment]
> 对于九键、十四键等，官方早有敎程，原理相同：https://github.com/osfans/trime/wiki/%E4%BA%94%E7%AC%94%E5%8F%8C%E9%94%AE%E9%85%8D%E7%BD%AE%E6%A1%88%E4%BE%8B%E8%AF%A6%E8%A7%A3(%E4%B8%80)-%E5%87%86%E5%A4%87%E7%AF%87

略微复杂了一些

**Comment by Bambooin** [comment]
@ted423 
可以尝试使用 https://github.com/osfans/trime/issues/377
