### ISSUE TITLE
[讨论]关于一键下载方案功能

### ISSUE THREAD

**Issue by laubonghaudoi** [osfans/trime#287]
目前iRime已经实现了方案一键下载部署功能，在方案列表中选择方案即可一键下载使用。但是iRime采用的是中心化管理方式，即所有方案都必须先PR到其集中式[仓库](https://github.com/jimmy54/iRime-Resource)中，才能在手机中下载使用。此方式优点是实现简单，且方便输入法软件作者管理。但缺点是如果一个方案有更新，每次都需要作者另外手动PR到集中式仓库中，增加了复杂性也延迟了更新发布速度。

关于方案的管理方式，我曾与佛振在此[#336](https://github.com/rime/home/issues/336)中讨论过，并总结出一套分布式的方案管理方法。请问同文输入法若实现此一键下载方案的功能，将使用何种方案管理方式？

**Comment by JieHao258** [comment]
厉害了

**Comment by Bambooin** [comment]
有可以定制化的配置，但是现在没有一键下载功能

https://github.com/Bambooin/rimerc
