### ISSUE TITLE
配置时间很长  导致anr 和 切换输入法失败

### ISSUE THREAD

**Issue by Laurtiv27** [osfans/trime#288]
![a](https://user-images.githubusercontent.com/18495569/56119343-8a396700-5f9e-11e9-8d4e-679c221c6977.png)

```
|->assets
   |->rime
       |->opencc
       |->rime/default.yaml
       |->rime/essay.txt
       |->rime/key_bindings.yaml
       |->rime/luna_pinyin.dict.yaml
       |->rime/luna_pinyin.schema.yaml
       |->rime/luna_quanpin.schema.yaml
       |->rime/punctuation.yaml
       |->rime/symbols.yaml
       |->rime/tongwenfeng.trime.yaml
       |->rime/trime.yaml
```

我在`assets` 文件夹 中添加了一些文件, 生成apk后, 第一次启动生成一些配置文件的时候, 时间花的很长。会导致anr,并且在设置里切换输入法的时候会长时间没有响应...。我想是因为这种行为的原因吗？还是有其他原因？ 或者您可以提供某些优化的方式吗？

**Comment by clunyes** [comment]
> ![a](https://user-images.githubusercontent.com/18495569/56119343-8a396700-5f9e-11e9-8d4e-679c221c6977.png)
> 
> ```
> |->assets
>    |->rime
>        |->opencc
>        |->rime/default.yaml
>        |->rime/essay.txt
>        |->rime/key_bindings.yaml
>        |->rime/luna_pinyin.dict.yaml
>        |->rime/luna_pinyin.schema.yaml
>        |->rime/luna_quanpin.schema.yaml
>        |->rime/punctuation.yaml
>        |->rime/symbols.yaml
>        |->rime/tongwenfeng.trime.yaml
>        |->rime/trime.yaml
> ```
> 
> 我在`assets` 文件夹 中添加了一些文件, 生成apk后, 第一次启动生成一些配置文件的时候, 时间花的很长。会导致anr,并且在设置里切换输入法的时候会长时间没有响应...。我想是因为这种行为的原因吗？还是有其他原因？ 或者您可以提供某些优化的方式吗？

怎么解决的呢
