### ISSUE TITLE
錯誤提醒

### ISSUE THREAD

**Issue by szc126** [osfans/trime#289]
想執行部署的時候又會莫名其妙地閃退，想選方案的時候又會叫我「放入default.yaml」，至少要寫個錯誤日誌吧_(:3」∠)_

**Comment by Bambooin** [comment]
可以试试这个已经配置好的配置

https://github.com/Bambooin/rimerc

部署时，需要时间较长，耐心等待。

**Comment by szc126** [comment]
emm，不是……問題是我自己在搞 schema 或者 trime.custom.yaml 的時候，如果有格式問題的話，Trime 就會閃退。但我卻無法知道 yaml 裏其實是有問題的。
