### ISSUE TITLE
Cannot setup the Chinese IME, default.yaml missing

### ISSUE THREAD

**Issue by marmistrz** [osfans/trime#292]
/edit: please see the second post for the solution/actual bug report

I tried following (as far as I understand them) the instructions in [here](https://github.com/osfans/trime/wiki/UserGuide) and [here](https://forum.f-droid.org/t/typing-chinese-with-trime/5961)

I cloned the rime/plum repository and executed `make` on my Linux machine. It created the folder output, containing the following files:
```
bopomofo_express.schema.yaml  cangjie5.dict.yaml            default.yaml       luna_pinyin.dict.yaml            luna_pinyin_simp.schema.yaml  punctuation.yaml    symbols.yaml
bopomofo.schema.yaml          cangjie5_express.schema.yaml  essay.txt          luna_pinyin_fluency.schema.yaml  luna_pinyin_tw.schema.yaml    stroke.dict.yaml    terra_pinyin.dict.yaml
bopomofo_tw.schema.yaml       cangjie5.schema.yaml          key_bindings.yaml  luna_pinyin.schema.yaml          luna_quanpin.schema.yaml      stroke.schema.yaml  terra_pinyin.schema.yaml
```

Btw. is there any way to install default.yaml and the schemas directly on the phone?

**Comment by marmistrz** [comment]
It appears that TRIME doesn't rescan the /sdcard/rime directory until the keyboard is enabled. After I enabled TRIME as the current input method, the keyboard was completely unusable for some time and I was unable to switch to any other keyboard

**Comment by xiaoxiaocainiao** [comment]
same issues, mac book pro , 10.14.5

**Comment by Bambooin** [comment]
Maybe you can follow this guide for you phone.

https://github.com/Bambooin/rimerc

Translate it using Google for understanding.

**Comment by Bambooin** [comment]
> It appears that TRIME doesn't rescan the /sdcard/rime directory until the keyboard is enabled. After I enabled TRIME as the current input method, the keyboard was completely unusable for some time and I was unable to switch to any other keyboard

The rime is deploying data, so your trime app is unresponsible, just wait for minutes.

**Comment by marmistrz** [comment]
@Bambooin it would be nice to display some notification, so that the user doesn't have to guess.
