### ISSUE TITLE
底部导航栏颜色适配

### ISSUE THREAD

**Issue by monologconnor** [osfans/trime#293]
如谷歌输入法在使用时 底部导航栏与输入法界面都为白色 更有一体感
![Screenshot_20190603-235734](https://user-images.githubusercontent.com/38450642/58807745-06296480-865c-11e9-979d-fe48f065f8f3.png)
![Screenshot_20190603-235724](https://user-images.githubusercontent.com/38450642/58807778-14778080-865c-11e9-9697-edab6cd7c6a1.png)
不知能否让输入法根据配色方案自适配或由用户选择导航栏颜色?

开发辛苦了

**Comment by junyixu** [comment]
奇怪，我的是白的，在用 termux 的时候，底栏是白的很刺眼，希望能选择黑的

**Comment by Bambooin** [comment]
可能需要适配不同 Andorid 版本

**Comment by tumuyan** [comment]
使用透明的背景图可能可以解决这个问题.  
截图是个测试皮肤,候选词栏上半部分是透明,下半部分是白色,开关系统深色模式效果的对比  

![Screenshot_2021-07-31-10-16-05-334_mark via](https://user-images.githubusercontent.com/3126801/127725741-2dc1cd94-507f-4cab-888e-b9ba1503931f.jpg)
![Screenshot_2021-07-31-10-16-16-991_mark via](https://user-images.githubusercontent.com/3126801/127725750-32890f9e-0b35-4ea7-898b-5cf09d8e5e09.jpg)

**Comment by junyixu** [comment]
@tumuyan 你这个是全面屏，没有系统导航栏啊
![Screenshot_20210801-224723_1](https://user-images.githubusercontent.com/40481594/127775217-f0d1227a-4aa5-4c17-9248-8ee92d3460c4.jpg)

**Comment by tumuyan** [comment]
我不知道是不是手机差异,我使用透明背景后,即使用传统三大金刚键,依然是自适应的,哪怕截图中qq都没有切换到暗色.
![Screenshot_2021-08-02-00-26-35-291_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/3126801/127778370-1d87e215-7296-4731-9b7c-711d97a175c8.jpg)
![Screenshot_2021-08-02-00-26-47-716_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/3126801/127778364-ad549bf4-8c5e-4e6d-8c50-958482cbc53c.jpg)

**Comment by junyixu** [comment]
我在 google play 上搜 navbar，然后出来一串类似的 app，随便选了一个，把 navigation bar 调成黑的了(我的输入法主题是黑的)
