### ISSUE TITLE
How to switch between installed schemas on android?

### ISSUE THREAD

**Issue by yunlhan** [osfans/trime#294]
Hello, on desktop version, we can press `ctrl+'` or `f4` then from the drop down list switch between different input schemas, say, pinyin <-> wubi. 

What's the equivalent key combination of `ctrl+'` for mobile trime on android? Is there a preset key or do I have to define it myself? Thanks.

**Comment by Bambooin** [comment]
Launch Trime app, select Input --> Schemas, then you can select your installed schemas.

Don't forget deploy it after you change your schema.

**Comment by yunlhan** [comment]
@Bambooin Thank you! That was something I tried. It works great for enabling just one schema at a time. What I meant was, e.g., enabling both pinyin and wubi, and switch between the two on the fly. One such occasion is, I share my phone with my parents and they use wubi, I use pinyin.

**Comment by osfans** [comment]
@yunlhan 长按左下角的按键，上方是“菜单”。
