### ISSUE TITLE
无法用简体输入

### ISSUE THREAD

**Issue by wangnan789** [osfans/trime#296]
trime-20170803 和trime-20181217这两个版本无法用简体输入，我使用的手机是vivo，安卓7
另外能否添加9宫格键盘，手机使用全键盘的按键太小了

**Comment by luhux** [comment]
rime没有九宫格拼音的方案

**Comment by Bambooin** [comment]
@cws999 可以试试这个配置文件 
 https://github.com/Bambooin/rimerc

**Comment by Bambooin** [comment]
另外 最新版，可以在这里下载。

https://github.com/osfans/trime/blob/gh-pages/release/app-release.apk
