### ISSUE TITLE
使用trime無法識別輸入方案

### ISSUE THREAD

**Issue by Reniastyc** [osfans/trime#297]
機型是小米Mix2，查到路徑是/storage/emulated/0/rime/，但修改用戶文件夾路徑，並複製配置文件後，無法正確識別。請問應如何處理？

**Comment by Bambooin** [comment]
参考如下配置文件步骤：

https://github.com/Bambooin/rimerc

**Comment by cognition9144** [comment]
并非无法识别，原因是没有生成 build 文件夹（https://github.com/osfans/trime/issues/334 ）

暂时需要手动「恢复默认设置」，生成 build 文件夹。

最终需要#287

**Comment by Bambooin** [comment]
@Reniastyc 
试试最新的 apk https://github.com/osfans/trime/tree/gh-pages

另外配置文件可以参考 https://github.com/Bambooin/rimerc
