### ISSUE TITLE
Full steps to install and make TRIME work on my Android phone

### ISSUE THREAD

**Issue by Susolina** [osfans/trime#299]
I have been trying to install TRIME and make it work on my android phone since hours, it is the pain in the axx to not have a clear guideline. As I am not a greek in programming so I have spent several hours to do reading and trying, finally, it works!  So I share the steps here, hope this post can help other users to save time.

To install TRIME on your Android and make it usable, you need to do the following:

After having downloaded TRIME and installed it (Version 3.1.2 (20181224) which is the latest version on F-Droid at them moment).

The first thing you need to do is installing RIME Ibus on your Linux machine by following the steps below (the information is from this page https://github.com/rime/home/wiki/RimeWithIBus).

1) Install Rime Ibus - 

Sudo add-apt-repository ppa:fcitx-team/nightly
sudo add-apt-repository ppa:lotem/rime
sudo apt-get update
sudo apt-get install ibus-rime

2) Install the input method of your choice (in here I take Cangjie as an example, see the list of available input methods https://github.com/rime/home/wiki/RimeWithIBus) -

sudo apt-get install librime-data-cangjie5

3) Copy all the file inside the folder indicated below (more information see this post https://forum.f-droid.org/t/typing-chinese-with-trime/5961) -

/usr/share/rime-data/

In the "rime-data" folder, you should see the following files:
cangjie5.dict.yaml            cangjie5.schema.yaml   luna_pinyin_fluency.prism.bin    luna_pinyin_simp.prism.bin    symbols.yaml
cangjie5_express.prism.bin    cangjie5.table.bin     luna_pinyin_fluency.schema.yaml  luna_pinyin_simp.schema.yaml
cangjie5_express.schema.yaml  default.yaml           luna_pinyin.prism.bin            luna_pinyin.table.bin    cangjie5.prism.bin            essay.txt              luna_pinyin.reverse.bin          luna_pinyin_tw.prism.bin    cangjie5.reverse.bin          luna_pinyin.dict.yaml  luna_pinyin.schema.yaml          luna_pinyin_tw.schema.yaml

4) Use an usb cable to connect your phone with your Linux, and paste all of the file (locate in the folder indicated above) into a temporal folder (whatever folder that you will able to find it inside your cell phone).
Once you disconnect your phone from the computer, go to find these file then copy them into the following folder inside your phone:

/storage/emulated/0/rime

P.S. You can also copy these files directly from Linux to the above folder by using ADB.

5) On your cell phone, launch TRIME, go to its setting, select “Change Keyboard” then select “Trime”. Then select “Deploy” then select “trime.yaml” then wait with patience until it says deployment successful.

P.S. if you don’t do all of these above, TRIME will be useless after the installation and it will claim that the default.yaml is missing (see also https://github.com/osfans/trime/issues/292).

**Comment by Bambooin** [comment]
Maybe you can try this config file 

https://github.com/Bambooin/rimerc

using Google translator.
