### ISSUE TITLE
长按退格键后，再长按其他键变为连续短按

### ISSUE THREAD

**Issue by harrysummer** [osfans/trime#30]
重现方法：
1. 9月30日版本，默认配置、中文、半角、汉字；
2. 在一个空文本框长按退格键直到Preview层消失；
3. 长按任意键（如a键，或上档键，或中英文切换键，或数字键盘切换键），观察异样

**Comment by harrysummer** [comment]
git df02251 版本编译运行已无此问题，建议关闭

**Comment by osfans** [comment]
好像還有問題的。
