### ISSUE TITLE
屏幕方向切换时，软键盘显示不全

### ISSUE THREAD

**Issue by luhux** [osfans/trime#300]
竖屏切换横屏时，横屏切换竖屏时，键盘不会自动调整长度

**Comment by fly6** [comment]
我也出現過，不過再來回切換一兩下就好了。是bug沒錯

**Comment by tumuyan** [comment]
这个问题目前可能也不存在了。横竖屏是两个布局，切换屏幕状态时会强制重新加载键盘。
