### ISSUE TITLE
知乎app上搜索框打字丢失光标

### ISSUE THREAD

**Issue by omgredfog** [osfans/trime#301]
复现率100%，其实不止知乎app这一个软件中有此情况，
很多软件中使用trime，都会在按一次键后，丢失光标，
需要重新放一下光标进去，才能继续打字。
原因不明。

**Comment by kitty-panics** [comment]
补充一下我的情况。
在知乎 APP 的搜索框中输入 英文/字母 后，搜索框的焦点丢失。

知乎版本：6.14.1
同文版本：3.1.3-20190930（至少在上三个版本中可复现此问题）

示例视频下载地址：
[https://pan.baidu.com/s/1Xs0voL9SlAlHn6G4ogoy_A](https://pan.baidu.com/s/1Xs0voL9SlAlHn6G4ogoy_A)

**Comment by monologconnor** [comment]
这边也遇到了同样的问题, 输入框经常会消失, 然后不知道因为什么又会重新出现, 反反复复的

**Comment by Bambooin** [comment]
Fix in #462
Daily build can be found for test and verify
https://github.com/osfans/trime/actions
