### ISSUE TITLE
候选项长度超出屏幕显示范围

### ISSUE THREAD

**Issue by fly6** [osfans/trime#303]
终于下决心好好调整下外观，不过始终没能把候选项长度调整成功：目标是希望候选项的长度若超过屏幕宽度，就自动调整到下一页，然后通过两侧的左右箭头来选取。试过layout下面的max_width, max_length都不行啊。
另外现在默认候选项是5项，把max_entries改成8也无法显示更多，请问如何调整？

**Comment by llpub** [comment]
确实，trime现在最急需解决的应该就是UI问题了，候选栏里的条目不能自适应屏幕宽度，而且也不能像其它现代安卓输入法一样把候选栏下拉显示更多候选项。这十分影响效率和输入体验。
如果能设计一个现代的UI，trime将秒杀baidu、搜狗。

**Comment by Bambooin** [comment]
类似的问题 #399 #366 

sticky_lines: 固顶行数（不与其它候选同排，单独一行显示的候选项个数）
max_entries: 最大词条数（允许进入悬浮窗的最大词条数）
all_phrases: 显示所有长词。所有满足min_length的词条都显示在悬浮窗（一般只用于table translator，有可能会改变候选项的显示顺序）

这个 wiki 里面有详细介绍

https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3
