### ISSUE TITLE
[分享]自用的简洁UI主题

### ISSUE THREAD

**Issue by heiher** [osfans/trime#304]
分享个自用的简洁UI主题，为提升触屏输入效率优化了键位布局，简化了符号表。虽是为郑码方案准备的，但应该也同样适用于其它形码方案。欢迎共同改进。

下载链接：[trime.yaml](https://raw.githubusercontent.com/heiher/trime/develop/app/src/main/assets/rime/trime.yaml)

![IMG_20191011_110740](https://user-images.githubusercontent.com/1407733/66627028-faaf0100-ec2c-11e9-9929-bf70bc7fde7a.jpg)
![IMG_20191011_110723](https://user-images.githubusercontent.com/1407733/66627042-fedb1e80-ec2c-11e9-9bb9-a747e8d7059a.jpg)
![IMG_20191011_110703](https://user-images.githubusercontent.com/1407733/66627048-013d7880-ec2d-11e9-93ed-4453cf57af94.jpg)
![IMG_20191011_110634](https://user-images.githubusercontent.com/1407733/66627056-06022c80-ec2d-11e9-9289-371991b0e6ec.jpg)

**Comment by fly6** [comment]
好久沒見到鄭碼了，不知道幾年前就說的新版出來了嗎？有的話我還想再回去試試。
拿回來研究一下爲什麼我的上滑鍵有些符號缺失了，謝謝啦！

**Comment by heiher** [comment]
> 好久沒見到鄭碼了，不知道幾年前就說的新版出來了嗎？有的話我還想再回去試試。

是说郑码输入法方案有新版本？

> 拿回來研究一下爲什麼我的上滑鍵有些符號缺失了，謝謝啦！

TRIME中滑动输入没成功过，后来我都删掉了这些配置。

**Comment by fly6** [comment]
是的，我現在已經不記得具體名字是什麼了。當時用的輸入方案是什麼也不太記得了，只是覺得有幾個跟規則不合，有點難受，就換了。

默認的trime.yaml可以上滑輸入數字啊。
