### ISSUE TITLE
如何禁用自动弹出成语？或者相关设置名称是什么？

### ISSUE THREAD

**Issue by sgqy** [osfans/trime#305]
打字时基本只看固定位置，凡是出现在最左侧的必然会按空格上屏。
有时突然弹出一个成语根本反应不过来，结果就错词了。
如何关闭这个功能？
![Screenshot_2019-10-13-13-18-19-328_com rhmsoft edit pro](https://user-images.githubusercontent.com/4893302/66711400-8bb4e200-edbd-11e9-9672-38b5d229e22a.jpg)
如图，欲输入「日文」，结果上屏「时时刻刻」，这在短时间内根本不知道已经打错字了。

另：「同文风」、「搜狗」中有此功能，「默认」无此功能。

**Comment by Bambooin** [comment]
词库里面由的话，就会出现，可以把词库的成语剔除
