### ISSUE TITLE
希望可以增加简洁的暗色颜色方案方便夜间打字

### ISSUE THREAD

**Issue by DuoPsychosis** [osfans/trime#308]
目前的暗色颜色方案霓虹、入梦等都有点花里胡哨，喜欢谷歌拼音输入法那类，但内置的只有白色的，且风格其实也没有很谷歌，其实入梦那款如果没有背景图，还挺接近谷歌的。

**Comment by luhux** [comment]
你可以自己写一个配色

**Comment by Bambooin** [comment]
试试  **孤寺** 这个配色，一直使用的这个，白天和夜晚都不错，暗色配置。

方法： 打开应用-->键盘-->配色-->孤寺

如果这个配色不喜欢，尝试其他配色，应该还有暗色的配色，可选。
