### ISSUE TITLE
在很多个app中不时无法使用

### ISSUE THREAD

**Issue by DuoPsychosis** [osfans/trime#309]
点按键盘无反应，且很卡。已知有微信、滴答清单等

**Comment by li9769006** [comment]
同问，非常影响使用。

**Comment by Bambooin** [comment]
希望提供更准确的复现场景和步骤，目前没有遇到过，

**Comment by ghost** [comment]
我是小米5s，刷机root，装了面具和太极，但我觉得这些应该不是问题。真正成问题的是当打开任何一个app ，用同文输入时，总是在输入几个词语后，键盘就消失了，点输入框没反应，要过一会儿，再点输入框，这时键盘又出现可以输入了。如果不输入任何词语，过一段时间，键盘也会消失。
在安装旧版 同文输入法-com.osfans.trime-v3.0.1-20170210.apk 后，问题还是这样。
MIUI 10 8.10.29 skymi 特别版 ， Android 8.0.0
同文版本：  3.1.3-20190930

**Comment by Bambooin** [comment]
@hjonline 请使用最新版，验证一下。

https://github.com/osfans/trime/tree/gh-pages

@DuoPsychosis @zhang5389 一直没有遇到这种情况，可以使用最新版验证一下
