### ISSUE TITLE
请在用户文件夹中放入default.yaml、输入法方案！

### ISSUE THREAD

**Issue by clunyes** [osfans/trime#311]
这些配置是在哪里呢？

**Comment by Bambooin** [comment]
可以试试可以直接使用的配置文件

https://github.com/Bambooin/rimerc

**Comment by daniel-zou** [comment]
在手机没有SD卡的情况下，无法输入中文，安装文件有缺失。手机只有内部存储，默认用户文件夹/sdcard/rime，手动改成/storage/emulated/0/rime，也不行，没有输入方案。总提示：请在用户文件夹中放入default.yaml、输入法方案！

**Comment by tournet** [comment]
遇到同样的问题，google play版的、github版的均不行，github 3.25版的还闪退。
