### ISSUE TITLE
在Vivo x7上老是崩溃，而且不显示键盘

### ISSUE THREAD

**Issue by AkarinLiu** [osfans/trime#313]
![Uploading 超级截屏_20191122_231520.png…]()

**Comment by Bambooin** [comment]
先下载最新版Trime https://github.com/osfans/trime/tree/gh-pages

然后试试可以直接使用的配置文件

https://github.com/Bambooin/rimerc

确认是否复现该问题。

另外无法看到你的截图，截图是否上传正确？

**Comment by AkarinLiu** [comment]
还是一样，没解决，希望能与vivo取得联系，解决这个问题。

**Comment by AkarinLiu** [comment]
另外想发图片给你，你的电子邮箱是？

**Comment by AkarinLiu** [comment]
我的手机是Vivo x7 ，系统是基于安卓5.1.1的FuntouchOS 3 Lite。这个问题持续了很久，希望作者能及时修复。

**Comment by Bambooin** [comment]
> 另外想发图片给你，你的电子邮箱是？

这个没有及时看到你的回复，截图的效果不是很理想。

最好的方法是使用logcat 抓取当时的log，以文本的形式，在这里附件添加。
有了log就很容易定位到问题。

PS: 这个手机的Android版本有点老旧了，兼容性和手机的流畅度可能不是很好了
是否可以考虑 更换支持 LineageOS 的新设备，系统兼容性应该会更好。

**Comment by AkarinLiu** [comment]
LOG文件内容：
————————————————————
2020/03/04-15:26:04.272854 7fa5589e80 Recovering log #62
2020/03/04-15:26:04.295820 7fa5589e80 Delete type=0 #62
2020/03/04-15:26:04.295913 7fa5589e80 Delete type=3 #61

**Comment by Bambooin** [comment]
logcat 的崩溃日志，保存成.txt，并以附件的形式提交，由于日志太大，最好不好直接粘贴在这里，保存成附件。

这个机型和android 版本，没法调试和验证，只能尽量解决。
