### ISSUE TITLE
无法完全独立完成部署

### ISSUE THREAD

**Issue by ivysrono** [osfans/trime#315]
Trime 3.1.3
Android 10.0
在 Win 上，我们可以在没有 `build` 文件夹的情况下完成部署。
在 Android 上，在用户文件夹下的相关自定义配置文件之外，还必须事先将在 PC 上已经部署生成的 `build` 文件夹下 `default.yaml` 和 `方案.schema.yaml` 放置到 Android 的 `build` 文件夹下，否则 Trime 无法读取方案，无法完成部署，会闪退。
经搜索发现类似报告：#266 #297

**Comment by zbinlin** [comment]
确实，在 Linux 下可以使用 default.custom.yaml 就可以了，好像在 Android 下不行，必须要 default.yaml

**Comment by Bambooin** [comment]
参考如下配置文件步骤：

https://github.com/Bambooin/rimerc

**Comment by zbinlin** [comment]
@Bambooin 你这个 repo 里并没有解答到这个 Issue 提出的问题。

**Comment by Bambooin** [comment]
@zbinlin 最新的版本的Trime，首先把以前的rime 文件夹重命名，unrime。

进入Trime-->输入-->重置-->勾选所有选项-->返回Trime-->部署

使用这个流程发现没有问题，可以部署。不过由于默认的没有输入方案，无法输入中文而已。

**Comment by Bambooin** [comment]
这个步骤操作下来，build目录没有default.yaml，依然可以使用，不过无法输入中文。

**Comment by zbinlin** [comment]
> 这个步骤操作下来，build目录没有default.yaml，依然可以使用，不过无法输入中文。

嗯，也就是说，如果没有 default.yaml 是无法正常使用中文？

**Comment by Bambooin** [comment]
default.yaml 和 方案.schema.yaml应该是输入方案，放在rime目录的。
rimerc里面有，部署的时候，会复制到build目录。
build目录里面不应该手动放置配置文件。
下次部署可能会覆盖build里面的东西。

**Comment by ivysrono** [comment]
这是中文输入法，不能输入中文怎么会被认为是成功呢？
我也知道不应该把文件放到build目录，问题是不放进去就不能正确生成。
现在放进去就是为了部署的时候被覆盖啊！
恕我理解不能，这不是Bug是feature？

**Comment by zbinlin** [comment]
@ivysrono `default.yaml` 可以放 build 目录的上一级（即 trime 目录下），但不能没有。

**Comment by Bambooin** [comment]
@ivysrono 希望还是直接使用 https://github.com/Bambooin/rimerc 的配置文件
Trime内置的目前无内置输入方案，所以手动需要添加，不过酷安市场上打包的好像内置了输入方案。
对于初次使用，还是建议直接复制别人整理好的配置文件，简单易用，词库还很大，很全。

**Comment by cognition9144** [comment]
> @ivysrono 希望还是直接使用 https://github.com/Bambooin/rimerc 的配置文件
> Trime内置的目前无内置输入方案，所以手动需要添加，不过酷安市场上打包的好像内置了输入方案。
> 对于初次使用，还是建议直接复制别人整理好的配置文件，简单易用，词库还很大，很全。

Clean install trime + rimerc 是无法正常使用的，因为 rimerc 不提供 `./build`，但有提供`default.yaml`。

> 进入Trime-->输入-->重置-->勾选所有选项-->返回Trime-->部署

用这个方法重置之后会包含 build 词库的程序，所以会生成 `./build`，之后就可以用了。可以在从重置之前/之后覆盖 rimerc。

这个操作完全可以省却。build 词库的过程应当检查 `./build` 是否存在。
