### ISSUE TITLE
B站输入弹幕问题

### ISSUE THREAD

**Issue by ghost** [osfans/trime#317]
输入法在B站上输入弹幕的时候没有备选栏，不知道这个能不能修复一下。

**Comment by c4dr01d** [comment]
这是截图

**Comment by ldcTnT** [comment]
将candidateView放到input.xml中，把onCreateCandidatesView中初始化candidate的逻辑放到onCreateInputView中，不使用onCreateCandidatesView方法就可以了

**Comment by Bambooin** [comment]
@ldcTnT 可以提供修复的PR

**Comment by Bambooin** [comment]
#306 一样的问题

**Comment by Bambooin** [comment]
#301 类似

**Comment by WhiredPlanck** [comment]
> 将candidateView放到input.xml中，把onCreateCandidatesView中初始化candidate的逻辑放到onCreateInputView中，不使用onCreateCandidatesView方法就可以了

这个可以有。据我所知，很多商业中文输入法（搜狗等）也是这样弄的。晚些时候来试试看。

**Comment by tumuyan** [comment]
@Bambooin 这个已经可以close了,之前在 #462  中使用 @ldcTnT 的解法解决了这个问题

![Screenshot_2021-08-31-16-43-01-617_tv danmaku bili](https://user-images.githubusercontent.com/3126801/131471807-12053d2c-ae85-4ce2-8d8d-41ca33dc0c21.jpg)

**Comment by Bambooin** [comment]
Daily build can be found for test and verify
https://github.com/osfans/trime/actions
