### ISSUE TITLE
在夸克浏览器中打字卡顿

### ISSUE THREAD

**Issue by Daedemons** [osfans/trime#318]
在夸克浏览器主界面打字非常卡顿，经常两三秒才能反应过来，其他输入法无此问题，详情见图
![夸克](https://user-images.githubusercontent.com/54841793/71708139-ff4d1500-2e29-11ea-84df-92f77f5ccd17.gif)
机型为realme x，android9.0

**Comment by Daedemons** [comment]
![夸克](https://user-images.githubusercontent.com/54841793/71708270-07f21b00-2e2b-11ea-9b64-00a2e17ad805.gif)

**Comment by Bambooin** [comment]
Daily build can be found for test and verify
https://github.com/osfans/trime/actions
