### ISSUE TITLE
文本选择功能

### ISSUE THREAD

**Issue by youweimiao** [osfans/trime#32]
这是个非常好的输入法，我使用过程中发现几个问题。
我用的是emui3.1系统，同文20151030。

从数字键盘切换回字母键盘不能记住原来字母中英文状态，虽然可以用2套字母、数字键盘解决，不过每个输入方案定义2套键盘比较麻烦。

如果一个按键比较长，点击这个按键的两侧无作用。

希望实现文本选择功能，先按 ”选择“ 然后通过 上下左右 方向键选择文本。

**Comment by osfans** [comment]
確實有這些問題，記下了。多謝！

**Comment by zaqzrh** [comment]
@osfans
Trime的文本编辑㘦能，“全选”选定全文本，
真希望文本能通过 “选择”加 ↑←↓→方向键选择“部分”文本功能。

**Comment by osfans** [comment]
按键的两侧无作用、文本选择功能這兩個應該還是要解決，所以沒有關。

**Comment by xiaoqun2016** [comment]
总结了一下跟输入法有关的功能：  
- [ ]  双击 （主要是shift键）  
- [ ]  长按候选（删词……）  
- [ ]  长按按键更多符号（a→ā á ǎ à A @）  
- [ ]  可触摸的按键间隙  
- [ ]  可展开的候选列表  
- [ ]  可翻页的符号面板  
- [ ]  可自由定义的状态栏  
- [ ]  语音输入界面  
- [ ]  单手模式 & 横屏布局  
- [ ]  双拼、三拼键盘  
- [ ]  编辑面板（↑↓←→选择……）
- [ ]  联想（主要靠librime）  
- [ ]  云词库  
- [ ]  九宫格 & 邻键纠错  
- [ ]  手写键盘 & 全键盘手写 & 笔划筛选  
- [ ]  图形配置界面

**Comment by osfans** [comment]
樓上的全

**Comment by xiaoqun2016** [comment]
补充了一下。  后面几项估计很难。

**Comment by osfans** [comment]
add7ca4a8eeb3f379fc9e2d30d000ff6c0bfdbff 解決按键的两侧无作用的問題

**Comment by osfans** [comment]
中英文状态應該也好了。

**Comment by osfans** [comment]
文本選擇在 #147 追蹤。
