### ISSUE TITLE
可以在指定的应用内默认为英（西）文输入状态吗？

### ISSUE THREAD

**Issue by 4SM** [osfans/trime#321]
例如，在Play商店，搜索弹出键盘后，默认状态是西文。（小狼毫可以这么做：在指定的程序下是英文状态）

**Comment by zoenglinghou** [comment]
似乎可以將 `reset_ascii_mode` 設爲 `true` 來記憶當前進程的中西文狀態，不過並不是你的需求

**Comment by Bambooin** [comment]
#500
