### ISSUE TITLE
能否實現讓鍵盤按鍵只有部分區域有效

### ISSUE THREAD

**Issue by iosonoungatto** [osfans/trime#324]
單手輸入的時候很容易誤觸鍵盤最邊緣的按鍵，十分影響輸入。我知道可以直接把最邊緣的按鍵的寬度減少再加上空白區域，不過這樣不太好看。有沒有可能做到讓鍵盤按鍵只有部分區域有效，比如說一個按鍵顯示出來的圖案寬度為10，但是只有按住它的左半邊寬度為5的時候按鍵才有效，這樣既美觀又可以防止誤觸。

**Comment by Bambooin** [comment]
把最邊緣的按鍵的寬度減少再加上空白區域

曲面屏幕的用户这样解决的
