### ISSUE TITLE
請問有「字詞建議」功能嗎？

### ISSUE THREAD

**Issue by bilinare** [osfans/trime#325]
就是像Gboard一樣，輸入一個字後會出現建議字詞在候選欄的功能。
例如輸入「感」後，候選欄會出現「覺 謝 到 情 受……」

**Comment by linkral** [comment]
似乎有个渐次提醒功能可以实现部分这样的情况，候选栏可能会是感觉 感谢 感到 感情 感受之类的，前提是词库也要做相应的调整。

**Comment by Bambooin** [comment]
目前无法实现该功能
