### ISSUE TITLE
Android 6.0 上請求權限

### ISSUE THREAD

**Issue by syu-id** [osfans/trime#33]
切換到同文輸入平臺輸入法就立即崩潰

環境：Android 6.0, Nexus 5

**Comment by osfans** [comment]
http://tieba.baidu.com/p/3917536050?pid=78555968788#78555968788
貼吧上有討論。

系统未给予trime任何权限，需要手动把权限开启，然后就可以正常使用了 
以後會做个提示，提醒用户开启相应的权限

![權限](http://imgsrc.baidu.com/forum/w%3D580/sign=36a01e7ecfea15ce41eee00186013a25/d668a6d6277f9e2f32936df31930e924ba99f38e.jpg)

**Comment by syu-id** [comment]
多謝！
開啓權限後實測 trime-20150902.apk 可以正常使用。
然而此後的 apk 則依然崩潰，在配置程序中執行「部署」也會導致配置程序意外關閉。

**Comment by osfans** [comment]
那可能要把rime文件夾刪掉重新來？

**Comment by syu-id** [comment]
開啟權限+重建rime文件夾後能夠使用了。
多謝！

Eric
2015/11/06 午前11:27 "Osfans" notifications@github.com:
