### ISSUE TITLE
[Feature Request] 设备内置硬件键盘环境下的输入法状态条自定义能力

### ISSUE THREAD

**Issue by SuperMarioSF** [osfans/trime#330]
Hello

目前想要实现自定义的物理键盘模式的状态条，在状态条上增加符号输入面板按钮和编辑面板按钮，但没能找到能实现的方法。

有一些硬件键盘的手机没有独立的 `Sym` 符号按键，无法调出符号输入面板，这就导致了键盘上没有的符号输入起来就必须换输入法才行；很多带有硬件内置全键盘的手机也没有方向键控制，没有编辑面板时候这就导致文字编辑比普通触摸屏手机还麻烦。

因此请求增加有关这个硬件键盘激活时的状态条的相关配置能力。

Thanks

![硬件键盘状态条在底部](https://user-images.githubusercontent.com/13301406/75660414-b50bd700-5ca6-11ea-92c0-fafd2066e0d0.png)

* * *

一些题外话。

我的手机是Unihertz Titan，这个手机的功能按键只有Shift和Alt，没有方向键也没有Sym按键。但类似的需求在其他型号手机上可能也是存在的，例如 #236 (Key2是没有方向键)

已经尝试过使用其他输入法。
 - Gboard/Google拼音 虽然能用Alt单击替代Sym键功能，但全角中文符号输入不能用。
 - 系统内置的Kika输入法虽然有直接把符号放在了状态栏，但功能自定义选项少得可怜，甚至不支持关闭英文的补全和联想功能。
 - TRIME在自定义能力上完全没问题，并且也没有Gboard输入不了全角字符的问题，但符号输入成了一个大问题，键盘上没有的符号输入起来就很困难。

**Comment by InfinityLoop1308** [comment]
Might be implemented by modify the switches of your schema.
