### ISSUE TITLE
請問同文輸入法能兼容android10嗎？

### ISSUE THREAD

**Issue by ZikangPang** [osfans/trime#331]
昨天我的華爲榮耀8x更新到了emui10.0.0，隨後同文輸入法總是在進行部署時崩潰。

**Comment by Bambooin** [comment]
可以兼容，需要使用最新版本。


可以參考這個信息：
https://github.com/osfans/trime/issues/298#issuecomment-534056200

**Comment by ZikangPang** [comment]
感謝，抱歉添麻煩了
