### ISSUE TITLE
调整键盘大小

### ISSUE THREAD

**Issue by sith-on-mars** [osfans/trime#333]
有办法调整键盘大小吗？我手指比较大，觉得默认的键盘有些小。

**Comment by Jas0nG0ng** [comment]
同求，更改了vertical_gap，height，key_hight都没有任何变化

**Comment by frankisze** [comment]
同求

**Comment by HollowMouse** [comment]
同求

**Comment by SivanLaai** [comment]
> 同求

https://github.com/JaaikoLai/rime_pure 我这里做了几款皮肤，调整了布局，主要为了方便配置

**Comment by Bambooin** [comment]
https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3

这个 wiki 介绍的很详细和全面
