### ISSUE TITLE
[Feature Request] 同步 userdb

### ISSUE THREAD

**Issue by 15cm** [osfans/trime#337]
`Synchronize` 这个按键目前只有单向同步，并不会合并 sync directory 的 userdb 到 trime。希望 trime 也能实现 [同步用戶資料](https://github.com/rime/home/wiki/UserGuide#%E5%90%8C%E6%AD%A5%E7%94%A8%E6%88%B6%E8%B3%87%E6%96%99)。

**Comment by a342191555** [comment]
好像是双向同步的哦

**Comment by Bambooin** [comment]
最新测试版，同步的时候，会把 luna_pinyin.userdb，同步到 /rime/sync/**/luna_pinyin.userdb.txt
luna_pinyin.userdb.txt 这个里面就是用户日常输入的单词，不知道是否满足你的需求。

**Comment by 15cm** [comment]
我当时有疑问的是另一个方向的同步，即把 /rime/sync/**/luna_pinyin.userdb.txt 全部合并到 luna_pinyin.userdb 中。我刚刚测试了一下，如上面 @a342191555 所说，双向同步是工作的。感谢答复。
