### ISSUE TITLE
自定义短语功能,在五筆拼音方案下不能使用

### ISSUE THREAD

**Issue by hjbfa** [osfans/trime#339]
Trime 五笔拼音方案下不能使用自定义短语,
一样的自定义短语添加方法,
在其它方案下可以使用,
相同自定义短语添加方法在小狼毫rime的五笔拼音方案下,
又是正常使用.
唯独在同文的五笔拼音方案下不能使用.
求大大们解决下此问题

我的添加方法是wiki中的:
自定义短语(可选)：存储少量的固定短语等数据。配置步骤：①新建短语翻译器 ②配置翻译器 ③往custom_phrase.txt添加自定义短语 （custom_phrase样例文件 *）

**Comment by MrCorn0-0** [comment]
我在小狼毫下也有這個問題，但是只在一個輸入法裡試過。

**Comment by Bambooin** [comment]
可能是 librime 的问题，可以在 librime 提问
