### ISSUE TITLE
长按时间、震动时间

### ISSUE THREAD

**Issue by huangchengcheng** [osfans/trime#34]
1. 可以调整长按的时间，这样输入符号快一点
2. 加入按键震动，最好震动时间可调

**Comment by osfans** [comment]
長按時間：
https://github.com/osfans/trime/blob/master/assets/rime/trime.yaml#L39

按鍵震動及時間：
https://github.com/osfans/trime/blob/master/assets/rime/trime.yaml#L31

**Comment by huangchengcheng** [comment]
回复神速，非常感谢！原来已经有了，非常抱歉，没有好好研读配置文件。

**Comment by osfans** [comment]
google play上架好像很麻煩，註冊還要錢。不熟悉流程。

**Comment by osfans** [comment]
上架問題在 #28 這裏討論。
那這個問題先關閉了。

**Comment by asdasd1dsadsa** [comment]
> 長按時間： https://github.com/osfans/trime/blob/master/assets/rime/trime.yaml#L39

补充一句，键名称叫做 longpress_timeout，在locale同级。现在的trime.yaml不是位于39行了。
