### ISSUE TITLE
最新测试版 20200330 无法运行

### ISSUE THREAD

**Issue by Rovever** [osfans/trime#342]
机型 Sony Xperia XZ1，系统 Android 9，升级最新测试版后无限提示“停止运行”，卸载重装也没用。

**Comment by Bambooin** [comment]
试试最新的 apk https://github.com/osfans/trime/tree/gh-pages

另外配置文件可以参考 https://github.com/Bambooin/rimerc

**Comment by Bambooin** [comment]
@Rovever 
@zhongweiy

**Comment by Rovever** [comment]
好的，我试试，谢谢啦
