### ISSUE TITLE
ctrl 额外键

### ISSUE THREAD

**Issue by 2939864240** [osfans/trime#343]
![IMG_20200509_001005](https://user-images.githubusercontent.com/37110653/81425148-9c79da80-9189-11ea-8613-962cb110a6c1.jpg)
方便地铁打代码

**Comment by womgit** [comment]
我最想加入的功能是在显示汉字栏里，可以放按键，这个栏又大又占位置，还丑。这可以放十个二十个小按键啊，别白白浪费了，赶紧加

**Comment by Bambooin** [comment]
https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3#%E7%A4%BA%E4%BE%8B%E6%96%B0%E5%BB%BA%E4%B8%80%E4%B8%AA%E5%89%AF%E9%94%AE%E7%9B%98

这个 wiki 介绍的很详细和全面，参考里面有一个副键盘示例
