### ISSUE TITLE
推出电脑版主题编辑器

### ISSUE THREAD

**Issue by isPoto** [osfans/trime#347]
我是trime的忠实用户，没有trime，我可能无法在手机上使用小鹤音形打字，这对于我来说是不能接受的。

不清楚开发者osfans对于主题编辑器的看法如何？

我希望能够参与主题的设计中。但我对于代码可能一时间难以精进，另外，我发现如果我去调整参数，我可能要频繁在编辑代码和效果预览中频频切换。

如果有一款可以在电脑上进行主题设计的工具会不会更好？
- Portable软件。配置可以随软件带到其他电脑上；
- 可视化设计。左边是主题效果预览，右边是参数的调整。其中参数的调整有拖条和一些按钮进行可视化的参数调整。通过可视化来降低设计主题的代码编写方式，降低难度。

**Comment by davidlauhn** [comment]
刚找到一个同文风主题修改工具，Android上的，可惜年代久远，用不了了

**Comment by Bambooin** [comment]
https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3

这个 wiki 介绍的很详细和全面
