### ISSUE TITLE
"Put default.yaml and schema files into user directory!"

### ISSUE THREAD

**Issue by HibGut** [osfans/trime#349]
Sorry for writing English, still learning Chinese. I installed Trime and it only types ABC characters even when switched to 中文. When I try to change the setting I get this error:
![photo_2020-07-02 19 02](https://user-images.githubusercontent.com/7153563/86398796-7747ab00-bca6-11ea-9625-f424f24f3478.jpg)
What do I need to do? Where do I find default.yaml and what are schema files?

**Comment by Bambooin** [comment]
You can find default.yaml and schema files in [Rimerc](https://github.com/Bambooin/rimerc)

Googel translation is good for you to follow the instruction.
