### ISSUE TITLE
开启 Synchronize background (后台同步) soft cursor（^）会自动消失。

### ISSUE THREAD

**Issue by yu-soong** [osfans/trime#352]
如题。一旦开启 Synchronize background，自动同步后，打字时 soft cursor 会自动消失。关闭 Synchronize background，手动同步，就不会发生这个问题。
用的是最新版trime (20200707)，系统是MIUI Global 11.0。
@a342191555

**Comment by a342191555** [comment]
请问能否提供更详细的说明或截图，我没有明白 soft cursor（^）指的是什么。

**Comment by yu-soong** [comment]
谢谢，如下图：
![Screenshot_2020-07-14-19-28-08-329_com yandex browser](https://user-images.githubusercontent.com/43726125/87534341-2e282b80-c696-11ea-92c9-165dc873dc5c.jpg)
![Screenshot_2020-07-15-12-25-39-101_com osfans trime](https://user-images.githubusercontent.com/43726125/87534491-63347e00-c696-11ea-814d-03a8508de2b3.jpg)

**Comment by a342191555** [comment]
感谢提供截图，bug已复现和定位，我会尽快提交一个更新。

**Comment by yu-soong** [comment]
谢谢！

**Comment by Bambooin** [comment]
@a342191555 fix it, try the last build.
