### ISSUE TITLE
输入框无法显示？

### ISSUE THREAD

**Issue by voiddreamz** [osfans/trime#355]
设备：OPPO A59s
系统：Color OS3.0（Android 5.1）
Trime版本：3.1.3
刚安装完成时应用本身无法打开，打开后没有任何界面。最近可以打开应用程序了，但是设置为同文输入法后输入框没有加载出来（等了10分钟问题仍然）

**Comment by Bambooin** [comment]
可以尝试最新的版本，看看是不是已经修复
https://github.com/osfans/trime/tree/gh-pages

**Comment by Yaktsar-0619** [comment]
> 可以尝试最新的版本，看看是不是已经修复
> https://github.com/osfans/trime/tree/gh-pages

I meet this bug also,but even I tried the lastest version,it also exist.

Version:3.1.3
Phone:Xiaomi CC 9E
OS:Android 9(MIUI 11.0.4)

**Comment by Televent-TY** [comment]
我的手机也出现了相同情况。已经尝试过包括最新版在内的若干个版本（从2016年的release到最新版都挨个试过了），均无键盘。
手机：小米8
系统：MIUI12.0.1、MIUI11。
Android版本: 10

**Comment by Televent-TY** [comment]
> 
> 
> 我的手机也出现了相同情况。已经尝试过包括最新版在内的若干个版本（从2016年的release到最新版都挨个试过了），均无键盘。
> 手机：小米8
> 系统：MIUI12.0.1、MIUI11。
> Android版本: 10

恢复出厂设置后已经解决。

**Comment by privapps** [comment]
类似的问题 出现在
TRIME 3.1.3-20191030 from F- DROID

华为EMUI MYA-TL10 EMUI 4.1
海信 HITV105C Android 10
来回折腾/安装好多次，快放弃的时候，被我折腾出来了


主要问题是配置文件，貌似没有完全配置好，我把我ubuntu linux ./.config/ibus/rime 的配置文件copy 到 Android 的 rime 目录下，就好了。

感觉是软件封装/安装的问题，而且下载新的输入法需要手动 copy，自己修改 yaml, 很不方便。

如果需要, 我或许可以帮忙 提高一下你们的易用性

**Comment by Bambooin** [comment]
大部分是权限或配置问题导致的，并且都已经解决。

**Comment by Bambooin** [comment]
@privapps 配置问题可以尝试参考 https://github.com/Bambooin/rimerc
