### ISSUE TITLE
多頁鍵盤

### ISSUE THREAD

**Issue by CyLoiMe** [osfans/trime#36]
输入emoji表情时要切换到emoji输入方案略显不便。

**Comment by osfans** [comment]
切鍵盤的話，可以自己加個emoji符號鍵盤。

切方案的話，可以自定義快捷鍵，快速切換到emoji方案。參考Keyboard_number之類的。

**Comment by ziloeng** [comment]
然emoji表情太多，40鍵也放不下。是否可以增加一個支持多頁的鍵盤功能，類似于google拼音輸入法的表情輸入界面，當按鍵數超過可顯示範圍時，可以通過左右滑切換鍵盤面板。

**Comment by CAPKLU** [comment]
我之前想过做一个针对emoji方案的键盘，目标是做成类似google输入法的效果，原本计划是  “多行候选区” + “一行自定义按键”  的布局。
开工之前用脚本把emoji分类了一下并规划了自定义按键，但是之后却没有找到可以在键盘布局里单独设置候选区样式的方法，按键区好像也不能有横向滚动条。 :laughing:

**Comment by osfans** [comment]
@CAPKLU 嗯，現在不支持滾動條。

**Comment by Sciroccogti** [comment]
请问各位目前是怎么实现输入emoji的？我把[小狼毫的配置方式](https://github.com/rime/rime-emoji/issues/16)移植过来好像不太管用QAQ

**Comment by Bambooin** [comment]
@Sciroccogti 最新版，同文风主题，里面有 主题->表情，即可输入 emoji

**Comment by Bambooin** [comment]
最新版，同文风主题已经有 emoji 键盘  主题->表情
