### ISSUE TITLE
trime.yaml中的[combo: 並擊]应支持绑定一个引导键。

### ISSUE THREAD

**Issue by mayiwen** [osfans/trime#360]
![1](https://user-images.githubusercontent.com/49465747/91837962-563c1000-ec7f-11ea-95ec-e638b80979c4.png)

首先咱先给按键绑上combo，这样这个键盘就支持并击了。
这个时候它这个并击怎么弄的呢？就是你用不是这绑定并击的键跟并击的键一块按，它就出现绑定的效果了。
如按空格不松，然后按个[u]它就上屏7了。
![2](https://user-images.githubusercontent.com/49465747/91837985-5dfbb480-ec7f-11ea-80ac-11e747245d0f.png)

可是，当你松了空格的时候，有个问题出现了。它不仅出现了7，它还在7后面补了一个空格。空格加[u]出现的不是”7”，而是”7_“。这是不合理的。
因为[s]这个键也没有绑定combo，所以它也是可以弄上并击的。用按下s的时候同时出按下u它出现的不也不是7，而是”7是”，为什么会现一个是呢？因为我s的编码就是“是”这个字。
按理说这个s或是空格应该看作电脑上的ctrl、alt这样的键，作为一个引导键，当它执行并击的时候，咱就别执行它本身的功能的。
而且按照原则，空格这样的键是不可以作为修饰键的。Autohotkey是一个电脑上修改快捷键的软件，大家都知道，空格又大又好按，是作为修饰键的最好的选择，但是可以用tab、caps、enter、ctrl、alt就是不可用space。因为space作了修饰键，速度快一点就没法打字了。会动不动就触发功能的，完全没法打字了。本来按的是[h][space]，但是很容易就变成了[space]&[h]。
那什么作为修饰键的最好的选择呢？如下图所示，我想指定图中的[中]作为修饰键。这个[中]不应绑定任何long_click作为功能。
![3](https://user-images.githubusercontent.com/49465747/91838066-7d92dd00-ec7f-11ea-8ae0-50b9428d8beb.png)

比如我按下[中]&[u]打出来的就是7。
我按下[中]不松，然后点[u][i][o][j][k][l]，输入的就是789456。然后松开[中]，此时切换了输入状态，变成了英文输入。按理说是不应该变的。
### 我的想法就是我应该能设置这个修饰的键，而不是除b区外所有的按键都是修饰键，这样打字误触，带来了很大的困扰。如果我按下了[中]这个键，我马上松开了，那执行切换中英文的操作。如果我没有松开，而是按下了同时，我又按了[u]这个键，那将执行combo的操作，这个时候就别切换中英文了。
如果这个能成功，第一层是基础层，第二层是长按层，这个可以作第三层。而且这个第三层比长按层要好很多。如果把上面的一排q到p10个键，绑上长按变成1到0，长按输入个手机号能把人给难受死。这第三层，左手按着[中]，右手按数字，也是快的很啊。为什么不提swipe_加四个方向，啊~，那四个不知道是不是我按的不对，感觉很难受，按个好几次还不出现1次。估计也不是下个版本就能弄好的事。
![3 1](https://user-images.githubusercontent.com/49465747/91838098-884d7200-ec7f-11ea-8cde-48286fd1e64f.png)

我没看出主题中的combo跟并击方案的关系，如果在schema设置一下
![4](https://user-images.githubusercontent.com/49465747/91838136-94393400-ec7f-11ea-8ba4-dde72f16c43d.png)

就是这个，这个设置了后，就是在主题中没有设置combo，也可以实现并击。按[a]&[u]就会出现7，但是一次只能1个，不能[a][u][u][u][u]。而且在英文状态下也不可以使用了。只能在中文状态下使用，感觉也不好用。
而在主题中设置好combo，就是在方案中不作任何设置也可以实现并击的效果，这是两个完全没有关系的事吧。。。。。。哈哈
至此，重回两层架构，一层基础，一层长按。

**Comment by xiaoqun2016** [comment]
给你的引导键<kbd>中</kbd>加上```combo: "VoidSymbol"```，欢迎进入第三层😜

**Comment by QiangF** [comment]
弄个第三层好麻烦，还是像hacker‘skeyboard里的ctrl或者alt一样的引导键好

**Comment by mayiwen** [comment]
> 
> 
> 给你的引导键中加上`combo: "VoidSymbol"`，欢迎进入第三层stuck_out_tongue_winking_eye
确实不错，加了 combo: "VoidSymbol" 可以不触发这个键的原有的功能。😄
但是有点不完美。会出现[s]&[l]、[space]&[j]。有这种存在，压根就快不了。
如果能绑定combo: "Flag"，有绑定Flag的与别的键组合的时候，不触发并击，而是按时间的先后顺序出键，就能用了。 
这个并击可能并不适合作第三层，是为了并击方案的人设计的。咱也不懂并击，就不搞了。能用就行了。
