### ISSUE TITLE
自定義詞五筆庫生效但原有wubi86詞庫失效效

### ISSUE THREAD

**Issue by aiys0211** [osfans/trime#361]
系統：Andriod9
步驟：
1.自定義五筆詞庫wubi86.custom.dict.yaml並導入wubi86詞庫，如圖所示：
![image](https://user-images.githubusercontent.com/30883151/91997898-25d29f80-ed6d-11ea-94bb-46c8230da422.png)
2.修改rime/wubi86.schema.yaml中的dictionary爲wubi86.custom，如圖所示：
![image](https://user-images.githubusercontent.com/30883151/91998284-9bd70680-ed6d-11ea-9901-7940fec573b5.png)
3.重新部署同文輸入法

問題現象：
打出drax出現“非捕獲分組”，這個詞是wubi86.custom.dict.yaml中的詞，自定義詞庫生效
![image](https://user-images.githubusercontent.com/30883151/91999763-53204d00-ed6f-11ea-9a14-9ec55800a447.png)
但是，打出rvf並沒有出現“挪”的選項，表示wubi86.dict.yaml失效
![image](https://user-images.githubusercontent.com/30883151/91998517-e3f62900-ed6d-11ea-8951-2699297a174a.png)

麻煩各位幫忙看看是哪裏出了問題，多謝~

**Comment by Sunpulseqd** [comment]
我的:
<wubi98_ci.schema.yaml>
translator:
  dictionary: wubi98_ci.extended

<wubi98_ci.extended.dict.yaml>
import_tables:
  - wubi98_ci


wubi98_ci.extended和wubi98_ci两个库都能打出来
