### ISSUE TITLE
怎么设置英文状态自动关闭候选栏

### ISSUE THREAD

**Issue by QiangF** [osfans/trime#362]
感觉西文状态没必要占个空间

**Comment by QiangF** [comment]
解决了：

      Mode_switch: {toggle: ascii_mode, toggle: _hide_candidate, send: Mode_switch, states: [ 中文, 西文 ]}

**Comment by QiangF** [comment]
我搞错了，还是不行

    myCandidate_switch: {toggle: _hide_candidate}
    Mode_switch: {toggle: ascii_mode, send: myCandidate_switch, states: [ 中文, 西文 ]}

**Comment by Bambooin** [comment]
目前好像无法实现
