### ISSUE TITLE
reset_ascii_mode 增加重置为英文状态

### ISSUE THREAD

**Issue by QiangF** [osfans/trime#364]
发现还是英文用的比较多

**Comment by qq1767899088** [comment]
我也非常需要这个功能,其他都很完美了.没有这个默认重置英文的设置,你手机关机 或重启后,它又默认为中文了,然后你在vim里那些功能键按上去不会起作用,你必须先换成英文状态.还有我有不少其他的情况,非常希望可以加个变量,让我们自己设置,谢谢

**Comment by ameaninglessname** [comment]
#503 重复了
