### ISSUE TITLE
在輸入區有日文漢字與假名時，游標持續跳回先前位置

### ISSUE THREAD

**Issue by ShamrockLee** [osfans/trime#365]
## 錯誤行爲
游標持續跳回先前位置。

## 再現方式
使用 Firefox Klar 開啓 DuckDuckGo ，在搜尋區貼上含有日文漢字及假名的字串，接着切換至 Trime 輸入法。

## 影像
![VID-1600535565660](https://user-images.githubusercontent.com/44064051/93685600-06fd3880-fae3-11ea-902a-db51d9c801db.gif)

**Comment by InfinityLoop1308** [comment]
Can not reproduce.
