### ISSUE TITLE
请问配置文件里哪个参数是设置候选词个数跟候选栏宽度

### ISSUE THREAD

**Issue by yisuixinq** [osfans/trime#366]
我修改了 max_entries ，候选栏有时会超过屏幕

**Comment by Bambooin** [comment]
sticky_lines: 固顶行数（不与其它候选同排，单独一行显示的候选项个数）
max_entries: 最大词条数（允许进入悬浮窗的最大词条数）
all_phrases: 显示所有长词。所有满足min_length的词条都显示在悬浮窗（一般只用于table translator，有可能会改变候选项的显示顺序）

这个 wiki 里面有详细介绍

https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3
