### ISSUE TITLE
LineageOS 17.1 下输入法崩溃

### ISSUE THREAD

**Issue by mytbk** [osfans/trime#367]
系统版本 LineageOS 17.1 (Android 10) 2020.9.22, 机器是红米Note 7(lavender). F-Droid的版本和最新的测试版都无法使用，一按虚拟键盘输入法就停止运行。

附件中是 adb logcat 相关日志。
[crash.log](https://github.com/osfans/trime/files/5333200/crash.log)

**Comment by mytbk** [comment]
再测试了一下，trime输英文没问题，就是输中文不行。

**Comment by Bambooin** [comment]
Android 10 已经适配，LineageOS 17.1 基于 Android 10，无法输入中文一般是配置的问题。

可以下载最新测试版，并参考 https://github.com/Bambooin/rimerc 配置信息。

**Comment by mytbk** [comment]
我刚刚打开同文输入法，把以前一直没设的“允许现实在其他应用的上层”打开，然后就没问题了。
