### ISSUE TITLE
程序在Android 10上无法使用，一直异常退出

### ISSUE THREAD

**Issue by xtay573269555** [osfans/trime#369]
程序在Android 10(Pixel 4a)上无法使用，一直异常退出。是不是需要在新的SDK上重新编译下了？

**Comment by Bambooin** [comment]
Android 10 已经适配，参考 #367 或其他类似问题

- 下载最新测试版 https://github.com/osfans/trime/tree/gh-pages
- 确保每个权限打开
- 添加配置文件 https://github.com/Bambooin/rimerc
