### ISSUE TITLE
【功能请求】长按字母弹出选框

### ISSUE THREAD

**Issue by Prcuvu** [osfans/trime#37]
例如谷歌的输入法中长按a键可选择@和a的各种变音字母（汉语拼音、其他语言的变音字母等）。
希望trime可以增加这个功能。

**Comment by Iey4iej3** [comment]
我不知道在哪个模式下支持它比较好，似乎是在 ASCII 模式？例如 é, æ, ß, č, ç 等等。

**Comment by Bambooin** [comment]
最新版的 Trime 在同文风主题

选择 主题->更多->拼音，可以出现 变音字母

其他各种符号，可以在主题里面选择

**Comment by Iey4iej3** [comment]
谢谢。不过这个似乎较麻烦（目前似乎并没有比切换到 AOSP 键盘方便）。
