### ISSUE TITLE
能否输入一个单词一次就记忆？

### ISSUE THREAD

**Issue by hjianhao** [osfans/trime#376]
电脑上小狼豪输入一个词一次就客运记忆，在同文上要输入几次材能记忆下来。

有没有设置可以让同文输入法和windows上的小狼毫那样可以一次输入就记忆？

**Comment by Bambooin** [comment]
https://github.com/Bambooin/rimerc
这个配置，里面使用同文风主题，会输入一次就记住，下次再输入，会在候选栏第一个显示
