### ISSUE TITLE
输入法无法使用

### ISSUE THREAD

**Issue by Cirno-NULL** [osfans/trime#378]
环境：Android8.1.0 emui 8.2.0
权限打开了悬浮窗、存储、允许在其他应用的上层显示
无法在任何地方输入文字
直接安装apk以后打开然后启用
然后就闪退了
也许是我少下载了什么东西？

**Comment by Bambooin** [comment]
应该是词库没有安装，可以下载最新版并试试这个词库
https://github.com/Bambooin/rimerc
