### ISSUE TITLE
手机如何删除自定义词

### ISSUE THREAD

**Issue by Sunpulseqd** [osfans/trime#379]
电脑版可以用 control+delete
手机如何删除自定义词呢?

**Comment by Ace-Who** [comment]
根据 Trime 的文档定制键盘
https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3

**Comment by Sunpulseqd** [comment]
> 根据 Trime 的文档定制键盘
> https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3

感谢 提示 在文档里找到了答案: 发送DeleteCandidate指令
