### ISSUE TITLE
请问「同文输入法」的「语音输入」如何调用系统的「语音引擎」？

### ISSUE THREAD

**Issue by arockshan** [osfans/trime#383]
- 参照 [trime詳解](https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3) ,我尝试给「同文输入法」添加 *语音输入* 功能，但 **VOICE_ASSIST** 不能调用 *讯飞语记* ，也没有调用 **系统的语音引擎**，表现是： 按下 <kbd>
語音</kbd> 键后，键盘会随之隐藏起来且没有任何输出；而且经我检验，这个过程触发了「同文输入法」的 **重新部署**,在系统的应用行为记录中，「同文输入法」有启动和读取应用列表的行为。
- 我的手机是 MIUI12 系统的，trime的版本是 3.1.3-20200719.
- 我想请教的是 `"preset_keys/VOICE_ASSIST": {label: 語音, send: VOICE_ASSIST}` 表明「同文输入法」发送了 <kbd>VOICE_ASSIST</kbd> 按键，这在我的手机中不起作用，是因为我的手机的 **小爱语音引擎** 对应的不是 <kbd>VOICE_ASSIST</kbd> 这个按键，还是别的什么原因？

**Comment by arockshan** [comment]
在我的 MIUI12 手机中，通过 <kbd>设置</kbd> → <kbd>应用设置</kbd> → <kbd>应用管理</kbd> ，在 应用管理 界面点进右上角菜单，选择 <kbd>默认应用设置</kbd> → <kbd>助手和语音输入</kbd> → <kbd>语音输入</kbd> ，成功把 语音输入引擎 改为 **小爱语音引擎** ，「同文输入法」的语音按键生效了。

**Comment by GoGoogle** [comment]
> 在我的 MIUI12 手机中，通过 设置 → 应用设置 → 应用管理 ，在 应用管理 界面点进右上角菜单，选择 默认应用设置 → 助手和语音输入 → 语音输入 ，成功把 语音输入引擎 改为 **小爱语音引擎** ，「同文输入法」的语音按键生效了。

我按照这种配置，最后还是没能唤醒语音服务，也是miui12。

**Comment by arockshan** [comment]
抱歉，我表述上有些许错误， **小爱语音引擎** 应为 **系统语音引擎**。我重新录制了一个视频，可供参考：
![语音输入](https://user-images.githubusercontent.com/62659791/112712467-c277ad00-8f0a-11eb-8b0e-713258445ea4.gif)
要点是：
- 我的手机是 RedmiNote8pro， **语音输入** 里系统默认的是 *com.mediatek.voicecommand.vis* 这个控件（每次重启手机后系统都会自动切换到这个选项）。
- 只要同文输入法配置好，在系统里将 **语音输入** 选项中选择 *系统语音引擎* 就好。

**Comment by GoGoogle** [comment]
![20210327_190924](https://user-images.githubusercontent.com/9440508/112718789-2b255080-8f30-11eb-8059-47164ac18a96.jpg)
我没有那个选项

**Comment by arockshan** [comment]
这和手机型号有关系吧，无可奈何啊。
