### ISSUE TITLE
【功能请求】手机输入法能否有输入纠错

### ISSUE THREAD

**Issue by ytskuh** [osfans/trime#385]
对于手机输入法而言，由于按键较小，输入错误是很常见的，我觉得输入纠错应该是必要的功能。

**Comment by Bambooin** [comment]
这个配置里面有对 (z zh pb 之类的处理)，使用起来可以处理 z zh等的匹配
https://github.com/Bambooin/rimerc

**Comment by ytskuh** [comment]
emmm我确实正在使用那个配置，不过我指的是比如一串词语中出现了一个键位错误，输入了相邻的字符，例如zx，ui，这种（我知道我不应该期望太高，不过这确实是有意义的）

**Comment by Bambooin** [comment]
由于 Trime 使用了 rime 引擎，纠错功能应该由 rime 提供，所以可以向上游提出该问题。

https://github.com/rime/librime/issues

**Comment by qwIvan** [comment]
> 由于 Trime 使用了 rime 引擎，纠错功能应该由 rime 提供，所以可以向上游提出该问题。
> 
> https://github.com/rime/librime/issues

相关的issue有人提吗？

**Comment by BunnySakura** [comment]
> > 由于 Trime 使用了 rime 引擎，纠错功能应该由 rime 提供，所以可以向上游提出该问题。
> > https://github.com/rime/librime/issues
> 
> 相关的issue有人提吗？

目前能找到的最后的记录：https://github.com/rime/librime/issues/999

看来优先级不高，真是很可惜🥲
