### ISSUE TITLE
数字键盘跳转主键盘

### ISSUE THREAD

**Issue by bauw2008** [osfans/trime#389]
这个问题主要出现在部分浏览器上,比如yandex.换其他输入法却没有问题.
![Screenshot_20210123-193941](https://user-images.githubusercontent.com/77882800/105577145-ce33df80-5db2-11eb-9fb1-ece542523aad.png)

![20210123_200201](https://user-images.githubusercontent.com/77882800/105577665-ff61df00-5db5-11eb-97e5-d5f620f6f464.gif)

**Comment by bauw2008** [comment]
![Uploading b2c378a7979cd73b8491593bee006b78.gif…]()

**Comment by bauw2008** [comment]
https://github.com/bauw2008/-/blob/a565ffa1e83baafefcf3e39848c1d98f26d88333/b2c378a7979cd73b8491593bee006b78.gif?raw=true

**Comment by bauw2008** [comment]
这个自动跳转目前发现概率高的地方分别是:
1.浏览器主页搜索框以半角,输入192.168.这种路由ip的时候出现,全角下不会跳转.在其他非主页窗口正常.
2.出现在一段网页链接要从中插入一个字符的时候,比如https://github.com,我要在https:s后回会出现自己打同一个字符到不能输入框自动停止.
从正式版到测试版都有这问题,用的新世纪五笔词库.

**Comment by Bambooin** [comment]
看录屏是使用的是 **同文风** 主题，这个会在数字键盘输入 '()' 的时候跳到主键盘，和 #382 类似。

**Comment by Bambooin** [comment]
可以在下面文件搜索 Keyboard_default，凡是输入触发一些条件的时候，会跳到主键盘

https://github.com/osfans/trime/blob/develop/app/src/main/assets/rime/tongwenfeng.trime.yaml

https://github.com/osfans/trime/blob/ae271fb1b03989c96cc4ac42a57e9cd805892090/app/src/main/assets/rime/tongwenfeng.trime.yaml#L3804

**Comment by Bambooin** [comment]
- 搜索 Keyboard_default 来排查到底是什么条件触发了 跳回主键盘

- 是不是触发了 Trime 崩溃什么的，可以在日志里面查看

**Comment by womgit** [comment]
我按右边箭头也会跳回主键盘，我猜测是转换焦点或失去焦点时（或者焦点不稳）会回到主键盘。这个搞笑，建议修改方向是保存app的键盘状态，除非app正常退出结束，否则不自动进行键盘切换。

**Comment by Bambooin** [comment]
无法复现，可以使用最新的测试版验证一下

**Comment by bauw2008** [comment]
这个问题已经解决了，主要是这个浏览器app有问题。
