### ISSUE TITLE
编译bin文件时出现闪退

### ISSUE THREAD

**Issue by zhouxiaobo500** [osfans/trime#39]
OS：Android 4.4.2
Version：trime-20151218

下载并放置完成brise文件夹之后，点击“部署”即瞬间退出，点击“配色”无任何响应。
而导入ibus编译的bin文件却能够正常使用，但部分单字无法打出。

请问该如何解决，谢谢！

**Comment by osfans** [comment]
用1222版看看。

/sdcard/rime刪掉，
然後用trime，會有英文鍵盤。
然後rime目錄裏面出現了trime.yaml等文件，
然後再把brise裏的方案放進去部署看看。

**Comment by zhouxiaobo500** [comment]
新版改进很不错！赞一个。已经成功了。
另外关于essay.txt，是起到了什么作用呢？

**Comment by Prcuvu** [comment]
essay.txt学名“八股文”，记录了一些高频词汇。

**Comment by zhouxiaobo500** [comment]
@Prcuvu 该文件是如何被rime调用的？yaml配置里并没有它的具体引用。

**Comment by zhouxiaobo500** [comment]
@osfans 还有一个问题，升级到新版本之后对圆角按钮接受不能，能否在更新时再考虑一下？

**Comment by osfans** [comment]
可以在
https://github.com/osfans/trime/blob/develop/assets/rime/trime.yaml#L51
這裏修改圓角半徑的，設成0的話應該可以禁用掉。

essay.txt就是默認詞庫，dict.yaml中指定`use_preset_vocabulary: true`即可使用，比如：
https://github.com/rime/librime/blob/develop/data/minimal/luna_pinyin.dict.yaml#L31
