### ISSUE TITLE
Version 3.1.3 crashes on Android 5

### ISSUE THREAD

**Issue by ghost** [osfans/trime#393]
#### Test environment
* Phone A (Brand: LG) has Android 5.0.2
* Phone B (Brand: Sony) has Android 6.0
* APK Version: [Latest beta](https://github.com/osfans/trime/tree/gh-pages) of TRIME (2021/01/23)
* Configuration: [rimerc](https://github.com/Bambooin/rimerc) by @Bambooin

#### Steps to reproduce
On both phones, follow the steps of rimerc installation.

#### Observed result
On Phone A, although all bin files are successfully generated, TRIME still cannot be used.
Using `adb logcat`, there is a line:
`E/AndroidRuntime(12831): android.view.InflateException: Binary XML file line #22: Error inflating class com.osfans.trime.KeyboardView`

On Phone B, TRIME works perfectly, and the above error does not show up in `adb logcat`.

#### Expected result
TRIME should not crash on Android 5.

**Comment by ghost** [comment]
Version 3.1.2 from F-Droid works on Android 5, but Version 3.1.3 does not work.

**Comment by Bambooin** [comment]
New trime apk is on gradle 4.0.0.
