### ISSUE TITLE
曲面屏手机如何调整键盘左右的 Margin 以便躲开曲面部分

### ISSUE THREAD

**Issue by zhangpiu** [osfans/trime#394]
手机是曲面屏，使用时如下图左右两边的红色矩形框所示的部分会位于屏幕的曲面部分，如何配置键盘左右的 margin 大小？
![image](https://user-images.githubusercontent.com/992199/110649161-50a62080-81f4-11eb-97e9-48ef5babaef4.png)

**Comment by Princelo** [comment]
![Lark20210330-180720](https://user-images.githubusercontent.com/10043310/112972577-fa892500-9182-11eb-823c-221eed187caf.jpeg)
每行兩邊設置空白的按鈕 按鈕不發送文本 和背景色一致

**Comment by Bambooin** [comment]
Thanks @Princelo for tips.
