### ISSUE TITLE
在使用九宫格输入时，切换到数字输入时，有时会无法切换回中文状态。后面需要重新部署才行。

### ISSUE THREAD

**Issue by ghost** [osfans/trime#395]

**Comment by GoGoogle** [comment]
你使用的哪个九宫格方案？

**Comment by ghost** [comment]
四叶草九宫格

在 2021年3月21日星期日，GoGoogle ***@***.***> 写道：
> 你使用的哪个九宫格方案？
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/rNaOYv-yua7KU4qDwB25soLAvrJezO4DmxHmnM-0uQFLkqFvKxfFfzXCej8hXS2N5EHOZBmvxzxMwPKtyTufID-j4_m4sRd0IsyBhkTvpM8yQr9DXxzs12ATV8U7K97gGrjSz7VcVE4vU6J-qU-BcYAMQmQZdLhCskvMjZwIzDbxgObmd3mOdUlNUbaTznXTQvjwFpMzYxizVaNxV9dL_sokND9gsKQnPbwtUcDxaA=s0-d-e1-ft#https://github.com/notifications/beacon/AMBVBFYLH2I5XMEWYEKROFDTEWP5BA5CNFSM4ZF24D6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOF7SNTDY.gif>

**Comment by ghost** [comment]
用的是https://github.com/SivanLaai/rime_pure/issues的方案，以前出现过几次，现在没碰上了。

在 2021年3月24日星期三，Travis You ***@***.***> 写道：
> 四叶草九宫格
>
> 在 2021年3月21日星期日，GoGoogle ***@***.***> 写道：
>> 你使用的哪个九宫格方案？
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/rNaOYv-yua7KU4qDwB25soLAvrJezO4DmxHmnM-0uQFLkqFvKxfFfzXCej8hXS2N5EHOZBmvxzxMwPKtyTufID-j4_m4sRd0IsyBhkTvpM8yQr9DXxzs12ATV8U7K97gGrjSz7VcVE4vU6J-qU-BcYAMQmQZdLhCskvMjZwIzDbxgObmd3mOdUlNUbaTznXTQvjwFpMzYxizVaNxV9dL_sokND9gsKQnPbwtUcDxaA=s0-d-e1-ft#https://github.com/notifications/beacon/AMBVBFYLH2I5XMEWYEKROFDTEWP5BA5CNFSM4ZF24D6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOF7SNTDY.gif>

**Comment by GoGoogle** [comment]
用的什么主题？我调用不出来九宫格

**Comment by ghost** [comment]
讯飞主题，还有我使用的是测试版的trime

在 2021年3月24日星期三，GoGoogle ***@***.***> 写道：
> 用的什么主题？我调用不出来九宫格
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/YF9IEdnn6Y4nBnzjlQB0ExUIBzQTi3n0uLYn3DG8IOUQwra09a9Z_1JV_vUlpuI6O62HcpvUEunmMH36hISKzF0uZao6pPxA48g1wAUZP_ELcWIM3RXcn6bQifarqcNXR0A3PyjMj9dZV6i4699ApWj56XedPBJjJqZy0RrRojFnsq8nLLEvOHaVzb-EYs0MZcevsJsqAw8FTTlYJMABDW21uVjx0TpCin02jtMe8A=s0-d-e1-ft#https://github.com/notifications/beacon/AMBVBF63WPZXVWKD4S2UAYLTFHY3DA5CNFSM4ZF24D6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGAEIJEQ.gif>

**Comment by GoGoogle** [comment]
> 讯飞主题，还有我使用的是测试版的trime 在 2021年3月24日星期三，GoGoogle ***@***.***> 写道：
> 用的什么主题？我调用不出来九宫格 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.<
> https://ci4.googleusercontent.com/proxy/YF9IEdnn6Y4nBnzjlQB0ExUIBzQTi3n0uLYn3DG8IOUQwra09a9Z_1JV_vUlpuI6O62HcpvUEunmMH36hISKzF0uZao6pPxA48g1wAUZP_ELcWIM3RXcn6bQifarqcNXR0A3PyjMj9dZV6i4699ApWj56XedPBJjJqZy0RrRojFnsq8nLLEvOHaVzb-EYs0MZcevsJsqAw8FTTlYJMABDW21uVjx0TpCin02jtMe8A=s0-d-e1-ft#https://github.com/notifications/beacon/AMBVBF63WPZXVWKD4S2UAYLTFHY3DA5CNFSM4ZF24D6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGAEIJEQ.gif>
我最后换了别的九宫格

**Comment by ghost** [comment]
可以麻烦分享一下吗？目前我就找到这个。

在 2021年3月25日星期四，GoGoogle ***@***.***> 写道：
> 讯飞主题，还有我使用的是测试版的trime 在 2021年3月24日星期三，GoGoogle @.***> 写道：
> 用的什么主题？我调用不出来九宫格 — You are receiving this because you authored the
thread. Reply to this email directly, view it on GitHub, or unsubscribe.<
>
https://ci4.googleusercontent.com/proxy/YF9IEdnn6Y4nBnzjlQB0ExUIBzQTi3n0uLYn3DG8IOUQwra09a9Z_1JV_vUlpuI6O62HcpvUEunmMH36hISKzF0uZao6pPxA48g1wAUZP_ELcWIM3RXcn6bQifarqcNXR0A3PyjMj9dZV6i4699ApWj56XedPBJjJqZy0RrRojFnsq8nLLEvOHaVzb-EYs0MZcevsJsqAw8FTTlYJMABDW21uVjx0TpCin02jtMe8A=s0-d-e1-ft#https://github.com/notifications/beacon/AMBVBF63WPZXVWKD4S2UAYLTFHY3DA5CNFSM4ZF24D6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGAEIJEQ.gif
>
> 我最后换了别的九宫格
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/-LFQTkrvnba8kOBY9MeeNumv4pVE-zZ8E0FWHq1anj6rD9ffNV4NIsbwKQMW97cMwMSK_XOmCAGe96vqkUx2S2Q1G16S4v1m69rY4knxg6WLPaCTR6QLvDC790eUAElEW53ppo-IWeEuGNB5W1X02xv9sl-1VN4ChqYWMdpfuHYLB3cS3UhbUJmbhF_bzykKR3FP1TihiAV4JEJC2RQmb7g7V_CVMh1mmfZMBc0a2w=s0-d-e1-ft#https://github.com/notifications/beacon/AMBVBF3HY673X4JJMQDNELLTFNDR3A5CNFSM4ZF24D6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGAL6PHY.gif>

**Comment by ghost** [comment]
找到了377楼的

在 2021年3月26日星期五，Travis You ***@***.***> 写道：
> 可以麻烦分享一下吗？目前我就找到这个。
>
> 在 2021年3月25日星期四，GoGoogle ***@***.***> 写道：
>> 讯飞主题，还有我使用的是测试版的trime 在 2021年3月24日星期三，GoGoogle @.***> 写道：
>> 用的什么主题？我调用不出来九宫格 — You are receiving this because you authored the
thread. Reply to this email directly, view it on GitHub, or unsubscribe.<
>>
https://ci4.googleusercontent.com/proxy/YF9IEdnn6Y4nBnzjlQB0ExUIBzQTi3n0uLYn3DG8IOUQwra09a9Z_1JV_vUlpuI6O62HcpvUEunmMH36hISKzF0uZao6pPxA48g1wAUZP_ELcWIM3RXcn6bQifarqcNXR0A3PyjMj9dZV6i4699ApWj56XedPBJjJqZy0RrRojFnsq8nLLEvOHaVzb-EYs0MZcevsJsqAw8FTTlYJMABDW21uVjx0TpCin02jtMe8A=s0-d-e1-ft#https://github.com/notifications/beacon/AMBVBF63WPZXVWKD4S2UAYLTFHY3DA5CNFSM4ZF24D6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGAEIJEQ.gif
>
>> 我最后换了别的九宫格
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/-LFQTkrvnba8kOBY9MeeNumv4pVE-zZ8E0FWHq1anj6rD9ffNV4NIsbwKQMW97cMwMSK_XOmCAGe96vqkUx2S2Q1G16S4v1m69rY4knxg6WLPaCTR6QLvDC790eUAElEW53ppo-IWeEuGNB5W1X02xv9sl-1VN4ChqYWMdpfuHYLB3cS3UhbUJmbhF_bzykKR3FP1TihiAV4JEJC2RQmb7g7V_CVMh1mmfZMBc0a2w=s0-d-e1-ft#https://github.com/notifications/beacon/AMBVBF3HY673X4JJMQDNELLTFNDR3A5CNFSM4ZF24D6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGAL6PHY.gif>
