### ISSUE TITLE
tfHanB 无效

### ISSUE THREAD

**Issue by yanhuacuo** [osfans/trime#396]
https://github.com/osfans/trime/blob/8e8ad1571c6c7c1dda07c4ea9e76de338e4360e3/app/src/main/java/com/osfans/trime/Candidate.java#L183

 tfHanB 似乎失效了，指定的后备字体无法正常显示。

**Comment by osfans** [comment]
我把98WB-U.ttf放到了這裏，可以顯示：/sdcard/rime/fonts/hanb.ttf。

**Comment by yanhuacuo** [comment]
> 我把98WB-U.ttf放到了這裏，可以顯示：/sdcard/rime/fonts/hanb.ttf。

您那里能「正常显示」，是因为从系统主题方面做了字体变动，而不是输入法这里的「设置」是正常的。
虫姐说跟您沟通过，单个字体的上限是65535，对九万多，以及未来更多的超集难以完整支持，不如将扩A到扩G分点拉出来设置。
