### ISSUE TITLE
如图所示，红圈里面的按键高度如何调整？

### ISSUE THREAD

**Issue by GoGoogle** [osfans/trime#398]
![Screenshot_20210325-223033_Google_1](https://user-images.githubusercontent.com/9440508/112490207-2343a000-8dba-11eb-9756-dcee5f484891.png)
我找了好久都没调整过来

`#第一行
      - {key_back_color: bh1, key_text_color: th1, width: 100, height: 18}
      - {click: ",", long_click: ";", key_back_color: keyboard_back_color, key_text_color: text_color, width: 15}
      - {click: 1, label: "'", composing: "'", long_click: "|", swipe_up: Up, swipe_down: Down, swipe_left: Left, swipe_right: Right}
      - {click: 2, label: abc, long_click: select_all, swipe_up: Up, swipe_down: Down, swipe_left: Left, swipe_right: Right}
      - {click: 3, label: def, long_click: "+", swipe_up: Up, swipe_down: Down, swipe_left: Left, swipe_right: Right}
      - {click: BackSpace, long_click: "-", width: 16}`
      
这里面的  `height: 18`  也不对，只把背景灰色撑高了

**Comment by Bambooin** [comment]
key_height: 键高*
key_width: 键宽*，占屏幕宽的百分比
⚠ 当按键布局中的height与width省略不写时，此处设置的key_height与key_width才会生效。

这个 wiki 里面有详细介绍

https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3
