### ISSUE TITLE
能否实现两行候选栏

### ISSUE THREAD

**Issue by love98wubi** [osfans/trime#399]
竖屏状态 候选字显示不了几个 能不能实现两行候选?

**Comment by Princelo** [comment]
你不是用五筆的嘛 糾結這個

**Comment by Bambooin** [comment]
竖屏状态时，如果输入的字符较长时，会多行显示的

如输入 “ybppbzm”，会显示三行

使用的配置为 https://github.com/Bambooin/rimerc
