### ISSUE TITLE
Android 11 闪退

### ISSUE THREAD

**Issue by QiangF** [osfans/trime#400]
用的这个配置https://github.com/Bambooin/rimerc，能输入英文，输入中文只能输一个汉字就闪退了。

**Comment by Bambooin** [comment]
1. 请使用最新测试版，https://github.com/osfans/trime/tree/gh-pages
2. 检查权限是否开启
3. 按照 https://github.com/Bambooin/rimerc 里面步骤，能否复现

目前手里没有 Android 11 的机子，无法复现，怀疑是**读取文件权限**没有开启导致的

**Comment by QiangF** [comment]
谢谢，解决了，是一个显示在别的应用上面的权限。
