### ISSUE TITLE
Upgrade to lastest librime and opencc to decrease startup time and make small bin file

### ISSUE THREAD

**Issue by Bambooin** [osfans/trime#401]
I have failed update it, someone can contribute it via pull request.

**Comment by WhiredPlanck** [comment]
I've managed to upgrade the OpenCC in my personal fork. You could see https://github.com/WhiredPlanck/trime-new .

**Comment by Bambooin** [comment]
Would you make pull request for OpenCC upgrade.

**Comment by Bambooin** [comment]
colsed in #408
