### ISSUE TITLE
我有一个好想法

### ISSUE THREAD

**Issue by Pantyhose-X** [osfans/trime#404]
我有一个好想法 你可以开发一个 监听输入法工具，应用于学习语言，这样可以纠正发音和加深记忆，调用文本转语音TTS 朗读输入单词或句子。 `输入空格` 后TTS朗读单词，`输入空格`10秒后朗读句子。
你可以内置 [mozilla文字转语音](https://github.com/mozilla/TTS) 或调用Win10内置的或调用Win10安装的
>
`视频例子`https://www.youtube.com/watch?v=YPBn6D6pf78&feature=youtu.be&t=213
>
Android 内置mozilla文字转语音或调用google文本转语音TTS。
>
不以英语为母语的人都需要学习英语，市场非常广

**Comment by osfans** [comment]
這個暫不考慮，先關閉。
