### ISSUE TITLE
功能请求：输入剪贴板中的内容

### ISSUE THREAD

**Issue by huyz-git** [osfans/trime#406]
尽管目前同文输入法已经可以通过 `send: Control+v` 来实现粘贴功能，但这样的实现是将 “粘贴” 这个动作发送给目标应用，然后由目标应用去读取剪贴板。
这种使用方式，必须授予目标应用 “读取剪贴板” 的权限，才能正常使用。
但目前市面上有一些应用，在授予其 “读取剪贴板” 权限时，会滥用剪贴板（即在用户没有显式要求粘贴文本或者主动允许应用静默读取时，应用就擅自读取剪贴板）。但如果不授予其权限，又一定程度会影响正常的使用。
考虑到正常使用剪贴板的场合大部分都是在输入文本的地方粘贴文本，此时往往输入法是激活状态。
如果`同文输入法`能够实现一个 “输入剪贴板中的内容” 的功能，由`同文输入法`去读取剪贴板中的文本，并将其输入。这样，只要授予`同文输入法` “读取剪贴板” 权限，就能正常粘贴文本，不用授予目标应用 “读取剪贴板” 权限，从而解决应用滥用剪贴板的问题。

配置举例：
```
paste: {label: 粘贴, send: function, command: clipboard} //增加一个 clipboard 的 command 用于读取剪贴板内容
- {click: v, long_click: paste, swipe_down: "\\", key_back_color: bh3, key_text_color: th3}
```

**Comment by Bambooin** [comment]
Close by #407
