### ISSUE TITLE
為按鍵定義了西文狀態，Label顯示正常，但按下依舊是Click事件。

### ISSUE THREAD

**Issue by rcetangle** [osfans/trime#41]
為按鍵定義了西文狀態，Label顯示正常，但按下依舊是Click事件。還是說我定義有誤？
{click: "select_all", ascii: "Shift_L"},
系統安卓5.0
還希望增加double_click。

**Comment by osfans** [comment]
雙擊的還沒做。
ascii的目前是只能顯示Label，跟composing之類的一樣。至於功能不知道能不能用rime的key_binder實現。

**Comment by osfans** [comment]
29號的版本應該解決了ascii的問題，不僅僅是顯示標籤了：
https://github.com/osfans/trime/releases/download/v3.0-beta/trime-20151229.apk

**Comment by rcetangle** [comment]
好效率👍

**Comment by osfans** [comment]
雙擊問題，轉到 #12  問題去討論。這個先關閉。
