### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Rovever** [osfans/trime#419]
最新版 3.2.1 在 Sony Xperia 1 Ⅲ（Android 11）经常闪退，输入卡顿严重。

**Comment by Bambooin** [comment]
可以按照这个配置文件重新部署一下，看看能否复现
https://github.com/Bambooin/rimerc

手里没有相应的机型和系统，无法排查

**Comment by Rovever** [comment]
我用了你的方法 输入-->恢复默认设置 简单测试了你的配置文件没有出现卡顿现象，
可能是我恢复旧手机的 luna_pinyin.userdb 太大（四年前的旧手机配置更低倒是没有卡顿）导致，删除就没有卡顿了
但是还有一个问题，不论你的方案还是我自己之前的方案 简繁体切换 都没有效果，都是显示繁体。
请教下这种情况是需要修改配置还是需要下载什么文件

**Comment by oniondelta** [comment]
初安裝 v3.2.1 也發生崩潰問題，排查許久發現是 opencc 新版的關係
新版 opencc 的格式是「.ocd2」，舊版是「.ocd」
如果 opencc 原檔中有詞條重複情形，部署後就會發生崩潰情形！
且不會生成出「.ocd2」檔案！
修正後，目前順暢使用，沒發生問題！
建議 opencc 不要移植舊版的檔案！

**Comment by Rovever** [comment]
确实一点部署就会卡死，请教下这个opencc要怎么弄

**Comment by oniondelta** [comment]
至少不要把之前的 opencc 資料夾放入 rime 資料夾中
這邊繁簡切換是正常運作的

**Comment by Rovever** [comment]
好的，谢谢你，我晚点试试看。

**Comment by Rovever** [comment]
https://github.com/BYVoid/OpenCC/wiki/Download
下载了这个Windows预编译文件，直接用share里面的opencc文件不知道可以不

**Comment by oniondelta** [comment]
不要再弄其他任何 opencc 的檔案進去了！除非你會弄！
只是繁簡切換，一般預設檔即可，沒必要添加！

回廠（預設），rime 資料夾中就會生成 一個 opencc 資料夾，
部署後，裡面的檔案就會生成出新版格式「.ocd2」

反正怎麼搞， 新版生成的 opencc 資料夾和其中檔案不要動！
除非使用的方案有掛接其他自製的 opencc 功能！

**Comment by Rovever** [comment]
我清除缓存重新恢复配置，没办法生成.ocd2，每次都是生成txt文件，还是没办法简繁切换

**Comment by Bambooin** [comment]
不能简繁切换，是因为 opencc 没有配置正确

可以按照下面步骤里面的第三步，恢复默认设置，重新部署即可

https://github.com/Bambooin/rimerc#详细步骤

**Comment by Rovever** [comment]
@Bambooin 谢谢你的解答和你的配置文件，现在成功部署了，暂时没有奔溃。
@oniondelta 谢谢你的提醒，我用 OpenCC 的 Windows 预编译文件解决了简繁体切换问题
https://github.com/BYVoid/OpenCC/wiki/Download

**Comment by Rovever** [comment]
@Bambooin 谢谢你的解答和你的配置文件，现在成功部署了，暂时没有奔溃。
@oniondelta 谢谢你的提醒，我用 OpenCC 的 Windows 预编译文件解决了简繁体切换问题
https://github.com/BYVoid/OpenCC/wiki/Download
