### ISSUE TITLE
浏览器编辑网址自动清空

### ISSUE THREAD

**Issue by fonaix** [osfans/trime#42]
手机：红米1S
浏览器：红米自带、搜狗浏览器
输入法：trime-20151228
打开网站后，点击地址栏编辑网址时会自动清空网址。

**Comment by osfans** [comment]
果然有問題。多謝。

**Comment by fonaix** [comment]
今天我发现，不仅是在浏览器中，在其它软件下编辑会自动选中文字时都会清空掉。

**Comment by osfans** [comment]
1230剛更新的apk應該能解決。

**Comment by fonaix** [comment]
嗯，可以了。

**Comment by osfans** [comment]
這回應該解決了：https://github.com/osfans/trime/releases/download/v3.0-beta/trime-20160104.apk

**Comment by fonaix** [comment]
好的，我试试。
