### ISSUE TITLE
Will Trime accept PR in Kotlin?

### ISSUE THREAD

**Issue by WhiredPlanck** [osfans/trime#421]
等了四年终于更新啦！

几个月前决定自己自学 Android 开发，期间接触了 Kotlin。想着同文好久没正式更新了，就开始着手写了些新东西，为此还开了个 fork：https://github.com/WhiredPlanck/trime-new 。

不过因为有练手的过程的影响，以及想法过于零散琐碎，就不想直接合过来了。

不知道同文接不接受 Kotlin 格式的贡献呢？（我也能用 Java，不过不如 Kotlin 熟练）
如果有可以贡献的想法，我会比自己捣鼓更谨慎和认真。

**Comment by Bambooin** [comment]
只要能提升用户体验，提高程序健壮性，非常欢迎加入 Trime 大家庭。

**Comment by Bambooin** [comment]
Android 开发也在慢慢转向 Kotlin 为主，语言仅仅是工具，重要的是目的和过程。

如果能借着转 Kotlin 的机会好好优化重构一下代码，提高代码质量和可读性，将是很好的机会。

**Comment by WhiredPlanck** [comment]
> Android 开发也在慢慢转向 Kotlin 为主，语言仅仅是工具，重要的是目的和过程。
> 
> 如果能借着转 Kotlin 的机会好好优化重构一下代码，提高代码质量和可读性，将是很好的机会。

是的，这就是我目前想的一大方向。我会努力的～
