### ISSUE TITLE
Force tone input with pinyin

### ISSUE THREAD

**Issue by ghost** [osfans/trime#423]
Is it possible to force tone input ? For example, I would like to write ni3 before getting candidates then select the character 你 I wanted. It would be for learning purposes

**Comment by Bambooin** [comment]
Rime doesn't support tone filter, so Trime either.

**Comment by ghost** [comment]
Apparently, Rime does support tone filter with [rime-terra-pinyin](https://github.com/rime/rime-terra-pinyin) so I guess it should be possible to port it to Trime but I don't know how

**Comment by Bambooin** [comment]
Maybe you can put rime-terra-pinyin in your config folder, and try deploy and choose schema of it.

**Comment by ghost** [comment]
Yes I'll try but I need to change it to accept numbers instead of punctuation signs for tones. Typing `hao3` is easier on an android keyboard than `hao<`.
