### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by ghost** [osfans/trime#425]
点击部署总是退出

**Comment by WhiredPlanck** [comment]
> 点击部署总是退出

这其实是预期行为，部署完成后为了释放内存，同文会自己“自杀”一次。手动再次进入就好。

**Comment by Bambooin** [comment]
如果无法输入汉语，应该是缺少 配置文件导致的，如 trime.yaml 等

可以参考 https://github.com/Bambooin/rimerc 配置文件，重新部署一下
