### ISSUE TITLE
Some Discussions on Trime Enhancement Plan

### ISSUE THREAD

**Issue by WhiredPlanck** [osfans/trime#428]
Hi。不久前，我按照自己的构想用 Kotlin 重构了同文的对话框组件（ #424 ）。

我目前还有其他类似的想法：

*  重构 `SeekBarPreference` 组件
*  重构 `Pref` 活动

重构 `SeekBarPreference`：之所以没有把 `SeekBarPreference`  这个组件放入 #424 里，是因为如果只是单纯地用 Kotlin 重写一次意义不太大，Kotlin 在此和 Java 一样没有什么太特别的地方。于是参考了一些其他输入法的设置界面（例如 Gboard），发现它们基本上都把这种进度条式的设置项放入了点击即弹出的对话框里。  我个人认为这是比较好的方式，一来是当前的 `Preference` 项进度条太短了，滑块又小，在手机上很难精准调节（强迫症表示不调到整数无法忍受 :laughing: )；二是在平板等大屏设备，这个条就显得更短了，显示不够灵活；三是放入对话框就可以有按钮重置默认值，或者确认/取消调节。  但同时也想到这样的 `Preference` 项比较个性，相比其他软件同文可能独一份，是不是只用微调就好呢？

重构 `Pref`：这将会是一个不小的工程。主要涉及到：
* 用 `AppCompatActivity` 代替已经过时的 `PreferenceActivity`
* 更灵活的日夜间模式（手动指定/自动跟随系统）
* 整理 `Preference` 项树

等等。 

之前我在我的 fork 里尝试了部分这些工作，整体效果来看是这样：

<a href="day"><img src="https://camo.githubusercontent.com/1c7d79ad9c8d14ae97e04984d730eba5aa145010f44d55676b6f9cf958d16e8c/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30352f32392f6a4a6e526d3562556168697a5a51582e706e67" align="center" height="960" width="540" ></a>

<a href="day"><img src="https://camo.githubusercontent.com/0e06331f88cef9dcb1102954057d5c77504009d750de37f1962794c30071b7c5/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30352f32392f65344d4b6871314e53677a565a72322e706e67" align="center" height="960" width="540" ></a>

部署、寻求帮助和关于信息都放入了右上角的选项菜单里，整体页面更简洁了，还有机会把一些常用的设置放出这个首页来（比如方案选择、主题选择和配色选择）。

以上是我近期想和能对同文「改造」的一些想法。

**Comment by WhiredPlanck** [comment]
噢，对了，我一直在关注并参考着一个新兴的键盘项目 [florisboard](https://github.com/florisboard/florisboard) 。这是一个完全由 Kotlin 编写的西文输入法。虽然不能输入中文，但我觉得在「输入中文」这方面之外它有很多细节可以参考和借鉴。florisboard 整体观感和 Gboard 重合性挺高，我觉得同文也能有一天成为一款更有商业输入法专业范儿的开源中文输入法。

**Comment by ameaninglessname** [comment]
大佬可以顺手修下：
横屏输入时，候选框超出屏幕；
部分场景输入不到选中的输入框里；
等问题嘛，目前的issue里应该有

不过，或许bug应该等到底层重构稳定之后再处理

感谢，辛苦！

**Comment by QiangF** [comment]
希望把一些控制键加进去，如 Ctrl Alt Esc Tab，这样方便在termux里用，参考
https://github.com/klausw/hackerskeyboard

**Comment by WhiredPlanck** [comment]
> 希望把一些控制键加进去，如 Ctrl Alt Esc Tab，这样方便在termux里用，参考
> https://github.com/klausw/hackerskeyboard

Emm，说实话我觉得现在不会要输入法来实现这个功能吧 …… 虽然我没用过 Termux，但有截图说明其会在底部自动显示功能键。

**更新**：这类功能键加在中文输入法里比较难（或者准确来说对同文比较难），因为这几个功能键输入法，要加判断条件选择是给输入法还是直接发送给其他软件。Hackerskeyboard 它本质是个**键盘**，并不是**输入法**，这是由于英文可以不需要选词因而没有太多输入法的概念，按键事件可以直接发送给 Termux，无需多加判断。   而且 Termux 会自己显示功能键的话，在输入法里加功能键就属实冗余了。

**Comment by WhiredPlanck** [comment]
> 横屏输入时，候选框超出屏幕；
> 部分场景输入不到选中的输入框里；

这些 Bug 我都知道哈，但是说实话我不太会修这种 …… 我还想解除同文的 5 候选字限制，结果自己尝试的时候没解除成功还引入了新 Bug …… :rofl:
