### ISSUE TITLE
浏览器的地址栏能否单独记忆中英状态？

### ISSUE THREAD

**Issue by xiaoqun2016** [osfans/trime#43]
现今的浏览器都有地址栏搜索功能，直接输入中文关键词即可进行搜索。在这种情况下，每次选中地址栏都自动切到英文模式反而不方便了。

可否让地址栏单独记忆中英状态？像谷歌触宝这些输入法就是这样做的：
用户上次使用地址栏时切到了什么状态，那么这次仍然沿用上次的状态，这样可以兼顾不同用户的使用习惯。

而且，即使在中文状态，rime也能很快捷地识别编码中的url，对网址输入也没影响。

**Comment by osfans** [comment]
那就不處理網址。只處理密碼。

**Comment by xiaoqun2016** [comment]
我好像没表达清楚意思。我上面是说，谷歌输入法是分开记忆「普通文本框」和「地址栏」的中英状态的。
这样比以前常见的统一记忆要来得复杂。

**Comment by osfans** [comment]
地址欄單獨記憶？目前沒有做，先統一記憶吧。

**Comment by xiaoqun2016** [comment]
那好，就先这样吧！ 在2016年01月04日 15:27 ，Osfans写道： 地址欄單獨記憶？目前沒有做，先統一記憶吧。 — Reply to this email directly or view it on GitHub.

**Comment by osfans** [comment]
地址欄不強制英文了：https://github.com/osfans/trime/releases/download/v3.0-beta/trime-20160104.apk

**Comment by osfans** [comment]
你終於註冊github了。不幫忙改代碼的話，幫忙維護yaml啊。

**Comment by xiaoqun2016** [comment]
嗯，我主要是来学习的，不懂的地方太多了。如果有需要的话，我可以做些力所能及的事情。
2016年1月4日 6:10 PM，"Osfans" notifications@github.com写道：

**Comment by osfans** [comment]
隨便什麼啊，yaml可以在線編輯，還有wiki也可以編輯。
要是編輯wiki的話，那就把release頁面的東西搬過去。

**Comment by xiaoqun2016** [comment]
嗯，可以试试。 在2016年01月05日 19:17 ，Osfans写道： 隨便什麼啊，yaml可以在線編輯，還有wiki也可以編輯。 要是編輯wiki的話，那就把release頁面的東西搬過去。 — Reply to this email directly or view it on GitHub.
