### ISSUE TITLE
能否在未来支持检测实体键盘连接，继续优化实体键盘输入体验？

### ISSUE THREAD

**Issue by wisim** [osfans/trime#434]
目前Trime虽然支持了悬浮窗口，但这个功能仍然存在一些问题。
1. 悬浮窗口偶尔会不跟随光标，或者不显示。比如我现在在Chrome中打字时，悬浮窗口就出现在屏幕的左上角（偶尔），并且常常消失（总是）。
2. 若不勾选「显示虚拟键盘」，则连接实体键盘后，虚拟键盘不会自动隐藏：若勾选了「隐藏虚拟键盘」，则连接实体键盘后，虚拟键盘无法唤出。
3. 在皮肤中设定悬浮窗口后，虚拟键盘的输入栏就被悬浮窗口替代，而原本应该出现在虚拟键盘最上方的输入栏消失了。
4. 即使取消勾选了「显示虚拟键盘」，用实体键盘打字时，屏幕的最下方也经常会出现一个横条，必须手动点击向下的箭头才能隐藏。
5. 默认的两个皮肤方案都没有默认开启悬浮窗口。

**Comment by WhiredPlanck** [comment]
由于我没有能连上 Android 设备的实体键盘，与之有关的问题不好测试和修复。会长期观望 ～

> 默认的两个皮肤方案都没有默认开启悬浮窗口。

我没记错的话，这应该是第一次安装同文就能看到默认开启的设置。它是在同文“键盘”设置页可独立控制的选项，应该与皮肤无关。

**Comment by wisim** [comment]
> 由于我没有能连上 Android 设备的实体键盘，与之有关的问题不好测试和修复。会长期观望 ～
> 
> > 默认的两个皮肤方案都没有默认开启悬浮窗口。
> 
> 我没记错的话，这应该是第一次安装同文就能看到默认开启的设置。它是在同文“键盘”设置页可独立控制的选项，应该与皮肤无关。

是的确实有这个开关。但是默认的效果我给你截个图。这个悬浮窗固定显示在左下角，而且经常没有内容。
我说的皮肤里的设置是 Trime.yaml 详解里「4.悬浮窗口」里的相关设置，设置好之后确实可以做到光标跟随和正常显示输入内容。不过如果输入法本身也有这类设定，那这些功能是不是有些重复了。
顺便吐槽一下Trime的设定，没有自带方案也就算了，就算复制好了default.yaml，也必须要建一个default.custom.yaml的空文件才能正常选择方案。= =||

![同文风一](https://obohe.com/i/2021/06/26/ujbv4v.png)
![同文风二](https://obohe.com/i/2021/06/26/ujdwo0.png)
![默认一](https://obohe.com/i/2021/06/26/uogemg.png)
![默认二](https://obohe.com/i/2021/06/26/uohzri.png)

**Comment by WhiredPlanck** [comment]
> 是的确实有这个开关。但是默认的效果我给你截个图。这个悬浮窗固定显示在左下角，而且经常没有内容。
> 我说的皮肤里的设置是 Trime.yaml 详解里「4.悬浮窗口」里的相关设置，设置好之后确实可以做到光标跟随和正常显示输入内容。不过如果输入法本身也有这类设定，那这些功能是不是有些重复了。
> 顺便吐槽一下Trime的设定，没有自带方案也就算了，就算复制好了default.yaml，也必须要建一个default.custom.yaml的空文件才能正常选择方案。= =||
> 

噢，横屏呀 …… 横屏状态下目前有个 Bug（ #100、#248、#317 等），无法显示候选栏。目前我也没定位到关键问题所在。不过会改进到的（虽然不知道要到何年何月 :joy: ）

**Comment by WhiredPlanck** [comment]
> ![默认二](https://camo.githubusercontent.com/f7be5c9abbaf0802d62345d5821a8cb7ec31910004f9a5ad6bb0de4db7b5e01c/68747470733a2f2f6f626f68652e636f6d2f692f323032312f30362f32362f756f687a72692e706e67)

这张图片的候选词，是在输入字数超过设定临界时溢出到编码窗口上的。所以说，横屏状态的这个悬浮窗，其实是编码栏，而不是候选栏，因为后者由于 Bug 没显示出来。很遗憾，如果你横屏下输入的需求较多，我只能暂时建议你更换其他皮肤（有些皮肤可以将所有候选提到编码栏里）或输入法。
