### ISSUE TITLE
@before 10这个键是个bug

### ISSUE THREAD

**Issue by flypyxh** [osfans/trime#436]
@before 10实际等于@before 11，少了@before 10这个键，当你打补丁增键时，就增加不了这个键，连续增加@before 9、@before 10是不连续的，相当于插入了9和11。

**Comment by Bambooin** [comment]
能否具体指明那个文件，或者那个配置

**Comment by flypyxh** [comment]
这是一个主题文件，不少用户曲面屏的缘故需要主题键盘居中，两边留空，于是我用寄生主题的方式，在原主题的基础上生成了居中的键盘，这就需要用到插入键，我的符号键盘有8列，所以第一排0键前插入一键before 0，然后在第一排末插入一键before 9,第二排插入一键before 10，正好要用到这个before 10，于是发现这个问题，9和10并没有连续，而是被隔开了，10没有出现在第二排的首位，而是出现在了第二位。所有的8列符号键盘全部出现这个问题，于是我只能把8列符号键盘改成7列，避开这个before 10键，才正常。


如果你还不清楚的话，我就再弄一个8列的符号键盘主题提交给你看。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "osfans/trime"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月21日(星期一) 晚上7:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [osfans/trime] @before 10这个键是个bug (#436)





 
能否具体指明那个文件，或者那个配置

**Comment by tumuyan** [comment]
这个也可以close了.

在 https://github.com/osfans/trime/pull/469 中皮肤增加参数keyboard_padding。用于竖屏状态下，为曲面屏添加屏幕左右两侧到键盘区域的间隙。
从实际需求的角度解决了问题.
如果before确实存在bug,理论上也需要librime修复了…

**Comment by flypyxh** [comment]
出新版了吗？在哪里下载？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "osfans/trime"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月1日(星期三) 上午10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [osfans/trime] @before 10这个键是个bug (#436)





 
这个也可以close了.
 
在 #469 中皮肤增加参数keyboard_padding。用于竖屏状态下，为曲面屏添加屏幕左右两侧到键盘区域的间隙。
 从实际需求的角度解决了问题.
 如果before确实存在bug,理论上也需要librime修复了…
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ameaninglessname** [comment]
[这下面的Artifacts可以下debug安装包](https://github.com/osfans/trime/actions/runs/1185973847)
