### ISSUE TITLE
希望发布安装包的时候至少能把 preclude 和 essay 包含进去。

### ISSUE THREAD

**Issue by wisim** [osfans/trime#440]
如题。
我并不希望 `default.yaml`、`essay.txt`、`keybindings.yaml`、`punctuation.yaml`、`symbols.yaml` 出现在用户文件夹里。可以的话。luna_pinyin 也不要出现在里面。这些东西不应该是随便改动的，而且最好能随着软件更新而更新。
而且出现在用户文件夹的这些东西对于桌面版来说是多余的。我不希望这些内容同步进去。
而且有一个预设的方案也会让这个软件易用一些 =。=
还有，必须有 `default.custom.yaml` 才能正常选择方案是不是太奇怪了。

**Comment by Bambooin** [comment]
preclude essay  可以在 以下配置里面获取最新的配置

https://github.com/Bambooin/rimerc

**Comment by walk143** [comment]
必须有`default.custom.yaml`在`librime/src/rime/lever/custom_settings.cc:46`有验证，为了记录用户选择的方案
