### ISSUE TITLE
请支持 setImeHintLocales 和 IME_FLAG_FORCE_ASCII

### ISSUE THREAD

**Issue by ivysrono** [osfans/trime#442]
https://developer.android.google.cn/reference/android/view/inputmethod/EditorInfo#hintLocales

https://github.com/nhirokinet/bluelineconsole/issues/17#issuecomment-775076908

Trime 不支持这些功能导致效果不如预期。

**Comment by WhiredPlanck** [comment]
已纳入待办，不过短期内可能完成不了～ 感谢建议

**Comment by tumuyan** [comment]
[f474004d](https://github.com/tumuyan/trime-without-CMake/commit/f474004d22b0eee13f99e3f921d3562890740c9a)  will support imeOptions IME_FLAG_FORCE_ASCII

**Comment by InfinityLoop1308** [comment]
I don't really understand the `serImeHintLocales`. Can you describe what we should do in detail?

**Comment by ivysrono** [comment]
@tumuyan 没有提pr啊

**Comment by tumuyan** [comment]
> @tumuyan 没有提pr啊

代码已经合并过了， bluelineconsole 的 IME_FLAG_FORCE_ASCII 现在是支持的

**Comment by ivysrono** [comment]
> > @tumuyan 没有提pr啊
> 
> 代码已经合并过了， bluelineconsole 的 IME_FLAG_FORCE_ASCII 现在是支持的

我说最近怎么程序切换的时候好像有些变化。谢谢。
