### ISSUE TITLE
考虑移除必须的存储权限

### ISSUE THREAD

**Issue by seff** [osfans/trime#443]
是否可以通过getExternalFilesDir()函数存取数据，或在用户未授权储存权限的时候，使用/storage/sdcard0/Android/data/packname/files作为存储路径，而不是现在不能工作的情况。

**Comment by WhiredPlanck** [comment]
如果我没记错的话，这是 Android 11 等环境的硬性要求。目前由于同文的部分工作机制所限，暂时无法很快得做到，未来可能会考虑。感谢建议～！
