### ISSUE TITLE
关于自适应图标

### ISSUE THREAD

**Issue by WhiredPlanck** [osfans/trime#447]
cc @Bambooin @osfans 

同文目前的图标，是硬绘制成了圆形样式。虽然在大部分系统上并不算太违和，但是还是稍显不和谐。

因此我修改了原来的 SVG，换了个字体，然后用 Android Studio 的 Image Asset Studio 重新创建了一个有自适应特性的图标。它的基本样式长这样：

![ic_launcher_new-playstore](https://user-images.githubusercontent.com/47623588/124214423-c546f700-db24-11eb-979b-94ff1d7efda7.png)

字体用的是[霞鹜文楷](https://github.com/lxgw/LxgwWenKai/)，一款由字体爱好者制作的开源中文字体。

如果觉得还可以的话，我或许能在 #446 里就加进去。

**Comment by WhiredPlanck** [comment]
新的 SVG 是在修改了原 SVG 文件后另存了一份。并且用了 Android Studio 的 Vector Asset Studio 创建了一份 XML 格式。SDK version 在 26 以上的设备就可以直接用 XML 文件渲染图标而非各个大小的 PNG 图片了。

**Comment by Bambooin** [comment]
个人观点，应用图标最好还是圆润些的好

可以参考 https://github.com/rime/artworks

**Comment by Bambooin** [comment]
如果能在现在的图标基础上，添加自适应功能，可以在单独的PR里面处理

**Comment by WhiredPlanck** [comment]
> 如果能在现在的图标基础上，添加自适应功能，可以在单独的PR里面处理

好的，我回头看看

**Comment by WhiredPlanck** [comment]
> 个人观点，应用图标最好还是圆润些的好
> 
> 可以参考 https://github.com/rime/artworks

啊，真不好意思，我才想起来没给看效果图。实际的适应效果要在设备上看。我这里有一份截图。

![Screenshot_20210702_101632](https://user-images.githubusercontent.com/47623588/124259414-107efb00-db61-11eb-8282-4a735016748c.jpg)

**Comment by WhiredPlanck** [comment]
> 如果能在现在的图标基础上，添加自适应功能，可以在单独的PR里面处理

@Bambooin 已在 #448 中提交。效果图如下：

![Screenshot_20210703_103151](https://user-images.githubusercontent.com/47623588/124341086-b0ce3180-dbec-11eb-845e-3c6239fd0e9d.jpg)
