### ISSUE TITLE
安卓9.0下如何在不使用应用最上层权限下显示拼音区域呢 

### ISSUE THREAD

**Issue by ldcTnT** [osfans/trime#450]

**Comment by WhiredPlanck** [comment]
这个目前没有办法，设计上就是这个拼音编码只能在一个悬浮窗里显示的。

一个勉强的解决办法是在设置中的“键盘”页，将嵌入式编辑模式改为“编码”，这样拼音就会显示在输入框里。但在一些情况下这会造成麻烦。

我们未来会想办法改进这一问题，即不需要悬浮窗权限就能显示编码。 感谢反馈

**Comment by ldcTnT** [comment]
> 这个目前没有办法，设计上就是这个拼音编码只能在一个悬浮窗里显示的。
> 
> 一个勉强的解决办法是在设置中的“键盘”页，将嵌入式编辑模式改为“编码”，这样拼音就会显示在输入框里。但在一些情况下这会造成麻烦。
> 
> 我们未来会想办法改进这一问题，即不需要悬浮窗权限就能显示编码。 感谢反馈

谢谢回复 我最近在研究google的latinme 看看他是怎么实现的
