### ISSUE TITLE
妈耶这输入法启动好慢啊

### ISSUE THREAD

**Issue by wisim** [osfans/trime#452]
切换一次输入法要卡半天 = =

妈耶换回同文风主题速度好一点了。所以是资源加载的问题吧……

尤其是在软件里的时候，弹出个键盘都要卡一下。

妈耶！

**Comment by WhiredPlanck** [comment]
不知道你的配置文件是如何的 ……

每个人配置不一样，所以如果是资源加载问题，我可能也难以复现。

检查一下是否有体积很大的配置文件呢？

**Comment by wisim** [comment]
> 不知道你的配置文件是如何的 ……
> 
> 每个人配置不一样，所以如果是资源加载问题，我可能也难以复现。
> 
> 检查一下是否有体积很大的配置文件呢？

体积比较大的也只有词库了。我也想不好应该怎么复现 = =
目前能我感觉到的卡主要是切换不同的输入法的时候，以及在不同的软件里唤出键盘的时候，键盘弹出卡顿，偶尔会有无法切换出键盘的情况。等一段时间会好。但也不是一直这样。
猜测可能输入法在每次唤出键盘的时候会做很多复杂的工作。
另外偶尔会有通过蓝牙键盘输入文字一段时间之后，输入法才开始显示编码和上屏的情况。
以上都可以归结为卡。
= =

**Comment by WhiredPlanck** [comment]
> 以及在不同的软件里唤出键盘的时候

你是否用了非常“豪华”的皮肤呢？目前已知很漂亮的皮肤加载起来确实比较耗时间。

**Comment by WhiredPlanck** [comment]
> 另外偶尔会有通过蓝牙键盘输入文字一段时间之后，输入法才开始显示编码和上屏的情况。

如果是在横屏出现这样的情况下，参见 #434（正好也是你开的 issue），里面有提到过这个原因。

**Comment by Bambooin** [comment]
是不是开启了自动同步功能，https://github.com/osfans/trime/issues/375#issuecomment-863259630

另外使用 https://github.com/Bambooin/rimerc 这个配置试试呢，没有发现卡顿现象
⁣
⁣

**Comment by Bambooin** [comment]
无法复现

**Comment by k79e** [comment]
老手机用的就是卡, 每次出键盘就卡, 用的自带的几个主题. 
装上没多久就删了.

**Comment by WhiredPlanck** [comment]
> 老手机用的就是卡, 每次出键盘就卡, 用的自带的几个主题. 装上没多久就删了.

最近进行过一波优化，请尝试最新的[每夜版](https://github.com/osfans/trime/releases/tag/nightly) 

@k79e 还麻烦发一下老手机的型号与配置。

**Comment by k79e** [comment]
@WhiredPlanck  ram 3g , android 8.0

**Comment by WhiredPlanck** [comment]
> @WhiredPlanck ram 3g , android 8.0

@k79e 实测 RAM 2G、Android 8.1 的模拟器里也能流畅运行。词库大点的方案部署可能会慢一点。
