### ISSUE TITLE
"Put default.yaml and schema files into user directory!" Help setting up Trime from F-Droid on Android Lineage OS 18.1

### ISSUE THREAD

**Issue by tomgagdotnet** [osfans/trime#453]
Hello and sorry, unfortunately I cannot read Mandarin.

I followed https://github.com/osfans/trime/issues/299 and https://github.com/osfans/trime/issues/349 but without success.

I am specifically interested in the "bopomofo" schema, it's for helping a friend of mine.

This is the ROM and device in case it's relevant: https://forum.xda-developers.com/t/rom-unofficial-ramdisk-11-lineageos-18-1-for-galaxy-s10e-s10-s10-s10-5g-exynos.4261301/

Here is what I do:
1) git clone https://github.com/rime/plum on my laptop and make, get a bunch of .yaml files in the output subdir
2) install Trime on the phone from F-Droid (phone has no Google services, only a bare Lineage)
3) create directory /sdcard/rime and copy inside all the .yaml files from my laptop
4) launch Trime for the first time, "display over other apps" -> allow, and give storage permissions
5) Enable Trime -> OK
6) Change Keyboard -> Trime
7) Wait a minute, app is unresponsive for a while
8) Deploy -> it shows "Deploying" for just a couple of seconds, then app closes. Crash?
9) reopen Trime
10) Input -> schemas -> ERROR: "Put default.yaml and schema files into user directory!"

Same thing happens if I do "Input->reset->all 3 boxes" between steps 7) and 8)

I can see 3 new dirs inside /sdcard/rime: build, opencc, and luna_pinyin.userdb

What am I doing wrong?

Thanks in advance for any useful answer!

**Comment by Bambooin** [comment]
Hi, I follow your steps and reproduce it.

I fix it by add default.custom.yaml in rime folder.

The content of this file:
```
patch:
  schema_list:
    - schema: bopomofo
...
```

**Comment by Bambooin** [comment]
By the way, your friend can learn pinyin input method, it is easier.

The config of luna_pinyin can be found in https://github.com/Bambooin/rimerc

**Comment by tomgagdotnet** [comment]
> Hi, I follow your steps and reproduce it.
> 
> I fix it by add default.custom.yaml in rime folder.
> 
> The content of this file:
> 
> ```
> patch:
>   schema_list:
>     - schema: bopomofo
> ...
> ```

Thank you, this seems to work for me, I will ask my friend to test and will get back in a couple of days if there is any issue, otherwise this issue can be closed :)

**Comment by tomgagdotnet** [comment]
All running fine, thanks, closing this issue.
