### ISSUE TITLE
Generate empty default.custom.yaml if it's missing in deploy

### ISSUE THREAD

**Issue by Bambooin** [osfans/trime#454]
"Put default.yaml and schema files into user directory!"

We should generate empty mock default.custom.yaml, if it's missing in rime.

To reference: #453 #349 #311 #299 #292 #278

**Comment by rainhear** [comment]
> We should generate empty mock default.custom.yaml, if it's missing in rime.

- 針對方案所需文件無誤無缺，卻始終出現 `請在使用者資料夾中放入default.yaml、輸入法方案!` 提示的情況，
- 同文需實現偵測 `default.custom.yaml` 存在與否，若不存在則 `自動生成`。
- 這個對新手入門十分重要，畢竟不是每一個新人，一開始就能自行排查 `default.custom.yaml` 存在與否。
