### ISSUE TITLE
在Firefox的网页中输入时，首选可能在没有点空格的情况下上屏

### ISSUE THREAD

**Issue by cloudfish** [osfans/trime#456]
复现步骤：
1. 在Firefox中，打开任意一个有输入框的网页
2. 点击一个空白的输入框
3. 尝试输入一些中文。我这里所有全键盘的输入方案都能复现，9键的没用过不太清楚。

现象：
按键时，上一个首选可能会自动上屏。比如用袖珍简化字拼音输入“一二”，在按下r键时，“yie”对应的首选“一额”会上屏，且此时输入法的首选仍然是“一二”，对应的输入是“yier”。
如果已经输入了一些内容，则不会触发bug。所以，我通常的做法是输入完毕以后把开头多余的汉字删除。

环境：
OS版本：Android 11
Firefox版本：F-Droid中的Fennec 89.1.1
同文版本：3.2.1-20210609

**Comment by Hxppdv** [comment]
@cloudfish 我也遇到了完全相同的问题，一直无法解决，问题只会在firefox上出现

**Comment by Bambooin** [comment]
我也遇到了同样的问题，这个问题在老的移动版 Firefox 并没有，好像是从版本 87 后开始出现的

**Comment by tumuyan** [comment]
偏好设置-嵌入式编辑模式-关 可以从现象上解决问题。原理不明。

**Comment by Bambooin** [comment]
Android 11
Firefox 91.1.0
Trime 3.2.2

好像没有这个问题了，怀疑是 Firefox 最新版本修复了这个问题，大家可以验证一下

**Comment by cloudfish** [comment]
Trime 3.2.2 应该是没发布的开发版本吧？我没找到也没有条件编译，就拿原来 3.2.1-20210609 试了一下，问题还是存在。Firefox 版本是 F-Droid 里的 91.1.0。（装了官方版试了一下，也是一样。）

**Comment by Bambooin** [comment]
问题还是会出现，但是有时能复现，有时不能复现

**Comment by iosonoungatto** [comment]
确实好像又出现了，现在是打两个字或超过两个字的时候首选可能会上屏幕。
之前也有过https://github.com/osfans/trime/issues/239

**Comment by Bambooin** [comment]
> 偏好设置-嵌入式编辑模式-关 可以从现象上解决问题。原理不明。

#129 看来只能关闭嵌入模式了
