### ISSUE TITLE
九宫格方案怎么订制拼音候选

### ISSUE THREAD

**Issue by sunwgit** [osfans/trime#457]
用的用的四叶草九宫格方案，没有搜狗那种左侧拼音候选，顶部文字候选的配置，导致要翻好久候选文字才能找到正确文字

**Comment by songhongwang** [comment]
> 用的用的四叶草九宫格方案，没有搜狗那种左侧拼音候选，顶部文字候选的配置，导致要翻好久候选文字才能找到正确文字

我也想要实现拼音筛选功能，请问你实现了吗 @sunwgit

**Comment by sunwgit** [comment]
> > 用的用的四叶草九宫格方案，没有搜狗那种左侧拼音候选，顶部文字候选的配置，导致要翻好久候选文字才能找到正确文字
> 
> 我也想要实现拼音筛选功能，请问你实现了吗 @sunwgit

问了四叶草九宫格的作者，他说这个rime底层决定的，他也没办法
