### ISSUE TITLE
实体键盘模式下的中英文混输

### ISSUE THREAD

**Issue by zhouxiaobo500** [osfans/trime#46]
trime版本：160120

描述：在连接蓝牙/实体键盘后，无法像屏幕键盘一般进行中英文混输。
举例输入“这里有一个issue”，就无法通过输入回车的方式输入issue。

另外，当打开大写开关后，trime自动切换至“西文”模式，若要重新进入中文模式还需点击屏幕切换，是否能有快捷键或其他方式一边加快输入？

可能有些描述上的不确切。。
以上。

**Comment by osfans** [comment]
ctrl+shift+1好像可以切換中英文。shift也可以。不知藍牙鍵盤上是否可以。

**Comment by zhouxiaobo500** [comment]
蓝牙键盘输入 Ctrl+Shift+1 直接就闪退了。@osfans

**Comment by osfans** [comment]
應該0324版本解決了閃退的問題。

**Comment by zhouxiaobo500** [comment]
试了一下，基本已解决。虽然不能用回车敲出来，但是可以用空格嘛。
谢谢了！
