### ISSUE TITLE
输入法卡死。

### ISSUE THREAD

**Issue by aaa1999** [osfans/trime#468]
请问这个输入法，你在软件页面想改点配置的时候，有时候就会卡死，必须重启才行，请问这个原因是什么啊。

**Comment by Bambooin** [comment]
可能是在部署，能整理复现步骤吗

**Comment by aaa1999** [comment]
> 可能是在部署，能整理复现步骤吗

部署，还有一些操作，按了之后就再也没有反应了。这个时候必须重启手机才能使用这个输入法。

**Comment by aaa1999** [comment]
> 可能是在部署，能整理复现步骤吗

好的，我再使用一段时间后再来反馈一些容易卡死的步骤。

**Comment by walk143** [comment]
卡死前`rime`路径下是否存在`trime.yaml`文件

**Comment by Bambooin** [comment]
无法复现
