### ISSUE TITLE
跟旋转屏幕有关的两个崩溃现象

### ISSUE THREAD

**Issue by xiaoqun2016** [osfans/trime#47]
新春快乐！  
过年期间，发现之前说的同文在微信公众号界面崩溃是有规律的。  
重现的方法如下：  
1. 打开任意一个微信公众号  
2. 持手机**侧卧**，就像下面这幅图中这样  
   ![ 侧卧持手机](http://pic.enorth.com.cn/0/10/91/67/10916738_397950.jpg)  
3. 点击公众号下方的输入框，**呼出**同文的键盘  
4. 输入任意字上屏或者什么也不做  
5. 点击返回键收起键盘  
6. 再点击此公众号的任意一篇文章，在载入文章的过程中，同文输入法就会崩溃  
- 崩溃的概率在90%以上  
- 只在人侧卧（_手机侧立_）时会这样，平放或直立手机都不会崩溃  
- 打开或关闭屏幕旋转功能都一样  

---

还有一个相关的问题，在qq上旋转屏幕会崩溃  
1. 打开手机的**屏幕旋转**功能  
2. 打开qq或者qq国际版  
3. 在好友对话界面，点击输入框，**呼出**同文键盘  
4. 不做任何输入，直接按返回键**收起**键盘  
5. **旋转手机屏幕到另一个方向**，同文输入法马上就崩溃  
- **这两个问题是从`20151222版`开始才有的，试过`1202`和`1204`版，都没问题。**  
- 试过删除rime文件夹，不加载任何方案，也一样。  
- 在另一部安卓2.3.5的手机上也可以重现这个问题

**Comment by osfans** [comment]
哈哈，側臥的是樓主自拍嗎？

**Comment by xiaoqun2016** [comment]
只是试试看在issue中贴图的方法对不对。必须声明一下**图片来自网络，版权归原作者所有**  
侧卧崩溃这种情况只有我这边会出现吗？

**Comment by osfans** [comment]
我還沒有試呢，今天有空要試下。

**Comment by osfans** [comment]
沒有再發現這個問題了？

**Comment by xiaoqun2016** [comment]
@osfans 问题还在，如果只有我这边会这样，那也没准是我自己手机的问题。这个问题先不管了。  

另外，我在wiki上试写了一些内容，没写完，主页还空荡荡的，老大有时间来写一下吧，顺便审核一下我写的那部分，估计有些地方我的理解有偏差。

**Comment by osfans** [comment]
看到你寫的了，我把它設爲主頁了。我複製出來的話，再打開。我發現我手機的重力感應器壞了，所以旋轉不了。

**Comment by xiaoqun2016** [comment]
你看rime的wiki主页是佛振写的，主页还是由软件的作者来写比较合适，这是别人替代不了的。我只是做一些辅助的工作，那些内容也不太适合放在主页。

**Comment by osfans** [comment]
哈哈，辛苦啊。rime你用的比我多，比我熟。

**Comment by xiaoqun2016** [comment]
不懂原理的实践就是瞎折腾。看不懂源码的人终究只是个用户，这方面我还差得远 :grin:

**Comment by DaengGWokFook** [comment]
這個問題最新版也有，橫轉豎，豎轉橫都會崩溃

**Comment by DaengGWokFook** [comment]
我的手機型號是LG L90 D415
安卓版本4.4.2

**Comment by DaengGWokFook** [comment]
解決旋轉問題就更新到release吧。

**Comment by osfans** [comment]
已經上傳：https://github.com/osfans/trime/releases/download/v3.0-beta2/trime-20160517.apk
