### ISSUE TITLE
手机怎么导出词库

### ISSUE THREAD

**Issue by aaa1999** [osfans/trime#471]
请问手机该怎么导出词库呀。找了好久都没有看到该如何把词库导出，或者导入的方法。电脑上可以
![image](https://user-images.githubusercontent.com/49224989/128447723-13b0b760-9c30-471e-9369-4cfabf943814.png)
在这里导出，那手机上应该怎么导出和导入呢。谢谢您。

**Comment by Bambooin** [comment]
备份: 可以在 输入->同步菜单里面，同步成功后，会在 rime/sync 文件夹里面
导入: 可以把备份的文件直接放在 rime 文件夹里面重新部署即可

可以参考现有配置 https://github.com/Bambooin/rimerc

**Comment by aaa1999** [comment]
好的，明白了。谢谢。
