### ISSUE TITLE
考虑废除现有符号键盘

### ISSUE THREAD

**Issue by tumuyan** [osfans/trime#474]
目前大厂符号键盘/字母键盘切换是这样的
![IMG_20210807_090938.jpg](https://user-images.githubusercontent.com/3126801/128583620-5438c88a-4d08-48e1-99a5-b45758f7784c.jpg)

同文是这样的(基本大家抄的都是同一套)
![IMG_20210807_091646.jpg](https://user-images.githubusercontent.com/3126801/128583622-cecf840e-e78f-49a1-9dec-7cd61bc4c6f2.jpg)

主要差异几个方面:
- 同文不支持滚动
- 同文没有最近使用的符号列表
- 切换符号键盘时,大厂自动隐藏候选栏.实际上输入符号的确不需要候选栏,同文浪费了键盘空间
- 同文切换横竖屏无法自动重新排布符号键盘,导致键盘空间浪费
- 如果不锁定符号键盘,大厂输入法在输入一次符号后,自动返回原键盘(我认为同文可以用长按来优化,如果长按某个符号,直接锁定,否则上屏符号并返回原键盘布局:当然加锁定键也可以;甚至可以加个开关,定义进入符号键盘是否默认只输入一个符号)

所以考虑重写符号键盘的布局
看大家的想法是怎么样的?(比如反对的理由?)
就符号键盘而言,有没有其他建议的地方?

**Comment by tumuyan** [comment]
另一个思路是, 不动现有符号键盘,使用弹出悬浮窗的方式解决问题(思路又回到了上一个issue).
我现在其实蛮纠结的,到底是动键盘还是不动键盘做悬浮窗?
做悬浮窗好处是扩展性强,但是需要找合适的库插进去,也可能不够美观(毕竟和现有键盘布局画风都不一样了).
动键盘的好处是UI和现有键盘客户很好融合,但是后边再扩展功能可能还是比较麻烦.

**Comment by ameaninglessname** [comment]
重写布局会使现有的主题文件失效么

**Comment by tumuyan** [comment]
> 重写布局会使现有的主题文件失效么

不会失效.可以正常使用
但是必须修改主题才能获得新布局带来的新体验(改动不会太复杂)

**Comment by coxde** [comment]
还是滚动比较好看一点。

**Comment by ameaninglessname** [comment]
支持动键盘,功能上,可以适当重构框架来实现更好的拓展性?可能工作量会更大

**Comment by walk143** [comment]
重写布局说的是后台组装按键的部分吗。期待这样的：
方案里定义一个符号列表，后台自动布局排列，超出可滑动（可一定数量后可换页）。

**Comment by tumuyan** [comment]
已经实现1-4  

由于重新布局, 符号键盘一屏显示按键数量轻松翻倍.横屏自动显示更多按键.  
![IMG_20210825_081639.jpg](https://user-images.githubusercontent.com/3126801/130706423-a5164c36-b734-40bd-bf40-48b465ff7fe9.jpg)

配置极致简单,根据实际需求修改按键相当轻松,皮肤行数锐减.
![Screenshot_2021-08-25-08-18-08-562_nextapp.fx.jpg](https://user-images.githubusercontent.com/3126801/130706515-21e17843-8087-4420-b067-73c3cf01b67a.jpg)

**Comment by ameaninglessname** [comment]
现在默认emoji不够全,其实是配置问题么

**Comment by tumuyan** [comment]
> 现在默认emoji不够全,其实是配置问题么


当然是配置问题了, trime的键盘上的emoji完全跟随皮肤. 符号数量够用就行,不够自己加,没用的就删除.
