### ISSUE TITLE
键盘部分区域颜色无法设置

### ISSUE THREAD

**Issue by QiangF** [osfans/trime#476]
目前的 trime.custom.yaml:

    comment_text_color: 0x7b868c #提示
    key_border_color: 0xffeff1 #按鍵邊框
    key_symbol_color: 0xff6b73 #按鍵符號
    key_text_color: 0xf7474f #按鍵文字
    on_key_text_color: 0xf7474f #按鍵打開狀態文字
    border_color: 0xffc7ca #邊框
    candidate_separator_color: 0xc1c7ca #候選分割背景
    on_key_back_color: 0x03948e #按鍵打開狀態背景
    hilited_text_color: 0xf3948e #標明編碼
    preview_text_color: 0xf3948e #按鍵提示文字
    candidate_text_color: 0xf00000 #候選文字
    text_color: 0xffff00 #編碼
    off_key_text_color: 0xff0f00 #按鍵關閉狀態文字
    shadow_color: 0x00ff00 #按鍵文字陰影
    hilited_candidate_text_color: 0xffff00 #標明候選文字
    hilited_comment_text_color: 0xffff00 #標明提示
    hilited_key_symbol_color: 0xffff00 #標明按鍵符號
    hilited_key_text_color: 0xffff00 #標明按鍵文字
    hilited_off_key_text_color: 0xffff00 #標明按鍵關閉狀態文字
    hilited_on_key_text_color: 0xffff00 #標明按鍵打開狀態文字
    label_color: 0xffff00 #標籤
    hilited_back_color: 0x00000000 #標明編碼背景
    hilited_candidate_back_color: 0x00000000 #標明候選背景
    hilited_key_back_color: 0x00000000 #標明按鍵背景
    hilited_off_key_back_color: 0x00000000 #標明按鍵關閉狀態背景
    hilited_on_key_back_color: 0x00000000 #標明按鍵打開狀態背景
    back_color: 0x00000000 #候選區背景
    key_back_color: 0x00000000 #按鍵背景
    off_key_back_color: 0x00000000 #按鍵關閉狀態背景
    preview_back_color: 0x00000000 #按鍵提示背景
    text_back_color: 0x00000000 #編碼區背景
    keyboard_back_color: 0x00000000 #鍵盤背景
![微信图片_20210808120658](https://user-images.githubusercontent.com/8192731/128620372-628bc95d-87fd-4064-b7e0-43a3a5f41ad1.jpg)

**Comment by QiangF** [comment]
我配置的排布比较紧凑，完整的配置文件 https://gist.github.com/QiangF/fc4779ef61708eaa284bd28b1a0ec257

**Comment by tumuyan** [comment]
你写了一大堆0x00000000的色彩, 0x00指的就是透明啊

**Comment by QiangF** [comment]
头都大了，还是没找到图里的两个亮区的设置：
![526738622](https://user-images.githubusercontent.com/8192731/128797164-e4feea1b-0e0f-4180-9045-d7890dee8fa2.jpg)

**Comment by QiangF** [comment]
无论怎么改，白色区域就是白色，我也找不到我的设置哪里有白色

**Comment by QiangF** [comment]
很奇怪，弄成透明就变黑了
![Uploading 896150364.jpg…]()

**Comment by atlanticfirst** [comment]
ni那里是    text_color: 0xffff2a00 #编码这个来着，，前面哪个表情应该是    hilited_text_color: 0xff000000 #高亮编码。这个软件配置文件的说明好容易搞混，缺少图文说明，光靠文字根本不知道哪个是哪个。。。。。
