### ISSUE TITLE
请问如何合并词典

### ISSUE THREAD

**Issue by qjjlb** [osfans/trime#479]
在Windows上有一个合并词典快照的选项，可以合并用户词典，同文上是否有，

**Comment by WhiredPlanck** [comment]
> 在Windows上有一个合并词典快照的选项，可以合并用户词典，同文上是否有，

目前开放的设置里还没有，但我们能考虑在未来添加为新功能。感谢支持

**Comment by WhiredPlanck** [comment]
> 在Windows上有一个合并词典快照的选项，可以合并用户词典，同文上是否有，

可以说一下用的哪个 Windows 版吗？

**Comment by qjjlb** [comment]
版本	Windows 10 专业版
版本号	21H1
操作系统内部版本	19043.1151

**Comment by WhiredPlanck** [comment]
> 版本 Windows 10 专业版
> 版本号 21H1
> 操作系统内部版本 19043.1151

噢，我说的不是 Windows 的版本，我是问你在 Windows 上用的是哪个软件，版本是什么 😃

**Comment by qjjlb** [comment]
小狼亳 [weasel 0.14.3](https://github.com/rime/weasel/releases/tag/0.14.3)

**Comment by WhiredPlanck** [comment]
> 小狼亳 [weasel 0.14.3](https://github.com/rime/weasel/releases/tag/0.14.3)

好的，我去看看源码

**Comment by starriddle** [comment]
这功能刚需啊，windows、linux、android，多平台都是用的rime，希望可以将词典合并
