### ISSUE TITLE
Nexus5 Android6.0.1無法輸入漢字

### ISSUE THREAD

**Issue by eailfly** [osfans/trime#48]
我在Nexus5、Android6.0.1安裝了trime-20160120.apk，但是發現不能輸入漢字，是不兼容嗎？

![screenshot_20160222-122253](https://cloud.githubusercontent.com/assets/3424220/13209528/c0d657dc-d95f-11e5-8563-b6fda6ff23b1.png)

**Comment by osfans** [comment]
應該不是吧？重新部署看看。

**Comment by eailfly** [comment]
没用，重新部署了还是没有汉字显示。
我是把fcitx-rime里的default.yaml、luna_pinyin_simp.schema.yaml、double_pinyin_flypy.schema.yaml三个文件复制到/sdcard/rime目录下的，步骤对吧？

**Comment by osfans** [comment]
噢，不對，少個*.dict.yaml。可能是在/usr/share/rime-data目錄下。
或者從網上直接下載：
https://github.com/rime/brise/tree/master/preset

**Comment by eailfly** [comment]
OK了，是我没有搞明白，谢谢
