### ISSUE TITLE
Develop Question: Lift the minSdkVersion to 16?

### ISSUE THREAD

**Issue by WhiredPlanck** [osfans/trime#484]
Google 已经在一段时间前正式弃用 SDK 小于 16 的开发支持了。  目前较新版本的 Android Studio 的不少新建操作也要求最低 SDK 版本要大于等于 16，一些函数/API 的使用也至少需要 SDK 大于等于 16 才能使用，否则就得另想办法。

虽然目前还可以自己手动创建满足需求的类或方法，但考虑到日后这会变得越来越麻烦，且小于 16 的平台的占比估计很小很小了，它们也有很大概率并不会使用同文。

不知道是否现在就可以把最小 SDK 版本升到 16 呢？

**Comment by tumuyan** [comment]
实际上很多地方都是直接写了判断API level的代码，如果是，那么执行，如果不是，根本不处理——只是单纯能安装不报错的程度，实际功能可能根本没有。
我版本最低的设备是4.0的电子书（那反应速度根本没法用来打字），所以我不反对。
但是这口子一旦开了就停不下来了，很快就发现得加到21。所以可能需要讨论的可能是16到底够不够，到底哪些东西需要更高的API level需要到多少…

**Comment by Bambooin** [comment]
看了一下
支付宝: 18
微信: 21
