### ISSUE TITLE
為什麽候選項沒有序號啊? 用的實體鍵盤, 候選項在第幾位很難看出來!!!

### ISSUE THREAD

**Issue by telanxrays** [osfans/trime#485]
![Screenshot_20210813_164301_com foxdebug acodefree](https://user-images.githubusercontent.com/54123851/129330521-6465c4dc-70d1-4d93-bf93-c5bdb54c8b10.jpg)

換了很多個皮膚, 都一樣, 是需要改什麽配置文件? 但搜了半天也沒發現有說怎麽改的.

有人知道怎麽弄不? 給每個候選項添加一個數字序號. 我平板用的實體鍵盤, 不需要用手指戳, 所以沒有序號很難受, 打字很慢, 候選長度會變動, 根本不知道在後面的選項到底是8還是9.

多謝

**Comment by tumuyan** [comment]
据我所知，候选栏代码里没有这一部分。你可以使用悬浮窗，参考图：
![Screenshot_2021-08-13-18-38-34-299_nextapp fx](https://user-images.githubusercontent.com/3126801/129345186-bc48c984-99b5-486f-ad82-70cfab29dd0e.jpg)

**Comment by telanxrays** [comment]
@tumuyan 謝謝解答, 我去看看配置, 貌似我的鍵盤設置裏就是開的'顯示懸浮窗口'項, 但打字的時候并沒有什麽懸浮窗口. 我再瞧瞧配置文件裏是不是跟你的不一樣.

**Comment by telanxrays** [comment]
@tumuyan 哥們, 看起來沒甚卵用, 我把主題改成同文風, 然後tongwenfeng.trime.yaml這個配置文件的comment_on_top和horizontal這兩個值都改成false, 結果也一樣, 候選界面并沒有位置上的變化, 無論是實體鍵盤模式亦或是虛擬鍵盤模式, 都沒有看到候選項有序號, 配色也切過, 也沒什麽鳥用, 另外你這個BILIBILI的配色默認里好像沒有.

**Comment by tumuyan** [comment]
你需要参考截图修改layout小节，设置min_length = 1 ，让全部候选词显示到悬浮窗。其他细节参考wiki章节。

https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3#4%E6%82%AC%E6%B5%AE%E7%AA%97%E5%8F%A3

**Comment by telanxrays** [comment]
@tumuyan 我再研究配置文件看看, 這輸入法配置細節有点多, 剛用沒多久, 難以一下吃透, 多謝指教.

**Comment by telanxrays** [comment]
@tumuyan 請問下你用的是最新的3.2.1版本嗎? 另外能不能把你的那個主題文件派對之星的trime.yaml文件全部內容發上來看一下? 我想參考下其他的鍵值, 說不定可以找到原因. 多謝了.

**Comment by telanxrays** [comment]
@tumuyan 嘿! 真的可以了! 就是最小詞長值改成1就行了! 就出懸浮窗了! OH YEAH! 哈, 超感謝!
![強吻, 親親](https://user-images.githubusercontent.com/54123851/129376105-be014e1d-3b1a-4d41-99eb-96a6c34e636e.gif)

**Comment by telanxrays** [comment]
@tumuyan 
![Screenshot_20210813_225736_com foxdebug acodefree](https://user-images.githubusercontent.com/54123851/129376942-ffbe369e-fcb3-4817-a1d5-3edaa799d664.jpg)
再次感謝~
