### ISSUE TITLE
老版本安卓系統(5.1)不彈出打字框(虛擬鍵盤)

### ISSUE THREAD

**Issue by telanxrays** [osfans/trime#486]
加載失敗的時候底下輸入框區域一團黑, 然後就彈出一個提示說加載輸入法失敗, 問是否清除數據.

手上有幾部老手機, 想倒騰裝個rime輸入法, 一部是4.4.4版本系統, 一部是5.1版本, 裝是能裝上, 設置面板也能打開, 但一切換輸入法點輸入焦點就死活不彈出虛擬鍵盤, 輸入>方案設置裏也讀取不出配置文件中已載入的輸入方案.

其他的平板手機系統在10左右的都正常, 就老版本不行, 折騰了好一會, 用別人的custom配置扔進去重新部署也沒用, 似乎是繪圖API和舊系統不兼容.

有沒有人搞咕出解決方案, 要是因為舊版的功能缺失導致的話看起來只能放棄在舊版安裝同文輸入法的想法了.

**Comment by WhiredPlanck** [comment]
可否说说用的是哪个版本？

因为手边没有比较老的设备，所以一直没有测试过旧版本 Android 的运行情况，很抱歉。之后我找个办法多照顾一下。

**Comment by telanxrays** [comment]
@WhiredPlanck

有個是5.1版本的, 還有個是4.4.4版本的, 安卓系統.

 用模擬器沒法測試嗎? 不是開發人員但之前用過安卓模擬器, 似乎可以選擇不同的安卓版本運行環境.

權限上應該是沒問題, 都是給了全部的權限, 兩個系統的狀況一樣, 打不開輸入框.

多謝關注, 辛苦了.

**Comment by WhiredPlanck** [comment]
> @WhiredPlanck
> 
> 有個是5.1版本的, 還有個是4.4.4版本的, 安卓系統.

Em，同文的版本就是当前 Release 里发放的吗？

> 用模擬器沒法測試嗎? 不是開發人員但之前用過安卓模擬器, 似乎可以選擇不同的安卓版本運行環境.

模拟器需要 x86，而且我机子上的虚拟机经常卡死，导致我并不太想。

> 權限上應該是沒問題, 都是給了全部的權限, 兩個系統的狀況一樣, 打不開輸入框.
> 
> 多謝關注, 辛苦了.

我正好从别人那边拿到了部旧手机，应该能帮助测试吧 ~

**Comment by telanxrays** [comment]
@WhiredPlanck 對的, Google Play Store裏面的3.1.3和最新的3.2.1都裝了, 都試過, 一樣狀況.

**Comment by rainhear** [comment]
- 已知最後一版可支持 `Android 5.1` 系統的 `Trime` 前端版本為 `20190313`，
- 但不知何故 [Releases](https://github.com/osfans/trime/releases) 頁面不少舊版下載鏈接缺失了，
- 可以進 `同文堂 QQ 群` [811142286](https://jq.qq.com/?_wv=1027&k=lCxEgOe1) 求助群友分享此版本。

**Comment by telanxrays** [comment]
@rainhear 多謝信息提供, 好像確實發佈歷史里沒有2019的版本.
