### ISSUE TITLE
翻页后不是在下一页的首部

### ISSUE THREAD

**Issue by osfans** [osfans/trime#49]
http://tieba.baidu.com/p/3917536050?pid=85790187972#85790187972

**Comment by xiaoqun2016** [comment]
补充一个相关的问题，候选项的宽度，英文与中文相同。这会导致英文词条的左右两边留下很大的空白。你可以看一下新的字集过滤器，在状态栏中`UTF-8` `GB2312`占用的宽度很大，显得不够紧凑

**Comment by osfans** [comment]
@xiaoqun2016 嗯，所以要改成半個漢字。

**Comment by Bambooin** [comment]
最新版已经解决翻页的问题
