### ISSUE TITLE
剪贴板管理器 添加一个空行为

### ISSUE THREAD

**Issue by walk143** [osfans/trime#493]
**Is your feature request related to a problem? Please describe.**
当剪贴板管理器选择了fv的“fv剪贴板”后，fv未启动时，复制会导致输入法面板消失（或许是程序内部已经崩溃）。选择首选“蓝牙”后，复制内容会弹出蓝牙界面

**Describe the solution you'd like**
需要增加一个空行为，即没有额外剪贴板管理器时，不影响程序输入

**Describe alternatives you've considered**

**Additional context**

**Comment by tumuyan** [comment]
这问题简单，我来修吧。
两方面：1 用try包裹，避免输入法崩溃  2 给选择列表增加一个空值选项
实际上已经在考虑废弃外置剪贴板管理器，改为内置了...

**Comment by walk143** [comment]
感谢。
诸如此类的行为，能否开一个全局线程池处理，至少是异步。和主程序的逻辑关系不大

**Comment by tumuyan** [comment]
这个issue也可以close了，调用其他剪贴板管理器效果并不好，目前已经改为内置剪贴板

**Comment by walk143** [comment]
#508  解决
