### ISSUE TITLE
是否内置输入方案文件？给普通用户选择的方便，使得新手不需要进行文件操作

### ISSUE THREAD

**Issue by UnsGentoals** [osfans/trime#496]

**Comment by telanxrays** [comment]
沒辦法, 這輸入法就是配置方法比較特殊, 但其實你只要活用搜索, 很多都是能夠很快速解決的, 比如雙拼方案, 只需要搜索"trime 雙拼配置", 就有github網頁出來了, 然後把配置文件下載扔到rime主目録, 再重新部署就能用切換鍵切換出來了.

**Comment by Bambooin** [comment]
可以参考另外一个开箱即用的配置

https://github.com/Bambooin/rimerc

**Comment by UnsGentoals** [comment]
> 可以参考另外一个开箱即用的配置
> 
> https://github.com/Bambooin/rimerc

在项目的介绍页面看到这个项目了，就是想问是否有可能内置这个项目的文件在android的文件中，然后给用户一个选择的按钮，这样方便很多新手用户。

**Comment by Bambooin** [comment]
> > 可以参考另外一个开箱即用的配置
> > https://github.com/Bambooin/rimerc
> 
> 在项目的介绍页面看到这个项目了，就是想问是否有可能内置这个项目的文件在android的文件中，然后给用户一个选择的按钮，这样方便很多新手用户。

以前提议过内置方案，但是没被采纳。rimerc 配置仅仅包含 luna-pinyin，也不太适合其他五笔用户的需求。

**Comment by UnsGentoals** [comment]
> > > 可以参考另外一个开箱即用的配置
> > > https://github.com/Bambooin/rimerc
> > 
> > 
> > 在项目的介绍页面看到这个项目了，就是想问是否有可能内置这个项目的文件在android的文件中，然后给用户一个选择的按钮，这样方便很多新手用户。
> 
> 以前提议过内置方案，但是没被采纳。rimerc 配置仅仅包含 luna-pinyin，也不太适合其他五笔用户的需求。

其实可以找到不同的配置文件内置，因为我在使用mac 版的输入法就没有手动修改文件，也有可以接受的使用体验。
是因为开源协议难以协调所以不能内置吗？
还是其他？

**Comment by Bambooin** [comment]
猜测可能是输入方案太多，定制化太多，没法满足所有人的特定需求。

**Comment by ghost** [comment]
> 可以参考另外一个开箱即用的配置

有没有极点五笔词库推荐个？极点的历史比较悠久，网上很多五笔教程推荐极点输入法。
