### ISSUE TITLE
“清屏按鍵”失效

### ISSUE THREAD

**Issue by zaqzrh** [osfans/trime#5]
旧的Trime的清屏按鍵
-{text：〈clear〉}失效！

**Comment by osfans** [comment]
不要着急，等把keyboard.yaml獨立出來，一起弄。

**Comment by zaqzrh** [comment]
Escape键应是通用，又符合rime的格式了。
把-{code：Escape}代替-{text：〈clear〉}用用先。

**Comment by osfans** [comment]
你那也可以編譯了？

**Comment by zaqzrh** [comment]
我不會編譯的，我只是使用Apktool解包把trime.yaml改了一下。發現Escape能用。

**Comment by osfans** [comment]
原來如此，那escape會隱藏窗口嗎？不隱藏的話，倒是符合你的要求了。

**Comment by zaqzrh** [comment]
不隱藏，不过键位上显示o字符样

**Comment by osfans** [comment]
爲什麼是o呢？我是畫的清屏按鍵。或者，你用label自定義看看？

**Comment by zaqzrh** [comment]
如果改為-{label:Escape}那麼按鍵消失了(空缺位)

**Comment by osfans** [comment]
要同時加。

> code: Escape, label: 清空

**Comment by zaqzrh** [comment]
如果-{code:Escape, label:淸空}這樣，不能用了，出現「很抱歉，同文輸入法平台已停止運行。」

**Comment by osfans** [comment]
要逗號的

**Comment by osfans** [comment]
空格好像也要

**Comment by zaqzrh** [comment]
-_{code:_Escape,_label:—淸空}

**Comment by osfans** [comment]
label後好像也要空格。

**Comment by osfans** [comment]
這是yaml的格式，具體我也不清楚。

**Comment by zaqzrh** [comment]
-_{code:_Escape,_label:—淸空}不能
-_{code:—Escape,—label—:—淸空}不能
-_{label:—"清空",_code:_Escape}也不能

**Comment by osfans** [comment]
我這測試沒有問題。

``` diff
diff --git a/assets/trime.yaml b/assets/trime.yaml
index dbbe358..d04834e 100644
--- a/assets/trime.yaml
+++ b/assets/trime.yaml
@@ -43,7 +43,7 @@ keyboard:
   - {text: b}
   - {text: n}
   - {text: m}
-  - {code: BackSpace, width: 20}
+  - {code: Escape, label: 清空, width: 20}
   - {label: '123', switch: 1, width: 15, code: <switch>, symbol: '...', symbolCode: Menu}
   - {symbol: '"', text: "'"}
   - {symbol: '<', text: ','}
```

**Comment by osfans** [comment]
clear也可以，剛給了一個默認圖標：

>  {code: Clear }
