### ISSUE TITLE
0328版切换方案会卡住

### ISSUE THREAD

**Issue by xiaoqun2016** [osfans/trime#50]
最新这三版都会这样，部署时也会这样。  
补充：  
全部初始化，只保留朙月拼音，部署时也会卡住。换回旧版就ok。

**Comment by osfans** [comment]
啊，看來又是多線程的原因。那要換回舊的庫了。

**Comment by xiaoqun2016** [comment]
没事的，我们可以先用旧版。多线程慢慢调整

**Comment by osfans** [comment]
重新更新了328，幫忙試試

**Comment by xiaoqun2016** [comment]
解决了，现在不卡了

**Comment by osfans** [comment]
多謝及時發現。我安卓6的，這幾個版本都不卡。看來舊版本的安卓只能用舊的boost庫。

**Comment by xiaoqun2016** [comment]
我这边可以抓日志，要不要发给你看看？

**Comment by osfans** [comment]
好啊，發出來看看。

**Comment by xiaoqun2016** [comment]
从开始切换方案到系统提示同文无响应，然后点击确定结束进程。抓了两次，一次是单独记录同文的日志，另一次是记录全部的。  
http://pan.baidu.com/s/1i5tVKFV

**Comment by osfans** [comment]
沒有明顯的異常，就是切換時後臺rime卡住了。多謝了！

**Comment by osfans** [comment]
今天更新了版，opencc升級到1.0.4
又把編譯器換回cmake+clang，生成的apk會小些。
不確定有沒有卡住的問題。我這測試沒有問題。

**Comment by xiaoqun2016** [comment]
@osfans 会卡住，跟0328版一样。

**Comment by osfans** [comment]
好吧，我換回去了，還用舊的boost庫。但是用新的編譯方法，apk會小些。
多謝測試！

**Comment by xiaoqun2016** [comment]
现在不卡了
