### ISSUE TITLE
不能记忆输入法状态

### ISSUE THREAD

**Issue by QiangF** [osfans/trime#500]
重现方法：

1. 主键盘切换到英文模式，当前可输入字母
2. 切换到数字键盘
3. 切换回主键盘，希望是1里面的英文模式，但是又回到中文了：(

**Comment by walk143** [comment]
```java
preset_keyboards:
  default:
    name: 預設40鍵
    author: "osfans <waxaca@163.com>"
    ascii_mode: 0
    width: 10
    height: 44
    lock: true #切換程序時記憶鍵
```

**Comment by QiangF** [comment]
好像不行： https://gist.github.com/QiangF/5a32b3818f8d1895223aefb64087e56b

**Comment by walk143** [comment]
使用gist中的主题无问题。qwerty0为英文切换到符号，返回后还是英文。你使用的是最新版本的trime吗。

**Comment by QiangF** [comment]
嗯，重新部署一下好像又好了。
