### ISSUE TITLE
通过“夜间模式”自动切换键盘配色

### ISSUE THREAD

**Issue by coxde** [osfans/trime#504]
#437 引入了自适应的夜间模式，可以自动改变 App 的亮色/暗色。请问能否据此改变键盘的配色？如“亮色”允许指定一种键盘配色，“暗色”则指定另一种键盘配色，并自适应系统设置以自动改变配色？

**Comment by tumuyan** [comment]
皮肤文件已经是一座屎山了.
影响背景和文字外观的,一方面是配色,一方面是背景图.配色本身嵌套了好几层, fallback_colors指定了配色,preset_color_schemes提供了配色方案, key又在指定配色. 

理论上讲,应该是一套皮肤中,preset_color_schemes提供多套配色,实际上很多人的皮肤用了大量图片,而配色是写死的一套. 而有多套配色的皮肤,又得手动写参数指定自动切换哪个…

**Comment by Bambooin** [comment]
配色问题还是由用户自己选择
