### ISSUE TITLE
trime状态栏上的菜单项默认显示在左边，如何配置，让菜单项局右显示？

### ISSUE THREAD

**Issue by iT-Boyer** [osfans/trime#505]
如 ：中英文切换菜单，在右边显示。

**Comment by tumuyan** [comment]
没有参数.  
替代方案两个:  
1. 做一个空的switch占位
2. 不使用候选栏,做一排键盘按键

**Comment by iT-Boyer** [comment]
很感谢有替代方案。

有写配置还不太熟悉，有具体操作步骤吗？

**Comment by iT-Boyer** [comment]
很感谢提供思路。

有些配置还不太熟悉，有具体的操作步骤吗？

**Comment by tumuyan** [comment]
> 很感谢提供思路。
> 
> 有些配置还不太熟悉，有具体的操作步骤吗？


参见附图修改方案(不是主题)

![Screenshot_2021-08-25-12-27-43-193_nextapp.fx.jpg](https://user-images.githubusercontent.com/3126801/130726668-2dbc3b99-a135-4caa-9963-0005678a7543.jpg)

**Comment by iT-Boyer** [comment]
使用空格填充菜单项的宽度，可以实现。

1. 新建switch占位菜单 有实现案例吗？
[参考](https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3#2switches)
```
  # 这是一个空按键，按下去不会执行任何动作
  - options: [ _key_VoidSymbol ]
     states: [ "    " ] #空键的宽度由这里的空格决定
```
2. 新增一排按键的配置该怎么操作？

我针对这两个问题，搜了下，没有找到相关资料，希望能帮解惑。谢谢了。

**Comment by flypyxh** [comment]
这个建议我很早就提过，osfans当时也认可，结果后来没实现，无障碍应该实现了，主要我是想放那个隐藏键盘的键，无奈只能通过中间加空格的方式，把隐藏键挤到右侧，但这样是不完善的，因为各人手机分辨率不同，主题效果就不同，有的可能没挤到右侧，只挤到中间，有的可能挤出了右侧。
