### ISSUE TITLE
[讨论]Config类的颜色/图片调用

### ISSUE THREAD

**Issue by tumuyan** [osfans/trime#512]
打算对config类做一些调整。

1. 皮肤参数位置进行调整。背景图/色从style统一移动到fallback_colors，然后由preset_color_schemes来定义。目前线上代码应该只涉及到：root_background  candidate_background  layout/background(在调整时打算改为window_background，让命名更恰当)   
并且，前两个参数是我近期增加的，影响应该不大。因此不对原有皮肤的相关参数做兼容。
如果有反对意见或者补充，可以回复

2. 在这里似乎是没有必要做null判断的？
https://github.com/osfans/trime/blob/74b6afb4550d19b06b56e0f9ab9ec11bbedd6289/app/src/main/java/com/osfans/trime/setup/Config.java#L730

```
    Object o = getColorObject(key);
    if (o == null) {
      o =
          ((Map<?, ?>) Objects.requireNonNull(presetColorSchemes.get(getColorSchemeName())))
              .get(key);
    }

```
因为这段代码调用，本质就是getColorObject代码的一部分。如果getColorObject获取的结果是null，那么这里重新读取得到的结果还是null
```
  private Object getColorObject(String key) {
    String scheme = getColorSchemeName();
    final Map<?, ?> map = (Map<?, ?>) presetColorSchemes.get(scheme);
    if (map == null) return null;
    getPrefs().getLooks().setSelectedColor(scheme);
    Object o = map.get(key);
    String fallbackKey = key;
    while (o == null && fallbackColors.containsKey(fallbackKey)) {
      fallbackKey = (String) fallbackColors.get(fallbackKey);
      o = map.get(fallbackKey);
    }
    return o;
  }

```
当忽略null判断时，这两个方法又完全相同了
```

  private Drawable getCurrentColorDrawable(String key) {
    final Object o = getColorObject(key);
    return drawableObject(o);
  }

  public Drawable getColorDrawable(String key){
    final Object o = getColorObject(key);
    return drawableObject(o);
  }

```

而getCurrentColorDrawable的调用只有一处，并且这里的null判断也毫无意义？：

```
        final Config config = get(context);
        Drawable d = config.getCurrentColorDrawable(s);
        if (d == null) d = config.drawableObject(o);
        return d;

```
因此可以直接把getCurrentColorDrawable  getColorDrawable两者合并 ？请大家看下我的理解对不对

**Comment by rainhear** [comment]
> 1. 皮肤参数位置进行调整。背景图/色从style统一移动到fallback_colors，然后由preset_color_schemes来定义。目前线上代码应该只涉及到：root_background candidate_background layout/background(在调整时打算改为window_background，让命名更恰当)

按設計分類來講，遷移到 `fallback_colors` 並支持 `preset_color_schemes` 自定義，確實更有條理性。

**Comment by rainhear** [comment]
> 1. 皮肤参数位置进行调整。背景图/色从style统一移动到fallback_colors，然后由preset_color_schemes来定义。目前线上代码应该只涉及到：root_background candidate_background layout/background(在调整时打算改为window_background，让命名更恰当)

按設計分類來講，遷移到 `fallback_colors` 並支持 `preset_color_schemes` 自定義，確實更有條理性。
