### ISSUE TITLE
3.2.2无法安装

### ISSUE THREAD

**Issue by LUKE-GG33** [osfans/trime#513]
3.2.2无法安装
![IMG_20210903_003450.jpg](https://user-images.githubusercontent.com/35057228/131882793-f9019023-6c2d-4955-8a0c-9102ef9e995a.jpg)
系统：lineageos17.1-20210825
机型：红米k20

**Comment by 15cm** [comment]
同样的问题。可以往 CI 的 release 里添加 released 版本吗？

**Comment by Bambooin** [comment]
目前没有 keystore，无法编译 release 版本

**Comment by 15cm** [comment]
我这边无法安装的原因其实是已有的 Trime 无法被替换。先手动删掉再安装 app-debug.apk 或者自己签名 release 的版本就好了。

**Comment by LUKE-GG33** [comment]
> 我这边无法安装的原因其实是已有的 Trime 无法被替换。先手动删掉再安装 app-debug.apk 或者自己签名 release 的版本就好了。

我昨天试过无法重新安装，今天更了一版rom可以安装了。

**Comment by tumuyan** [comment]
我提议更改下测试版的包名和名称,然后换一个密钥专供自动编译测试版release?
