### ISSUE TITLE
希望添加对于按键振动的优化

### ISSUE THREAD

**Issue by ofseed** [osfans/trime#514]
现在大多数手机都有线性马达，但是同文中的「按键震动」设定不能使用手机线性马达带来的震动提升，震感是老式的
让人感到松垮的震感。我个人认为这个震感的优化能给打字体验带来非常大的提升。

虽然我没有搞过安卓开发，但是我看似乎不止系统应用能有这种震感，或许系统有提供了相应的API？如果找的到文档，
应该不会太难增加这个功能

**Comment by ameaninglessname** [comment]
[之前在这有过一些讨论](https://github.com/osfans/trime/pull/445)

**Comment by WhiredPlanck** [comment]
线性马达的支持比较头疼，因为在这一方面几乎没有任何有效文档可以参考。目前进展缓慢。
