### ISSUE TITLE
关于语音支持

### ISSUE THREAD

**Issue by lingzhuxin** [osfans/trime#518]
文件说明表示语音支持是借用的手机语音识别服务，但是必须要安装讯飞语记才可以，想知道这个调用讯飞是在哪儿能改吗？调用谷歌的语音识别可以吗

**Comment by WhiredPlanck** [comment]
语音识别调用的是系统的语音识别服务，你可以在手机系统的设置中搜索语音查找有关设置项。

**Comment by Bambooin** [comment]
参考 #383
