### ISSUE TITLE
导航栏图标颜色不遵循系统亮暗色主题

### ISSUE THREAD

**Issue by 15cm** [osfans/trime#519]
**Describe the bug**
在系统为亮色主题的情况下，导航栏图标是白色而非黑色，使其几乎不可见：

<img src="https://i.imgur.com/zgZu39C.png" width="50%" height="50%">

**To Reproduce**
- 我的 [trime.custom.yaml](https://github.com/15cm/rime-config/blob/master/trime.custom.yaml)

外观为预设主题和颜色，在任意有文本输入框的应用里呼出键盘，比如 Firefox on Android。

**Expected behavior**
导航栏图标颜色应该为黑色，Gboard 和 Samsung 自带的键盘在此环境下都显示黑色图标。我写了一个 [commit](https://github.com/15cm/trime/commit/919dd06babeea97231ad995a15a845b8e802d220) 来强制指定 `BarUtils.setNavBarLightMode`，得到的效果如下：

<img src="https://i.imgur.com/ARp29iH.png" width="50%" height="50%">

**Smartphone**
 - Device: Samsung S21
 - OS: Android 11
 - Version: 3.2.2

**Additional context**
是否可以在配置的 `style` 项目或者 `preset_color_schemes` 中的每一项添加一个指定 navbar light mode 的选项供用户调节？系统亮暗色以及不同的 color schemes 排列组合很多，只有用户知道自己的配置需要怎么样的导航栏图标颜色。我觉得 `preset_color_schemes` 是个比较合适的地方。

**Comment by WhiredPlanck** [comment]
目前导航栏的设置逻辑是跟随用户键盘配色主色调的。这个情况应该属于 Bug 了，感谢反馈。

**Comment by yanhuacuo** [comment]
> 目前导航栏的设置逻辑是跟随用户键盘配色主色调的。这个情况应该属于 Bug 了，感谢反馈。

还有「状态栏」与「候选栏」，都有问题的：


> 新版本部分问题已经修复，除了键盘字体有些大

反馈如下：

- 「状态栏背景色」不能适应「主题背景色」

![pic](https://github.com/yanhuacuo/98wubi-weasel/raw/master/demo/QQ%E5%9B%BE%E7%89%8720211019213655.jpg)

![pic](https://github.com/yanhuacuo/98wubi-weasel/raw/master/demo/QQ%E5%9B%BE%E7%89%8720211019213702.jpg)

- 正常如下：

![pic](https://github.com/yanhuacuo/98wubi-weasel/raw/master/demo/QQ%E5%9B%BE%E7%89%8720211019214054.jpg)

![pic](https://github.com/yanhuacuo/98wubi-weasel/raw/master/demo/QQ%E5%9B%BE%E7%89%8720211019214047.jpg)

**Comment by WhiredPlanck** [comment]
> 反馈如下：
> 
>     * 「状态栏背景色」不能适应「主题背景色」

这也是个 Bug，是因为我们之前的取色方法出现了一些 Bug，现在应当已经修复。

**Comment by 15cm** [comment]
我最初的问题 https://github.com/osfans/trime/issues/519#issue-989341176 在 develop 分支的最新 commit 8fba667bc121340f491c0a7b20ea7f232a0a761b 依然存在。用同样的 patch 依然能修复得到同样的效果。是否考虑重新开启这个 issue 讨论？（我貌似没有 reopen 权限）
