### ISSUE TITLE
OpenCC部署成功但不会马上生效

### ISSUE THREAD

**Issue by xiaoqun2016** [osfans/trime#52]
新版果然集成了OpenCC！  
试将`STPhrases.txt`中的：  

```
码表  碼錶 碼表  
```

改成：  

```
码表  碼表 碼錶  
```

部署OpenCC成功，但并不马上生效，需要将同文进程重启才行。如果让它马上生效会不会更好些  

---

再请教一下，有没有办法让一对多转换同时显示？比如上面的`码表    碼錶 碼表`，在简体转繁体时默认只显示`碼錶`，而我们交流输入法的人说的一般都是`碼表`，用`碼錶`很怪。  
我对OpenCC不熟，目前只查到这篇：https://github.com/BYVoid/OpenCC/issues/146 。貌似还不能实现。  
如果能一对多同时显示，就可以实现类似于用中文输入emoji表情这样的功能，应该还是挺实用的。  
*一对多转换是OpenCC的问题，只是蛮问一下。可能在OpenCC的issue提问更合适

**Comment by osfans** [comment]
是啊，集成了。因爲txt生成的ocd，跟電腦上的不通用，所以手機上需要自己生成ocd。
重新部署rime也不行嗎？

**Comment by xiaoqun2016** [comment]
重新部署可以生效。如果把两个部署合并，可以简化操作，但不知道会不会有问题？

**Comment by osfans** [comment]
一對多，好像opencc不支持吧？
既然不能立即生效，那就合併吧，比平時多一秒而已。

**Comment by xiaoqun2016** [comment]
一对多仅支持单字，比如：   
```
只	只 隻 祇
干	幹 乾 干
````
输入简体`只`，可以显示对应的三个繁体字。  
但对词组无效，比如上面说的`码表`  
我觉得这样不太合理。也可能是我不了解OpenCC的用法，我再看看。  

---

独立设置比较直观，合并了又怕大家不知道有这个功能，到时候又要写一堆说明。如果能让部署OpenCC完成后也自动重启进程，也许就不用合并了？

**Comment by osfans** [comment]
那有沒有分開的必要？

部署OpenCC 1秒
部署rime 10秒

如果第一個加上rime的，那就是11秒，有必要嗎？

**Comment by xiaoqun2016** [comment]
看来是没必要，有时候只需要部署OpenCC。我提这个issue只是希望OpenCC部署后能马上生效，后面有点离题了

**Comment by osfans** [comment]
那就合併了，雖然這樣OpenCC部署就慢了。但至少可以立即生效了。

**Comment by xiaoqun2016** [comment]
好纠结，合并了又会让opencc部署变慢那么多，现在又不希望合并了。老大你看着办吧，我都没意见了

**Comment by osfans** [comment]
但是那1秒單獨的部署opencc，有沒有意義呢？

**Comment by osfans** [comment]
我也糾結。要不就在部署裏面加上opencc部署？原來的opencc還留着？

**Comment by xiaoqun2016** [comment]
看看这样行不行：点击部署的时候弹出类似回厂那种菜单，可以给方案或opencc打钩，如果两个都打钩就一起部署。
又或者像iphone恢复出厂设置那样，点击部署后弹出三个选项：  
①opencc  
②输入方案  
③opencc+输入方案  

不知道行不行，又或者以后再说啦

**Comment by osfans** [comment]
那樣又要多點一次了，也不好。

**Comment by xiaoqun2016** [comment]
试了一下0331版，效果还好，总体部署时间在5~8秒之间，跟先前没有多大区别。

**Comment by osfans** [comment]
那就好，先這樣了。

**Comment by xiaoqun2016** [comment]
内置的opencc有点问题，s2twp.json这个配置无效。  
原因可能是回厂时没有生成TWPhrases.txt，所以opencc部署时也不会生成TWPhrases.ocd。也可能是新版把TWPhrases.txt分解成了三个TWPhrases×××.txt，然后引用的时候出错了？  
tw2sp.json也有问题  

---

补充：  
把s2twp.json改成这样就生效了。  

``` json
{
  "name": "Simplified Chinese to Traditional Chinese (Taiwan standard, with phrases)",
  "segmentation": {
    "type": "mmseg",
    "dict": {
      "type": "ocd",
      "file": "STPhrases.ocd"
    }
  },
  "conversion_chain": [{
    "dict": {
      "type": "group",
      "dicts": [{
        "type": "ocd",
        "file": "STPhrases.ocd"
      }, {
        "type": "ocd",
        "file": "STCharacters.ocd"
      }]
    }
  }, {
    "dict": {
      "type": "ocd",
      "file": "TWPhrasesIT.ocd"
    }
  }, {
    "dict": {
      "type": "ocd",
      "file": "TWPhrasesName.ocd"
    }
  }, {
    "dict": {
      "type": "ocd",
      "file": "TWPhrasesOther.ocd"
    }
  }, {
    "dict": {
      "type": "ocd",
      "file": "TWVariants.ocd"
    }
  }]
}
```

不知道有没有改对？

**Comment by osfans** [comment]
我查下，可能OpenCC需要預處理txt。

**Comment by osfans** [comment]
現在應該好了。果然要處理一下txt，不能直接從opencc複製。

**Comment by xiaoqun2016** [comment]
嗯，0401版好了，👌
