### ISSUE TITLE
Help & About menu always be white color

### ISSUE THREAD

**Issue by Bambooin** [osfans/trime#521]
**Describe the bug**
Help & About menu always white color

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'Other'
2. Click on 'Night Mode'
3. Select  'Dark'
4. See bug

**Expected behavior**
Help & About menu should be dark mode

**Log**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Redmi]
 - OS: [Android 11]
 - Version: [3.2.2]

**Additional context**

**Comment by WhiredPlanck** [comment]
This is a design on purpose, not a bug. If the menu follow the night mode, it may be not very clear to read, IMO.

**Comment by Bambooin** [comment]
LineageOS 18.1
- Files: it's lighter black color in dark theme.
- Messaging: same too.
- Phone: same too.

**Comment by WhiredPlanck** [comment]
> LineageOS 18.1
> 
>     * Files: it's lighter black color in dark theme.
> 
>     * Messaging: same too.
> 
>     * Phone: same too.

Quiet useful information. I'll change it.
