### ISSUE TITLE
点击候选行为变化

### ISSUE THREAD

**Issue by walk143** [osfans/trime#524]
**Describe the bug**

自3.2.1之后，点击候选成了发送数字。当数字参与编码时，造成点击候选无法上屏的问题。目前没找到是什么造成的这个改动。

**To Reproduce**
Steps to reproduce the bug:
1. symbol设置`recognizer/patterns/punct: '^/([0-9]0?|[A-Za-z]+)$'`
2. 输入`/`，然后点击候选1
3. 变成了输入`/1`的效果

**Expected behavior**

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi Mix 4]
 - OS: [e.g. Android 11]
 - Version: [e.g. 3.2.1]

**Additional context**

据群友讨论，应该是之前发送的为`Ctrl+数字`，现在变为了直接发送数字（未验证）

**Comment by tumuyan** [comment]
…这是哪个群的群友说的啊，之前是直接commit，现在是模拟发数字键。
做这样的修改是因为直接commit会导致lua模拟selector出现异常。
解决办法其实也有了，为这个功能加开关，或者模拟方向键+空格键。我后边修吧。
其实还有另一个bug，只模拟了1-9数字键，（如果设置大于9改候选），大于9的无法正常上屏。

**Comment by walk143** [comment]
群：811142286，大佬方便的话进来交流下。
这个相关代码在哪个位置了。
最好还是能加开关手动开启。模拟方向加空格是要怎么实现点选，按多次方向吗

**Comment by tumuyan** [comment]
我周末来修吧，这个始末还是我比较清楚。  
模拟方向加空格就是直接调用handleAction方法…

**Comment by tumuyan** [comment]
这个应该可以close了
