### ISSUE TITLE
F-droid构筑失败

### ISSUE THREAD

**Issue by AsimovGod** [osfans/trime#526]
https://gitlab.com/fdroid/rfp/-/issues/1848

**Comment by AsimovGod** [comment]
依旧没有修好吗,可否告知更新计划

**Comment by Bambooin** [comment]
能再次触发 F-Droid 编译吗，上次的提交后，没有看到再次编译

**Comment by Bambooin** [comment]
如果还是编译不过，提供相应的错误日志，用于排查

**Comment by ivysrono** [comment]
应该要发布新release才能触发

**Comment by AsimovGod** [comment]
有人修复了构筑脚本，但必须发布新release。  
  
不知道能否进行。
https://gitlab.com/fdroid/fdroiddata/-/issues/2482#note_684576007

**Comment by AsimovGod** [comment]
已经有开发者构筑成功，但我并非开发组成员，英语也很差。交流很困难，可以麻烦哪位开发者去交流吗。 
[#2482](https://gitlab.com/fdroid/fdroiddata/-/issues/2482)

**Comment by xlucn** [comment]
3.2.3依然失败。。。

**Comment by ivysrono** [comment]
> 3.2.3依然失败。。。

我也想来反馈了

**Comment by Bambooin** [comment]
需要 F-Droid 那边合并后，问题才可能解决，另外可以自己编译或是使用 CI 编译的

**Comment by breakings** [comment]
最近发布的全是 debug版本，有没有计划发布 releases版本或者谷歌商店更新计划

**Comment by Bambooin** [comment]
The version 3.2.3 is released in F-Droid

https://f-droid.org/packages/com.osfans.trime/

https://gitlab.com/fdroid/fdroiddata/-/issues/2482

**Comment by Bambooin** [comment]
@breaking see https://github.com/osfans/trime/issues/416
