### ISSUE TITLE
滑行輸入

### ISSUE THREAD

**Issue by aaron2wh** [osfans/trime#529]
可以增加滑行輸入嗎？我之前一直使用Gboard的滑行輸入會大大加快打字速度。最近轉到RIME，發現沒有這個功能

PS：另外有個小疑惑，就是同文鍵盤最上排狀態欄的 🈶️️->🈚️️是什麼意思和作用啊？旁邊的全角半角，中文西文都好理解

**Comment by Bambooin** [comment]
duplicate #281

**Comment by xlucn** [comment]
我觉得两个issue不一样，OP提到了加快打字速度，那么这个应该是指在不同按键之间持续滑动，然后输入法收集其中想输入的几个键（应该是看拐弯的节点）：
![](http://www.shoujihuifu.com/wp-content/uploads/2019/08/1-7.jpg)

**Comment by aaron2wh** [comment]
對的，就是這個意思

**Comment by CrazyBoyFeng** [comment]
glide typing  
不知道是因为专利限制还是技术上比较难，这个功能在商业中文输入法中，我只在谷歌和搜狗见到过。据我个人体验，搜狗的输入没有谷歌准确。

这个功能不是仅仅分析手势的端点那么简单，还要分析路径上的所有可能。  
比如从`t`滑行到`i`，就有`ti`、`tui`、`t'yi`三种可能。如果算上模糊音、邻近按键遗漏/误触、中英混输，可能性就更多了。
