### ISSUE TITLE
新改版后，上下左右键不太稳定

### ISSUE THREAD

**Issue by xiaoqun2016** [osfans/trime#53]
最近这几版，左右两键集成了原先上下左右四键功能，上下键变成翻页键，这挺好。但在使用过程中，偶尔会回退到改版前的样子（上下键移动候选焦点，左右键移动编码焦点）。  
在过去一周当中，这种情况随机出现了五六次。每次出现时都只能重新部署才能恢复正常。
我试过改变`horizontal_mode`，但好像没有作用。  

---

补充：
由于方向键不常用，所以每次发现功能回退时，都不是第一现场了，到底是什么条件触发了这个问题也很难知道。估计只能从代码入手排查。又或者是我手机系统本身有问题，先记录一下。

**Comment by xiaoqun2016** [comment]
可能是librime问题？佛振之前更新了这个功能(feature) selector: horizontal mode.，在手机版上设为`true`和`false`并没有区别？

**Comment by osfans** [comment]
是跟這個功能有關。手機上有設置。但是不知如何複製。

**Comment by osfans** [comment]
幫忙看看

**Comment by xiaoqun2016** [comment]
@osfans  0413版，水平模式修好了。估计这个issue也解决了。  

但是新出了一种卡顿现象，与之前略有不同：  
- 仅在切换方案时卡住
- 部署、切换配色、部署OpenCC等都没问题

**Comment by osfans** [comment]
我也發現了，正在解決

**Comment by osfans** [comment]
apk已經上傳，歡迎測試

**Comment by xiaoqun2016** [comment]
@osfans 不卡了，但是horizontal_mode又失效了，设置`true`和`false`都是`false`

**Comment by osfans** [comment]
所以就是切換方案時，無法設置horizontal_mode，一設置就會卡住。不設置的話，又無法生效。只能重新部署。

**Comment by xiaoqun2016** [comment]
重新部署可以生效，没有问题了。

**Comment by xiaoqun2016** [comment]
好吧，还是有问题。就像你说的那样：方向键功能回退就是由于切换方案时没有设置horizontal_mode，而设置了horizontal_mode又会使切换方案卡住。不知道电脑版会不会这样？

**Comment by osfans** [comment]
我試試電腦上的，如果電腦上也有問題，那就是librime的問題。

**Comment by osfans** [comment]
又搞了版，切換方案時又強制設定了下模式。電腦上也有這個問題。

**Comment by xiaoqun2016** [comment]
好了。

**Comment by osfans** [comment]
聽公子說_horizontal是跟方案走的，所以我以前理解有誤
參見： rime/librime#83

**Comment by osfans** [comment]
取消了*.trime.yaml，都放到了schema中的style裏，跟小狼毫保持一致。
測試了horizontal和color_schema，都可以用。

**Comment by xiaoqun2016** [comment]
试了其它style参数，放在schema中也没有问题。又可以做出很多变化了。👍

**Comment by osfans** [comment]
还有什么跟小狼毫不兼容的 你也帮忙提出来 我小狼毫用得少。同样的功能 尽量用相同的配置 比如这里的style/horizontal
