### ISSUE TITLE
我们有没有必要在同文内加远程输入功能

### ISSUE THREAD

**Issue by tumuyan** [osfans/trime#530]
远程输入，就是利用电脑或者其他打字更方便的设备打字，代替手机本身的输入法打字。

我的设想是，用类似
 https://typecho.in/ 的服务在线打字（用户可以自定义网址和css selector）, 悬浮窗UI包含文本框, 刷新,上屏,清除,单行开关几个部分.通过自定义的url实现pc和手机数据同步.解析分为单行模式解析和多行模式解析.单行模式自动刷新,自动上屏倒数第二行的内容.多行模式需要手动刷新确认并上屏（当然也可以在其他设备上直接复制粘贴）

使用这样的解决方案，显然无法绕过联网权限。或者使用同文直接联网，或者使用扩展软件联网和同文交互。所以有没有必要增加这个功能呢？

**Comment by xlucn** [comment]
如果手机在电脑边，可以直接scrcpy

**Comment by ameaninglessname** [comment]
可以让同文支持插件么, 让插件获得联网权限,然后与同文交互.
支持插件的话,同文的可能性会上一个新台阶

**Comment by tumuyan** [comment]
> 如果手机在电脑边，可以直接scrcpy

不在同一网络就不行了。



> 可以让同文支持插件么, 让插件获得联网权限,然后与同文交互.
> 支持插件的话,同文的可能性会上一个新台阶

已经支持调用外部软件了

**Comment by xlucn** [comment]
> > 如果手机在电脑边，可以直接scrcpy
> 
> 不在同一网络就不行了。

那就用wifi或者连USB。我一个普通用户的看法是，一方面，对于输入法，联网（尤其是连第三方服务器）这种anti-feature不是很理想；另一方面，连外网的延迟甚至链接性都很难保证，用在打字这种事上，用户体验会不会堪忧？

当然，我既不是开发者，也没有这种功能的刚需，只是列举下自己的想法，不想左右大家的最终决定。
