### ISSUE TITLE
后台同步无效

### ISSUE THREAD

**Issue by Sunpulseqd** [osfans/trime#532]
后台同步无效,3.2.0版的自动同步没问题

**Comment by ameaninglessname** [comment]
问一下，后台同步/自动同步是干啥用的？

**Comment by Sunpulseqd** [comment]
> 问一下，后台同步/自动同步是干啥用的？

离开输入键盘5秒之后 自动同步 sync目录

**Comment by Bambooin** [comment]
删除 build 目录，重新部署一下呢，另外如果词库很大的话，频繁同步不利于性能

**Comment by Sunpulseqd** [comment]
> 删除 build 目录，重新部署一下呢，另外如果词库很大的话，频繁同步不利于性能

无效
