### ISSUE TITLE
收集按键手势误触的情况

### ISSUE THREAD

**Issue by tumuyan** [osfans/trime#534]
**Describe the bug**
同文输入法与其他输入法的键盘在设计上有根本性的不同，
同文的每一个按键都可以点击、长按、上划、下滑、左滑、右滑，在功能丰富、触发迅速的同时，带来了容易误就触发的问题。  
在不对键盘设计做的大的变更的前提下，要解决这个问题有些困难。
我们需要先理清到底有哪些情况容易产生误触？就我个人而言，上下滑动误触率低于5%，一个可以接受的水平。但是毕竟人和人是有差异的...有群友认为实在无法忍受。

已知的操作技巧：
1. 只要滑动速度快，就会减少误触
2. 与1相似，只要把长按时间加长，就会减少误触（因此考虑修改默认时间，从而改善新安装的用户的体验？）
3. 滑动动作的起始位置尽量在按键中央，滑动结束位置无所谓，滑动结束在其他按键上也不影响判定。

此issue收集容易发生按键手势误触的情况，看是否有改善的方法（请具体说明怎么样操作、结果怎么样）

**Comment by Sunpulseqd** [comment]
只在空格键上用左右滑动,因为我设计的空格键比较长. 其他的键不用滑动,很难操作

**Comment by xlucn** [comment]
## 我的观点

我觉得trime的手势识别方面的“**歧义性**”很严重。下面是我的测试，和与gboard的对比，gboard这方面做得很优秀。

“误触”这个说法在这里不一定准确。因为目前trime好像没有精确的规定什么样的操作会触发什么样的结果（Edit: 不是没规定，毕竟代码在那，但问题是用户并不知道）。并且，对于一些相似的操作，其“歧义性”很严重。这里“**歧义性**”指本来很相似的操作，trime会解读为完全不同的手势。

你提到了几点“操作技巧”，我觉得这实际是负面的用户体验。用户应该不必精确地控制滑动的速度和位置，就可以得到预期的结果。换句话说，相似的滑动速度和位置，不应该产生不同的手势结果。这就是**降低“歧义性”**。

现在这个issue旨在修补。我觉得确实要像你说的，要“对键盘设计做的大的变更”。但不一定要改得面目全非，可以考虑一定向后兼容性的情况，做一些用户体验的改进。如果需要，我（或者任何人）应该**再开issue，将问题剖析地更深一些**。

## 录屏示例

下面有4个视频，都是测试的从一个按键滑向另一个按键，稍稍改变速度和位置，然后看上屏结果。

大家观看这些视频时，可以尝试通过观察滑动路径，猜测究竟是上屏的什么字符，看看猜对多少。

### 1. 无下划触发按键的情况

   - trime倾向于在缓停于c键时，上屏`c`，在迅速掠过c键时，上屏`f`。但是，我无法获知精确的分界在哪。
   - 相比之下，gboard**只关注滑动终止按键**，只要我滑到c键松手，就一定上屏`c`，无“歧义性”。
     - 结尾有一次上屏`f`，经过逐帧播放视频，那是因为我松手时手指又回到了f键，依然无歧义。

   1.1 trime f到c

https://user-images.githubusercontent.com/12032219/135979808-98f3bdea-ad86-4772-8b9a-77b0116cc0c9.mp4

   1.2 gboard f到c

https://user-images.githubusercontent.com/12032219/135979764-abbb84f1-2a91-4a44-aedd-32d37dc15b6c.mp4

### 2. 有下划触发按键的情况

trime中同文风主题下，默认在k键下划，输出`_`。gboard中文支持下划操作，k键下划输出全角括号`（`。

- trime的手势识别更加混乱，我不知道什么时候会上屏`k`，什么时候上屏`m`以及`_`。
- gboard对于存在下划操作的按键，处理方式是下划过程锁定该键。可以从录屏中多次停止手指的表现看出，锁定期间，不会触发任何其它按键。同样，无“歧义性”。

   2.1 trime k到m

https://user-images.githubusercontent.com/12032219/135980054-eadecaa7-d4d9-438d-9642-3ba5474d0fd8.mp4

   2.2 gboard k到m

https://user-images.githubusercontent.com/12032219/135979792-8e9d6c62-ea5c-4325-a404-ea73df7d1af1.mp4

**Comment by tumuyan** [comment]
盘了n遍代码之后我觉得我完全理解你的录屏到底发生了什么。
这就是我在前边提到的两个问题：
1. 移动速度（慢
2. 停留时间（长
同文原先的判断方式，速度达到一定程度，才会进入初始触摸位置的滑动判定，这也是Android 原生API的手势判定硬性条件。
当速度不足，就会进入终止位置的长按判定。如果长按判定失败，触发终止位置的点击事件。

所以提交了针对性的修复：
1. 减少除速度之外的其他判定条件
2. 长按判定前，再次进入滑动判定，滑动距离由用户自己设定

理论上会有明显的改善（但是对我来说，原本误触就有限，感受不太明显

**Comment by xlucn** [comment]
我不太会盘代码，经过尝试阅读[这里的代码](https://github.com/osfans/trime/blob/58e7b8373e21bb0f8cb932453fe34cdc27730a90/app/src/main/java/com/osfans/trime/ime/keyboard/KeyboardView.java#L385)，得到了可能部分不正确的判定步骤（合并了方向判定），如有错误，请指出：

```python
if 速度 > 临界值:
  # 进入初始按键的滑动判定
  if 终止速度 满足条件:  # 我理解有问题，代码里是要小于初速的1/4？但是好像速度大些才触发滑动
    return 初始按键滑动
  else:
    return 初始按键点击
else:
  # 进入终止按键的长按判定
  if 时长足够:
    return 终止按键长按
  else:
    return 终止按键点击
```

然后 @tumuyan 你提出修复1是修改这些if条件内的阈值（还是减少if判定的次数？不清楚“减少”是指什么）；以及修复2是增加判定，在滑动距离足够时，不进入终止按键的长按判定，而是进入初始按键的滑动判定（或者说，将最外层if改为“速度足够 或 滑动距离足够”）。我理解的对吗？

**Comment by qwIvan** [comment]
请问群友是什么群？
