### ISSUE TITLE
允许按键内swipe手势终点超出按键范围

### ISSUE THREAD

**Issue by YanceyChiew** [osfans/trime#535]
**Is your feature request related to a problem? Please describe.**
当前的按键内轻扫手势只能识别起点和终点都在同一按键范围内的手势，按键的尺寸太小，而且扫动需要很快否则就会识别称长按，这都让准确作出上下左右扫动变得困难，或者在快速打字时因为短距离的拖动产生误触。

**Describe the solution you'd like**
可配制的swipe手势响应距离与超时，比较手势起点和终点，按照可配制的参数区分出长按、扫动以及无效操作，释放时的触点不局限于触发时所在按键的范围。如果有计划支持滑行输入，存在冲突，可选禁用其中之一，或者设置一个较短的原地（短距离）保持时间作为长按与扫动的触发动作。

**Describe alternatives you've considered**
如果超出控件范围后获取触点座标实现有困难，希望可以可选配制在超出的一瞬决定响应哪种手势。当前为单击按键，可能是在按键监听手势时判断到view不存在时就执行了默认动作？

**Additional context**

**Comment by xlucn** [comment]
可能相关issue： #281 

不过，滑动的范围好像可以超出当前按键。只不过当滑动到其他按键上时，其他按键会亮起，但实际触发的还是起始按键的滑动。可见上述issue里的动图示例。我不是开发者，只是自己总结了下trime的行为。

#534 和 pr #537 也在关注类似的问题，但貌似只涉及滑动长度的判断条件。

我也觉得trime在按键手势识别方面问题太多了，现在的还没有一个全面的issue总结这个问题。

**Comment by YanceyChiew** [comment]
@OliverLew 谢谢，经过测试确实扫动触发与终点无关，实际有关的是 #537 提到的扫动速度，这个大概是动作超时固定，要让终点在按键外扫动距离变长需要的速度也越快，我平时的操作没有达到这个速度要求故误以为终点只能在按键范围内。等那个pr merge后应该就能让扫动手势容易触发多了。
