### ISSUE TITLE
请问大佬可否适配线性马达？

### ISSUE THREAD

**Issue by UR-SillyB** [osfans/trime#539]
对于普遍震动马达的手机，普通的震感非常不舒服，请大佬适配一下手机自带的线性马达。
之前我在旧版本修改过振动，使用的是下面的代码
VibrationEffect.createPredefined(0);
this.vibrator.vibrate(vibrationEffect);
成功适配了小米手机的线性马达，其中createPredefined(0)中的0为小米手机中的预设，不确定其他手机是否仍然为0

**Comment by Bambooin** [comment]
#514
