### ISSUE TITLE
”方案“选项用不了！--小白的使用记录

### ISSUE THREAD

**Issue by boboIqiqi** [osfans/trime#54]
初次加入，请多指教。

我在wiki上，下载了，最新版的APK， 20160414版。
安装上，按照说明，
- 启用
- 设置为默认输入法

然后，就只能输入英文，而且没有候选字提示。

设置“方案”时，总是提示： 
`请在/sdcard/rime中放入....方案`

我按照说明，下载了相关文件。连上手机，打开手机存储卡，但是找不到/sdcard/rime/这个目录。

然后，我写了一个脚本，用adb push将
brise-master\supplement
中的所有相关文件全部push到/sdcard/rime

按照说明，我又重新布署了一下。仍然不同，在输入法界面上点击“方案“，程序还会直接崩掉

我的机器环境还没有配好，先从一个使用者角度提一点问题吧。

**Comment by xiaoqun2016** [comment]
是否安卓6.0系统？有没有给同文读写存储卡的权限？

**Comment by boboIqiqi** [comment]
不好意思，是我没有看清楚。我只是把 brise-master\supplement 下的所有文件拷贝到手机。
但是没有按提示说的，把根目录下的 essay.txt , default.yaml 和 symbols.yaml拷贝进去。
抱歉，输入法真的很不错，我会继续关注的。很喜欢输入完后，可以直接在候选框切换中英文。
我用的是五笔。

但是，这一步估计要难道不少非专业人士，我是找也半天也没有找到/sdcard/rime.

不过，我觉得拷贝文件，这一步会难倒不少电脑小白。我刚开始也没找到那个提示的/rime/sdcard/文件夹在哪里？要不是我使用adb push, 我还真解决不了这个问题。

开源软件，大家都在开发中，客户体验难免会差一点。

为什么不把这几个文件都直接打包apk里面呀！嗯现在的app都很大,用户也不在乎多几个文件少几个文件吧！

输入法做得真的很不错，我很喜欢。我也是一个输入法爱好者很期望可以加入你们。

**Comment by boboIqiqi** [comment]
终于搞明白了。
mnt代表mount，mnt/sdcard是实际的文件所在的地方，/sdcard是mnt/sdcard的虚拟或快捷方式. 
/sdcard/就是我用电脑大容量存储格式打开手机，内置存储的根目录。

只是默认没有创建 rime这个文件夹，我刚开始搜了一下都没有搜到

**Comment by xiaoqun2016** [comment]
欢迎加入 😊

**Comment by osfans** [comment]
歡迎歡迎。現在訪問github速度較慢，所以apk沒敢搞太大。要不轉移到國內的git上？

**Comment by xiaoqun2016** [comment]
@osfans 如果上架到应用市场，应该就可以增量更新了吧？到时候可以内置一些必要的文件，方便初学者

**Comment by zhl111** [comment]
> 不好意思，是我没有看清楚。我只是把 brise-master\supplement 下的所有文件拷贝到手机。 但是没有按提示说的，把根目录下的 essay.txt , default.yaml 和 symbols.yaml拷贝进去。 抱歉，输入法真的很不错，我会继续关注的。很喜欢输入完后，可以直接在候选框切换中英文。 我用的是五笔。
> 
> 但是，这一步估计要难道不少非专业人士，我是找也半天也没有找到/sdcard/rime.
> 
> 不过，我觉得拷贝文件，这一步会难倒不少电脑小白。我刚开始也没找到那个提示的/rime/sdcard/文件夹在哪里？要不是我使用adb push, 我还真解决不了这个问题。
> 
> 开源软件，大家都在开发中，客户体验难免会差一点。
> 
> 为什么不把这几个文件都直接打包apk里面呀！嗯现在的app都很大,用户也不在乎多几个文件少几个文件吧！
> 
> 输入法做得真的很不错，我很喜欢。我也是一个输入法爱好者很期望可以加入你们。

你好，你写的这些我也没看懂，我是将电脑上的所有文件拷贝到手机上的，我也找不到这个目录，你是怎么解决的？
