### ISSUE TITLE
输入时会出现卡顿情况

### ISSUE THREAD

**Issue by jim-kirisame** [osfans/trime#541]
**Bug描述**
在Trime从v3.1.3升级到v3.2.2后，发现输入时会经常出现卡顿的情况，具体表现为在连续输入字符时字符不再上屏，卡顿1-2s后继续上屏。

此问题基本出现于词与词的分割处。例如，输入“测试输入”（ceshishuru）的时候，"ce" 不会卡顿，“shi”会卡顿但基本不可感知，按下“shu”后即开始明显卡顿。

**设备信息**
 - Xiaomi Mi 8
 - OS: Android 11
 - Version:  3.2.2

**附加信息**
使用的方案是[aurora-pinyin](https://github.com/hosxy/rime-aurora-pinyin) + zhwiki，但即使我关闭了zhwiki后也会出现此情况。

**Comment by jim-kirisame** [comment]
删除词库和Build文件夹后重新同步部署解决了。

**Comment by Iey4iej3** [comment]
建议把这个解决方案添加到主页，在 GUI 中添加按钮以实现这个功能（例如叫做“初始化部署”和“初始化用户词库”）。
