### ISSUE TITLE
View class Composition is an AppCompat widget that can only be used with a Theme.AppCompat 

### ISSUE THREAD

**Issue by iovxw** [osfans/trime#545]
**Describe the bug**

log 里出现如上错误，但程序本身行为未发现异常

将

https://github.com/osfans/trime/blob/cd19c26c710acde288395e89205d3a32b43e12e3/app/src/main/java/com/osfans/trime/ime/text/Composition.java#L55

里的 `AppCompatTextView` 替换回 `android.widget.TextView` 错误便不再出现

引入这一变动的是 5e78630ae249d93141e545584bb7296744617061，不知 @tumuyan 是否有头绪？

**To Reproduce**
Steps to reproduce the bug:
1. 启动 Trime
2. 看 logcat

**Expected behavior**

**Log**
```
View class com.osfans.trime.ime.text.Composition is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
```

**Screenshots**

**Smartphone (please complete the following information):**
 - OS: Android 11
 - Version: cd19c26c710acde288395e89205d3a32b43e12e3

**Additional context**

**Comment by tumuyan** [comment]
当时的变更原因可能有两个:
1. 由于更换了API level, 改为Androidx库的时候用了Alt+Enter自动修复, 没仔细确认
2. 背景之类的设置参数需要把类改为这个

应该没有特殊考量, 如果替换之后as没有增加新的错误提示(不是log)就可以改回去
