### ISSUE TITLE
发现了一个小bug,方案选项可能会崩

### ISSUE THREAD

**Issue by boboIqiqi** [osfans/trime#55]
昨天我下载安装了程序，刚开始没有将需要的几个文件拷对，然后在输入法界面，长按 选单 按钮 ，选择方案时，程序崩了。但在输入法的主配置界面，选方案会给出提示。

今天我查了一点，是 trime.java, private void showDialog没有判断参数为null

**Comment by boboIqiqi** [comment]
或者往前一步，获取方案配置对话框完成之后，判断一下有没有为空的情况，唯恐了就不要调用showdialog

**Comment by osfans** [comment]
多謝，你也可以幫忙提PullRequest啊

**Comment by osfans** [comment]
或者直接隱藏“方案”按鈕？

**Comment by boboIqiqi** [comment]
好的，我一定尽快熟悉代码。我白天上网不方便只能晚上回去上网。

**Comment by osfans** [comment]
直接隱藏方案按鈕。
