### ISSUE TITLE
什么时候开发九宫格？还有双键输入模式

### ISSUE THREAD

**Issue by boboIqiqi** [osfans/trime#56]
我一直喜欢用双键输入模式。我想实现这个功能应该从哪里入手？麻烦大家给个思路。大家近期有什么开发计划。

**Comment by osfans** [comment]
librime主要是針對PC的，一個鍵對應多個碼，好像不太好做。有計劃的都列在了issues裏面。

**Comment by boboIqiqi** [comment]
好的，我好好看一下。不过，说实话手机上九宫格还是主流。但这个迟早是要实现的。

**Comment by boboIqiqi** [comment]
有一种方案不知道行不行，嗯就是一个键还是对一个字母，但是把码表变了，只有一半的字母。wubi这样是可以的。我做过一个小demo，我发哪？

**Comment by osfans** [comment]
這個只是前臺。
後臺還是要librime，可以在小狼毫、ibus-rime、fcitx-rime上面實驗。

**Comment by osfans** [comment]
這種方法有的，就跟模糊音一樣，現在就可以實現的。librime有這種轉換規則。

**Comment by boboIqiqi** [comment]
那只显示一半的按键，再把按键大小和界面label改头换面，不就实现双键文字了吗？

**Comment by boboIqiqi** [comment]
好吧，这应该是个骚主意。五笔还行，拼音要修改拼音选项估计就不行了

**Comment by osfans** [comment]
是啊，模糊了之後，再想變清晰，目前是不行。

**Comment by xirtam-ch** [comment]
强烈希望android版本能加入九宫格输入！！！

**Comment by freewuh** [comment]
同求五笔双键

**Comment by freewuh** [comment]
已经没有人关注这个了吗？

**Comment by osfans** [comment]
很難。所以沒有進展。

**Comment by beversmith** [comment]
顶起来啊，九宫格

**Comment by Raywang80s** [comment]
九宫地球启用九宫格时为什么一个键只有一个字母哇？？。。。掉字母了还是bug没解决呢。。

**Comment by ivysrono** [comment]
+1

**Comment by Bambooin** [comment]
https://github.com/osfans/trime/issues/377

有 rimer 折腾出 九宫格的输入方案，大家可以试用一下。

@xirtam-ch @beversmith @freewuh
