### ISSUE TITLE
【缺陷】注音西文键盘没有Shift键，无法输入大写字母

### ISSUE THREAD

**Issue by Prcuvu** [osfans/trime#57]
由于注音键盘没有Shift键，必须切换到其他方案才可以输入大写字母。这个问题在进入密码输入框时尤其明显。
希望注音键盘在西文状态可以切换到预设的西文布局。如果可以更进一步，希望所有方案在西文模式时可以统一使用预设西文布局。

**Comment by xiaoqun2016** [comment]
@osfans 尝试将注音的键盘`{click: Hide, long_click: Delete}`改成`{ascii: Shift_L, click: Hide, long_click: Delete}`，但切换到西文模式时，仅仅**单击**`Shift_L`，就立即锁定大写状态。

**Comment by heangfat** [comment]
我將中文、西文切換鍵改成了切換大小寫鍵 `Shift_L`，因爲鍵盤頂上專設了一个按鈕切換中西文，底下這个鍵重複了。

**Comment by xiaoqun2016** [comment]
注音仓颉键盘在中文模式看不到英文字母，加shift可能也不好用？  

>希望注音键盘在西文状态可以切换到预设的西文布局

ascii_mode: 0|1|qwerty  西文模式时切到指定的键盘

或者有更好的做法？

**Comment by osfans** [comment]
有道理，這個方法不錯。

**Comment by DaengGWokFook** [comment]
以下截圖是我自己改良的倉頡鍵盤，每個鍵都有幾個功能，z鍵也改成通用鍵，可取代其餘二十五個鍵。
![screenshot_2017-02-13-23-16-38](https://cloud.githubusercontent.com/assets/18633778/22915091/c59acbfc-f242-11e6-8697-26e940ffd9f1.png)
![screenshot_2017-02-13-23-16-33](https://cloud.githubusercontent.com/assets/18633778/22915092/c59b34a2-f242-11e6-8acb-f65de799b12b.png)

**Comment by osfans** [comment]
@DaengGWokFook 通用鍵不用改schema裏的speller嗎？

**Comment by DaengGWokFook** [comment]
要在schema裏的speller加algebra才能發揮通用鍵功能，但是部署會比較久

**Comment by coldwintw** [comment]
我是自己去調整trime.yaml，在中間有一個「註音鍵盤」(可能是當時輸入者打錯字)
其中有一段是這樣子的 
      - {click: 'Mode_switch', long_click: Menu}
      - {click: Keyboard_symbols, long_click: Keyboard_number}
      - {click: space, width: 30}
      - {label: 'ㄦ', long_click: '"', click: "-"}

我把這段改成這樣
    - {click: Mode_switch, long_click: Menu}
    - {click: Shift_L, send_bindings: false}
    - {click: Keyboard_symbols, long_click: Keyboard_number}
    - {click: space, width: 20}
    - {label: 'ㄦ', long_click: '"', click: "-"}

簡單講就是加進去一個SHIFT鍵,然後調整一下空白鍵的WIDTH。
然後我的注音鍵盤就可以輸入大寫英文了。
有興趣的不妨試看看

**Comment by osfans** [comment]
81c30bda1b03166cec79e6ec12515c00ec5d351a 修正。
