### ISSUE TITLE
使用快捷键C复制导致闪退

### ISSUE THREAD

**Issue by daniuwo** [osfans/trime#570]
**Describe the bug**
使用C快捷键复制编辑器会闪退，在代码编辑器场景才会出现。

**To Reproduce**
Steps to reproduce the bug:
1. 去这里测试 [https://tool.lu/coderunner/](https://tool.lu/coderunner/) 
2. 打开上面的网址在编辑器里面使用快捷键A全选，然后接着按快捷键C复制。在git Issue编辑器复制也会重现
3. 然后编辑器就闪退了（在git Issue编辑器使用C快捷键复制也会重现）
**Expected behavior**

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. 中兴Axon 30 Ultra 5G]
 - OS: [e.g. Android 11]
 - Version: [e.g. 3.2.3]
 - Theme: [e.g. Tongwenfeng]

**Additional context**

**Comment by WhiredPlanck** [comment]
目前编辑器操作因进行了测试不严谨的重构，代码存在瑕疵。正在逐步修复中，感谢反馈 ～

**Comment by Bambooin** [comment]
3.2.5 works and can't reproduce
