### ISSUE TITLE
[Bug] libc report fatal error when InputMethodService onCreate

### ISSUE THREAD

**Issue by WhiredPlanck** [osfans/trime#573]
**Describe the bug**
libc reports fatal error when InputMethodService onCreate

**To Reproduce**
Steps to reproduce the bug:
Connect the physical phone and run app in Android Studio, then launch the app.

**Expected behavior**
You know

**Log**
```
...
I/Trime: onCreate...
I/TextToSpeech: Sucessfully bound to com.iflytek.speechsuite
A/libc: Fatal signal 31 (SIGSYS), code 1 (SYS_SECCOMP) in tid 12911 (om.osfans.trime), pid 12911 (om.osfans.trime)
```

**Smartphone**
 - Device: Honor ViewPad 6
 - OS: Android 10
 - Version: 3.2.4
 - Theme: Tongwenfeng

**Comment by iovxw** [comment]
Can't reproduce, can you provide more logs? https://android-developers.googleblog.com/2017/07/seccomp-filter-in-android-o.html

Have you cleared your workspace before compiling? CMakeCache is always a problem

Try remove `app/.cxx` `app/build` `build`

**Comment by WhiredPlanck** [comment]
> Can't reproduce, can you provide more logs? https://android-developers.googleblog.com/2017/07/seccomp-filter-in-android-o.html
> 
> Have you cleared your workspace before compiling? CMakeCache is always a problem
> 
> Try remove `app/.cxx` `app/build` `build`

Unfortunately, this problem still appear on my device.

**Comment by iovxw** [comment]
From your log:

> A/DEBUG: Cause: seccomp prevented call to disallowed arm64 system call 291

syscall 291 of arm64 is `statx`

https://android.googlesource.com/platform/bionic/+/refs/heads/android11-mainline-release/libc/SYSCALLS.TXT

https://android.googlesource.com/platform/bionic/+/refs/heads/android10-mainline-release/libc/SYSCALLS.TXT

Seems like Android 11 have `statx` but 10 doesn't

I'll disable statx in next PR

**Comment by WhiredPlanck** [comment]
Great! LGTM ~
