### ISSUE TITLE
Orgnization for Trime project

### ISSUE THREAD

**Issue by Bambooin** [osfans/trime#576]
Orgnization is better for **team collaboration and code review**.

There are some choice:
- We create a new orgnization for Trime.
- ~~We can join https://github.com/rime/ organization.~~ (rejected)
- Any better ideas are welcome.

Still needs some discussion....

**Comment by ameaninglessname** [comment]
Just a question : why not just join **Rime** just like other platform "implementations"?

**Comment by Bambooin** [comment]
We don't have permission to join any organization which doesn't belong to us.

**Comment by InfinityLoop1308** [comment]
Vote for create a new organization.

**Comment by WhiredPlanck** [comment]
I suggest that create a new organization for Trime since current code quality make it hard to be recognized by Rime official.

**Comment by WhiredPlanck** [comment]
@Bambooin Unfortunately, I think lotem made it clear that he didn't want Trime in `rime` organization. It may be the only way to create a new organization for Trime.

![IMG_20231216_194907](https://github.com/osfans/trime/assets/47623588/1194d384-0884-4916-b701-11a4d148ec5c)

**Comment by Bambooin** [comment]
Got it, thanks.

We should improve Trime stability and quality for users, and I don't have permission to migrate the project to the new orgnization right now.

**Comment by ameaninglessname** [comment]
Could we fork this project, put it in the new organization and have release build?

**Comment by MokOopsing** [comment]
![image](https://github.com/osfans/trime/assets/39441028/515fe7be-af82-4ec9-a3c3-4fe493110e05)

Like this?

**Comment by Bambooin** [comment]
Seems fork will lose all issues and pull requests which won't be a perfect solution.

**Comment by WhiredPlanck** [comment]
> Seems fork will lose all issues and pull requests which won't be a perfect solution.

Old issues and PRs are still here to be read, I think forking is just OK.

**Comment by Bambooin** [comment]
We have more collaborators right now, this is not an urgent issue anymore.
