### ISSUE TITLE
麻烦问一下，如何配置语音输入

### ISSUE THREAD

**Issue by boboIqiqi** [osfans/trime#58]
我看贴吧和源码里都有语音输入相关的论述，不知道如何配置。
另外我每次用选单切换到迅飞输入法后，想切换回来，该如何进行呀，要重新进入系统的设置菜单，重新切换回来。感觉别的输入法都没有提供这个菜单。

**Comment by xiaoqun2016** [comment]
trime.yaml里面的`preset_keys`预定义了一些功能键，其中的`VOICE_ASSIST`就是语音输入，你把这个功能键放到你要用的键盘布局中，就可以启动语音输入。  
比如这样： `{click: space, long_click: VOICE_ASSIST, width: 28}`就是长按空格键启动语音输入。  
语音输入是直接调用系统的语音引擎，你可以安装讯飞语记或者讯飞语音+，都可以。  
另有一个参数`style/speech_opencc_config`，是将语音输入的结果经过`OpenCC`转换一下再上屏，可以实现简繁转换等效果。  

再补充一下：  
默认的空格键是长按重复的`repeatable: true`，如果要把语音输入设到空格键长按上，需要先把它的长按重复关掉`repeatable: false`

**Comment by xiaoqun2016** [comment]
在打字时，可以从系统通知栏切换输入法

**Comment by boboIqiqi** [comment]
非常感谢。以前没注意过，你说的正是我需要的。
