### ISSUE TITLE
安裝trime 3.2.3不自動生成default.yaml及不能選中輸入法方案

### ISSUE THREAD

**Issue by tiujejauci** [osfans/trime#587]
**安裝trime 3.2.3及啟動後出現如下問題**
①無法自動生成default.yaml。
②多次嘗試：選中輸入法方案會自動重啟程式，導致無法使用輸入法，閣下已自行準備好輸入方案放在輸入法之指定位置。
③選中離開時清理記憶體會自動重啟程式。

**Log**
無日誌，為方便解決日後問題，建議增加匯出日誌選項，

**Screenshots**
![Screenshot_2021-11-13-07-46-20](https://user-images.githubusercontent.com/31369434/141598407-6815168f-68fa-4271-919c-ce20e60f23af.png)

**Smartphone (please complete the following information):**
 - Device: [Nokia 7plus]
 - OS: [Android 9]
 - Version: [3.2.3]
 - Theme: [Tongwenfeng]
請修復以上問題。

**Comment by 5fff** [comment]
Similar issue in 3.2.0 and 3.1.3 from FDroid, does not work out of the box. It has default config but it cannot detect the yaml files and shows the above dialog when selecting a schema(方案) . When in Chinese mode it will type only English. 
Should I expect this IME to be able to type Chinese right after installation? Or I'm supposed to perform some manual step before I can use it?

**Comment by Bambooin** [comment]
It's fixed in 3.2.4, you can try it now

@xuruicheng96 you can try https://github.com/Bambooin/rimerc
