### ISSUE TITLE
Dvorak Layout

### ISSUE THREAD

**Issue by B83C** [osfans/trime#588]
**Is your feature request related to a problem? Please describe.**
 Well, I am not a typist, but I have been used to typing on Dvorak layout everywhere. So it's frustrating not to have it on mobile phones.

**Describe the solution you'd like**
The title is already self-explainatory, just Dvorak layout as an option...

**Describe alternatives you've considered**
Haven't seen any pinyin IME with such feature yet

**Comment by rainhear** [comment]
- 鍵盤佈局可以參考[trime.yaml詳解](https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3)自行設計，調整按鍵單擊事件 `click` 即可。
