### ISSUE TITLE
定义键盘布局在哪里定义？

### ISSUE THREAD

**Issue by boboIqiqi** [osfans/trime#59]
不好意思，昨天在电脑上看源码，一直找不到定义键盘布局的地方。我以前看过，安卓的源码示例中SoftKeybroad。里面有一个xml文件可以定义键盘各个按键。咱们的项目里面怎么没有呀。全都在trime.yaml文件中吗？
另外，有没有相关的配置文档，麻烦给我推荐

**Comment by boboIqiqi** [comment]
有点看不懂yaml文件

**Comment by xiaoqun2016** [comment]
我们有wiki：  https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3

**Comment by boboIqiqi** [comment]
谢谢你，我没有认真看wiki，光下载用apk，就没有认真看

**Comment by osfans** [comment]
原本是xml。
爲了自定義和兼容rime，換成了yaml。
