### ISSUE TITLE
在 http://rime.im/download/ 添加鏈接

### ISSUE THREAD

**Issue by lotem** [osfans/trime#60]
在 Rime 下載頁新增「Android」標題
並爲 Trime 錄入
項目名稱、
簡短介紹、
下載鏈接等

**Comment by osfans** [comment]
在想要不要搞到什麼市場上面。

**Comment by lotem** [comment]
原來泰如方言不是吳語啊。失敬。
我曾奇怪《同文》爲何不叫 drime 而是 trime。

**Comment by osfans** [comment]
不是，不過跟吳語搭界了。

**Comment by lotem** [comment]
在市場上架了再更新下載頁唄。

**Comment by boboIqiqi** [comment]
推荐FDroid，这个应用市场上全部都是开源的软件。我们项目组就是在这上面做开发的
