### ISSUE TITLE
横竖屏切换的一些想法

### ISSUE THREAD

**Issue by TiceCosmos** [osfans/trime#607]
1. 键盘区分横竖屏
    - number@port: ...
    - number@land: ...
1. 横屏模式关闭悬浮窗口功能

**Comment by tumuyan** [comment]
1. 横屏可以通过设置padding参数，令使用体验略为改善。目测目前没有人处理
2. 列入待办
实际上横屏的问题很多，尤为凸出的是这两个：
1. 部分App无法正确切换键盘方向，以termux和debian为例
2. 横屏模式下的全屏模式无法刷新文本框色彩
