### ISSUE TITLE
Enable manually trigger jni build with trick

### ISSUE THREAD

**Issue by Bambooin** [osfans/trime#608]
**Is your feature request related to a problem? Please describe.**

Enable manually trigger jni build with trick

As #594, jni cache is invalid, but it doesn't tigger jni build

We need a better way to tirgger jni build manually 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by iovxw** [comment]
Some options: https://microsoft.github.io/code-with-engineering-playbook/continuous-delivery/devops-provider-recipes/github-actions/runtime-variables/runtime-variables/#solution
