### ISSUE TITLE
In default theme, some key labels have oversized fonts

### ISSUE THREAD

**Issue by austinhuang0131** [osfans/trime#613]
v3.2.3 默认主题中最下方各键字体过大，之前（如v3.2.0）则无此问题。

**To Reproduce**
Steps to reproduce the bug:
1. Use default theme (regardless of colour)
2. Bring up the IME

**Expected behavior**
The labels on the bottom row keys should be of a smaller size; This was the case in older versions (eg. v3.2.0).

**Log**
n/a

**Screenshots**

![screenshot_20211202-201804](https://user-images.githubusercontent.com/16656689/144528545-3d9acd22-b262-44e9-962e-9d41aa1631eb.png)

**Smartphone (please complete the following information):**
 - Device: Sony Xperia XA2 (H3123)
 - OS: Android 9
 - Version: 3.2.3 F-Droid
 - Theme: Default

**Additional context**

**Comment by Bambooin** [comment]
You can try new release 3.2.4, it is debug now

**Comment by tumuyan** [comment]
https://github.com/osfans/trime/issues/528  was never fixed, not only v3.2.3 but also v3.2.4

**Comment by Bambooin** [comment]
I check Tongwenfeng theme, it's font size is normal, so maybe issue is the congfig of trime.yaml
