### ISSUE TITLE
Harmony OS(鸿蒙)v2不能安装trime-3.2.4，安全签名不一致？

### ISSUE THREAD

**Issue by wwzrh** [osfans/trime#618]
![微信图片_20211205103425](https://user-images.githubusercontent.com/12047479/144731292-e24a1e3d-de09-41c6-8495-c3ebf33b1b4d.jpg)

**Comment by Bambooin** [comment]
You can unistall origin trime, and install 3.2.4, as we only have debug build

see #416

**Comment by atlanticfirst** [comment]
去f droid下，鸿蒙我是在f-droid下的，目前没碰到什么问题

**Comment by wwzrh** [comment]
HarmonyOS手机设置纯净模式默认是开启状态，在调试安装apk时需进入HarmonyOS手机设置退出纯净模式。
解决办法，操作路径：设置>系统和更新->纯净模式，或者在设置中搜索纯净模式，单击退出。
即可安装debug版。
如trime-3.2.X-arm64-v8a-debug.apk
