### ISSUE TITLE
【v3.2.4】懸浮窗 `編碼註釋 comment` 初始化時未正常加載

### ISSUE THREAD

**Issue by rainhear** [osfans/trime#621]
## 漏洞描述

`3.2.4` 版本中，懸浮窗 `編碼註釋 comment` 初始化時未正常加載

## 重現漏洞

重現漏洞的步驟：

1. 更新至 `3.2.4`，初次在文本編輯區域調出同文鍵盤
2. 輸入編碼，`編碼註釋 comment` 未能加載
3. 重選一次 `主題` 後，則 `編碼註釋 comment` 恢復可見
4. 由第三方輸入法切回同文時，`編碼註釋 comment` 也未能加載

## 預期行為

`初始化時` 或 `由第三方輸入法切回同文時`， `編碼註釋 comment` 均能正常加載

## ~~日誌~~

~~如果適用，請添加崩潰日誌以快速聚焦您的問題。~~

## 截圖

![編碼註釋](https://user-images.githubusercontent.com/60956322/145069166-8a2e43f8-2b3e-46bc-a63f-08af6b62fb27.png)

## 智能手機（請填寫以下信息）

- 設備：【ZUK Z2 Pro】
- 操作系統：【Android 7.0】
- 版本：【3.2.4】
- 主題：【個人主題】

## ~~附加內容~~

~~在此處添加有關此問題的任何其他內容。~~

**Comment by iovxw** [comment]
在 #609  中这个问题已经修复了，但我还在修一些其他部分，所以暂时没合并

-------------
算了先能修一点是一点吧

**Comment by rainhear** [comment]
> 在 #609 中这个问题已经修复了，但我还在修一些其他部分，所以暂时没合并

期待合併。😀

**Comment by rainhear** [comment]
> 算了先能修一点是一点吧

外語文盲，很多英文議題都未能及時讀懂，導致重複提交相同議題。😂
