### ISSUE TITLE
从3.1.3升级到3.2.x, preset_keyboards columns设置无效

### ISSUE THREAD

**Issue by RFDAJE** [osfans/trime#628]
3.1.3截图 设置columns为11的效果
![IMG_20211211_135041](https://user-images.githubusercontent.com/22750/145677618-e9ee718a-3778-44c3-b3d3-c64b662d689c.jpg)

3.2.x截图 配置文件相同, 显示效果强制columns为10
![IMG_20211211_135304](https://user-images.githubusercontent.com/22750/145677642-7c6eede9-7c09-4b66-bd45-2db66b344725.jpg)

**Comment by tumuyan** [comment]
显然发生问题的不是columns没有生效，而是按键宽度计算差异导致了现在一个按键要占用比之前更大的空间，导致按键数量=10<columns=11。
columns设置了按键数量上限 并不代表按键数量一定等于他。
你可以通过设置值为<10的数字进行验证。

**Comment by RFDAJE** [comment]
感谢回复。升级到3.2.4后，略微缩减宽度，结束运行“同文”，再开启问题解决。
