### ISSUE TITLE
能不能跟Keepass结合，做一个输入帐号和密码的键盘

### ISSUE THREAD

**Issue by boboIqiqi** [osfans/trime#63]
我手机上装了安卓版的keepass 可以管理各种账号和密码。他有一个自带的键盘，用来直接输入密码的。但是不好用，要切换。能不能把这个功能集成到我们项目中。

**Comment by boboIqiqi** [comment]
因为手机上输入密码和账号是比较常见的输入场合。而且比较麻烦，相对于台式机，因为现在密码一般都要求有符号，数字带字母，要来回切换键盘。

这是源码链接，一个跨平台的密码管理工具
http://keepass2android.codeplex.com/SourceControl/latest

**Comment by xiaoqun2016** [comment]
keepass安装文件25M，体积是同文的10倍，不过它内置的键盘做得挺好的，跟输入法似的。  
谷歌Play Store上另有一个开源的KeePassDroid （ https://play.google.com/store/apps/details?id=com.android.keepass ）， 不带键盘的，只有2M。 源码在这里（ https://github.com/bpellin/keepassdroid ）。  

Rime编译出`table.bin`固态词典后就可以删除`dict.yaml`了。所以，用固态词典储存用户密码应该也是可行的，这也是一种简易的加密方法。不过应该比较容易破解吧。  但一般的黑客应该也想不到有人会用输入法的固态词典储存密码吧。  

所以，keepass是加密软件附带简易输入法，同文是输入法附带简易加密功能！😄

**Comment by boboIqiqi** [comment]
你说的挺对的。我是想，能不能提供一个插件把把两者结合起来。各自维护各自领域，又能合二为一，不用来回切换。keepass 自带的键盘不能输入中文,输完密码以后的切换回来. 还是不太方便 .
或者把那个2m的，程序做成插件，可以动态加载到我们的输入法中。

**Comment by boboIqiqi** [comment]
毕竟输入法是一个经常使用的软件，而密码管理只是后台程序，提供安全保证就行

**Comment by xiaoqun2016** [comment]
@boboIqiqi  
试了25M那个，键盘不错，功能挺多，还可以扩展插件，难怪体积那么大。不晓得是不是可以把Rime做成插件集成到里面？

**Comment by osfans** [comment]
似乎把rime集成到那裏比較好
