### ISSUE TITLE
F-Droid build failure: Version mismatch between generated code and library headers

### ISSUE THREAD

**Issue by jspricke** [osfans/trime#634]
FAILED: librime/proto/CMakeFiles/rime-proto-objs.dir/rime_proto.capnp.c++.o 
  /opt/android-sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --gcc-toolchain=/opt/android-sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/opt/android-sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -DBOOST_NO_CXX11_SCOPED_ENUMS -DRIME_VERSION=\"1.7.3\" -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/algorithm/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/any/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/crc/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/date_time/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/dll/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/filesystem/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/format/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/interprocess/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/iostreams/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/lexical_cast/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/optional/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/range/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/regex/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/scope_exit/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/signals2/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/utility/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/uuid/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/locale/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/array/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/assert/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/bind/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/concept_check/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/config/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/core/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/exception/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/function/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/iterator/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/mpl/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/static_assert/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/throw_exception/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/tuple/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/type_traits/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/unordered/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/type_index/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/integer/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/io/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/numeric/conversion/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/smart_ptr/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/tokenizer/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/winapi/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/move/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/predef/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/spirit/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/system/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/container_hash/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/detail/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/container/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/intrusive/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/preprocessor/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/random/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/conversion/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/typeof/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/parameter/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/variant/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/serialization/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/tti/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/function_types/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/fusion/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/endian/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/phoenix/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/pool/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/proto/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/thread/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/dynamic_bitset/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/mp11/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/atomic/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/chrono/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/align/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/ratio/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/boost/libs/rational/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/librime/thirdparty/include -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/capnproto/c++/src -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/OpenCC/deps/marisa-0.2.6/include -Iinclude -Ilibrime/src -I/home/vagrant/build/com.osfans.trime/app/src/main/jni/librime/src -Ilibrime/proto -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb     -std=c++14 -O2 -g -DNDEBUG -fPIC   -Wno-format -std=gnu++14 -MD -MT librime/proto/CMakeFiles/rime-proto-objs.dir/rime_proto.capnp.c++.o -MF librime/proto/CMakeFiles/rime-proto-objs.dir/rime_proto.capnp.c++.o.d -o librime/proto/CMakeFiles/rime-proto-objs.dir/rime_proto.capnp.c++.o -c librime/proto/rime_proto.capnp.c++
  In file included from librime/proto/rime_proto.capnp.c++:4:
  librime/proto/rime_proto.capnp.h:10:2: error: "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
  #error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
   ^
  1 error generated.

https://monitor.f-droid.org/builds/log/com.osfans.trime/20211130#site-footer

Can you have a look?

**Comment by Bambooin** [comment]
The root cause is: we upgrade capnproto to 0.9.1, and build it directly from submodule `app/src/main/jni/capnproto`

In order to install dependency, remove GitLab 0.8.1 build script and use our `script/dependency.sh`

See #594 for reference

PS: My GitLab account is lost, so I can't add patch for FDroid now

**Comment by jspricke** [comment]
I've opened a PR: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10239

**Comment by Bambooin** [comment]
I try to fix it, maybe this will work

1. `cmake` should 3.10.2
2. remove `srclibs` since we build from submodule
3. romove make `check` target, it's for test only
4. `nkd` should be r32

Please verify and change it if I am wrong about something

```
- versionName: 3.2.4
    versionCode: 20211130
    commit: d35d85039dd632aaa3bb99915fd0c5c5fe41a833
    subdir: app
    submodules: true
    sudo:
      - apt-get update || apt-get update
      - apt-get -y install g++ openjdk-11-jdk
      - update-alternatives --auto java
      - pushd app/src/main/jni/capnproto/c++
      - autoreconf -i
      - ./configure
      - make -j`nproc`
      - make install
      - popd
    gradle:
      - yes
    prebuild: JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 $$SDK$$/tools/bin/sdkmanager
        'cmake;3.10.2' > /dev/null
    scandelete:
      - app/src/main/jni
    ndk: r23
```

**Comment by Bambooin** [comment]
```
bash: line 0: pushd: app/src/main/jni/capnproto/c++: No such file or directory
```

Maybe `pwd` is already in `app`, and we just use `src/main/jni/capnproto/c++`?

Or git clone submodule path doesn't exist? This error is wired

**Comment by linsui** [comment]
In `sudo` pwd is in the root path of the fdroiddata repo. Is that possible the use capnproto with installing? Then we don't need sudo.

**Comment by Bambooin** [comment]
Maybe it's the cause of path issue

But the `make install` need sudo to install capnproto

I check the doc, sudo seem doesn't change `pwd` path

**Comment by linsui** [comment]
Another problem is that when we execute the sudo command, we haven't clone the app repo. So finally we have to use the srclib. Can we install capnproto in a local path?

**Comment by Bambooin** [comment]
Yes, we can build from `srclib`, but if we upgrade capnproto next time, F-Droid build script have to upgrade too.

**Comment by linsui** [comment]
Unfortunately, I don't know other solutions. You can ping us when you updating capnproto or we'll fix it when the build fails. Thanks!

**Comment by Bambooin** [comment]
The cmake should be 3.10.2, or the build will fail

https://github.com/osfans/trime/commit/c096c9b1cc57b29fe50f5e38f7942f991a2e9e87

**Comment by Bambooin** [comment]
It seems we don't have enough time to build, do you guy have permission to setup up timeout to 2 hours

https://docs.gitlab.com/ee/ci/runners/configure_runners.html#set-maximum-job-timeout-for-a-runner

**Comment by linsui** [comment]
It should be fine. I just merged it.

**Comment by jspricke** [comment]
Thanks linsui!

**Comment by iovxw** [comment]
> Can we install capnproto in a local path?

Yes, see `$CAPNP` https://github.com/osfans/trime/blob/d8686821762668db8523bba7b47897926827a426/app/src/main/jni/cmake/CapnprotoWorkarounds.cmake

**Comment by linsui** [comment]
Thanks! Could you  please elaborate how we should pass the `$CAPNP`? Maybe it can be built with gradle?

**Comment by iovxw** [comment]
> Could you please elaborate how we should pass the `$CAPNP`?
```bash
cd app/src/main/jni/capnproto
cmake -DCMAKE_INSTALL_PREFIX=/the/local/path/you/controlled
make
export CAPNP=/the/local/path/you/controlled/bin/capnp
```
> Maybe it can be built with gradle?

The problem is the path

capnproto have to be installed somewhere, and this path should be decided by user (gradle doesn't have a location for compile-time tools)

Or we can install it to the gradle's build dir, but that's dirty
