### ISSUE TITLE
按键音效包格式定义

### ISSUE THREAD

**Issue by tumuyan** [osfans/trime#636]
**Is your feature request related to a problem? Please describe.**
拟定增加自定义按键音效包

**Describe the solution you'd like**

1. 音效包文件放置到用户目录的sound子目录中。
2. 音效包包含一个配置文件和一组音频文件。
3. 配置文件包含存放音频文件的子目录名，音频文件列表，按键值与音频对应关系三部分
4. 按键与音频对应关系为多个分组，每组包含该组使用的按键键值范围，或者具体的哪几个按键（特别的，包含一个default分组），对应哪几个序号的音频文件或音频文件名，按键与音频文件是按顺序循环对应还是每次按键时随机触发

需要讨论的是，使用什么格式怎么加载文件？
1. 原有的yaml库似乎是从build目录里加载yaml，似乎需要赋值到build目录才行，不过问题不大
2. 引入新的库加载json或者yaml
3. 使用文本文件，用java类的序列化和反序列直接加载

**Describe alternatives you've considered**

**Additional context**
拟定初始化时直接加载全部音效，因此效果音上限为soundpool上限32.
每个音频文件大小上限为soundpool允许的上限100k

**Comment by iovxw** [comment]
现在用户目录里的东西有点太多了, 已经无法区分 trime 和 rime 的配置, 再增加一个 sound 文件夹实在多. 新建一个 trime 文件夹把 sound 和现有其他配置移动到内比较好?

同时也可以切分一下现在的 *.trime.yaml, 把重复的部分抽出来放进去

**Comment by tumuyan** [comment]
在考虑有没有必要增加类似midi音乐的功能。
也就是说，音效包内包含1 2 3 4 5 6 7不同音阶的音效，并且包含一个类似midi的乐谱，只要持续按按键，就会持续播放音乐，但是由于按键速度不稳定，音乐速度非常不稳定，就像一个拙劣上八音盒一样。
