### ISSUE TITLE
Split *.trime.yaml

### ISSUE THREAD

**Issue by iovxw** [osfans/trime#639]
**Is your feature request related to a problem? Please describe.**

*.trime.yaml is too big

#636

**Describe the solution you'd like**

Split `*.trime.yaml` to reusable modules, and keeps compatibility

将 `*.trime.yaml` 切分为可复用的模块同时保持兼容性

比如：

```
.
├── opencc
│   └── ...
├── sync
│   └── ...
├── trime                 <-- create trime dir
│   ├── colors.yaml
│   ├── keyboards.yaml
│   └── keys.yaml
│   └── sound
│       └── ...
├── trime.yaml
├── tongwenfeng.trime.yaml
└── ...
```

and include `trime/*.yaml` in `*.trime.yaml` with https://github.com/rime/home/wiki/Configuration#%E5%8C%85%E5%90%AB

然后将切分的  `trime/*.yaml` 包含进 `*.trime.yaml` 即可

**Describe alternatives you've considered**

**Additional context**

**Comment by tumuyan** [comment]
不建议对trime文件再做切分。
目前很多主题的配色和按键分组、fallback是一定程度耦合的。而按键又与键盘深度耦合，拆分之后实际上复用程度还是有限，还是只能凑合用。

另外实际上现在的目录结构是这样的，如果做调整，我觉得给主题丢到trime目录就完事了，没有必要再去拆分文件。

```
share
├── opencc
│   └── ...
├── trime.yaml
└── tongwenfeng.trime.yaml

user
├── sync
│   └── ...
├── build
│   └── ...
├── background
│   └── ...主题的background子目录
├── sound
│   ├──... sound folders
│   └── sound.yaml
├── 主题.trime.yaml
└── ...方案和词库


```

**Comment by iovxw** [comment]
你是对的

**Comment by tumuyan** [comment]
还是reopen吧。
我是支持移动trime.yaml的。
直接trime内放置每个主题的图片子目录，以及主题yaml文件。
font目录在用户目录下，取消background目录。sound维持现在pr的样子。

**Comment by iovxw** [comment]
> 我是支持移动trime.yaml的。

**Comment by iovxw** [comment]
> 我是支持移动trime.yaml的。

是指移动到 share？只是移动的话并没有意义吧

> 直接trime内放置每个主题的图片子目录，以及主题yaml文件。
> font目录在用户目录下，取消background目录。sound维持现在pr的样子。

这破坏了兼容性，得有迁移方案或者下个大版本才能做

按理说资源不需要特定前缀才对，我觉得直接用相对路径就挺好

**Comment by tumuyan** [comment]
是在user目录内移动，不是移动到share。
这样user目录下的散装文件就和小狼毫完全一致了。多的东西都在trime和sound目录里。
一个额外的好处是后续强制主题必须放到单独的子目录中，不在有background一堆图片文件。

变成这样
```
user
├── sync
│   └── ...
├── build
│   └── ...
├── trime
│   ├── ...主题的背景图folder
│   └── 主题.trime.yaml
├── sound
│   ├──... 音效包 folders
│   └── 音效包.sound.yaml
└── ...方案和词库
```

**Comment by starriddle** [comment]
个人想法，rime通用文件维持原目录结构，trime的特有文件，全都放到trime文件夹内，至于内部结构，主题yaml文件平铺，图片、音效包、字体，完全可以自定义路径，以trime目录作为根目录来引用。这些资源都是可以被多个主题共用的，不应该强制和主题yaml捆绑到一个目录；也不必都放到一个文件夹里，比如使用的背景图片比较多，也可以每个主题的图片分开来保存。所以感觉通过相对路径来引用比较好，至于这些文件怎么个结构，让我们这些DIYer们自己决定就可以了，毕竟众口难调，那就给个地方自己折腾吧。
我记得好象是哪里说过，准备把共享和用户文件夹合并的，不再分设两个？我好像一直就一个rime文件夹……
