### ISSUE TITLE
准备在FDroid上发布的帖子，大家先帮忙看看哈

### ISSUE THREAD

**Issue by boboIqiqi** [osfans/trime#64]
我写了一段简单的介绍。基本就是参照网站上别人的写法。
先贴到下面，一会睡眠前就发到FDroid上面。大家有空帮忙看看有什么问题不？

**trime**  --- A Chinese Input Method

Trime is an open source Chinese Input Method for Android which is based on another famous Open Source Chinese Input Method called Rime in PC (https://github.com/rime).

Rime is a cross-platform Input Method which can run in Windows, Linux and Mac and has a great population of users in China.

Trime's used Rime Core library, and runs in Android, so you will like it if you love Rime.

License:  Apache License V2.0 (https://github.com/osfans/trime/blob/develop/COPYING)
Source code:  https://github.com/osfans/trime
Issue Tracker:  https://github.com/osfans/trime/issues
Download:https://github.com/osfans/trime/releases/download/v3.0-beta2/trime-20160120.apk
Wiki: https://github.com/osfans/trime/wiki

======== The Home Page ==== 
https://github.com/osfans/trime
## License

```
Apache License 2.0
```
## 3rd Party Library

第三方庫/3rd Party Library
- android-cmake (BSD 3-Clause License)
- minilog (New BSD License)
- OpenCC (Apache License 2.0)
- RIME(BSD License)
  - Boost C++ Libraries (Boost Software License)
    - libiconv (LGPL License)
  - darts-clone (New BSD License)
  - marisa-trie (BSD License)
  - UTF8-CPP (Boost Software License)
  - yaml-cpp (MIT License)
  - LevelDB (New BSD License)
    - snappy(BSD License)
## Build

Arch Linux
`yaourt -S android-{ndk,sdk,sdk-build-tools,sdk-platform-tools,platform} apache-ant make apk`

![2016-04-21-22-04-47](https://cloud.githubusercontent.com/assets/1284515/14712038/30ac86f8-080e-11e6-81a0-ea2ff687a3dc.png)

**Comment by boboIqiqi** [comment]
这是一个通过的帖子
https://f-droid.org/forums/topic/forecastie/

**Comment by xiaoqun2016** [comment]
👍

**Comment by boboIqiqi** [comment]
网站不支持多级标题。

``` html
<ul>
<li>android-cmake (BSD 3-Clause License)</li>
<li>minilog (New BSD License)</li>
<li>OpenCC (Apache License 2.0)</li>
<li>RIME(BSD License)</li>
    <ul>
    <li>Boost C++ Libraries (Boost Software License)</li>
    <ul>
              <li>libiconv (LGPL License)</li>
    </ul>
    <li>darts-clone (New BSD License)</li>
    <li>marisa-trie (BSD License)</li>
    <li>UTF8-CPP (Boost Software License)</li>
    <li>yaml-cpp (MIT License)</li>
    <li>LevelDB (New BSD License)</li>
       <ul>
                   <li>snappy(BSD License)</li>
       </ul>
    </ul>
</ul>

```

**Comment by osfans** [comment]
讚一個！

**Comment by osfans** [comment]
找到了，哈哈。
https://f-droid.org/forums/topic/trime-a-chinese-input-method/

**Comment by osfans** [comment]
加你了，應該可以直接提交代碼了。

**Comment by boboIqiqi** [comment]
谢谢老大。争取早日成为一名合格的队员

**Comment by osfans** [comment]
這個fdroid似乎沒有人管我們的提交？
