### ISSUE TITLE
是否能够在切换中英文时自动切换全半角?

### ISSUE THREAD

**Issue by zinwalin** [osfans/trime#640]
大部分英文输入状态下，不需要全角英文，如果切换英文时能自动切换成半角及英文标点，会方便很多； 同样，中文状态下，自动切换为全角及中文标点。

这个需求有什么好的实现思路吗？

**Comment by starriddle** [comment]
这个，不是本来就这样的么？嗯，我这边切换中英文时标点符号也是自动切换的
