### ISSUE TITLE
v3.2.4 Cannot keep IME on English mode

### ISSUE THREAD

**Issue by austinhuang0131** [osfans/trime#643]
**Describe the bug**

* 切换至西文后，再次调用输入法时会切换回中文。
* 点击同一界面的另一输入框时亦然，但是状态栏中的开关却不会切换，直到输入后才会切换。

**To Reproduce**
Steps to reproduce the bug:
1. Change language to English using the switch on the status bar
2. Either select a different input field, or hide the keyboard then bring it up again

**Expected behavior**
Language remains English (as in v3.2.3)

**Log**
n/a

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: Sony Xperia XA2, H3123
 - OS: Android 9
 - Version: 3.2.4
 - Theme: Default

**Additional context**
n/a

**Comment by tusooa** [comment]
能复现，auto caps似乎也有问题。不知道有没有别的配置项也出问题的。
