### ISSUE TITLE
3.2.4 Always crash in LineageOS

### ISSUE THREAD

**Issue by InfinityLoop1308** [osfans/trime#644]
**Describe the bug**
when using 3.2.4 in LineageOS, it always result in crash, maybe every 30minute. After that, it needs around 30s to restart and work.

**To Reproduce**
Steps to reproduce the bug:
No specified steps. Just use it and it will crash soon.
Note crash can be triggered by open the app and click deploy.

**Expected behavior**
No crash.

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Oneplus 8
 - OS: LineageOS
 - Version: 18.1
 - Theme: Enhanced Tongwenfeng

**Additional context**

**Comment by Bambooin** [comment]
Maybe it's the config or `OOM` setting kill Trime

My device is LineageOS 18.1 and never found this issue

You can try this config: https://github.com/Bambooin/rimerc
**Reset all file in the setting**

Or you can try new daily build

**Comment by InfinityLoop1308** [comment]
> Maybe it's the config or `OOM` setting kill Trime
> 
> My device is LineageOS 18.1 and never found this issue
> 
> You can try this config: https://github.com/Bambooin/rimerc **Reset all file in the setting**
> 
> Or you can try new daily build

Sadly I am using JiuGong schema, so that not work for me. (But when I try using yours 26key schema it works really good and smoothly)
I think the problem is caused by the unwisely design of JiuGong schema, rather than Trime itself.
I will try to raise an issue to that repo, and this issue might be closed.
