### ISSUE TITLE
使用github action在线编译客制化Apk

### ISSUE THREAD

**Issue by tumuyan** [osfans/trime#648]
**Is your feature request related to a problem? Please describe.**
没有内置输入方案是同文的一个门槛，而对皮肤  包名  图标 的修改是一部分用户的切实需求。虽然使用工具也能做这些动作，但是并不方便。

**Describe the solution you'd like**
参考https://github.com/P3TERX/Actions-OpenWrt  
仿照自助编译openwrt，新开一个项目来帮助用户利用github action编译客制化同文App。同文仓库做如下变更来配合：
1. 添加复制更多内置文件到用户目录的方法
2. 去除矢量图标，方便用户自己用位图替换全部图标
3. 从另外的配置文件文件读取值作为App名称  
4. 从另外的配置文件读取值作为App预设的参数（比如指定user目录）
**Describe alternatives you've considered**

**Additional context**

**Comment by tumuyan** [comment]
https://github.com/tumuyan/trime-without-CMake/blob/develop/.github/workflows/build-my-trime.yml

已经在我的仓库，实现了基本的定制功能，ci文件如上。readme页面有简单的说明。

**Comment by WhiredPlanck** [comment]
> 2\. 去除矢量图标，方便用户自己用位图替换全部图标

这点请慎重考虑，当初全部换为矢量图就是考虑到各种场景下各个形状、大小变体制作困难、花样繁多，需要准备很多文件 ……

另外，矢量图标和位图互相不冲突，只用增加文件即可。
