### ISSUE TITLE
動態鍵盤標籤、動態輸入碼

### ISSUE THREAD

**Issue by DaengGWokFook** [osfans/trime#65]

**Comment by Prcuvu** [comment]
自定义西文键盘可以单独讨论，手写键盘和词句联想librime都没有提供，实现难度也不小。

**Comment by DaengGWokFook** [comment]
我用非英文字母的鍵盤，輸入英文時必須切換其它輸入法，所以想請教一下怎麼自定義西文鍵盤怎麼設置？在開啓多方案時，能一鍵轉換到指定的輸入方案嗎？

**Comment by osfans** [comment]
參考倉頡和注音鍵盤，都可以在英文狀態下輸入英文的

https://github.com/osfans/trime/blob/develop/assets/rime/trime.yaml#L1169

就是同一個鍵盤，中文狀態輸字根，英文狀態輸字母。

**Comment by osfans** [comment]
一鍵切換指定方案現在不行。不過不難，有時間我來做。

**Comment by DaengGWokFook** [comment]
這個我知道，我用其它文字輸入方案，直接上屏那種，只須schema和設好鍵盤就行，無須字典。但是想輸入英文時就出現麻煩，按西文切換後，鍵盤不是英文字母，還是原來的輸入碼。所以我才建議自定義英文鍵盤。

**Comment by xiaoqun2016** [comment]
@DaengGWokFook  如果是外语键盘，可以这样：  
{click: g, label: "ㅎ"}  
或者：  
{click: "ㅎ" , ascii: g}    

你可能需要按第二种来做

**Comment by osfans** [comment]
那應該xiaoqun提到的第二種能滿足你的需求。

**Comment by osfans** [comment]
比如符號鍵盤，可以同時支持中文模式和英文模式兩種。
https://github.com/osfans/trime/blob/develop/assets/rime/trime.yaml#L1048

**Comment by DaengGWokFook** [comment]
第二種方法果然行得通。
根據輸入碼改變label行嗎？
例如：中古三拼，鍵盤一開始label是第一行，輸入第一個碼後立刻顯示第二行label，輸入第二個碼後立刻顯示第三行label。選取文字上屏後，又回到第一行label。
![sampheng_1920_1080 gothic](https://cloud.githubusercontent.com/assets/18633778/14836262/c57bc128-0bdc-11e6-9e5a-2c31766fcb80.png)

**Comment by osfans** [comment]
這個好像不行，我來看下，應該又要正則比較好。

**Comment by osfans** [comment]
要不就不正則？只考慮是第幾個編碼？不過詞組的話，可能會有問題。

``` yaml
click: q
label: [影,  麻陽, x]
```

或者加入正則的話，有什麼更好的語法嗎？

**Comment by DaengGWokFook** [comment]
@osfans 
click:  q 
label:  [影,麻陽, x]
你所說的方法用哪個版本才能運用？

**Comment by osfans** [comment]
還沒做，確定需要的話，就做做看。

**Comment by DaengGWokFook** [comment]
label1: "影" label2: "麻陽" label 3: "x"
我覺得這樣比較好，先試試吧

**Comment by osfans** [comment]
這樣也不好，要是5碼的話，還得設label5。我再看看代碼裏面怎麼方便。

**Comment by DaengGWokFook** [comment]
label#1,2,3: ["影","麻陽", "x"]
這樣如何？

**Comment by DaengGWokFook** [comment]
突然想起了動態輸入碼。把兩個動態功能加上去可以嗎？
click#1,2,3: ["q","ia", "x"]

**Comment by xiaoqun2016** [comment]
双拼&三拼是librime拼写运算已经实现的功能。  
对比一下你说的动态输入：  

拼写运算是把拼音的组合映射到单个按键。  
动态输入是把单个的按键映射到拼音组合。  

两种做法相反，效果差不多。  
但拼写运算做出的方案可以多平台通用，
而动态输入做出的方案仅能在同文中使用。  

拼写运算可以多对一映射，比如自然码中的`iang`与`uang`都映射到了`d`键上，
而反过来，动态输入没办法一对多映射（若要把`d`键同时映射到`iang`和`uang`，相当于九宫格了）。  

动态标签是拼写运算的辅助，而动态输入是拼写运算的重复？

**Comment by osfans** [comment]
同意楼上，只做标签。楼主你是要跟label区分吗？那就用labels。但如果同时设label和labels，就只有labels起作用吧？

**Comment by DaengGWokFook** [comment]
@osfans 那就先照你的思路做個測試版，看看怎麼樣

**Comment by DaengGWokFook** [comment]
@osfans 動態鍵盤標籤再加個切換全角半角和中英符號自動轉換標籤

**Comment by osfans** [comment]
中英文现在有吧？
全角好像没有 但是rime中一个键可以对应多个全角或半角符号，所以还是不做吧。

**Comment by Bambooin** [comment]
过时的 issue
