### ISSUE TITLE
修改liquid_keyboard keyboards顺序造成symbol键盘从列表中消失

### ISSUE THREAD

**Issue by RFDAJE** [osfans/trime#652]
**Describe the bug**
想修改一下小键盘的排列顺序，symbol键盘应该在emoji后显示，但却在部署后从列表中消失，也就是emoji后变成了拉丁，而非symbol键盘。
`"liquid_keyboard/keyboards": [clipboard, emoji, symbol, lation, ascii, cn, exit, history, math, list, ids, pinyin, unit, exit, grease, rusa,  yinbiao, table, exit]
`

**To Reproduce**
Steps to reproduce the bug:
4. See bug

**Expected behavior**

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**
![IMG_20220101_111204](https://user-images.githubusercontent.com/22750/147848345-790ed967-4d16-4af7-971b-c3f92e3e6ac4.jpg)

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi 8 UD]
 - OS: [e.g. Android 10]
 - Version: [e.g. 3.2.4]
 - Theme: [e.g. Tongwenfeng]

**Additional context**

**Comment by tumuyan** [comment]
皮肤可能在更新时遗失了一些东西.
在symbol小节需要补充内容
`    type: SINGLE`

**Comment by RFDAJE** [comment]
问题解决，多谢。
