### ISSUE TITLE
preset_keys date command 输出错误结果

### ISSUE THREAD

**Issue by RFDAJE** [osfans/trime#653]
**Describe the bug**

`Date: {label: 日期, command: date, option: "yyyy-MM-dd"}` 应输出例如`2022-01-02`，结果输出错误的`2022 M01 2`

**To Reproduce**
Steps to reproduce the bug:
4. See bug

**Expected behavior**

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi 8 UD]
 - OS: [e.g. Android 10]
 - Version: [e.g. 3.2.3]
 - Theme: [e.g. Tongwenfeng]

**Additional context**

**Comment by Bambooin** [comment]
see #617

You can use version 3.2.4+
