### ISSUE TITLE
v3.2.4 横屏下键盘无法显示

### ISSUE THREAD

**Issue by starriddle** [osfans/trime#654]
**Describe the bug**
之前3.1.3版本正常，更新到3.2.4后就显示不了横屏键盘，竖屏下显示正常。
有时候会闪一下，猜测是个错误提示框，不过太快了，不知道是个啥，闪一下就没了
通过 F-Droid 市场安装的

**Log**
不知道日志哪里找？

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10 Pro
 - OS: MIUI 12.5.* 稳定版，Android 11
 - Version: 3.2.4
 - Theme: 默认，同文风（升级的时候，将原rime配置文件夹重命名了，因此主题配置都是新的版本）

**Comment by astroshot** [comment]
我用 Fdroid 版 3.2.4 也出现过这个问题，后来在设置里把横屏模式改成『自动』就没问题了

**Comment by starriddle** [comment]
多谢，终于解决了，都准备退回到3.1.3了，汗
不管把横屏模式设置成哪个选项，都可以正常显示了，而安装后默认的未设置导致横屏显示不了，也是醉了
话说，试了自动、总是、从不，发现三个选项下，横屏显示都是一样的……所以加了这个选项使用来干嘛的
