### ISSUE TITLE
关于剪贴板和语音输入能否调用系统内置功能[MIUI相关]

### ISSUE THREAD

**Issue by starriddle** [osfans/trime#655]
**Is your feature request related to a problem? Please describe.**
1. trime 增加了剪贴板功能，对于本身没有该功能的手机来说很有用，但是如果系统本身就有该功能的话，其实就重复了。
2. 原先VOICE_ASSIST 按键能够调出系统的语音输入功能（3.1.3 + MIUI11），然后不知道啥时候开始，我的MIUI用不了了

**Describe the solution you'd like**
1. 剪贴板功能能否设置为可以开启关闭的组件式功能呢，资源能省一点是一点，哈哈。然后想办法找到系统内置剪贴板的调用接口，直接通过一个按键就可以调用，不可否认，人家内置的总归是要更稳定一点
2. MIUI 从12 开始，出来了一个全面屏键盘优化的功能，但是貌似只有内置输入法才能享受。我的想法是能否把里面的语音输入和剪贴板（其实主要就是这俩）的接口找到，在trime里能够通过按键唤出

**Describe alternatives you've considered**
做到和内置输入法那种效果其实也可以，但推测可能会比较麻烦，毕竟人家内置输入法是双方合作的

**Additional context**
![001](https://user-images.githubusercontent.com/10235625/147934243-df2dcd80-5fd3-406f-b2a9-504d884b61a2.jpg)

![002](https://user-images.githubusercontent.com/10235625/147934253-c092740b-f5f0-45c6-ba4d-3609df9d5307.jpg)

![003](https://user-images.githubusercontent.com/10235625/147934264-d614305b-2c35-41f2-87e2-697962830490.jpg)

**Comment by ameaninglessname** [comment]
剪贴板功能怎么用的?可以呼出一个面板么,我在rime里没找到呼出方式

**Comment by ameaninglessname** [comment]
操作方式可否补充到文档里呢

**Comment by ameaninglessname** [comment]
我发现了，由于是新功能，使用老皮肤的话，没有对应的按键，
用同文风默认皮肤可以

**Comment by tumuyan** [comment]
使用这个功能需要修改输入法的包名为miui合作版的输入法的包名.
譬如百度  com.baidu.input_mi

**Comment by tumuyan** [comment]
> 操作方式可否补充到文档里呢

见 https://github.com/tumuyan/trime-without-CMake/wiki/键盘布局
目前这部分功能还没有完善,因此没有添加到正式wiki文档中

**Comment by ZeekoZhu** [comment]
可以使用 Lsposed 模块：解锁 MIUI 键盘优化，在 MIUI 12.5 中测试有效。
