### ISSUE TITLE
邮件客户端 K-9 Mail或者FairEmail 收件人To: 栏无法弹出键盘进行输入

### ISSUE THREAD

**Issue by RFDAJE** [osfans/trime#659]
**Describe the bug**
邮件客户端 K-9 Mail或者FairEmail 收件人To: 栏无法弹出键盘进行输入

**To Reproduce**
Steps to reproduce the bug:
4. See bug

**Expected behavior**
键盘应该弹出允许输入

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. MI 8 UD MIUI 12.0.5]
 - OS: [e.g. Android 10]
 - Version: [e.g. 3.2.x]
 - Theme: [e.g. Tongwenfeng]

**Additional context**

**Comment by tumuyan** [comment]
这个应该是 #645 已经修复过的bug.
我自己编译的版本是可以正常弹出键盘的

![Screenshot_2022-01-07-23-13-47-926_com fsck k9](https://user-images.githubusercontent.com/3126801/148564426-eb46f2ee-356d-4cd9-b3e3-993fee33e57c.jpg)
