### ISSUE TITLE
部署后需要停止运行“同文输入法”，修改才生效

### ISSUE THREAD

**Issue by RFDAJE** [osfans/trime#660]
**Describe the bug**
部署后需要停止运行“同文输入法”，修改才生效

**To Reproduce**
Steps to reproduce the bug:
4. See bug

**Expected behavior**
部署后，再次弹出键盘进行输入，修改没有生效。必须强行停止运行“同文输入法”后，再弹出键盘修改才生效。

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. MI 8 UD MIUI 12.0.5]
 - OS: [e.g. Android 10]
 - Version: [e.g. 3.2.x]
 - Theme: [e.g. Tongwenfeng]

**Additional context**

**Comment by zhin2929** [comment]
我也遇到了，不能立刻生效，有点麻烦
