### ISSUE TITLE
最新版trime不支持lua，建议trime.yaml修改时间格式

### ISSUE THREAD

**Issue by tao659** [osfans/trime#665]
**Is your feature request related to a problem? Please describe.**
※ 常用的时间选项：y年，M月，d日，h时（12小时制），H时（24小时制），m分，s秒，S毫秒，E星期，D一年中的第几天，w一年中第几个星期，a上午/下午，z时区

E 输出为 周一，周二，周日
能否改E成输出一，二，日，用户可以根据需求
设置   星期E
或者 周E适应不同需求

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tumuyan** [comment]
此功能由lua脚本提供

**Comment by tao659** [comment]
找到这个https://github.com/hchunhui/librime-lua
参照usage 弄了一番 不起作用
rime.lua 文件
function date_translator(input, seg)
   if (input == "date") then
      --- Candidate(type, start, end, text, comment)
      yield(Candidate("date", seg.start, seg._end, os.date("%Y年%m月%d日"), " 日期"))
   end
end

function single_char_first_filter(input)
   local l = {}
   for cand in input:iter() do
      if (utf8.len(cand.text) == 1) then
         yield(cand)
      else
         table.insert(l, cand)
      end
   end
   for i, cand in ipairs(l) do
      yield(cand)
   end
end

在schema中也加了

engine:
  ...
  translators:
    ...
    - lua_translator@date_translator
    ...
  filters:
    ...
    - lua_filter@single_char_first_filter

重新部署 不管用

**Comment by tao659** [comment]
> 此功能由lua脚本提供
找到这个https://github.com/hchunhui/librime-lua
参照usage 弄了一番 不起作用
rime.lua 文件
function date_translator(input, seg)
if (input == "date") then
--- Candidate(type, start, end, text, comment)
yield(Candidate("date", seg.start, seg._end, os.date("%Y年%m月%d日"), " 日期"))
end
end

function single_char_first_filter(input)
local l = {}
for cand in input:iter() do
if (utf8.len(cand.text) == 1) then
yield(cand)
else
table.insert(l, cand)
end
end
for i, cand in ipairs(l) do
yield(cand)
end
end

在schema中也加了

engine:
...
translators:
...
- lua_translator@date_translator
...
filters:
...
- lua_filter@single_char_first_filter

重新部署 不管用

**Comment by tumuyan** [comment]
> 找到这个https://github.com/hchunhui/librime-lua 参照usage 弄了一番 不起作用 rime.lua 文件 function date_translator(input, seg) if (input == "date") then --- Candidate(type, start, end, text, comment) yield(Candidate("date", seg.start, seg._end, os.date("%Y年%m月%d日"), " 日期")) end end
> 
> function single_char_first_filter(input) local l = {} for cand in input:iter() do if (utf8.len(cand.text) == 1) then yield(cand) else table.insert(l, cand) end end for i, cand in ipairs(l) do yield(cand) end end
> 
> 在schema中也加了
> 
> engine: ... translators: ... - lua_translator@date_translator ... filters: ... - lua_filter@single_char_first_filter
> 
> 重新部署 不管用

你确认部署后,输入date没有结果嘛?另外你的single_char_first_filter应该是不需要的

**Comment by tao659** [comment]
是的， 没有反映，single_char_first_filter 是例子带的， 刚开始没有加single_char_first_filter，没效果，后来加了也没效果， 用的是 四叶草 方案， luna_pinyin也试过， 都没有效果，只输出打字词语， 不会出现日期

>

**Comment by tao659** [comment]
> > 找到这个https://github.com/hchunhui/librime-lua 参照usage 弄了一番 不起作用 rime.lua 文件 function date_translator(input, seg) if (input == "date") then --- Candidate(type, start, end, text, comment) yield(Candidate("date", seg.start, seg._end, os.date("%Y年%m月%d日"), " 日期")) end end
> > function single_char_first_filter(input) local l = {} for cand in input:iter() do if (utf8.len(cand.text) == 1) then yield(cand) else table.insert(l, cand) end end for i, cand in ipairs(l) do yield(cand) end end
> > 在schema中也加了
> > engine: ... translators: ... - lua_translator@date_translator ... filters: ... - lua_filter@single_char_first_filter
> > 重新部署 不管用
> 
> 你确认部署后,输入date没有结果嘛?另外你的single_char_first_filter应该是不需要的

研究了几天， windows 上实验出来了，Android没有弄出来，貌似trime不支持 lua？

**Comment by tumuyan** [comment]
我测试了最新版的确没有lua支持了，原因不明。
之前是可以的

**Comment by iovxw** [comment]
我的锅, 插件加载出了点问题, 但现在 log 没有修好, 不太好 debug

这周末修复
