### ISSUE TITLE
由App指定Enter键的文字

### ISSUE THREAD

**Issue by tumuyan** [osfans/trime#669]
**Is your feature request related to a problem? Please describe.**
输入法的Enter键由App指定所显示的内容，显示完成、发送、搜索、下一个等不同文字。

**Describe the solution you'd like**
在onStartInputView()时，从EditorInfo中读取信息，并修改Enter键的文字为完成、发送、搜索、下一个等

**Describe alternatives you've considered**
对其他输入法来说并不困难，但是对目前同文的皮肤影响较大，实现难度较高。（可能可以参考空格键，但是我并不清楚目前的空格键的文字是怎么显示输入方案名称的）

**Additional context**

**Comment by iovxw** [comment]
可以加入几个新的状态, 类似现在的 `ascii` `paging` `has_menu`, 让用户自己根据类型做选择

还可以允许扩展更多状态, 顺便解决 #578 这样的问题

比如一个键的配置可以这样:

```yaml
 - {click: Enter, label: 回车, when: {type: search, label: 搜索}}
```

**Comment by tumuyan** [comment]
> 可以加入几个新的状态, 类似现在的 `ascii` `paging` `has_menu`, 让用户自己根据类型做选择
> 
> 还可以允许扩展更多状态, 顺便解决 #578 这样的问题
> 
> 比如一个键的配置可以这样:
> 
> ```yaml
>  - {click: Enter, label: 回车, when: {type: search, label: 搜索}}
> ```

 情况其实很不一样. Enter键的文字,是由文本框属性指定的,是说文本框已经有明确的文字,而不是输入法解析属性判断这个值应该转换为什么文字.

**Comment by iovxw** [comment]
> 情况其实很不一样. Enter键的文字,是由文本框属性指定的,是说文本框已经有明确的文字,而不是输入法解析属性判断这个值应该转换为什么文字.

给这个 label 提供默认值就可以了, 用户需要能自己控制究竟是显示 "搜索" 还是 "🔍", 抑或是不使用

**Comment by tumuyan** [comment]
在主题style小节中增加以下参数, 并修改Enter键的label为`enter_labels`, 即可定义不同情景下的Enter键文字, 推荐按键搭配composing参数使用.
内置主题已完成修改.

```

  action_label_type: never  #是否使用App的ActionLabel内容作为Enter键的文本 only | first | last | never
  enter_labels:  # 定义Enter键在不同情景下显示的文本
    go: 前往
    done: 完成
    next: 下个
    pre:  上个
    search: 搜索
    send: 发送
    default: Enter   # 定义默认Enter键的文本

```
