### ISSUE TITLE
想要解决乱码  

### ISSUE THREAD

**Issue by boboIqiqi** [osfans/trime#67]
[] 发现界面上方按钮的提示是乱码，就是末尾都 鈫？ 这样。 修选字里有时也会出现。好像跟繁体字有关。候选字里一般是末尾出现一个 鋁？
[] 进入语音输入时提示也是乱码
我这不好发图片。
不过感觉这应该比较好解决。我自己想试着解决一下。大家有什么意见。这个算是bug吧。还是只有我机器上有？跟设置有关吗？

另外老大交付的事还没做完，最近帖子一直没被审核。我再跟进一下

**Comment by boboIqiqi** [comment]
不是说[]会有任务列表，怎么出不来

**Comment by osfans** [comment]
什么任务列表？好像没有遇到乱码。你是把电脑上的bin直接拷来用了吗？

**Comment by boboIqiqi** [comment]
对，我是直接编译运行到电脑上的。这样会有问题吗？
就是github markdown

[ ] 未完成的工作
[x] 已完成的工作

**Comment by boboIqiqi** [comment]
- [] 未完成
  -[] 未完成
  -[x] 已完成

**Comment by osfans** [comment]
- [ ] 未完成的工作
- [ ] 已完成的工作

所以前面要加個減號？

**Comment by boboIqiqi** [comment]
![Uploading Screenshot_2016-04-24-08-04-09.jpeg…]()
刚开始确实是乱码。可能是我编译的环境设置得有问题吧。

重新编译了一下好了。

![Uploading Screenshot_2016-04-25-22-25-01.jpeg…]()

**Comment by osfans** [comment]
看不见图片 要不发qq群或者贴吧？

**Comment by boboIqiqi** [comment]
我们有QQ群吗？我加一下
