### ISSUE TITLE
无法设置键盘默认为英文输入模式

### ISSUE THREAD

**Issue by z99h** [osfans/trime#679]
**Describe the bug**
无法设置键盘默认为英文输入模式

**To Reproduce**
Steps to reproduce the bug:
1. tongwenfeng.trime.yaml 里修改 style/layout/reset_ascii_mode 为 false, preset_keyboards/default/ascii_mode 修改为 1
2. double_pinyin_plus.schema.yaml 里修改如下:
```xml
switches:
  - name: ascii_mode
    reset: 1
    states: [ 中文, 西文 ]
 ```
3. 重新加载 trime 后，打开任意 app，默认还是中文输入模式，切换为英文，切换到手机桌面，再切换回来，输入模式又变成了英文

**Expected behavior**
1. 可以通过某种设置，让 trime 初始状态下默认输入英文
2. 可以通过某种设置，让 trime 记住上一次使用时（全局）的输入模式，比如我在 app A 里面打英文，切到手机桌面，再回来，trime 应该还是英文模式

**Log**
N/A

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21
 - OS: Android 12
 - Version: v3.2.4-20211220
 - Theme: Tongwenfeng（修改过 preset_keyboards/default 的键盘布局）

**Additional context**
N/A

**Comment by qq1767899088** [comment]
同样的需求，我觉得很多人需要可以默认英文，我提交了同样的请求去年，然而好几个版本过去了，还是没有被修复

**Comment by Bambooin** [comment]
You can try the latest daily build, seem fix by #711

**Comment by goduck777** [comment]
最新版本里面在切换程序时 ascii_mode 确实可以保持住了。但是在切换键盘时候还是会重置，比如从default的qwerty键盘切换到数字键盘，再返回default键盘就会发现键盘变回了默认的ascii_mode。

请问能不能在切换键盘时也不要reset。在之前的版本中，如果设置了reset_ascii_mode=0，就不会在切换键盘时重置。

**Comment by InfinityLoop1308** [comment]
> 最新版本里面在切换程序时 ascii_mode 确实可以保持住了。但是在切换键盘时候还是会重置，比如从default的qwerty键盘切换到数字键盘，再返回default键盘就会发现键盘变回了默认的ascii_mode。
> 
> 请问能不能在切换键盘时也不要reset。在之前的版本中，如果设置了reset_ascii_mode=0，就不会在切换键盘时重置。

Can not reproduce this problem. Could you provide your keyboard config?
In current version, if the `reset_ascii_mode` is set to `true`, it will reset the keyboard to its configured `ascii_mode` .

**Comment by z99h** [comment]
> You can try the latest daily build, seem fix by #711

Confirmed, thanks

**Comment by goduck777** [comment]
> > 最新版本里面在切换程序时 ascii_mode 确实可以保持住了。但是在切换键盘时候还是会重置，比如从default的qwerty键盘切换到数字键盘，再返回default键盘就会发现键盘变回了默认的ascii_mode。
> > 请问能不能在切换键盘时也不要reset。在之前的版本中，如果设置了reset_ascii_mode=0，就不会在切换键盘时重置。
> 
> Can not reproduce this problem. Could you provide your keyboard config? In current version, if the `reset_ascii_mode` is set to `true`, it will reset the keyboard to its configured `ascii_mode` .

I know, but I want trime to remember the last setting of ascii_mode, not jut reset it every time I change the keyboard.

In the previous version, if I switch to ascii mode in Chinese keyboard, then switch to number keyboard to input some numbers, then switch back to Chinese keyboard, the ascii mode is still there. This is true no matter what value of reset_ascii_mode is set.

This behavior is consistent with other IME like Gboard. However, in the current version, when I switch back to Chinese keyboard, it always reset to the mode set in reset_ascii_mode. Basically, there is no variable to save the current status of ascii_mode, and the IME can only do reset.

I am not very familiar with Java/Kotlin, but I think someone remove the class property to save the status in of ascii_mode in recent changes. I hope someone can add it back.

**Comment by InfinityLoop1308** [comment]
> I know, but I want trime to remember the last setting of ascii_mode, not jut reset it every time I change the keyboard.

In my opinion, this is just the behavior with `reset_ascii_mode=false`. Could you please try it?

**Comment by goduck777** [comment]
No, this post is about the behavior of reset_ascii_mode=false. Please take a look at the first post.

The issue is that, even with setting reset_ascii_mode=false, the keyboard can still be reset sometimes. The #711 fix the issue when switching apps, but did not fix the issue when switching to num keyboard and switch back.
