### ISSUE TITLE
候选字上方的按钮，建议做成图标，不要是文字

### ISSUE THREAD

**Issue by boboIqiqi** [osfans/trime#68]
![Uploading Screenshot_2016-04-25-22-25-01.jpeg…]()

上面是我平时用的触宝输入法。
感觉图标更好一点，文字有时候不知道去点，而且功能多了，纯文字不好描述

**Comment by xiaoqun2016** [comment]
状态栏图标现在是开放给用户自定义的，是在schema.yaml中更改。  
可以半文字半图标：  
![screenshot_2016-04-26-10-05-47-1](https://cloud.githubusercontent.com/assets/16501929/14804623/b8e203d0-0b2a-11e6-8e4c-0dccbdca6a98.jpg)  
或者纯图标：  
![screenshot_2016-04-26-10-08-33-1](https://cloud.githubusercontent.com/assets/16501929/14804634/cb30639c-0b2a-11e6-8fce-83c9a54a5825.jpg)  

不知道是不是你要的效果？

另外，issue上传图片时，要等github传完，再点comment提交。如果没有传完就提交，就会出现你那样[Uploading ……

**Comment by boboIqiqi** [comment]
好的，谢谢你 @xiaoqun2016 .你的回答总是直击要点。
我问问哈：
- 你用的是什么编辑器？怎么可以显示图片呢？你输入的那个是emoji表情吗？
- 你下面的个图片是自己合成的？还是实时预览呀？

**Comment by xiaoqun2016** [comment]
- 是emoji，不是图片。  用的是QuickEdit，语法高亮和正则表达式支持得不错。如果要处理超大文本，用VimTouch可能更快。  
- 部署后直接截图的，没有合成。Rime没有预览功能。

**Comment by Bambooin** [comment]
过时的 issue
