### ISSUE TITLE
v3.2.5版没有“编码栏”提示

### ISSUE THREAD

**Issue by wwzrh** [osfans/trime#682]
**Describe the bug**
![微信图片_20220207095853](https://user-images.githubusercontent.com/12047479/152714281-00379cc3-799b-41cf-a641-294a645d6711.jpg)
@Bambooin @WhiredPlanck @tumuyan @iovxw

**Comment by tumuyan** [comment]
点输入配置-恢复默认设置，覆盖一下主题文件

**Comment by wwzrh** [comment]
收到，谢谢
