### ISSUE TITLE
改进与scrcpy的易用性

### ISSUE THREAD

**Issue by ameaninglessname** [osfans/trime#683]
**Is your feature request related to a problem? Please describe.**
在使用scrcpy无线连接到手机时，
直接用电脑的键盘控制手机打字，
会有一些问题。
并且我并不确定是trime还是srccpy的问题
[scrcpy,一个手机投屏到电脑的软件](https://github.com/Genymobile/scrcpy)， 比如：

1. 在选择候选字时，需要按两下
2. 在想输入‘，’逗号时，按下无效，必须先按下shift，切到英文，再按下shift，切回中文，就可以输入逗号了

**Describe the solution you'd like**
最佳状态就是 电脑的按键输入可以完美复制到手机的trime上，或者更好用

**Comment by WhiredPlanck** [comment]
@ameaninglessname 我日常通过模拟器测试时感觉还好。请问现在如何？

**Comment by ameaninglessname** [comment]
Trime: 尝试在不同软件输入"default":
https://github.com/osfans/trime/assets/20263103/b75e90fd-93b8-4d41-b6f4-6d70ab0dd7bd


Gboard:尝试输入default及其它文字:
https://github.com/osfans/trime/assets/20263103/c6fcbbb9-2c39-4fc6-9e65-0927ad999481

目前我使用scrcpy,在安卓14 crdroid系统上,无法正常使用trime,部分日用软件点击输入框就黑屏,像是从下往上展开了什么东西. 盲打倒是可能可以用.候选词也只能盲选,对比Gboard可用性不太够.

**Comment by goofyz** [comment]
奇怪。我一直都是用 scrcpy 在 PC 上控制我的手機 (Android 7, 10, 13, 14 也試過)。
用 trime 完全正常，沒有黑屏的問題。會有 soft keyboard 彈出來，也可直接用PC 鍵盤打字。
你是用最新的版本嗎？

**Comment by ameaninglessname** [comment]
> 奇怪。我一直都是用 scrcpy 在 PC 上控制我的手機 (Android 7, 10, 13, 14 也試過)。
> 用 trime 完全正常，沒有黑屏的問題。會有 soft keyboard 彈出來，也可直接用PC 鍵盤打字。
> 你是用最新的版本嗎？

是的，最新版。

如果你们无法复现的话，那可以先关闭这个issue
