### ISSUE TITLE
用v3.2.5版定制的“编辑键盘”按键Shift_L+Left('←')和Shift_L+Right('→')组合键不起作用

### ISSUE THREAD

**Issue by wwzrh** [osfans/trime#685]
用v3.2.5定制的“编辑键盘”按键Shift_L+Left('←')和Shift_L+Right('→')组合键不起作用
![微信图片_20220211162302](https://user-images.githubusercontent.com/12047479/153559177-60c57671-27a1-4727-8b7a-23cca8a25c29.jpg)
使用“tongwenfeng.trime.yaml”的“Keyboard_numberb”编辑键盘的组合键也无效。
请大侠帮忙测试一下，谢谢！
@Bambooin @WhiredPlanck @tumuyan @iovxw

**Comment by zhin2929** [comment]
的确是无效

**Comment by shitlime** [comment]
确实存在这个问题，一直在烦恼这个问题，今天想发issues发现github上已经有了。
具体表现为`Shift`键按下后**能触发**`shift_lock`（以按键颜色改变为依据），但是配合方向键`↑ ↓ ← →`**无法选择**输入框的文本内容。
在旧版本中并无这个问题，是不是v3.2.5按键的逻辑有所修改导致`Shift+方向键`无法选择文字？

附：
shift按键的配置：
`Shift_Lxz: {label: 选择, preview: '⇪', functional: false, send: Shift_L, shift_lock: click}`
