### ISSUE TITLE
是否能够长按一个按键对应多个字符？

### ISSUE THREAD

**Issue by deluxghost** [osfans/trime#687]
范围包括主键盘和 liquid_keyboard，前者类似 gboard 长按字母可以弹出多个字符，松手输入

后者类似各种 emoji 键盘，一个键位可以对应多个当前表情的变体（对应不同人种皮肤颜色等）

**Comment by tumuyan** [comment]
实现方法和操作逻辑完全不同，绝无可能。这个就像其他输入法没有按键左右上下四个方向滑动的动作一样
