### ISSUE TITLE
候选区如何设置序号？

### ISSUE THREAD

**Issue by Schezuk** [osfans/trime#689]
候选区如何设置为有序号？不然需要数自己选了哪个
<img src="https://camo.githubusercontent.com/05538f717c12c6f84b3dd7721769a8d317984aced7dd6053644caf5bec230e36/687474703a2f2f696d677372632e62616964752e636f6d2f666f72756d2f7069632f6974656d2f323461306461663262323131393331333931306636633064363233383063643739303233386432362e6a7067">
类似于rime版本
<img src="https://camo.githubusercontent.com/ccf1aa20feee0d38291d2a90406554ee68985f7e350a12b11bbcd74744d74671/687474703a2f2f692e696d6775722e636f6d2f685374793663422e706e67">

另外，如果menu候选项多，能否自动延迟到第二批预选项，而不是需要手动左右滑动找到不可见区的候选项？

**Comment by Schezuk** [comment]
![Screenshot](https://user-images.githubusercontent.com/7524886/154594774-8a3d7ffa-0faf-4562-8b67-ce0920d317fd.jpg)
如图，垂直候选区有序号而水平候选区没有，在哪里设置能补上？

而且最右侧的候选列表超过了候选区范围，需要手动移动才能看见，如何设置自动推迟到下一屏？

**Comment by mitnk** [comment]
在你的主题文件 `xxx.trime.yaml` 中
在 `style:` 下面找到 `window:` 将它的的内容中的第二项的 `label` 加上 `%s`. 如
```
...
style:
  ...
  window:
      - {start: "‍🦀 ", composition: "%s", end: "", letter_spacing: 0}
      - {start: "\n", label: "%s.", candidate: "%s", comment: " %s", end: "", sep: " "}
```
