### ISSUE TITLE
可否調用第三方字體作為候選字的顯示字體？

### ISSUE THREAD

**Issue by Pljvr** [osfans/trime#690]
鑑於Android系統無Root權限無法安裝擴展字元集，希望能通過輸入法本身來調用外部第三方字體的ttf檔案以實現候選字自定義字體。

為了於Android系統顯示內置資源集所不包含的字元（通常是顯示方格），嘗試過改變系統顯示字體的方法（非安裝擴展字元集到系統中），但由於此方式是調用某一字體檔作為系統介面所有文字的默認顯示字體，通通套用，因而會出現更多其他顯示問題。

以上所講的字體，並不是手機字體風格-即標楷體、黑體、細明體、仿宋體之類-這種，而是擴展字元。類似於某些語言文字的字元集。在用同文輸入法輸入西夏文、契丹文、女真文等系統字元集所不帶的文字時，如果能調用外部字體顯示候選字，將會極大提高輸入體驗，並且防止系統介面因改變系統顯示字體而出現形變。

*改變候選字字體或又可以通過輸入法皮膚來實現。
但查/rime中檔案xxx.trime.yaml，其中有«candidate_font: han.ttf #候選字型»，不知從何調用。

**Comment by Schezuk** [comment]
放入rime/fonts/文件夹下
扩b有hanb选项

**Comment by Pljvr** [comment]
> 放入rime/fonts/文件夹下
> 扩b有hanb选项

嘗試於rime/fonts/目錄中放置相應字體檔案，並重命名為han.ttf，重新部署之後，輸入法候選字可以應用該字體。
但若果將檔案重命名為hanb.ttf，側候選字仍以系統字體顯示，然而擴充字符集中文字不可顯示，仍為方格。
【另外，可否將rime/fonts/目錄中han.ttf與hanb.ttf兩者之外的字體檔案作為擴充字符庫的存在（或者將fonts的某一子目錄作為擴充庫），以方便多語言文字的切換】

**Comment by Schezuk** [comment]
直接
candidate_font: HanaminA.ttf
hanb_font: HanaminB.ttf
即可
文件夹里原名放置HanaminA.ttf和HanaminB.ttf

**Comment by Pljvr** [comment]
已找到解決方案，對於多語言文字方案的輸入，直接修改相應方案的schema.yaml即可。預估是PC端與Android端rime輸入法調用字體檔案的字符串之邏輯有異。

具體操作：
查所使用的幾種古代文字輸入法的schema.yaml檔案（此檔案原初為PC的rime輸入法設計），其中均有以下字符串：

style:
  font_face: "‹字體檔基本名›"
  font_point: 30 #字號

此數行為一般rime平台的中文輸入法所不具備

原中間一行：
  font_face: "‹字體檔基本名›"
改為：
  candidate_font: ‹字體檔全名›.ttf
如此即可用於Android版的同文輸入法

同時，Android上需將“‹字體檔全名›.ttf”置於rime/fonts/檔案夾內。

說明：
由於古文字數字化受新考古發現影響，時常會有字符集更新，故其字體檔命名一般規則是：【‹字體基本名›+‹版本號›.ttf】，即【XXX vX.X.X.ttf】的格式。
PC平台上系統可識別字體檔案的具體資料，而Android平台上無法安裝擴展字元集，且同文輸入法只可依據字體檔案名來調用rime/fonts/中的檔案，故作此改動。

補充：
  candidate_font: ‹字體檔全名›.ttf
中
‹字體檔全名›可自訂，但務必保持與rime/fonts/中的檔案名相同。
