### ISSUE TITLE
「抬」字没有正确转为简化字

### ISSUE THREAD

**Issue by Reniastyc** [osfans/trime#695]
**Describe the bug**
应该是OpenCC的问题，在简化字模式下，「抬」字还是传统字

**To Reproduce**
Steps to reproduce the bug:
4. See bug
完全从最初安装，切到简化字模式，发现「抬」字没有简化

**Expected behavior**

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**
![QQ图片20220302140819](https://user-images.githubusercontent.com/37499529/156305199-bab77a49-5fe7-4005-90dd-5c1497254200.jpg)

**Comment by tumuyan** [comment]
建议简中用户直接用简中词库(譬如我在用的袖珍简化字拼音),不要用opencc转换了
明月拼音简化字,打咩

**Comment by Zerorigin** [comment]
这个问题好像应该去 OpenCC 项目里反馈？
