### ISSUE TITLE
Google play最新版在Android 13 DP1無法顯示候選字

### ISSUE THREAD

**Issue by subaruphoe** [osfans/trime#696]
![Screenshot_20220303-131801](https://user-images.githubusercontent.com/62179261/156501375-03131ad7-9459-4baf-a2be-f1e493a1e9e2.png)
用release裡的最新版也一樣，版本TPP1.220114.016，裝置Pixel 6

**Comment by wzyboy** [comment]
该问题在 Beta 3.3 TPB3.220617.002 依然存在

**Comment by wzyboy** [comment]
更新到 3.2.7 问题得到了修复。
