### ISSUE TITLE
正确读取共享文件夹中的主题

### ISSUE THREAD

**Issue by h0cheung** [osfans/trime#697]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
在目前版本，共享文件夹中的主题不能被正确读取。具体表现为:
1. 如果共享文件夹中不含 trime.yaml，trime 会在共享文件夹生成默认主题文件。
2. 设置中的主题选择只会显示用户文件夹中的主题
只有用户文件夹中含有 trime.yaml 时，主题选择才会显示＂默认＂，也只有此时才可以切换到其他主题（无此文件会显示其他主题但切换无效）。
3. 共享文件夹中的 trime.yaml 可作为默认主题被读取，但起不到 2. 中描述的作用，其他主题文件则无效。
4. 如上，trime 读取主题文件的逻辑似乎比较混乱，与 rime 读取配置文件文件的规则不符。

**Describe alternatives you've considered**

**Additional context**

**Comment by Bambooin** [comment]
Fix in #889

**Comment by h0cheung** [comment]
> Fix in #889

在含有该 pr 的版本中仍然异常，可以看到共享文件夹里的主题，但是启用它们之后就会直接变成默认主题。
而且，trime 还是会自动往共享文件夹添加内置主题文件和 user.yaml，按理说共享文件夹应该是只读的。
