### ISSUE TITLE
上排鍵位的字符大小設置無效

### ISSUE THREAD

**Issue by zaqzrh** [osfans/trime#7]
1、上排鍵位的字符大小設置無效(鍵盤字號已調到28,無作用)；
2、輸入欄的編碼字母無法更改大小；
請考慮。

**Comment by osfans** [comment]
根據鍵盤字號按比例設定？或者分別設定？
放在yaml中自定義？

**Comment by zaqzrh** [comment]
1、上排鍵位的字符大小,根據鍵盤字號按比例設定好些吧
（上排太大了會使人眼花的，太小了看不淸）。
2、輸入欄的編碼字母大小，可在系統設置自定義好些吧
（類鍵盤字號、候選字號的設置）。

**Comment by zaqzrh** [comment]
該功能已完成
