### ISSUE TITLE
開發計劃

### ISSUE THREAD

**Issue by osfans** [osfans/trime#70]
开发计划：
- [ ]  #12 双击 （主要是shift键）  
- [ ]  #37 长按按键更多符号（a→ā á ǎ à A @）
- [ ]  #65 双拼、三拼键盘
- [x]  #32 编辑面板（↑↓←→选择……）
- [x]  #32 可触摸的按键间隙  
- [ ]  #26 可自由定义的状态栏  
- [ ]  #62 可翻页的符号面板
- [ ]  #45 可展开的候选列表
- [ ]  #23 单手模式 & 横屏布局  
- [x]  #31 并击
- [ ]  长按候选（删词……）  
- [ ]  在线下载方案
- [ ]  语音输入界面 
- [ ]  图形配置界面 

需要第三方：
- [ ]  云词库  
- [ ]  手写键盘 & 全键盘手写 

需要librime支持：
- [ ]  联想 
- [ ]  九宫格
- [ ]  邻键纠错  
- [ ]  笔划筛选

**Comment by osfans** [comment]
果然會出現進度條

**Comment by zaqzrh** [comment]
目前Trime的“按键设置”能细化到“不同键盘的每一个键”的好像有按键的“尺寸”“标签”“文本”“功能键”等。而字体类型、字体大小、颜色等好像还是“通用设置”。如按键“g”不能独立设为“黑体，22号，绿色”贴吧也有例子图。

**Comment by boboIqiqi** [comment]
## 从产品角度看开发计划

现在不是都流行"敏捷开发"吗？

[敏捷开发之Scrum扫盲篇](http://www.cnblogs.com/taven/archive/2010/10/17/1853386.html)

> 经常性的交付可以工作的软件，交付的间隔可以从几周到几个月，交付的时间间隔越短越好。
> 然后根据客户的反馈，进行下一次迭代。

所以，我们要尽快的发布一个能用的产品。
发布一个能用的产品的好处是：
- 用得人多了，反馈就多，我们会更有目标，更有动力
- 用得人多了，加入我们的人也会更多，贡献的代码和资源会更多

如果要尽快交付一个产品，我觉得我们当前最主要的任务按顺序是：

### 图形化配置界面

参照当前主流的手机输入法界面，做一个常用选项的图形化配置界面。

#### 为什么需要图形化配置界面

我们的产品的核心优势就在于，拥有无限的定制可能。
但是目前的情况是，用户找不到。打个比方，
就像我们拥有一个品类繁多的商品仓库，我们也挂出招牌想要出售。但是，我们没有柜台展示，门也锁着，用户只能通过窗户看一下。
用户说，你们要有什么就好了。我们说，我们有呀，给你钥匙，你打开，往哪里找，就能拿出来。
高级用户能找出来，但是更多的用户根本就找不到。门槛还是挺高的，先学rime配置，yaml多次尝试才可以。
而且还有更多的用户根本就不会问，下一来一看，没有特色，而且基本功能都不全，常用的选项都找不到，觉得就是一个测试产品，然后就删了。

和小狼毫不一样的是，小狼毫在电脑上，可以直接修改，保存，部署。
我们的输入法在手机，你想让用户修改一下配置，用户还得连到手机上。还得来回拷贝文件。
好多用户拷文件都用手机管家，估计都找不到rime目录在哪。

**总之，没有它，我们会失去99%的潜在用户**

另位，大家可以讨论一下我们目标人群：
方言和喜欢折腾的极客
但是，我觉得如果只针对这些人的话，我们的项目肯定也做不大。
而且即使是喜欢折腾的极客，他们也希望首先有一个可以完成基本功能的输入法，和一些他们可以快速试用到的选项。
这样更能保证他们不被别的也能折腾的玩意吸引，而是加入我们，折腾我们的输入法。

#### 配置中需要包含哪些内容

> 把四大主流输入法下下来，各个选项点一点，主流的功能你就都知道了。

这是我问我弟，想要什么功能的时候，我弟说的。

首先，要在配置界面中包含主流输入法常用的功能选项。
现在主流输入法的配置界面都很相似，这差不多已经成为一个业界标准。你可以看看，搜狗，百度，触宝，讯飞还有华为、小米自带的输入法的配置界面。我们照这个做，用户也会比较习惯，会省去很多学习代价。

然后，就是我们的特色了，在图形化界面上，加一些我们输入法的独有的，方便配置的选项。就可以看出我们的特色了。能让用户以最小的代价感受到，我们输入法的优势。（这样，我们就相当于有了一个柜台）

将第二部分的功能能达到10项，我觉得就是一个巨大的优势了。

### 九宫格输入

用九宫格的人有多少
我参照我身边的人有限的样本数量，偏高校学生，或者计算机行业的人比较多。
大概人数：20人
拼音：18 (我用五笔，我爸用手写)
九宫格：15左右

九宫格达到3/4, 而且因为我身边都是接触电脑比较多，对全键盘的指法比较熟，如果全国看，用九宫格的人数应该会更多。

网上给的数据是

> 2014Q3，中国手机网民手机输入方式的选择上，拼音输入(九宫格)和拼音输入(全键盘)分别占比46.7%和29.8%。选择五笔输入和手写输入的手机网民占比较少，分别为3.1%、12.5%。 

[2014我国手机输入法数据排行分析](http://www.chinabgao.com/stat/stats/40652.html)

**没有九宫格，我们要失去至少50%的潜在用户。按照我的统计是75%**

### 发布

如果能实现上面两项功能，我们就应该到国内主流的各大应用商店发布。
发布太重要了，而且我们以后就可以在线升级，不断维护。

关于在线下载方案，我觉得当前并不最最主要的，因为你把所有的方案文件都打包到apk中，也不会超20M。现在我下个触宝，都直接40M了。

**Comment by boboIqiqi** [comment]
另外，关于产品设计，可以推荐两本书。上次跟老大也说了：
[重来](https://book.douban.com/subject/5320866/)
[简约至上](https://book.douban.com/subject/5394309)

我觉得对做我们的产品会有帮助.
第一本书讲如何创业。主要就是说专注某个特定的用户群，要尽快把产品上线。从创业者角度讲做好一个产品。
第二本书主要就是讲如何设计，他把用户分成专家型用户和普通用户。专家用户想法特别多，希望能造一个会飞的汽车，就是希望酷，专业，他们不计成本，不计代价。但是大多数用户都是普通用户，他们只希望尽量少的代价，满足他们的需要。
每个产品的主要的服务对象，都是普通用户。（相对于普通输入法，我们的用户要专业一些，但是他们大多数也是想满足他们的需要，从这个角度讲，他们也是普通用户）

@xiaoqun2016 小群老师，你怎么看呀

**Comment by xiaoqun2016** [comment]
先引用佛振在wiki上写的：  

> ## Rime 輸入方案
> 
> 作者的一點主張：選用適合自己的輸入法。
> 　
> 來折騰 Rime 的同學，我只能說，您對輸入法的追求比較與衆不同啦！
> 　
> 當然，因爲您理想中的輸入方式千奇百怪、也許從沒有人那樣玩過，所以不可能在那種勾勾選選的介面上做得出來；需要親手來創作——Rime 輸入方案！
> 　
> 
> ### Rime 是啥
> 
> 　
> Rime 不是一種輸入法。是從各種常見鍵盤輸入法中提煉出來的抽象的輸入算法框架。因爲 Rime 涵蓋了大多數輸入法的「共性」，所以在不同的設定下，Rime 可化身爲不同的輸入法用來打字。
> 　
> 
> ### 爲啥這麼繁？
> 
> 　
> 一鍵就搞掂，必然選項少，功能單一。不好玩。
> 　
> 輸入法程序一寫兩三年，也許還不夠火候；花兩三個小時來讀入門書，已是輸入法專業速成班。

rime是输入算法框架，专注于输入技术的研究，这可能是佛振最初给自己的定位吧。  
rime的目标用户是分层次的，有技术基础的用户可以深入定制输入方案，再将配置好的方案分享给普通用户使用。我最初也是用路人做的「不知郑码」方案，从普通用户慢慢过渡到可以自己定制。  

同文如果真的要推广，是不是可以先把预置的布局和配色做得更精致点，让普通用户拿过来就可以用，都不需要定制。就像谷歌拼音的安卓版，只有简简单单的两个皮肤，都没法修改，但是在play商店仍然有5000万的下载量，远远超过搜狗百度。（会去play商店的人也是有点与众不同啦，这仅代表某类用户的选择）     

如果你对rime的复杂程度有点了解，应该会知道要想把rime的配置全部图形化显然是不可能做到的，但是简单的常用的选项可以先试做看看。  
 既然是使用了rime的内核，我们还是先把跟输入相关的功能做好吧。

**Comment by boboIqiqi** [comment]
我觉得根本不是布局和配色的问题，而是使用习惯的问题。我们的复制粘贴不太好找(输入按键上放操作，刚开始确实不习惯)，表情面板也找不到。我用过百度和触宝，他们的配置界面特别像，搜狗也差不多。

而且从技术上讲，图形配置界面与文本配置并不冲突。图形配置只实现常用功能，最终也会生成yaml 文件。所以，不需要提供所有的配置项。就像winrar其实配置项也特别多，如果你用命令行模式，你就可以用参数实现更细致的定制。但是它也有图形界面，图形界面只提供最常用的选项，也是我们常用的。

电脑上转小狼毫的转变不大，因为都是统一的键盘和按键功能，只有输入模式的细微差异。手机上就不一样了吧

**Comment by osfans** [comment]
大家都很專業，都很有想法啊，哈哈。

目前圖形界面有的是我覺得常用的：
- [x] 方案列表
- [x] 配色列表

還缺哪些？可以幫忙補上：
- [ ] 按鍵聲音
- [ ] 按鍵震動
- [ ] 按鍵彈窗

置於自定義鍵盤佈局、配色之類的，好像比較複雜。可以另外搞個類似於百度輸入法皮膚的PC端工具。
九宮格要librime支持，不然糾錯、篩選的功能還是沒有，還是沒法用。

@boboIqiqi 你可以直接提交，用戶最需要的，你覺得最重要的。
@xiaoqun2016 预置的布局和配色，你覺得哪些要改的，可以直接改啊。美工這方面，我還真不會。
我是把我覺得我能做出來的、容易做的放在最前面。

人多了，大家就可以分分工了，哈哈。

**Comment by xiaoqun2016** [comment]
如果让我来做布局配色，绝对会让人骂的。  
我喜欢谷歌式的简洁。 
我对同文的要求很低，去年十月份的版本就够用了。  
很奇葩吧？所以不要相信我说的。

**Comment by osfans** [comment]
我要求也低，覺得夠用了，哈哈。所以進度才慢吧。

**Comment by boboIqiqi** [comment]
老大，我是想照着主流输入法的界面设计，它们好像现在都特别统一，风格很类似，我现在截不了图，你们可以比较一下触宝和百度。都是候选框，有个配置面板，有一些常用的配置项，我就先照触宝的配置风格实现吧，就是把候选框做得强大一点。
你觉得呢？
小群老师，你是最专业的。
您要是有空，能多发一些关于rime 和trime 的博客和配置案例，专题教程什么的，必定有更多的人拜入您的门下

**Comment by osfans** [comment]
候選框的配置面板是要做的，就是可自定義的狀態欄。目前都是用的rime的switches，也準備先在這裏加。

**Comment by boboIqiqi** [comment]
再说一下我的思路有没有问题
我觉得配置界面的用户主要分为3类
- 普通使用者 这个要实现其他输入法的基本功能, 而且刚刚配置上不需要部署.这个就在候选框在设置面板里面设置 
- 布局和配色的创作者 这个可以坐在PC上，也可以做成在线版的。像我们发布markdown回复，写完代码，可以预览一下。我们甚至可以用JavaScript 做一些交互，播放按键位置，选中按键，更改大小和颜色背景
- 输入方案的创作者 这个我估计比较难做图形化配置界面。小狼号上有一个c #写的工具，我还没看。
  
  对于普通用户来说需要更改布局配色, 只要下载预览别人配置好的方案 。可能需要局部微调，我们可以进入编辑模式，长按某个键，对该键的大小和按键内容作微调。但是这个当前也不是最着急的。

其实我觉得就是把用户从别的输入法更换到我们的时候，使用习惯更改代价最小，在到基础上再做进一步定制。主流的输入法经过专业的设计和测试，又被这么多人使用一定有其合理科学的一面，不管是使用方式，还是配界界面。我们做要实现它，然后再提供局部微调和定制

**Comment by boboIqiqi** [comment]
反正第一类用户的配置界面是最需要和最重要的。
就是修改完不用重新布署，

**Comment by osfans** [comment]
同意，不過這方面我不太熟，你幫忙先加啊。包括單手模式也是。
確實不用重新部署，只有輸入法方案相關的纔要部署。

**Comment by frank-king** [comment]
鄰鍵糾錯這個功能，急需啊！不然打字很慢……
我也好想參與開發這個，祇不過我現在是小白，正糾結於如何使用Android Studio中。

**Comment by DaengGWokFook** [comment]
@whjpji 鄰鍵糾錯可以在方案裏增加模糊音實現，但是重碼率會增加，打字速度可能會降低。

**Comment by osfans** [comment]
同意樓上

**Comment by frank-king** [comment]
@DaengGWokFook
我所說的鄰鍵糾錯，是僅當按鍵偏離目標鍵中心或介於某兩鍵之間時才糾錯的，不是模糊音。
比如當我按「G」鍵時，若按偏了，按到「F」與「G」鍵之間時，在候選欄就按偏離程度將「F」「G」鍵的候選字按一定優先級都列出來（按鍵位置更偏向「F」則F在前，否則「G」在前）。多於兩鍵時同理。
由於我用蒼頡輸入法，錯碼不像拼音那樣很容易被識別出來（比如拼音「hang」，若按鍵稍偏，按成了「hanf」，通過正則表達式應該很容易識別出這是一個錯誤的編碼，糾正起來也相對容易），而蒼頡碼差之毫釐，失之千里，編碼一錯，很容易讓人不知所云。因此我急需這個功能。
在我以前用的「輕鬆倉頡輸入法」中是有鄰鍵糾錯的功能的，憑着對rime電腦輸入法的好感換成了trime之後，才發現沒有這個功能有時打一個會半天打不出來，於是愈來愈急，愈急愈亂。

我不太清楚librime的運作機制，感覺好像祇需要在按鍵之後判斷一下查詢多次編碼再整合一下就可以了？也許不一定像我說的這麼簡單吧，不然各位大神肯定早就實現了。
最近在學android開發，待我學成了，再來好好研究一下。

**Comment by beversmith** [comment]
九宫格，我爱你

**Comment by Endif12** [comment]
请问现在有九宫格了吗

**Comment by GoGoogle** [comment]
没九宫格好难受

**Comment by Endif12** [comment]
现在我找到一些九宫格方案，但是还是不太好用，我用的是全拼，主要是不能从第一个拼音开始自己选，希望大神可以按市面上主流的全拼输入法九宫格方式配置一个方案，那就是造福于大众了呀

**Comment by ivysrono** [comment]
九宫格+1

**Comment by xiaozuyu2014** [comment]
九宫格+1亿

**Comment by Bambooin** [comment]
九宫格已经有群友实现 #337

@xiaozuyu2014 @ivysrono @GoGoogle

**Comment by GoGoogle** [comment]
> 九宫格已经有群友实现 #337
> 
> @xiaozuyu2014 @ivysrono @GoGoogle

#337 不是九宫格吧？

**Comment by Bambooin** [comment]
@GoGoogle 笔误输入错误
#377

**Comment by GoGoogle** [comment]
> @GoGoogle 笔误输入错误
> #377

用过，不过这个按键需要调教，太小了。
