### ISSUE TITLE
fooview搜索框输入时, 键盘面板会把浮动候选框挡住

### ISSUE THREAD

**Issue by hxse** [osfans/trime#701]
1. trime.yaml, 添加下面字段
      layout:
        position: fixed
        spaceing: -40
2. 打开fooview悬浮球, 用里面的内置浏览器搜索, 会发现悬浮候选框消失了, 被隐藏到面板后面去了, 虽然还能打出字, 但是看不见候选框了
3. 只在fooview里发现这个情况, 其他app表现都正常

**Comment by WhiredPlanck** [comment]
@hxse 已解决，请下载最新版。
