### ISSUE TITLE
更改方案不生效

### ISSUE THREAD

**Issue by Kinboise** [osfans/trime#706]
**描述问题**
在设置中修改要启用的方案后不生效。部署、强制停止都无效。去`rime/default.custom.yaml`里看已经变过来了，但实际方案选单里还是原来那些。

**设备信息**
 - Device: realme GT Neo 闪速版
 - OS: Android 11
 - Version: 3.2.5
 - Theme: 默认

**Comment by InfinityLoop1309** [comment]
Check your version code. Trime would not make any change if a theme/dict/schema has a version code same to before.

**Comment by Bambooin** [comment]
Please verify in the latest build.
