### ISSUE TITLE
想要有打注音文、顏文字的方案

### ISSUE THREAD

**Issue by xillinnq** [osfans/trime#707]
在台灣，大家很喜歡打注音符號，因為有種親切感，用了同文之後，很喜歡同文的鍵盤快捷性，而且可以自定義鍵盤字體大小等等，還可以安裝行列，讓我很快樂！

但最近因為使用了同文，不能打顏文字跟注音符號，感覺跟朋友溝通上變得比較不親密，好像很嚴肅嗚嗚

希望可以有打注音符號的方案🙌🙌
在Gboard的話是注音鍵盤上長按會有注音文（很好用）
在行列則是要w8之後一個個選（太麻煩）
希望有機會可以整合🥲🥲

喜歡打注音文ㄉ大家也可以來留言，見識一下注音文ㄉ偉大（？

**Comment by Bambooin** [comment]
As for `注音`， you can try https://github.com/rime/rime-bopomofo

As for `颜文字`，you can try `主题`-> `颜文` in the `Tongwenfeng` theme.

Hack the Rime.

**Comment by xillinnq** [comment]
@Bambooin 

感謝回覆💞
我的意思比較是打出「純注音」而不是用注音打字🤣

另外我不太懂下方回應的意思，我這邊的主題沒有顏文字

**Comment by Bambooin** [comment]
`颜文字` is in `同文风` theme, you should enable it.

**Comment by xillinnq** [comment]
okay, i found it just now!:)

But, i use array30 keyboard, i can't use tongwenfeng to type.

in the other side ,i can't change the code of  tongwenfeng, because i dont know what's the file i can use.

I want to change the board to traditional Chinese. I am used to reading traditional Chinese. 

thank youn for replying me immediately👍

**Comment by Bambooin** [comment]
The theme file is `tongwenfeng.trime.yaml`, you can change it for your appetite.

It's just theme file, so you can use it for any thing including traditional input.

**Comment by lunarythia** [comment]
@xillinnq This is an old issue, but you can follow the suggestion here to add array to the theme file.  https://github.com/rime/rime-array/pull/12#issuecomment-2268511886
