### ISSUE TITLE
在知乎上编辑回答或文章时, 行首输入时不应上屏却自动上屏

### ISSUE THREAD

**Issue by jacobax** [osfans/trime#710]
**Describe the bug**
比如新起一行, 原本要输入`测试`两字, 小鹤双拼输入编码是`ce ui`, 当输入`c`时, `才`字出现在第一候选位, 继续完成输入, 当输入到`e`码时, `才`字已经自动上屏, 候选栏为正常继续输入状态
目前只发现在知乎编辑回答或文章行首输入时有此现象，输入方案中并未设置自动上屏

**To Reproduce**
Steps to reproduce the bug:
1. 打开知乎编辑文章或回答
2. 任一行行首输入编码
3. 不应上屏却自动上屏

![Screenshot_2022-04-12-10-21-26-622_com.zhihu.android.jpg](https://user-images.githubusercontent.com/23228895/162866658-affe9d0e-dc8b-432e-b895-1423f4d7fff1.jpg)
**Smartphone (please complete the following information):**
 - Device: redmi note10
 - OS: Android 12
 - Version: 3.2.5
 - Theme: default、同文风增强版
 - schema: 小鹤双拼、朙月拼音、小鹤音形
 - zhihu: 8.9.0

**Comment by tumuyan** [comment]
关闭嵌入应该可以解决问题

**Comment by jacobax** [comment]
> 关闭嵌入应该可以解决问题

关闭确实可以
就是比较奇怪, 目前只在知乎发现这现象
不知道能不能在嵌入开启情况下解决

**Comment by tumuyan** [comment]
类似的问题讨论过多次了，目前的解决办法就是嵌入。

参考
https://github.com/osfans/trime/issues/129
https://github.com/osfans/trime/issues/456
