### ISSUE TITLE
关于user目录和share目录的讨论

### ISSUE THREAD

**Issue by tumuyan** [osfans/trime#712]
### 现状
目前同文可以设置两个配置路径： user目录 和 share目录。
其中share目录放置了 从assets目录中释放的openCC，tongwenfeng和default两个主题。

### 存在的问题
1. 在打开App后，同文会从share目录部署两个主题到build目录，实测耗时2秒。这是唤起键盘慢的原因之一。当然，并非每个人都会遇到这个问题——当user目录和share目录相同时，这个部署过程是跳过的。
2. 切换主题时，如果user目录没有同文风主题，即使build目录内存在同文风的build结果，但是是不会显示在主题选择列表里的

### 处理方式
1. 把释放主题文件的路径，从共用目录改为user目录，所有的主题操作均在user目录中。从而免除了打开App时，从share目录build的时间浪费
2. 或者直接取消share目录

**Comment by WhiredPlanck** [comment]
Focus on #1186
