### ISSUE TITLE
是不是应该先把trime的域名占了？

### ISSUE THREAD

**Issue by boboIqiqi** [osfans/trime#72]
https://sg.godaddy.com/zh/domains/searchresults.aspx?checkAvail=1&domainToCheck=boboIqiqi

到网上搜了一下，这个域名。
trime.com已经被占了
不过还有些别的　trime.co
一年只要17刀

小狼毫有域名吗？
要不帮它也申一个，
rime.sg　，一年只要$9.99
https://sg.godaddy.com/zh/domains/searchresults.aspx?checkAvail=1&domainToCheck=boboIqiqi

如果老大觉得需要，　我愿意免费捐赠，　先占下来再说，以后慢慢维护
大家觉得呢？

**Comment by osfans** [comment]
小狼毫是rime.im 目前跟他共用的 已经在他的下载页面加上下载链接

**Comment by xiaoqun2016** [comment]
好像$25可以注册谷歌的开发账号，然后就可以在谷歌的 Play商店上架App了

**Comment by osfans** [comment]
谷歌上架有没有好处啊？我也不知道呢 只是大陆访问不方便

**Comment by xiaoqun2016** [comment]
谷歌面对的是全球用户，有些国内软件的流氓功能都不太敢在国际版中使用，而且，谷歌的审核好像也挺严格的，所以谷歌商店的App质量会比国内商店的高一点，比如UC浏览器国际版。应该有一部分人会像我这样翻墙去谷歌商店下载应用吧。

**Comment by Prcuvu** [comment]
在Play上上架有“官方认可”的意味，在宣传上有好处。而且方便Play强迫症用户。

**Comment by xiaoqun2016** [comment]
Trime跟Rime是一家。
