### ISSUE TITLE
3.2.5版本状态栏变黑、部署失效

### ISSUE THREAD

**Issue by Matthew-Harris-36** [osfans/trime#726]
一加7T，Coloros12.1，安卓12，同文输入法3.2.5
1、使用默认主题，长按左下角中文按钮，打开选单，在弹出的窗口，点击“方案”，就会导致状态栏变黑，更新主题和配色也无法修复。并且会覆盖掉共享文件夹的default.custom.yaml文件。
2、上面问题通过清除存储资料恢复后，点击部署，虽然显示部署成功，但方案仍为默认的繁体注音正体。从方案里选择五笔86，确认后，键盘仍未改变过来，只能多次点击，后台放一段时间，它自己才会转变。

**Comment by Bambooin** [comment]
Please verify in latest build.
