### ISSUE TITLE
color_schemas 自定义颜色字段无法使用颜色名

### ISSUE THREAD

**Issue by nopdan** [osfans/trime#730]
color_schemas 里 `menu_back_color: white`，键盘里 `key_back_color: menu_back_color`，不生效。
改为 `menu_back_color: 0xffffff` 正常。

**Comment by nopdan** [comment]
> color_schemas 里 `menu_back_color: white`，键盘里 `key_back_color: menu_back_color`，不生效。 改为 `menu_back_color: 0xffffff` 正常。

经过测试 0x55 这种格式也会出错

**Comment by cxcn** [comment]
> > color_schemas 里 `menu_back_color: white`，键盘里 `key_back_color: menu_back_color`，不生效。 改为 `menu_back_color: 0xffffff` 正常。
> 
> 经过测试 0x55 这种格式也会出错

实测 0x55 这种已经失效了，默认的颜色定义也不能使用，现在有问题就是颜色名了。
