### ISSUE TITLE
_hide_comment 失效

### ISSUE THREAD

**Issue by nopdan** [osfans/trime#735]
3.2.6-5-20220425，没有效果

**Comment by BAIHUAN1001** [comment]
_hide_key_hint 失效
3.2.6-20220605 没有效果
或者是我不会配置？请帮助我

**Comment by nopdan** [comment]
现在 _hide_comment 好了， _hide_candidate 又坏了

**Comment by WhiredPlanck** [comment]
请看新版本有无此问题。Please take a look for new version.
每夜版/Nigntly Build：https://github.com/osfans/trime/releases/tag/nightly
