### ISSUE TITLE
Add a button to clear trime clipboard.

### ISSUE THREAD

**Issue by reiuyfan** [osfans/trime#739]
**Is your feature request related to a problem? Please describe.**

The clipboard that cannot be emptied is confusing and annoying.

**Describe the solution you'd like**

As far as I know, trime stores the clipboard data in the clipboard.db in the application directory, just delete it to clear the clipboard, so I would like to add a button to delete this file.

**Describe alternatives you've considered**

No fit.

**Additional context**

No fit.

**Comment by InfinityLoop1308** [comment]
The title sounds misleading, since the system clipboard will not be cleaned using your method. You may specify the title to the trime clipboard.

**Comment by Bambooin** [comment]
Add in #863
