### ISSUE TITLE
自定義鍵盤按鍵高度

### ISSUE THREAD

**Issue by DaengGWokFook** [osfans/trime#74]
寬度已經能調，求高度

**Comment by osfans** [comment]
目前是統一的高度：`key_height: 44 #鍵高`
https://github.com/osfans/trime/blob/develop/assets/rime/trime.yaml#L28

**Comment by DaengGWokFook** [comment]
有些鍵經常按，想把它放大，獨立加寬和加高

**Comment by osfans** [comment]
目前一行内每个高度是一样的。需要各行高度不同？

**Comment by DaengGWokFook** [comment]
對，若與上行或下行重疊則設定間隔

**Comment by osfans** [comment]
1c5379eadd87b43b45f74ce4bc8f68a03787074b 解決了此問題，設定某一行的第一個按鍵的高度height即可。
