### ISSUE TITLE
关于wiki的维护

### ISSUE THREAD

**Issue by boboIqiqi** [osfans/trime#75]
# @xiaoqun2016 ,老师，我在wiki上写了一点今天新学的知识。

好多我怕我理解会有偏差，整理出来，也是自己的梳理，请大家检查。

以前看过一本书，叫《如何阅读代码》，说，要主动积极的去验证自己的理解。方法有二
1.　尝试修改完善代码，跑起来看看效果
2.　尝试修改完善文档，问问别人对不对

其实我还想整理很多知识（主要是我现在不会，不想好不容易找到，过一段时间又忘记了）比如
- vim+小狼毫的全配置:　就是ESC自动切英文，还有半角全角的配置
- 小狼毫五笔的配置

虽然，这些网上也有一些说明，但都比较零散，问到别人又不好意思。
我想把我查到的都整理在一起。或者可能有些别人已经整理好了我还没有找到。信息来源主要是小狼毫网站，然后它的wiki和贴吧搜索
还有我配置五笔双键中学习到的知识。比如，我差不多算是理解了键盘布局是怎么样切换的了，yaml数据的格式，序列下标的引用，映射的几种表示方法

欢迎大家批评。路漫漫其修远兮，要学的东西太多了，还没有帮老大写过一行代码

另外，我发现wiki上的markdown与github flavor markdown不一样，比如 
- GFM需要##后面加一个空格，然后才能被认为是标题。而wiki上面不用。
- wiki上面不能直接换行，需要两个换行，才会被解释为一个换行。或者在行末尾加两个空格(经典markdown风格)
- wiki上面不支持用tab开头，来输入代码
- wiki上添加列表-之前要有一个空行，否则会合并到上一行，无法显示列表

**Comment by boboIqiqi** [comment]
刚开始不会用预览，一直在重新编辑，这样没有问题吧。以后保证不会了

**Comment by xiaoqun2016** [comment]
看到了，忍不住再加32个赞👍

**Comment by zaqzrh** [comment]
@boboIqiqi 
trimer小知识(1) Yaml文件开头注释是什么意思？
trimer小知识(2) 配置文件中的一些yaml语法
为什么“trimer”要加个“r”呢？

**Comment by boboIqiqi** [comment]
@zaqzrh 表示人的意思呀，同文爱好者必备的小知识
@xiaoqun2016 老师向您看齐

**Comment by xiaoqun2016** [comment]
vim+rime，在用esc退出插入模式的时候使rime进入西文模式，试了同文可以做到。 只需`accept: Release+Escape, toggle: ascii_mode, when: always`，key_binder的位置可以不用调。  
github上的markdown确实不大一样，比如我想用`[TOC]`生成目录，但是不支持。  
😊 😊

**Comment by boboIqiqi** [comment]
@xiaoqun2016 好的，那我知道了，我们以后不要叫中文名了好不好。感觉我被人肉了。

**Comment by xiaoqun2016** [comment]
@boboIqiqi  从你的email猜的，没有人肉

**Comment by boboIqiqi** [comment]
@xiaoqun2016 我写了一个简单的资料汇总，请大家帮忙修改完善

**Comment by xiaoqun2016** [comment]
@boboIqiqi 写得很好 👍

**Comment by boboIqiqi** [comment]
Xiaoqun老师起的好早啊，早睡早起好习惯。
你帮我看看还有些别的吧，想贴吧的好贴，还有你说的速成方案有文档吗？还是要看他的yaml文件

**Comment by boboIqiqi** [comment]
还有论坛，rime的网站没列上去。
我现在在有Google拼音，我们的界面原来是模仿它的？候选框里只有语言切换。但是人家也有隐藏键盘按钮。另外，大家的长按按键提示都在按键的下方，我们的在上方。

**Comment by xiaoqun2016** [comment]
@boboIqiqi 速成没有文档。东风破里面的每个方案都有特色，都可以看成是一篇定制教程。 你看过rime的wiki，有了基础，现在应该只要看yaml就可以了解其中的原理了。  
如果我没记错的话，谷歌拼音曾经取消过隐藏按钮。无奈的是普通用户并不理解谷歌的用心。所以它在是否坚持自己的设计理念上也是做过挣扎的，但并没有完全妥协。也许吧

**Comment by xiaoqun2016** [comment]
- Wiki尽量统一风格，比如简繁体的使用。（我虽然平时用的是简体，但写Wiki时都会转成繁体，因为先前Rime和Trime已有的页面都是用繁体的。）  
- 及时更新知识，以免误导别人。
