### ISSUE TITLE
斜杠加字母输入符号功能失效

### ISSUE THREAD

**Issue by arockshan** [osfans/trime#750]
之前好像（不太记得清了）一直用的 *realese3.13* 下的测试版，只要使用 **斜杠+字母** 的方式便可候选对应字符，如 `/xl`候选希腊字母，如`/jt`对应各种箭头的候选。 
近日重新安装了比较近的版本，发现这一功能失效了。于是今天重新把从 *release3.13* 至 *release3.26* 都安装了一遍，发现都存在这个问题。
不知道是不是我的手机的原因，还是软件本身的问题。

**Comment by Bambooin** [comment]
I can't reproduce in latest daily build..

It works for me, `Tongwenfen` theme and in Chinese mode, input `/xl` will get the result.

**Comment by arockshan** [comment]
抱歉，浪费大佬的时间了。现在可以确定这个问题只与我经常使用的输入方案有关系，在 `trime` 里切换到别的输入方案，没有上述问题。

**Comment by arockshan** [comment]
定位到问题了。既不是软件的问题，也不是输入方案的问题，而是我手机 rime 文件夹下的  `symbols.yaml` 文件版本太旧了（`config_version: '1.0'`），替换为 1.3 的版本，问题就解决了。相对于1.3的版本，1.0的版本少了两行代码：
```
  punctuator/import_preset: symbols
  recognizer/patterns/punct: '^/([0-9]0?|[A-Za-z]+)$'
```
