### ISSUE TITLE
Support deleteCandiate on long click candidate

### ISSUE THREAD

**Issue by InfinityLoop1308** [osfans/trime#769]
**Is your feature request related to a problem? Please describe.**

The existed DeleteSelection method need too many steps to finish when the selected candidate is not the first. It also needs 3 additional key bindings to finish the deletion, which is costly on those keyboards with fewer keys.(e.g. jiugong keyboard).

**Describe the solution you'd like**

Long click the candidate to delete a user-created word.

**Describe alternatives you've considered**

**Additional context**

**Comment by InfinityLoop1308** [comment]
I have already made a draft,  but it requires a change in librime and can not directly commited to this repo.

**Comment by tumuyan** [comment]
1. 这个功能至少需要一个开关来直接关闭。
2. 我觉得实现的并不好，我们可以把点击候选拆分为选择一个候选，然后做下一步的动作——模拟空格commit（普通点击），或者模拟Ctrl+k删除候选（触发长按，甚至是上下滑），或者取消（触发候选栏内容的移动）。
3. 我个人觉得长按单独触发高亮候选的变化是合适的，直接删除候选不太合适。

**Comment by InfinityLoop1308** [comment]
> 1. 这个功能至少需要一个开关来直接关闭。

Will be added in next commit,

>     2. 我觉得实现的并不好，我们可以把点击候选拆分为选择一个候选，然后做下一步的动作——模拟空格commit（普通点击），或者模拟Ctrl+k删除候选（触发长按，甚至是下滑），或者取消（触发滑动）。

I don't really get your point. In this pr, the 'Simple Click' and "delete candidate" are both implemented. Do you mean adding a swipe gesture to cancel the selection?

**Comment by InfinityLoop1308** [comment]
>     3. 我个人觉得长按单独触发高亮候选的变化是合适的，直接删除候选不太合适。

I guess you are assuming Trime is running without `Click Candidate` option. I think this feature should be confined to use with `Click Candidate`, since those schemas without this option are very likely to have other deleting methods.

**Comment by tumuyan** [comment]
> > 1. 这个功能至少需要一个开关来直接关闭。
> 
> Will be added in next commit,
> 
> > ```
> > 2. 我觉得实现的并不好，我们可以把点击候选拆分为选择一个候选，然后做下一步的动作——模拟空格commit（普通点击），或者模拟Ctrl+k删除候选（触发长按，甚至是下滑），或者取消（触发滑动）。
> > ```
> 
> I don't really get your point. In this pr, the 'Simple Click' and "delete candidate" are both implemented. Do you mean adding a swipe gesture to cancel the selection?

yes, maybe swipe is better than long press for delete candidate . but it should be selected by user.

To delete a candidate now use the up and down keys to change the highlighted candidate, then Ctrl+k to complete the deletion.
I think it would be appropriate for the touch event to simulate this process , it could avoid to modify librime

**Comment by InfinityLoop1308** [comment]
> To delete a candidate now use the up and down keys to change the highlighted candidate, then Ctrl+k to complete the deletion. I think it would be appropriate for the touch event to simulate this process

As I mentioned, using 3 keys is too costly and not acceptable in JiuGong themes.

> , it could avoid to modify librime

This is not an issue now since my PR to `librime` is already merged.

**Comment by tumuyan** [comment]
> As I mentioned, using 3 keys is too costly and not acceptable in JiuGong themes.

Not use 3 keys, but send event just like send keys. Not send number keys, like `select_candidate(index) `  and send `Ctrl+k`



> This is not an issue now since my PR to is already merged.`librime`

So that‘s ok

**Comment by InfinityLoop1308** [comment]
> Not use 3 keys, but send event just like send keys. Not send number keys, like `select_candidate(index) ` and send `Ctrl+k`


I don't think there is a way to do it in JiuGong as it is in severe short of keys,  but anyway it seems we can just ignore this topic as this feature should be confined to used with `Click Candidate` in  my opinion. Traditional schema would not be affected by this change and could stay the same as brefore.
