### ISSUE TITLE
project build error

### ISSUE THREAD

**Issue by jarry622** [osfans/trime#770]
In file included from librime/proto/rime_proto.capnp.c++:4:
  librime/proto/rime_proto.capnp.h:10:2: error: "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
  #error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
   ^
  1 error generated.

**Comment by Bambooin** [comment]
Please keep your local `capnp` same of source code with `0.10.1`.
