### ISSUE TITLE
Mac android studio build error

### ISSUE THREAD

**Issue by jarry622** [osfans/trime#772]
C/C++: /Users/xxx/Workspace/trime/app/src/main/jni/CMakeLists.txt debug|armeabi-v7a : CMake Error at /Users/xxx/Workspace/trime/app/src/main/jni/boost/libs/log/CMakeLists.txt:579 (add_library):
  Target "boost_log_setup" links to target "Boost::coroutine" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

**Comment by InfinityLoop1308** [comment]
try https://github.com/tumuyan/trime-without-CMake

**Comment by WhiredPlanck** [comment]
Remove the `build` and `.cxx` directory under the `app` and try again.
