### ISSUE TITLE
关于选择朙月拼音简体字后为什么还会出现有些字打出来是繁体的问题

### ISSUE THREAD

**Issue by hong26** [osfans/trime#773]
关于选择朙月拼音简体字后为什么还会出现有些字打出来是繁体字的问题，这个问题应该怎么解决呢？

**Comment by WhiredPlanck** [comment]
明月拼音等来自 Rime 官方的方案默认都是直出繁体字，简体字是由 OpenCC 转换而来的。所以你需要检查一下 OpenCC 滤镜是否故障了。

**Comment by hong26** [comment]
> 明月拼音等来自 Rime 官方的方案默认都是直出繁体字，简体字是由 OpenCC 转换而来的。所以你需要检查一下 OpenCC 滤镜是否故障了。

你好，那MIUI系统手机需要怎么处理呢？

**Comment by WhiredPlanck** [comment]
> 你好，那MIUI系统手机需要怎么处理呢？

这无关手机系统。尝试一下以下步骤：打开 app -> 输入配置 -> 恢复默认设置 -> 勾选“opencc”选项，然后点“确定”，直到提示“重置成功”。
