### ISSUE TITLE
Titan Pocket 不显示虚拟键盘无法显示候选区

### ISSUE THREAD

**Issue by gttnnn** [osfans/trime#777]
**Describe the bug**
Titan Pocket 切换显示虚拟键盘才能正常显示候选区

**To Reproduce**
Titan Pocket有实体键盘。
1、问题：定位到输入框，光标闪烁，从系统下拉菜单“选择输入法”，关闭“显示虚拟键盘”开关。没有弹出状态栏。打字时仅有悬浮窗，没有候选区，用数字键可以选到看不见的其他候选项。
2、找到一个权宜之计：从系统下拉菜单“选择输入法”，打开“显示虚拟键盘”开关。屏幕下方正常弹出状态栏和虚拟键盘。再从系统下拉菜单“选择输入法”，关闭“显示虚拟键盘”开关。此时没有状态栏，但开始输入就能正常弹出候选区（无虚拟键盘），候选区为空的时候状态栏也能正常显示。换个输入框又要重复一次打开再关闭“显示虚拟键盘”的操作才能不开虚拟键盘正常输入。在我的手机上可以稳定复现。

**Expected behavior**
定位到输入框，光标闪烁，开始输入弹出候选区。候选区为空的时候状态栏正常显示。

**Log**
无

**Screenshots**
![实体键盘](https://user-images.githubusercontent.com/763295/174506765-43eddd1e-c442-472f-99a2-3bc93ecb7980.jpg)
![无候选区](https://user-images.githubusercontent.com/763295/173985463-0e967c7f-0a4b-4f95-8d75-3d377eeec088.png)

**Smartphone (please complete the following information):**
 - Device: Unihertz Titan Pocket
 - OS: Android 11
 - Version: 3.1.3-20190930
 - Theme: 默认

**Additional context**
Titan pocket 屏幕分辨率为 716*720 ，有实体键盘。系统有“迷你模式”强制屏幕变成9:16 纵向格式，切换之后此问题依然出现，应该与屏幕长宽比例无关。

**Comment by dallaslu** [comment]
在最新版的 Trime 中，不显示虚拟键盘时，悬浮窗也是没有的。

不过，Trime 内置的迷你键盘非常适合 Pocket，可以设定其为接入物理键盘时自动启用。

建议通过配置文件进一步定制这个迷你键盘。比如，参考 kika，仅保留一排按键；调低按键高度；添加些 Pocket 键盘未提供的常用键位等。

![Screenshot_20220712-190237](https://user-images.githubusercontent.com/914202/178541233-bb3aa1ed-da9d-47c6-92b9-2f3dfcda9858.png)

悬浮窗和候选区是两个部分。默认配置中，五个字以上的内容才会出现在候选区。这些也可以配置。

或许不隐藏软键盘体验更好些。一切尽在  `trime.custom.yaml` 中，哈哈

**Comment by MikeyWei** [comment]
我 Titan Pocket 折腾了几次，使用自带的物理键盘输入法了。

**Comment by controlledentropy** [comment]
阿这，被大佬无视了么....
