### ISSUE TITLE
取消強制中文

### ISSUE THREAD

**Issue by DaengGWokFook** [osfans/trime#78]
在瀏覽器輸入網址時切換成西文，按瀏覽器X刪除文字後立即變回中文，很不方便。
原先是中文就中文，西文就西文，不要自動切換，手動切換比較好。

**Comment by boboIqiqi** [comment]
我试了一下，点击一下x键，是完成输入，键盘会隐藏是不是？
你需要的功能可以表达为，每次关闭输入法的时候，记录下当前的状态。如果在极短的时间内重新打开，就不要切换到主键盘，而是保存上次的状态。
另外的解决方案，或者你可以设置一个全选删除键，就不用点x，而是直接删除所有的输入。

还有就是小狼毫可以根据应用的名称设定输入模式，不知道手机上，可以实现不

**Comment by DaengGWokFook** [comment]
我想說輸入網址時地址欄最右方有X，按X即可一鍵清除地址欄所有字符（X是瀏覽器本身有的，不是同文鍵盤），就是按了X後自動變回中文模式，很不方便

**Comment by xiaoqun2016** [comment]
reset_ascii_mode: false  
更多功能请参考trime.yaml详解……

**Comment by boboIqiqi** [comment]
我的浏览器也有这个按键，我是火狐。你用的是什么浏览器呀？不知道咱俩的效果是否一样，在我的浏览器上点了这个键，会隐藏输入面板。重新开始浏览网页。我理解那个按键并不清除内容，重新输入，而是取消输入，离开地址栏的意思。你如果要删除所有的输入，你只要全选，然后按退格键就好。不要点那个x按键。你再试试可以不

**Comment by boboIqiqi** [comment]
原来有相关定义，我都不敢发了，我再帖一个问题。看看是什么原因。

在@xiaoqun2016 的帮助下，我的五笔双键已经可以使用了，现在同文也是我的主力输入法了。但是今天发现了一个后果挺严重的漏洞。我刚开始写了一段话，我想把它复制到另一个地方。我的主界面键盘没有全选。我切换到符号键盘，然后点击一下全选 全部选中。 但是符号界面又没有粘贴复制，我就又切换了一下键盘，然后我的东西就被全删了。这个应该是切换键盘的，bug ，切换时不应该删除选中的内容。而且即使要删除，也应该默认复制到剪切板。还有我们可以参考一下触宝输入法的界面，应该把全选复制粘贴等编辑功能，专门放到一个布局上，然后在候选框中有切换按钮。这些按键单独一两个，孤立的出现一个键盘上没有意义。

**Comment by boboIqiqi** [comment]
不过，你提的这个问题也确实是
我试了一下触宝输入法，它会记录下上次的输入状态，上次关闭前是英文，切换回来还是英文。我们是不是也应该这样。@osfans

**Comment by xiaoqun2016** [comment]
@boboIqiqi  你说的也是用这个`reset_ascii_mode: false` 控制。  

在安卓系统中，长按文本，会出现全选&复制&粘贴……的菜单，这是安卓的基础功能，不知道你有没有发现？  
安卓中，如果是英文文本，会自动选择整个单词。以前用过ios，它做得更好，甚至可以智能识别中文词组并选中，所以习惯了用系统自带的这个功能。

**Comment by osfans** [comment]
旧版的没有这个设置，然后默认就为true，就强制中文了。要不新加设置时，默认为false？

**Comment by osfans** [comment]
或者true false 这种都做图形界面 也比较简单

**Comment by DaengGWokFook** [comment]
按照xiaoqun的方法果然有效。新版就做圖形界面吧

**Comment by boboIqiqi** [comment]
@xiaoqun2016 好的，我试一下，以后多用用这个功能，可以跟输入法界面互相补充。非常感谢，听君一席话，胜读十年书。
智能识别中文词组，这个是自然语言处理里面的分词吧。librime,做拼音整句识别肯定也用到了。
你可以问一下老大可以实现不？ @osfans 
在编辑面板定义一个键，编辑时，先获取当前文本框中的内容，进行分词，然后每次点击，在当前光标位置，按词组扩大选择范围。
[分词技术](http://baike.baidu.com/link?url=Ert0C2-DhO3PSfZtzxIk6euI5iqJbXPOwega2-qc_qFIlbnJ5Uz_KsmC_-vSqjz-IGZ8TGdwviRoIGYPqpv5cq)

我看好像不难实现，就是拿一个大词库，进行多次匹配取最优，也没有用到什么语义理解分析。

**Comment by xiaoqun2016** [comment]
@boboIqiqi 先声明一下，我的观点可能很奇葩，莫怪。😊  

关于选择复制，不必太花精力在这上面，甚至砍掉这个功能也无妨。因为这是安卓系统要做的事情，输入法过度干涉会有「窥探用户隐私」的嫌疑。  ios上的输入法好像都没有这个功能？（是不是苹果为了安全，阻止了输入法滥用这个权限？） 国外的安卓输入法也几乎没有做这个功能。  
佛振在谷歌上班，不知道他有没有参与开发安卓版的谷歌拼音？不过我好像从谷歌拼音中看到了跟rime有某些相似的地方。  
 如果让他提点建议，他会说什么呢？

**Comment by boboIqiqi** [comment]
嗯，有道理，先实现最最重要的功能。我试了一下用案桌的确实比较好用。

我是想了解一下输入法中用到的一些自然语言处理的知识。
拼音整句识别对语义分析要求很高，做了九宫格是不是要求更高，因为选拔范围变得更广了。咱们的语义分析引擎能达到不？@osfans

另外，我当前就是集中实现候选框中的配置界面，参照别的输入法。@xiaoqun2016 你会做图标不，后面可能需要有人做些图标，只要把别人的扣下来，稍稍改得不一样一点

**Comment by xiaoqun2016** [comment]
@boboIqiqi 关于图标  
style总共五十多个选项，大概有二三十个选项可以做到图形界面里，图标好像很难。美工我也不懂
