### ISSUE TITLE
全选+切换键盘的一个bug 

### ISSUE THREAD

**Issue by boboIqiqi** [osfans/trime#79]
在@xiaoqun2016 的帮助下，我的五笔双键已经可以使用了，现在同文也是我的主力输入法了。但是今天发现了一个后果挺严重的漏洞。我刚开始写了一段话，我想把它复制到另一个地方。我的主界面键盘没有全选。我切换到符号键盘，然后点击一下全选 全部选中。 但是符号界面又没有粘贴复制，我就又切换了一下键盘，然后我的东西就被全删了。这个应该是切换键盘的，bug ，切换时不应该删除选中的内容。而且即使要删除，也应该默认复制到剪切板。还有我们可以参考一下触宝输入法的界面，应该把全选复制粘贴等编辑功能，专门放到一个布局上，然后在候选框中有切换按钮。这些按键单独一两个，孤立的出现一个键盘上没有意义。

**Comment by osfans** [comment]
确实有这个问题 还蛮严重的 可能是切换时上屏了空字？

**Comment by xiaoqun2016** [comment]
inline_preedit: false就好了。  
是跟嵌入模式有关系？

**Comment by osfans** [comment]
这样啊 好发现 要解决
