### ISSUE TITLE
重复刚上屏的字%1 如何设置呢

### ISSUE THREAD

**Issue by hbghlyj** [osfans/trime#798]
类似于
```   Wiki: {label: 維基, send: function, command: run, option: "https://zh.wikipedia.org/wiki/%s"} #搜索網頁: %s或者%1$s爲當前漢字```
请问如何把一个键的功能设为: 重复刚上屏的字%1
比如要输入"哈哈哈哈",上屏一个"哈"以后,按3下重复键就可以了.

**Comment by tumuyan** [comment]
目前不支持，虽然增加支持并不困难，但是通用性太低了，建议使用lua实现
