### ISSUE TITLE
[xperia 1iii]奇怪的BUG，导致无法使用拍照键

### ISSUE THREAD

**Issue by linGinc** [osfans/trime#803]
手机：Xperia 1iii
系统：Android 12（61.1.A.9.128）安全更新：2022年6月1日 Play系统更新：2022年6月1日
Trime版本：3.2.2以后所有版本
问题：使用3.2.2 realse版后面的所有版本（均卸载，删除文件夹，重新安装），部署后，可以正常使用，但锁屏后会出现BUG，表现为：手机按拍照键（实体按键）启动相机后，再按拍照键拍照，拍完一张后按拍照键无法再次进行拍照，3.2.2版本正常。

**Comment by guanu244** [comment]
靠，找問題找了好久，居然是輸入法造成的嗎
謝謝你
5 ii也會

**Comment by sntc06** [comment]
Pixel 5 也會，Android 12/13 都有這個行為
只要把 音量鍵 行為 設定成快門，就會發生
感覺有點像是 onKeyDown, onKeyUp 這裡有問題

**Comment by WhiredPlanck** [comment]
感谢反馈，我们已注意到这个 bug 多时，但由于现有代码对按键处理的复杂性，短时间内可能无法解决。

**Comment by cabins** [comment]
在vivo的手机上，也会使音量键快门失效。

**Comment by goofyz** [comment]
最近 Samsung 機上轉用 trime 也發現這問題，希望有人能做出修正。感謝。
