### ISSUE TITLE
输入法内置计算器功能

### ISSUE THREAD

**Issue by tumuyan** [osfans/trime#805]
**Is your feature request related to a problem? Please describe.**
计算器是部分输入法的小功能，同文也可以有。
如果不反对，我打算增加这个功能 @Bambooin 

**Describe the solution you'd like**
引入MVEL2
键盘增加“使用等号计算“的功能开关
当输入=时，尝试读取选区内容。如果没有内容，读取对所在行内容，把文本传递给MVEL2，如果有计算结果ans，输出=ans。如果没有合法ans，按照正常打字处理

**Comment by Bambooin** [comment]
I don't think that we need this feature right now.

We should focus and fix issue related with IME by now.

**Comment by baozilala** [comment]
这么多年过去了，还在修复bug？这个功能提议的那么好有什么进展吗？

**Comment by baozilala** [comment]
> **Is your feature request related to a problem? Please describe.** 计算器是部分输入法的小功能，同文也可以有。 如果不反对，我打算增加这个功能 [@Bambooin](https://github.com/Bambooin)
> 
> **Describe the solution you'd like** 引入MVEL2 键盘增加“使用等号计算“的功能开关 当输入=时，尝试读取选区内容。如果没有内容，读取对所在行内容，把文本传递给MVEL2，如果有计算结果ans，输出=ans。如果没有合法ans，按照正常打字处理

是一个好的建议，搜狗有这个功能用着很方便，不过现在已经切到同文了，每次都很蹩脚的调出手机计算器。雾凇方案只能自己修改快捷键
