### ISSUE TITLE
外接鍵盤組合鍵

### ISSUE THREAD

**Issue by osfans** [osfans/trime#81]
比如`Control+Shift+2`，用來切換中英文

**Comment by boboIqiqi** [comment]
老大还用外接键盘呀，那是用平板了？我也有一个，一直在吃灰。看来可以拍上用途了。我写的吉他输入法模型特别适合平板或大屏手机。回头发上来给你们看一下

**Comment by boboIqiqi** [comment]
只是为什么要+2，直接跟电脑一样，ctrl + space 不行吗。

**Comment by osfans** [comment]
那是小狼毫默認的。

**Comment by mitetou** [comment]
我在yaml文件里将这个快捷方式定义为shift键,可是不起效果,想知道原因。

**Comment by osfans** [comment]
ctrl alt shift暫時不能用，用功能鍵吧

**Comment by osfans** [comment]
f7f16e335a9b4f7c7322344ed583cecb39c0ebdc 修正

**Comment by lilydjwg** [comment]
我使用的 20181217 版本，ctrl+space 没效果 :-(
