### ISSUE TITLE
opencc裏後綴爲ocd文件怎麼修改？

### ISSUE THREAD

**Issue by DaengGWokFook** [osfans/trime#82]
要用甚麼程序？

**Comment by osfans** [comment]
最新版的trime是有帶opencc的txt文件的，你修改txt後，部署時就會生成ocd文件。

**Comment by DaengGWokFook** [comment]
手機的ocd文件複製到電腦有效嗎？

**Comment by osfans** [comment]
应该不通用，x86和arm不通用，32位和64位也不通用。只有txt通用。

**Comment by osfans** [comment]
电脑上opencc也有生成ocd的工具的。
或者要通用的话，修改配置文件，直接用text，不要使用ocd：

``` json
#hk2s.json
{
  "name": "Traditional Chinese (Hong Kong standard) to Simplified Chinese",
  "segmentation": {
    "type": "mmseg",
    "dict": {
      "type": "text",
      "file": "TSPhrases.txt"
    }
  },
```

这样应该也行。

**Comment by DaengGWokFook** [comment]
小狼毫沒有的json是甚麼文件？

**Comment by Prcuvu** [comment]
OpenCC文件格式经历了一次修改，小狼毫0.9.30使用了旧版OpenCC，所以没有json文件。json对应小狼毫的ini文件。

**Comment by osfans** [comment]
如樓上所說，小狼毫用的舊版的opencc，是ini文件。最新opencc的json文件參看：
https://github.com/BYVoid/OpenCC/tree/master/data/config
