### ISSUE TITLE
librime未能正确处理shift组合键

### ISSUE THREAD

**Issue by tumuyan** [osfans/trime#824]
**Describe the bug**
在同文调用librime时，实际上未能正确处理shift组合键。
按下软键盘时，使用直接发送字符的方式传值给librime，librime并没有直接处理按键事件，因此此时字母键打字正常，但是shift+数字和符号不能发送中文符号；
当使用实体键盘时，Shift+字母键也不能输入大写字母到编码区。

**To Reproduce**
Steps to reproduce the bug:
4. See bug

**Expected behavior**
Rime.onKey 正确处理shift键的组合键

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi Mix 4]
 - OS: [e.g. Android 11]
 - Theme: [e.g. Tongwenfeng]
 - Version: [e.g. 3.2.1]
 - Build info: 
```
Build: Commit CI   
Date: 2022-08-08 14:04 UTC   
Commit: v3.2.7-45-g1ce3bec, 2022-08-07 21:03:21 +0800   
Branch: develop   
Repository: https://github.com/osfans/trime  
```

**Additional context**

**Comment by sbxlmdsl** [comment]
但是，在同文3.2.10中，这些Shift组合键的输入在中文标点时是完全正常的，肯定是在3.2.11中引入的问题，而不是librime的问题。

**Comment by sbxlmdsl** [comment]
跟踪发现，这些Shift组合键在3.2.11中，根本就没有经过librime中的engine的ProcessKey处理，因为被keyCodeToVal判断成RimeKey_VoidSymbol了。

**Comment by WhiredPlanck** [comment]
现已修复。
