### ISSUE TITLE
Google Play上版本（3.1.3）不支持Android 13

### ISSUE THREAD

**Issue by BYVoid** [osfans/trime#825]
**Describe the bug**
The version on Google Play 3.1.3 does not support Android 13. The candidate bar is not shown. Please help update Google Play.

**To Reproduce**
Steps to reproduce the bug:
Type anything

**Expected behavior**
Show candidate bar

**Screenshots**
![Screenshot_20220812-142104](https://user-images.githubusercontent.com/245270/184447899-7dc7ce14-1edb-4a81-a171-7d7e006e7839.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 13
 - Theme: both
 - Version: 3.13

**Comment by gkovacs** [comment]
I can confirm that I have the same issue after upgrading to Android 13. I am using the same device (Pixel 6 Pro) and the same version of trime

**Comment by InfinityLoop1308** [comment]
As Android 13 is still in preview, the support may take long time. You must wait until one of the maintainers upgraded to Android 13 and apply a fix. Sorry, but currently we can do nothing about that.

**Comment by qwernser** [comment]
@InfinityLoop1309 thanks for the explanation. may I know if there is any existing plan for the upgrade and fix

**Comment by InfinityLoop1308** [comment]
> @InfinityLoop1309 thanks for the explanation. may I know if there is any existing plan for the upgrade and fix

AFAIK, no. Seems maintainers are all busy these days.

**Comment by qwernser** [comment]
> AFAIK, no. Seems maintainers are all busy these days.

sad.. anyway thanks

**Comment by tzwm** [comment]
Have the same issue

**Comment by zhihmeng** [comment]
分享一下…

我自己也有個輸入法的產品 (UrKeyboard) 遇到一樣的問題…後來在 google 開發者論壇裡找到了一個 work around 的解決方案…

就是在 onStartInput() 多 call 一次 setCandidatesViewShown(true) …然後那個 candidateView 就很神奇可以正常顯示了…

別問我為什麼會這樣…我也找不到原因…我猜有可能是 Android 13 改了某些 render view 的順序吧…XD

**Comment by Bambooin** [comment]
Please use Fdroid or Github release, Google Play was deprecated.

**Comment by Bambooin** [comment]
Follow up with #997
