### ISSUE TITLE
反查時鍵盤可自定義

### ISSUE THREAD

**Issue by DaengGWokFook** [osfans/trime#83]
例如：倉頡用拼音反查，應該將反查鍵盤改爲拉丁字母更方便。

**Comment by osfans** [comment]
想法不错 支持 不知能不能获得反查状态

**Comment by DaengGWokFook** [comment]
爲了方便將電腦輸入方案直接複製到手機，建議還是改trime.yaml。
弄好兩個鍵盤並命名爲倉頡和拼音。
trime.yaml
patch：
cangjie5 keyboard：{standard：倉頡，reverse：拼音}

**Comment by xiaoqun2016** [comment]
提供一种思路，供参考：
```yaml
    - {click: "`{Keyboard_xxx}" #按下反查引导键`，自动切换到xxx键盘
```
至于反查后如何返回仓颉键盘，可以改造xxx键盘

**Comment by osfans** [comment]
这思路不错 确实不好确定是否为反查
