### ISSUE TITLE
數字小鍵盤輸入無反應

### ISSUE THREAD

**Issue by z-Wind** [osfans/trime#832]
**Describe the bug**
在有的應用程式中，像是 chrome，按下數字小鍵盤的數字，無看到任何輸出
但若是大鍵盤的上排數字，是可以成功輸出的

**To Reproduce**
1. 打開 chrome，點擊搜索框
2. 切換至數字小鍵盤
3. 輸入數字無任何反應

**Expected behavior**
希望能成功輸出數字

**Screenshots**
![image](https://user-images.githubusercontent.com/16359142/185350789-6a51565c-53a9-4fd7-a650-033a32940f14.png)

**Smartphone (please complete the following information):**
 - Device: 紅米Note 4X
 - OS: Android 11, LineageOS18.1
 
![image](https://user-images.githubusercontent.com/16359142/185350684-bddc0b49-dd2b-40c5-a609-1ef95a232421.png)

**Comment by tumuyan** [comment]
这个bug已经修复过了，请从github action下载ci自动构建的apk文件。

**Comment by z-Wind** [comment]
不好意思，請問我該到哪下載呢？
release 中也只有 3.2.7 跟我的版本似乎是一樣的

**Comment by tumuyan** [comment]
https://github.com/osfans/trime/actions/workflows/commit-ci.yml

![image](https://user-images.githubusercontent.com/3126801/185445564-55f5f3b9-7d0a-46f7-a6c4-762617f95209.png)

![image](https://user-images.githubusercontent.com/3126801/185445767-c8bb3d7e-a241-4e7e-89de-66cc606706a2.png)
