### ISSUE TITLE
集成自动填充功能

### ISSUE THREAD

**Issue by tumuyan** [osfans/trime#834]
**Is your feature request related to a problem? Please describe.**

https://developer.android.google.cn/guide/topics/text/ime-autofill?hl=zh-cn

**Describe the solution you'd like**

1. 兼容其他自动填充工具
2. 输入法本身提供自动填充服务

**Describe alternatives you've considered**

**Additional context**

**Comment by InfinityLoop1308** [comment]
My user experience of autofilling is very bad using Firefox or keepassDX. If it is because of their bad design, I will be eager to give Trime a try. Otherwise, it may not need to be integrated since it is totally unusable.
