### ISSUE TITLE
候選框日文字亂碼

### ISSUE THREAD

**Issue by z-Wind** [osfans/trime#837]
**Describe the bug**
選字時，日文字都是豆腐塊，同樣的設定在 linux 上不會出現
應該是 font 的問題，但一直無法成功設定
請問我是否有弄錯什麼呢？

 - 共享資料夾：/sdcard/rime/default
 - 使用者資料夾：/sdcard/rime/custom

部署做法：將 build 全砍，重新部署，並強制停止同文輸入法，再重新啟動
試過的方法
1. 將 HanaMinB.ttf 放到 /sdcard/rime/default/fonts/hanb.ttf
2. 將 HanaMinB.ttf 放到 /sdcard/rime/custom/fonts/hanb.ttf
3. 將 HanaMinB.ttf 放到 /sdcard/rime/fonts/hanb.ttf
4. 將 HanaMinA.ttf 放到 /sdcard/rime/default/fonts/han.ttf
    將 HanaMinB.ttf 放到 /sdcard/rime/default/fonts/hanb.ttf

![image](https://user-images.githubusercontent.com/16359142/185937028-6120ba6d-92dc-4e3e-b408-2b2ef1a0e287.png)
![image](https://user-images.githubusercontent.com/16359142/185937088-b99b6da7-dca3-4837-b36a-134777f7faea.png)

**Smartphone (please complete the following information):**
 - Device: 紅米Note 4X
 - OS: Android 11, LineageOS18.1
![image](https://user-images.githubusercontent.com/16359142/185937585-3c196fab-dfa4-4bee-8da7-f28fb9b94e5d.png)

**Comment by z-Wind** [comment]
後來找到原因了，因為字是 unicodes 的 Private Use Area，所以才會是方塊字
linux 在這一塊應該是定義成日文字，所以才正常

**Comment by wsickid** [comment]
> 後來找到原因了，因為字是 unicodes 的 Private Use Area，所以才會是方塊字 linux 在這一塊應該是定義成日文字，所以才正常

怎么解决讷
