### ISSUE TITLE
问一个小问题键盘布局，.default和default有什么区别?

### ISSUE THREAD

**Issue by boboIqiqi** [osfans/trime#84]
``` yaml
  "style/keyboards":
    - .default
    - default
    - number
    - symbols
```

就是在 trime.custom.yaml中。为什么以.开始呀？

另外我昨天发现了一个网站，本来想发到咱们这里来的，结果发到rime里面了。
贴到下面：
https://github.com/rime/home/issues/78

**Comment by osfans** [comment]
那個是rime的主站。

**Comment by osfans** [comment]
.default會自動找一個鍵盤方案，default就是一個叫default的方案。
