### ISSUE TITLE
〔重新部署〕无效

### ISSUE THREAD

**Issue by yanhuacuo** [osfans/trime#842]
最新时间节点：

https://github.com/osfans/trime/commit/0c8f8847fd9a74aff72aaf121b1c105da5af736a

编译出来的 APK，〔重新部署〕无效，不能将「用户目录」下的 yaml 参数改动，正确部署出来。

还有另一件诡异的事情，如果此时杀进程的话，内置的 trime.yaml 会无视「用户目录」下已有同名文件的事实，强行对本地覆盖。

希望改进。

**Comment by yanhuacuo** [comment]
泡冒看看，好像重构版自发布以来一直都有「本地参数改动无法部署生效」的问题。

**Comment by tzwm** [comment]
+1 有同样的问题。
v3.2.7

**Comment by yanhuacuo** [comment]
> +1 有同样的问题。 v3.2.7

影响使用了。

**Comment by yanhuacuo** [comment]
最新节点，依然有问题，冒泡追一追进度。

**Comment by WhiredPlanck** [comment]
“重新部署”实际是操作了 app 的哪个按钮呢 ……？

**Comment by yanhuacuo** [comment]
> “重新部署”实际是操作了 app 的哪个按钮呢 ……？

设置中的「部署」按钮啊，当修改过 yaml 之后，令其生效所要按的那个按钮。

**Comment by WhiredPlanck** [comment]
> > “重新部署”实际是操作了 app 的哪个按钮呢 ……？
> 
> 设置中的「部署」按钮啊，当修改过 yaml 之后，令其生效所要按的那个按钮。

你是否修改的是 `*.custom.yaml`，如果是的话，这个问题已在 PR #899 中解决。

另外的提醒：app 首页的部署按钮是不会部署主题的，这个部署按钮针对且只能针对 rime 的方案、字典等起效。同文的主题配置只是用到了 rime 为 yaml 添加的一些独有的编译语法，所以要靠 rime 引擎的部署功能来部署，但除此之外主题配置和 rime 引擎本身毫无瓜葛。主题的部署在选择和应用主题的那一刻开始。

**Comment by WhiredPlanck** [comment]
> 还有另一件诡异的事情，如果此时杀进程的话，内置的 trime.yaml 会无视「用户目录」下已有同名文件的事实，强行对本地覆盖。

同文每次全新启动时，会同步一次内置的数据，如果用户是直接对 `trime.yaml` 进行修改的话，就会被覆盖。所以我推荐通过 `trime.custom.yaml` 来打补丁，这样就不会有这个问题了。

**Comment by WhiredPlanck** [comment]
请看新版本有无此问题。Please take a look for new version.
每夜版/Nigntly Build：https://github.com/osfans/trime/releases/tag/nightly
