### ISSUE TITLE
〔字符宽度计算有问题〕拆分注解会换行

### ISSUE THREAD

**Issue by yanhuacuo** [osfans/trime#843]
悬浮窗最大宽度给了 1200 也不行：
![字符宽度计算有问题](https://raw.githubusercontent.com/yanhuacuo/wiz/main/IMG_20220904_104640.jpg)

**Comment by yanhuacuo** [comment]
最新时间节点编译的 APK

https://github.com/osfans/trime/commit/0c8f8847fd9a74aff72aaf121b1c105da5af736a

**Comment by yanhuacuo** [comment]
3 月份编译过的版本，就没有这个问题。

**Comment by yanhuacuo** [comment]
问题依旧，冒泡。

**Comment by WhiredPlanck** [comment]
@yanhuacuo 请调大 `style/layout/max_length` 参数。
