### ISSUE TITLE
有的方案不能部署

### ISSUE THREAD

**Issue by linsui** [osfans/trime#849]
**Describe the bug**
我导入了 https://github.com/mutoe/rime 的方案，但是部署的时候 自然码双拼+ 的文件没有出现在 build 文件夹里。在 Linux 上部署正常。请问是有什么配置需要设置吗？自然码双拼和其他方案都部署正常，唯独 double_pinyin_plus 这个方案无法部署。

**To Reproduce**
Steps to reproduce the bug:
4. See bug

**Expected behavior**

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 6
 - OS: Android 11
 - Theme: Dark temple
 - Version: 3.2.8
 - Build info: 
   ```
 Build: null
 Date: 2022-09-05 16:44 UTC
 Commit: v3.2.8, 2022-08-18 22:35:50 +0800
 Branch: null
 Repository: https://github.com/osfans/trime
   ```
**Additional context**

**Comment by WhiredPlanck** [comment]
看起来 double_pinyin_plus 用了几个比较大的词典，目前同文在遇到大词典的时候部署性能会较差，这个短期内可能改观有限。感谢反馈 ～
