### ISSUE TITLE
关于商业模式的一些想法

### ISSUE THREAD

**Issue by boboIqiqi** [osfans/trime#85]
虽说谈钱有点俗，不过想想如果我们的劳动有回报的话，那会多有动力啊。
一切不以赚钱为目的的创业都是耍流氓。
而且小琴老师帮了我这么多我也多么想给她一些回报啊。

下面就说说我的想法。
我主要是想希望推出一个类似应用商店的，输入法商店。里面放自定义好的布局和输入方案。
每个输入法都是经过作者自己认真使用，觉得很高效值得推荐的方案。会附带教程和使用说明。以及一些输入技巧。

然后下载方案需要付金币。另外对现有的方案进行微调也需要请专家付金币。

嗯这样我咨询小琴老师然后我付他金币我得到了一个方案。然后我把我的方案放到商店里面供你下载。每次下载都会收获金币。小琴老师付出的是技术，我付出的是一种方案的设计和使用测试。

每个手机，第一次注册会给一定的金币，嗯以后可以通过完成别人的咨询或者花钱购买金币。

对于我和小秦老师，因为已经有好多金币了就可以就可以回兑人民币

**Comment by boboIqiqi** [comment]
当然还会有些其他的问题，比如盗版。有人把所有的方案文件都上传到一个免费的网上。我们可以给用户的只是编译后的二进制文件。需要定制的话必须跟指定的专家联系。

比如说我的五笔双健方案，指定的专家就是小琴老师。需要做微调或者定制都要联系他。

好心老师帮人定制，可以获取一定的金币和下载提成，还有以后的维护权利

**Comment by boboIqiqi** [comment]
我用语音输入，实在不想打英文，@xiaoqun2016 你就将就一下哈

**Comment by boboIqiqi** [comment]
二进制文件，可以加一些保护，跟手机的imei 号或者什么的绑定

**Comment by osfans** [comment]
不是叫小羣嗎？周邊的可以搞搞，類似於售後，主程序還是純淨點好。

**Comment by boboIqiqi** [comment]
其实就是一个论坛模式，金币可以花钱购买，也可以帮别人定制，完成别人的要求，或者咨询来获取。

另外，我的还可以举办一些输入法比赛了。像QQ上经常有什么天雨跟打群。可以测速度，码长什么的。下个客户端就可以了。我们可以下个插件到输入法中，到微信群上跟打。
还可以做微信公众号，好友之间晒速度。

这些是推广方面的

**Comment by xiaoqun2016** [comment]
@boboIqiqi 
关于商业模式，多多输入法好像有提供收费定制服务，不知道效果如何。

**Comment by osfans** [comment]
我也不熟，你們做的話，我支持，革命分工不同。

**Comment by boboIqiqi** [comment]
@xiaoqun2016 
xiaoqun老师果然见多识广，我稍稍看了一下多多的网站，
然后就看到一个帖子：
[多输入法会出mac和linux版本](http://chinput.com/thread-2522-1-1.html)

> 多多输入法会考虑出mac和linux版本的吗，如果会出的话我想rime这些肯定弱爆了

我们还有同行竞争呀！
不过，我理解多多的输入法定制用户还是面向输入法制作者，而不是普通用户。另外，定制服务提供者和受益者，还是多多自己，而不是多多的专家用户。他更多的还是希望通过卖软件赚钱，而不是服务。

所以，我又有些新想法，虽然不成熟，但是抛砖引玉，说出来跟大家讨论一下。

昨晚在QQ上给xiaoqun老师送了一朵花(不是玫瑰，就是你教师节送老师的那种)
然后我就发现，
百度贴吧，有T豆，可以送礼物
QQ也要充钱，才能送虚拟礼品
再想想，网上开直播，讲讲笑话，或者吃碗面，就有土豪打赏。我们这些靠技术吃饭，为人提供支持的，难道就没有一点机会能让感激我们的同学给我们一些小费吗？为什么要便宜了南极企鹅和北极熊？

我的想法就是，我们把rime.im的论坛稍稍改造一下。普通的还是发贴，回答，这都没有问题。当然，也可以引入积分了，金币，虚拟物品什么的
然后重点是，建立一个**专家出诊制**。就是像医院一样，有些专家医生可以出诊，像京东客服一下，在线提供服务。如果某位专家充裕的一段时间，就可以在线出诊。然后如果有土豪(总会有的，土豪就喜欢花钱)，愿意挂号预约专家，帮忙实现Rime的定制。就需要出点金币了。或者咨询完，可以再打赏一些。

网站还是通过出售金币赚钱，但是专家也可以靠出诊，打赏拿到收益。当然不同级别的专家，出诊费也可以不一样。除了挂号费，还可以按服务时间酌情加费，厉害的专家(xiaoqun老师级别的)几分钟就可以解决问题，或者找到解决方案的链接。不厉害的专家可能还需要在线做功课，提供的指导也不一定是最全面最优的。服务质量，我们可以通过录音，查看聊天记录，来进行审核。

对于专家，我们还可以定期吸收一批有经验的用户。可以建立等级考试（在线考，或者电话面试），以及经常在论坛回答某一方面的问题，都可以成为专科医生，有自己擅长的领域，用户预约的时候可以看到。根据自己的问题类型来预约专家。

总之，就是建立一个论坛，把用户集中起来，然后提供一些VIP服务，从高级用户身上赚钱，然后为免费用户提供更优质的服务。让专家有收益，让小白提问更理直气壮。这样我们的团队建设会更完善，Rime的生态系统也会形成，发展会更有动力。

@osfans 请老大提供意见

**Comment by Prcuvu** [comment]
@lotem 这个主意如何？

**Comment by Prcuvu** [comment]
据我所知，schema文件目前是不会转化成二进制文件的，只有dict会。如果要实现这个想法，需要让librime予以配合。

**Comment by boboIqiqi** [comment]
@prcuvu librime的的原理我还不太懂，不过感觉如果能将源码和二进制文件分开，对版权保护和商业化会比较好。当然定制的话就只能联系原作者。

**Comment by xiaoqun2016** [comment]
高手不来，那就在我们小白之间讨论一下。   
- 需要花钱定制的场景多不多？  
  Rime配置门槛高，不太接地气，如果再搞咨询服务收费，潜在的用户会不会被吓跑了？  
  而且真正实用的方案一旦配置完成，就很少需要更改了。 一套方案可以给一群人用。有可能Rime越是强大，需要定制的机会就越少。如果定制需求不多，即使加密了schema又能带来多少收益呢？  
  从我个人的经历来讲，调试出适合自己的方案可能只需要掌握30% Rime的知识。而帮别人解决问题可以推动自己深入了解Rime，这其实也是在帮自己。  
- 竞争对手是谁？  
  多多仅仅适合传统形码的打法。图形界面，联想，词典，命令直通车，这些是它的长处。但它并不是一个功能全面的输入法平台（语句模式、语言模型几乎还是空白）。
  小小输入法介于多多和Rime之间，有特色，但很低调，容易被人低估。它坚持自己的定位，没有把别人当成竞争对手，这么多年都在默默地完善自己。
  Rime的竞争对手可能也是自己吧。多多和小小虽然在某些方面不如Rime，但它们在自己定位的领域都做得无可挑剔，所以我觉得它们都是成熟的产品。虽然我一直在用Rime，但总觉得Rime是半成品，它给自己定了一个很高的起点，到现在都还没完成，让人满怀期待又无可奈何。（并非贬义）  

以上是个人观点，欢迎批评指正。

**Comment by boboIqiqi** [comment]
@xiaoqun2016 终于有人回复了。
非常感谢xiaoqun同学总能在第一时间给出专业的意见。
虽然意见有些不一致，但是还是让我脑洞大开。等周末我再好好研究一下，你说的这些输入法。也再做一些调研吧。毕竟我对小狼毫还有新版的rime-gist都不太懂

我只说说我个人的感觉吧。如果花10块钱，和半个小时的时间，有人帮我定制好我的五笔，Vim+小狼毫以及几个输入法的细节，我还是愿意的。（半个小时，是指我会提前把我的要求大致整理好，才能跟专家交流，既然都整理好了，为什么不上论坛？因为优质的回答太难等了。而且还得自己反复试和理解。）

反过来，我愿意花一些时间回复别人的贴子，这个毕竟是我的知识梳理，但是，如果让我把半个小时，专门在QQ帮一个新手定制他的输入法，我就不太愿意了。因为，这段时间我完全被他占据了。要不停的互动。但是，新手往往喜欢这样。我现在也有很多问题，但是我没有时间去网上查，或者发贴子问，问了别人也是给一个链接，让自己试。但是一个经验的专业客服，会给出最贴切用户需要的方案。（其实我就是想他把文件发给我，我就能用了）

咨询服务收费，只是针对没有时间的用户。只是论坛问答的一个补充。专家也可以免费义诊，这不冲突。或者在晋升专家之前，要先免费实习一段时间。但是免费，排号就得排队了。土豪又可以花钱插队什么的。

需要花钱定制场景多不多？
每个人的使用习惯和使用场景不同，还是需要一些定制，或者使用技巧的传授。
如果现在有个人定制好了Vim版的小狼毫全配置，花几块钱，我也是愿意的。不仅仅是一个配置，而且还会教给我很多使用技巧。

关于定制吧
其实大家需要的定制并不限于输入方案本身（主流的输入法也就那些），还有一些使用习惯和一些快捷功能。到手机，定制就会更多一些了，因为整个键盘布局都可以定制。所以多多的定制实在是少了些

能想到就是这些吧。我先好好补充补充知识。

很高兴能有机会跟xiaoqun同学交流输入法方面的各种知识，保持联系哦。

**Comment by lotem** [comment]
市場太小了，我認爲不足以支持爲實現商業模式所做的投資。
所以我就不做了，勸 @osfans 也先別做。
其他同學有興趣可以嘗試整理自己手頭的資源，打包發佈一個專門的產品。
爲此做出的努力如果幫到他人，應該是可以有回報的。

---

我覺得現在亟需的是分享資源的渠道、工具和規範。
不應該強調傳播定製輸入法的技能本身，每項定製的方法和內容，都應該可以通過代碼或簡單腳本分享，而不是讓每個人學會並重做一遍。

有幾點主張：
分享資源的粒度：分享單項內容意義大於分享全套配置。因爲需求完全一致的用戶極少。應允許在功能級別進行自由組合。
強調以源碼形式分享，以鼓勵用戶參與已有內容的除錯、改進和再創作。
使用線上版本控制工具管理和發佈資源。

**Comment by osfans** [comment]
老大的意見還是很中肯的。確實市場不大，還有我們的東西也不太成熟。
但要是有人弄個論壇什麼的，我也會是去的。比如QQ羣，貼吧，酷安市場。

單項內容？太細的話，就是教程和經驗分享了？
說到分享，目前我蒐集了github上好多開源方案，放在了 https://github.com/osfans/rime-tool 這裏。

**Comment by zaqzrh** [comment]
小白说小白的话，@xiaoqun2016正解。Rime门槛高，相信@boboIqiqi折腾一段时间总算入门了，付出了不少的时间和精力，如果还要付钱？那真的不想“玩”了！

目前有哪个输入法还能“收费”的，拼音\五笔的搜狗、百度、qq、微软等等，自定义的多多、小小等等，多多和小小能生存除了它的功能长处外，主要还是能支持win8和10。

**Comment by kahaani** [comment]
支持@lotem的观点：「強調以源碼形式分享，以鼓勵用戶參與已有內容的除錯、改進和再創作。」
不希望以「不公开码表」为目的的二进制化，因为不符合开源精神。

**Comment by boboIqiqi** [comment]
本来以为会有人支持呢，没想到被轮番轰炸了。@xiaoqun2016 老师，你是不是都不好意思上第二波批判了？ 唉，真理总是掌握在少数人手中。
等过一段时间，我把网站搭起来，再给你们看吧。

@Kahaani 
- 首先，开源不是目的，用户最关心的也不开源，而是更好的使用体验。你会用微信，支付宝跟他们开不开源没有关系吧。如果不开源，能保护开发者的权益，促使他们开发出更好的，更符合用户需求的输入方案，再主动配上教程，积极努力的传播，我觉得对用户也会更用利吧。
- 其次，是否开源应该是开发者的权利，由开发者决定。Android系统是开源的，但是不能要求Android上所有的应用都开源呀。如果作者做一个输入方案，那么是否开源应该由方案创作者决定。从这个角度讲，Rime应该提供这个选项
- 最后，“强调以源码形式分享，鼓勵用戶參與已有內容的除錯、改進和再創作”，这个还真不好说。你看看Linux和Windows上哪个应用多就知道了。用户参与是有成本代价，如果别人做好了，能满足我的需求，干嘛要参与。当然，Vim，Python,Eclipse 这些程序员的工具除外...

**Comment by boboIqiqi** [comment]
@zaqzrh 
“付出了不少的时间和精力，如果还要付钱？那真的不想“玩”了！”
差不多吧，大哥，就是你说的。真心的有点累。主要是缺乏成就感。要折腾很多细节，而且知道网上已经有人解决了，但是我还是没解决，你可以说是我的问题，但是，我想学习一点更高层的Rime知识，不是天天在这里折腾这个。或者等我懂原理了再来折腾吧。

“目前有哪个输入法还能“收费”的”
这个可能是吧。我问我女朋友了，就是那个qiqi,她也说她不会为输入法花一分钱的。真不好说

**Comment by boboIqiqi** [comment]
@osfans 老大，我们私下交流

**Comment by boboIqiqi** [comment]
@lotem 佛振老大也不支持，哭
不过，我觉得便宜有便宜的做法呀。就是用开源的discuz模板，再链上QQ的链接。交流在QQ上进行。
应该也还可以吧。
大概估算一下，如果是一个PHP熟手，差不多一个礼拜就搭起来了吧。然后再放到一个免费的空间上。再在我们的域名里给个链接，就可以上线了。
然后，我没有做过网络，不过也想学习一下吧。就当练个手了。差不多两个月？我还要学一段时间的rime，算上三个月。到今年中秋，差不多吧。

我还在学习Rime，最近工作比较忙。感谢Github,感谢我们的项目。让我在工作之余，接触到广阔的天地。让我学习了vim,yaml，正则表达式，等一系列的东西。领略了老大的设计

还是希望rime能发扬光大吧！不仅只限于一个小众的工具

**Comment by boboIqiqi** [comment]
最重要的，我觉得吧，知识只有传播和分享中才能不断升值。想想现在新手们为什么会退出，一是因为rime确实配置门槛高，没有人专业的辅导。另一个，是因为即使折腾得跟搜狗百度的差不多，也没有什么用处，只能给自己用，而且还不方便维护，学到的知识，也没有办法得到升值。如果有一个平台，可以有偿的分享他的知识，那前面的学习就有了实在的意义

**Comment by xiaoqun2016** [comment]
确实，有时候真理掌握在少数人手中。但加上“总是”意思就变啦。太过励志，不真实。  
总结这个问题下的不同观点，趋利，避害，中和，各有优缺点，不要走极端就好。  做这件事情对你有好处，不过可能不是你想的那种，以后应该会明白吧。

**Comment by osfans** [comment]
還是贊成xiaoqun2016的看法。

如果不怎麼花時間和金錢的話，可以先做做看。不過也要做好最壞的打算，最後可能用戶不多。

**Comment by xiaoqun2016** [comment]
知乎的「值乎」 https://zhi.zhihu.com/  
果壳的「分答」 http://fd.zaih.com/  
以及「想见」问答  http://www.exiangjian.cn/wenda/  
这些跟付费问答相关的东西最近开始萌芽了。不知道能走多远？  
可以关注一下。

**Comment by boboIqiqi** [comment]
@xiaoqun2016 好久不见，非常想念。
最近都事情比较多，都没关注Github
谢谢你的几个同贴子，我会好好看的。

**Comment by osfans** [comment]
暫時關閉
