### ISSUE TITLE
3.2.8无法选字

### ISSUE THREAD

**Issue by Eyion** [osfans/trime#854]
输入法版本：3.2.8
主题方案：四叶草九宫格
配色方案：默认同文风优化版
问题：拼音输入后无法选字，因为选字时会在拼音处继续输入，比如输入you（即968），选第一个“有”字，会在you后输入1（变成9681），无法确定下“有”字，请问是什么问题？如何解决？

**Comment by guanu244** [comment]
鍵盤設定>點擊候選字 直接上屏候選字

**Comment by Eyion** [comment]
谢谢，如何将此词库放到四叶草九宫格方案中，链接：https://github.com/wuhgit/CustomPinyinDictionary
