### ISSUE TITLE
候选栏里候选字前如何显示序号,不是悬浮窗?

### ISSUE THREAD

**Issue by Sunpulseqd** [osfans/trime#856]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Sunpulseqd** [comment]
"style/window": 
    - {start: "", composition: "%s", end: "", letter_spacing: 0.12} #letter_spacing需要Android5.0
    - {start: "\n", label: "%s.", candidate: "%s", comment: "%s", end: ""}

**Comment by WhiredPlanck** [comment]
@Sunpulseqd 只有悬浮窗显示候选才有编号。
