### ISSUE TITLE
liquid_keyboard_window Bug * 2

### ISSUE THREAD

**Issue by RISEN-B** [osfans/trime#857]
**Describe the bug**
在汉语拼音输入模式下，由liquid_keyboard_window造成的两个相关Bug：
Bug 1. 如果未设置liquid_keyboard_window，进入liquid键盘后再返回主键盘，输入拼音则无法显示悬浮窗 (如自带的tongwenfeng主题)。
Bug 2. 在设置了liquid_keyboard_window后，悬浮窗正常的情况下，正在输入拼音时，竖屏切换横屏，再切换回竖屏，则悬浮窗会卡在屏幕上，必须强制停止Trime才能去掉悬浮窗。

**To Reproduce**
Bug 1 复现：
自带的tongwenfeng主题进入liquid键盘再返回，输入任意拼音即可复现。
Bug 2 复现：
自带的trime主题输入拼音时，切换横竖屏即可复现。

**Version**
F-Droid 3.2.8

**Comment by RISEN-B** [comment]
图片补充：
Bug 1：
![bug1](https://user-images.githubusercontent.com/34066513/193454319-d0e2da1f-772d-484f-b59b-e2f741af9b5b.jpg)
Bug 2：
![bug2](https://user-images.githubusercontent.com/34066513/193454360-b0c86157-1435-45a9-9f7a-0fb35ba61766.jpg)

**Comment by WhiredPlanck** [comment]
这个问题可能和 #897 的悬浮窗问题类似。

**Comment by shitlime** [comment]
可以在出现问题的主题中加入以下配置解决Bug1：

```yaml
  liquid_keyboard_window: #液态键盘模式下显示的悬浮窗口組件
    - {start: "", click: "space", label: " 空格 "}
    - {start: "", click: "BackSpace", label: " 删除 "}
    - {start: "", click: "Return", label: " 回车 "}
    - {start: "", click: "liquid_keyboard_exit", label: " 返回 "}
```

附上 [笔记](https://shitlime.gitbook.io/trime-problems-note/yuan-ma-yue-du-bi-ji-pei-zhi#xuan-fu-chuang-xiao-shi-wen-ti)

至于Bug2，我也不太清楚……
