### ISSUE TITLE
同文使用的權限

### ISSUE THREAD

**Issue by DaengGWokFook** [osfans/trime#86]
最近下載個apk權限刪除器，想刪除facebook，qq，微信之類軟件的間諜權限，無意點進同文，看下圖。
能否解釋一下？
![screenshot_2016-05-13-19-25-30](https://cloud.githubusercontent.com/assets/18633778/15264414/ea174856-1940-11e6-8dfc-a59bcf0c416b.png)

**Comment by osfans** [comment]
语音输入
保存码表
按键振动

**Comment by DaengGWokFook** [comment]
我記得你說過語音輸入是借用手機已經安裝的語音識別系統

**Comment by osfans** [comment]
是啊 你可以关了试试。我这边关了就不能输入了

**Comment by DaengGWokFook** [comment]
你說對了，刪除權限再使用則顯示權限不足，無法使用
