### ISSUE TITLE
联想功能

### ISSUE THREAD

**Issue by yubaolinfish** [osfans/trime#860]
作者你好：
librime作者提供了 https://github.com/lotem/librime-predict 库，是支持联想功能，请问下trime目前支持吗，或者有开发计划吗
原文：https://github.com/rime/librime/issues/65

**Comment by spew8712** [comment]
https://github.com/shewer/librime-lua-script
有人用lua寫出了聯想功能
親測可在trime上運作
只是行爲跟在windows上不太一樣
會在commit前之候選階段就顯示聯想項（排在原本候選項後面），嚴重拖累性能，慎用！
（windows上使用shewer所提供之rime.dll，聯想項會在commit後才出現在自己的候選窗，commit前只會依所錄入碼顯示原本候選項）

**Comment by spew8712** [comment]
上述問題已暫時解決
見[shewer/librime-lua-script#16](https://github.com/shewer/librime-lua-script/issues/16)之作法

**Comment by Tsinswreng** [comment]
https://github.com/Tsinswreng/rime-TswG
内有我自己用lua实现的联想插件。同文、小狼毫均可用

**Comment by WhiredPlanck** [comment]
同文现已加入 librime-predict 插件支持。
