### ISSUE TITLE
这款输入法在5.1的系统上运行不起来

### ISSUE THREAD

**Issue by Rachel-hsw** [osfans/trime#861]
6.0上运行起来了，但是好卡的

**Comment by Rovever** [comment]
我从android4.4到现在12一直用，个人感觉trime版本3.1.3和3.2.1（目前在用，系统12）最稳定，不卡。最新版添加了许多新功能，但同样很多bug，还在完善中，测试还可以，日常使用没必要追新。

**Comment by Rachel-hsw** [comment]
> 我从android4.4到现在12一直用，个人感觉trime版本3.1.3和3.2.1（目前在用，系统12）最稳定，不卡。最新版添加了许多新功能，但同样很多bug，还在完善中，测试还可以，日常使用没必要追新。

好嘞，谢谢
