### ISSUE TITLE
键盘样式乱码

### ISSUE THREAD

**Issue by tao659** [osfans/trime#862]
同文风 样式，在通过键盘上的主题样式切换 主题时，
键盘会出现乱码如下。
![IMG_20221015_193553](https://user-images.githubusercontent.com/16471291/195984476-31b98eac-8c55-4708-8e1e-5489c217c6d1.jpg)

**Comment by WhiredPlanck** [comment]
已成功复现。还没有找到具体原因，但猜测是元素的相对位置在切换过程中暂停在了一个中间过渡的阶段，所以会短暂出现一下排版错乱的情况。临时的解决方案之一是随便点一个按键，可能就能恢复正常；或者切换为别的主题，然后再切换回来。

**Comment by iislong** [comment]
![Screenshot_2022-11-16-14-49-08-918_com osfans trime](https://user-images.githubusercontent.com/2937252/202105755-1d784c23-417c-472b-b006-35d78313d82e.jpg)
主题切换出错的同时会产生重复的主题列表，重装后进行切换操作复现

**Comment by WhiredPlanck** [comment]
> 主题切换出错的同时会产生重复的主题列表，重装后进行切换操作复现

这种情况可以判断你的共享目录和用户目录是同一个目录。主题选择器的列表目前的生成原理是，共享目录和用户目录各扫描一次，将后缀名为 `trime.yaml` 结尾的文件名去掉这个后缀后加入列表中，最后显示出来。虽然我加了逻辑判断使得两个目录路径相同时只扫一个目录的结果，但偶尔还是会卡出两个来，日后看看有没有更好的方法。
