### ISSUE TITLE
求教开发环境搭建

### ISSUE THREAD

**Issue by boboIqiqi** [osfans/trime#87]
我以前的Android SDK版本比较老。是4.3（API 18）。有些函数的常量，都没有。
(JDK是1.6,刚开始也不支持 switch(String),不过这个我解决了。)

现在的问题是，我昨晚更新了SDK,现在SDK Manager的内容如下:
![sdkcontent](https://cloud.githubusercontent.com/assets/1284515/15264696/c0f718e4-19a8-11e6-87cd-c7ca89ea96a3.png)

但是，我Eclipse还是提示错误
![eclipseerror](https://cloud.githubusercontent.com/assets/1284515/15264693/bef2c4c6-19a8-11e6-9633-11696e627a93.PNG)

我查了一下.M就是Android6.0的API里面的呀，我也已经安装了，而且我也没有改AndroidManifest.xml中的TargetSDK, 还有哪里有问题？
求老大指教

**Comment by osfans** [comment]
清空看看 那之前怎么编译过的？

**Comment by boboIqiqi** [comment]
clean了好几次，貌似了不管用。之前是将这个函数内容注释掉。就这.M和几个函数没有定义
我这不是想跟大家保持一致，不用每次提交都注释什么的

**Comment by osfans** [comment]
不行就趁机换到android studio？

**Comment by osfans** [comment]
或者只是警告，不影响编译？

**Comment by boboIqiqi** [comment]
算了，那先这样吧，我每次提交最后的Pull Request的时候，把这个注释打开就行了。

我也想过换Android Studio，折腾了几次，还是放弃了。
用来编我们的项目要添加很多文件，不知道是我没设置好还是什么的。

同事都用Eclipse，交流都不方便。而且我现在也不想再学一套快捷键，Eclipse用习惯了。

**Comment by boboIqiqi** [comment]
老大，我今天争取先把那个PC命令下发的Receiver实现一下，然后发上来，你测试下。
争取完成一个Pull Request的合并。

默写一下命令
1.更新本地仓库  git fetch upstream
2.从最新的develop分支创建一个分支　 git checkout -b  feature/pc-debug-command-receiver
3. git commit -m
4. git push -u origin feature/pc-deubg-command-receiver

**Comment by osfans** [comment]
好啊 编译过应该就没问题
所有target都改成23看看？不编jni的话 依赖的东西不多。我都是用linux命令行编的。

**Comment by boboIqiqi** [comment]
@osfans　老大，真不好意思。就是你说的那个问题。
在是在　project.properties　这个文件里的。
我只改了AndroidManifest.xml中的 TargetSDK

> # Project target.
> target=android-23
> key.store=debug.keystore
> key.alias=androiddebugkey

没有改这里的
