### ISSUE TITLE
可不可以在后台部署？

### ISSUE THREAD

**Issue by fxliang** [osfans/trime#872]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
有些方案部署时间超长，占用顶层界面无法操作任何东西，体验和死机无异，建议进入disable状态，另开线程部署。

**Comment by Bambooin** [comment]
I don't think it a good idea, since only first deployemt is long with heavy dictionary file.

Otherwise, it's very short in the second time.

**Comment by fxliang** [comment]
> I don't think it a good idea, since only first deployemt is long with heavy dictionary file.
> 
> Otherwise, it's very short in the second time.

then is it good idea to keep the suck experience for the first time deployment or other situation like that ? OMG

**Comment by Bambooin** [comment]
The deployment is for building the config and dictionary bin file, so user can't do anything during deployment.

User can't choose theme and color or other things during deployment.

As far as I known, the rime in macOS, Windows and Linux just disables UI during deployment too.

**Comment by fxliang** [comment]
i'm not mac user or linux user, so i don't know rime in those systems. 
however in windows, for sure i know, rime won't diable the system ui interactions. while deployment undergoing, yes , rime is disabled, but we could still open apps, input ascii codes, switch to other imes, kill apps and so on and on.
