### ISSUE TITLE
无法进入APP中的剪贴板，收藏夹和草稿箱内容

### ISSUE THREAD

**Issue by txmu** [osfans/trime#874]
如题。版本为最新编译成功的3.2.10，进入app内的剪贴板内容时直接崩溃，而进入收藏夹/草稿箱内容时弹出“选择同文输入法作为默认输入法”。有一次点剪贴板也出现的是选择同文输入法作为默认输入法，有一次能正常进收藏夹，其他的不行

**Comment by luckyfatpig** [comment]
同样的问题

**Comment by WhiredPlanck** [comment]
App 内的管理页面已暂时不可用，请暂时直接在键盘上进行相关操作
