### ISSUE TITLE
coloros13系统运行时看不到候选框，候选框是一片空白

### ISSUE THREAD

**Issue by lovinghonoka** [osfans/trime#875]
![Uploading Screenshot_2022-11-07-13-07-19-16_a252b927494330cdc2c8ba3b3f952e5e.jpg…]()

**Comment by lovinghonoka** [comment]
![Screenshot_2022-11-07-13-07-19-16_a252b927494330cdc2c8ba3b3f952e5e](https://user-images.githubusercontent.com/37255154/200230807-fb17052c-c271-4e39-b85c-e30f93725271.jpg)

**Comment by WhiredPlanck** [comment]
又是这样，是 Android 13 底层吗

**Comment by lovinghonoka** [comment]
是安卓13




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月10日(星期四) 下午3:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [osfans/trime] coloros13系统运行时看不到候选框，候选框是一片空白 (Issue #875)





 
又是这样，是 Android 13 底层吗

**Comment by WhiredPlanck** [comment]
> 是安卓13
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年11月10日(星期四) 下午3:13 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [osfans/trime] coloros13系统运行时看不到候选框，候选框是一片空白 (Issue #875) 又是这样，是 Android 13 底层吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

那就对了，这个属于 Android 13 特定问题，晚点排查一下

**Comment by steven-shi** [comment]
同样问题 救命无法使用输入法了
我刚升级了安卓13

**Comment by 1208005448** [comment]
救命，我也是遇到了这样的问题，希望早日修复

**Comment by steven-shi** [comment]
问题解决了，不要使用Google play上的版本，那个太旧了，在release这里下载最新版本就行了

**Comment by kentsin** [comment]
能更新一下 Play Store 上版本嗎?

**Comment by Bambooin** [comment]
Please use latest Github release version, Google Play market is deprecated.
