### ISSUE TITLE
安卓平台外接键盘显示优化

### ISSUE THREAD

**Issue by martin214** [osfans/trime#878]
鸿蒙3平台下外接键盘没法隐藏虚拟键盘而只显示候选框

**Comment by cabins** [comment]
这个问题在vivo Pad上也有类似的情况。大致的表现为：

总要先弹出来屏幕键盘，手动按下返回键后才能隐藏。感觉如果修改成，先检测是否连接了键盘，如果连接了就不弹出来就好了。

**Comment by cabins** [comment]
我现在的解决方案/思路是这样的：

① 新建一个mini键盘，只保留候选框（准确的说是，空白的一行/个按键，以及高度设置为1）；
② 在默认的键盘和mini键盘都开启切换应用程序的时候保留布局，这样你只需要切换一次到mini键盘，之后就一直是mini键盘（直到你手动切换回默认键盘）。

感觉这样解决了我使用的主要痛点。虽然还是有一次手动切换，但也就只有一次而已。
