### ISSUE TITLE
reset_ascii_mode在应用QuickEdit Text Editor Pro的搜索中有点问题

### ISSUE THREAD

**Issue by TingTing1990** [osfans/trime#879]
### 描述错误：
使用九宫输入法，将reset_ascii_mode设为true，在QuickEdit Text Editor Pro搜索中转到英文键盘后搜索，如果出现历史记录点击后转跳回九宫的中文模式，这里是正常的，但是输入法的状态栏那里显示的是“英/西文”模式，打字输出正常，也立马变回了“中/中文”模式

### 复现：
已附上视频

https://user-images.githubusercontent.com/51083586/203705118-e953dfea-d8a6-447e-a94b-50e530bd8b11.mp4

### 预期行为：
reset_ascii_mode为true，因转回为九宫的中文状态/状态栏的ascii_mode应为中

### 应用和系统：
F-d的3.2.9
三星Android 12

**Comment by punalex** [comment]
借問一下, 我在"鍵盤設定"的"嵌入式編碼模式"選了輸入碼, 我在用倉頡中文輸入時用中英混打, 和你一樣打了as選了屏幕上的ascii, 但as兩個輸入碼還留在輸入區變成asciias, 後面的as有底線代表還是輸入模式, 請問有辦法在點選屏幕的字(或和屏幕互動)後清除輸入碼嗎?
