### ISSUE TITLE
同文输入法有没有简单科普的说明

### ISSUE THREAD

**Issue by hyaray** [osfans/trime#880]
之前只用过小狼毫，现在想使用同文输入法，遇到以下问题：
1. 下载：有release和F-Droid两种方式，安装包大小还不同，应该选哪个？
2. 主题有trime和tongwenfeng两种，功能区别是什么？一般用哪个好？
3. 部署后，是不是第一次打开都会卡好几秒才行，这是正常情况吗？部署几分钟都可以，但更希望在用的时候能直接开启。

**Comment by guanu244** [comment]
我不專業，只是個使用者
但目前新版本用起來問題非常多
整個異常卡頓、每日早晨會自動切換回其他輸入法（3.2.9才出現的問題，不知道是不是什麼應用衝突了）
然後換回輸入法都要開啟APP，否則鍵盤不會出現，接著又有一定機率部屬失敗，
應用會沒有回應，要一直重啟碰機率，從多工頁面滑掉APP甚至也會關閉鍵盤。

我建議
若是用不到剪貼簿或者草稿的功能，
可以選release3.2.3以前的版本做使用，甚至3.2.1，我覺得在那以前的版本都沒多大問題。

至於問題
1. release就好
2. 審美問題
3. 第一次部屬依照設定檔的不同，有些會卡很久，甚至停止回應，最久的有遇過30分鐘的，
這期間APP完全不會有任何提示，只會完全停止回應，等就對了。

至於第一次打開會卡我覺得是3.2.9的問題，你可以先退回3.2.8試試。

**Comment by hyaray** [comment]
非常感谢解惑，原来新版本问题多多，那我就换回老版本！！
相关信息真的太少了，一直踩坑的感觉真难受

**Comment by cabins** [comment]
我使用了329两天就暂时回退到328了。

① 我一直使用的是github的release版本；没有对比过区别，功能上应该没有差异（猜测）；
② 我是自己修改了默认主题的风格，添加了自定义的键盘布局，所以两个主题对我来说没有什么区别；默认安装完了之后，就是主题的风格不同而已；没有功能区别；
② 可能是我的配置比较简单（小鹤音形〔主要〕+98五笔〔体验学习〕），从来没有碰到部署那么长时间的，基本上都是几秒钟的时间。打开的时候也没有碰到过卡顿。

科普说明的话，我一直是读wiki的。感觉写的还不错呀~

**Comment by hyaray** [comment]
再次感谢，我把我折腾的心得分享下：
1. 手机安装release版，`3.2.9`选`配色`有bug，可以先用3.2.8，新版本肯定会修复。
2. 复制小狼毫的用户文件夹大部分文件，以下是排除列表
    - weasel.custom.yaml
    - weasel.yaml
    - installation.yaml
    - user.yaml
    - rime.dll
    - opencc 如果用`ocd`格式，需要用64位的 `opencc_dict` 编译
3. 同文不像小狼毫自带几个输入方案，所以还要从[[共享文件夹]]复制
    - default.yaml
    - 关联输入方案的`schema.yaml`文件
4. 部署功能因为没有日志非常难受，所以暂时就依赖PC把大部分依赖都build好迁移
5. 同文额外增加了键盘方案，自带两套键盘方案，我认为tongwenfeng的比trime强大多了，配置文件也大不少。如果自己有特别喜好，以此为模板再自己修正，单独弄个键盘风格即可
6. windows上的临时按键，在同文上可能没有，也依赖上面调整键盘按键的方式实现
7. 其他的待完善。
