### ISSUE TITLE
3.2.9 arm64版本无法修改配色

### ISSUE THREAD

**Issue by carlos444** [osfans/trime#887]
**Describe the bug**
3.2.9 arm64版本无法修改虚拟键盘配色

**To Reproduce**
Steps to reproduce the bug:
1. 打开同文输入法配置工具
2. 点击主题与配色-点击配色，再次打开虚拟键盘，仍为默认配色
3. 重新部署也无效
4. 3.2.8无此bug

**Expected behavior**
希望能正常显示其他配色

**Smartphone (please complete the following information):**
 - Device: [华为huawei nova 5 pro]
 - OS: [e.g. Android 9]
 - Theme: [e.g. Tongwenfeng]
 - Version: [3.2.9]
 - Build info: 
 - Builder: Release CI
Build Time: 2022-11-01 11:55 UTC
Build Version Name: v3.2.9-0-ga34a9c3
Git Hash: a34a9c3
Git Branch: v3.2.9
Git Repo: https://github.com/osfans/trime

**Comment by cabins** [comment]
这貌似是已知问题了。

**Comment by Bambooin** [comment]
Fix in #877
