### ISSUE TITLE
重新部署这个黑匣子，能优化下吗？

### ISSUE THREAD

**Issue by hyaray** [osfans/trime#888]
每次点击部署就闪退了，输入法一直出不来无法打字，哪怕等个10几分钟也问题依旧，都是后来稀里糊涂自己好的。
如果之前已经部署过了，不应该所有都再重新生成一次吧？是否有记录文件修改日期来判断是否需要重新部署。
像小狼毫重新部署都是瞬间完成的，而同文则完全不知道重新部署都在做了什么事，手机性能和PC也没差那么多啊。
如果配置有错误，我也要彻底地修复问题，但是无从下手，请求指导！！！

**Comment by Bambooin** [comment]
For the config issue, you can use https://github.com/Bambooin/rimerc

For the deployment issue, see #866
