### ISSUE TITLE
自定rime文件夾位置

### ISSUE THREAD

**Issue by DaengGWokFook** [osfans/trime#89]
我的手機不知爲何總是將手機內存作爲默認儲存和讀取位置，而且只有4GB，下載大型遊戲幾乎爆滿。
我想過將rime文件夾放到sd卡，可以減少內存負擔。

**Comment by osfans** [comment]
目前准备这么做，系统的放data目录，用户的可以自定义。

**Comment by William8915** [comment]
Before this function is officially available could you please show me how to do it if I want to compile the package myself? I have modified the hard-coded paths in src/com/osfans/trime/Config.java and jni/librime_jni/rime.h to point to /path/to/my/external/sdcard/Android/data/com.osfans.trime but it doesn't seem to do the trick, any ideas or sugeestions?

**Comment by osfans** [comment]
@William8915 @DaengGWokFook 
91dcff0dd7f7ade4cb3f232a2c221c299cd19f7c fixed.
