### ISSUE TITLE
make debug failed on Ubuntu

### ISSUE THREAD

**Issue by sbxlmdsl** [osfans/trime#890]
**Describe the bug**
Tried to execute "make debug" for building trime v3.2.9 on 64 bit Ubuntu and failed.

**Screenshots**
![image](https://user-images.githubusercontent.com/17001744/207485517-d21be697-0124-4c89-98f2-37482d6b02af.png)

![image](https://user-images.githubusercontent.com/17001744/207485308-7a11d7fa-6532-43cf-8cd5-a91c418c10ac.png)

![image](https://user-images.githubusercontent.com/17001744/207485010-e6959182-71b2-4dce-8465-d2fa9a1cb2f2.png)

**Comment by Bambooin** [comment]
Please follow the build script in Github Action, our platform of ci is Ubuntu.
