### ISSUE TITLE
部署过程中提示 charset_filter 重复注册

### ISSUE THREAD

**Issue by tao659** [osfans/trime#891]
如下图所示，是配置文件的问题吗？
![Screenshot_2022-12-17-13-21-33-069_com osfans trime](https://user-images.githubusercontent.com/16471291/208226802-f62eef33-4a4d-4a92-8612-684b7b8251f7.jpg)

**Comment by tao659** [comment]
版本及编译信息如下：
v3.2.9-18-gf7cc962-debug
Builder: Commit CI
Build Time: 2022-12-13 13:06 UTC
Build Version Name: v3.2.9-18-gf7cc962
Git Hash: f7cc962
Git Branch: develop
Git Repo: https://github.com/osfans/trime

**Comment by WhiredPlanck** [comment]
如果不影响正常使用，一般无需担心。
