### ISSUE TITLE
Crashing on swiching theme / color

### ISSUE THREAD

**Issue by WhiredPlanck** [osfans/trime#892]
**Describe the bug**
The app crashes after switching the theme or color in the setting page.

**To Reproduce**
Found one crash with steps:
1. Theme & Color
2. Themes
3. Switch to another theme
4. Crash(90%)

**Expected behavior**
As we all know ...

**Log**
N/A

**Screenshots**
N/A

**Comment by WhiredPlanck** [comment]
This is mentioned in #889 and actually fixed in #877 .

**Comment by Bambooin** [comment]
Fix in #877
