### ISSUE TITLE
键盘按键倒圆角 取消了？

### ISSUE THREAD

**Issue by tao659** [osfans/trime#895]
版本信息
Builder: Pull Request CI
Build Time: 2022-12-25 06:08 UTC
Build Version Name: v3.2.9-51-g812bea5d
Git Hash: 812bea5d
Git Branch: 894/merge
Git Repo: https://github.com/osfans/trime

新版本好像取消了键盘按键倒圆角？如下图 
![Screenshot_2022-12-25-15-05-15-467_com android browser](https://user-images.githubusercontent.com/16471291/209459657-c3b14900-ef8a-4e72-ad30-80068211ebd0.jpg)

**Comment by WhiredPlanck** [comment]
应该是圆角参数未能正确应用上，可能是哪里代码写歪了 ……

**Comment by WhiredPlanck** [comment]
> 应该是圆角参数未能正确应用上，可能是哪里代码写歪了 ……

@tao659 已找到原因。3.2.10 版本进行了主题解析的重构，将只显示纯颜色的可绘制类型（Drawable）从原来的 GradientDrawable 替换为了 ColorDrawable，以期减少性能损耗（但其实没有确定的证据证明这样就能显著降低性能损耗，是我一厢情愿）。然而 ColorDrawable 作为一个简单的可绘制类型，基本只能显示颜色而不能设置圆角等外观参数，这等同于按键的圆角参数失效了。之后会换回 GradientDrawable。感谢反馈 ～
