### ISSUE TITLE
悬浮窗不显示，ascii_mode记不住

### ISSUE THREAD

**Issue by lidawei97688** [osfans/trime#897]
新版本的trime似乎没有申请【在其他应用上层显示】，所以悬浮窗看不到，切换主题和配色的窗口画面也在键盘上方输入法和应用的交界处被裁掉

ascii状态在切换到其他键盘后再切换回来的时候会重置为中文，无法记住切换键盘前的ascii状态（版本3.2.4—3.2.10都是如此）

**Comment by WhiredPlanck** [comment]
> 新版本的trime似乎没有申请【在其他应用上层显示】，所以悬浮窗看不到，切换主题和配色的窗口画面也在键盘上方输入法和应用的交界处被裁掉

新版本的同文不再需要【在其他应用上层显示】来显示悬浮窗。请检查设置中的开关是否开启。我这里测试一切正常。目前未有其他用户报告此类问题。

不过你说到输入法的窗口被裁切的问题，我认为这可能是你的系统有其他图层遮挡在了上方。可以检查一下是否有其他应用影响了显示。

> ascii状态在切换到其他键盘后再切换回来的时候会重置为中文，无法记住切换键盘前的ascii状态（版本3.2.4—3.2.10都是如此）

这似乎是一个特性，在切回主键盘时将 ascii_mode 重置。请检查方案里的
```yaml
switches:
...
- name: ascii_mode
  reset: 1
...
```
处是否有 `reset: 1` 这行设置，如果有，尝试将其置 0 或去掉这一行，然后重新部署看看是否依旧这样。

另外，方便告知一下你现在使用的 Android 版本和 ROM 名称吗？

**Comment by lidawei97688** [comment]
华为mate20
android 9
EMUI 9.0
这系统应该是没啥参考价值了
以上方法试了一下，没起效果

**Comment by WhiredPlanck** [comment]
> 华为mate20 android 9 EMUI 9.0 这系统应该是没啥参考价值了 以上方法试了一下，没起效果

悬浮窗还是不显示吗？

**Comment by lidawei97688** [comment]
> 

悬浮窗或许已经显示了，但无法出现在其他应用上层，在我新买的安卓13系统的手机上是可以正常显示悬浮窗的，
其他的比如主题和配色选择的窗口也是只能显示出现在键盘上的部分，再往上的就被裁掉了
![Screenshot_20230107_092726_com android mms](https://user-images.githubusercontent.com/58324866/211125378-55a724dd-75cd-4769-bdef-0cee0f1bbaea.jpg)
![Screenshot_20230107_092751_com android mms](https://user-images.githubusercontent.com/58324866/211125381-04b0ffe6-d16a-4cec-8adf-80d2556aa89b.jpg)

**Comment by WhiredPlanck** [comment]
@lidawei97688 我在 Android 9 的模拟器里复现了，这可能是 Android 9 的特定问题。有待研究怎么修复。

**Comment by WhiredPlanck** [comment]
@lidawei97688 今天摸索了一天，不太好修。需要再等等。

**Comment by lidawei97688** [comment]
> @lidawei97688 今天摸索了一天，不太好修。需要再等等。

不急，打好地基要紧
