### ISSUE TITLE
版本选择

### ISSUE THREAD

**Issue by Eyion** [osfans/trime#898]
各版本对应的设备是什么，能否有个说明？不知道应该选择哪个更合适，谢谢！

**Comment by ameaninglessname** [comment]
手机选择arm64后缀的就好

> [点击了解更多](https://stackoverflow.com/questions/56824557/what-is-the-difference-between-armeabi-v7a-arm64-v8a-x86)

**Comment by Eyion** [comment]
> 手机选择arm64后缀的就好
> 
> > [点击了解更多](https://stackoverflow.com/questions/56824557/what-is-the-difference-between-armeabi-v7a-arm64-v8a-x86)

好的，谢谢。但有个问题，安装后无法回到之前的九宫格拼音，方案和主题都设置过了。（用的是四叶草九宫方案）

**Comment by guocuixia** [comment]
华为p40pro.鸿蒙2.0 四叶草方案 可使用3.2.5版本arm64(用最新版不能正常使用)

**Comment by Eyion** [comment]
> 华为p40pro.鸿蒙2.0 四叶草方案 可使用3.2.5版本arm64(用最新版不能正常使用)

谢谢。
先转到其他输入法用吧，是不是得在其他输入法得到有个人输入习惯的词库导进来用会比较好？目前用着不太趁手，比如选词，效率较低。

**Comment by guocuixia** [comment]
> > 华为p40pro.鸿蒙2.0 四叶草方案 可使用3.2.5版本arm64(用最新版不能正常使用)
> 
> 谢谢。
> 先转到其他输入法用吧，是不是得在其他输入法得到有个人输入习惯的词库导进来用会比较好？目前用着不太趁手，比如选词，效率较低。

3.2.7也可以  

或者暂时用手机自带的输入法吧,我是因为发现搜狗输入法会上传输入记录和剪贴板记录才决定换的.

同文单右手选第一个候选词比较难选中,需要正确姿势才可以^的确不趁手

如果可以调键盘高度应该能解决

我也还没弄词库,可以慢慢弄

**Comment by guocuixia** [comment]
> > 华为p40pro.鸿蒙2.0 四叶草方案 可使用3.2.5版本arm64(用最新版不能正常使用)
> 
> 谢谢。
> 先转到其他输入法用吧，是不是得在其他输入法得到有个人输入习惯的词库导进来用会比较好？目前用着不太趁手，比如选词，效率较低。

刚把手机的文字显示大小显示改大,刚说的第一个候选词选不准的问题解决了
