### ISSUE TITLE
推荐一个Unicode 8.0符号字体

### ISSUE THREAD

**Issue by zaqzrh** [osfans/trime#9]
推荐一个Unicode Standard, Version 8.0的符号字体
http://users.teilar.gr/~g1951d/Symbola.zip

**Comment by osfans** [comment]
我電腦上就是這個。這個該怎麼用呢？鍵盤、候選詞、拼音？

**Comment by zaqzrh** [comment]
这个当作用户选用吧。
它只是对symbols.yaml的显示补充，由用户放/sdcard/rime/fonts/。

**Comment by osfans** [comment]
嗯，不過目前字符集沒分得太細，只分了基本字符和擴展字符集。
你看怎麼分比較合適？

**Comment by zaqzrh** [comment]
目前还没有一个能包含所有的unicode8.0字符的字体，花园明朝体也只含部分符号，国际标准超大字符集字体支持包(Unifonts 6.0)问题多缺字多，Symbola只是搜集字符部分。基本字符已够用了，以外的由用户想办法吧！
