### ISSUE TITLE
需求如下图

### ISSUE THREAD

**Issue by qwert-f** [osfans/trime#900]
![Screenshot_2023-01-04-17-25-12-87_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/50124761/210524061-71248e00-f644-4baa-a247-e1209b325546.jpg)

![Screenshot_2023-01-04-17-25-50-99_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/50124761/210524114-300e5354-254c-4f37-beae-56594f4d3422.jpg)
上面两张图一张是同文输入法另一个是grammarly输入法，在已打开一个主应用而另一个新开应用是浮窗状态时，若浮窗应用需要使用输入法，会全屏占用，希望可以半屏或浮窗状态占用

**Comment by qwert-f** [comment]
两张图片均是后面打开了需要横屏的应用，新开的QQ是属于浮窗状态，然后点开QQ聊天界面输入框后，输入法展示的状态

**Comment by guanu244** [comment]
emm...鍵盤設定內，
不是就有一個橫屏時全屏編輯，
這個選項可以設定嗎？

**Comment by qwert-f** [comment]
> emm...鍵盤設定內，
> 不是就有一個橫屏時全屏編輯，
> 這個選項可以設定嗎？

我知道横屏全屏设定，但是需求你看图，两张图差别那么大，一个几乎占满整个屏幕，一个占半屏
