### ISSUE TITLE
似乎同文输入法不再适合非程序员使用了。

### ISSUE THREAD

**Issue by 4SM** [osfans/trime#901]
反观 小狼毫／鼠须管／中州韵 每隔几年更新一次，非常稳定。
同文是不是可以区分升级通道？让愿意进行测试的程序员可以经常在 github 上下载到最新版本，普通受众可以在 play 商店／f-droid 下载并且使用【**经过测试的，出厂可用的**】稳定版本？其实普通受众并不求时常更新，稳定才是最重要的，哪怕是几年升级一次，不要让用户战战兢兢地点按【**更新**】按钮，可以吗？

在 f-driod 商店下载的 3.2.10 居人无法设置键盘高度，原有的 trime.custom.yaml 失效也就算了，但键盘高度只能适合婴儿的小手指，让成年人如何使用？发布之前测试过了吗？还是发布后让普通用户扮演小白鼠做测试？？

抱歉，我不是程序员，我也没有参与软件测试的意愿，但无论如何，忠言逆耳，作者的更新策略的确是太过激进，激进到只剩下愿意参与测试的一小撮程序员了。

谢谢。

**Comment by guocuixia** [comment]
在手机设置里文字显示大小改大,键盘就大了

**Comment by WhiredPlanck** [comment]
> 但无论如何，忠言逆耳

我理解你说话不好听的原因，然而即便这样也无济于事。原作者现在已经几乎不参与软件开发了。近来的更新都是我和另外一位贡献者 @tumuyan 在推进。而最近因为各种原因，现在就剩下我一个人在开发了（你看看提交历史就能发现了）。人手少、任务重，同文有许多代码需要重构或者加以改进，bug 多是意料之中的。然而我也越来越陷入思维定式了，每次打开 IDE 都一脸茫然不知道怎么改进 ……

如果你或者你能拉人入伙来帮忙，我感激不尽 …… 开源项目纯靠爱发电，我现在是学生，空闲时间还多些，明年我参加工作的时候如果再没有人能帮忙继续开发的话，我估计同文就可能陷入停止更新的困境了。

> 在 f-driod 商店下载的 3.2.10 居人无法设置键盘高度

我目前除了你的和 @guocuixia 的 Issue 外，没有收到其他类似的反馈。不能排除是所用的配置本身不合理，所以受到了新版重构的影响。新版对配置参数的应用方式是更合理的，也许你需要重新调整配置。


另外介绍一下同文目前的发行策略：目前同文是固定每隔一季度时间自动发行一次新版，所以如果这之间提交的代码有 bug 而没有及时被发现而被修复的话，那么就会带入新版中。前面我提到了同文项目面临的难处，所以目前的情况就是我只能尽力修复，让问题不在下一个版本出现。

**Comment by 4SM** [comment]
我要求现在真的很低，只要键盘高度高一点，让我手指可以摁的舒服一点，这个要求真不过份吧 :) trime.custom.yaml 究竟应该怎么写？谢谢。

**Comment by WhiredPlanck** [comment]
> 我要求现在真的很低，只要键盘高度高一点，让我手指可以摁的舒服一点，这个要求真不过份吧 :) trime.custom.yaml 究竟应该怎么写？谢谢。

在 trime.custom.yaml 的以下地方：
```yaml
patch:
   ...
   keyboard_height: <你想要的像素值，最大值为你的屏幕的长边像素值>
   ...
```
然后再在“主题和配色”处再选一次主题（或者切成其他的再切回来）

**Comment by 4SM** [comment]
> > 我要求现在真的很低，只要键盘高度高一点，让我手指可以摁的舒服一点，这个要求真不过份吧 :) trime.custom.yaml 究竟应该怎么写？谢谢。
> 
> 在 trime.custom.yaml 的以下地方：
> 
> ```yaml
> patch:
>    ...
>    keyboard_height: <你想要的像素值，最大值为你的屏幕的长边像素值>
>    ...
> ```
> 
> 然后再在“主题和配色”处再选一次主题（或者切成其他的再切回来）

还是不行 :( 。你可以给我一份  trime.custom.yaml 吗？谢谢。

**Comment by undus5** [comment]
每每看到开源应用遇到这种巨婴用户都无语地不行，理直气壮地指责，还“我不愿意参与测试”，“这点要求不过分吧”。
怎的，开发者们是吃你家米了吗，他们压根就没有义务满足你的要求，无论过不过分。
虽然同文的现状确实让人诟病，但是有问题正常提就行了，实在不行自己也下场参与进来，不要像狗一样乱叫。

**Comment by oniondelta** [comment]
冒個頭給同文輸入法開發者加油！

開源軟體為開發者佛心興趣使然免費貢獻的！
使用者有問題，平鋪直敘表達就好！

**Comment by WhiredPlanck** [comment]
> 还是不行 :( 。你可以给我一份 trime.custom.yaml 吗？谢谢。

如果不行，试试删掉 `trime.custom.yaml` 和 build 文件夹下的 `trime.yaml`，然后再新建 `trime.custom.yaml` 写上相应内容后，再应用一次主题。如果还不行，再重新删掉上述文件，然后直接修改 `trime.yaml`，再应用一次主题。这样还不行的话，如果可以的话就把你写的 `trime.custom.yaml` 发出来，我这边来测试一下看看。

**Comment by 4SM** [comment]
> > 还是不行 :( 。你可以给我一份 trime.custom.yaml 吗？谢谢。
> 
> 如果不行，试试删掉 `trime.custom.yaml` 和 build 文件夹下的 `trime.yaml`，然后再新建 `trime.custom.yaml` 写上相应内容后，再应用一次主题。如果还不行，再重新删掉上述文件，然后直接修改 `trime.yaml`，再应用一次主题。这样还不行的话，如果可以的话就把你写的 `trime.custom.yaml` 发出来，我这边来测试一下看看。

直接修改 `trime.yaml` 是修改这一行 `  keyboard_height: 250 #锁定键盘高度，避免切换时键盘高度变化而造成闪烁` 吗？

我的 `trime.custom.yaml` 如下：

```
patch:
   keyboard_height: 65	# 指定键盘高度
```

都试过的，但还是改不了键盘高度。

**Comment by 4SM** [comment]
另外补充一下，我的Android系统版本是：13.

**Comment by WhiredPlanck** [comment]
@4SM 有点怪，那可能是这个参数失效有一段时间了，但没人察觉到。我晚些时候排查一下，谢谢反馈 ～

**Comment by WhiredPlanck** [comment]
@4SM 截至相关 PR 合并时，我已经测试过 trime.custom.yaml 的起效情况，修改的参数确实已经传递了进去，但是基本只有键盘高度这个参数没有真正起效。同文的主题设置有几档关于键盘高度的，但我修改过后似乎都没有起效。这个问题可能不太简单，需要进一步排查。无论如何，感谢你的反馈 ～
