### ISSUE TITLE
第一个候选词无法准确选中,手机自带下拉搜索框无法实时搜索

### ISSUE THREAD

**Issue by guocuixia** [osfans/trime#903]
1.单个候选词点第一个词时需要十分精准，选择时右手拇指点按绝大多数情况下不能准确选中，
请问哪个版本可以调节键盘高度解决此问题，
使用方案:四叶草九宫格

2,华为p40pro２.０系统  下拉搜索框里输入搜索需要按确定才能显示结果，其它输入法是一边输入时就能直达搜索结果

3.手机自带下拉搜索框输入时上屏的字出现错乱,经过一番胡乱配置才得以正常.

总体使用不顺畅,主要配置耗时费力还多bug,

四叶草九宫格方案 3.2.10版本无法使用
目前使用3.2.7

手机端拼音九宫格还是很多人使用的 

希望有个成熟的方案

感谢作者

**Comment by guocuixia** [comment]
把手机的文字显示大小改大,刚说的第一个候选词选不准的问题解决

**Comment by WhiredPlanck** [comment]
> 单个候选词点第一个词时需要十分精准，选择时右手拇指点按绝大多数情况下不能准确选中，

这个问题有待我进一步测试，先谢谢你的反馈 ～


> 华为p40pro２.０系统 下拉搜索框里输入搜索需要按确定才能显示结果，其它输入法是一边输入时就能直达搜索结果

请尝试将“键盘设置”中的“嵌入式编辑模式”改为“首选”，看看有无改善。


> 手机自带下拉搜索框输入时上屏的字出现错乱,经过一番胡乱配置才得以正常.

信息有点不足，我这里也无法复现 …… 不知可否录屏呢？

另外，还烦请告知一下手机具体使用的 Android / HarmonyOS 的版本以及手机型号。

**Comment by guocuixia** [comment]
> > 手机自带下拉搜索框输入时上屏的字出现错乱,经过一番胡乱配置才得以正常.
> 

这个所谓错乱是输入第一个字母显示的不是对应的字，需要在输入第一个字母后，从第二个字母开始才能正常显示，那么会导致每次输入后必须删除第一个字母后才能再进行搜索

例如:在搜索栏里搜:"文件管理"，输入第一个字母"w'，搜索栏显示为"字"，而不是文或者w音开头的词，需要在w之后继续输入:"wen jian guan li"


手机版本:华为p40pro HarmonyOS 2.0 (2.0.0.280)
附 :录屏 不知有没上传成功

**Comment by guocuixia** [comment]
https://user-images.githubusercontent.com/81362502/210789521-61ca5112-9118-43c3-9411-e7f9752b6925.mp4

视频里显示输入"w"时搜索里直接上屏显示为"我"，有时不一样，
都是要在第二个字母开始输入才是正确的，每次输入完成后都要删除第一个字再进行搜索，体验很不好

**Comment by WhiredPlanck** [comment]
> SVID_20230105_204532_1.mp4
> 
> 视频里显示输入"w"时搜索里直接上屏显示为"我"，有时不一样， 都是要在第二个字母开始输入才是正确的，每次输入完成后都要删除第一个字再进行搜索，体验很不好

这种 bug 我也是第一次见 …… 我摸索一下吧，感谢反馈 ～

**Comment by guocuixia** [comment]
不知道和使用的方案有没关系
四叶草九宫使用的是https://github.com/SivanLaai/rime-pure/releases
版本rime_pure V1.1.7


正在使用的四叶草九宫格版本使用也不顺畅，例如:"符号",选择需要的符号后需要手动点返回，别的输入法如“小艺输入法”，在符号里直接有常用符号可选，选择完成不用手动返回！效率相差比较大，这个问题我会提交到
SivanLaai 那里
![Screenshot_20230105_215057_com android chrome_edit_33155808037127](https://user-images.githubusercontent.com/81362502/210796754-111b4f98-4e4c-42e6-831a-cfaa38ecd108.jpg)
![Screenshot_20230105_214958_com android chrome_edit_33196531503788](https://user-images.githubusercontent.com/81362502/210796762-f98fc25e-e7e6-41bd-8613-bf6d14c03ffb.jpg)

**Comment by WhiredPlanck** [comment]
@guocuixia 你似乎没有启用悬浮窗功能，更多符号这个选择器组件的作者将返回开关做进悬浮窗里了，所以没开的话会看不到。这确实不太合理，未来会尝试改进一下。
