### ISSUE TITLE
和小狼毫相比，同文缺少了一些自带配置文件

### ISSUE THREAD

**Issue by hyaray** [osfans/trime#905]
感谢作者的更新，`3.2.10`终于有错误提示了，非常棒，如果能增加点说明如何解决常见的错误就更好了。

我是小狼毫和同文用同一套配置，发现同文缺少了`default.yaml` , 从 `https://raw.githubusercontent.com/rime/rime-prelude/master/default.yaml` 下载的`default.yaml`，又用到了`punctuation.yaml`和`key_bindings.yaml`，这两个文件同样是同文没有自带的，
于是，我把这些文件全添加到了小狼毫的配置文件里，再同步到同文。不知道这种处理方式是否妥当，应该有更正确的方式吧！

**Comment by WhiredPlanck** [comment]
除了主题文件，同文基本没有自带任何方案依赖和其他配置文件。这是一个特性，同文因为高度自定义，所以不内置（钦定）任何方案依赖。
但是总的来说，你说的几个文件是几乎每个方案必须用到的，所以你的做法没有问题。
除了你所说的方法外，还可以直接到这个仓库 https://github.com/Bambooin/rimerc 里下载预配置。

**Comment by hyaray** [comment]
非常感谢耐心解答，解惑了！！
