### ISSUE TITLE
实体键盘中用shift或是ctrl键切换中英文

### ISSUE THREAD

**Issue by mitetou** [osfans/trime#91]
如题，如果有方法，请指点我。
感谢几位开发者，谢谢，这么好的输入法，让我在各个平台都能流畅的享受码字的快乐，谢谢。

**Comment by mitetou** [comment]
第二个问题，如何在实体键盘中用shift或是ctrl键切换中英文，按照佛振的教程，发现并不起效果。

**Comment by osfans** [comment]
暫時這兩個問題都沒有解決

**Comment by osfans** [comment]
光標跟隨已完成。

**Comment by Jim-Young** [comment]
现在支持实体键盘了吗？
我在android 6里面，用实体键盘，不能用shift键切换还不是问题，可以按crtl+shift+2来切换，但是不能用 上下左右键+shift 来选择文字都很不方便了，如果可以用ctrl+shift+左右选择文字组就更好

如果想自己加这个功能，从哪里入手呢？

谢谢指点

**Comment by osfans** [comment]
f7f16e335a9b4f7c7322344ed583cecb39c0ebdc 已修正ctrl或shift組合鍵。也可以用Shift+方向選擇文字了。
