### ISSUE TITLE
在 vivo 和 OPPO 手机上均出现侯选栏不显示的问题

### ISSUE THREAD

**Issue by yikyuencheung** [osfans/trime#910]
在近期推出的新款手机（如 iQOO 11 Pro、vivo x90、一加 11）上均发现侯选栏不显示的问题。手机系统版本均为 Android 13，已开启悬浮窗权限。

![Screenshot_2023_01_09_16_50_24_09_cf3cf72bd8e53b0db7ddb0a6f2208af9](https://user-images.githubusercontent.com/11884953/211270572-cf08c511-3ed5-4cec-90c8-d292bb54dfd2.jpg)

曾怀疑过是同文不支援高分辨率萤幕（如 2K 屏）导致，但将系统分辨率降为 1080P 或使用原生 1080P 的手机也会出现该问题。麻烦排查。

非常感谢。

**Comment by yikyuencheung** [comment]
原来是 Google Play 版本太老的缘故，已解决。感谢。

**Comment by shenmishajing** [comment]
> 原来是 Google Play 版本太老的缘故，已解决。感谢。

@yikyuencheung 求问是如何解决的，我试了3.1.3的版本，还是存在这个问题
