### ISSUE TITLE
合入#908后跳转键盘行为异常

### ISSUE THREAD

**Issue by MokOopsing** [osfans/trime#913]
**Describe the bug**
合入#908后跳转键盘行为异常，从ascii_mode:0 的键盘跳到 ascii_mode:1 的键盘（英文键盘），再点击按键输入字母，实际会打中文字

**To Reproduce**
Steps to reproduce the bug:
1. 从action 获取最新的包安装后使用
2. 从ascii_mode:0 的键盘跳到 ascii_mode:1 的键盘（英文键盘），再点击按键输入字母

**Expected behavior**
从ascii_mode:0 的键盘跳到 ascii_mode:1 的键盘，可以正常输入字母

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi Mix 4]
 - OS: [e.g. Android 11]
 - Theme: [e.g. Tongwenfeng]
 - Version: [e.g. 3.2.1]
 - Build info: 
   ```
   You could find build info in About Activity and click it to copy.
   e.g. 
   Build: Commit CI
   Date: 2022-06-12 10:09 UTC
   Commit: v3.2.6-58-gd9b4c1f, 2022-06-12 17:58:14 +0800
   Branch: develop
   Repository: https://github.com/osfans/trime
   ```
**Additional context**

**Comment by zbinlin** [comment]
你将 `ascii_mode:1` 的键盘配置里添加上 `reset_ascii_mode: true` 试试

**Comment by WhiredPlanck** [comment]
请看新版本有无此问题。Please take a look for new version.
每夜版/Nigntly Build：https://github.com/osfans/trime/releases/tag/nightly
