### ISSUE TITLE
关于改善swipe触发成功率的建议

### ISSUE THREAD

**Issue by hk3f** [osfans/trime#914]
在滑动输入数字或标点符号的时候，成功率有些低，例如按键p，click设置"p", swipe_up设置“0"，swipe_down设置")"
向上滑成功率高一些，因为滑动到顶部就超出键盘范围了，不会误触发
向下成功率就比较低，因为画出按键P的范围之后就到了L按键区域，较高的概率触发输入L
再比如按键M不管定义swipe_up还是swipe_down都比较容易误触发。
试着调整设置当中的几个滑动参数也不能很好的规避。

建议这个地方是否可以参考googlepinyin的设计，
googlepinyin支持下滑输入
按键P下滑输入"0"，按键L下滑输入")"，
当触发了下滑输入之后，会进入一个锁定状态，
y向不管滑多远都不会触发其他按键，
x方向在左右各2-3个按键范围之内也不会释放，x方向超过3个按键范围则释放
这样可以提高滑动输入的成功率。

![image](https://user-images.githubusercontent.com/2787342/212372589-bd030bcf-26e9-48d0-b314-797bc615e1d7.png)

**Comment by WhiredPlanck** [comment]
滑动和按键悬浮显示目前是半残废的，原因是原来的实现差得不行，所以直接先砍掉了。目前键盘的渲染和显示有比较严重的性能问题，以后大概率是要重构的，因此短期内不会只改善滑动问题。 感谢你的反馈 ～

**Comment by gqqnbig** [comment]
请问目前the action swipe_up有效了吗？

**Comment by gqqnbig** [comment]
我发现了有设置virtual keyboard -> allow swipe gesture。打开后就可以滑行了。
