### ISSUE TITLE
建议加入"刪除誤上屏的錯詞"的功能

### ISSUE THREAD

**Issue by sharp-tasting** [osfans/trime#915]
**Is your feature request related to a problem? Please describe.**
如题, 同文输入法从创立以来一直没有加入"刪除誤上屏的錯詞"的功能. 该功能在小狼毫/鼠须管上面都有, 参见  [刪除誤上屏的錯詞](https://github.com/rime/home/wiki/UserGuide#%E5%88%AA%E9%99%A4%E8%AA%A4%E4%B8%8A%E5%B1%8F%E7%9A%84%E9%8C%AF%E8%A9%9E)

**Describe the solution you'd like**
(1) 在键盘上设立删除自定义词组的热键, 或者

**Describe alternatives you've considered**
(2) 在输入法设置里面加入自造词词典管理功能 (列表, 框选, 多选, 删除)

**Additional context**
(3) 目前由于同文输入法没有此功能, 只能借助电脑鼠须管来回同步, 即: 
手机同文输入法同步→把手机同步文件夹传到电脑→电脑鼠须管同步→电脑鼠须管删词→电脑鼠须管同步→把电脑同步文件夹传到手机→手机同文输入法同步, 
才能删除手机上错误输入的词组. 所以非常希望直接在同文输入法上面删除词汇. 这对于平时不(想)来回多终端同步的用户而言, 很重要

**Comment by sharp-tasting** [comment]
(4) 再补充说明: 直接从手机同步文件夹上把 luna_pinyin.userdb.txt 里找到错词, 然后改 c=-1 然后试图逆向同步是毫无用处的, 因为同步之后错词仍然能打出来, 而且 luna_pinyin.userdb.txt 里相应的 c会重新变成正数

**Comment by 340dt7zw** [comment]
一直有啊，在设置里打开长按删除候选

**Comment by WhiredPlanck** [comment]
@sharp-tasting 请在 app 中打开“键盘设置”，找到“长按删除候选词”，将开关打开。然后回到键盘尝试长按候选词进行删除。

**Comment by sharp-tasting** [comment]
找到了, 多谢!

**Comment by easythd** [comment]
长按删除了候选词后，候选里确实没有了，但打这个输入码，还是能上屏那个错词。。。。好奇怪，重新部署一次也是这样
