### ISSUE TITLE
候选字页面效率太低了、另外希望自带拼音输入、九宫格布局

### ISSUE THREAD

**Issue by pros2021** [osfans/trime#916]
希望能优化安卓手机输入法的这几个点，是我十多年使用国内主流输入法总结的经验，

           
如果可以做到安卓手机上安装后就能输入中文，那么基本就满足90%普通用户的要求了、能让那些讨厌国内流氓输入法的用户 无缝衔接切换到rime。
            另外希望同文输入法，输入中文过程中，希望能显示拼音字母、可以定位到指定位置、删除输错的字母  添加字母。_（如下截图）_。

1. 候选字页面，遇到难的字、查找效率太低，希望能参考主流输入法的页面、整屏的显示和滑动。_（如下截图）_。

2.希望能学习讯飞输入法的经验，提供各大主流输入法的键盘布局选择，来减少用户使用rime同文的不习惯、能无缝切换到同文输入法。    比如提供讯飞键盘布局、搜狗键盘布局、百度输入法键盘布局等。_（如下截图）_。

3. 这点不太重要。。。可以提供九宫格拼音布局（因为好多几亿搜狗用户多年来都是用的九宫拼音、多年形成习惯）。

我找到一个九宫格布局的作者，适配了安卓手机 同文输入法3.2.9以及以下版本（最新的3.2.10适配失效了），推荐给你 可以看看 (https://github.com/SivanLaai/rime-pure )。

![3(1)](https://user-images.githubusercontent.com/77537594/212463044-4be700f5-4edb-478d-9be3-4bf7181c6c3e.jpg)
![4](https://user-images.githubusercontent.com/77537594/212463048-230d0e3a-5920-4117-b86a-a261e2644cac.jpg)

**Comment by WhiredPlanck** [comment]
候选栏设计成和电脑那样翻页，是考虑到有爱好者喜欢用悬浮窗显示候选词，就像电脑上那样。这里有很多屎山，我已经很多次想重构了，但都因种种因素而暂时放弃。
另外同文因为其高度自定义性，现任仓库主要管理者 @Bambooin 说不内置（钦定）任何方案。不过我正在考虑提议内置入 rime 的一些必需文件（https://github.com/rime/rime-prelude ），以降低一些折腾成本。 感谢你的反馈 ～

**Comment by photoe** [comment]
钦定不内置，也可以。————但是前提是要把视频教程做好、做清楚。但是现在的情况是：全网都找不到完整可靠的视频教程。。。

电脑、手机的这个开源输入法，最大的缺点就是没有基础视频教程，直接劝退百分之90的普通用户。很明显这是个程序员思维，没有产品经理辅助、导致没有从用户角度着想 完善教程。

希望完善基础 基础的视频教程！或者内置拼音输入和九宫格。     软件安装好之后，至少得能直接输入拼音，这是基本的。其他小众的人想折腾，就去折腾。大家互不影响。

**Comment by pros2021** [comment]
> 候选栏设计成和电脑那样翻页，是考虑到有爱好者喜欢用悬浮窗显示候选词，就像电脑上那样。这里有很多屎山，我已经很多次想重构了，但都因种种因素而暂时放弃。 另外同文因为其高度自定义性，现任仓库主要管理者 @Bambooin 说不内置（钦定）任何方案。不过我正在考虑提议内置入 rime 的一些必需文件（https://github.com/rime/rime-prelude ），以降低一些折腾成本。 感谢你的反馈 ～

钦定不内置，也可以。————但是前提是要把视频教程做好、做清楚。但是现在的情况是：全网都找不到完整可靠的视频教程。。。

电脑、手机的这个开源输入法，最大的缺点就是没有基础视频教程，直接劝退百分之90的普通用户。很明显这是个程序员思维，没有产品经理辅助、导致没有从用户角度着想 完善教程。

希望完善基础 基础的视频教程！或者内置拼音输入和九宫格。 软件安装好之后，至少得能直接输入拼音，这是基本的。其他小众的人想折腾，就去折腾。大家互不影响。

**Comment by WhiredPlanck** [comment]
@photoe 问就是未来可期 …… 这个项目目前就我一个人在写代码，一个人审核。好多想做的事情没时间整 ……

**Comment by pros2021** [comment]
> @photoe 问就是未来可期 …… 这个项目目前就我一个人在写代码，一个人审核。好多想做的事情没时间整 ……

大佬，可以留下邮箱或者联系方式吗？我可以帮做基础配置视频，

**Comment by Renkai** [comment]
> 候选栏设计成和电脑那样翻页，是考虑到有爱好者喜欢用悬浮窗显示候选词，就像电脑上那样。这里有很多屎山，我已经很多次想重构了，但都因种种因素而暂时放弃。 另外同文因为其高度自定义性，现任仓库主要管理者 @Bambooin 说不内置（钦定）任何方案。不过我正在考虑提议内置入 rime 的一些必需文件（https://github.com/rime/rime-prelude ），以降低一些折腾成本。 感谢你的反馈 ～

-----
支持这个操作, 我直接把鼠须管 ~/Library/Rime 里正常工作的配置复制到同文, 发现还少一些文件, 又从 `/Library/Input Methods/Squirrel.app/Contents/SharedSupport` 拷贝了一些过去才行

**Comment by WhiredPlanck** [comment]
> > @photoe 问就是未来可期 …… 这个项目目前就我一个人在写代码，一个人审核。好多想做的事情没时间整 ……
> 
> 大佬，可以留下邮箱或者联系方式吗？我可以帮做基础配置视频，

你可以直接放链接在这里，没关系的 ～

**Comment by SivanLaai** [comment]
> 候选栏设计成和电脑那样翻页，是考虑到有爱好者喜欢用悬浮窗显示候选词，就像电脑上那样。这里有很多屎山，我已经很多次想重构了，但都因种种因素而暂时放弃。 另外同文因为其高度自定义性，现任仓库主要管理者 [@Bambooin](https://github.com/Bambooin) 说不内置（钦定）任何方案。不过我正在考虑提议内置入 rime 的一些必需文件（https://github.com/rime/rime-prelude ），以降低一些折腾成本。 感谢你的反馈 ～

我是本楼提到的[同文九宫格](https://github.com/SivanLaai/rime-pure)的维护者，我想着可以参与到这个开源项目九宫格这块的工作来，手机端九宫输入法是很多人手机使用的首选方案，，个人觉得九宫格有必要作为一个内置或者预选的九宫格方案，目前同文九宫格我感觉贴合这个需求，同时九宫的方案并入同文仓库可以进一部调整，近期我已经完成了九宫格对于新版本的适配和合并到trime，同时发布了debug整合版本。
