### ISSUE TITLE
liquid_keyboard_window 左侧部分区域无法点击

### ISSUE THREAD

**Issue by deluxghost** [osfans/trime#918]
**Describe the bug**
进入 liquid keyboard 后，现在左上角的 liquid_keyboard_window 会提供一些按钮，这个悬浮窗左侧一点区域无法点击，导致第一个按钮不是很好用

**To Reproduce**
Steps to reproduce the bug:
1. 使用默认的 trime 主题（其他也一样）
2. 点击 符号->更多 按钮进入 liquid keyboard
3. 点击左上角的“空格”按钮的左半部分无效，右半部分有效

**Expected behavior**
消除无法点击的区域

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: 小米 K50u
 - OS: Android12
 - Theme: Trime
 - Version: 3.2.10
 - Build info: 
   ```
   Builder: null
   Build Time: 2023-01-03 16:55 UTC
   Build Version Name: v3.2.10-0-g6098ec72
   Git Hash: 6098ec72
   Git Branch: null
   Git Repo: https://github.com/osfans/trime
   ```
**Additional context**

**Comment by tumuyan** [comment]
确认存在第一个按钮无法点击的问题，可以追溯到3.2.7，可能该功能添加之初就存在bug。
一个挽救的方法是自定义一个空按键到最左侧，这样就可以消除不能点击的影响了。
这个问题理应我来处理，但是我应该在春节后才能去做debug了。
