### ISSUE TITLE
打字、切換方案、使用symbols增加RAM，耗電快

### ISSUE THREAD

**Issue by DaengGWokFook** [osfans/trime#92]
![screenshot_2016-05-20-11-56-11](https://cloud.githubusercontent.com/assets/18633778/15442830/a3dc94ce-1eb1-11e6-987e-4d54dd8206fb.png)
方案都是將電腦預設方案複製到手機，3個自定義方案都是kb級的，產生的bin都是mb級，有無辦法減少ram和佔內存的空間？一般輸入法都是佔20mb左右ram的。

**Comment by osfans** [comment]
慢慢增長的嗎？那可能真有泄漏

**Comment by DaengGWokFook** [comment]
bin文件佔空間好像沒變。佔RAM總是變動，有時20MB，有時100mb，耗電快時肯定超過100mb。

**Comment by xiaoqun2016** [comment]
@DaengGWokFook  
可能跟输入方案有关。  
说一下我这边的情况，以供参考。  
我这边有两个方案，其中一个是table_translator形码方案，反查加固态词典各种bin加起来有50M，算是比较大的方案了，但用的拼写运算很少，平时使用时，内存稳定在30~40M，而且可以动态调整。  
另一个用了script_translator的双拼加辅助码方案，各种bin加起来只有20M，但由于用了辅助码，拼写运算棱镜bin就占了将近12M，使用这个方案时，内存占用明显变大，稍微打一会儿就会升到50M以上，而且有不断上升的趋势。  
像第二种方案那样，我猜测，时间久了，随着用户词典体积增大，内存占用可能会更厉害。由于不常用，暂时无法验证。  
所以，不妨检查一下你的方案有没有用了很多拼写运算，再导出你的用户词典，看看是不是很大？如果确实有这方面的问题，看看能不能优化一下方案？  

其它输入法都是只有一种输入方案，而且是经过开发者不断优化过的，其内存占用尚且那么大。 而Rime是开放的平台，我们不可能毫无限制地使用Rime，又要求它能够无条件地降低内存占用量。我们在定制方案的同时，也要适当考虑优化性能。  
你觉得呢？

**Comment by DaengGWokFook** [comment]
我只選擇三樣方案，放在rime文件夾裏的方案而且沒選取會影響ram嗎？

**Comment by xiaoqun2016** [comment]
没选取不会影响。你可以试试朙月拼音，对比一下，就知道各个方案对内存的影响情况是不同的了。

**Comment by xiaoqun2016** [comment]
想起以前发现的一个现象，~~librime~~  trime可能真有问题。  
当schema中：  

``` yaml
punctuator:
  import_preset: default
```

这时候基本没问题。  
如果是这样：  

``` yaml
punctuator:
  import_preset: symbols
```

使用了扩充的特殊符号或者自定义的其它符号文件，那么每次切换方案，内存有可能会上升3~4M，这是会不断累加的。来回切换十次，可能内存就会升高20M左右。如果你经常要在不同方案间切换，内存占用量不知不觉就会升上去了。  
之所以会怀疑symbols，是因为换回default会好很多。  
我后来是把symbols移到dict.yaml中去了，避开了这个问题，以至于差点忘记了。

**Comment by boboIqiqi** [comment]
这是传说中的内存泄露吗？@osfans 老大好有经验

**Comment by DaengGWokFook** [comment]
@xiaoqun2016 你說對了，轉換方案會累積ram，但是我轉換的方案都是default

**Comment by osfans** [comment]
什麼意思？怎麼轉換？

**Comment by osfans** [comment]
之前好像是部署之後無法回收內存，所以現在改成部署完徹底退出，這樣就可以回收了。

**Comment by DaengGWokFook** [comment]
@osfans 切換輸入方案，例如：粵拼到倉頡，倉頡到注音。ram不斷增加

**Comment by xiaoqun2016** [comment]
@DaengGWokFook 
如果换成symbols，会比default高4~5倍，相比之下，default那一点点已经是可以忽略了。

**Comment by osfans** [comment]
總結一下，切換方案、使用symbols，ram會增加。

**Comment by DaengGWokFook** [comment]
@osfans 對，而且不會減。希望能儘快解決

**Comment by osfans** [comment]
估計不好解，部署佔內存也沒解決。

**Comment by Prcuvu** [comment]
这是trime的问题还是librime的问题？

**Comment by osfans** [comment]
還不清楚，如果電腦上也有這種問題，那就是librime的問題。

**Comment by xiaoqun2016** [comment]
试了一下，小狼毫没有这个问题。

**Comment by DaengGWokFook** [comment]
除了切換方案，還有打字也會增加RAM。現在我在不打字時馬上換回Google輸入法

**Comment by DaengGWokFook** [comment]
這是個大問題，先解決不使用同文輸入法鍵盤時的ram，保持30以下，以後再慢慢解決使用鍵盤時的RAM問題。

**Comment by xiaoqun2016** [comment]
@DaengGWokFook 20160108版及以前的版本，在~~闲置~~切换方案时内存回收效果比较明显，你可以试试。  
~~如果方便的话，可以把你的方案发过来，也许会找到解决这个问题的更多线索。~~

**Comment by DaengGWokFook** [comment]
@xiaoqun2016 你說的舊版本的確對降低ram很有效,可是舊版存在轉屏崩潰問題

**Comment by osfans** [comment]
降低打字時的ram，還是切換方案時的ram？

**Comment by DaengGWokFook** [comment]
@osfans 不論哪個ram降低都是有益的,都能減少死機頻率和耗電率.

**Comment by xiaoqun2016** [comment]
@DaengGWokFook  试试8号的新版，已经改善很多。

**Comment by DaengGWokFook** [comment]
@xiaoqun2016 的確有效，現在ram幾乎限制於20mb以下了，謝了

**Comment by osfans** [comment]
這麼好？這個是librime的泄漏，老大解了，我就直接導入進來了。
