### ISSUE TITLE
3.2.10 拉起键盘时，候选栏的开关没有正常显示，反而显示了“展开候选”按钮

### ISSUE THREAD

**Issue by deluxghost** [osfans/trime#923]
设置里面“每页显示候选词数量”为“不超出候选栏”

我的输入方案使用了候选栏的开关，用来切换中英/简繁，正常拉起键盘时，应该显示成这样：

![photo_6210776375535710333_x](https://user-images.githubusercontent.com/5835759/212831893-af93e2c9-d26f-495e-b18b-8f4fccbe4407.jpg)

但偶尔会没有开关显示，只有一个展开候选按钮：

![photo_6210776375535710332_x](https://user-images.githubusercontent.com/5835759/212831860-10d4d5de-640f-45e1-a8ff-96ed4e867ce9.jpg)

**Comment by JieHao258** [comment]
是的，期待适配安卓13，候选显示能正常

**Comment by WhiredPlanck** [comment]
请看新版本有无此问题。Please take a look for new version.
每夜版/Nigntly Build：https://github.com/osfans/trime/releases/tag/nightly
