### ISSUE TITLE
[Dev] Debug build mode slow down the native codes performance

### ISSUE THREAD

**Issue by WhiredPlanck** [osfans/trime#926]
@Bambooin Some users have complained the speed of deployment is very slow since v3.2.x released. After some investigation, I found that this has a lot to do with the fact that we used the debug build variant. In the debug build mode, CMake compiles the native codes with the `Debug` build type, which slows down native code performance. We need to compile the native codes with `RelWithDebInfo` build type (the default CMake build type in the release build variant) to make the performance be normal.

**Comment by wxyzh** [comment]
Maybe Can add `set(CMAKE_BUILD_TYPE RelWithDebInfo) ` after [set(CMAKE_CXX_STANDARD 14)](https://github.com/osfans/trime/blob/0943b3010d703738a3daa1c47b8740e25bf333a8/app/src/main/jni/CMakeLists.txt#L6)
