### ISSUE TITLE
Android 13 LineageOS无法显示侯选词

### ISSUE THREAD

**Issue by bigzhu** [osfans/trime#928]
**Describe the bug**
如图, 侯选词页无法显示出来

**Screenshots**
![2023-01-29 12 54 08](https://user-images.githubusercontent.com/489815/215305692-0ab13125-7019-4eb6-acf3-099448e95d84.jpg)

**Smartphone (please complete the following information):**
 - Device: [One plus 5T]
 - OS: [Android 13]
 - Version: [LineageOS 20]
 - Build info: 
   ```
   You could find build info in About Activity and click it to copy.
   e.g. 
   Build: Commit CI
   Date: 2022-06-12 10:09 UTC
   Commit: v3.2.6-58-gd9b4c1f, 2022-06-12 17:58:14 +0800
   Branch: develop
   Repository: https://github.com/osfans/trime
   ```
**Additional context**

**Comment by JieHao258** [comment]
是的，解决了吗？这个问题好久了，一直是还存在着

**Comment by Steven52065** [comment]
安卓13
努比亚Z50
同样有这个问题
弄了一下午+一晚上...也没弄好

**Comment by JieHao258** [comment]
你是自己编译？我类原生13也是这个问题，显示不出

**Comment by 4SM** [comment]
这个现在没法用。暂时用 gboard。等更新吧。

**Comment by easythd** [comment]
三星s20fe，安卓13，同文3.29，一切正常

**Comment by Bambooin** [comment]
Please uprade your Trime to latest release and verify again.
