### ISSUE TITLE
无法设定自动上屏、自动清屏等重要功能

### ISSUE THREAD

**Issue by fofc12** [osfans/trime#93]
在使用外接键盘打字的过程中，
    auto_select_unique_candidate: false  # 无重码**自动上屏**
    auto_clear: auto    #错码**自动清除**
这两项其中一项加入speller中后，就会使输入法不可用了，但是据说好像PC上的可以。。。而这两个功能对于一个五笔用户来讲又是至关重要的。。。所以无法设置非常致命，又没有找到好的替代方法。

此外，ctrl+a键是可用的，但ctrl+z**撤消**似乎不可用，而万一**错打多字词组**的时候，要按退格键删半天。

另外，如果可以有shift+方向键选择，还有复制粘贴的快捷键，我想手机就可以很大程度代替电脑了。

同文是我在手机上最喜欢的输入法，以上是我发现的问题，希望可以得到解决，衷心愿同文越好。

**Comment by boboIqiqi** [comment]
学习，以前都不知道有这些设置

**Comment by osfans** [comment]
是只有外接鍵盤有問題嗎？應該跟PC上一樣的。

**Comment by xiaoqun2016** [comment]
- 自动上屏可直接设置`speller/auto_select` 和 `speller/max_code_length` ，不需要`auto_select_unique_candidate`  
- 自动清屏用法可参考这个issue rime/librime#60。  
  
  以上在新版中测试有效。  
- Ctrl+A与Ctrl+Z的问题可合并入#81 **外接键盘组合键** 讨论。
