### ISSUE TITLE
横屏没办法阻止全屏编辑模式

### ISSUE THREAD

**Issue by leehaoxindehao** [osfans/trime#930]
使用平板或者手机横屏，会进入全屏编辑模式，没办法关掉

**Comment by leehaoxindehao** [comment]
在软件的键盘设置里，关掉也不起作用

**Comment by leehaoxindehao** [comment]
@osfans

**Comment by cabins** [comment]
为啥这个问题没有人处理？

**Comment by cabins** [comment]
这个问题我好像定位到原因了。

app/src/main/java/com/osfans/trime/ime/landscapeinput/LandscapeInputUIMode.kt

这个文件里，初始化map的时候，并没有往里面放内容，所以导致后面查询到的永远是`AUTO_SHOW`这个默认值。如下：
```
package com.osfans.trime.ime.landscapeinput

import java.util.Locale
import kotlin.collections.HashMap

enum class LandscapeInputUIMode {
    AUTO_SHOW,
    ALWAYS_SHOW,
    NEVER_SHOW,
    ;

    companion object {
        private val convertMap: HashMap<String, LandscapeInputUIMode> = hashMapOf()

        fun fromString(mode: String): LandscapeInputUIMode {
            val type = convertMap[mode.uppercase(Locale.getDefault())]
            return type ?: AUTO_SHOW
        }
    }
}
```

所以解决方案应该是将初始化的值补充完整。比如：
```
package com.osfans.trime.ime.landscapeinput

import java.util.Locale
import kotlin.collections.HashMap

enum class LandscapeInputUIMode {
    AUTO_SHOW,
    ALWAYS_SHOW,
    NEVER_SHOW;

    companion object {
        private val convertMap: HashMap<String, LandscapeInputUIMode> = hashMapOf()
        init {
            convertMap["AUTO_SHOW"] = AUTO_SHOW
            convertMap["ALWAYS_SHOW"] = ALWAYS_SHOW
            convertMap["NEVER_SHOW"] = NEVER_SHOW
        }

        fun fromString(mode: String): LandscapeInputUIMode {
            val type = convertMap[mode.uppercase(Locale.getDefault())]
            return type ?: AUTO_SHOW
        }
    }
}
```


我自己本地测试了下，这样的修改应该是生效的。但我的代码水平……实在一般，所以不确定这样写是否是最优的（大概率不是，我写的时候甚至还需要去搜索kotlin的语法）。所以希望大佬们，能够把这里的代码优化一下。

@tumuyan @Bambooin @goofyz

**Comment by cabins** [comment]
AI建议我把伴生对象里面的那一句换成

```private val convertMap: Map<String, LandscapeInputUIMode> = LandscapeInputUIMode.values().associateBy { it.name }```

^_^

**Comment by goofyz** [comment]
不太明白問題所在。有截圖看看嗎？

**Comment by cabins** [comment]
大概意思就是，不论Trime的设置中，这个开关选择哪个选项（即便是〔从不〕）

![Screenshot_20231124_090030](https://github.com/osfans/trime/assets/2500123/c9817e78-0c36-4f2c-bd5a-f295923fc0a7)


![Screenshot_20231124_090035](https://github.com/osfans/trime/assets/2500123/4b3a82d2-2c10-4384-9ce6-c9a346a6ad77)


光标进入到横屏的输入框里的时候，都会进入到下面的全屏编辑模式：

![Screenshot_20231124_090047](https://github.com/osfans/trime/assets/2500123/88fb57e9-1ef5-4d74-b21b-ebf0c7bc5ec9)

@goofyz

**Comment by cabins** [comment]
代码上看的话，Trime.java文件的这个方法获取到的case结果永远都是AUTO_SHOW
![图片](https://github.com/osfans/trime/assets/2500123/c5f0a69d-80dc-43b8-9876-8d82435552cc)

跟下去AppPrefs.kt中
![图片](https://github.com/osfans/trime/assets/2500123/05968648-a163-436b-b6fe-73bcc39e5081)

这部分，在get()的时候，获取的结果是错误的，再往下跟，就是我上面说的那个空的map了。

**Comment by goofyz** [comment]
明白。試了改一下，可以拿到正確的值了。不過 keyboard 大小變得好奇怪，不肯定是否我的 keyboard 方案問題。

**Comment by quxian4869** [comment]
@cabins 您好，我在按您的方法尝试重新打包程序的时候总是出错，请问该怎么解决呀

![image](https://github.com/user-attachments/assets/979cfab1-db55-4df9-ae76-9e6638b52bdd)
