### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by chwt163** [osfans/trime#933]
首先非常感谢开源作者的无私奉献。
1，首页的play和酷安链接，点进去还是旧版本？难怪我年前装了几次都无法使用。
2，现在的主题外观会吓跑大多数的新用户，建议参考fcitx的主题做几个，现在的主题列表太长而且没有预览，找半天也没有顺眼的。
3，把双拼和其他支持的输入法都打包进apk吧，这些事情真的不适合新手。
4，进入剪贴板和其他功能之后，要滑动较长距离才出现返回按钮，建议把返回按钮固定在左侧或者右侧。
5，要是能支持九宫格和笔画输入就更好了。
![Screenshot_20230206_163400](https://user-images.githubusercontent.com/70951194/216923676-31a8a226-898d-4f48-a0f0-c37502726ace.jpg)

**Comment by yanhuacuo** [comment]
做好稳定性和功能平移就不错了，同文的传播，主要还是靠不同的使用者小群体内部传帮带，集成就太臃肿了，内置n多方案，跟风大厂做一站式体验，以期获取「新用户」，根本不现实。

**Comment by Wenti-D** [comment]
以 RIME 为基础的输入法主打的应该都类似于「自己动手，丰衣足食」的概念，想要什么输入方式，去 [「東風破」](https://github.com/rime/plum) 找找然后自己添上便是。另外，现在的维护者似乎意识到了键盘在很多方面存在问题，想重构但老是鸽。

**Comment by chwt163** [comment]
linux和windows上我用了很长时间的rime，配置好了确实很好用，但现在已经不太想折腾了，对于大多数人来讲，更想要的也是开箱即用。
https://github.com/SivanLaai/rime-pure/releases
这里有个集成包，两位作者能不能沟通合并一下？

**Comment by Bambooin** [comment]
You can try this: https://github.com/Bambooin/rimerc

**Comment by sls1005** [comment]
不如把「東風破」整合進來，以免還要依賴 Termux 這種終端模擬器才能用 plum。
