### ISSUE TITLE
同文输入法无法显示候选词

### ISSUE THREAD

**Issue by Nie2048** [osfans/trime#934]
**Describe the bug**
输入法不能显示候选次（如图）
![Screenshot_2023-02-08-10-33-42-341_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/59966980/217414226-adb5a258-3697-4459-962a-e2e38c1f29c3.jpg)

**logs**
2023/02/08-10:27:24.410187 77e733e4f8 Recovering log #84
2023/02/08-10:27:24.410651 77e733e4f8 Level-0 table #86: started
2023/02/08-10:27:24.418118 77e733e4f8 Level-0 table #86: 162 bytes OK
2023/02/08-10:27:24.475329 77e733e4f8 Delete type=0 #84
2023/02/08-10:27:24.479622 77e733e4f8 Delete type=3 #83
2023/02/08-10:27:24.484537 7724196cb0 Compacting 4@0 + 0@1 files
2023/02/08-10:27:24.496746 7724196cb0 Generated table #88@0: 8 keys, 293 bytes
2023/02/08-10:27:24.496814 7724196cb0 Compacted 4@0 + 0@1 files => 293 bytes
2023/02/08-10:27:24.500573 7724196cb0 compacted to: files[ 0 1 0 0 0 0 0 ]
2023/02/08-10:27:24.502595 7724196cb0 Delete type=2 #20
2023/02/08-10:27:24.507855 7724196cb0 Delete type=2 #5
2023/02/08-10:27:24.524164 7724196cb0 Delete type=2 #65
2023/02/08-10:27:24.531546 7724196cb0 Delete type=2 #86

**Smartphone (please complete the following information):**
 - Device: 红米k50 至尊版
 - OS: 安卓13   MIUI14.0.5.0(升级MIUI14之后才出行的问题)
 ![Screenshot_2023-02-08-10-39-57-165_com.osfans.trime.jpg](https://user-images.githubusercontent.com/59966980/217414915-ae6a5d55-61ab-429a-953d-12a17c8218fe.jpg)

**Comment by tylinux** [comment]
Android  13 需要使用新版本，Google Play 里的版本比较老，可以从 Github Release下载。

**Comment by Nie2048** [comment]
> Android 13 需要使用新版本，Google Play 里的版本比较老，可以从 Github Release下载。

好的！！  解决了，谢谢大佬。  我还以为Google Play 里是最新的
