### ISSUE TITLE
更新MIUI14后没有候选字框了

### ISSUE THREAD

**Issue by yansir2022** [osfans/trime#936]
**Describe the bug**

**To Reproduce**
Steps to reproduce the bug:
4. See bug

**Expected behavior**

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi Mix 4]
 - OS: [e.g. Android 11]
 - Theme: [e.g. Tongwenfeng]
 - Version: [e.g. 3.2.1]
 - Build info: 
   ```
   You could find build info in About Activity and click it to copy.
   e.g. 
   Build: Commit CI
   Date: 2022-06-12 10:09 UTC
   Commit: v3.2.6-58-gd9b4c1f, 2022-06-12 17:58:14 +0800
   Branch: develop
   Repository: https://github.com/osfans/trime
   ```
**Additional context**

**Comment by Bambooin** [comment]
Same with #928
