### ISSUE TITLE
After Android 13 update, no candidate display | can't swap keyboards directly?

### ISSUE THREAD

**Issue by kori228** [osfans/trime#939]
**Describe the bug**
After the recent Android software update, the candidate characters for input are no longer displayed. Tested with Yunlong IPA and Cantonese Jyutping input. Also don't see the option to swap from Yunlong to Jyutping directly. 

**To Reproduce**
Steps to reproduce the bug:
1. Update to Android 13
2. Install custom schemas Yunlong IPA or Jyutping

**Expected behavior**
Candidates should show up as you type. 

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**
[To be added](https://imgur.com/a/VAvqccJ)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A51
 - OS: Android 13
 - Theme: 
 - Version: 1.5.3?
 - Build info: 
   ```
   You could find build info in About Activity and click it to copy.
   e.g. 
   Build: Commit CI
   Date: 2022-06-12 10:09 UTC
   Commit: v3.2.6-58-gd9b4c1f, 2022-06-12 17:58:14 +0800
   Branch: develop
   Repository: https://github.com/osfans/trime
   ```
**Additional context**

**Comment by Bambooin** [comment]
See #928
