### ISSUE TITLE
宣傳視頻

### ISSUE THREAD

**Issue by osfans** [osfans/trime#94]
@xiaoqun2016 要不要做個宣傳視頻，或者就用上次的教程視頻？
發給2016年输入法表演与讨论会，qq 邮箱1047771050

 @boboIqiqi

**Comment by xiaoqun2016** [comment]
重新做一个好点的宣传视频吧。先想想要表达的重点，列个大纲，再具体实现。  
文案和美工我也不专业，大家一起开脑洞吧。 @boboIqiqi

**Comment by boboIqiqi** [comment]
不好意思，今天才看到。

对输入法大会不太了解，不知道他们具体有什么要求呀？

不过不管怎么说，可以借这个机会，整理一下我们对产品的定位和主打的优势。
想想我们有什么亮点。
我先自己说说

## 内核使用LibRime

完全Rime化定制，与PC各操作统一平台，统一方案和配置
对Rime用户会比较有吸引力

## 可以定制键盘

这个是对我吸引力最大的。
我一直想把我的密码什么的做成一个键，方便输入，不过也没实现
还想做一个Markdown专用的键盘。方便在手机输入Markdown那些符合

如果时间充裕，我们可以让菜鸟群里的网码们把个自的键盘截个图晒出来。
这样，可以录一个简短的片断，展示一下这个优势。
有各种各样的键盘。我看群里有定制的双拼方案特别多

## 支持语音输入

虽然，这个目前还不完善，但是对我来说，是很有吸引力的。
因为，我在手机上不太喜欢打太多字，打多了手指会难受（职业病了）
所以，我特别希望咱们的语音输入可以完善一下。
提供界面什么的。
我见过苹果的语音，交互方面比讯飞做得好一些。
就是，输入完一句话后，有些字词识别得不确定，点击后，可以给出候选字进行修改。
这个就比较人性化了。

## 支持各种小众、自定义输入方案

@xiaoqun2016 小琴的郑码
还有QQ菜鸟群里，他们讨论的乱十七笔画什么的
支持自定义 

## 未来，开发中的ppt产品
- 可以考虑把密码管理KeePass加上。
- 可以考虑把我的吉他输入模式加上

我以前给老大@osfans 发过一个小视频。
主要就是适合，大屏手机和平板。用单手的五个手机进行盲打。
还是采手PC上的指法，左手的键位对应到右手对应的手指。
也相当于双键方案，但是是单手操作。

我觉得咱们可以建一个QQ讨论组，有空就讨论讨论

@xiaoqun2016 小琴，好久不见了。貌似大家最近都比较忙了。

**Comment by osfans** [comment]
暫時關閉
