### ISSUE TITLE
[BUG] 草稿功能不能停用

### ISSUE THREAD

**Issue by easythd** [osfans/trime#941]
如题，在app其它设置的草稿箱这里，把草稿箱历史记录上限这项设置为停用，但停用不起作用，仍然在流式键盘上的草稿中，还继续有20条草稿不断记录

**Comment by WhiredPlanck** [comment]
@easythd 请留意一下这些草稿的内容是否有更新。设置里的停用只是自停用时刻起不再记录草稿，但是之前留下的记录不会自动删除。

**Comment by easythd** [comment]
有，一直在更新，我特意试了。其它就是启用状态。
