### ISSUE TITLE
3.2.11部署成功，键盘出不来

### ISSUE THREAD

**Issue by hyaray** [osfans/trime#946]
如题，都是`releases`下载的，怎么会`签名不一致`呢？
另外，`3.2.11`安装后，部署能成功，但是始终无法出现键盘，回到`3.2.10`就正常

**Comment by wxyzh** [comment]
已知如果switchs中有options时会拉不出键盘

**Comment by hyaray** [comment]
这个没有，但还是出不来。折腾了

**Comment by siuze** [comment]
有同样问题，部署后点击任意输入框调不出键盘，且trime debug版本闪退，release版本跳转如软件内提示崩溃。

3.2.10正常。但是两版本均存在部署时候非预期的闪退，需要多次重新进入点击部署才能显示部署成功相关提示框。

使用方案：
[ShanRenMaLTS.zip](https://github.com/osfans/trime/files/10892565/ShanRenMaLTS.zip)

崩溃日志：
[com.osfans.trime-2023-03-05T18_32_11Z.txt](https://github.com/osfans/trime/files/10892628/com.osfans.trime-2023-03-05T18_32_11Z.txt)

**Comment by WhiredPlanck** [comment]
请看新版本有无此问题。Please take a look for new version.
每夜版/Nigntly Build：https://github.com/osfans/trime/releases/tag/nightly
