### ISSUE TITLE
顯示滑動輸入碼

### ISSUE THREAD

**Issue by DaengGWokFook** [osfans/trime#95]
O keyboard 的鍵盤佈局值得參考，下圖是預設的日文佈局之一。
![screenshot_2016-06-25-22-24-55](https://cloud.githubusercontent.com/assets/18633778/16363268/aa1a767c-3b93-11e6-93fc-a99341b1b499.png)
按shift轉換平假片假
![screenshot_2016-06-26-11-38-11](https://cloud.githubusercontent.com/assets/18633778/16363272/ba2f4c22-3b93-11e6-84c2-eb4093ee415f.png)
這樣做就一鍵十個標籤了，之前我在rime/home提到輸入碼不限制就是想減少標籤。

**Comment by Bambooin** [comment]
过时的 issue
