### ISSUE TITLE
运行action是否需要设置相关环境变量？

### ISSUE THREAD

**Issue by siuze** [osfans/trime#950]
我将项目fork之后尝试运行action，运行make debug步骤时报错，详见https://github.com/siuze/trime/actions/runs/4335037169/jobs/7569323908

是哪些变量没设置好吗？

项目fork后未提交过改动

**Comment by wxyzh** [comment]
fork整个仓库呢？

**Comment by siuze** [comment]
将所有branch都fork后问题解决

**Comment by siuze** [comment]
排查了一下发现不是分支的原因，是我fork之后update了所有子模块，相当一部分子模块更新后的文件改动造成编译失败，回退子模块版本即可

**Comment by wxyzh** [comment]
注意下 librime-luadep
