### ISSUE TITLE
冒号始终输出西文冒号

### ISSUE THREAD

**Issue by seff** [osfans/trime#958]
无论是中文还是西文、全角还是半角输入状态下，冒号始终输出西文冒号。

**Comment by amalgame21** [comment]
I can also reproduce that in v3.2.11, but not in v3.2.9.

**Comment by HashLiver** [comment]
感叹号和问号也是

**Comment by Wenti-D** [comment]
这个问题在3.2.10是正常的，但自3.2.11开始就有了，很怪。

**Comment by jim-kirisame** [comment]
同，包括感叹号、省略号等其他符号也是输出西文符号，但句号等能正常输出中文符号。

**Comment by WhiredPlanck** [comment]
请看新版本有无此问题。Please take a look for new version.
每夜版/Nigntly Build：https://github.com/osfans/trime/releases/tag/nightly
