### ISSUE TITLE
3.2.11配置文件失效，无法部署，一切键盘就闪退

### ISSUE THREAD

**Issue by atlanticfirst** [osfans/trime#959]
之前一更新就会崩溃，但卸载重新安装就好了。但这次不管怎么重装一打开就闪退，大佬能不能帮忙看下是什么原因.......

--------- beginning of crash
E/AndroidRuntime(17193): FATAL EXCEPTION: main
E/AndroidRuntime(17193): Process: com.osfans.trime, PID: 17111
E/AndroidRuntime(17193): android.view.InflateException: Binary XML file line #14 in com.osfans.trime:layout/input_root: Binary XML file line #16 in com.osfans.trime:layout/tab_bar: Error inflating class com.osfans.trime.ime.symbol.TabView
E/AndroidRuntime(17193): Caused by: android.view.InflateException: Binary XML file line #16 in com.osfans.trime:layout/tab_bar: Error inflating class com.osfans.trime.ime.symbol.TabView
E/AndroidRuntime(17193): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(17193): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
E/AndroidRuntime(17193): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/AndroidRuntime(17193): 	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
E/AndroidRuntime(17193): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
E/AndroidRuntime(17193): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
E/AndroidRuntime(17193): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
E/AndroidRuntime(17193): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/AndroidRuntime(17193): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
E/AndroidRuntime(17193): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/AndroidRuntime(17193): 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
E/AndroidRuntime(17193): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
E/AndroidRuntime(17193): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/AndroidRuntime(17193): 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
E/AndroidRuntime(17193): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
E/AndroidRuntime(17193): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/AndroidRuntime(17193): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
E/AndroidRuntime(17193): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
E/AndroidRuntime(17193): 	at com.osfans.trime.databinding.InputRootBinding.inflate(InputRootBinding.java:51)
E/AndroidRuntime(17193): 	at com.osfans.trime.databinding.InputRootBinding.inflate(InputRootBinding.java:45)
E/AndroidRuntime(17193): 	at com.osfans.trime.ime.core.Trime.onCreateInputView(Trime.java:723)
E/AndroidRuntime(17193): 	at android.inputmethodservice.InputMethodService.updateInputViewShown(InputMethodService.java:2075)
E/AndroidRuntime(17193): 	at android.inputmethodservice.InputMethodService.prepareWindow(InputMethodService.java:2646)
E/AndroidRuntime(17193): 	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:2575)
E/AndroidRuntime(17193): 	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:923)
E/AndroidRuntime(17193): 	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInputWithToken(InputMethodService.java:897)
E/AndroidRuntime(17193): 	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:232)
E/AndroidRuntime(17193): 	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
E/AndroidRuntime(17193): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(17193): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(17193): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(17193): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(17193): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17193): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(17193): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(17193): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Integer com.osfans.trime.data.theme.Config$Colors.getColor(java.lang.String)' on a null object reference
E/AndroidRuntime(17193): 	at com.osfans.trime.ime.symbol.TabView.reset(TabView.java:61)
E/AndroidRuntime(17193): 	at com.osfans.trime.ime.symbol.TabView.<init>(TabView.java:95)
E/AndroidRuntime(17193): 	... 34 more
E/CustomActivityOnCrash(17193): App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
E/CustomActivityOnCrash(17193): android.view.InflateException: Binary XML file line #14 in com.osfans.trime:layout/input_root: Binary XML file line #16 in com.osfans.trime:layout/tab_bar: Error inflating class com.osfans.trime.ime.symbol.TabView
E/CustomActivityOnCrash(17193): Caused by: android.view.InflateException: Binary XML file line #16 in com.osfans.trime:layout/tab_bar: Error inflating class com.osfans.trime.ime.symbol.TabView
E/CustomActivityOnCrash(17193): Caused by: java.lang.reflect.InvocationTargetException
E/CustomActivityOnCrash(17193): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
E/CustomActivityOnCrash(17193): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/CustomActivityOnCrash(17193): 	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
E/CustomActivityOnCrash(17193): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
E/CustomActivityOnCrash(17193): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
E/CustomActivityOnCrash(17193): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
E/CustomActivityOnCrash(17193): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/CustomActivityOnCrash(17193): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
E/CustomActivityOnCrash(17193): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/CustomActivityOnCrash(17193): 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
E/CustomActivityOnCrash(17193): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
E/CustomActivityOnCrash(17193): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/CustomActivityOnCrash(17193): 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
E/CustomActivityOnCrash(17193): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
E/CustomActivityOnCrash(17193): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/CustomActivityOnCrash(17193): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
E/CustomActivityOnCrash(17193): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
E/CustomActivityOnCrash(17193): 	at com.osfans.trime.databinding.InputRootBinding.inflate(InputRootBinding.java:51)
E/CustomActivityOnCrash(17193): 	at com.osfans.trime.databinding.InputRootBinding.inflate(InputRootBinding.java:45)
E/CustomActivityOnCrash(17193): 	at com.osfans.trime.ime.core.Trime.onCreateInputView(Trime.java:723)
E/CustomActivityOnCrash(17193): 	at android.inputmethodservice.InputMethodService.updateInputViewShown(InputMethodService.java:2075)
E/CustomActivityOnCrash(17193): 	at android.inputmethodservice.InputMethodService.prepareWindow(InputMethodService.java:2646)
E/CustomActivityOnCrash(17193): 	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:2575)
E/CustomActivityOnCrash(17193): 	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:923)
E/CustomActivityOnCrash(17193): 	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInputWithToken(InputMethodService.java:897)
E/CustomActivityOnCrash(17193): 	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:232)
E/CustomActivityOnCrash(17193): 	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
E/CustomActivityOnCrash(17193): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/CustomActivityOnCrash(17193): 	at android.os.Looper.loopOnce(Looper.java:201)
E/CustomActivityOnCrash(17193): 	at android.os.Looper.loop(Looper.java:288)
E/CustomActivityOnCrash(17193): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/CustomActivityOnCrash(17193): 	at java.lang.reflect.Method.invoke(Native Method)
E/CustomActivityOnCrash(17193): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/CustomActivityOnCrash(17193): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/CustomActivityOnCrash(17193): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Integer com.osfans.trime.data.theme.Config$Colors.getColor(java.lang.String)' on a null object reference
E/CustomActivityOnCrash(17193): 	at com.osfans.trime.ime.symbol.TabView.reset(TabView.java:61)
E/CustomActivityOnCrash(17193): 	at com.osfans.trime.ime.symbol.TabView.<init>(TabView.java:95)
E/CustomActivityOnCrash(17193): 	... 34 more
E/CustomActivityOnCrash(17193): Failed when resolving the restart activity class via getLaunchIntentForPackage, stack trace follows!
E/CustomActivityOnCrash(17193): java.lang.ClassNotFoundException: com.osfans.trime.PrefLauncherAlias
E/CustomActivityOnCrash(17193): 	at java.lang.Class.classForName(Native Method)
E/CustomActivityOnCrash(17193): 	at java.lang.Class.forName(Class.java:454)
E/CustomActivityOnCrash(17193): 	at java.lang.Class.forName(Class.java:379)
E/CustomActivityOnCrash(17193): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.getLauncherActivity(CustomActivityOnCrash.java:648)
E/CustomActivityOnCrash(17193): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.guessRestartActivityClass(CustomActivityOnCrash.java:602)
E/CustomActivityOnCrash(17193): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.lambda$install$0(CustomActivityOnCrash.java:177)
E/CustomActivityOnCrash(17193): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash$$ExternalSyntheticLambda0.uncaughtException(Unknown Source:2)
E/CustomActivityOnCrash(17193): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
E/CustomActivityOnCrash(17193): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
E/CustomActivityOnCrash(17193): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
E/CustomActivityOnCrash(17193): Caused by: java.lang.ClassNotFoundException: com.osfans.trime.PrefLauncherAlias
E/CustomActivityOnCrash(17193): 	... 10 more
I/Process (17193): Sending signal. PID: 17111 SIG: 9

**Comment by wxyzh** [comment]
需要提供主题文件

**Comment by atlanticfirst** [comment]
是不是因为我是在老的主题基础上改的，所以才会出现兼容问题啊？有办法在自己的主题的基础上调用其他主题的键盘吗？

**Comment by wxyzh** [comment]
有可能是symbols文件的问题

**Comment by WhiredPlanck** [comment]
请看新版本有无此问题。Please take a look for new version.
每夜版/Nigntly Build：https://github.com/osfans/trime/releases/tag/nightly
