### ISSUE TITLE
升级到3.2.11 以后 打不出简体字了，输入方案配置文件一个都没变，打出来的都是繁体字，简繁切换开关换来换去都一样

### ISSUE THREAD

**Issue by FanXiangTM** [osfans/trime#960]
**Describe the bug**

**To Reproduce**
Steps to reproduce the bug:
4. See bug

**Expected behavior**

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi Mix 4]
 - OS: [e.g. Android 11]
 - Theme: [e.g. Tongwenfeng]
 - Version: [e.g. 3.2.1]
 - Build info: 
   ```
   You could find build info in About Activity and click it to copy.
   e.g. 
   Build: Commit CI
   Date: 2022-06-12 10:09 UTC
   Commit: v3.2.6-58-gd9b4c1f, 2022-06-12 17:58:14 +0800
   Branch: develop
   Repository: https://github.com/osfans/trime
   ```
**Additional context**

**Comment by WhiredPlanck** [comment]
´_>` 你的方案是什么？你的设备信息是什么 ……？关键信息你是一个也不给啊 …… 怎么帮你判断呢 ？

**Comment by FanXiangTM** [comment]
> ´_>` 你的方案是什么？你的设备信息是什么 ……？关键信息你是一个也不给啊 …… 怎么帮你判断呢 ？

输入方案是朙月拼音，设备型号是 华为novia 5i 其它信息因为程序没有崩溃所以不知道在哪里看Log

**Comment by wxyzh** [comment]
优先检查opencc相关的配置和文件

**Comment by ngedwin** [comment]
我也有同樣問題，我是速成方案
一樣是之前版本正常，新買了手機把最新輸入法安裝後就發覺不能打簡體字了

**Comment by WhiredPlanck** [comment]
@FanXiangTM @ngedwin 两位检查一下**共享目录**下的 opencc 文件夹，看看有没有 .ocd/.ocd2 结尾的文件。

**Comment by atmouse-** [comment]
https://github.com/Bambooin/rimerc
我用这个 rimerc在 3.2.11 就无法使用，回退到 3.2.10 就正常。

题外话:我认为大多数人用的rc失效时很致命的。单元测试应该做起来

**Comment by Alozxy** [comment]
> @FanXiangTM @ngedwin 两位检查一下**共享目录**下的 opencc 文件夹，看看有没有 .ocd/.ocd2 结尾的文件。

似乎deploy以后不会自动生成ocd文件

**Comment by WhiredPlanck** [comment]
此问题已在 f215633 修复。
