### ISSUE TITLE
语音输入识别出错

### ISSUE THREAD

**Issue by amperexia** [osfans/trime#97]
在trime中调用语音输入，会识别出一长串重复的字符串，比如语音输入“测试”，上屏结果显示"測試策士柵柵側室測室"。何解？

**Comment by osfans** [comment]
複製不出來，默認不是選擇的訊飛語音？

**Comment by amperexia** [comment]
安装了讯飞语记。在系统设置里的默认语音识别引擎只能选择Google，改不了，是这个原因吗？

**Comment by osfans** [comment]
應該是這個原因，所以你默認沒有選到訊飛。訊飛語記中有個什麼識別能力。

**Comment by amperexia** [comment]
确认是这个原因。在手机设置的“辅助应用和语音输入”里要把“辅助应用”切换成“无”，下面才会出现更改“语音输入”为讯飞语记的选项。之前辅助应用设置成Goolge所以切换不了默认语音引擎。

**Comment by osfans** [comment]
現在好了？所以谷歌默認的有問題？

**Comment by xiaoqun2016** [comment]
@amperexia 某些第三方的辅助服务会导致随机的语音朗读问题，已知的有绿色守护：  
![2016-08-06 07 47 14](https://cloud.githubusercontent.com/assets/16501929/17453217/d0161ee8-5b3d-11e6-97d9-8e3f903eb939.png)

那么会不会有某些辅助服务会导致随机的语音识别问题？    
可以重点检查一下手机的运行环境，比如语音反馈、辅助服务等等，关掉这些功能，估计就正常了

**Comment by osfans** [comment]
暫時關閉，有問題再開。
