### ISSUE TITLE
真心佩服。硬生生把同文给搞砸了！

### ISSUE THREAD

**Issue by 4SM** [osfans/trime#979]
1. 卸载同文。
2. 删除 rime 文件夹。
3. 安装同文。
4. 复制 double_pinyin_flypy.custom 等文件到 Android rime 文件夹。
5. 够纯净了吧？照样：报！错！

您硬生生将一个成品，变成了半成品！。佩服，佩服！

**Comment by MokOopsing** [comment]
你大可不必追太新的版本，哪个版本你觉得好用就用哪个不就好了

**Comment by Rovever** [comment]
我用3.2.1好多年了一直很稳，现在安卓12。目前新版本明显是大改中有bug很正常，打包的都是debug

**Comment by wxyzh** [comment]
目前整个项目都在重构中，有bug是不可避免的。
反馈时最好按照要求，提供设备信息和日志文件。

**Comment by WhiredPlanck** [comment]
´_>` 我再说一遍，我的精力有限，写的代码有时进步有时退步。阁下要是有精力出言不逊，不如想想办法帮忙贡献代码或者提供一下日志等信息以供调查原因。

如果你以上都无法做到，可考虑使用旧版本，或出门右转看看[小企鹅输入法](https://github.com/fcitx5-android/fcitx5-android)。

还有我想强调一下，GitHub 的 Issue 是**用来反馈问题**的，**不是用来发泄情绪**的。这样毫无作用的无能狂怒对软件功能和维护状况的改进可以说微乎其微，因为我不是全职搞开源的人。甚至我都不是科班出身的，纯用爱发电。阁下要是真需要有个地方宣泄情绪，倒是可以考虑发邮件给我，还请您尽量不要在此让大家烦心。

**Comment by amalgame21** [comment]
v3.2.9 is working perfectly fine for me.
v3.2.10 is buggy.
In v3.2.11, the only problem for me is the duplicated `return` key registered in `termux` app. Others are working fine. Sometime it may crash in first launch, I do not know why. I think the developers are working on it.

Just stick to v3.2.9 or before if you want the stability.
I think the developers already explained the situation to you in #901. No need to press him so much.

**Comment by WhiredPlanck** [comment]
@amalgame21 Thanks for your feedback.

**Comment by WhiredPlanck** [comment]
@4SM 同文已推出 [3.2.18 版本](https://github.com/osfans/trime/releases/tag/v3.2.18)和[每夜版](https://github.com/osfans/trime/releases/tag/nightly)，诚邀您进行体验。
