### ISSUE TITLE
黑莓priv 来回滑几次就提示输入法停止运行了

### ISSUE THREAD

**Issue by yueduz** [osfans/trime#98]
还有只要滑出实体键盘不管有没有文本框都显示状态栏

**Comment by osfans** [comment]
狀態欄的問題轉 #101

**Comment by yueduz** [comment]
我下载了你发给我的新程序，这个问题也没有再出现了。

Osfans notifications@github.com于2016年8月17日周三 20:39写道：

**Comment by osfans** [comment]
好，所以有可能你上次用的是5月份的版本。那先關了，發現再開。
