### ISSUE TITLE
opencc 文件不能生效

### ISSUE THREAD

**Issue by orbitoo** [osfans/trime#980]
我需要补充 emoji 的输入, 我找到了 rime-emoji 的仓库, 但它提供的文件是繁体字的.
我用了 opencc 的库来将文本转化成简体的, 这样生成的文件在小狼毫和中文输入法上都能正常工作, 但在 trime 上不生效.

 - Device: [Redmi K50U]
 - OS: [MIUI 14 / Android 13]
 - Theme: [单静]
 - Version: [3.2.11]
 - Build info: 
```
Builder: Commit CI
Build Time: 2023-03-25 12:51:21 UTC
Build Version Name: v3.2.11-63-gf2156336
Git Hash: f2156336
Git Branch: develop
Git Repo: https://github.com/osfans/trime
```

附上转换后的文件.

[emoji_category_cn.txt](https://github.com/osfans/trime/files/11077413/emoji_category_cn.txt)

[emoji_word_cn.txt](https://github.com/osfans/trime/files/11077412/emoji_word_cn.txt)

我发现原版的换行是 LF 而非 CRLF, 但我修改了换行符之后依然不生效.

**Comment by WhiredPlanck** [comment]
@orbitoo 和 #960 一样的问题，是因为 OpenCC 的词典没机会被部署，所以没起效。已在 f215633 修复。

**Comment by orbitoo** [comment]
我使用了action里的最新版本，但问题依然存在，在部署时会发生闪退，请再确认bug是否正确修复?

**Comment by wxyzh** [comment]
@orbitoo opencc里是不是有不相关或者格式错误的文件？另外部署后，输入功能是否正常？

**Comment by orbitoo** [comment]
> @orbitoo opencc里是不是有不相关或者格式错误的文件？另外部署后，输入功能是否正常？

我确定文件没问题, 在小狼毫和中文输入法上均能部署成功.

我现在的解决方法是: 先用中文输入法部署, 然后把编译生成的 ocd 文件拷贝到 trime 文件目录, 然后把 json 文件里关联的文件类型改成 ocd, 现在已经可以正常使用了, 但输入法不能把 txt 文件编译成 ocd2 的问题仍旧存在, 在上次的版本中并未正确修复.
