### ISSUE TITLE
展开候选列表时有概率崩溃

### ISSUE THREAD

**Issue by Wenti-D** [osfans/trime#983]
**Describe the bug**
我将「每页候选词数量」设置为「不超出候选栏」，于是在输入时候选栏就多了个展开候选的按钮，点了会跳到名为「候选」的液态键盘，但在进入「候选」的时候有概率崩溃。

**To Reproduce**
如前文所述。

**Expected behavior**
别崩就行。

**Log**
[com.osfans.trime-2023-03-30T06_42_54Z.txt](https://github.com/osfans/trime/files/11111849/com.osfans.trime-2023-03-30T06_42_54Z.txt)

**Screenshots**
没有。

**Smartphone:**
 - Device: HUAWEI P40 Pro
 - OS: Harmony OS 3 / Android 12
 - Theme: [星天](https://github.com/Wenti-D/Astralwelkin)
 - Version: 3.2.12 dev
 - Build info: 
   ```
   Builder: Windy Deng
   Build Time: 2023-03-26 05:22:58 UTC
   Build Version Name: v3.2.11-63-gf2156336
   Git Hash: f2156336
   Git Branch: develop
   Git Repo:  https://github.com/osfans/trime.git
   ```
**Additional context**
无。

**Comment by WhiredPlanck** [comment]
候选列表这部分写的不是特别理想，但是现在积重难返，有点不好修。

**Comment by wxyzh** [comment]
对于候选栏，我更期望是循序滚动，上屏后复位到最前面。

**Comment by Wenti-D** [comment]
> 对于候选栏，我更期望是循序滚动，上屏后复位到最前面。

循序滚动是什么形式（

**Comment by wxyzh** [comment]
> > 对于候选栏，我更期望是循序滚动，上屏后复位到最前面。
> 
> 循序滚动是什么形式（

不用翻页按钮，一直向右滑动

**Comment by WhiredPlanck** [comment]
请看新版本有无此问题。Please take a look for new version.
每夜版/Nigntly Build：https://github.com/osfans/trime/releases/tag/nightly

**Comment by Wenti-D** [comment]
> 请看新版本有无此问题。Please take a look for new version. 每夜版/Nigntly Build：https://github.com/osfans/trime/releases/tag/nightly

目前未有再现，不过似乎候选展开的速度慢了一些。
