### ISSUE TITLE
chore(ci): replace cache check file #180 版本 闪退

### ISSUE THREAD

**Issue by tao659** [osfans/trime#985]
**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi 12pro ]
 - OS: [e.g. Android 12]
 - Theme: [e.g. Tongwenfeng]
 - Version: [chore(ci): replace cache check file #180 版本]
 - Build info: 
 
安装完 授权存储权限
启用 并 选用同文输入法
进入程序主界面
此时点击任意菜单都会闪退

选中编辑框后也无法弹出键盘

**Comment by wxyzh** [comment]
可能是CI 的cache 有问题。
@tao659  可以尝试使用https://github.com/WhiredPlanck/trime-new/actions/runs/4566392904 的产物。
@Bambooin 麻烦帮忙删除 Actions的cache 并重新运行下，我再看下cache的计算是否符合预期。

**Comment by Bambooin** [comment]
Done
