### ISSUE TITLE
priv 实体键盘回车不能编码上屏

### ISSUE THREAD

**Issue by yueduz** [osfans/trime#99]
屏幕键盘确可以

**Comment by osfans** [comment]
懷疑是回車鍵的keycode不同，可以看log中的Trime Rime相關信息嗎？

**Comment by yueduz** [comment]
不知道怎么看

Osfans notifications@github.com于2016年8月17日周三 20:37写道：

**Comment by osfans** [comment]
我好像用模擬鍵盤試驗出來了

**Comment by yueduz** [comment]
期待更新

Osfans notifications@github.com于2016年8月17日周三 20:45写道：

**Comment by osfans** [comment]
放release裏，還是放哪裏呢？你有在羣裏嗎？

**Comment by osfans** [comment]
只有Enter有問題吧？

**Comment by osfans** [comment]
請使用如下驗證： https://github.com/osfans/trime/releases/download/v3.0-beta2/trime-20160817.apk

**Comment by yueduz** [comment]
非常感谢 已经可以正常回车上屏了。还有另外一个问题我也反馈过，只要滑开实体键盘，没有聚焦文本框也会显示输入法状态栏，比如桌面

Osfans notifications@github.com于2016年8月17日周三 21:05写道：
