### ISSUE TITLE
The keyboard is too large that i cannot input When playing game

### ISSUE THREAD

**Issue by zjsxwc** [osfans/trime#992]
**Describe the bug**
玩王者荣耀的时候，输入法太大了，右边几个按键都不能正常显示

**To Reproduce**
Steps to reproduce the bug:
打开王者荣耀，进行聊天，就能看到。

**Expected behavior**
键盘能够小一点，实在太大了

**Screenshots**
![rime-large-keyboard](https://user-images.githubusercontent.com/3849577/230855555-45fbb05f-7ebf-4f5d-aaad-37c164b20271.png)

**Smartphone:**
 - Device: [Redmi note9 pro]
 - OS: [Android 12  MIUI 13.0.15]
 - Theme: [Tongwenfeng]
 - Version: [3.2.11]

**Comment by amalgame21** [comment]
Keyboard height can be adjusted.
Are you using tongwenfeng theme `tongwenfeng.trime.yaml`？

https://github.com/osfans/trime/blob/ba7aff0281149ae0631e0feaa21ffcc0a5307172/app/src/main/assets/rime/tongwenfeng.trime.yaml#L82L83

The fist line represent the portrait keyboard height.
The second line represent the landscape keyboard height, which is the line you want to adjust.
DO NOT directly edit the `tongwenfeng.trime.yaml` file.
Instead, you should create a `tongwenfeng.trime.custom.yaml` inside the `rime` user directory

example of `tongwenfeng.trime.custom.yaml`:
```
patch:
  "style/keyboard_height_land": 130 #锁定横屏下键盘高度，避免切换时键盘高度变化而造成闪烁
```

After that, inside the `trime` app, select "Theme & Color" => "Theme" => "select (tonwenfeng) again"
and your keyboard height should be changed.

Reference
https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3

**Comment by zjsxwc** [comment]
> Keyboard height can be adjusted. Are you using tongwenfeng theme `tongwenfeng.trime.yaml`？
> 
> https://github.com/osfans/trime/blob/ba7aff0281149ae0631e0feaa21ffcc0a5307172/app/src/main/assets/rime/tongwenfeng.trime.yaml#L82L83
> 
> The fist line represent the portrait keyboard height. The second line represent the landscape keyboard height, which is the line you want to adjust. DO NOT directly edit the `tongwenfeng.trime.yaml` file. Instead, you should create a `tongwenfeng.trime.custom.yaml` inside the `rime` user directory
> 
> example of `tongwenfeng.trime.custom.yaml`:
> 
> ```
> patch:
>   "style/keyboard_height_land": 130 #锁定横屏下键盘高度，避免切换时键盘高度变化而造成闪烁
> ```
> 
> After that, inside the `trime` app, select "Theme & Color" => "Theme" => "select (tonwenfeng) again" and your keyboard height should be changed.
> 
> Reference https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3


It is also the width proplem, not only heigth.
是宽度问题，不单单是高度问题，你看这个p键，我还怎么按啊

![Screenshot_2023-04-23-10-54-40-183_com android browser](https://user-images.githubusercontent.com/3849577/233817179-d08d084b-2a7f-4c60-9920-aaee9ee89ab0.jpg)

**Comment by zjsxwc** [comment]
加了个
  "style/keyboard_padding_land": 80
能用，就是丑了点
